### ISSUE TITLE
kops-controller cannot access S3 in GovCloud us-gov-west-1 region

### ISSUE THREAD

**Issue by lazzarello** [kubernetes/kops#10012]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.18.0-beta.1 (git-ec8022b352)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-29T18:29:22Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

Amazon Web Services GovCloud.

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Run kops-controller in region us-gov-west-1.

**5. What happened after the commands executed?**

kops-controller fails to apply nodeLabels, making instance groups non-functional, among other things.

After finding [this commit](https://github.com/kubernetes/kops/commit/93f0b914cf73785fba7ee65218e4fe02d3ee7f8b) I determined that the DaemonSet for kops-controller needed the environment variable AWS_REGION to operate correctly in the this region. The author notes that a problematic region is cn-north-1, which also has differences accessing S3.

**6. What did you expect to happen?**

The nodeLabels to be applied without manually editing the DaemonSet.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: dev.ops
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops/dev.ops
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    - instanceGroup: master-us-gov-west-1b
      name: b
    - instanceGroup: master-us-gov-west-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    - instanceGroup: master-us-gov-west-1b
      name: b
    - instanceGroup: master-us-gov-west-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.0
  masterPublicName: api.dev.ops
  networkCIDR: 10.194.0.0/16
  networkID: vpc-049283722348d3555
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.194.0.0/19
    id: subnet-0cd9e25c90879ad97
    name: us-gov-west-1a
    type: Private
    zone: us-gov-west-1a
  - cidr: 10.194.64.0/19
    id: subnet-041fe76d52cff26a0
    name: us-gov-west-1b
    type: Private
    zone: us-gov-west-1b
  - cidr: 10.194.128.0/19
    id: subnet-0675fa3f5637b3b83
    name: us-gov-west-1c
    type: Private
    zone: us-gov-west-1c
  - cidr: 10.194.192.0/22
    id: subnet-0faa5c268899dd758
    name: utility-us-gov-west-1a
    type: Utility
    zone: us-gov-west-1a
  - cidr: 10.194.196.0/22
    id: subnet-0c3ebbb202afbc33d
    name: utility-us-gov-west-1b
    type: Utility
    zone: us-gov-west-1b
  - cidr: 10.194.200.0/22
    id: subnet-0c32765ed9c7dad32
    name: utility-us-gov-west-1c
    type: Utility
    zone: us-gov-west-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

Relevant log lines. I'm not sure what the best fix for this is long-term. I know it's not adding an env var to the DaemonSet manifest.

```
{"log":"I1002 03:51:52.813889       1 s3context.go:170] defaulting region to \"us-east-1\"\n","stream":"stderr","time":"2020-10-02T03:51:52.814029798Z"}
{"log":"I1002 03:51:53.187722       1 s3context.go:191] unable to get bucket location from region \"us-east-1\"; scanning all regions: InvalidToken: The provided token is malformed or otherwise invalid.\n","stream":"stderr","time":"2020-10-02T03:51:53.188339497Z"}
{"log":"\u0009status code: 400, request id: 8BEC08909D45D4EB, host id: baVntVW0+NjFvnLO19QgxtUYP+wq7dVKJd7co+VEbecbV9DviZSdqLCZ7aVJ2UAPnNCshwrrdlU=\n","stream":"stderr","time":"2020-10-02T03:51:53.188406616Z"}
{"log":"E1002 03:51:53.478285       1 controller.go:258] controller-runtime/controller \"msg\"=\"Reconciler error\" \"error\"=\"unable to load cluster object for node ip-10-194-131-199.us-gov-west-1.compute.internal: error loading Cluster \\\"s3://kops/dev.ops/cluster.spec\\\": Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials\\n\\tstatus code: 401, request id: 265b3afc-95e5-4ae2-b353-6f36ecb77c48\"  \"controller\"=\"node\" \"request\"={\"Namespace\":\"\",\"Name\":\"ip-10-194-131-199.us-gov-west-1.compute.internal\"}\n","stream":"stderr","time":"2020-10-02T03:51:53.478474151Z"}
{"log":"I1002 03:51:54.478694       1 s3context.go:325] unable to read /sys/devices/virtual/dmi/id/product_uuid, assuming not running on EC2: open /sys/devices/virtual/dmi/id/product_uuid: permission denied\n","stream":"stderr","time":"2020-10-02T03:51:54.479315966Z"}
{"log":"I1002 03:51:54.478730       1 s3context.go:170] defaulting region to \"us-east-1\"\n","stream":"stderr","time":"2020-10-02T03:51:54.479354032Z"}
{"log":"I1002 03:51:54.768343       1 s3context.go:191] unable to get bucket location from region \"us-east-1\"; scanning all regions: InvalidToken: The provided token is malformed or otherwise invalid.\n","stream":"stderr","time":"2020-10-02T03:51:54.768701463Z"}
```
