### ISSUE TITLE
additionalUserData runs before docker has been installed

### ISSUE THREAD

**Issue by nehzata** [kubernetes/kops#10070]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.18.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```yaml
  additionalUserData:
  - name: initialise.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      set -x
      sudo apt-get install -y git
      sudo update-alternatives --set editor /usr/bin/vim.tiny
      sudo adduser --quiet --shell `which git-shell` --disabled-password --gecos "" git
      sudo usermod -aG docker git
```

**5. What happened after the commands executed?**
the last line adding user `git` to the `docker` group fails because docker hasn't been installed yet..

i get the error: `usermod: group 'docker' does not exist`

**6. What did you expect to happen?**
the `git` user to get added to `docker` group

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

relevant section of cluster manifest... everything else is default and/or not relevant
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8.mydomain.com
  name: master-ap-southeast-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-2a
  role: Master
  rootVolumeSize: 20
  subnets:
  - ap-southeast-2a
  additionalUserData:
  - name: initialise.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      set -x
      sudo apt-get install -y git
      sudo update-alternatives --set editor /usr/bin/vim.tiny 
      sudo adduser --quiet --shell `which git-shell` --disabled-password --gecos "" git
      sudo usermod -aG docker git
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
+ sudo update-alternatives --set editor /usr/bin/vim.tiny
update-alternatives: using /usr/bin/vim.tiny to provide /usr/bin/editor (editor) in manual mode
+ which git-shell
+ sudo adduser --quiet --shell /usr/bin/git-shell --disabled-password --gecos  git
+ sudo usermod -aG docker git
usermod: group 'docker' does not exist
```

**9. Anything else do we need to know?**
