### ISSUE TITLE
Worker node is not joining the cluster because Unable to find image 'protokube:1.18.1' locally

### ISSUE THREAD

**Issue by atam003** [kubernetes/kops#10085]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.18

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11

**3. What cloud provider are you using?
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Provide the kops hook image i.e. nividia-device-plugin after that worker node fails to join cluster

**5. What happened after the commands executed?**
worker node fails to join cluster

**6. What did you expect to happen?**
Cluster should be up

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2020-09-27T23:41:29Z
  name: atam-cluster.k8s.local
spec:
  cloudLabels:
    "k8s.io/cluster-autoscaler/enabled": ""
    "k8s.io/cluster-autoscaler/atam-cluster.k8s.local": ""
  additionalPolicies:
    node:  |
     [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
              ],
            "Resource": [
                  "arn:aws:s3:::atagrawal002/standalone/log/*" 
             ]
        }
     ]

    master:  |
     [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
              ],
            "Resource": [
                  "arn:aws:s3:::atagrawal002/standalone/log/*" 
             ]
        }
     ]

   
  kubeScheduler:
    logLevel: 2
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  kubelet:
   anonymousAuth: false
   nodeStatusUpdateFrequency: 4s
  kubeControllerManager:
   nodeMonitorPeriod: 2s
   podEvictionTimeout: 30s
   nodeMonitorGracePeriod: 30s
  cloudProvider: aws
  configBase: s3://atagrawal002/standalone/k8s-infa/atam-cluster.k8s.local/k8s-state-store/atam-cluster.k8s.local/
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-1b0
      name: a0
    
    enableEtcdTLS: true
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-1b0
      name: a0
    
    enableEtcdTLS: true
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 207.207.12.3/32
  kubernetesVersion: 1.11.5
  masterPublicName: api.atam-cluster.k8s.local
  networkCIDR: 172.20.0.0/16  
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 207.207.12.3/32
  sshPort: 22
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-1b
    type: Public
    zone: us-west-1b
  - cidr: 172.20.64.0/19
    name: us-west-1c
    type: Public
    zone: us-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2020-09-27T23:41:29Z
  labels:
    kops.k8s.io/cluster: atam-cluster.k8s.local
  name: master-us-west-1b0
spec:  
  cloudLabels:
    "k8s.io/cluster-autoscaler/enabled": ""
    "k8s.io/cluster-autoscaler/atam-cluster.k8s.local": ""
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-1b0
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-1b
  additionalUserData:
  - name: init-user-script.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "success" | tee infa-success 

  - name: upload-user-script-log.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      instance_id=$(curl http://169.254.169.254/latest/meta-data/instance-id) 
      unix_time=$(date '+%s') 
      cloud_init_log_file_name=$instance_id"-cloud-init-"$unix_time.log 
      aws s3 cp /var/log/cloud-init.log s3://atagrawal002/standalone/log/ClusterLogs/atam-cluster.k8s.local/1601250089104/$instance_id/$cloud_init_log_file_name
 
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2020-09-27T23:41:29Z
  labels:
    kops.k8s.io/cluster: atam-cluster.k8s.local
  name: nodes
spec:
  cloudLabels:
    "k8s.io/cluster-autoscaler/enabled": ""
    "k8s.io/cluster-autoscaler/atam-cluster.k8s.local": ""
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  hooks:
  - execContainer:
      image: atagrawal/nvidia-device-plugin:0.1.0-cuda10.1
  machineType: g4dn.xlarge
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-1b
  - us-west-1c
  additionalUserData:
  - name: init-user-script.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "success" | tee infa-success 

  - name: upload-user-script-log.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      instance_id=$(curl http://169.254.169.254/latest/meta-data/instance-id) 
      unix_time=$(date '+%s') 
      cloud_init_log_file_name=$instance_id"-cloud-init-"$unix_time.log 
      aws s3 cp /var/log/cloud-init.log s3://atagrawal002/standalone/log/ClusterLogs/atam-cluster.k8s.local/1601250089104/$instance_id/$cloud_init_log_file_name
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
After terminating the node. for the new node, it works fine. Facing this issue since yesterday i.e. 21st Oct 2020.
Please refer attached daemon log
[daemon.log](https://github.com/kubernetes/kops/files/5427393/daemon.log)
