### ISSUE TITLE
Cluster not validated when cilium.enablePrometheusMetrics is set to true

### ISSUE THREAD

**Issue by linecolumn** [kubernetes/kops#10081]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.19.0-alpha.5 (git-921f3e7109a4871ec1cb0b0e512785533a24dbce)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.18.9

**3. What cloud provider are you using?**

AWS

I'm testing KOPS 1.19 alpha5 and cluster is not validated when I set enablePrometheusMetrics under cilium sections:

```
  networking:
    cilium:
       enablePrometheusMetrics: true
```

As soon as I remove `enablePrometheusMetrics` KOPS can validate cluster.

I'm generating Terraform file(s) and then apply it for cluster creation.

Terraform v0.12.24

**Comment by olemarkus** [comment]
Hi,

Can you please follow the issue template here: https://github.com/kubernetes/kops/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

In particular, we would need to know what validation errors you are getting.

**Comment by linecolumn** [comment]
Here are addition information.

Validating cluster test2.redacted.com

```
INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
test-nodes		Node	t3.medium	1	7	eu-central-1a
master-eu-central-1a	Master	t3.medium	1	1	eu-central-1a
test2-nodes		Node	t3.medium	1	7	eu-central-1a
spot-ig			Node	t3.medium	1	3	eu-central-1a

NODE STATUS
NAME						ROLE	READY
ip-172-17-35-232.eu-central-1.compute.internal	node	False
ip-172-17-37-37.eu-central-1.compute.internal	master	False
ip-172-17-42-176.eu-central-1.compute.internal	node	False
ip-172-17-51-31.eu-central-1.compute.internal	node	False

VALIDATION ERRORS
KIND	NAME						MESSAGE
Node	ip-172-17-35-232.eu-central-1.compute.internal	node "ip-172-17-35-232.eu-central-1.compute.internal" is not ready
Node	ip-172-17-37-37.eu-central-1.compute.internal	master "ip-172-17-37-37.eu-central-1.compute.internal" is not ready
Node	ip-172-17-42-176.eu-central-1.compute.internal	node "ip-172-17-42-176.eu-central-1.compute.internal" is not ready
Node	ip-172-17-51-31.eu-central-1.compute.internal	node "ip-172-17-51-31.eu-central-1.compute.internal" is not ready
Pod	kube-system/cilium-7d86r			system-node-critical pod "cilium-7d86r" is pending
Pod	kube-system/cilium-operator-599dd6875b-6d2q7	system-cluster-critical pod "cilium-operator-599dd6875b-6d2q7" is pending
Pod	kube-system/cilium-p7gvf			system-node-critical pod "cilium-p7gvf" is pending
Pod	kube-system/cilium-qs4tb			system-node-critical pod "cilium-qs4tb" is pending
Pod	kube-system/cilium-xg5bm			system-node-critical pod "cilium-xg5bm" is pending
Pod	kube-system/coredns-579dc57f59-kptkc		system-cluster-critical pod "coredns-579dc57f59-kptkc" is pending
Pod	kube-system/coredns-autoscaler-6cc7676775-x4nkc	system-cluster-critical pod "coredns-autoscaler-6cc7676775-x4nkc" is pending
Validation Failed

Validation failed: cluster not yet healthy
```

cluster yaml:

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-10-23T20:47:01Z"
  name: test2.redacted.com
spec:
  additionalPolicies:
    node: "[\n  {\n    \"Action\": [\n        \"autoscaling:DescribeAutoScalingGroups\",\n        \"autoscaling:DescribeAutoScalingInstances\",\n        \"autoscaling:DescribeLaunchConfigurations\",\n        \"autoscaling:DescribeTags\",\n        \"autoscaling:SetDesiredCapacity\",\n        \"autoscaling:TerminateInstanceInAutoScalingGroup\",\n        \"ec2:DescribeLaunchTemplateVersions\"\n    ],\n    \"Resource\": \"*\",\n    \"Effect\": \"Allow\"\n  }\n] \n"
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://test-bucket/test2.redacted.com
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:14001
    name: main
    version: 3.4.3
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:14002
    name: events
    version: 3.4.3
  externalDns:
    watchIngress: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    maxRequestsInflight: 1000
    serviceNodePortRange: 30000-33000
  kubeDNS:
    nodeLocalDNS:
      enabled: true
    provider: CoreDNS
  kubeProxy:
    enabled: false
  kubelet:
    allowedUnsafeSysctls:
    - net.ipv4.ip_forward
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.9
  masterPublicName: api.test2.redacted.com
  networkCIDR: 172.17.0.0/16
  networking:
    cilium:
      enableNodePort: true
      enablePrometheusMetrics: true
      enableRemoteNodeIdentity: true
      preallocateBPFMaps: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: ""
  subnets:
  - cidr: 172.17.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-23T20:47:01Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: test2.redacted.com
  name: test-nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423
  machineType: t3.medium
  maxSize: 7
  minSize: 1
  nodeLabels:
    test-node: "true"
    kops.k8s.io/instancegroup: test-nodes
    node-role.kubernetes.io/test: ""
    on-demand: "true"
  role: Node
  subnets:
  - eu-central-1a
  taints:
  - platform-test-nodes=true:NoSchedule
  - on-demand=true:PreferNoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-23T20:47:01Z"
  labels:
    kops.k8s.io/cluster: test2.redacted.com
  name: master-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-23T20:47:01Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: test2.redacted.com
  name: platform-nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423
  machineType: t3.medium
  maxSize: 7
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: test2-nodes
    on-demand: "true"
    test2-node: "true"
  role: Node
  subnets:
  - eu-central-1a
  taints:
  - test2-node=true:PreferNoSchedule
  - on-demand=true:PreferNoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-23T20:47:01Z"
  labels:
    kops.k8s.io/cluster: test2.redacted.com
  name: spot-ig
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label: ""
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423
  machineType: t3.medium
  maxPrice: "0.0400"
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: spot-ig
    on-demand: "false"
  role: Node
  subnets:
  - eu-central-1a
```

kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

As soon as I comment:

```       
       enablePrometheusMetrics: true
```

or change it to false cluster can be created and validated properly.
