### ISSUE TITLE
dns-controller multiples pods in NodeAffinity status

### ISSUE THREAD

**Issue by azman0101** [kubernetes/kops#10147]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```bash
kops-1.19.0-alpha.5 version
Version 1.19.0-alpha.5 (git-921f3e7109a4871ec1cb0b0e512785533a24dbce)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

create a cluster with this spec:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: test-cluster.aws.dummy-customer.fr
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Environment: dummy-cluster
  cloudProvider: aws
  configBase: s3://dummycustomer-kops-states-dummy-test-cluster/test-cluster.aws.dummy-customer.fr
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    bastion:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    master:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    node:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - XXXXXXXXX
  kubernetesVersion: 1.18.10
  masterPublicName: api.test-cluster.aws.dummy-customer.fr
  networkCIDR: 10.134.216.0/22
  networking:
    cilium:
      IPTablesRulesNoinstall: false
      autoDirectNodeRoutes: false
      bpfCTGlobalAnyMax: 0
      bpfCTGlobalTCPMax: 0
      clusterName: ""
      cniBinPath: ""
      enableNodePort: true
      enableRemoteNodeIdentity: false
      enableipv4: false
      enableipv6: false
      monitorAggregation: ""
      nodeInitBootstrapFile: ""
      preallocateBPFMaps: false
      reconfigureKubelet: false
      removeCbrBridge: false
      restartPods: false
      sidecarIstioProxyImage: ""
      toFqdnsEnablePoller: false
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - XXXXXXXXX
  subnets:
  - cidr: 10.134.216.128/25
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.134.217.0/25
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 10.134.217.128/25
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 10.134.216.0/28
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 10.134.216.16/28
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 10.134.216.32/28
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**5. What happened after the commands executed?**

```bash
kubectl get deployment -n kube-system dns-controller
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
dns-controller   1/1     1            1           20m
```

A lot of dns-controller pods has been created during cluster initialization but can't be scheduled because of Predicate NodeAffinity.

```bash
kubectl get pod -A
NAMESPACE           NAME                                                                      READY   STATUS         RESTARTS   AGE
cilium-monitoring   grafana-54dbdc987-z4dtd                                                   1/1     Running        0          52s
cilium-monitoring   prometheus-6ff848df8b-lk7bn                                               1/1     Running        0          52s
kube-system         cilium-6jwdk                                                              1/1     Running        1          12m
kube-system         cilium-hk7jp                                                              1/1     Running        0          11m
kube-system         cilium-lblr8                                                              1/1     Running        0          12m
kube-system         cilium-operator-67cb784f66-sb5dd                                          1/1     Running        0          12m
kube-system         cilium-rkqzk                                                              1/1     Running        0          11m
kube-system         cilium-wb5pk                                                              1/1     Running        0          12m
kube-system         cilium-zr7gv                                                              1/1     Running        0          11m
kube-system         dns-controller-84d645665c-48pz7                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-4f2pr                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-4fjbn                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-4sh5r                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-55jbg                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-7j22m                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-8nsgv                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-94bw8                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-bpsv7                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-d2jrt                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-d5kgf                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-drt2z                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-gkq66                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-hgf5s                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-hrtw9                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-l24qh                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-mntz9                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-mzckq                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-nkjjb                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-p8th9                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-qdf7j                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-qszjf                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-qxng7                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-qxvpx                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-t8sff                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-tdtzx                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-tp7j7                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-tzndc                                           1/1     Running        2          12m
kube-system         dns-controller-84d645665c-tzq5s                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-wc9dv                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-xsgk5                                           0/1     NodeAffinity   0          12m
kube-system         dns-controller-84d645665c-zsp9n                                           0/1     NodeAffinity   0          12m
kube-system         etcd-manager-events-ip-10-134-216-182.eu-central-1.compute.internal       1/1     Running        0          11m
kube-system         etcd-manager-events-ip-10-134-217-102.eu-central-1.compute.internal       1/1     Running        0          11m
kube-system         etcd-manager-events-ip-10-134-217-226.eu-central-1.compute.internal       1/1     Running        0          11m
kube-system         etcd-manager-main-ip-10-134-216-182.eu-central-1.compute.internal         1/1     Running        0          11m
kube-system         etcd-manager-main-ip-10-134-217-102.eu-central-1.compute.internal         1/1     Running        0          11m
kube-system         etcd-manager-main-ip-10-134-217-226.eu-central-1.compute.internal         1/1     Running        0          12m
kube-system         kops-controller-cgw4n                                                     1/1     Running        2          12m
kube-system         kops-controller-qwgs7                                                     1/1     Running        2          11m
kube-system         kops-controller-zxnk8                                                     1/1     Running        1          11m
kube-system         kube-apiserver-ip-10-134-216-182.eu-central-1.compute.internal            2/2     Running        2          11m
kube-system         kube-apiserver-ip-10-134-217-102.eu-central-1.compute.internal            2/2     Running        2          12m
kube-system         kube-apiserver-ip-10-134-217-226.eu-central-1.compute.internal            2/2     Running        2          12m
kube-system         kube-controller-manager-ip-10-134-216-182.eu-central-1.compute.internal   1/1     Running        0          11m
kube-system         kube-controller-manager-ip-10-134-217-102.eu-central-1.compute.internal   1/1     Running        0          11m
kube-system         kube-controller-manager-ip-10-134-217-226.eu-central-1.compute.internal   1/1     Running        0          11m
kube-system         kube-dns-677d5df9b4-bh9ln                                                 3/3     Running        0          10m
kube-system         kube-dns-677d5df9b4-lxh8m                                                 3/3     Running        0          12m
kube-system         kube-dns-autoscaler-7f87957f46-6t5zk                                      1/1     Running        0          12m
kube-system         kube-scheduler-ip-10-134-216-182.eu-central-1.compute.internal            1/1     Running        0          12m
kube-system         kube-scheduler-ip-10-134-217-102.eu-central-1.compute.internal            1/1     Running        0          11m
kube-system         kube-scheduler-ip-10-134-217-226.eu-central-1.compute.internal            1/1     Running        0          11m
```

There are all managed by a single RS.

```bash
kubectl describe pod -n kube-system dns-controller-84d645665c-nkjjb
Name:                 dns-controller-84d645665c-nkjjb
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 ip-10-134-217-102.eu-central-1.compute.internal/
Start Time:           Sun, 01 Nov 2020 10:06:04 +0100
Labels:               k8s-addon=dns-controller.addons.k8s.io
                      k8s-app=dns-controller
                      pod-template-hash=84d645665c
                      version=v1.19.0-alpha.5
Annotations:          scheduler.alpha.kubernetes.io/critical-pod:
Status:               Failed
Reason:               NodeAffinity
Message:              Pod Predicate NodeAffinity failed
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/dns-controller-84d645665c
Containers:
  dns-controller:
    Image:      k8s.gcr.io/kops/dns-controller:1.19.0-alpha.5
    Port:       <none>
    Host Port:  <none>
    Command:
      /dns-controller
      --watch-ingress=false
      --dns=aws-route53
      --zone=*/ZWLHH4GED2TT4
      --zone=*/*
      -v=2
...
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:
Events:
  Type     Reason        Age   From                                                      Message
  ----     ------        ----  ----                                                      -------
  Normal   Scheduled     18m   default-scheduler                                         Successfully assigned kube-system/dns-controller-84d645665c-nkjjb to ip-10-134-217-102.eu-central-1.compute.internal
  Warning  NodeAffinity  18m   kubelet, ip-10-134-217-102.eu-central-1.compute.internal  Predicate NodeAffinity failed
```

```bash
kubectl describe rs -n kube-system dns-controller-84d645665c
Name:           dns-controller-84d645665c
Namespace:      kube-system
Selector:       k8s-app=dns-controller,pod-template-hash=84d645665c
Labels:         k8s-addon=dns-controller.addons.k8s.io
                k8s-app=dns-controller
                pod-template-hash=84d645665c
                version=v1.19.0-alpha.5
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 1
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/dns-controller
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 31 Failed
Pod Template:
  Labels:           k8s-addon=dns-controller.addons.k8s.io
                    k8s-app=dns-controller
                    pod-template-hash=84d645665c
                    version=v1.19.0-alpha.5
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod:
  Service Account:  dns-controller
  Containers:
   dns-controller:
    Image:      k8s.gcr.io/kops/dns-controller:1.19.0-alpha.5
    Port:       <none>
    Host Port:  <none>
    Command:
      /dns-controller
      --watch-ingress=false
      --dns=aws-route53
      --zone=*/ZWLHH4GED2TT4
      --zone=*/*
      -v=2
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      KUBERNETES_SERVICE_HOST:  127.0.0.1
    Mounts:                     <none>
  Volumes:                      <none>
  Priority Class Name:          system-cluster-critical
Events:
  Type     Reason            Age                 From                   Message
  ----     ------            ----                ----                   -------
  Warning  FailedCreate      19m                 replicaset-controller  Error creating: pods "dns-controller-84d645665c-" is forbidden: error looking up service account kube-system/dns-controller: serviceaccount "dns-controller" not found
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-hgf5s
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-qxvpx
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-4f2pr
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-d2jrt
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-8nsgv
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-nkjjb
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-xsgk5
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-qxng7
  Normal   SuccessfulCreate  19m                 replicaset-controller  Created pod: dns-controller-84d645665c-4fjbn
  Normal   SuccessfulCreate  18m (x15 over 19m)  replicaset-controller  (combined from similar events): Created pod: dns-controller-84d645665c-mzckq
```

**6. What did you expect to happen?**

Not having those dns-controller pods with the status NodeAffinity

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Already provided in point 4.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I've reproduce the problem twice with those cluster spec.

```bash 
kubectl get pod -A
NAMESPACE     NAME                                                                      READY   STATUS         RESTARTS   AGE
kube-system   cilium-4g9hl                                                              1/1     Running        0          67m
kube-system   cilium-d5tnb                                                              1/1     Running        0          67m
kube-system   cilium-fxgz6                                                              1/1     Running        0          65m
kube-system   cilium-jhsgt                                                              1/1     Running        0          65m
kube-system   cilium-operator-67cb784f66-vwnhp                                          1/1     Running        0          67m
kube-system   cilium-qv2jk                                                              1/1     Running        0          67m
kube-system   cilium-th9x9                                                              1/1     Running        0          65m
kube-system   dns-controller-84d645665c-2qxpv                                           0/1     NodeAffinity   0          66m
kube-system   dns-controller-84d645665c-cs4dq                                           0/1     NodeAffinity   0          66m
kube-system   dns-controller-84d645665c-k4bjb                                           0/1     NodeAffinity   0          66m
kube-system   dns-controller-84d645665c-nvd5v                                           0/1     NodeAffinity   0          66m
kube-system   dns-controller-84d645665c-p5mvt                                           0/1     NodeAffinity   0          67m
kube-system   dns-controller-84d645665c-qwrcs                                           1/1     Running        0          66m
kube-system   dns-controller-84d645665c-vhc58                                           0/1     NodeAffinity   0          66m
kube-system   dns-controller-84d645665c-vq4b7                                           0/1     NodeAffinity   0          66m
kube-system   dns-controller-84d645665c-z57n5                                           0/1     NodeAffinity   0          66m
kube-system   etcd-manager-events-ip-10-134-216-232.eu-central-1.compute.internal       1/1     Running        0          66m
```

IGs:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:59Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: bastions
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:55Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: master-eu-central-1a
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:55Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: master-eu-central-1b
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:55Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: master-eu-central-1c
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:55Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: nodes-eu-central-1a
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1a
  role: Node
  rootVolumeSize: 110
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:55Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: nodes-eu-central-1b
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1b
  role: Node
  rootVolumeSize: 110
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-01T15:53:55Z"
  labels:
    kops.k8s.io/cluster: test-cluster.aws.dummy-customer.fr
  name: nodes-eu-central-1c
spec:
  image: MY_ACCOUNT/dummy-customer-ubuntu-20.04-k8s-feat-test-cilium-1.18.10-kops-1.18.2-1604083199
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1c
  role: Node
  rootVolumeSize: 110
  subnets:
  - eu-central-1c
```

**Comment by rifelpet** [comment]
@azman0101 can you also post your instance groups? `kops get ig --name test-cluster.aws.dummy-customer.fr -o yaml`

**Comment by azman0101** [comment]
@rifelpet IGs added

**Comment by AgileOPS-IP** [comment]
The same thing happened to me. The instance type is t3.medium

**Comment by next-luisalbertoleon** [comment]
We've just had the same issue, we upgrade kops from 1.16.4 to 1.18.2, (1.17 in the middle)

```
$ kubectl get pods --all-namespaces  | grep -v Running
NAMESPACE                          NAME                                                                  READY   STATUS         RESTARTS   AGE
kube-system                        dns-controller-6ccdddd954-2mbgv                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-2mv5p                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-6pcvr                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-bmsld                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-fg6fz                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-gjhz4                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-hlz47                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-n6r5r                                       0/1     NodeAffinity   0          3h59m
kube-system                        dns-controller-6ccdddd954-t4c92                                       0/1     NodeAffinity   0          3h59m
```

The issue is that I added some params that affect master configuracion (etcd and kubeapiserver options) and when I do the rolling upgrade the problem is gone.

```
$ kubectl get pods --all-namespaces  | grep -v Running
NAMESPACE                          NAME                                                                  READY   STATUS    RESTARTS   AGE

$ kubectl get deployment -n kube-system dns-controller
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
dns-controller   1/1     1            1           2y69d

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```


regards,

**Comment by johngmyers** [comment]
What does the dns-controller Deployment? Do you have some mutating admission controller that is adding a `nodeAffinity`?

**Comment by igoratencompass** [comment]
Same just happened to me in a k8s cluster v1.18.12 I just created with kOps v1.18.2 

```
$ kc get pods -n kube-system -l k8s-addon=dns-controller.addons.k8s.io,k8s-app=dns-controller -o wide
NAME                             READY   STATUS         RESTARTS   AGE   IP             NODE                                         NOMINATED NODE   READINESS GATES
dns-controller-799bffddd-2dpmj   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-5jmdl   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-bps9h   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-br5xh   1/1     Running        0          19m   10.233.6.127   ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-f764t   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-gf2m5   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-j75sd   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-rz8dq   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
dns-controller-799bffddd-tpqjd   0/1     NodeAffinity   0          19m   <none>         ip-10-233-6-127.eu-west-1.compute.internal   <none>           <none>
```

As you can see the `dns-controller` pod is already running on the node where the rest of them are in `NodeAffinity` state. The node is a master node:

```
$ kc get nodes -o wide
NAME                                         STATUS   ROLES    AGE   VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
ip-10-233-6-108.eu-west-1.compute.internal   Ready    node     13m   v1.18.12   10.233.6.108   <none>        Ubuntu 20.04.1 LTS   5.4.0-1029-aws   docker://19.3.11
ip-10-233-6-127.eu-west-1.compute.internal   Ready    master   14m   v1.18.12   10.233.6.127   <none>        Ubuntu 20.04.1 LTS   5.4.0-1029-aws   docker://19.3.11
ip-10-233-7-122.eu-west-1.compute.internal   Ready    node     12m   v1.18.12   10.233.7.122   <none>        Ubuntu 20.04.1 LTS   5.4.0-1029-aws   docker://19.3.11
ip-10-233-7-96.eu-west-1.compute.internal    Ready    master   14m   v1.18.12   10.233.7.96    <none>        Ubuntu 20.04.1 LTS   5.4.0-1029-aws   docker://19.3.11
ip-10-233-8-30.eu-west-1.compute.internal    Ready    master   13m   v1.18.12   10.233.8.30    <none>        Ubuntu 20.04.1 LTS   5.4.0-1029-aws   docker://19.3.11
ip-10-233-8-74.eu-west-1.compute.internal    Ready    node     12m   v1.18.12   10.233.8.74    <none>        Ubuntu 20.04.1 LTS   5.4.0-1029-aws   docker://19.3.11
```

**Comment by supersaeyan** [comment]
> We've just had the same issue, we've upgraded kops from 1.16.4 to 1.18.2, (1.17 in the middle)
> 
> ```
> $ kubectl get pods --all-namespaces  | grep -v Running
> NAMESPACE                          NAME                                                                  READY   STATUS         RESTARTS   AGE
> kube-system                        dns-controller-6ccdddd954-2mbgv                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-2mv5p                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-6pcvr                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-bmsld                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-fg6fz                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-gjhz4                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-hlz47                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-n6r5r                                       0/1     NodeAffinity   0          3h59m
> kube-system                        dns-controller-6ccdddd954-t4c92                                       0/1     NodeAffinity   0          3h59m
> ```
> 
> The issue is that I added some params that affect master configuracion (etcd and kubeapiserver options) and when I do the rolling upgrade the problem is gone.
> 
> ```
> $ kubectl get pods --all-namespaces  | grep -v Running
> NAMESPACE                          NAME                                                                  READY   STATUS    RESTARTS   AGE
> 
> $ kubectl get deployment -n kube-system dns-controller
> NAME             READY   UP-TO-DATE   AVAILABLE   AGE
> dns-controller   1/1     1            1           2y69d
> 
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> regards,

Hi @next-luisalbertoleon, could you please mention the exact params you added that fixed the problem?

**Comment by next-luisalbertoleon** [comment]
Hi there!

I think the problem was because we have an ig node with taints and nodelabels:

```
spec:
  nodeLabels:
    key0: "value0"
  taints:
  - key1=value1:NoSchedule
```

then the dns-controller was not able to start, maybe your scenario is the same.

The issue went away when I made another change in the cluster, all nodes were upgraded and running in the cluster.
I added memory and cpu request for etcd main and event, and modify kubeapiserver maxRequestsInflight param but I didn't change anything related with dns-controller.


regards,
Luis
