### ISSUE TITLE
Kubernetes Deployment `k8s-ec2-srcdst` uses wrong CA Path on CentOS-like worker nodes

### ISSUE THREAD

**Issue by kitos9112** [kubernetes/kops#10150]
Hello,

I'm using the latest GA v1.18.2 version on Kops to bootstrap an AWS Kubernetes cluster on version 1.18.9 which employs Calico as CNI. The relevant piece of my cluster_config.yaml snippet would look like:

```yaml
(...)
  networking:
    calico:
      majorVersion: v3
      crossSubnet: true <<--- This triggers the creation of `k8s-ec2-srcdst` deployment as an K8S addon
      PrometheusMetricsEnabled: true
(...)
``` 

Everything seems to function quite well if I'm using the default debian-like AMI where all your automated tests run against, however, the problem arises when I use my company hardened AMIs based on Amazon Linux 2 as the volume named `ssl-certs` does not exist in any of the K8S worker nodes. From a `kubectl describe pods `

```
│   Warning  Failed     36m                    kubelet, ip--XXXXX-.eu-west-1.compute.internal  Error: failed to start container "k8s-ec2-srcdst": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"root ││ fs_linux.go:58: mounting \\\"/etc/ssl/certs/ca-certificates.crt\\\" to rootfs \\\"/var/lib/docker/overlay2/c9f2fc7d51f71e83a25a1327ee88cc7c0e815941c4560c0136cd22cdf44724fa/merged\\\" at \\\"/var/lib/docker/overlay2/c9f2fc7d51f71e83a25a1327ee88cc7c0e815941c4560c0136cd22cdf44724fa/merged/etc/ssl/certs/ca-certifica ││ tes.crt\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type   
```

In fact, taking a look at your source code [k8s-1.16.yaml.template](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template#L4224) the `path` variable points to a hardcoded value where the CA certificate bundles should be for Debian distributions only but neither for archlinux nor CentOS-like OS for example.

Although, the issue I've just described has a really simple fix I'm even willing to implement myself. I noticed you're using a `SSL_CERT_PATH` varible to pass this specific variable to the cluster-autoscaler addon, not sure this logic could be follow for the aforementioned deployment.

Cheers,
Marcos S.

**Comment by hakman** [comment]
@kitos9112 I think this could be easily fixed by mounting all the `/etc/ssl/certs`. Could you do a quick check?

**Comment by kitos9112** [comment]
@hakman Thanks for your reply. Yes, that's an easy fix and makes sense instead of adding more configuration overhead.

I've just tried editing the `deployment` spec in the same live cluster by mounting the whole directory as a _Directory_ type in the hostPath directive with successful results.

```yaml
# https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template#L4216
(...)
         volumeMounts:
            - name: ssl-certs
              mountPath: "/etc/ssl/certs"
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
            type: Directory
```

Do you want me to submit a PR with this small fix?
