### ISSUE TITLE
docker command not installed on Node

### ISSUE THREAD

**Issue by fvasco** [kubernetes/kops#10155]
**1. What `kops` version are you running?
`Version 1.18.2 (git-84495481e4)`

**2. What Kubernetes version are you running?
~~~
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
~~~

**3. What cloud provider are you using?**
AWS us-east-1

Unfortunately, we cannot provide a real reproducer, now a good report.
When an Ec2 instance has been started, it does not join the group as a Node.
Logging on in it using `ssh`, `kubelet` isn't started and `docker` command isn't unavailable on the command line (Ubuntu suggested some commands to install it).
This issue happened one time only, we waited 15 minutes before terminating the instance.

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: xxx
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx
  dnsZone: xxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesVersion: 1.18.10
  masterInternalName: k8s.internal.xxx
  masterPublicName: k8s.xxx
  networkCIDR: xxx/16
  networkID: vpc-5b74b93c
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets: xxx
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201014
  machineType: c5.large
  maxSize: 25
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - c5.large
    - c5d.large
    onDemandAboveBase: 20
    onDemandBase: 0
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1f
---
many others, unrelated to this issue...
```
