### ISSUE TITLE
Unable to attach externalPolicy to InstanceGroup

### ISSUE THREAD

**Issue by slashr** [kubernetes/kops#10203]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.2 (git-84495481e4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.18.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit cluster 
- Add under spec
```
  externalPolicies:
    nodes.test.example.com:
    - arn:aws:iam::123456789:policy/ALBIngressControllerIAMPolicy
```

**5. What happened after the commands executed?**
```
Will modify resources:
  IAMRolePolicy/node-policyoverride
  	ExternalPolicies    	 [arn:aws:iam::123456789:policy/ALBIngressControllerIAMPolicy] -> <nil>
  	Managed             	 true -> true
```
The policy is actually being removed from the Role.

**6. What did you expect to happen?**
Expected the policy specified to be attached to the Role

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I followed these instructions: https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#adding-external-policies

**Comment by hakman** [comment]
Hey @slashr, by any chance you are using this together with an existing IAM instance profile?
https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#use-existing-aws-instance-profiles

**Comment by slashr** [comment]
@hakman No, but I'm indeed using this together with additionalPolicies

https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#adding-external-policies

**Comment by hakman** [comment]
Could you add a minimal cluster spec to use for reproducing the issue? Thanks!

**Comment by slashr** [comment]
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-11-14T10:55:56Z"
  generation: 20
  name: test.example.com
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeTags",
                "route53:ListHostedZones",
                "route53:ListResourceRecordSets"
                    ],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "route53:ChangeResourceRecordSets"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/ZSE1234BX05"
            ]
        }
      ]
  api:
    loadBalancer:
      sslCertificate: arn:aws:acm:eu-central-1:123456789:certificate/69a29b41-0e66-4819-91d6
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    kubernetes.io/cluster/test.example.com: owned
  cloudProvider: aws
  configBase: s3://test-spw-state-store/test.example.com
  dnsZone: ZSE8PKL8DBX05
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    nodes:
    - arn:aws:iam::123456789:policy/ALBIngressControllerIAMPolicy
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    disableBasicAuth: false
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.6
  masterInternalName: api.internal.test.example.com
  masterPublicName: api.test.example.com
  networkCIDR: 172.64.0.0/16
  networkID: vpc-0c7f6a32351a429fd
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.64.16.0/22
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.64.20.0/22
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.64.8.0/23
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.64.12.0/23
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  topology:
    bastion:
      bastionPublicName: bastion.test.example.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-14T10:55:57Z"
  generation: 13
  labels:
    kops.k8s.io/cluster: test.example.com
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3.xlarge
  maxSize: 10
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - t3.xlarge
    - t2.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    KubeClusterAutoscaling: Enabled
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
```

Am I right in assuming that the `spec.externalPolicies` should be the name of the InstanceGroup and not the name of the IAM Role? Either I tried using both and the result was the same.
