### ISSUE TITLE
Question: ClusterAutoscaler addon not installed, what is missing?

### ISSUE THREAD

**Issue by djablonski-moia** [kubernetes/kops#10223]
kOps version: v1.19.0.-beta.1
K8s version: 1.18.9

I've added the cluster-autoscaler config to our cluster spec, as described in the [docs](https://kops.sigs.k8s.io/cluster_spec/#cluster-autoscaler), but when creating a new cluster or updating an existing cluster, nothing changes at all.

```yaml
spec:
  cluster:
    clusterAutoscaler:
      enabled: true
      skipNodesWithLocalStorage: false
      skipNodesWithSystemPods: true
```

It seems I'm missing something, but I can't figure out what. Can you give me a hint? Thanks in advance! 😄

**Comment by hakman** [comment]
I think the docs are wrong and should be just:
```yaml
spec:
  clusterAutoscaler:
    enabled: true
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: true
```
/cc @olemarkus
