### ISSUE TITLE
New storageclass kops-ssd-1-17 not present on upgraded clusters

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes/kops#10246]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.0 (git-698bf974d8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
# Updated kubernetesVersion in cluster.yaml
kops replace -f cluster.yaml
kops update cluster --yes
kops rolling-update cluster

**5. What happened after the commands executed?**
cluster upgraded fine to k8s 1.18

**6. What did you expect to happen?**
New storageclass kops-ssd-1-17 that was introduced would show up.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
https://gist.github.com/ryan-dyer-sp/90533f97521c92513f95784249b03401
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
From looking at the docker logs on the master I can see the following where it appears to not want to process the storage-aws channel as its not the latest
```
ov 16 16:02:59 ip-10-1-12-239 docker[6192]: I1116 16:02:59.318007    7028 channel_version.go:106] Checking existing channel: Version=1.15.1 Channel=s3://bucket/cluster/addons/bootstrap-channel.yaml Id=v1.7.0 ManifestHash=62705a596142e6cc283280e8aa973e51536994c5 compared to new channel: Version=1.15.0 Channel=s3://bucket/cluster/addons/bootstrap-channel.yaml Id=v1.15.0 ManifestHash=00cf6e46e25b736b2da93c6025ce482474d83904
Nov 16 16:02:59 ip-10-1-12-239 docker[6192]: I1116 16:02:59.318043    7028 channel_version.go:123] New Version is less then old
```
Relevant entries from bootstrap-channel.yaml
```
  - id: v1.15.0
    kubernetesVersion: '>=1.15.0'
    manifest: storage-aws.addons.k8s.io/v1.15.0.yaml
    manifestHash: 00cf6e46e25b736b2da93c6025ce482474d83904
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.0
  - id: v1.7.0
    kubernetesVersion: <1.15.0
    manifest: storage-aws.addons.k8s.io/v1.7.0.yaml
    manifestHash: 62705a596142e6cc283280e8aa973e51536994c5
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.0
```

**Comment by johngmyers** [comment]
What versions of kops has this cluster been on? It looks like it installed a version "1.15.1" of storage-aws, but I don't see that version in the handful of release branches I looked at.

**Comment by ryan-dyer-sp** [comment]
As our bucket is versioned I was able to find that back on Jan30`20 we ended up with the bootstrap which contains this version and ran with it until jul of this year.  Below is the file if it helps any
```
kind: Addons
metadata:
  creationTimestamp: null
  name: bootstrap
spec:
  addons:
  - manifest: core.addons.k8s.io/v1.4.0.yaml
    manifestHash: 3ffe9ac576f9eec72e2bdfbd2ea17d56d9b17b90
    name: core.addons.k8s.io
    selector:
      k8s-addon: core.addons.k8s.io
    version: 1.4.0
  - id: k8s-1.10.yaml
    kubernetesVersion: '>=1.10.0 <1.12.0'
    manifest: node-authorizer.addons.k8s.io/k8s-1.10.yaml
    manifestHash: 16ff343e1226ea2fc2fb2c6d9478021f555f1dee
    name: node-authorizer.addons.k8s.io
    selector:
      k8s-addon: node-authorizer.addons.k8s.io
    version: v0.0.4-kops.1
  - id: k8s-1.12.yaml
    kubernetesVersion: '>=1.12.0'
    manifest: node-authorizer.addons.k8s.io/k8s-1.12.yaml
    manifestHash: 589276a37007e34da9098f0d1eba7deeef864f98
    name: node-authorizer.addons.k8s.io
    selector:
      k8s-addon: node-authorizer.addons.k8s.io
    version: v0.0.4-kops.1
  - id: k8s-1.6
    kubernetesVersion: '>=1.6.0 <1.12.0'
    manifest: coredns.addons.k8s.io/k8s-1.6.yaml
    manifestHash: 64577bb328d1d16908f48a9fb91e1847d4625f5f
    name: coredns.addons.k8s.io
    selector:
      k8s-addon: coredns.addons.k8s.io
    version: 1.6.6-kops.1
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: coredns.addons.k8s.io/k8s-1.12.yaml
    manifestHash: a13799b731376680448ab65220dcd38155fe54de
    name: coredns.addons.k8s.io
    selector:
      k8s-addon: coredns.addons.k8s.io
    version: 1.6.6-kops.1
  - id: k8s-1.9
    kubernetesVersion: '>=1.9.0'
    manifest: kubelet-api.rbac.addons.k8s.io/k8s-1.9.yaml
    manifestHash: e1508d77cb4e527d7a2939babe36dc350dd83745
    name: kubelet-api.rbac.addons.k8s.io
    selector:
      k8s-addon: kubelet-api.rbac.addons.k8s.io
    version: v0.0.1
  - manifest: limit-range.addons.k8s.io/v1.5.0.yaml
    manifestHash: 2ea50e23f1a5aa41df3724630ac25173738cc90c
    name: limit-range.addons.k8s.io
    selector:
      k8s-addon: limit-range.addons.k8s.io
    version: 1.5.0
  - id: pre-k8s-1.6
    kubernetesVersion: <1.6.0
    manifest: dns-controller.addons.k8s.io/pre-k8s-1.6.yaml
    manifestHash: 25f0ad31fcf6f30aa1f19b54d1b672a8dad83fcf
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 1.15.1
  - id: k8s-1.6
    kubernetesVersion: '>=1.6.0 <1.12.0'
    manifest: dns-controller.addons.k8s.io/k8s-1.6.yaml
    manifestHash: 7f7c89f38ede18f475a3124d68e8af45a468a4dc
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 1.15.1
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: dns-controller.addons.k8s.io/k8s-1.12.yaml
    manifestHash: c988adb3783ef60483daa886e5d2879f12e7892a
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 1.15.1
  - id: v1.15.0
    kubernetesVersion: '>=1.15.0'
    manifest: storage-aws.addons.k8s.io/v1.15.0.yaml
    manifestHash: 23459f7be52d7c818dc060a8bcf5e3565bd87a7b
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.1
  - id: v1.7.0
    kubernetesVersion: '>=1.7.0 <1.15.0'
    manifest: storage-aws.addons.k8s.io/v1.7.0.yaml
    manifestHash: 62705a596142e6cc283280e8aa973e51536994c5
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.1
  - id: v1.6.0
    kubernetesVersion: <1.7.0
    manifest: storage-aws.addons.k8s.io/v1.6.0.yaml
    manifestHash: 7de4b2eb0521d669172038759c521418711d8266
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.1
  - id: k8s-1.7
    kubernetesVersion: '>=1.7.0 <1.8.0'
    manifest: networking.amazon-vpc-routed-eni/k8s-1.7.yaml
    manifestHash: 5a2322f76f2a249e18d4ad824385faa2595c06e2
    name: networking.amazon-vpc-routed-eni
    selector:
      role.kubernetes.io/networking: "1"
    version: 1.5.0-kops.1
  - id: k8s-1.8
    kubernetesVersion: '>=1.8.0 <1.10.0'
    manifest: networking.amazon-vpc-routed-eni/k8s-1.8.yaml
    manifestHash: 4147bcad535749c38755ac3a6e3a7719f161d1c9
    name: networking.amazon-vpc-routed-eni
    selector:
      role.kubernetes.io/networking: "1"
    version: 1.5.0-kops.1
  - id: k8s-1.10
    kubernetesVersion: '>=1.10.0 <1.12.0'
    manifest: networking.amazon-vpc-routed-eni/k8s-1.10.yaml
    manifestHash: 1b8473a758bce9aa6056ce64adc33cf24d90bb7b
    name: networking.amazon-vpc-routed-eni
    selector:
      role.kubernetes.io/networking: "1"
    version: 1.5.0-kops.1
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: networking.amazon-vpc-routed-eni/k8s-1.12.yaml
    manifestHash: f3f5a67d0dde7f709a78396c250f85cde19401cf
    name: networking.amazon-vpc-routed-eni
    selector:
      role.kubernetes.io/networking: "1"
    version: 1.5.0-kops.1
```
