### ISSUE TITLE
Addition of etcd metrics does not trigger rolling update

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes/kops#10252]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.18.0 (git-698bf974d8)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Added the etcd metrics(manager.env.**) to the cluster spec.
```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a-1
      name: a-1
      encryptedVolume: true
    - instanceGroup: master-us-east-1b-1
      name: b-1
      encryptedVolume: true
    - instanceGroup: master-us-east-1c-1
      name: c-1
      encryptedVolume: true
    name: main
    version: 3.3.10
    enableEtcdTLS: true
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:8081
      - name: ETCD_METRICS
        value: extensive
  - etcdMembers:
    - instanceGroup: master-us-east-1a-1
      name: a-1
      encryptedVolume: true
    - instanceGroup: master-us-east-1b-1
      name: b-1
      encryptedVolume: true
    - instanceGroup: master-us-east-1c-1
      name: c-1
      encryptedVolume: true
    name: events
    version: 3.3.10
    enableEtcdTLS: true
```

kops replace -f cluster.yaml
kops update cluster --yes
kops rolling-update cluster --yes

**5. What happened after the commands executed?**
Kops reported that masters were up to date and did not need to be rolled.

**6. What did you expect to happen?**
kops reports masters need to be rolled and does not require --force to update the masters.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
