### ISSUE TITLE
Can't generate terraform when using externalLoadBalancers in two IGs

### ISSUE THREAD

**Issue by kuzaxak** [kubernetes/kops#10268]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
kops version
Version 1.19.0-beta.1 (git-6fa37fc5bdc2eedd7f0c696dd8155ac267b310fd)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.18

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster --target=terraform  --out=update --yes`

Create two IG with externalLoadBalancers -> targetGroupArn

**5. What happened after the commands executed?**

Fatal error:

```
F1118 23:54:29.146441   64478 task.go:59] found duplicate tasks with name "TargetGroup/external-tg-0": *awstasks.TargetGroup {"Name":"external-tg-0","Lifecycle":null,"VPC":null,"Tags":null,"Port":null,"Protocol":null,"ARN":"arn:aws:elasticloadbalancing:eu-west-1:*******:targetgroup/nodes-ingress-http/55f391*******","Shared":true,"HealthyThreshold":null,"UnhealthyThreshold":null} and *awstasks.TargetGroup {"Name":"external-tg-0","Lifecycle":null,"VPC":null,"Tags":null,"Port":null,"Protocol":null,"ARN":"arn:aws:elasticloadbalancing:eu-west-1:*******:targetgroup/jenkins-nlb/dac3*******","Shared":true,"HealthyThreshold":null,"UnhealthyThreshold":null}
```

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-10-15T17:39:23Z"
  generation: 10
  name: %%%%%%%%
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://XXXXXXXX/%%%%%%%%
  dnsZone: %%%%%%%%
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Unit]
      Description=Download Heptio AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/aws-iam-authenticator
      ExecStart=/usr/bin/docker run --net=host --rm -v /srv/kubernetes/aws-iam-authenticator:/srv/kubernetes/aws-iam-authenticator quay.io/coreos/awscli@sha256:7b893bfb22ac582587798b011024f40871cd7424b9026595fd99c2b69492791d aws s3 cp --recursive s3://XXXXXXXX/%%%%%%%%/addons/authenticator /srv/kubernetes/aws-iam-authenticator/
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
    - PersistentVolumeClaimResize
    authenticationTokenWebhookConfigFile: /srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml
    featureGates:
      ExpandInUsePersistentVolumes: "true"
      ExpandPersistentVolumes: "true"
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    featureGates:
      ExpandInUsePersistentVolumes: "true"
      ExpandPersistentVolumes: "true"
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      ExpandInUsePersistentVolumes: "true"
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.12
  masterInternalName: api.internal.%%%%%%%%
  masterPublicName: api.%%%%%%%%
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.20.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.20.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  topology:
    bastion:
      bastionPublicName: bastion.%%%%%%%%
    dns:
      type: Public
    masters: private
    nodes: private
  updatePolicy: external

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-10-15T17:39:23Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: %%%%%%%%
  name: bastions
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-15T13:10:44Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: %%%%%%%%
  name: jenkins
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/%%%%%%%%: ""
    manager: asg
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:********:targetgroup/jenkins-nlb/dac350e01bd4fd16
  - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:********:targetgroup/open-vpn/2562c11a1f2d4d4
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: jenkins
    manager: asg
    spotinst.io/node-lifecycle: od
  role: Node
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-10-15T17:39:23Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: %%%%%%%%
  name: master-eu-west-1a
spec:
  externalLoadBalancers:
  - loadBalancerName: api-k8s-XXXXXXXX
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: t3.xlarge
  maxSize: 1
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-09-02T09:46:40Z"
  generation: 9
  labels:
    kops.k8s.io/cluster: %%%%%%%%
  name: odgroup
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/%%%%%%%%: ""
    manager: asg
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:********:targetgroup/nodes-ingress-http/55f391087e587b66
  - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:********:targetgroup/nodes-ingress-https/2891ec7cb06e9b57
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026
  machineType: m5.xlarge
  maxSize: 5
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: odgroup
    manager: asg
    spotinst.io/node-lifecycle: od
  role: Node
  rollingUpdate:
    maxUnavailable: 2
  subnets:
  - eu-west-1a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/kuzaxak/58170c13fe7a0c2c66a79b748b58556f

**9. Anything else do we need to know?**
