### ISSUE TITLE
control-plane node not labeled properly making kops-controller unschedulable

### ISSUE THREAD

**Issue by rendhalver** [kubernetes/kops#10300]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.2 (git-84495481e4)
I also tried this with kops 1.16.4 with the same result.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
#Update  cluster version to 1.16.x
kops update cluster $CLUSTER --yes
kops update cluster $CLUSTER
kops rolling-update cluster $CLUSTER --cloudonly --instance-group-roles=Master --yes

**5. What happened after the commands executed?**
The control-plane node was missing the labels that defined it as a control-plane and kops-controller was unschedulable so the labels couldn't be updated.
These were the only labels the control-plane node had. Yes we only run one in our clusters.
`beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-2,failure-domain.beta.kubernetes.io/zone=ap-southeast-2a,kubernetes.io/arch=amd64,kubernetes.io/hostname=awssydtst321,kubernetes.io/os=linux`

**6. What did you expect to happen?**
The contol-plane to be started properly.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: REDACTED
spec:
  additionalPolicies:
    master: |
      [
        {
            "Effect": "Allow",
            "Action": [
                "iam:Get*",
                "iam:List*"
            ],
            "Resource": "*"
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ListHostedZones",
            "route53:ListHostedZonesByName",
            "route53:ListResourceRecordSets"
          ],
          "Resource": [
            "*"
          ]
        },

        {
            "Effect": "Allow",
            "Action": "route53:GetChange",
            "Resource": "arn:aws:route53:::change/*"
        },

        {
            "Effect": "Allow",
            "Action": [
                "iam:Get*",
                "iam:List*"
            ],
            "Resource": "*"
        },

        {
          "Effect": "Allow",
          "Action": [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
            "logs:DescribeLogStreams"
          ],
          "Resource": [
            "arn:aws:logs:*:*:*"
          ]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://REDACTED/REDACTED
  dnsZone: REDACTED
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-2a
      name: a
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-2a
      name: a
    name: events
  hooks:
  - before:
    - kubelet.service
    manifest: |
      Type=oneshot
      ExecStart=/usr/local/bin/set-hostname awssydtst
  iam:
    legacy: false
  kubeAPIServer:
    admissionControl:
    - AlwaysPullImages
    - PersistentVolumeClaimResize
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/apiserver/audit.log
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
    terminatedPodGCThreshold: 10
  kubelet:
    anonymousAuth: false
    featureGates:
      ExpandPersistentVolumes: "true"
    hostnameOverride: '@hostname'
    streamingConnectionIdleTimeout: 5m0s
  kubernetesApiAccess:
  - 10.0.128.0/19
  - 10.0.0.0/17
  kubernetesVersion: 1.16.15
  masterInternalName: api.internal.REDACTED
  masterPublicName: api.REDACTED
  networkCIDR: 10.3.0.0/16
  networkID: vpc-REDACTED
  networking:
    canal: {}
  nonMasqueradeCIDR: 10.103.0.0/16
  sshAccess:
  - 10.0.128.0/19
  subnets:
  - cidr: 10.3.0.0/19
    egress: nat-REDACTED
    id: subnet-1c295c7b
    name: ap-southeast-2a
    type: Private
    zone: ap-southeast-2a
  - cidr: 10.3.64.0/19
    egress: nat-REDACTED
    id: subnet-REDACTED
    name: ap-southeast-2c
    type: Private
    zone: ap-southeast-2c
  - cidr: 10.3.128.0/21
    id: subnet-REDACTED
    name: utility-ap-southeast-2a
    type: Utility
    zone: ap-southeast-2a
  - cidr: 10.3.144.0/21
    id: subnet-REDACTED
    name: utility-ap-southeast-2c
    type: Utility
    zone: ap-southeast-2c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-23T00:59:08Z"
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-ap-southeast-2a
spec:
  associatePublicIp: false
  cloudLabels:
    App: kubernetes
    Env: tst
  image: REDACTED
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-2a
  role: Master
  subnets:
  - ap-southeast-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-11-23T00:59:08Z"
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  associatePublicIp: false
  cloudLabels:
    App: kubernetes
    Env: tst
    spot-enabled: "true"
  image: REDACTED
  machineType: t2.large
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-southeast-2a
  - ap-southeast-2c

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
As I mentioned above we only run one master node.
I am going to guess this is part of the cause for the problem.
We haven't had any problems with this setup until we upgraded to 1.16.
