### ISSUE TITLE
DNS Controller Remove InternalAPI

### ISSUE THREAD

**Issue by WoodProgrammer** [kubernetes/kops#10329]
Hi,

I have got a Kubernetes cluster deployed on 1.16.0 K8s version and components are routed to the internal load balancer. But when rolling-update command upgraded masters successfully, DNS-controller removes the internal-api load balancer record from Route53.
How can I fix this issue? 

Kops manifest file: 
```
  api:
    loadBalancer:
      type: Internal
      useForInternalApi: true
```

Thanks
