### ISSUE TITLE
Allow specification of public subnets in private topology mode

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1036]
**Problem:** 
When using kops to configure and launch a cluster into an existing VPC, kops creates all new subnets for k8s, regardless of what may already be there. 

We can do better for private topology. In private mode, kops existing behavior creates 2 new subnets per AZ, one public and one private. The public subnets are each allocated one new NAT gateway. This is redundant- If our VPC already has a public subnet, we can use this to host the ELBs for the API and bastion servers and also re-use the public subnet’s NAT gateway. This is economically relevant because the ELBs and NATs aren’t free. I also think reusing public subnets where applicable helps to simplify the VPC and this should also be relevant. 

**Proposal:** 
I propose that at time of cluster creation, we let the creator specify pre-existing public subnets that would be used to launch the ELBs for API and bastion (if used). Then kops would create the cluster and use these public subnets instead of creating it’s own. 

I envision the way this feature might work is to input the desired public subnets during  `kops edit cluster`  . 
Example current configuration screen for 2AZ subnetting (just relevant pieces):
```
      topology:
        masters: private
        nodes: private
      zones:
      - cidr: 172.20.32.0/19
        name: us-east-2a
        privateCIDR: 172.20.128.0/19
      - cidr: 172.20.64.0/19
        name: us-east-2b
        privateCIDR: 172.20.160.0/19

```

Example proposed configuration screen:
```
      topology:
        masters: private
        nodes: private
      zones:
      - cidr: 172.20.32.0/19
        name: us-east-2a
        privateCIDR: 172.20.128.0/19
      - cidr: 172.20.64.0/19
        name: us-east-2b
        privateCIDR: 172.20.160.0/19
    # If you already have public subnets with NAT gateways that you would like to use,
    # delete the zones declaration above and complete these options instead:
    #  - name: us-east-2a
    #      public-subnet-id: subnet-id1
    #      privateCIDR: UNALLOCATED_CIDR
    #  - name: us-east-2b
    #      public-subnet-id: subnet-id2
    #      privateCIDR: UNALLOCATED_CIDR

```
The user would fill in the subnets that they want to use which are located in their VPC. Since kops needs it’s own private subnets, we would maintain existing privateCIDR specifications and behavior. Any CIDR that would have worked in the original example would be fine for my case. Compared to “stock-kops”, this proposal leans much more on the user to know what’s going on and to make good choices. To this effect, I would want to ensure that the public subnets provided were real and had NAT gateways attached to them. 

Clarification via @jmound: 

> we should clarify what is meant by a public subnet, namely that it is one that is associated with a routing table with a route to the public internet such that the destination of 0.0.0.0/0 is an internet gateway

Thoughts? I think this is a little bit complicated in the `kops edit cluster` section but I don't think it's insurmountable and it's not likely to be attempted by someone using kops to create their first cluster.

CC @kris-nova @jmound
