### ISSUE TITLE
Cannot attach additionalPolicies to IAM role shared between instances groups

### ISSUE THREAD

**Issue by alefray** [kubernetes/kops#10362]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.18.2 (git-84495481e4)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops update cluster --yes --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges
```

To reproduce this issue:
1. create an empty IAMRole directly on AWS
2. create a cluster as follows:
- 2 node (or master) instances groups sharing the previous IAMRole
- specify an additionalPolicy for node (or master)

**5. What happened after the commands executed?**

The command ran successfully but silently ignored the IAM additionalPolicies section if the IAM Role is shared by multiple instance groups.

**6. What did you expect to happen?**

One of the two:
- The policy is created i.e. the IAM Role has an new inline IAM policy (prefixed additional-) with the content defined in `additionalPolicies.node`
- A Warning/Error message explicitly stating the configuration is ignored/skipped for some reason.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Here is a minimal example with:
- 2 Master instance groups:
  - master-eu-west-3a
  - master-eu-west-3b
- 2 Node instance groups:
  - nodes-eu-west-3a
  - nodes-eu-west-3b

```yaml
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{ .kopsClusterName }}
spec:
  additionalPolicies:
    node: |
      [
        {
            "Sid": "AllowKopsBucketAccess",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "{{ $.kmsKeyId }}"
        }
      ]
    master: |
      [
        {
            "Sid": "AllowKopsBucketAccess",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "{{ $.kmsKeyId }}"
        }
      ]

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .kopsClusterName }}
  name: master-eu-west-3a
spec:
  cloudLabels:
    kubernetes.io/cluster/{{ .kopsClusterName }}: "true"
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/masters.{{ .kopsClusterName }}
  image: amazon/amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3a
  role: Master
  rootVolumeSize: 16
  subnets:
  - master-eu-west-3a
  tenancy: default

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .kopsClusterName }}
  name: master-eu-west-3b
spec:
  cloudLabels:
    kubernetes.io/cluster/{{ .kopsClusterName }}: "true"
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/masters.{{ .kopsClusterName }}
  image: amazon/amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3b
  role: Master
  rootVolumeSize: 16
  subnets:
  - master-eu-west-3b
  tenancy: default

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .kopsClusterName }}
  name: nodes-eu-west-3a
spec:
  cloudLabels:
    kubernetes.io/cluster/{{ .kopsClusterName }}: "true"
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/nodes.{{ .kopsClusterName }}
  image: amazon/amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-3a
  role: Node
  rootVolumeSize: 16
  subnets:
  - nodes-eu-west-3a
  tenancy: default

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .kopsClusterName }}
  name: nodes-eu-west-3b
spec:
  cloudLabels:
    kubernetes.io/cluster/{{ .kopsClusterName }}: "true"
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/nodes.{{ .kopsClusterName }}
  image: amazon/amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-3b
  role: Node
  rootVolumeSize: 16
  subnets:
  - nodes-eu-west-3b
  tenancy: default
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Not relevant.

**9. Anything else do we need to know?**

To my understanding, if an iam role is shared by multiple instance groups then additional policies are not generated.
See: https://github.com/kubernetes/kops/blob/v1.18.2/pkg/model/iam.go#L189-L230

In our case, the IAMRole is created by terraform before applying `kops update cluster ..`.

We recently changed our single nodes instance group to per AZ nodes instance group. 
As a consequence, the additional policy is not set anymore.

If this behavior is not considered as bug, it would be nice to have it documented as a limitation.

**Comment by hakman** [comment]
You cannot combine custom instance profiles with additionalPolicies. kOps cannot modify the custom instance profile, as it may be used in multiple clusters. You should use either one or the other. Any thoughts?

**Comment by alefray** [comment]
Thanks for your quick reply.

Defining additionalPolicies with a custom instance profile currently works: policy is added as inline.

To do so, I have to specify `--lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges` to reuse an existing role/instance profile but do not override the `IAMRolePolicy` stage.

Example with single instance group / custom role:
```yaml
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{ .kopsClusterName }}
spec:
  additionalPolicies:
    node: |
      [
        {
            "Sid": "AllowKopsBucketAccess",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "{{ $.kmsKeyId }}"
        }
      ]

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-instance-group
spec:
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/custom_iam_role
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-instance-group
  role: Node
  subnets:
  - nodes-subnet-a
  - nodes-subnet-b
  - nodes-subnet-c

```

However, the following example would not work because this time `custom_iam_role` is "shared" by the 2 instance groups:
```
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{ .kopsClusterName }}
spec:
  additionalPolicies:
    node: |
      [
        {
            "Sid": "AllowKopsBucketAccess",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "{{ $.kmsKeyId }}"
        }
      ]

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-instance-group-a
spec:
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/custom_iam_role
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-instance-group-b
  role: Node
  subnets:
  - nodes-subnet-a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-instance-group-b
spec:
  iam:
    profile: arn:aws:iam::{{ .accountId }}:instance-profile/custom_iam_role
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-instance-group-b
  role: Node
  subnets:
  - nodes-subnet-b
```

I understand there may be arguments for ignoring this scenario as you mentionned, but 
- the current behavior is not consistent (single vs 2 IGs) from what we would expect i.e. both failing or succeding.
- this subtle difference of behavior is completely silent and was quite hard to understand/debug.
