### ISSUE TITLE
AWS launch template metadata options lacking "http_endpoint" attribute fails with Terraform

### ISSUE THREAD

**Issue by seh** [kubernetes/kops#10393]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.19.0-beta.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.19.4
```
version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. _kops  update cluster --out=. --target=terraform --create-kube-config=false_
1. _terraform apply -auto-approve_

**5. What happened after the commands executed?**

The AWS API rejects the operations attempted by the Terraform AWS provider, with messages for each `aws_launch_template` resource like this:
```
Error: error creating Launch Template (lt-0f27a1c3cb68aba0f) Version: InvalidParameterValue: A value of ‘’ is not valid for http-endpoint. Valid values are ‘enabled’ or ‘disabled’.
	status code: 400, request id: fd0c6d8c-ad70-4877-9adf-00e6e35f2edc

  on kubernetes.tf line 695, in resource "aws_launch_template" "bastions-redacted":
 695: resource "aws_launch_template" "bastions-redacted" {
```

**6. What did you expect to happen?**

The Terraform configuration generated by _kops update cluster_ should apply successfully.

**7. Please provide your cluster manifest.**

<details>
<summary>Cluster manifest</summary>
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-11-25T17:50:06Z"
  generation: 4
  name: redacted-cluster
spec:
  additionalSans:
  - api.internal.redacted
  api:
    loadBalancer:
      additionalSecurityGroups:
      - sg-08a64a8847a6d0cd3
      class: Network
      crossZoneLoadBalancing: true
      idleTimeoutSeconds: 3600
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://redacted-kops-state/redacted-cluster
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    featureGates:
      EphemeralContainers: "true"
  kubeControllerManager:
    featureGates:
      LegacyNodeRoleBehavior: "false"
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      EphemeralContainers: "true"
  kubernetesVersion: 1.19.4
  masterInternalName: api.internal.redacted-cluster
  masterPublicName: api.redacted-cluster
  metricsServer:
    enabled: true
  networkCIDR: 10.3.0.0/16
  networkID: vpc-0b963d861ceaf3b17
  networking:
    calico:
      bpfEnabled: true
      crossSubnet: true
      mtu: 8951
      typhaReplicas: 3
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - cidr: 10.3.100.0/22
    id: subnet-0c828450b78705439
    name: utility-us-east-2a
    type: Utility
    zone: us-east-2a
  - cidr: 10.3.104.0/22
    id: subnet-0398d4a75a3888c0c
    name: utility-us-east-2b
    type: Utility
    zone: us-east-2b
  - cidr: 10.3.108.0/22
    id: subnet-058646b4f6fbd9929
    name: utility-us-east-2c
    type: Utility
    zone: us-east-2c
  - cidr: 10.3.0.0/22
    egress: nat-094e8b4023a0f8093
    id: subnet-08a9f946eb2814ee4
    name: us-east-2a
    type: Private
    zone: us-east-2a
  - cidr: 10.3.4.0/22
    egress: nat-026c73e6779288dc7
    id: subnet-0442a24d37181e2a3
    name: us-east-2b
    type: Private
    zone: us-east-2b
  - cidr: 10.3.8.0/22
    egress: nat-0e034de3e76de6d12
    id: subnet-03617a6eec6a5fbed
    name: us-east-2c
    type: Private
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
</details>

**8. Anything else do we need to know?**

Per my initial report (https://github.com/kubernetes/kops/pull/10324#discussion_r539311959) on #10324, there's an open Terraform issue describing this problem: hashicorp/terraform-provider-aws#12564. I think it's best if we include [the "http_endpoint" attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#http_endpoint) explicitly, and not rely on the AWS provider treating the documented default behavior correctly.

At present, the generated Terraform configuration looks like this:
```terraform
resource "aws_launch_template" "bastions-redacted" {
  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      delete_on_termination = true
      encrypted             = false
      volume_size           = 32
      volume_type           = "gp2"
    }
  }
  iam_instance_profile {
    name = aws_iam_instance_profile.bastions-redacted.id
  }
  image_id      = "ami-00a38eb907df07525"
  instance_type = "t3.micro"
  key_name      = aws_key_pair.redacted.id
  lifecycle {
    create_before_destroy = true
  }
  metadata_options {
    http_put_response_hop_limit = 1
    http_tokens                 = "optional"
  }
  // ...
}
```
