### ISSUE TITLE
kops --api-ssl-certificate is ignored

### ISSUE THREAD

**Issue by guerzon** [kubernetes/kops#10648]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```shell
kops create cluster \
  --cloud aws \
  --vpc ${VPC_ID} \
  --subnets ${SUBNET1_ID} \
  --zones ap-southeast-1a \
  --master-size m5.large --master-count 1 \
  --node-size m5.large --node-count 2 \
  --dns-zone uranus.company.io \
  --api-ssl-certificate "arn:aws:acm:ap-southeast-1:<account_ID>:certificate/<UUID>" \
  ${CLUSTER_NAME}
```

**5. What happened after the commands executed?**

Command was successful and the cluster was created. However, the API server does not use the certificate in ACM

```
...
-----END CERTIFICATE-----
subject=/CN=kubernetes-master
issuer=/CN=kubernetes
```

**6. What did you expect to happen?**

The cluster should use the SSL certificate from ACM.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-01-23T18:14:04Z"
  name: uranus.company.io
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://uranus-kops/uranus.company.io
  containerRuntime: docker
  dnsZone: uranus.company.io
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    percyacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.15
  masterPublicName: api.uranus.company.io
  networkCIDR: 10.0.0.0/16
  networkID: vpc-VPCID
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.88.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.32.0/21
    id: subnet-<SUBNETID>
    name: ap-southeast-1a
    type: Public
    zone: ap-southeast-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-01-23T18:14:05Z"
  labels:
    kops.k8s.io/cluster: uranus.company.io
  name: master-ap-southeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201112.1
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1a
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-01-23T18:14:05Z"
  labels:
    kops.k8s.io/cluster: uranus.company.io
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201112.1
  machineType: m5.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-southeast-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I know the certificate is valid:

```
percy:uranus percy$ aws acm list-certificates
CertificateSummaryList:
- CertificateArn: arn:aws:acm:ap-southeast-1:<account_ID>:certificate/<UUID>
  DomainName: '*.uranus.company.io'
percy:uranus percy$
```
