### ISSUE TITLE
InstanceGroup externalLoadBalancer - found duplicate tasks

### ISSUE THREAD

**Issue by kxesd** [kubernetes/kops#10664]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.19.0-beta.3 (git-e43f1cc6e3c77d093935d1706042861095d75eb7)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-15T11:35:50Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
a. Create 2 or more InstanceGroup's with the same `externalLoadBalancers` in the spec
b. `kops update cluster mycluster.tld`

**5. What happened after the commands executed?**
Received an error message with a bunch of goroutine information
```
found duplicate tasks with name "ClassicLoadBalancer/my-loadbalancer": *awstasks.ClassicLoadBalancer {"Name":"my-loadbalancer","Lifecycle":null,"LoadBalancerName":"my-loadbalancer","DNSName":null,"HostedZoneId":null,"Subnets":null,"SecurityGroups":null,"Listeners":null,"Scheme":null,"HealthCheck":null,"AccessLog":null,"ConnectionDraining":null,"ConnectionSettings":null,"CrossZoneLoadBalancing":null,"SSLCertificateID":"","Tags":null,"ForAPIServer":false,"Shared":true} and *awstasks.ClassicLoadBalancer {"Name":"my-loadbalancer","Lifecycle":null,"LoadBalancerName":"my-loadbalancer","DNSName":null,"HostedZoneId":null,"Subnets":null,"SecurityGroups":null,"Listeners":null,"Scheme":null,"HealthCheck":null,"AccessLog":null,"ConnectionDraining":null,"ConnectionSettings":null,"CrossZoneLoadBalancing":null,"SSLCertificateID":"","Tags":null,"ForAPIServer":false,"Shared":true}
```

**6. What did you expect to happen?**
The externalLoadBalancer to be added to both InstanceGroup's

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

InstanceGroup: nodes-a
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-a
spec:
  externalLoadBalancers:
  - loadBalancerName: my-loadbalancer
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-a
    reliable: "true"
    reserved: "true"
  role: Node
  rootVolumeSize: 64
  rootVolumeType: gp2
  subnets:
  - ap-southeast-2a
```

InstanceGroup: nodes-b
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-b
spec:
  externalLoadBalancers:
  - loadBalancerName: my-loadbalancer
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-b
    reliable: "true"
    reserved: "true"
  role: Node
  rootVolumeSize: 64
  rootVolumeType: gp2
  subnets:
  - ap-southeast-2b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
