### ISSUE TITLE
[Question / Feature Request] AWS NLB - EIP Allocations

### ISSUE THREAD

**Issue by timothyclarke** [kubernetes/kops#10706]
Firstly thanks for the work people have put in for the the Network Loadbalancer in AWS clusters.

Is there a way (without using `-out ... --target=terraform` and editing the tf config) to use IP allocations so we can make use of static IP's?

I haven't thought through the cli elements to create the cluster, but I would expect that the spec would be something like
```
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
      elasticIPs:
      - eipalloc-000abc123
      - eipalloc-111def456
      - eipalloc-222ghi789
```

**Comment by bharath-123** [comment]
I don't think kOps currently supports specifying allocationIds of elasticIps to attach to a network load balancer. You probably would have to manually associate an elastic ip at this point of time. 

But I do see a way to do this in kOps. The `SubnetMapping` struct in `CreateLoadBalancerInput` accepts an allocationId for an elasticIp for a specified subnet.([link](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.1.0/types#SubnetMapping)) which can be used to associate elastic ips to the nlb.

**Comment by bharath-123** [comment]
I think if we can specify a mapping of subnetId to allocationId of the elastic ip in the lb spec, we should be able to associate elastic ips to the nlb.

**Comment by rifelpet** [comment]
Agreed, I think it would be reasonable to support this. We'll need the new API fields to be able to represent which subnet ID to use for each allocation ID. I _believe_ that the [name](https://github.com/kubernetes/kops/blob/9d0dd3c4c1957f829504376778d0ee67f8f4d28f/tests/integration/update_cluster/complex/in-v1alpha2.yaml#L68) field of subnets in the ClusterSpec are unique, so we might be able to get away with referencing them by name


Maybe something along the lines of:

```yaml
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
      subnetMapping: # or a more generic term for this
      - subnet: us-east-1a-public
        allocationID: eipalloc-111def456
      - subnet: us-east-1b-public
        allocationID: eipalloc-222ghi789
```

Then we just find the subnet ID associated with each subnet name and pass all of that into the CreateLoadBalancerInput.
