### ISSUE TITLE
kops-controller enters crashloop on update to k8s 1.19.7

### ISSUE THREAD

**Issue by MichaelJDrK** [kubernetes/kops#10704]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. Create a new cluster with kops 1.19.0 and Kubernetes 1.18.15. (1 master, 2 nodes)
2. Set "kubernetesVersion: 1.19.7" in the cluster.yaml
3. Update cluster.yaml in S3: "kops replace -f cluster.yaml"
4. Update cloud resources: "kops update cluster $NAME --yes"

**5. What happened after the commands executed?**

This will trigger an update to the kops-controller deployment. The kops-controller will now be in a crashloop because of the new config.yaml. 

E0201 09:34:10.278898       1 main.go:107] setup "msg"="unable to start server" "error"="reading \"ca\" certificate: open /etc/kubernetes/kops-controller/pki/ca.pem: no such file or directory"                                   
 stream closed  

kops-controller expects certificates on the node, which are not yet available, because there wasn't a rolling update yet.
You cannot do a rolling-update, because the cluster validation will not pass (because of the crashloop)

**6. What did you expect to happen?**

The cluster should remain stable. kops-controller should not enter a crashloop because of the missing certificates. There should be some smooth transition.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: FOOBAR
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        }        
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://FOOBAR
  containerRuntime: docker
  dnsZone: FOOBAR
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 3
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 3
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook    
  kubeAPIServer:
    disableBasicAuth: true
    enableProfiling: false
  kubeControllerManager:
    terminatedPodGCThreshold: 10
    enableProfiling: false
  kubeDNS:
    provider: CoreDNS
  kubeScheduler:
    enableProfiling: false    
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.7
  masterPublicName: api.FOOBAR
  networkCIDR: 172.20.0.0/16
  networkID: FOOBAR
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    id: FOOBAR
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    id: FOOBAR
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: FOOBAR
  name: master-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxPrice: "0.020"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeOptimization: true  
  rootVolumeSize: 8
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: FOOBAR
  name: nodes-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxPrice: "0.020"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1a
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 10
  subnets:
  - eu-central-1a
  
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster:FOOBAR
  name: nodes-eu-central-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxPrice: "0.020"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1b
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 10
  subnets:
  - eu-central-1b  

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
-/-

**9. Anything else do we need to know?**
-/-
