### ISSUE TITLE
calico-kube-controllers stuck not ready during rolling update.

### ISSUE THREAD

**Issue by jetersen** [kubernetes/kops#10737]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.3 (git-11ec695516)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
1.18.10, upgrading to 1.18.15.

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops rolling-update 😅

**5. What happened after the commands executed?**

Over time I have noticed every time I have done rolling updates all they from 1.18.0, to 1.18.1, 1.18.2 through to 1.18.3. I noticed the calico-kube-controllers gets into a not ready state and the cluster validation will fail. Not sure what the underlying issue is but a simple `kubectl delete pod --namespace kube-system calico-kube-controllers` does the trick.

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 1
  name: my cluster
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "sts:AssumeRole",
          ],
          "Resource": [
            "*"
          ]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "sts:AssumeRole",
          ],
          "Resource": [
            "*"
          ]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/euc1: ""
  cloudProvider: aws
  configBase: s3://clusters.company.io/my-cluster.company.io
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-eu-central-1a
          name: a
        - encryptedVolume: true
          instanceGroup: master-eu-central-1b
          name: b
        - encryptedVolume: true
          instanceGroup: master-eu-central-1c
          name: c
      memoryRequest: 100Mi
      name: main
      version: 3.2.24
    - cpuRequest: 100m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-eu-central-1a
          name: a
        - encryptedVolume: true
          instanceGroup: master-eu-central-1b
          name: b
        - encryptedVolume: true
          instanceGroup: master-eu-central-1c
          name: c
      memoryRequest: 100Mi
      name: events
      version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: kubelogin
    oidcGroupsClaim: groups
    oidcIssuerURL: https://dex.company.io
    oidcUsernameClaim: email
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
    - NA
  kubernetesVersion: 1.18.15
  masterPublicName: api.my-cluster.company.io
  networkCIDR: 172.31.0.0/16
  networkID: vpc-9b9c0bf3
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/17
  sshAccess:
    - NA
  subnets:
    - cidr: 172.31.0.0/20
      id: subnet-a6b8e9ce
      name: eu-central-1a
      type: Public
      zone: eu-central-1a
    - cidr: 172.31.16.0/20
      id: subnet-704bd40a
      name: eu-central-1b
      type: Public
      zone: eu-central-1b
    - cidr: 172.31.32.0/20
      id: subnet-1ffad755
      name: eu-central-1c
      type: Public
      zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-22T21:47:05Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: my-cluster.company.io
  name: master-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.medium
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
      - t3.medium
      - t3a.medium
    onDemandAboveBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
    - eu-central-1a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-22T21:47:06Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: my-cluster.company.io
  name: master-eu-central-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.medium
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
      - t3.medium
      - t3a.medium
    onDemandAboveBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
    - eu-central-1b

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-22T21:47:06Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: my-cluster.company.io
  name: master-eu-central-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.medium
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
      - t3.medium
      - t3a.medium
    onDemandAboveBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
    - eu-central-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-22T21:47:06Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: my-cluster.company.io
  name: nodes-large
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5.large
  maxPrice: "0.30"
  maxSize: 10
  minSize: 0
  mixedInstancesPolicy:
    instances:
      - m5.large
      - m5a.large
      - m5d.large
      - m5n.large
      - m5ad.large
      - m5dn.large
      - r5.large
      - r5a.large
      - r5d.large
      - r5n.large
      - r5ad.large
      - r5dn.large
      - c5.xlarge
      - c5a.xlarge
      - c5d.xlarge
      - t3.large
      - t3a.large
      - i3.large
    onDemandAboveBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-large
  role: Node
  subnets:
    - eu-central-1a
    - eu-central-1b
  suspendProcesses:
    - AZRebalance
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
NA

**9. Anything else do we need to know?**
