### ISSUE TITLE
Traefik won't work OOTB with default "masters" IAM role

### ISSUE THREAD

**Issue by alejandroandreu** [kubernetes/kops#10753]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.18.15

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create a vanilla cluster in AWS:

```sh
kops create -f cluster.yaml; \
kops create secret --name k8s.dev.example.com sshpublickey admin -i ~/.ssh/k8s_rsa.pub; \
kops update cluster k8s.dev.example.com --yes;
# wait for cluster to be ready...
# wait...
# install Traefik via Helm
kubectl create ns traefik
helm repo add traefik "https://helm.traefik.io/traefik"
helm repo update
helm install \
	traefik traefik/traefik \
	--namespace traefik
```

**5. What happened after the commands executed?**

Traefik pod runs alright. Traefik `Service` (type `LoadBalancer` by default) can't be created because `masters.k8s.dev.example.com` IAM role is lacking `iam:CreateServiceLinkedRole` permissions.

Describing the `traefik` service inside the `traefik` namespace shows the following:

`Warning  SyncLoadBalancerFailed  7s    service-controller  Error syncing load balancer: failed to ensure load balancer: AccessDenied: User: arn:aws:sts::703422386914:assumed-role/masters.k8s.dev.example.com/i-028937957b1c39c9c is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::703422386914:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing`

**6. What did you expect to happen?**

The Traefik service is created just fine.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.dev.example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig: {}
  cloudLabels:
    Environment: dev
  cloudProvider: aws
  configBase: s3://k8s-dev-eu-west-3-kops-state/k8s.dev.example.com
  containerRuntime: docker
  dnsZone: dev.example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-3a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-3a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - IP_ADDRESS
  kubernetesVersion: 1.18.15
  masterPublicName: api.k8s.dev.example.com
  networkCIDR: 172.20.0.0/16
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - IP_ADDRESS
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-3a
    type: Public
    zone: eu-west-3a
  - cidr: 172.20.64.0/19
    name: eu-west-3b
    type: Public
    zone: eu-west-3b
  - cidr: 172.20.96.0/19
    name: eu-west-3c
    type: Public
    zone: eu-west-3c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
    spotinst.io/spot-percentage: "100"
    spotinst.io/fallback-to-ondemand: "false"
    spotinst.io/utilize-reserved-instances: "false"
    spotinst.io/ocean-instance-types-whitelist: "t2.large,t3.large,t3a.large"
    spotinst.io/ocean-default-launchspec: "true"
  name: nodes-eu-west-3a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-3a
  role: Node
  subnets:
  - eu-west-3a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
    spotinst.io/spot-percentage: "100"
    spotinst.io/fallback-to-ondemand: "false"
    spotinst.io/utilize-reserved-instances: "false"
    spotinst.io/ocean-instance-types-whitelist: "t2.large,t3.large,t3a.large"
  name: nodes-eu-west-3b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-3b
  role: Node
  subnets:
  - eu-west-3b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
    spotinst.io/spot-percentage: "100"
    spotinst.io/fallback-to-ondemand: "false"
    spotinst.io/utilize-reserved-instances: "false"
    spotinst.io/ocean-instance-types-whitelist: "t2.large,t3.large,t3a.large"
  name: nodes-eu-west-3c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-3c
  role: Node
  subnets:
  - eu-west-3c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
    spotinst.io/spot-percentage: "0"
    spotinst.io/fallback-to-ondemand: "true"
    spotinst.io/utilize-reserved-instances: "false"
    spotinst.io/ocean-instance-types-whitelist: "t2.small,t3.small,t3a.small"
  name: master-eu-west-3a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3a
  role: Master
  subnets:
  - eu-west-3a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I don't think it's necessary.

**9. Anything else do we need to know?**

N/A
