### ISSUE TITLE
running "kubectl drain" no longer removes machine instances from ELBs

### ISSUE THREAD

**Issue by amorey** [kubernetes/kops#10774]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.19.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.19.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kubectl drain <node>

**5. What happened after the commands executed?**

Previously, using kops/k8s 1.18.2/1.18.10 running `kubectl drain` would remove machine instances from classic ELBs. Now running `kubectl drain` does not do so.

**6. What did you expect to happen?**

I expected running `kubectl drain` to remove the node machine instances from classic ELBs. I was also hoping that running `kubectl drain` would remove instances from network ELBs but that isn't happening either (with both kops/k8s 1.18.2/1.18.10 and 1.19.0/1.19.7).

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-02-01T13:55:38Z"
  name: <REDACTED>
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: <REDACTED>
  containerRuntime: docker
  dnsZone: <REDACTED>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: <REDACTED>
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: <REDACTED>
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    <REDACTED>
  kubernetesApiAccess:
  - <REDACTED>
  kubernetesVersion: 1.19.7
  masterPublicName: <REDACTED>
  networkCIDR: 10.0.0.0/16
  networkID: <REDACTED>
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - <REDACTED>
  subnets:
  - cidr: 10.0.32.0/19
    id: <REDACTED>
    name: <REDACTED>
    type: Public
    zone: <REDACTED>
  - cidr: 10.0.64.0/19
    id: <REDACTED>
    name: <REDACTED>
    type: Public
    zone: <REDACTED>
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-01T13:55:39Z"
  labels:
    kops.k8s.io/cluster: <REDACTED>
  name: <REDACTED>
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: <REDACTED>
  role: Master
  subnets:
  - <REDACTED>

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-01T13:55:39Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: <REDACTED>
  name: <REDACTED>
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<REDACTED>: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxSize: 10
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t3a.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: <REDACTED>
  role: Node
  rootVolumeSize: 30
  subnets:
  - <REDACTED>

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-01T13:55:39Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: <REDACTED>
  name: <REDACTED>
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<REDACTED>: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxSize: 10
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - t3.medium
    - t3a.medium
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 2
  nodeLabels:
    kops.k8s.io/instancegroup: <REDACTED>
  role: Node
  rootVolumeSize: 30
  subnets:
  - <REDACTED>
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
