### ISSUE TITLE
Cannot SSH into Kubernetes Cluster

### ISSUE THREAD

**Issue by dkoutsou** [kubernetes/kops#10770]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
kops version
I0208 18:19:45.552205   14561 featureflag.go:167] FeatureFlag "AlphaAllowGCE"=true
Version 1.19.0
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
Google Cloud

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I create and deploy a one node cluster using: 
```kops create cluster part1.k8s.local --zones europe-west3-a --node-count 2 --node-image ubuntu-os-cloud/ubuntu-2004-focal-v20210129 --node-size "e2-standard-2" --ssh-public-key ~/.ssh/id_rsa.pub --state ${KOPS_STATE_STORE}/ --project=${PROJECT}```
```kops update cluster --name part1.k8s.local --yes --admin```

I then wait for the cluster to be ready and get the external IP of one of the nodes using:

```kubectl get nodes -o wide```
However when I try to login to the node I get:

```ssh -i ~/.ssh/id_rsa admin@<PUBLIC_IP>
admin@<PUBLIC_IP>: Permission denied (publickey).
````

**6. What did you expect to happen?**

Login to the node.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-02-08T16:50:04Z"
  name: part1.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    gceServiceAccount: default
  cloudProvider: gce
  configBase: gs://cloud-computing-eth-dkoutsou/part1.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-europe-west3-a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-europe-west3-a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.7
  masterPublicName: api.part1.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: cloud-computing-eth-2021
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: europe-west3
    region: europe-west3
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-08T16:50:06Z"
  labels:
    kops.k8s.io/cluster: part1.k8s.local
  name: master-europe-west3-a
spec:
  image: cos-cloud/cos-stable-77-12371-114-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: master-europe-west3-a
  role: Master
  subnets:
  - europe-west3
  zones:
  - europe-west3-a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-08T16:50:06Z"
  labels:
    kops.k8s.io/cluster: part1.k8s.local
  name: nodes-europe-west3-a
spec:
  image: ubuntu-os-cloud/ubuntu-2004-focal-v20210129
  machineType: e2-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    cloud.google.com/metadata-proxy-ready: "true"
    kops.k8s.io/instancegroup: nodes-europe-west3-a
  role: Node
  subnets:
  - europe-west3
  zones:
  - europe-west3-a
```
