### ISSUE TITLE
kops edit ig not working

### ISSUE THREAD

**Issue by Maduflavins** [kubernetes/kops#10800]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
I am running kops version 1.19.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
kubernetes version v1.19.0 --kops

**3. What cloud provider are you using?**
cloud provider is AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops edit ig nodes --name ${NAME}`

**5. What happened after the commands executed?**
I got the below error
`error reading InstanceGroup "nodes": InstanceGroup.kops.k8s.io "nodes" not found`

**6. What did you expect to happen?**
I expected to see a yaml file where i can edit the configuration of the nodes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  name: ld.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kubernetes-product-teams/ktrsyuu.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.7
  masterPublicName: 'api.binnkkih.com'
  networkCIDR: xxx.yy.0.0/xx
  networking:
    kubenet: {}
  nonMasqueradeCIDR: xxxx.yyy.c.d/xx
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: kubernetes-product-teams.k8s.local
  name: master-us-east-1a
spec:
  image: xxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-2xxxxxx.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: kubernetes-product-teams.k8s.local
  name: nodes-us-east-1a
spec:
  image: xxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxxx.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: kubernetes-product-teams.k8s.local
  name: nodes-us-east-1b
spec:
  image: xxxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxxxx.x
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1b
  role: Node
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: kubernetes-guguig7gugug.k8s.local
  name: nodes-us-east-1c
spec:
  image: xxxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxx.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1c
  role: Node
  subnets:
  - us-east-1c
[ec2-user@ip-172-31-90-109 ~]$ 
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  name: ld.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://hhi8iiiug9l/ktrsyuu.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.7
  masterPublicName: 'api.binnkkih.com'
  networkCIDR: xxx.yy.0.0/xx
  networking:
    kubenet: {}
  nonMasqueradeCIDR: xxxx.yyy.c.d/xx
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: huuiiuguiguuuu.k8s.local
  name: master-us-east-1a
spec:
  image: xxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-2xxxxxx.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: kubernetes-product-teams.k8s.local
  name: nodes-us-east-1a
spec:
  image: xxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxxx.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: kubernetes-product-teams.k8s.local
  name: nodes-us-east-1b
spec:
  image: xxxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxxxx.x
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1b
  role: Node
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T00:27:44Z"
  labels:
    kops.k8s.io/cluster: xxxx.k8c.local
  name: nodes-us-east-1c
spec:
  image: xxxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxx.1
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1c
  role: Node
  subnets:
  - us-east-1c
[ec2-user@ip-172-31-90-109 ~]$ 

---
images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.12.0 <1.13.0"
    - name: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.13.0 <1.14.0"
    - name: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.14.0 <1.15.0"
    - name: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.15.0 <1.16.0"
    - name: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.16.0 <1.17.0"
    - name: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-11-19
      providerID: aws
      kubernetesVersion: ">=1.17.0 <1.18.0"
    - name: xxxxxxxxxxx/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-xxxxxx.1
      providerID: aws
      kubernetesVersion: ">=1.18.0"
    - providerID: gce
      kubernetesVersion: "<1.16.0-alpha.1"
      name: "cos-cloud/cos-stable-65-10323-99-0"
    - providerID: gce
      kubernetesVersion: ">=1.16.0-alpha.1"
      name: "cos-cloud/cos-stable-77-12371-114-0"
    - providerID: gce
      kubernetesVersion: ">=1.17.0"
      name: "ubuntu-os-cloud/ubuntu-2004-focal-v20210119a"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.20.0"
    recommendedVersion: 1.20.2
    requiredVersion: 1.20.0
  - range: ">=1.19.0"
    recommendedVersion: 1.19.7
    requiredVersion: 1.19.0
  - range: ">=1.18.0"
    recommendedVersion: 1.18.15
    requiredVersion: 1.18.0
  - range: ">=1.17.0"
    recommendedVersion: 1.17.17
    requiredVersion: 1.17.0
  - range: ">=1.16.0"
    recommendedVersion: 1.16.15
    requiredVersion: 1.16.0
  - range: ">=1.15.0"
    recommendedVersion: 1.15.12
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.10
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.12
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: "<1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.10
  kopsVersions:
  - range: ">=1.20.0-alpha.1"
    #recommendedVersion: "1.19.0-beta.3"
    #requiredVersion: 1.19.0
    kubernetesVersion: 1.20.2
  - range: ">=1.19.0-beta.3"
    #recommendedVersion: "1.19.0-beta.3"
    #requiredVersion: 1.19.0
    kubernetesVersion: 1.19.7
  - range: ">=1.18.0-alpha.1"
    recommendedVersion: "1.18.2"
    #requiredVersion: 1.18.0
    kubernetesVersion: 1.18.15
  - range: ">=1.17.0-alpha.1"
    recommendedVersion: "1.18.2"
    #requiredVersion: 1.17.0
    kubernetesVersion: 1.17.17
  - range: ">=1.16.0-alpha.1"
    recommendedVersion: "1.18.2"
    #requiredVersion: 1.16.0
    kubernetesVersion: 1.16.15
  - range: ">=1.15.0-alpha.1"
    recommendedVersion: "1.18.2"
    #requiredVersion: 1.15.0
    kubernetesVersion: 1.15.12
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.10
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.12
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: "<1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.11.10
error reading InstanceGroup "nodes": InstanceGroup.kops.k8s.io "nodes" not found
[ec2-user@ip-172-31-90-109 ~]$ 

```

**9. Anything else do we need to know?**
