### ISSUE TITLE
Question: why max pods lower than expected on AWS?

### ISSUE THREAD

**Issue by LordNoteworthy** [kubernetes/kops#10835]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kubectl describe nods <node_name>

**5. What happened after the commands executed?**
```
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         36
  ephemeral-storage:           130045936Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      71926564Ki
  pods:                        **110**
```

**6. What did you expect to happen?**
According to AWS [doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html), the maximum number of pods per node is calculated with this formula: N * (M-1) + 2
- N is the number of Elastic Network Interfaces (ENI) of the instance type
- M is the number of IP addresses of a single ENI
- For a `c5.9xlarge`: N=8, M=30 which should set the max pods to: 234, the [link](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) will show the same count.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-01-21T10:30:36Z"
  generation: 2
  name: kops.company.com
spec:
  additionalPolicies:
    node: |
      [
        {
        "Effect": "Allow",
        "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "autoscaling:DescribeTags"
        ],
        "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://company-com-kops-state/kops.company.com
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.15
  masterInternalName: api.internal.kops.company.com
  masterPublicName: api.kops.company.com
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

Cheers.

**Comment by hakman** [comment]
I think there is some confusion about what Kubernetes recommends and what AWS allows:
https://kubernetes.io/docs/setup/best-practices/cluster-large/
https://kubernetes.io/docs/concepts/cluster-administration/networking/#aws-vpc-cni-for-kubernetes

Should be easy to increase the limit if you want to:
```yaml
spec:
    kubelet:
        maxPods: 150
```
