### ISSUE TITLE
kOps 1.19 sets Cilium enableRemoteNodeIdentity to true by default, which is a breaking change

### ISSUE THREAD

**Issue by agilgur5** [kubernetes/kops#10836]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.19

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.9

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Simplest way to reproduce would be to:
1. Create a fresh cluster using Cilium, e.g. with `kops create-cluster --networking cilium`.
2. Then add a simple `NetworkPolicy`, such as this `kube-dns` one:

```yaml
# Allow traffic from other namespaces to kube-dns (CoreDNS)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
  - from:
    - namespaceSelector: {}
```

3. Send some request _from a host_ (e.g. `hostNetwork: true` pod or SSH'ed into a host) to `kube-dns`, e.g. `curl kube-dns.kube-system.cluster.service.local` or an `nslookup` to something. This request will fail and timeout
    - This is just a simple example using a service that already exists in a default cluster; any other service works too. I'm not totally sure exactly how host DNS works, this was just one service we had issues with.
  
As a more complicated example of what we ran into:
1. Create a new kOps 1.19 cluster using a kOps template with:

```yaml
# ...
networking:
  cilium: {}
# ...
```

2. Run something that requires host networking, e.g. KIAM agents access the KIAM server via `hostNetwork`. `metrics-server` and KEDA receive requests from the host's `kupe-apiserver` to serve metrics in the appropriate APIs. Or DNS as the example above.

3. Add a simple `NetworkPolicy`:

```yaml
---
# Default network policy to deny all traffic from outside the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: test-namespace-where-service-was-deployed
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

4. KIAM agents or `metrics-server` requests or KEDA requests etc will fail.

**5. What happened after the commands executed?**

Requests timeout

**6. What did you expect to happen?**

Requests succeed, as they do with kOps 1.18 and these manifests.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

This should be the only relevant piece, but can provide more if necessary.

```yaml
# ...
networking:
  cilium: {}
# ...
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Commands themselves aren't failing, rather they seem to be working as intended and there seemingly is a bug in the code (see links below). Either that, or the API docs that say the default is `false` are wrong and the Release Notes/CHANGELOG for 1.19 need to be updated to mention this _breaking_ change.

**9. Anything else do we need to know?**

#### How to resolve this in kOps 1.19

These `NetworkPolicy`s worked fine in kOps 1.18, but in 1.19, we need to add the hosts to our `NetworkPolicy` (specifically, via `CiliumNetworkPolicy` that can specify hosts) in order to get these services to work. For instance, in the `kube-dns` example above, if we replace that policy with this one, it works without issues:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: kube-dns-from-host
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
    - fromEntities:
      - cluster
```

(can use `host` and `remote-node` entities as well, but since we want all pods to access it too, we use `cluster`).

In kOps 1.19, even if we downgrade to Cilium 1.7 (1.7 was the default in 1.18, 1.8 is the default for 1.19), this issue still occurs. I assume this is because `enable-remote-node-identity` was actually [introduced in Cilium 1.7](https://docs.cilium.io/en/v1.7/install/upgrade/#configmap-remote-node-identity), and so the downgrade has no effect when kOps 1.19 still sets it to `true` by default.

#### Relevant lines of code, can make PRs to change these

Here are some lines of code I believe are relevant that we found while debugging:
- I believe [these lines](https://github.com/kubernetes/kops/blob/a6dce2e/pkg/model/components/cilium.go#L91-L93) from `cilium.go`, added in PR https://github.com/kubernetes/kops/pull/9424, are the culprit. They seem to set `enableRemoteNodeIdentity` to `true` when it is `nil`, instead of `false`.
- https://github.com/kubernetes/kops/pull/8731 added several docs that say `Default: false`, but they seem to no longer hold due to the lines above seemingly contradicting that.
  - I'm not totally sure where the `.yaml.template` in that PR is used (as opposed to `cilium.go`), as [its logic sets it to `false` if unset](https://github.com/kubernetes/kops/blob/2db0b18145282ebb47b277691f55fa7100b57f32/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template#L157), just as the docs suggest.
- [1.19 Release Notes](https://github.com/kubernetes/kops/releases/tag/v1.19.0) make no mention of `enableRemoteNodeIdentity`, and, most importantly, no mention of this as a _breaking_ change.

I can write a PR to change all the docs to remove the `Default: false` reference, but can't write a PR against the GitHub Release Notes.
I'm not sure if reverting this in a patch is wise, as that would also be another breaking change (and it is the default in Cilium 1.7+ and improves security), but if that is the path that is decided, I can write a PR to change the `cilium.go` line of code to set to `false` by default.

#### Related Issue in Cilium

Related, but will not impact this issue: I filed https://github.com/cilium/cilium/issues/14989 with Cilium as I didn't think plain, CNI-neutral k8s `NetworkPolicy` would be affected by `enable-remote-node-identity`, as [the k8s spec](https://kubernetes.io/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet) does not define any behavior for that as it is currently unsupported by it. It is only possible with `CiliumNetworkPolicy` to specify hosts.
