### ISSUE TITLE
dns-controller avoid creation by annotation

### ISSUE THREAD

**Issue by dignajar** [kubernetes/kops#10831]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
There is some way to avoid the creation of the DNS record for specific ingress?

For example, the following ingress will create the DNS record for `echo.mydomain.com`.
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: echo.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
```

**2. Feel free to provide a design supporting your feature request.**
Would be good to have an annotation to deny to the dns-controller to set up the DNS record, something like this:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    dns.alpha.kubernetes.io/disable: true
spec:
  rules:
  - host: echo.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
```

**Comment by olemarkus** [comment]
I assume you are running dns-controller with `watch-ingress=true`? Recommend you use [external-dns](https://github.com/kubernetes-sigs/external-dns) instead.

**Comment by dignajar** [comment]
Yes, I'm using `watch-ingress=true`, the idea is to pick up some ingress and not all of them.
I will check external-dns.

Meanwhile, I solved it like this.
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-alias: "echo.mydomain.com"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
```
