### ISSUE TITLE
The public LB getting associated to private subnet in Kops 1.17.6 (Note- I don't see same issue in Kops 1.11.8)

### ISSUE THREAD

**Issue by bhushan558** [kubernetes/kops#10848]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.17.6

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.17.6
**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster
**5. What happened after the commands executed?**
New cluster deployed successfully
**6. What did you expect to happen?**
The public LB was getting associated to 1 private subnet(In theory, it should be associated with 3 public subnets). This is the reason health check was failing and few nodes which are in different AZ showing out of service. I deleted LBs and reran kops cluster update, still same issue. The config was also good. Is this an issue Kops version 1.17? Hence, we need to add subnets manually to LBs.
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
name: test-cluster
bucket: "axyz"
kubernetesVersion: 1.17.6
dnsSuffix: abc.com
nodes:
  spotAmi: ami-1234
  onDemandAmi: ami-1234
  azCount: 3
  largeMaxSize: 5
  xlargeMaxSize: 5
  onDemandLargeMaxSize: 2
  onDemandXLargeMaxSize: 5
masters:
  ami: ami-12345
  ha: true
  machineTypeZoneB: t2.medium
  machineTypeZoneC: t2.medium
monitoringNodes:
  mnInstanceType: t2.large
awsAccountId: "12345"


networkID: vpc-1234
networkCIDR: 1.2.3.4/21

subnets:
- cidr: 1.2.3.4/24
  egress: nat-3456
  id: subnet-4567
  name: eu-west-1a
  type: Private
  zone: eu-west-1a
- cidr: 1.2.3.4/24
  egress: nat-5678
  id: subnet-8765
  name: eu-west-1b
  type: Private
  zone: eu-west-1b
- cidr: 7.8.4.5./24
  egress: nat-5678
  id: subnet-7684
  name: eu-west-1c
  type: Private
  zone: eu-west-1c
- cidr: 7.8.9.5/24
  id: subnet-34577
  name: utility-eu-west-1a
  type: Utility
  zone: eu-west-1a
- cidr: 2.6.3.8/24
  id: subnet-9199
  name: utility-eu-west-1b
  type: Utility
  zone: eu-west-1b
- cidr: 6.4.1.0/24
  id: subnet-0856
  name: utility-eu-west-1c
  type: Utility
  zone: eu-west-1c

```
```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Additionally, internal LB is being added to only one private subnet, I had to add 2 extra subnets manually.
