### ISSUE TITLE
Openstack: reconciliation of InstanceGroups on rolling update does not work properly sometimes

### ISSUE THREAD

**Issue by mitch000001** [kubernetes/kops#10898]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.0 (git-04d36d7d92)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.15

**3. What cloud provider are you using?**
Openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops rolling-update cluster --yes`

**5. What happened after the commands executed?**
The cluster ran the deletion of the old node, continued with reconciling the instance group and kept stuck with the error that the instance group has one node less than expected. 
See https://gist.github.com/mitch000001/d47abdf699dd9096914d98b7b0608830 for details.

**6. What did you expect to happen?**
The instance group should get the missing node back.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: mycluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  assets:
    containerRegistry: registry.mycorp.com
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v2
        createStorageClass: false
        ignore-volume-az: true
        override-volume-az: nova
      loadbalancer:
        floatingNetwork: public
        floatingNetworkID: 12345678-9cc1-4ed0-bbdc-a7476669b4bd
        manageSecurityGroups: true
        method: ROUND_ROBIN
        provider: haproxy
        useOctavia: false
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        externalNetwork: public
  cloudControllerManager:
    clusterName: mycluster.k8s.local
    image: registry.mycorp.com/k8scloudprovider-openstack-cloud-controller-manager:v1.18.0
    logLevel: 2
  cloudProvider: openstack
  configBase: s3://my-bucket/mycluster.k8s.local
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - instanceGroup: master-zone-01
          name: etcd-zone-01
          volumeSize: 5
          volumeType: fast-500
        - instanceGroup: master-zone-02
          name: etcd-zone-02
          volumeSize: 5
          volumeType: fast-500
        - instanceGroup: master-zone-03
          name: etcd-zone-03
          volumeSize: 5
          volumeType: fast-500
      memoryRequest: 100Mi
      name: main
      provider: Manager
    - cpuRequest: 100m
      etcdMembers:
        - instanceGroup: master-zone-01
          name: etcd-zone-01
          volumeSize: 5
          volumeType: fast-500
        - instanceGroup: master-zone-02
          name: etcd-zone-02
          volumeSize: 5
          volumeType: fast-500
        - instanceGroup: master-zone-03
          name: etcd-zone-03
          volumeSize: 5
          volumeType: fast-500
      memoryRequest: 100Mi
      name: events
      provider: Manager
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    allowPrivileged: true
    apiAudiences:
      - api
      - istio-ca
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
      - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: 1.18.15
  masterPublicName: api.mycluster.k8s.local
  metricsServer:
    enabled: true
  networkCIDR: 10.0.0.0/20
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
  sshKeyName: mycluster.k8s.local
  subnets:
    - cidr: 10.0.1.0/24
      name: local_zone_01
      type: Private
    - cidr: 10.0.2.0/24
      name: local_zone_02
      type: Private
    - cidr: 10.0.3.0/24
      name: local_zone_03
      type: Private
    - cidr: 10.0.15.0/29
      name: utility-local_zone_01
      type: Utility
  topology:
    bastion:
      bastionPublicName: bastion.mycluster.k8s.local
    dns:
      type: Private
    masters: private
    nodes: private

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:18Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: bastion-zone-01
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  machineType: blc.1-2
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: bastion-zone-01
    x-ion.de/wireguard: "true"
  role: Bastion
  subnets:
    - utility-local_zone_01
  zones:
    - local_zone_01

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:19Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: master-zone-01
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: nodefs.available<65G,imagefs.available<65G
    evictionSoftGracePeriod: nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 80m
      ephemeral-storage: 60G
      memory: 2.2G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.4-12
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: master-zone-01
    x-ion.de/wireguard: "true"
  role: Master
  subnets:
    - local_zone_01
  zones:
    - local_zone_01

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:19Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: master-zone-02
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: nodefs.available<65G,imagefs.available<65G
    evictionSoftGracePeriod: nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 80m
      ephemeral-storage: 60G
      memory: 2.2G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.4-12
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: master-zone-02
    x-ion.de/wireguard: "true"
  role: Master
  subnets:
    - local_zone_02
  zones:
    - local_zone_02

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:19Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: master-zone-03
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: true
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: nodefs.available<65G,imagefs.available<65G
    evictionSoftGracePeriod: nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 80m
      ephemeral-storage: 60G
      memory: 2.2G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.4-12
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: master-zone-03
    x-ion.de/wireguard: "true"
  role: Master
  subnets:
    - local_zone_03
  zones:
    - local_zone_03

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:19Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: node-zone-01
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: false
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: nodefs.available<65G,imagefs.available<65G
    evictionSoftGracePeriod: nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 80m
      ephemeral-storage: 60G
      memory: 2.2G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.4-12
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: node-zone-01
    x-ion.de/wireguard: "true"
  role: Node
  subnets:
    - local_zone_01
  zones:
    - local_zone_01

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:19Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: node-zone-02
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: false
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: nodefs.available<65G,imagefs.available<65G
    evictionSoftGracePeriod: nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 80m
      ephemeral-storage: 60G
      memory: 2.2G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.4-12
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: node-zone-02
    x-ion.de/wireguard: "true"
  role: Node
  subnets:
    - local_zone_02
  zones:
    - local_zone_02

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-22T13:14:19Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: node-zone-03
spec:
  additionalSecurityGroups:
    - mycluster.k8s.local.monitoring
  associatePublicIp: false
  cloudLabels:
    prometheus.io_node_exporter_port: "55000"
    prometheus.io_node_problem_detector_port: "20257"
  image: ubuntu-focal-20-04-amd64-2021-02-18
  kubelet:
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionSoft: nodefs.available<65G,imagefs.available<65G
    evictionSoftGracePeriod: nodefs.available=30s,imagefs.available=30s
    kubeReserved:
      cpu: 80m
      ephemeral-storage: 60G
      memory: 2.2G
    systemReserved:
      cpu: 100m
      ephemeral-storage: 5G
      memory: 100M
  machineType: blc.4-12
  maxSize: 2
  minSize: 1
  nodeLabels:
    k8s.io/instancegroup: node-zone-03
    x-ion.de/wireguard: "true"
  role: Node
  subnets:
    - local_zone_03
  zones:
    - local_zone_03
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I suspect that the issue lies within https://github.com/kubernetes/kops/blob/master/pkg/instancegroups/instancegroups.go#L378. Occasionally the deletion of the node takes longer and the function returns as it is a nonblocking action. As we don't wait for the node to be deleted nor verify that it's gone we can run into a state where we're running the apply command but don't create a new node as the old one has the same name and is in the state of deletion.
One solution could be to move the waiting after the deletion of machines rather than after applying.
