### ISSUE TITLE
kops-controller DNS name should be configurable

### ISSUE THREAD

**Issue by rwunderer** [kubernetes/kops#10899]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

About a year ago company re-branding caused a change of DNS domain for our kOps clusters. It is currently not possible to rename a running cluster (see #298) so we adjusted the following settings in order to not have to re-create everything from scratch:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: production.old-domain.com
spec:
  configBase: s3://my-clusters-bucket/production.old-domain.com
  dnsZone: new-domain.com
  masterInternalName: api.internal.production.new-domain.com
  masterPublicName: api.production.new-domain.com
...
```

So far this has been working perfectly.

Upgrading to kops 1.19 / k8s 1.19 broke things however, forcing us to downgrade again to k8s 1.18: new worker-nodes hang on trying to join the cluster as they are unable to reach `kops-controller.internal.production.old-domain.com`. 
This is because `old-domain.com` does not exists anymore so the correct A record cannot be set, nor can the name be resolved later.

The root cause is that the dns entry for kops-controller is being set to `kops-controller.internal.{{ ClusterName }}`

Everything would still work if we could customize that entry to `kops-controller.internal.production.new-domain.com`.

**2. Feel free to provide a design supporting your feature request.**

Either of the following would solve our issue:

* Add a new optional `kopsControllerInternalName` field to Cluster spec
* or derive the dns entry by removing the hostname part from `masterInternalName` and replacing it with `kops-controller`.

_**NB**: I considered filing a bug, but on studying the documentation I got the feeling that using a domain name different from cluster name is not strictly supported. Still I can think of other situations where the current behavior might lead to problems and the proposed change seems to be of little impact while helping a log in situations like this._
