### ISSUE TITLE
kops cluster upgrade fails with kops-controller left in CrashLoopBack

### ISSUE THREAD

**Issue by lowrylp** [kubernetes/kops#10902]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster ^
     --cloud=aws ^
     --kubernetes-version=1.18.8 ^
     --name=%ClusterName% ^
     --master-zones=us-west-2a,us-west-2b,us-west-2c ^
     --master-count=3 ^
     --master-size=m5.large ^
     --zones=us-west-2a,us-west-2b,us-west-2c  ^
     --node-size=m5.large ^
     --node-count=3 ^
     --topology private ^
     --networking weave ^
     --dns public ^
     --ssh-public-key R:\mykey.pub

kops update cluster --name sheltie.llowry.net --yes --admin
kops validate cluster --wait 10m
kops upgrade cluster sheltie.llowry.net
kops upgrade cluster sheltie.llowry.net --yes
kops update cluster sheltie.llowry.net --yes
kubectl get pods -n kube-system

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Created a new temp cluster.

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-02-22T22:12:59Z"
  name: sheltie.llowry.net
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://aws-bucket/sheltie.llowry.net
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.8
  masterPublicName: api.sheltie.llowry.net
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: 172.20.0.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 172.20.4.0/22
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 172.20.8.0/22
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/lowrylp/d546eb1980a0952d1f682083b78f0122

**9. Anything else do we need to know?**
R:\>kubectl get pods -n kube-system
NAME                                                                   READY   STATUS             RESTARTS   AGE
dns-controller-7b99485889-kndzq                                        1/1     Running            0          19m
etcd-manager-events-ip-172-20-113-127.us-west-2.compute.internal       1/1     Running            0          19m
etcd-manager-events-ip-172-20-36-43.us-west-2.compute.internal         1/1     Running            0          19m
etcd-manager-events-ip-172-20-89-54.us-west-2.compute.internal         1/1     Running            0          18m
etcd-manager-main-ip-172-20-113-127.us-west-2.compute.internal         1/1     Running            0          19m
etcd-manager-main-ip-172-20-36-43.us-west-2.compute.internal           1/1     Running            0          19m
etcd-manager-main-ip-172-20-89-54.us-west-2.compute.internal           1/1     Running            0          19m
kops-controller-2tzkn                                                  1/1     Running            0          18m
kops-controller-44md8                                                  0/1     CrashLoopBackOff   7          12m
kops-controller-rb7q4                                                  0/1     CrashLoopBackOff   7          12m
kube-apiserver-ip-172-20-113-127.us-west-2.compute.internal            2/2     Running            1          18m
kube-apiserver-ip-172-20-36-43.us-west-2.compute.internal              2/2     Running            1          18m
kube-apiserver-ip-172-20-89-54.us-west-2.compute.internal              2/2     Running            1          18m
kube-controller-manager-ip-172-20-113-127.us-west-2.compute.internal   1/1     Running            0          19m
kube-controller-manager-ip-172-20-36-43.us-west-2.compute.internal     1/1     Running            0          19m
kube-controller-manager-ip-172-20-89-54.us-west-2.compute.internal     1/1     Running            0          19m
kube-dns-677d5df9b4-n5d6n                                              3/3     Running            0          19m
kube-dns-677d5df9b4-xpgj2                                              3/3     Running            0          17m
kube-dns-autoscaler-7f87957f46-q79fx                                   1/1     Running            0          19m
kube-proxy-ip-172-20-112-54.us-west-2.compute.internal                 1/1     Running            0          16m
kube-proxy-ip-172-20-113-127.us-west-2.compute.internal                1/1     Running            0          19m
kube-proxy-ip-172-20-36-43.us-west-2.compute.internal                  1/1     Running            0          19m
kube-proxy-ip-172-20-56-133.us-west-2.compute.internal                 1/1     Running            0          17m
kube-proxy-ip-172-20-64-242.us-west-2.compute.internal                 1/1     Running            0          18m
kube-proxy-ip-172-20-89-54.us-west-2.compute.internal                  1/1     Running            0          19m
kube-scheduler-ip-172-20-113-127.us-west-2.compute.internal            1/1     Running            0          19m
kube-scheduler-ip-172-20-36-43.us-west-2.compute.internal              1/1     Running            0          19m
kube-scheduler-ip-172-20-89-54.us-west-2.compute.internal              1/1     Running            0          19m
weave-net-5g2vd                                                        2/2     Running            2          18m
weave-net-5qv8n                                                        2/2     Running            0          19m
weave-net-72dxv                                                        2/2     Running            1          18m
weave-net-9dz79                                                        2/2     Running            0          19m
weave-net-jmlzs                                                        2/2     Running            0          19m
weave-net-rbt2t                                                        2/2     Running            0          18m

R:\>kubectl logs kops-controller-44md8 -n kube-system
E0222 22:42:18.778796       1 main.go:107] setup "msg"="unable to start server" "error"="reading \"ca\" certificate: open /etc/kubernetes/kops-controller/pki/ca.pem: no such file or directory"

R:\>kubectl describe pod kops-controller-44md8 -n kube-system
Name:                 kops-controller-44md8
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 ip-172-20-36-43.us-west-2.compute.internal/172.20.36.43
Start Time:           Mon, 22 Feb 2021 14:31:21 -0800
Labels:               controller-revision-hash=7946ffbd97
                      k8s-addon=kops-controller.addons.k8s.io
                      k8s-app=kops-controller
                      pod-template-generation=2
                      version=v1.19.0
Annotations:          dns.alpha.kubernetes.io/internal: kops-controller.internal.sheltie.llowry.net
Status:               Running
IP:                   172.20.36.43
IPs:
  IP:           172.20.36.43
Controlled By:  DaemonSet/kops-controller
Containers:
  kops-controller:
    Container ID:  docker://f95a1d4f1399eaec97e984e13750117238f0157da897264594a6faf671a495bb
    Image:         k8s.gcr.io/kops/kops-controller:1.19.0
    Image ID:      docker-pullable://k8s.gcr.io/kops/kops-controller@sha256:7eca9d6e744afdc0f116a91697560b53a0fde5702353d28a5a29fcbf8922c2f0
    Port:          <none>
    Host Port:     <none>
    Command:
      /kops-controller
      --v=2
      --conf=/etc/kubernetes/kops-controller/config/config.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 22 Feb 2021 14:42:18 -0800
      Finished:     Mon, 22 Feb 2021 14:42:18 -0800
    Ready:          False
    Restart Count:  7
    Requests:
      cpu:        50m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /etc/kubernetes/kops-controller/config/ from kops-controller-config (rw)
      /etc/kubernetes/kops-controller/pki/ from kops-controller-pki (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kops-controller-token-2tgh4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kops-controller-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kops-controller
    Optional:  false
  kops-controller-pki:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/kops-controller/
    HostPathType:  Directory
  kops-controller-token-2tgh4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kops-controller-token-2tgh4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kops.k8s.io/kops-controller-pki=
                 node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned kube-system/kops-controller-44md8 to ip-172-20-36-43.us-west-2.compute.internal
  Normal   Pulled     11m (x5 over 13m)     kubelet            Container image "k8s.gcr.io/kops/kops-controller:1.19.0" already present on machine
  Normal   Created    11m (x5 over 13m)     kubelet            Created container kops-controller
  Normal   Started    11m (x5 over 13m)     kubelet            Started container kops-controller
  Warning  BackOff    3m10s (x47 over 13m)  kubelet            Back-off restarting failed container

R:\>
