### ISSUE TITLE
Panic during kops update cluster

### ISSUE THREAD

**Issue by omg-sr** [kubernetes/kops#10908]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

I0223 10:06:57.744484    4932 featureflag.go:167] FeatureFlag "Spotinst"=true
Version 1.19.1 (git-8589b4d157a9cb05c54e320c77b0724c4dd094b2)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops update cluster --name "****" \
    --out "terraform/****-k8s" \
    --target "terraform" \
    --create-kube-config="false" \
    --yes
```

**5. What happened after the commands executed?**

I0223 10:05:48.529332    4907 featureflag.go:167] FeatureFlag "Spotinst"=true
I0223 10:05:55.861894    4907 executor.go:111] Tasks: 0 done / 130 total; 62 can run
I0223 10:05:55.865672    4907 dnszone.go:242] Check for existing route53 zone to re-use with name "----"
I0223 10:05:56.221819    4907 dnszone.go:249] Existing zone "----" found; will configure TF to reuse
I0223 10:05:56.876196    4907 executor.go:111] Tasks: 62 done / 130 total; 26 can run
I0223 10:05:57.003594    4907 executor.go:111] Tasks: 88 done / 130 total; 32 can run
I0223 10:05:59.753100    4907 executor.go:111] Tasks: 120 done / 130 total; 7 can run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x304423f]

goroutine 777 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/spotinsttasks.(*Elastigroup).Find(0xc0012b7560, 0xc000f91180, 0x0, 0x0, 0x0)
        upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go:345 +0x10ff
reflect.Value.call(0x40103c0, 0xc0012b7560, 0xe13, 0x4141c26, 0x4, 0xc000994560, 0x1, 0x1, 0x4774f20, 0xc000530360, ...)
        GOROOT/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x40103c0, 0xc0012b7560, 0xe13, 0xc000994560, 0x1, 0x1, 0xc0012b7560, 0xe13, 0xc000530360)
        GOROOT/src/reflect/value.go:337 +0xb9
k8s.io/kops/util/pkg/reflectutils.InvokeMethod(0x40103c0, 0xc0012b7560, 0x4141cba, 0x4, 0xc0011dfdb0, 0x1, 0x1, 0x4000580, 0x40b0360, 0x4010300, ...)
        util/pkg/reflectutils/walk.go:77 +0x3d9
k8s.io/kops/upup/pkg/fi.invokeFind(0x46a6180, 0xc0012b7560, 0xc000f91180, 0x7f755c241c20, 0xc0012b7560, 0x1, 0x10)
        upup/pkg/fi/default_methods.go:123 +0xb4
k8s.io/kops/upup/pkg/fi.DefaultDeltaRunMethod(0x46a6180, 0xc0012b7560, 0xc000f91180, 0x1, 0xc000a484b0)
        upup/pkg/fi/default_methods.go:47 +0x705
k8s.io/kops/upup/pkg/fi/cloudup/spotinsttasks.(*Elastigroup).Run(0xc0012b7560, 0xc000f91180, 0xc000a484b0, 0x0)
        upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go:452 +0x45
k8s.io/kops/upup/pkg/fi.(*executor).forkJoin.func1(0xc0012b40e0, 0x7, 0x7, 0xc000e22dc0, 0xc00025b440, 0xc00101e0e0, 0x6)
        upup/pkg/fi/executor.go:187 +0x1ae
created by k8s.io/kops/upup/pkg/fi.(*executor).forkJoin
        upup/pkg/fi/executor.go:183 +0x105

**6. What did you expect to happen?**

I would expect this command to work correctly and without error.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-01-06T09:23:14Z"
  generation: 60
  name: "****"
spec:
  additionalPolicies:
    master: |
      "****"
    node: |
      "****"
  api:
    loadBalancer:
      sslCertificate: "****"
      type: Internal
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    spotinstOrientation: balanced
    spotinstProduct: Linux/UNIX (Amazon VPC)
  cloudProvider: aws
  configBase: "****"
  dnsZone: "****"
  encryptionConfig: true
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
  fileAssets:
  - content: |
      "****"
    name: aws-encryption-provider.yaml
    path: /etc/kubernetes/manifests/aws-encryption-provider.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authorizationMode: RBAC,Node
    disableBasicAuth: true
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - PodSecurityPolicy
    enableProfiling: false
    featureGates:
      TTLAfterFinished: "true"
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - "****"
  - "****"
  kubernetesVersion: 1.18.15
  masterInternalName: "****"
  masterPublicName: "****"
  networkCIDR: "****"
  networkID: "****"
  networking:
    calico:
      mtu: 8912
  nonMasqueradeCIDR: "****"
  sshAccess:
  - "****"
  subnets:
  - cidr: 172.30.40.0/24
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.30.41.0/24
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.30.36.0/24
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.30.37.0/24
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.30.38.0/24
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.30.39.0/24
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I0223 10:11:01.098143    5026 aws_cloud.go:1434] Calling DescribeImages to resolve name "099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1"
I0223 10:11:01.098242    5026 request_logger.go:45] AWS request: ec2/DescribeImages
I0223 10:11:01.186241    5026 aws_cloud.go:1496] Resolved image "ami-0da36f7f059b7086e"
I0223 10:11:01.186356    5026 network_load_balancer.go:217] Listing all NLBs for findNetworkLoadBalancerByNameTag
I0223 10:11:01.186500    5026 request_logger.go:45] AWS request: elasticloadbalancing/DescribeLoadBalancers
I0223 10:11:01.544961    5026 network_load_balancer.go:301] Querying ELBV2 api for tags for [----]
I0223 10:11:01.545279    5026 request_logger.go:45] AWS request: elasticloadbalancing/DescribeTags
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x304423f]

goroutine 675 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/spotinsttasks.(*Elastigroup).Find(0xc000ca8fc0, 0xc000874280, 0x0, 0x0, 0x0)
        upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go:345 +0x10ff
reflect.Value.call(0x40103c0, 0xc000ca8fc0, 0xe13, 0x4141c26, 0x4, 0xc00060e980, 0x1, 0x1, 0x4774f20, 0xc000f98300, ...)
        GOROOT/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x40103c0, 0xc000ca8fc0, 0xe13, 0xc00060e980, 0x1, 0x1, 0xc000ca8fc0, 0xe13, 0xc000f98300)
        GOROOT/src/reflect/value.go:337 +0xb9
k8s.io/kops/util/pkg/reflectutils.InvokeMethod(0x40103c0, 0xc000ca8fc0, 0x4141cba, 0x4, 0xc000e65db0, 0x1, 0x1, 0x4000580, 0x40b0360, 0x4010300, ...)
        util/pkg/reflectutils/walk.go:77 +0x3d9
k8s.io/kops/upup/pkg/fi.invokeFind(0x46a6180, 0xc000ca8fc0, 0xc000874280, 0x7f8fc4f7a410, 0xc000ca8fc0, 0xc001199e01, 0xc000e65e68)
        upup/pkg/fi/default_methods.go:123 +0xb4
k8s.io/kops/upup/pkg/fi.DefaultDeltaRunMethod(0x46a6180, 0xc000ca8fc0, 0xc000874280, 0x630f898, 0xc0002ca1c0)
        upup/pkg/fi/default_methods.go:47 +0x705
k8s.io/kops/upup/pkg/fi/cloudup/spotinsttasks.(*Elastigroup).Run(0xc000ca8fc0, 0xc000874280, 0x0, 0x0)
        upup/pkg/fi/cloudup/spotinsttasks/elastigroup.go:452 +0x45
k8s.io/kops/upup/pkg/fi.(*executor).forkJoin.func1(0xc001262c80, 0x5, 0x5, 0xc000bb9170, 0xc000f0c7e0, 0xc0004f6690, 0x2)
        upup/pkg/fi/executor.go:187 +0x1ae
created by k8s.io/kops/upup/pkg/fi.(*executor).forkJoin
        upup/pkg/fi/executor.go:183 +0x105

**9. Anything else do we need to know?**

I only get this after trying to upgrade my kops version to 1.19.x, I haven't made any updates to the cluster yaml and I don't see this panic with kops 1.18.x

Thanks
