### ISSUE TITLE
externalPolicies sort order affects kops update cluster change tracking

### ISSUE THREAD

**Issue by gregkoganvmm** [kubernetes/kops#10939]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.20.4
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops edit cluster`
add an "externalPolicies" section with 2 list items:
```
externalPolicies:
    master:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    node:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    - arn:aws:iam::8xxx:policy/AWSLoadBalancerControllerIAMPolicy
 ```
`kops update cluster --yes`
**5. What happened after the commands executed?**
running it the first time shows pending changes
running `kops update cluster` the second time shows the same change pending

```
Will modify resources:
  IAMRolePolicy/node-policyoverride
  	ExternalPolicies    	 [arn:aws:iam::8xxx:policy/AWSLoadBalancerControllerIAMPolicy, arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore] -> [arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore, arn:aws:iam::872709308123:policy/AWSLoadBalancerControllerIAMPolicy]
  	Managed             	 true -> true
```

**6. What did you expect to happen?**
No changes should be pending. If the order of policies is reversed as below, no changes are pending, so this appears to be a sorting issue when comparing existing vs pending state.

```
externalPolicies:
    master:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    node:
    - arn:aws:iam::8xxx:policy/AWSLoadBalancerControllerIAMPolicy
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore    
 ```
