### ISSUE TITLE
kops should support creating internal (VPC only) ELBs for apiserver / bastion

### ISSUE THREAD

**Issue by mtanski** [kubernetes/kops#1097]
After playing around with different tools for deploying kubernetes on AWS I settled on kops. One thing I was not able to find / make work is creating internal (VPC only) ELB instances. I've searched the documentation and code in the repository. After asking on the kubernets slack instance it turns out it's not currently supported.

In the current state it's possible to create a cluster that places into a VPC only subnet (by setting private topology) but strangely the ELB that is created for the private apiserver/bastion host using a internet-facing ELB.

Our use case is running a entirely private kubernets cluster that only used other by internal services (including existing ones) and we would not like to expose the apiserver to the outside world.

**Comment by chrislovecnm** [comment]
Currently, we do no have that feature.  Happy to have that feature in the model, if you would like to contribute.

**Comment by mtanski** [comment]
Sure thing @chrislovecnm. I do need some guidance how to go around this, esp. the yaml conf part of it.

My initial instinct tells me to:
- make the internet-facing ELB default for backwards
- add apiserver to topology
- add elb subsection to topology.(bastion|apiserver)

```
...
    topology:                                                                                         
    bastion:
      enabled: true
      elb: { internal: true }
    apiserver:
      elb: { internal: true }
    masters: private
    nodes: private
```

Given some guidance on the approach I can go ahead and implement it.

**Comment by chrislovecnm** [comment]
@kris-nova / @justinsb ... Ideas?

@mtanski the bastion is getting moved into an an instancegroup as well. Best advice I have for u is to submit a design PR and we can work through it.

**Comment by kris-nova** [comment]
This might be an API change - if it is, this means we will need a design doc in the PR, and we should all be looking at 

I would wait to start this until after https://github.com/kubernetes/kops/milestone/1 which should be released this week - we will know more then what the design of this will look like :)

**Comment by justinsb** [comment]
This will work in alpha4 once it is release (i.e. once the pending PRs have merged and we do the release) :-)

Here's how it should work:

`kops create cluster --topology private --channel alpha --zones us-east-1c name.example.com --networking kopeio-vxlan`

If you then `kops edit cluster name.example.com`, there will be a section

```
spec:
  api:
    loadBalancer:
      type: Public
```

which you'll have to change to

```
spec:
  api:
    loadBalancer:
      type: Internal
```

And then `kops update cluster` etc as usual

**Comment by justinsb** [comment]
This should work in kops 1.5.0 beta1, which is now released, so I'm going to close.  But if this is not fixed in 1.5.0 beta1 or later, please comment or reopen.

**Comment by jamesgoodhouse** [comment]
Setting loadBalancer type to Internal appears to only affect the API server, and not the bastion server. Is this the intended behavior, or maybe I'm misunderstanding how one would set the bastion LB to be internal also?

**Comment by dlouzan** [comment]
Though justinsb's message states that this should be working since kops 1.5.0 beta1, using kops 1.5.1 I'm not able to switch an automatically created public ELB to an internal ELB, I get the following error after editing my cluster and triggering a cluster update:

```
I0313 15:30:12.011348   21686 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
I0313 15:30:22.011602   21686 executor.go:91] Tasks: 59 done / 62 total; 1 can run
W0313 15:30:22.069016   21686 executor.go:109] error running task "LoadBalancer/api.k8s.sob-prod.local" (7m8s remaining to succeed): subnet changes on LoadBalancer not yet implemented: actual=[subnet-c2c0a8aa] -> expected=[subnet-d5c0a8bd]
I0313 15:30:22.069119   21686 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
```

My configuration is as follows:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2017-02-22T13:55:14Z"
  name: k8s.sob-prod.local
spec:
  api:
    loadBalancer:
      type: Public
  channel: stable
  cloudProvider: aws
  configBase: s3://<hidden>
  dnsZone: <hidden>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.5.2
  masterInternalName: api.internal.k8s.sob-prod.local
  masterPublicName: api.k8s.sob-prod.local
  networkCIDR: 10.110.0.0/16
  networkID: vpc-f2c06d9a
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.110.8.0/24
    egress: nat-02d62e637dd9b7838
    id: subnet-d5c0a8bd
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.110.0.0/24
    id: subnet-c2c0a8aa
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

I am trying to change the api.loadBalancer from Public to Internal

Am I missing anything?
