### ISSUE TITLE
roleCustomIamRoles doesn't work

### ISSUE THREAD

**Issue by jcmartins** [kubernetes/kops#11001]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops version 1.19.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Kubernetes 1.19.8

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create -f my-cluster.yaml
kops update my-cluster.k8s.local --yess

**5. What happened after the commands executed?**
Kops try to create the roles rather then roles declared in the roleCustomIamRoles

**6. What did you expect to happen?**
Use the role  existing in the iam declared in the roleCustomIamRoles

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
roleCustomIamRoles:
    master: arn:aws:iam::xxxxxxxx:role/BURoleForKopsMaster
    node: arn:aws:iam::xxxxxxxxx:role/BURoleForKopsNode

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: master-sa-east-1a
spec:
  iam:
    profile: arn:aws:iam::xxxxxxxxxx:instance-profile/InstanceProfileForKopsMaster
  associatePublicIp: false
  image: ami-xxxxxxxxxxx
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-sa-east-1a
  role: Master
  subnets:
  - sa-east-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

 is not authorized to perform: iam:CreateRole on resource

**9. Anything else do we need to know?**
The message error is try to CreateRole but I would like use the existing role declared in the roleCustomIamRoles ( BURoleForKopsMaster )
