### ISSUE TITLE
InsecureRegistries present not correct setting in DOCKER_OPTS

### ISSUE THREAD

**Issue by maohsiang** [kubernetes/kops#11024]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.19.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.8

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kop replace, kops create

**5. What happened after the commands executed?**
cat /etc/sysconfig/docker 
DOCKER_OPTS=--insecure-registry=first.docker.registry, second.docker.registry 

**6. What did you expect to happen?**
cat /etc/sysconfig/docker 
DOCKER_OPTS=--insecure-registry=first.docker.registry --insecure-registry=second.docker.registry 

**9. Anything else do we need to know?**
Docker ver: 20.10.3

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{env "FULL_NAME"}}
spec:
  docker:
    version: 20.10.3
    insecureRegistries:
    - first.docker.registry
    - second.docker.registry 
    registryMirrors:
    - http://docker.mirror
```
