### ISSUE TITLE
[toolbox]: instance selector with arm64 arch, outputs wrong arch image

### ISSUE THREAD

**Issue by sachincool** [kubernetes/kops#11023]
kops Version: 1.19.1 

cli-command:

`kops toolbox  instance-selector nodes --vcpus 4 --flexible --usage-class spot --cpu-architecture arm64 --dry-run `

output:
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: test.k8s.local
  name: nodes
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/prod.k8s.local: "1"
    kops.k8s.io/instance-selector: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: a1.xlarge
  maxSize: 10
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - a1.xlarge
    - c6g.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-south-1a
  - ap-south-1b
  - ap-south-1c
  ```
  
  The AMI  : `099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1` is x86_64
  
  Expected:  Output AMI should be of the same Arch
