### ISSUE TITLE
[toolbox]: assets bundle for offline mirror

### ISSUE THREAD

**Issue by guydog28** [kubernetes/kops#11033]
Currently it is required to do a `kop update cluster` dry run to see what all resources are going to be downloaded when deploying a cluster.  For staging an offline (completely no internet access) cluster with a local mirror, request a toolbox command that will download all of the required kubernetes, kops, cni, etc resources and sha256 files to a local destination for eventual use by Cluster/assets/fileRepository.  It's worth noting that this command is run from an environment _with_ internet access, and the the files will be moved to the constrained environment for use in deploying the offline cluster.  

Potential commands:

`kops toolbox assets-bundle`:   downloads everything in proper file structure to current directory (possibly add flag to provide directory)
`kops toolbox assets-bundle --dry-run`: only prints the URLs only to the assets that would be downloaded

**Comment by guydog28** [comment]
@justinsb re: office hours 3/12/2021

**Comment by guydog28** [comment]
This is currently my process for staging assets for an offline mirror, but it requires creating a temp cluster and a cluster spec to download the assets and then delete the cluster.

1. Using kOps version 19.1, create a simple spec to stage files to a local folder to create an asset mirror:
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: offline.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  assets:
    fileRepository: /local/path/to/staged/asset_folder
    # below will be used when actually deploying using my "no-internet-available mirror"
    # fileRepository: http://resolvable-mirror-url-in-captive-environment/
  authorization:
    rbac: {}
  # channel: http://resolvable-mirror-url-in-captive-environment/channels/stable
  cloudProvider: aws
  configBase: s3://kops-state-store/offline.k8s.local
  containerd:
    version: 1.4.3
  containerRuntime: containerd
  kubeDNS:
    provider: CoreDNS
  etcdClusters:
  - cpuRequest: 200m
    enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 512Mi
    name: main
    manager:
    version: 3.4.13
  - cpuRequest: 200m
    enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 512Mi
    name: events
    manager:
    version: 3.4.13
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.8
  masterInternalName: api.internal.offline.k8s.local
  masterPublicName: api.offline.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: offline.k8s.local
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a

  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: offline.k8s.local
  name: bastions
spec:
  image: ami-id-you-use
  machineType: t3a.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: offline.k8s.local
  name: master-us-east-1a
spec:
  image: ami-id-you-use
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: offline.k8s.local
  name: nodes-ondemand-1a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/offline.k8s.local: ""
  image: ami-id-you-use
  machineType: m5a.xlarge
  maxSize: 8
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: on-demandig-1a
    on-demand: "true"
  role: Node
  rollingUpdate:
    maxSurge: 8
  subnets:
  - us-east-1a

```
2. Using, above file, create cluster records in temporary internet-connected S3 `kops create -f kops-offline.k8s.local.yaml`
3. Stage Assets to `/local/path/to/staged/asset_folder` as specified in the cluster spec using `kops update cluster --yes --phase assets -v 4`
4.  Manually move files at `/local/path/to/staged/asset_folder` to mirror URL specified in commented out `fileRepository` in captive environment (`http://resolvable-mirror-url-in-captive-environment/`)
5. Now that I have my mirror, clean up temp environment with `kops delete cluster --yes`

That's the process, the below is what I do after for any readers who want to do this today.

6. Move cluster yaml to captive environment and switch `fileRepository` to use the mirror URL and uncomment `channel`
7. Create cluster records in captive environment with `kops create -f kops-offline.k8s.local.yaml`
8. Deploy cluster resources with `kops update cluster --yes`
