### ISSUE TITLE
container-selinux still has hard-coded internet location, and does not map via assets/fileRepository for isolated environments.

### ISSUE THREAD

**Issue by guydog28** [kubernetes/kops#11038]
This appears to be the last remaining item that can't be mirrored for offline cluster downloading in the assets phase.

https://github.com/kubernetes/kops/blob/5857e9d2c4eb07fa2d3693d69275d2a7552f2ac1/nodeup/pkg/model/packages.go#L73

**Comment by hakman** [comment]
Not quite sure how you get to this in the assets phase.

**Comment by guydog28** [comment]
This is for a RHEL 7.9 deployment (I'm required to used that for this deployment). Specifically though, I can stage all assets locally using the assets phase and a local file folder as my fileRepository.  I can then sync that folder to a mirror location accessible in my offline cluster environment.  Then change the fileRepository to use that mirror URL in my offline/no-internet environment. I can verify then that all assets are downloaded from my mirror, with the exception of this, which still reaches for the internet.  This was tested in 19.1.

**Comment by hakman** [comment]
One request, if you don't mind. Please specify in all tickets:
1. the kOps version you use and a simple cluster spec that can be used to reproduce things
2. command / output / logs that can make it easier to reproduce.

In this case, I am not sure you are using RHEL 7 or CentOS 7, given what I see in code:
https://github.com/kubernetes/kops/blob/de65803ceb0d01826acbbb840f3455dba275be82/nodeup/pkg/model/packages.go#L68-L81

**Comment by guydog28** [comment]
1. kOps version 19.1, simple spec to stage files to a local folder to create an asset mirror:
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: offline.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  assets:
    fileRepository: /local/path/to/staged/asset_folder
    # below will be used when actually deploying using my "no-internet-available mirror"
    # fileRepository: http://resolvable-mirror-url-in-captive-environment/
  authorization:
    rbac: {}
  # channel: http://resolvable-mirror-url-in-captive-environment/channels/stable
  cloudProvider: aws
  configBase: s3://kops-state-store/offline.k8s.local
  containerd:
    version: 1.4.3
  containerRuntime: containerd
  kubeDNS:
    provider: CoreDNS
  etcdClusters:
  - cpuRequest: 200m
    enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 512Mi
    name: main
    manager:
    version: 3.4.13
  - cpuRequest: 200m
    enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 512Mi
    name: events
    manager:
    version: 3.4.13
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.8
  masterInternalName: api.internal.offline.k8s.local
  masterPublicName: api.offline.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: offline.k8s.local
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a

  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: offline.k8s.local
  name: bastions
spec:
  image: ami-id-for-rhel79
  machineType: t3a.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: offline.k8s.local
  name: master-us-east-1a
spec:
  image: ami-id-for-rhel79
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: offline.k8s.local
  name: nodes-ondemand-1a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/offline.k8s.local: ""
  image: ami-id-for-rhel79
  machineType: m5a.xlarge
  maxSize: 8
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: on-demandig-1a
    on-demand: "true"
  role: Node
  rollingUpdate:
    maxSurge: 8
  subnets:
  - us-east-1a

```
2. Using, above file, create cluster records in temporary internet-connected S3 `kops create -f kops-offline.k8s.local.yaml`
3. Stage Assets to `/local/path/to/staged/asset_folder` using `kops update cluster --yes --phase assets -v 4`
4.  Manually move files at `/local/path/to/staged/asset_folder` to mirror URL specified in commented out `fileRepository` in captive environment (`http://resolvable-mirror-url-in-captive-environment/`)
5. Now that I have my mirror, clean up temp environment with `kops delete cluster --yes`
6. Move cluster yaml to captive environment and switch `fileRepository` to use the mirror URL and uncomment `channel`
7. Create cluster records in captive environment with `kops create -f kops-offline.k8s.local.yaml`
8. Deploy cluster resources with `kops update cluster --yes`
9. Watch logs on master and nodes, and verify that all assets are downloaded from `http://resolvable-mirror-url-in-captive-environment/`, except it tries to install `container-selinux` from internet URL at `http://vault.centos.org/7.6.1810/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm`

**Comment by guydog28** [comment]
The issue is this `http://vault.centos.org/7.6.1810/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm` is treated like a hardcoded edge case in this code.  Perhaps in the assets phase, it could download this file just in case you are deploying to CentOS or RHEL if it doesn't know this from the specified AMI ID yet at that point.  Then, if this is downloaded to assets, and `fileRepository` is specified, it would pull the RPM from `http://resolvable-mirror-url-in-captive-environment/centos/7.6.1810/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm` instead

**Comment by hakman** [comment]
I think I understand the issue. The file is used in RHEL setups because that file is not available in any free repo.
I think though it should be possible to add a condition there and try `fileRepository` when it's set.

**Comment by guydog28** [comment]
Yes, that would work.  So two parts:

1. Assets phase downloads that file to my local `/local/path/to/staged/asset_folder` to create my mirror.
2. This code would try to dowload from `http://resolvable-mirror-url-in-captive-environment/centos/7.6.1810/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm` if `fileRepository` is set.

**Comment by hakman** [comment]
I think there may be a confusion regarding the assets phase in general. We call assets phase the part where kOps tracks various files it needs later, like kubelet, kubectl, docker, containerd and a few others. At this point, everything is generic, no info on OS type. One could have N different IGs, with different OS on each one.

The packages part is different and has nothing to do with the assets. It just tries to install some packages from what mirrors are configured on the hosts, but has some complicated approach for that file. It is actually the only one handled that way.

One option would be to create a new AMI using Packer or something similar, that has this file already. If it already exists, it won't be downloaded again.
"/var/cache/nodeup/packages/container-selinux.rpm": sha1:7de4211fa0dfd240d8827b93763e1eb5f0d56411
If

**Comment by guydog28** [comment]
hmm, in that case maybe a separate approach may be even better. 

what if kOps also looked at four folders in the `fileRepository` URL, `bastions`, `masters`, `nodes`, and `packages`.  Any file here would be downloaded to the instance when it comes up.  For instance, in my `fileRepository` mirror, i may see the following folders:

```
**bastions**
containerd
k8s-artifacts-cni
kops
kubnernetes-release
linux
**masters**
**nodes**
**packages**
```

inside `packages` I could place `container-selinux.rpm` and `container-selinux.rpm.sha256` and kOps would download them to `/var/cache/nodeup/packages`. 

Then `masters`, `nodes`, and `bastions` could download files to a predictable location that scripts specified in the `fileAssets` section that could do something with those files.  

then could do in my cluster spec:

```
spec: 
  fileAssets:
  - name: install rpms
    # Note if not path is specified the default path it /srv/kubernetes/assets/<name>
    path: /var/lib/my-script
    roles: 
    - Master
    - Node 
    content: |
      # script run on an archive located in both `masters` and `nodes` folder
```

This solution would provide a lot of flexibility in environments without internet.

Additionally, since I receive my AMIs from another team, I don't have to create a new AMI that adds container-selinux every time they provide and update.  I just change the ami ID in my IG spec and container-linux gets downloaded and installed from my mirror.

**Comment by guydog28** [comment]
I think the `masters`, `nodes`, `bastions` solution likely could go into another "improvement" ticket.  But the `packages` folder would solve this ticket.

**Comment by hakman** [comment]
You already have:
1. https://kops.sigs.k8s.io/instance_groups/#additionaluserdata
2. https://kops.sigs.k8s.io/cluster_spec/#hooks

I would suggest using one of them to download the package. What do you think?

**Comment by guydog28** [comment]
I was able to successfully download the package using: 

```
spec:
  additionalUserData:
  - name: a-stage-container-selinux.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      rpm --import http://path/to/mirror/RPM-GPG-KEY-CentOS-7
      curl-L http://path/to/mirror/7.6.1810/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm > /var/cache/nodeup/packages/container-selinux.rpm
```

However I have to run this script manually to get it to work... it doesn't download the file as part of cloud-init. does cloud-init have the rights to write this file at that stage?
