### ISSUE TITLE
Cluster Creation Fails Due to etcd Volume Mounting Error

### ISSUE THREAD

**Issue by chodges15** [kubernetes/kops#11115]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.19.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**
Openstack
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster --cloud openstack --name my-cluster.k8s.local --state ${KOPS_STATE_STORE} --zones nova --network-cidr 192.170.0.0/16 --image ubuntu_20_04_cloud_init --master-count=1 --node-count=1 --node-size m1.small --master-size m1.small --topology public --ssh-public-key ~/.ssh/cloud_rsa.pub --networking weave --os-ext-net net02 --api-loadbalancer-type="" --os-dns-servers=<redacted> --etcd-storage-type ceph
```

**5. What happened after the commands executed?**
Was able to apply config using `kops update cluster --name my-cluster.k8s.local --yes --admin`, however the validation failed after 10 minutes and the API server never becomes reachable.

etcd volumes created and exist in Openstack. The following shows up in the etcd log on the master nodes:
```
I0322 20:17:45.787441    6518 volumes.go:309] Listing Openstack disks in 5d96bcea99114f7497a54e820687f869/nova
I0322 20:17:46.858168    6518 mounter.go:294] Trying to mount master volume: "c9debe4a-e66e-40a3-be6d-3ec15259871a"
I0322 20:17:50.585272    6518 mounter.go:308] Currently attached volumes: [0xc000111180]
I0322 20:17:50.585344    6518 mounter.go:72] Master volume "c9debe4a-e66e-40a3-be6d-3ec15259871a" is attached at "/dev/hdb"
I0322 20:17:50.585432    6518 mounter.go:86] Doing safe-format-and-mount of /dev/hdb to /mnt/master-a.etcd-main.my-cluster.k8s.local
I0322 20:17:50.585699    6518 volumes.go:408] Could not find device path for volume; scanning buses
I0322 20:17:50.912367    6518 volumes.go:410] Error scanning buses: executable file not found in $PATH
I0322 20:17:56.913512    6518 volumes.go:408] Could not find device path for volume; scanning buses
```
**6. What did you expect to happen?**
Validated and working cluster.
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-03-22T20:12:50Z"
  name: my-cluster.k8s.local
spec:
  api: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        ignore-volume-az: false
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        dnsServers: <redacted>
        externalNetwork: net02
  cloudProvider: openstack
  configBase: swift://k8s/my-cluster.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-nova
      name: a
      volumeType: ceph
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-nova
      name: a
      volumeType: ceph
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.9
  masterPublicName: api.my-cluster.k8s.local
  networkCIDR: 192.170.0.0/16
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 192.170.32.0/19
    name: nova
    type: Public
    zone: nova
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-03-22T20:12:50Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: master-nova
spec:
  image: ubuntu_20_04_cloud_init
  machineType: m1.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-nova
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-03-22T20:12:50Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: nodes-nova
spec:
  image: ubuntu_20_04_cloud_init
  machineType: m1.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-nova
  role: Node
  subnets:
  - nova
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I have tried this and failed on two separate Openstack clusters. I am open to changing my config to get something to work.
