### ISSUE TITLE
nodeLabels not applied after upgrading to kops 1.18.3 (k8s 1.18.17)

### ISSUE THREAD

**Issue by voiser** [kubernetes/kops#11122]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.18.3 (git-11ec695516)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", ...}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17",  ...}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Installed kops 1.18.3 from the github releases and:
```
$  kops upgrade cluster --yes
```

**5. What happened after the commands executed?**

The cluster was successfully upgraded to k8s 1.18.17. Node labels specified in the instancegroup are not set anymore.

**6. What did you expect to happen?**

Node labels specified in the instancegroup are set to the new instances.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-10-06T16:48:18Z"
  generation: 4
  name: xxxxx.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxxxx/xxxxx.com
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - xxxxx
  kubernetesVersion: 1.18.17
  masterInternalName: api.internal.xxxxx.com
  masterPublicName: api.xxxxx.com
  networkCIDR: 10.0.0.0/16
  networkID: vpc-xxxxx
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - xxxxx
  subnets:
  - cidr: 10.0.2.0/24
    id: subnet-aaa
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 10.0.0.0/24
    id: subnet-bbb
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.0.1.0/24
    id: subnet-ccc
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-15T15:24:49Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: xxxxx.com
  name: cpu
spec:
  cloudLabels:
    meaning: cpu
    role: compute
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210315
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: cpu
    meaning: cpu
  role: Node
  subnets:
  - us-east-1c

---

(master nodes follow)
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The labels specified in the 'Node' IG are:

```yaml
  nodeLabels:
    kops.k8s.io/instancegroup: cpu
    meaning: cpu
```

The labels are correctly set in the instance's `ig_spec.yaml` file:

```shell
/opt/kops/conf$ cat ig_spec.yaml
kubelet: null
nodeLabels:
  kops.k8s.io/instancegroup: cpu
  meaning: cpu
taints: null
```

I _guess_ `nodeup` is ignoring this file when creating the systemd kubelet unit, but I'm only guessing. In the user data I see that the `nodeup` version is 1.18.3:

```shell
NODEUP_URL=https://artifacts.k8s.io/binaries/kops/1.18.3/linux/amd64/nodeup,https://github.com/kubernetes/kops/releases/download/v1.18.3/linux-amd64-nodeup,https://kubeupv2.s3.amazonaws.com/kops/1.18.3/linux/amd64/nodeup
NODEUP_HASH=8430d05efa58c0fea0693d8590a22278bac16a754b52670e3bdc3a06ab7391f0
```

Any idea about how can I identify the issue?

Thanks!
