### ISSUE TITLE
Memory resource requests aren't picked up kops

### ISSUE THREAD

**Issue by iamanv** [kubernetes/kops#11197]
I have a use case wherein I am trying to update the resource requests of `kube-apiserver` for a k8s cluster on aws using kops. I tried applying the changes by running `kops_update` with the config changes as follows:

```
kubeAPIServer:
    logLevel: 1
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditPolicyFile: /srv/kubernetes/audit_policy.yml
    insecurePort: 0
    tokenAuthFile: ""
    authorizationMode: "Node,RBAC"
    runtimeConfig:
      autoscaling/v2beta1: "true"
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - StorageObjectInUseProtection
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - Priority
    - ResourceQuota
    - DenyEscalatingExec
    cpuRequest: 400m         ------------------- change1  
    memoryRequest: 1440Mi     ------------------- change2
```

Nodes have sufficient memory and cpu to be allocated for the resource requests. 

```
Also, only the cpu request is detected(as below) or read from the configuration change

Will modify resources:
  LaunchConfiguration
  	UserData
  	                    	...
  	                    	    bindAddress: 0.0.0.0
  	                    	    cloudProvider: aws
  	                    	+   cpuRequest: 400m
  	                    	    enableAdmissionPlugins:
  	                    	    - NamespaceLifecycle
  	                    	...
```
Why isn't the memory change detected as a change to be made to the cluster? Also, a simple kubectl describe on one of the master node reveals that other master node components like kube-scheduler have their memory requests as 0%. Does that mean the memory resource requests cannot be modified? If yes, what would be the best way to do that? Any pointers/suggestion would be very helpful. Thanks
I referred  https://github.com/kubernetes/kops/blob/6f302f0ea7c67be455bc9479e2a6c0ddeed170d8/k8s/crds/kops.k8s.io_clusters.yaml#L1477 for making the resource adjustments. 

![image](https://user-images.githubusercontent.com/73945184/114274389-cb549c80-9a3b-11eb-9f38-9e06aaa66443.png)

**Comment by hakman** [comment]
Hi @iamanv. I can just deduce that you are not using kOps 1.19+, which is when this setting was added: https://github.com/kubernetes/kops/pull/10306.

**Comment by iamanv** [comment]
@hakman Thanks for replying. A quick version check reveals that the kops version is 1.19.1
![image](https://user-images.githubusercontent.com/73945184/114277327-58055780-9a48-11eb-8401-5e96566ba84d.png)

**Comment by hakman** [comment]
I tried to reproduce this and my result is different somehow. Please also note that kOps 1.19 uses launch templates instead of launch configs, so maybe it helps tracking the issue.
```
Will modify resources:
  LaunchTemplate/master-a.masters.kops1.test.hakman.dev
  	UserData            
  	                    	...
  	                    	    bindAddress: 0.0.0.0
  	                    	    cloudProvider: aws
  	                    	+   cpuRequest: 400m
  	                    	    disableBasicAuth: true
  	                    	    enableAdmissionPlugins:
  	                    	...
  	                    	    maxMutatingRequestsInflight: 500
  	                    	    maxRequestsInflight: 1000
  	                    	+   memoryRequest: 1440Mi
  	                    	    requestheaderAllowedNames:
  	                    	    - aggregator
  	                    	...
```

**Comment by iamanv** [comment]
@hakman What steps did you have to take to see the memory change? Would be helpful. Also, I noticed there was no launch template defined for creating instances in my case. It should be a good starting point though.

**Comment by hakman** [comment]
I could say the same about creating the issue without using the template :).
Steps:
1. Create simple cluster using kOps 1.19.1 and k8s 1.17
2. Update the config with:
    ```yaml
      kubeAPIServer:
        cpuRequest: 400m
        memoryRequest: 1440Mi
    ```
3. Run `kops update cluster`
