### ISSUE TITLE
Fresh cluster shows apiserver client certificate expiring, kube controller-manager and scheduler down

### ISSUE THREAD

**Issue by xpepermint** [kubernetes/kops#11211]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.20`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

`AWS / EC2`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```sh
# Create cluster.
$ kops create cluster \
    --node-count 2 \
    --master-count 1 \
    --zones eu-central-1a \
    --master-zones eu-central-1a \
    --networking calico \
    ${NAME}
$ kops update cluster --name XXX --yes --admin
# Install kube-prometheus.
$ git clone https://github.com/prometheus-operator/kube-prometheus.git
$ cd kube-prometheus
$ kubectl create -f manifests/setup
$ kubectl create -f manifests/
$ kubectl --namespace monitoring port-forward svc/prometheus-k8s 9090
=> navigate to `http://localhost:9090/alerts`
```

**5. What happened after the commands executed?**

The Prometheus dashboard shows `5` alerts firing:

```yaml
name: Watchdog
expr: vector(1)
labels:
  severity: none
annotations:
  message: This is an alert meant to ensure that the entire alerting pipeline is functional.
  This alert is always firing, therefore it should always be firing in Alertmanager
  and always fire against a receiver. There are integrations with various notification
  mechanisms that send a notification when this alert is not firing. For example the
  "DeadMansSnitch" integration in PagerDuty.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/watchdog
```

```yaml
name: KubeClientCertificateExpiration
expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
labels:
  severity: warning
annotations:
  description: A client certificate used to authenticate to the apiserver is expiring in less than 7.0 days.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubeclientcertificateexpiration
  summary: Client certificate is about to expire.
```

```yaml
name: KubeClientCertificateExpiration
expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
labels:
  severity: critical
annotations:
  description: A client certificate used to authenticate to the apiserver is expiring in less than 24.0 hours.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubeclientcertificateexpiration
  summary: Client certificate is about to expire.
```

```yaml
name: KubeControllerManagerDown
expr: absent(up{job="kube-controller-manager"} == 1)
for: 15m
labels:
  severity: critical
annotations:
  description: KubeControllerManager has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubecontrollermanagerdown
  summary: Target disappeared from Prometheus target discovery.
```

```yaml
name: KubeSchedulerDown
expr: absent(up{job="kube-scheduler"} == 1)
for: 15m
labels:
  severity: critical
annotations:
  description: KubeScheduler has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubeschedulerdown
  summary: Target disappeared from Prometheus target discovery.
```

**6. What did you expect to happen?**

The Prometheus dashboard should not have `pending` or `firing` alerts only `inactive`. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-04-12T09:05:03Z"
  name: XXX
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://XXX/XXX
  containerRuntime: containerd
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.5
  masterPublicName: api.XXX
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-12T09:05:03Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: master-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210315
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-12T09:05:03Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: nodes-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210315
  machineType: t3.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1a
  role: Node
  subnets:
  - eu-central-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

-

**9. Anything else do we need to know?**

<img width="1145" alt="Screenshot 2021-04-12 at 12 13 52" src="https://user-images.githubusercontent.com/174279/114378986-90ac4a80-9b88-11eb-953b-f19aff86f023.png">
