### ISSUE TITLE
Kops with terraform failing

### ISSUE THREAD

**Issue by vignesh-v-nutanix** [kubernetes/kops#11254]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: v1.21.0

also the terraform version i use is
Terraform v0.14.3

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --name=mykops.tk --state=s3://mykops.tk --authorization RBAC --zones=ap-south-1a --node-count=2 --node-size=t2.micro --master-size=t2.micro --master-count=1 --dns-zone=mykops.tk --out=tfmykops --target=terraform  --ssh-public-key=/Users/vsdgh.v/.ssh/key.pub

cd tfmykops
terraform init

**5. What happened after the commands executed?**
```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Warning: Interpolation-only expressions are deprecated

  on kubernetes.tf line 24, in output "master_autoscaling_group_ids":
  24:   value = ["${aws_autoscaling_group.master-ap-south-1a-masters-mykops-tk.id}"]

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 63 more similar warnings elsewhere)


Error: Unsupported argument

  on kubernetes.tf line 1:
   1: locals = {

An argument named "locals" is not expected here. Did you mean to define a
block of type "locals"?


Error: Attribute redefined

  on kubernetes.tf line 96, in resource "aws_autoscaling_group" "master-ap-south-1a-masters-mykops-tk":
  96:   tag = {

The argument "tag" was already set at kubernetes.tf:90,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 102, in resource "aws_autoscaling_group" "master-ap-south-1a-masters-mykops-tk":
 102:   tag = {

The argument "tag" was already set at kubernetes.tf:90,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 108, in resource "aws_autoscaling_group" "master-ap-south-1a-masters-mykops-tk":
 108:   tag = {

The argument "tag" was already set at kubernetes.tf:90,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 114, in resource "aws_autoscaling_group" "master-ap-south-1a-masters-mykops-tk":
 114:   tag = {

The argument "tag" was already set at kubernetes.tf:90,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 137, in resource "aws_autoscaling_group" "nodes-mykops-tk":
 137:   tag = {

The argument "tag" was already set at kubernetes.tf:131,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 143, in resource "aws_autoscaling_group" "nodes-mykops-tk":
 143:   tag = {

The argument "tag" was already set at kubernetes.tf:131,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 149, in resource "aws_autoscaling_group" "nodes-mykops-tk":
 149:   tag = {

The argument "tag" was already set at kubernetes.tf:131,3-6. Each argument may
be set only once.


Error: Attribute redefined

  on kubernetes.tf line 155, in resource "aws_autoscaling_group" "nodes-mykops-tk":
 155:   tag = {

The argument "tag" was already set at kubernetes.tf:131,3-6. Each argument may
be set only once.


Error: Invalid resource name

  on kubernetes.tf line 288, in resource "aws_route" "0-0-0-0--0":
 288: resource "aws_route" "0-0-0-0--0" {

A name must start with a letter or underscore and may contain only letters,
digits, underscores, and dashes.


Error: Unsupported argument

  on kubernetes.tf line 484:
 484: terraform = {

An argument named "terraform" is not expected here. Did you mean to define a
block of type "terraform"?`
```

**6. What did you expect to happen?**
I wanted the terraform init, plan and apply commands to be successful

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-04-18T07:50:30Z"
  name: mykops.tk
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mykops.tk/mykops.tk
  dnsZone: mykops.tk
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.15
  masterPublicName: api.mykops.tk
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-18T07:50:31Z"
  labels:
    kops.k8s.io/cluster: mykops.tk
  name: master-ap-south-1a
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2021-02-05
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1a
  role: Master
  subnets:
  - ap-south-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-18T07:50:31Z"
  labels:
    kops.k8s.io/cluster: mykops.tk
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2021-02-05
  machineType: t2.micro
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-south-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
NO

**9. Anything else do we need to know?**
No
