### ISSUE TITLE
Cilium 1.9 uses incorrect cilium-operator

### ISSUE THREAD

**Issue by lsowen** [kubernetes/kops#11290]
In https://github.com/cilium/cilium/issues/9920 and https://github.com/cilium/cilium/pull/10972, Cilium started shipping a "fat" operator (`cilium-operator`) with everything built in and "slim" operators (eg `cilium-operator-generic` and `cilium-operator-aws`) with only the specific cloud provider options enabled.

The 1.9 addon templates reference the `cilium-operator-generic` (one of the "slim" operators): https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template#L798  This is missing much of the cloud specific functionality, such as AWS ENI IPAM support, which leads to error messages like:

```
level=fatal msg="eni allocator is not supported by this version of cilium-operator-generic" subsys=cilium-operator-generic
```

The 1.8 addon template correctly references the "fat" operator `cilium-operator`: https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template#L727   which properly includes all the generic functionality _plus_ the cloud specific functionality such as AWS ENI IPAM.

I believe the fix would be to update the `k8s-1.12-v1.9.yaml.template` file to use the `cilium-operator` instead.  As a temporary workaround with kops version 1.20.0 you can update your cluster config to a specific 1.8 based cilium like:

```yaml
spec:
  networking:                                                                                                                                                                                                                                                                                                                 
    cilium:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      version: v1.8.9 
```
