### ISSUE TITLE
failed to attach externalPolicies

### ISSUE THREAD

**Issue by karancode** [kubernetes/kops#11295]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.18.2 (git-84495481e4)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`Server Version: v1.18.12`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
below is a simple kops config
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s1.xxx.xxx
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  cloudConfig:
    elbSecurityGroup: sg-xxx  
  configBase: s3://xxx/xxx
  dnsZone: Zxxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-events
      name: a
    ...
    name: main
  - etcdMembers:
    - instanceGroup: master-events
      name: a
    ...
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 75.x.x.x/x      # Internal
  kubernetesVersion: 1.18.12
  kubelet:
    anonymousAuth: false
  masterPublicName: api.k8s.xxx
  networkCIDR: 10.221.x.x/x
  networkID: vpc-xxx
  networking:
    calico:
      majorVersion: v3
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.221.0.0/24
  subnets:
  - cidr: 10.221.x.x/x
    id: subnet-xxx
    name: ap-xxx-xx-
    type: Private
    zone: ap-xxx-xx
    ...
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  additionalPolicies:
    node: |
      ...
    master: |
      ...
  externalPolicies:
    master:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    node:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  cloudLabels:
    Resource: K8S
    Service: Platform
    Managed: Terraform
  target:
    terraform:
      providerExtraConfig:
        version: ">= 1.44.0"

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s1.xxx.xxx
  name: master-k8s1-x
spec:
  additionalUserData:
  - name: set-fsdescriptor.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "*  soft  nofile 65535" >> /etc/security/limits.d/fsdescriptor.conf
      echo "*  hard  nofile 65535" >> /etc/security/limits.d/fsdescriptor.conf
  iam:
    profile: arn:aws:iam::xxx:instance-profile/masters-k8s1.xxx.xxx
  image: ami-0ce107ae7af2e92b5  # amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2     
  machineType: m4.large
  maxSize: 1
  minSize: 1
  cloudLabels:
    Resource: K8S
    Managed: Terraform
    TechTeam: platform
    Creator: kops-terraform
  nodeLabels:
    kops.k8s.io/instancegroup: master-k8s1-xxx
  role: Master
  subnets:
  - ap-xxx-xx
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s1.xxx.xxx
  name: nodes-xxx
spec:
  additionalUserData:
  - name: set-fsdescriptor.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "*  soft  nofile 65535" >> /etc/security/limits.d/fsdescriptor.conf
      echo "*  hard  nofile 65535" >> /etc/security/limits.d/fsdescriptor.conf
  additionalSecurityGroups:
    - sg-xxx          
  iam:
    profile: arn:aws:iam::xxx:instance-profile/nodes-xxx.xxx
  image: ami-0ce107ae7af2e92b5 #amzn2-ami-hvm-2.0.20200917.0-x86_64-gp2        
  machineType: r5.4xlarge
  maxSize: 1
  minSize: 1
  cloudLabels:
    Resource: K8S
    Managed: Terraform
    TechTeam: platform
    Creator: kops-terraform
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-xxx-xxx
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 200
  rootVolumeType: gp2
  subnets:
  - ap-xxx
  suspendProcesses:
  - AZRebalance
```
I have added `spec.externalPolicies` now to attach SSMCore to our nodes role.
To update, run below:
```
kops update cluster --name $(KOPS_NAME) --state $(KOPS_STATE) --out=../terraform_kops --target=terraform
```

**5. What happened after the commands executed?**
commands succeeded with no changes
 
**6. What did you expect to happen?**
expected to have the policy attached to the iam role(?)

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I checked for the comments in other issues and note [here](https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#use-existing-aws-instance-profiles) that _Currently kOps only supports using existing instance profiles for every instance group in the cluster, not a mix of existing and managed instance profiles._ 
But in our case the instance profiles are also generated by kops (terraform). for ex : 
```hcl
resource "aws_iam_instance_profile" "masters-k8s1-xxx-xxx" {
  name = "masters-k8s1.xxx.xxx"
  role = aws_iam_role.masters-k8s1-xxx.xxx.name
}
...
```
Could you please help in this case? Thanks.
