### ISSUE TITLE
KubeDNS still running after 1.20 Upgrade

### ISSUE THREAD

**Issue by atze234** [kubernetes/kops#11345]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`v1.20.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`v1.20.6`
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kubectl get po -nkube-system`
**5. What happened after the commands executed?**
```
[...]
coredns-5489b75945-c6vmj                                               1/1     Running   0          12m
coredns-5489b75945-wtfg5                                               1/1     Running   0          12m
coredns-autoscaler-6f594f4c58-fqtpc                                    1/1     Running   0          12m
[...]
kube-dns-677d5df9b4-7wwhn                                              3/3     Running   0          12m
kube-dns-677d5df9b4-8gsmk                                              3/3     Running   0          10m
kube-dns-autoscaler-7f87957f46-7pz5s                                   1/1     Running   0          12m
[...]
```

**6. What did you expect to happen?**
kube-dns should not be there anymore, as coredns is default now? Or should the deployment be removed by hand? Or did i miss a required Action on an Upgrade in the past? 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-04-13T09:03:15Z"
  generation: 18
  name: x
spec:
  api:
    loadBalancer:
      class: Classic
      idleTimeoutSeconds: 3600
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Bill_To: "x"
    Product: y
  cloudProvider: aws
  configBase: s3://x
  dnsZone: xx
  docker:
    insecureRegistry: registry-x
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-file=5
    - max-size=100m
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  fileAssets:
  - content: "shortended..."
    name: audit-config
    path: /srv/kubernetes/audit.conf
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.conf
    logLevel: 1
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    maxPods: 330
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.6
  masterInternalName: api.internal.x
  masterPublicName: api.x
  networkCIDR: x
  networkID: vpc-x
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  rollingUpdate:
    maxUnavailable: 2
  sshAccess:
  - x
  - x
  subnets:
  - cidr: x
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: x
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: x
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: x
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

```
