### ISSUE TITLE
Failed Kops upgrade 1.18.3 => 1.19.2 - Issuing new certificate: "master"

### ISSUE THREAD

**Issue by jlsan92** [kubernetes/kops#11370]
After running `kops update cluster ...` I notice `Issuing new certificate: "master"`. Then after a couple of seconds, `kubectl` and even `kops rolling-update cluster` fail with 

```
Unable to connect to the server: x509: certificate is valid for service-account, not api.my.cluster.net
```

To be able to connect again, I need to run `kops update cluster` again but with Kops 1.18.3 (The version I want to move from). Same behaviour, a couple of seconds after then I can connect back to my cluster's API. Seems impossible to upgrade to Kops 1.19. Not sure if `kops rolling-update cluster --cloudonly` would return a healthy cluster.

Not sure if I'm missing an important step but [Required Actions](https://kops.sigs.k8s.io/releases/1.19-notes/#required-actions) don't mention anything regarding certificates.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.19.2 (git-e288df46e173ba8ce44ac52502283206c0d211ee)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops update cluster --name $KOPS_CLUSTER_NAME --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges --out=config/terraform --target=terraform
```

**5. What happened after the commands executed?**

Normal `kops update cluster` output except for a new line => `57165 vfs_castore.go:590] Issuing new certificate: "master"`

**6. What did you expect to happen?**

Normal `kops update cluster` behaviour without rotating master's certs

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: my.cluster.net
spec:
  additionalPolicies: {}
  addons:
  - manifest: s3://my-kops-state-store/my.cluster.net/addons/flux.addons.weave.works/addon.yaml
  - manifest: s3://my-kops-state-store/my.cluster.net/addons/helm-operator.addons.weave.works/addon.yaml
  - manifest: s3://my-kops-state-store/my.cluster.net/addons/dns-controller-internal.addons.k8s.io/addon.yaml
  api:
    loadBalancer:
      crossZoneLoadBalancing: true
      idleTimeoutSeconds: 600
      type: Public
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Cluster: my.cluster.net
  cloudProvider: aws
  configBase: s3://my-kops-state-store/my.cluster.net
  dnsZone: XXXXXXXXX
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: member-a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: member-b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: member-c
    name: main
    provider: Manager
    version: 3.3.10
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: member-a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: member-b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: member-c
    name: events
    provider: Manager
    version: 3.3.10
  iam:
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
    - AlwaysPullImages
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    authorizationMode: RBAC,Node
    disableBasicAuth: true
    enableProfiling: false
    tlsCipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_RSA_WITH_AES_128_CBC_SHA
    - TLS_RSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
  kubeControllerManager:
    enableProfiling: false
    horizontalPodAutoscalerUseRestClients: true
    tlsCipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_RSA_WITH_AES_128_CBC_SHA
    - TLS_RSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubeScheduler:
    enableProfiling: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    kubeReserved:
      cpu: 360m
      memory: 893Mi
    protectKernelDefaults: false
    readOnlyPort: 0
    streamingConnectionIdleTimeout: 5m0s
    systemReserved:
      cpu: 100m
      memory: 100Mi
    tlsCipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_RSA_WITH_AES_128_CBC_SHA
    - TLS_RSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
  kubernetesApiAccess:
  - 222.222.222.222/32
  kubernetesVersion: 1.18.18
  masterPublicName: api.my.cluster.net
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      IPTablesRulesNoinstall: false
      autoDirectNodeRoutes: false
      bpfCTGlobalAnyMax: 0
      bpfCTGlobalTCPMax: 0
      clusterName: ""
      cniBinPath: ""
      enableNodePort: false
      enablePrometheusMetrics: true
      enableRemoteNodeIdentity: false
      enableipv4: false
      enableipv6: false
      monitorAggregation: ""
      nodeInitBootstrapFile: ""
      preallocateBPFMaps: false
      reconfigureKubelet: false
      removeCbrBridge: false
      restartPods: false
      sidecarIstioProxyImage: ""
      toFqdnsEnablePoller: false
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - cidr: 172.20.32.0/19
    name: private-us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: private-us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: private-us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my.cluster.net
  name: master-us-east-1a
spec:
  associatePublicIp: false
  detailedInstanceMonitoring: false
  iam:
    profile: arn:aws:iam::123456789:instance-profile/kops-master-role
  image: 075585003325/Flatcar-stable-2605.12.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - private-us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my.cluster.net
  name: master-us-east-1b
spec:
  associatePublicIp: false
  detailedInstanceMonitoring: false
  iam:
    profile: arn:aws:iam::123456789:instance-profile/kops-master-role
  image: 075585003325/Flatcar-stable-2605.12.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - private-us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my.cluster.net
  name: master-us-east-1c
spec:
  associatePublicIp: false
  detailedInstanceMonitoring: false
  iam:
    profile: arn:aws:iam::123456789:instance-profile/kops-master-role
  image: 075585003325/Flatcar-stable-2605.12.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - private-us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my.cluster.net
  name: nodes
spec:
  associatePublicIp: false
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/my.cluster.net: owned
  detailedInstanceMonitoring: false
  iam:
    profile: arn:aws:iam::123456789:instance-profile/kops-worker
  image: 075585003325/Flatcar-stable-2605.12.0-hvm
  machineType: m5.xlarge
  maxSize: 10
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - private-us-east-1a
  - private-us-east-1b
  - private-us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
