### ISSUE TITLE
kops-controller setting taint as label

### ISSUE THREAD

**Issue by DiegoLelis** [kubernetes/kops#11458]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.20.0 (git-1.20.0) 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`1.17.14`

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create an instance group with this config: 
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-05-11T19:17:02Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster.mydomain.io
  name: data-gpu
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/node-template/label/k8s.amazonaws.com/accelerator: nvidia-tesla-v100
    k8s.io/cluster-autoscaler/node-template/label/taint/dedicated: gpu:NoSchedule
    k8s.io/cluster-autoscaler/node-template/resources/nvidia.com/gpu: "1"
    k8s.io/cluster-autoscaler/cluster.mydomain.io: "1"
    team: ml
  hooks:
  - before:
    - docker.service
    execContainer:
      image: repo.k2labs.org/masiosare/k8s-nvidia-driver:410.104.2
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: p3.2xlarge
  maxPrice: "8.00"
  maxSize: 20
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - p3.2xlarge
    - p3.8xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    k8s.amazonaws.com/accelerator: nvidia-tesla-v100
    kops.k8s.io/instancegroup: data-gpu
    team: ml
  role: Node
  rollingUpdate:
    maxSurge: 60%
  rootVolumeSize: 100
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  taints:
  - dedicated=gpu:NoSchedule
```

**5. What happened after the commands executed?**
N/A
**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: stg.mydomain.io
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: stg.mydomain.io
  name: data-gpu
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/node-template/label/k8s.amazonaws.com/accelerator: nvidia-tesla-v100
    k8s.io/cluster-autoscaler/node-template/label/taint/dedicated: gpu:NoSchedule
    k8s.io/cluster-autoscaler/node-template/resources/nvidia.com/gpu: "1"
    k8s.io/cluster-autoscaler/stg.mydomain.io: "1"
    team: ml
  hooks:
  - before:
    - docker.service
    execContainer:
      image: repo.mydomain.org/masiosare/k8s-nvidia-driver:410.104.2
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: p3.2xlarge
  maxPrice: "8.00"
  maxSize: 20
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - p3.2xlarge
    - p3.8xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    k8s.amazonaws.com/accelerator: nvidia-tesla-v100
    kops.k8s.io/instancegroup: data-gpu
    team: ml
  role: Node
  rollingUpdate:
    maxSurge: 60%
  rootVolumeSize: 100
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  taints:
  - dedicated=gpu:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Command: `k logs -n kube-system kops-controller-<master_id> | grep gpu:NoSchedule`
```
E0511 19:35:12.803457       1 controller.go:302] controller-runtime/manager/controller/node "msg"="Reconciler error" "error"="error applying patch to node: Node \"ip-10-0-66-47.ec2.internal\" is invalid: metadata.labels: Invalid value: \"gpu:NoSchedule\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" "name"="ip-10-0-66-47.ec2.internal" "namespace"="" "reconciler group"="" "reconciler kind"="Node
```

**9. Anything else do we need to know?**
I believe the problem is on the colon of the taint and the fact that kops-controller is trying to set the taint as a label
