### ISSUE TITLE
breaking change for spot inst elasticgroup users: machine type specified is invalid

### ISSUE THREAD

**Issue by omg-sr** [kubernetes/kops#11513]
Hey :wave:

I'm encountering a breaking change when trying to update my cluster using the latest v1.20.1 release.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

I0518 11:47:03.561416   10409 featureflag.go:165] FeatureFlag "Spotinst"=true
Version 1.20.1 (git-5a27dad40a703f646433595a2a40cf94a0c43cd5)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS + Spot Inst Elasticgroups

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster

**5. What happened after the commands executed?**

nodes.spec.machineType: Invalid value: "m5.large,m5.xlarge,m5a.large,m5a.xlarge": machine type specified is invalid: "m5.large,m5.xlarge,m5a.large,m5a.xlarge"

**6. What did you expect to happen?**
Update to work as expected and in the same way it does with kops 1.18.x

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-06T09:23:14Z"
  generation: 15
  labels:
    kops.k8s.io/cluster: "****"
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5.large,m5.xlarge,m5a.large,m5a.xlarge
  maxSize: 20
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**9. Anything else do we need to know?**

I had a look to see if an issue for this already existed. Whilst it doesn't, I noticed https://github.com/kubernetes/kops/pull/10747 which at a glance looks likely to be the culprit.

Thanks
