### ISSUE TITLE
Cluster created but not working on private Openstack cloud with private CA

### ISSUE THREAD

**Issue by atorrescogollo** [kubernetes/kops#11528]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.20.1 (git-5a27dad40a703f646433595a2a40cf94a0c43cd5)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```bash
$ kops get clusters --name my-cluster.k8s.local -o yaml | grep -i kubernetesVersion
  kubernetesVersion: 1.20.6
```

**3. What cloud provider are you using?**
openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
1. Environment setup
```bash
source /path/to/openrc.sh
export OS_DOMAIN_NAME=MYDOMAIN
export KOPS_STATE_STORE=swift://kops
```
2. Create cluster
```bash
kops create cluster \
  --cloud openstack \
  --name my-cluster.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones nova \
  --network-cidr 10.0.0.0/24 \
  --image ubuntu20_04 \
  --master-count=3 \
  --node-count=1 \
  --node-size 02CPU-4GB-20GB \
  --master-size 02CPU-4GB-20GB \
  --etcd-storage-type __DEFAULT__ \
  --api-loadbalancer-type="" \
  --topology private \
  --bastion \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking weave \
  --os-dns-servers=<PRIVATEDNSSERVER>,1.1.1.1 \
  --os-ext-net ext_net

kops update cluster --name my-cluster.k8s.local --yes --admin
```
3. Add private CA to Master InstanceGroups
```bash
kops edit instancegroup master-nova-1
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: master-nova-<N>
spec:
  ...
  useHostCertificates: true
  additionalUserData:
  - name: cacert.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat > /usr/local/share/ca-certificates/mycert.crt <<EOF
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
      EOF
      update-ca-certificates
---
```
4. Rolling-update to reload InstanceGroups
```bash
kops rolling-update cluster --cloudonly --yes
```
5. Check logs (for instance, in master1)
* API Server:
```bash
tail /var/log/kube-apiserver.log
...
W0519 09:03:07.695225       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:4001  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
```
* ETCD:
```bash
 tail /var/log/etcd*
==> /var/log/etcd-events.log <==
...
I0519 09:07:10.847562   25213 volumes.go:173] Using user-agent etcd-manager gophercloud/2.0.0
could not build OpenstackVolumes: error authenticating openstack client: Get "https://<OPENSTACKHOST>:5000/": x509: certificate signed by unknown authority

==> /var/log/etcd.log <==
...
I0519 09:06:06.735073   23807 volumes.go:173] Using user-agent etcd-manager gophercloud/2.0.0
could not build OpenstackVolumes: error authenticating openstack client: Get "https://<OPENSTACKHOST>:5000/": x509: certificate signed by unknown authority
```

**5. What happened after the commands executed?**
Cluster is created but etcd can't connect to openstack so it does not start. **Setting `useHostCertificates: true` does not mount `/etc/ssl/` into etcd containers**. API Server, however, mounts the volume correctly:
```yaml
# /etc/kubernetes/manifests/kube-apiserver.manifest
apiVersion: v1
kind: Pod
metadata:
  ...
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - args:
    ...
    image: k8s.gcr.io/kube-apiserver:v1.20.6
    name: kube-apiserver
    ...
    volumeMounts:
    ...
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    ...
  - args:
    ...
    image: k8s.gcr.io/kops/kube-apiserver-healthcheck:1.20.1
    ...
  ...
  volumes:
...
  - hostPath:
      path: /etc/ssl
    name: etcssl
...
```

```yaml
# /etc/kubernetes/manifests/etcd-main.manifest
apiVersion: v1
kind: Pod
metadata:
  ...
  name: etcd-manager-main
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - mkfifo /tmp/pipe; (tee -a /var/log/etcd.log < /tmp/pipe & ) ; exec /etcd-manager --backup-store=swift://kops/my-cluster.k8s.local/backups/etcd/main --client-urls=https://__name__:4001 --cluster-name=etcd --containerized=true --dns-suffix=internal.my-cluster.k8s.local --etcd-insecure=false --grpc-port=3996 --insecure=false --peer-urls=https://__name__:2380 --quarantine-client-urls=https://__name__:3994 --v=6 --volume-name-tag=k8s.io/etcd/main --volume-provider=openstack --volume-tag=KubernetesCluster=my-cluster.k8s.local --volume-tag=k8s.io/etcd/main --volume-tag=k8s.io/role/master=1 > /tmp/pipe 2>&1
    ...
    image: k8s.gcr.io/etcdadm/etcd-manager:3.0.20210430
    name: etcd-manager
    ...
    volumeMounts:
    - mountPath: /rootfs
      name: rootfs
    - mountPath: /run
      name: run
    - mountPath: /etc/kubernetes/pki/etcd-manager
      name: pki
    - mountPath: /var/log/etcd.log
      name: varlogetcd
  ...
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: rootfs
  - hostPath:
      path: /run
      type: DirectoryOrCreate
    name: run
  - hostPath:
      path: /etc/kubernetes/pki/etcd-manager-main
      type: DirectoryOrCreate
    name: pki
  - hostPath:
      path: /var/log/etcd.log
      type: FileOrCreate
    name: varlogetcd
...
```

**6. What did you expect to happen?**
Etcd boots up correctly so that api server can boot up.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
kops get clusters --name my-cluster.k8s.local -o yaml
---
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-05-19T08:05:50Z"
  name: my-cluster.k8s.local
spec:
  api: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        ignore-volume-az: false
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
      router:
        dnsServers: <MYDNSSERVER>,1.1.1.1
        externalNetwork: ext_net
  cloudProvider: openstack
  configBase: swift://kops/my-cluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-nova-1
      name: etcd-1
      volumeType: __DEFAULT__
    - instanceGroup: master-nova-2
      name: etcd-2
      volumeType: __DEFAULT__
    - instanceGroup: master-nova-3
      name: etcd-3
      volumeType: __DEFAULT__
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-nova-1
      name: etcd-1
      volumeType: __DEFAULT__
    - instanceGroup: master-nova-2
      name: etcd-2
      volumeType: __DEFAULT__
    - instanceGroup: master-nova-3
      name: etcd-3
      volumeType: __DEFAULT__
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.6
  masterPublicName: api.my-cluster.k8s.local
  networkCIDR: 10.0.0.0/24
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.32/27
    name: nova
    type: Private
    zone: nova
  - cidr: 10.0.0.0/30
    name: utility-nova
    type: Utility
    zone: nova
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**
I don't know how to reload pods by editing manifests behind `/etc/kubernetes/manifests/` to test diferent configurations, but I guess that mounting `/etc/ssl/` into ectd containers should work.
Also, I think that the command `kops create cluster` should have an option to specify the ca bundle file directly so that kubernetes pods can mount it. Editing InstanceGroups manually should not be needed.

**Comment by zetaab** [comment]
Kops does not support self signed certificates in openstack setup

**Comment by atorrescogollo** [comment]
Thank you for your reply. In fact, they are not self-signed. They are signed by a private CA. I think that in an Openstack environment it is reasonable to have a private CA since it is private cloud. Is it planned to support this use case?

**Comment by wesselvdv** [comment]
This is not necessarily supported by kOps, but it's very easy to add custom startup script using `spec.additionalUserdata`

**Comment by wesselvdv** [comment]
Example:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-05-21T07:59:58Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: node
spec:
  additionalUserData:
    - name: 05_ca_certificates.sh
      type: text/x-shellscript
      content: |
        #!/usr/bin/env sh

        cat > /usr/local/share/ca-certificates/custom.crt <<EOF
        -----BEGIN CERTIFICATE-----
        <CUSTOM>
        -----END CERTIFICATE-----
        EOF

        update-ca-certificates
```

**Comment by atorrescogollo** [comment]
I found why /etc/ssl/certs is not mounted in etcd containers. **I put `useHostCertificates` in InstanceGroup resource instead of Cluster resource**. My bad. Cluster nodes are now in Ready state. Correct configuration should be:
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: my-cluster.k8s.local
spec:
  useHostCertificates: true
  ...
```
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: master-nova-<N>
spec:
  ...
  additionalUserData:
  - name: cacert.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      curl -kL 'https://url/path/to/myca.crt'
      update-ca-certificates
```
