### ISSUE TITLE
AWS ASG couldn't launch new instances: Client error on launch

### ISSUE THREAD

**Issue by kellycampbell** [kubernetes/kops#11545]
During an upgrade, new instances were never starting and had this error in the AWS console instance troubleshooting section:

`Client.InternalError: Client error on launch`

This documentation page describes the issue and resolution:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/ts-as-instancelaunchfailure.html#ts-as-instancelaunchfailure-12

In my case, I just had to grant the right policy permissions to the ASG service role:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html#policy-example-cmk-access

It would be good if kops found this issue and corrected it or identified it during the upgrade process.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.20.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Upgrading 1.19.10 -> 1.20.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops upgrade cluster
kops update cluster
kops rolling-update cluster

**5. What happened after the commands executed?**

When trying the rolling-update on a single control-plane node (non-prod test cluster and testing the upgrade on a single node first), the new instances created from the ASG failed to launch. They quickly went to Terminated state within less than 30 seconds usually.

**6. What did you expect to happen?**

Instance to launch successfully.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-12-11T15:50:59Z"
  generation: 92
  name: xxxxxxx
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": "route53:GetChange",
          "Resource": "arn:aws:route53:::change/*"
        },
        {
          "Effect": "Allow",
          "Action": "route53:ChangeResourceRecordSets",
          "Resource": "arn:aws:route53:::hostedzone/*"
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets",
            "route53:ListHostedZonesByName"
          ],
          "Resource": [
            "*"
          ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
              "ec2:AttachVolume",
              "ec2:CreateSnapshot",
              "ec2:CreateTags",
              "ec2:CreateVolume",
              "ec2:DeleteSnapshot",
              "ec2:DeleteTags",
              "ec2:DeleteVolume",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeInstances",
              "ec2:DescribeSnapshots",
              "ec2:DescribeTags",
              "ec2:DescribeVolumes",
              "ec2:DescribeVolumesModifications",
              "ec2:DetachVolume",
              "ec2:ModifyVolume"
            ],
            "Resource": "*"
      }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: alpha
  cloudProvider: aws
  configBase: s3://bucketname/xxxxxxx
  dnsZone: dnszone.com
  docker:
    execOpt:
    - native.cgroupdriver=systemd
  etcdClusters:
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    name: main
    version: 3.4.13
  - cpuRequest: 200m
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 512Mi
    name: events
    version: 3.4.13
  externalPolicies:
    master:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    node:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  - content: |-
      /var/log/fluentd.log{
        rotate 5
        copytruncate
        missingok
        notifempty
        compress
        maxsize 1000M
        daily
        create 0644 root root
      }
    name: fluentd
    path: /etc/logrotate.d/fluentd
  - content: |
      apiVersion: audit.k8s.io/v1 # This is required.
      kind: Policy
      omitStages:
        - "RequestReceived"
      rules:
        - level: RequestResponse
          resources:
          - group: ""
            resources: ["pods"]
            verbs: ["create", "patch", "update", "delete"]

        - level: RequestResponse
          resources:
          - group: "rbac.authorization.k8s.io"
            resources: ["clusterroles", "clusterrolebindings"]

        - level: Metadata
          omitStages:
          - RequestReceived
          resources:
          - group: authentication.k8s.io
            resources:
            - tokenreviews

        - level: RequestResponse
          omitStages:
          - RequestReceived
          resources:
          - group: authorization.k8s.io
            resources:
            - subjectaccessreviews

        - level: Metadata
          resources:
          - group: ""
            resources: ["pods/log", "pods/status"]

        - level: None
          resources:
          - group: ""
            resources: ["configmaps"]
            resourceNames: ["controller-leader"]

        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
          - group: "" # core API group
            resources: ["endpoints", "services"]

        - level: None
          userGroups: ["system:authenticated"]
          nonResourceURLs:
          - "/api*" # Wildcard matching.
          - "/version"
          - "/healthz*"
          - "/swagger*"
          - "/metrics"

        - level: Request
          resources:
          - group: "" # core API group
            resources: ["configmaps"]
          namespaces: ["kube-system"]

        - level: RequestResponse
          resources:
          - group: "" # core API group
            resources: ["secrets", "configmaps"]

        - level: Request
          resources:
          - group: "" # core API group
          - group: "extensions" # Version of group should NOT be included.

        - level: Metadata
          omitStages:
            - "RequestReceived"
    name: audit-policy
    path: /var/lib/k8s_audit/audit-policy.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogFormat: json
    auditLogMaxAge: 5
    auditLogMaxBackups: 3
    auditLogMaxSize: 10
    auditLogPath: /var/lib/k8s_audit/audit.log
    auditPolicyFile: /var/lib/k8s_audit/audit-policy.yaml
    featureGates:
      EphemeralContainers: "true"
      TTLAfterFinished: "true"
    oidcClientID: identifierstuffhere.apps.googleusercontent.com
    oidcIssuerURL: https://accounts.google.com
    oidcUsernameClaim: email
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubeDNS:
    nodeLocalDNS:
      enabled: true
    provider: CoreDNS
  kubeScheduler:
    featureGates:
      EphemeralContainers: "true"
  kubelet:
    anonymousAuth: false
    cgroupDriver: systemd
  kubernetesApiAccess:
  - allowed ip cidrs here/32
  kubernetesVersion: 1.20.7
  masterInternalName: api.internal.xxxxxxx
  masterPublicName: api.xxxxxxx
  networkCIDR: 172.23.0.0/16
  networking:
    calico:
      crossSubnet: true
      majorVersion: v3
      prometheusMetricsEnabled: true
      prometheusMetricsPort: 9090
      typhaReplicas: 3
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - allowed cidrs/32
  subnets:
  - cidr: 172.23.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.23.64.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  - cidr: 172.23.96.0/19
    name: us-east-2c
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-12-11T15:50:59Z"
  generation: 30
  labels:
    kops.k8s.io/cluster: xxxxxxx
  name: master-us-east-2a
spec:
  cloudLabels:
    expenseAccount: "51150"
    expenseCategory: eng
    function: kubernetes-controller
    usageCategory: eng
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  subnets:
  - us-east-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-27T18:43:31Z"
  generation: 17
  labels:
    kops.k8s.io/cluster: xxxxxxx
  name: master-us-east-2b
spec:
  cloudLabels:
    expenseAccount: "51150"
    expenseCategory: eng
    function: kubernetes-controller
    usageCategory: eng
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: master-us-east-2b
  role: Master
  subnets:
  - us-east-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-27T18:43:26Z"
  generation: 15
  labels:
    kops.k8s.io/cluster: xxxxxxx
  name: master-us-east-2c
spec:
  cloudLabels:
    expenseAccount: "51150"
    expenseCategory: eng
    function: elastic
    usageCategory: eng
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: master-us-east-2c
  role: Master
  subnets:
  - us-east-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-12-11T15:50:59Z"
  generation: 54
  labels:
    kops.k8s.io/cluster: xxxxxxx
  name: nodes
spec:
  cloudLabels:
    expenseAccount: "51150"
    expenseCategory: eng
    function: worker
    role: node
    usageCategory: eng
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: r5.xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: nodes
    kubernetes.io/fluentd-ds-ready: "true"
  role: Node
  rollingUpdate:
    maxSurge: 3
  subnets:
  - us-east-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-03-24T21:32:42Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: xxxxxxx
  name: nodes-2a
spec:
  cloudLabels:
    expenseAccount: "51150"
    expenseCategory: eng
    function: worker
    role: node
    usageCategory: eng
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: r5.xlarge
  maxSize: 8
  minSize: 8
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: nodes-2a
    kubernetes.io/fluentd-ds-ready: "true"
  role: Node
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 2
  subnets:
  - us-east-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

There may have been new policies attached to our AWS account by our parent organization between the time we upgraded to 1.19 and now, e.g. for things like new volumes must be encrypted. I believe the volumes on the old cluster weren't encrypted. I don't remember seeing anything else specific about volume type or encryption during the upgrade process.
