### ISSUE TITLE
Add support for AWS LB access log collection

### ISSUE THREAD

**Issue by f-ld** [kubernetes/kops#11608]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
When creating k8s clusters with kops on AWS, we have the [ability to select the cluster class](https://kops.sigs.k8s.io/cluster_spec/#load-balancer-class), either classic ELB or NLB (and more, like subnet configuration.

What cannot be done is the ability to configure access logs (for ELB or NLB with TLS termination).
Adding some configuration keys to the cluster spec under `spec` > `api` > `loadbalancer` should allow end users to:
- activate TLS termination for NLB loadbalancers (otherwise not access log collection possible). I have the feeling this is already possible with `sslCertificate` option.
- configure LB access collection.

**2. Feel free to provide a design supporting your feature request.**
One example could be [something like what k8s does with LB backed services](https://kubernetes.io/docs/concepts/services-networking/service/#elb-access-logs-on-aws), using similar set of keys and values. For example cluster spec would be:
```
spec:
  api:
    loadBalancer:
      class: Classic
      accessLogs:
        enabled: true
        emitInterval: 5
        s3BucketName: my-access-log-bucket
        s3BucketPrefix: k8s/apiserver/
```

And then TLS termination is required to be configured on NLBs to activate access logs, but if I'm not wrong, this is what `sslCertificate` and `sslPolicy` are doing.
