### ISSUE TITLE
Kops doesnt add masters to cluster when changing master instance group min/max size 

### ISSUE THREAD

**Issue by mihok** [kubernetes/kops#1168]
Creating a new cluster changing one master zones instance group size MinSize and MaxSize creates the instances but does not add them to the kuberentes cluster pool. I went through the steps to create a new cluster of 5 nodes and 5 masters but only had 3 of the master nodes connect to the cluster.

`kops version`: Version git-2d03bbe4

Steps to reproduce:
1. Run 
```bash
./kops create cluster \
    --node-count 5 \
    --zones us-east-1c,us-east-1d,us-east-1b \
    --master-zones us-east-1c,us-east-1d,us-east-1b \
    --dns-zone kops.turnstyle.io \
    --node-size t2.medium \
    --master-size t2.medium \
    --image ami-e6d5d2f1 \
    --vpc vpc-d4d039b0 \
    --network-cidr 11.0.0.0/16 \
    --ssh-public-key ~/.ssh/key.pub \
    ${NAME}
```

2. Edit master ig `us-east-1c` with `kops edit ig --name=kops.mydomain.com master-us-east-1c`, changing `minSize` and `maxSize` from 1 to 3

Resulting instance group config looks like this:
```yaml
metadata:
  creationTimestamp: "2016-12-15T14:59:14Z"
  name: master-us-east-1c
spec:
  associatePublicIp: false
  image: ami-e6d5d2f1
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  role: Master
  zones:
  - us-east-1c

```

3. Pull the trigger (`kops update cluster kops.mydomain.com --yes`)

Result creates 5 masters and 5 nodes but does not add the 2 additional masters in us-east-1c to the cluster.
