### ISSUE TITLE
rootVolumeSize value not respected for on demand node instance group with 5TB root disk

### ISSUE THREAD

**Issue by krisshub** [kubernetes/kops#11705]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2021-02-05
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 5000
  subnets:
  - us-east-1a
 ```
**5. What happened after the commands executed?**
The nodes ASG was created with 5000 GB root volume, but with only 2TB partition being used.

df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             62G     0   62G   0% /dev
tmpfs            13G  3.1M   13G   1% /run
**/dev/nvme0n1p2  1.9T  3.0G  1.8T   1% /**
tmpfs            62G     0   62G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            62G     0   62G   0% /sys/fs/cgroup

lsblk
NAME        MAJ:MIN RM    SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0    4.9T  0 disk 
|-nvme0n1p1 259:1    0 1007.5K  0 part 
**`-nvme0n1p2 259:2    0      2T  0 part /**

**6. What did you expect to happen?**
Node using the full 5000 GB capacity of the root volume.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: probe-test.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://probe-kubernetes-state-store/probe-test.k8s.local
  containerRuntime: docker
  additionalPolicies:
    node: |
      [
        {
           "Action":[
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams",
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
           ],
           "Resource":"*",
           "Effect":"Allow"
        }
      ]
    master: |
      [
        {
           "Action":[
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams",
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
           ],
           "Resource":"*",
           "Effect":"Allow"
        }
      ]
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  kubernetesVersion: 1.14.10
  masterPublicName: api.probe-test.k8s.local
  networkCIDR: 
  networkID: 
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  subnets:
  - id: 
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - id: 
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2021-02-05
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  rootVolumeSize: 200
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2021-02-05
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 5000
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: bastions
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2021-02-05
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
    - utility-us-east-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
As per https://github.com/kubernetes/kops/issues/4330, we are using stretch image for M5 instances, however we are still seeing the issue

**Comment by olemarkus** [comment]
This bug report is against an unsupported version of kOps. At minimum, upgrade to latest kOps and see if the bug persists.

In particular there are changes done to root volume support in 1.20+.

**Comment by krisshub** [comment]
Hi @olemarkus , i am still seeing the same issue after upgrade of kops.
1. What kops version are you running? The command kops version, will display
this information.
Version 1.20.1

2. What Kubernetes version are you running? kubectl version will print the
version if a cluster is running or provide the Kubernetes version specified as
a kops flag.

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run? What is the simplest way to reproduce this issue?

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  rootVolumeSize: 5000
  rootVolumeOptimization: true
  subnets:
  - us-east-1a
```

5. What happened after the commands executed?
The nodes ASG was created with 5000 GB root volume, but with only 2TB partition being used.

 df -h
Filesystem      Size  Used Avail Use% Mounted on
**/dev/root       2.0T  3.8G  2.0T   1% /**
devtmpfs         62G     0   62G   0% /dev
tmpfs            62G     0   62G   0% /dev/shm
tmpfs            13G  1.7M   13G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            62G     0   62G   0% /sys/fs/cgroup
/dev/loop0       34M   34M     0 100% /snap/amazon-ssm-agent/3552
/dev/loop1       56M   56M     0 100% /snap/core18/1997
/dev/loop2       33M   33M     0 100% /snap/snapd/11588
/dev/loop3       71M   71M     0 100% /snap/lxd/19647
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/protokube/rootfs
shm              64M     0   64M   0% /run/containerd/io.containerd.grpc.v1.cri/sandboxes/d2507ea2909d34e416496ce658161af9c75e9a3f6a423a5af9bc4551cf84f139/shm
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/d2507ea2909d34e416496ce658161af9c75e9a3f6a423a5af9bc4551cf84f139/rootfs
shm              64M     0   64M   0% /run/containerd/io.containerd.grpc.v1.cri/sandboxes/c8584f3f9039e517ff4b78b9b0b0612233515461d650ee55c0d03f573e6709f4/shm
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/c8584f3f9039e517ff4b78b9b0b0612233515461d650ee55c0d03f573e6709f4/rootfs
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/5cc1096002e43a5ee831baa4113c55e1c197bde409d7ca892a86372aa41b6df4/rootfs
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/bdaa905d0cda43dc37e518efd663cdde3e4262e04745e0307eaa101cd89f6b7f/rootfs
shm              64M     0   64M   0% /run/containerd/io.containerd.grpc.v1.cri/sandboxes/9894502fa5fd3b8eeb4965d8ec26763ef6865f0fa503e7835f8ac9a3a90c8ce8/shm
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/9894502fa5fd3b8eeb4965d8ec26763ef6865f0fa503e7835f8ac9a3a90c8ce8/rootfs
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/7d7f362c8439a77577f25be055306d720ee5e15937afe280cefa2a90341f2def/rootfs
shm              64M     0   64M   0% /run/containerd/io.containerd.grpc.v1.cri/sandboxes/09e4c8fa7e20b5175d12faaedc6d5468b3f9adad8a13cd8c738a6a37d698e637/shm
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/09e4c8fa7e20b5175d12faaedc6d5468b3f9adad8a13cd8c738a6a37d698e637/rootfs
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/2d0837e80201aad5a64d41872ef16a43aa8b5259fb03e979180ab7bd67fbbc2e/rootfs
shm              64M     0   64M   0% /run/containerd/io.containerd.grpc.v1.cri/sandboxes/dbea74573c5358be92513116f3cd82791d69237cc326e0ef926a7105d9254006/shm
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/dbea74573c5358be92513116f3cd82791d69237cc326e0ef926a7105d9254006/rootfs
overlay         2.0T  3.8G  2.0T   1% /run/containerd/io.containerd.runtime.v2.task/k8s.io/3a465f5d0207ec7c6a89bb51de5627bc9fdad29e9972bd9c211673acc334a5e9/rootfs
tmpfs            13G     0   13G   0% /run/user/1000

 lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0 33.3M  1 loop /snap/amazon-ssm-agent/3552
loop1         7:1    0 55.5M  1 loop /snap/core18/1997
loop2         7:2    0 32.3M  1 loop /snap/snapd/11588
loop3         7:3    0 70.4M  1 loop /snap/lxd/19647
**nvme0n1     259:0    0  4.9T  0 disk 
└─nvme0n1p1 259:1    0    2T  0 part /**


6. What did you expect to happen?
Node using the full 5000 GB capacity of the root volume.

7. Please provide your cluster manifest. Execute
kops get --name my.example.com -o yaml to display your cluster manifest.
You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: probe-test.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://probe-kubernetes-state-store/probe-test.k8s.local
  additionalPolicies:
    node: |
      [
        {
           "Action":[
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams",
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
           ],
           "Resource":"*",
           "Effect":"Allow"
        }
      ]
    master: |
      [
        {
           "Action":[
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams",
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
           ],
           "Resource":"*",
           "Effect":"Allow"
        }
      ]
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - x.x.x.x/8
  kubernetesVersion: 1.20.7
  masterPublicName: api.probe-test.k8s.local
  networkCIDR: 10.126.32.0/20
  networkID: xxxxxx
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - x.x.x.x/8
  subnets:
  - id: xxxx
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - id: xxxx
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  rootVolumeSize: 200
  rootVolumeOptimization: true
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  rootVolumeSize: 5000
  rootVolumeOptimization: true
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: bastions
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
    - utility-us-east-1a
```
8. Please run the commands with most verbose logging by adding the -v 10 flag.
Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

**Comment by hakman** [comment]
@krisshub It seems more of a limitation of the MBR partitioning scheme:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_constraints.html#aws_limits

**Comment by krisshub** [comment]
> @krisshub It seems more of a limitation of the MBR partitioning scheme:
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_constraints.html#aws_limits
> https://aws.amazon.com/premiumsupport/knowledge-center/ec2-ubuntu-convert-mbr-to-gpt/

Thanks for the response @hakman. Is there any provision to add more space as our applications are failing due to low ephemeral storage.

**Comment by hakman** [comment]
Most likely, you will need to create a custom AMI with GPT. Once you have that, kOps should be able to use it without any issues.

**Comment by krisshub** [comment]
Ok, Can you please share any reference for the same.

Also, is the below method applicable for the image that i am using **"image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415"**

https://kops.sigs.k8s.io/tutorial/working-with-instancegroups/#adding-additional-storage-to-the-instance-groups.

**Comment by hakman** [comment]
In theory it should work too, but never tried it with such big disks.

**Comment by krisshub** [comment]
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  volumeMounts:
    - device: /dev/sdf
      filesystem: ext4
      path: /var/lib/docker
  volumes:
    - device: /dev/sdf
      size: 2000
      type: gp2
  subnets:
  - us-east-1a
```

The cluster fails and gets stuck during validation.

VALIDATION ERRORS
KIND    NAME                                            MESSAGE
Machine i-07d981f746d6a0efa                             machine "i-07d981f746d6a0efa" has not yet joined cluster
Pod     kube-system/coredns-5489b75945-g44kz            system-cluster-critical pod "coredns-5489b75945-g44kz" is pending
Pod     kube-system/coredns-autoscaler-6f594f4c58-q5ljp system-cluster-critical pod "coredns-autoscaler-6f594f4c58-q5ljp" is pending

Validation Failed
W0607 20:21:55.168781   53101 validate_cluster.go:221] (will retry): cluster not yet healthy

**Comment by hakman** [comment]
Maybe it's `/dev/xvdf`? Also, `gp2` should probably be `gp3`.

**Comment by krisshub** [comment]
> Maybe it's `/dev/xvdf`? Also, `gp2` should probably be `gp3`.

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  volumeMounts:
    - device: /dev/xvdf
      filesystem: ext4
      path: /var/lib/docker
  volumes:
    - device: /dev/xvdf
      size: 2000
      type: gp3
  subnets:
  - us-east-1a
```
Still facing the same issue after making the above changes.

**Comment by hakman** [comment]
I suggest to SSH to the instance and see what happens, you should find some error message that would help.

**Comment by krisshub** [comment]
Checked the logs, getting the below error:

Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: I0608 06:56:50.197530    1730 volumes.go:65] Attempting to format and mount device: /dev/xvdf, path: /var/lib/docker
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: I0608 06:56:50.197555    1730 mount_linux.go:405] Attempting to determine if disk "/dev/xvdf" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/xvdf])
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: I0608 06:56:50.198867    1730 mount_linux.go:408] Output: "blkid: error: /dev/xvdf: No such file or directory\n", err: exit status 2
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: I0608 06:56:50.198894    1730 mount_linux.go:366] Disk "/dev/xvdf" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/xvdf]
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: E0608 06:56:50.200093    1730 mount_linux.go:372] format of disk "/dev/xvdf" failed: type:("ext4") target:("/var/lib/docker") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: The file /dev/xvdf does not exist and no size was specified.
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: )
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: E0608 06:56:50.200120    1730 volumes.go:68] failed to mount the device: /dev/xvdf on: /var/lib/docker, error: format of disk "/dev/xvdf" failed: type:("ext4") target:("/var/lib/docker") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: The file /dev/xvdf does not exist and no size was specified.
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: )
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: W0608 06:56:50.200136    1730 main.go:133] got error running nodeup (will retry in 30s): error building loader: format of disk "/dev/xvdf" failed: type:("ext4") target:("/var/lib/docker") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: The file /dev/xvdf does not exist and no size was specified.
Jun  8 06:56:50 ip-10-126-33-47 nodeup[1730]: )
Jun  8 06:56:50 ip-10-126-33-47 systemd[1]: run-r5aa0013d53e544c4bbd8a71c8feaf7ed.scope: Succeeded.

**Comment by hakman** [comment]
The new disk is `/dev/nvme1n1`.

**Comment by krisshub** [comment]
i tried using **/dev/nvme1n1** also, but then i get the below error.

W0608 12:15:33.356072   62863 executor.go:139] error running task "AutoscalingGroup/nodes-us-east-1a.probe-test.k8s.local" (9m5s remaining to succeed): error creating AutoScalingGroup: You must use a valid fully-formed launch template. **Invalid device name /dev/nvme1n1**
I0


```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  volumeMounts:
    - device: /dev/nvme1n1
      filesystem: ext4
      path: /var/lib/docker
  volumes:
    - device: /dev/nvme1n1
      size: 2000
      type: gp3
  subnets:
  - us-east-1a
```

**Comment by hakman** [comment]
Maybe something like this?
```yaml
  volumeMounts:
    - device: /dev/nvme1n1
      filesystem: ext4
      path: /var/lib/docker
  volumes:
    - device: /dev/sda1
      size: 2000
      type: gp3
```

**Comment by krisshub** [comment]
> Maybe something like this?
> 
> ```yaml
>   volumeMounts:
>     - device: /dev/nvme1n1
>       filesystem: ext4
>       path: /var/lib/docker
>   volumes:
>     - device: /dev/sda1
>       size: 2000
>       type: gp3
> ```


After the above change, it didn't create the volume on the EC2 instance.
```
 lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0 33.3M  1 loop /snap/amazon-ssm-agent/3552
loop1         7:1    0 70.4M  1 loop /snap/lxd/19647
loop2         7:2    0 32.3M  1 loop /snap/snapd/11588
loop3         7:3    0 55.5M  1 loop /snap/core18/1997
nvme0n1     259:0    0  128G  0 disk 
└─nvme0n1p1 259:1    0  128G  0 part /
```

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: probe-test.k8s.local
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: m5a.8xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  volumeMounts:
    - device: /dev/nvme1n1
      filesystem: ext4
      path: /var/lib/docker
  volumes:
    - device: /dev/sda1
      size: 2000
      type: gp3
  subnets:
  - us-east-1a
 ```


Logs:
```
un  8 09:25:10 ip-10-126-33-142 nodeup[1705]: I0608 09:25:10.552819    1705 volumes.go:65] Attempting to format and mount device: /dev/nvme1n1, path: /var/lib/docker
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: I0608 09:25:10.552845    1705 mount_linux.go:405] Attempting to determine if disk "/dev/nvme1n1" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/nvme1n1])
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: I0608 09:25:10.554201    1705 mount_linux.go:408] Output: "blkid: error: /dev/nvme1n1: No such file or directory\n", err: exit status 2
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: I0608 09:25:10.554245    1705 mount_linux.go:366] Disk "/dev/nvme1n1" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/nvme1n1]
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: E0608 09:25:10.555491    1705 mount_linux.go:372] format of disk "/dev/nvme1n1" failed: type:("ext4") target:("/var/lib/docker") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: The file /dev/nvme1n1 does not exist and no size was specified.
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: )
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: E0608 09:25:10.555522    1705 volumes.go:68] failed to mount the device: /dev/nvme1n1 on: /var/lib/docker, error: format of disk "/dev/nvme1n1" failed: type:("ext4") target:("/var/lib/docker") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: The file /dev/nvme1n1 does not exist and no size was specified.
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: )
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: W0608 09:25:10.555539    1705 main.go:133] got error running nodeup (will retry in 30s): error building loader: format of disk "/dev/nvme1n1" failed: type:("ext4") target:("/var/lib/docker") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)
Jun  8 09:25:10 ip-10-126-33-142 nodeup[1705]: The file /dev/nvme1n1 does not exist and no size was specified.

```

**Comment by krisshub** [comment]
Thanks @hakman . Tried your approach and now the below configuration works:
```
  volumeMounts:
    - device: /dev/nvme1n1
      filesystem: ext4
      path: /var/lib/docker
  volumes:
    - device: /dev/sdb
      size: 2500
      type: gp3
```

```
lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0 33.3M  1 loop /snap/amazon-ssm-agent/3552
loop1         7:1    0 55.5M  1 loop /snap/core18/1997
loop2         7:2    0 32.3M  1 loop /snap/snapd/11588
loop3         7:3    0 70.4M  1 loop /snap/lxd/19647
nvme1n1     259:0    0  2.5T  0 disk /var/lib/docker
nvme0n1     259:1    0  200G  0 disk 
└─nvme0n1p1 259:2    0  200G  0 part /
```
