### ISSUE TITLE
Kops DNS records are derived from ClusterName and not from masterPublicName/masterInternalName

### ISSUE THREAD

**Issue by EladDolev** [kubernetes/kops#11751]
/kind bug

**1. What `kops` version are you running? **

1.19.3

**2. What Kubernetes version are you running? **

1.19.11

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Setting `metadata.name` to `k8s.<non existing domain/domain with no write permissions to master nodes>` would not allow worker nodes to join the cluster

**5. What happened after the commands executed?**

Worker Nodes are failing to join the cluster because they cannot resolve `kops-controller.internal.<ClusterName>` as this record does not exist

**6. What did you expect to happen?**

Worker Nodes should have been looking for `masterInternalName` since it is defined

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: <ClusterName>
spec:
  api:
    loadBalancer:
      securityGroupOverride: sg-0d07177fd12e13439
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://<my bucket>/kops/<ClusterName>
  containerRuntime: docker
  dnsZone: Z0742037375PMML3RXE8P
  etcdClusters:
  - name: main
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:2379
    cpuRequest: 100m
    memoryRequest: 512Mi
    etcdMembers:
    - instanceGroup: master-a
      name: a
      encryptedVolume: true
    - instanceGroup: master-b
      name: b
      encryptedVolume: true
    - instanceGroup: master-c
      name: c
      encryptedVolume: true
  - name: events
    cpuRequest: 50m
    memoryRequest: 150Mi
    etcdMembers:
    - instanceGroup: master-a
      name: a
      encryptedVolume: true
    - instanceGroup: master-b
      name: b
      encryptedVolume: true
    - instanceGroup: master-c
      name: c
      encryptedVolume: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    MemoryRequest: 1Gi
    targetRamMb: 1024
    featureGates:
      TTLAfterFinished: "true"
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cpuCFSQuota: false
    cloudProvider: aws
    clusterDomain: us-east-1.k8s
    cpuManagerPolicy: static
    kubeReserved:
      cpu: "50m"
  kubeProxy:
    MemoryRequest: 25Mi
    metricsBindAddress: 0.0.0.0
  kubeDNS:
    domain: us-east-1.k8s
    provider: CoreDNS
    coreDNSImage: k8s.gcr.io/coredns:1.7.0
    nodeLocalDNS:
      enabled: false
    externalCoreFile: >
      us-east-1.k8s in-addr.arpa ip6.arpa {
        errors
        health {
          lameduck 5s
        }
        kubernetes {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        loop
        cache 30
        loadbalance
        ready
        reload
      }
      k8s:53 {
        log
        health {
          lameduck 5s
        }
        prometheus :9153
        forward . 100.64.64.64
        reload
      }
      . {
        errors
        health {
          lameduck 5s
        }
        prometheus :9153
        forward . 169.254.169.253
        cache 600
        reload
      }
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.11
  masterInternalName: api.k8s.<real domain defined in `dnsZone`>
  masterPublicName: api.k8s.<real domain defined in `dnsZone`>
  networkCIDR: 10.10.0.0/16
  networkID: vpc-0cc063143f1401b01
  networking:
    amazonvpc:
      env:
      - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
        value: "true"
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: utility-a
    zone: us-east-1a
    cidr: 10.10.1.0/24
    type: Utility
  - name: utility-b
    zone: us-east-1b
    cidr: 10.10.2.0/24
    type: Utility
  - name: utility-c
    zone: us-east-1c
    cidr: 10.10.3.0/24
    type: Utility
  - name: dmz-a
    zone: us-east-1a
    cidr: 10.10.12.0/22
    type: Private
  - name: dmz-b
    zone: us-east-1b
    cidr: 10.10.20.0/22
    type: Private
  - name: dmz-c
    zone: us-east-1c
    cidr: 10.10.32.0/22
    type: Private
  - name: private-a
    zone: us-east-1a
    cidr: 10.10.112.0/22
    type: Private
  - name: private-b
    zone: us-east-1b
    cidr: 10.10.120.0/22
    type: Private
  - name: private-c
    zone: us-east-1c
    cidr: 10.10.132.0/22
    type: Private
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```shell
Jun 11 11:11:47 ip-10-40-13-2 nodeup[795]: W0611 11:11:47.704142     795 executor.go:139] error running task "BootstrapClient/BootstrapClient" (5m41s remaining to succeed): Post "https://kops-controller.internal.<ClusterName>:3988/bootstrap": dial tcp: lookup kops-controller.internal.<ClusterName> on 127.0.0.53:53: no such host
```

**9. Anything else do we need to know?**

This thing broke with Kops 1.19 that introduced kops-controller to generate certificates for worker nodes
TBH looking at the code I'm not even sure how it was working before, as master nodes are also looking for some `.internal.` addresses for etcd auto discovery

We're defining all network and IAM roles/permissions outside of Kops, and passing them as parameters

IMHO there's no sense in creating DNS records for kops controller, as the K8s api record can be used, but even if those records for kops-controller are being created, they should be created in the same DNS zone defined in `dnsZone` where `masterInternalName` record is being created (assuming it is defined), falling back to `masterPublicName` (assuming it is defined) and only lastly falling back to `metadata.name`

I can try and create a PR myself, but please let me know if you classify this as a bug, and what should be the best approach here
