### ISSUE TITLE
Kops cluster-autoscaler addon not getting deploy up

### ISSUE THREAD

**Issue by ifosch** [kubernetes/kops#11759]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 
 I've tried this with both kops 1.19 and kops 1.20.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 
 I'm using kubernetes 1.19.9.

**3. What cloud provider are you using?**

AWS, on EC2.

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

On a cluster provisioned on EC2 using kops with manually created
deployment for cluster-autoscaler, I removed the deploy.  Then edit the
cluster definition to include the cluster autoscaler example
configuration from the documentation.  I run `kops update cluster
example.k8s.local --yes` and then `kops rolling-update cluster
example.k8s.local --yes`.

**5. What happened after the commands executed?**

The cluster is rolling updated, but there's no cluster autoscaler pods
not deployment.

**6. What did you expect to happen?**

I expected to have the cluster-autoscaler deploy created and
corresponding pod up and running on the kube-system namespace.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-02-13T14:47:28Z"
  generation: 26
  name: example.k8s.local
spec:
  additionalPolicies:
    node: |
      [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    environment: example
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    expander: least-waste
    balanceSimilarNodeGroups: false
    scaleDownUtilizationThreshold: "0.5"
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.19.1
    cpuRequest: "100m"
    memoryRequest: "300Mi"
  configBase: s3://kops-bucket/example.k8s.local
  docker:
    bridgeIP: 192.168.3.1/24
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-region-1
      name: 1
    - instanceGroup: master-region-2
      name: 2
    - instanceGroup: master-region-3
      name: 3
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-region-1
      name: 1
    - instanceGroup: master-region-2
      name: 2
    - instanceGroup: master-region-3
      name: 3
    memoryRequest: 100Mi
    name: events
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Service]
      Type=oneshot
      RemainAfterExit=no
      ExecStart=/bin/sh -c "sed -i -e 's/^pool/#pool/g' -e 's/^# pool: .*$/server 169.254.169.123 prefer iburst/' /etc/ntp.conf"
      ExecStartPost=/bin/systemctl restart ntp.service
    name: change_ntp_server.service
    roles:
    - Node
    - Master
  - before:
    - docker.service
    manifest: |
      [Service]
      Type=oneshot
      RemainAfterExit=no
      ExecStartPre=/bin/mkdir -p /root/.docker
      ExecStart=/usr/bin/wget https://amazon-ecr-credential-helper-releases.s3.region-4.amazonaws.com/0.3.1/linux-amd64/docker-credential-ecr-login -O /bin/docker-credential-ecr-login
      ExecStartPost=/bin/chmod +x /bin/docker-credential-ecr-login
      ExecStartPost=/bin/sh -c "echo '{\n  \"credHelpers\": {\n    \"111111111111.dkr.ecr.us-east-1.amazonaws.com\": \"ecr-login\"\n  }\n}' > /root/.docker/config.json"
    name: setup_ecr_docker.service
    roles:
    - Node
    - Master
  - manifest: |
      [Unit]
      Description=Telegraf Container
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=/bin/sh -lc "docker pull 111111111111.dkr.ecr.us-east-1.amazonaws.com/telegraf"
      ExecStartPre=/bin/sh -lc "/usr/bin/docker rm -f telegraf || echo OK"
      ExecStart=/usr/bin/docker run -p 9126:9126 --rm --name telegraf 111111111111.dkr.ecr.us-east-1.amazonaws.com/telegraf

      [Install]
      WantedBy=multi-user.target
    name: telegraf.service
    roles:
    - Node
    - Master
    useRawManifest: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 192.168.6.0/25
  kubernetesVersion: 1.19.9
  masterInternalName: api.internal.example.k8s.local
  masterPublicName: api.example.k8s.local
  networkCIDR: 192.168.0.0/20
  networkID: vpc-11111111
  networking:
    calico:
      crossSubnet: true
      majorVersion: v3
      prometheusMetricsEnabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 192.168.6.0/25
  subnets:
  - cidr: 192.168.9.0/24
    name: region-3
    type: Private
    zone: region-3
  - cidr: 192.168.10.0/24
    name: region-1
    type: Private
    zone: region-1
  - cidr: 192.168.11.0/24
    name: region-2
    type: Private
    zone: region-2
  - cidr: 192.168.8.0/26
    name: utility-region-3
    type: Utility
    zone: region-3
  - cidr: 192.168.8.64/26
    name: utility-region-1
    type: Utility
    zone: region-1
  - cidr: 192.168.8.128/26
    name: utility-region-2
    type: Utility
    zone: region-2
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-13T14:47:29Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: example.k8s.local
  name: master-region-3
spec:
  additionalSecurityGroups:
  - sg-11111111
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-region-3
  role: Master
  subnets:
  - region-3

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-13T14:47:29Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: example.k8s.local
  name: master-region-1
spec:
  additionalSecurityGroups:
  - sg-11111111
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-region-1
  role: Master
  subnets:
  - region-1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-13T14:47:29Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: example.k8s.local
  name: master-region-2
spec:
  additionalSecurityGroups:
  - sg-11111111
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-region-2
  role: Master
  subnets:
  - region-2

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-13T14:47:29Z"
  generation: 11
  labels:
    kops.k8s.io/cluster: example.k8s.local
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-11111111
  cloudLabels:
    example.k8s.local/autoscaler/enabled: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5a.xlarge
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - region-3
  - region-1
  - region-2
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Update: https://controlc.com/ca90e288
Rolling-update: https://controlc.com/58c59773

**9. Anything else do we need to know?**

I've tried forcing a rolling update, but the result is the same, no
deploy for `cluster-autoscaler`. The verbose output for the forced
rolling update is too big to push, but I can send them.  I've checked
kubelet's logs but found nothing about the cluster autoscaler
manifest.
