### ISSUE TITLE
etcd volumes do not line up with proper masters/IGs

### ISSUE THREAD

**Issue by jmcdonagh** [kubernetes/kops#11760]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.20.1 (git-5a27dad40a703f646433595a2a40cf94a0c43cd5)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

```
AWS
```

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I build a fresh kops cluster from a template. The simplest way to reproduce is to build with the yaml I will paste below.

**5. What happened after the commands executed?**

Everything is great. Cluster is operational. However, the wrong etcd volumes are attached to the wrong instances.

**6. What did you expect to happen?**

etcd volumes to be associated with the proper IGs

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-06-11T07:23:42Z"
  name: cluster1.k8s.acme.com
spec:
  additionalNetworkCIDRs:
  - 172.20.0.0/16
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/ZXY65LDAS28GL",
            "arn:aws:route53:::hostedzone/Z21NU48Z9P5JX4"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "acm:DescribeCertificate",
            "acm:ListCertificates",
            "acm:GetCertificate",
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "cognito-idp:DescribeUserPoolClient",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CreateNetworkAclEntry",
            "ec2:CreateSecurityGroup",
            "ec2:CreateTags",
            "ec2:DeleteTags",
            "ec2:DeleteSecurityGroup",
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeAddresses",
            "ec2:DescribeInstances",
            "ec2:DescribeInstanceStatus",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeLaunchTemplateVersions",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSubnets",
            "ec2:DescribeTags",
            "ec2:DescribeVpcs",
            "ec2:ModifyInstanceAttribute",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:RevokeSecurityGroupIngress",
            "ec2:ReplaceNetworkAclEntry",
            "ec2messages:AcknowledgeMessage",
            "ec2messages:DeleteMessage",
            "ec2messages:FailMessage",
            "ec2messages:GetEndpoint",
            "ec2messages:GetMessages",
            "ec2messages:SendReply",
            "elasticloadbalancing:AddListenerCertificates",
            "elasticloadbalancing:AddTags",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:CreateRule",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DeleteRule",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:DescribeListenerCertificates",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeLoadBalancerAttributes",
            "elasticloadbalancing:DescribeRules",
            "elasticloadbalancing:DescribeSSLPolicies",
            "elasticloadbalancing:DescribeTags",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeTargetGroupAttributes",
            "elasticloadbalancing:DescribeTargetHealth",
            "elasticloadbalancing:ModifyListener",
            "elasticloadbalancing:ModifyLoadBalancerAttributes",
            "elasticloadbalancing:ModifyRule",
            "elasticloadbalancing:ModifyTargetGroup",
            "elasticloadbalancing:ModifyTargetGroupAttributes",
            "elasticloadbalancing:RegisterTargets",
            "elasticloadbalancing:RemoveListenerCertificates",
            "elasticloadbalancing:RemoveTags",
            "elasticloadbalancing:SetIpAddressType",
            "elasticloadbalancing:SetSecurityGroups",
            "elasticloadbalancing:SetSubnets",
            "elasticloadbalancing:SetWebACL",
            "iam:CreateServiceLinkedRole",
            "iam:GetServerCertificate",
            "iam:ListServerCertificates",
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets",
            "ssm:DescribeAssociation",
            "ssm:DescribeDocument",
            "ssm:GetDeployablePatchSnapshotForInstance",
            "ssm:GetDocument",
            "ssm:GetManifest",
            "ssm:GetParameter",
            "ssm:GetParameters",
            "ssm:ListAssociations",
            "ssm:ListInstanceAssociations",
            "ssm:PutComplianceItems",
            "ssm:PutConfigurePackageResult",
            "ssm:PutInventory",
            "ssm:UpdateAssociationStatus",
            "ssm:UpdateInstanceAssociationStatus",
            "ssm:UpdateInstanceInformation",
            "ssmmessages:CreateControlChannel",
            "ssmmessages:CreateDataChannel",
            "ssmmessages:OpenControlChannel",
            "ssmmessages:OpenDataChannel",
            "tag:GetResources",
            "tag:TagResources",
            "waf:GetWebACL",
            "wafv2:GetWebACLForResource",
            "wafv2:GetWebACL",
            "wafv2:AssociateWebACL",
            "wafv2:DisassociateWebACL",
            "waf-regional:GetWebACLForResource",
            "waf-regional:GetWebACL",
            "waf-regional:AssociateWebACL",
            "waf-regional:DisassociateWebACL"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:GetObject"
          ],
          "Resource": [
            "arn:aws:s3:::bucket-other",
            "arn:aws:s3:::bucket-other/*"
          ]
        },
        {
          "Action": "s3:*",
          "Resource": "arn:aws:s3:::bucket1",
          "Effect": "Allow"
        },
        {
          "Action": "s3:*",
          "Resource": "arn:aws:s3:::bucket1/*",
          "Effect": "Allow"
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/ZXY45LXGS388X",
            "arn:aws:route53:::hostedzone/Z2MTU4ZZKP5JT4"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "acm:DescribeCertificate",
            "acm:ListCertificates",
            "acm:GetCertificate",
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "cognito-idp:DescribeUserPoolClient",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CreateNetworkAclEntry",
            "ec2:CreateSecurityGroup",
            "ec2:CreateTags",
            "ec2:DeleteTags",
            "ec2:DeleteSecurityGroup",
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeAddresses",
            "ec2:DescribeInstances",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeInstanceStatus",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeLaunchTemplateVersions",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSubnets",
            "ec2:DescribeTags",
            "ec2:DescribeVpcs",
            "ec2:ModifyInstanceAttribute",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:ReplaceNetworkAclEntry",
            "ec2:RevokeSecurityGroupIngress",
            "ec2messages:AcknowledgeMessage",
            "ec2messages:DeleteMessage",
            "ec2messages:FailMessage",
            "ec2messages:GetEndpoint",
            "ec2messages:GetMessages",
            "ec2messages:SendReply",
            "elasticloadbalancing:AddListenerCertificates",
            "elasticloadbalancing:AddTags",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:CreateRule",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DeleteRule",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:DescribeListenerCertificates",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeLoadBalancerAttributes",
            "elasticloadbalancing:DescribeRules",
            "elasticloadbalancing:DescribeSSLPolicies",
            "elasticloadbalancing:DescribeTags",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeTargetGroupAttributes",
            "elasticloadbalancing:DescribeTargetHealth",
            "elasticloadbalancing:ModifyListener",
            "elasticloadbalancing:ModifyLoadBalancerAttributes",
            "elasticloadbalancing:ModifyRule",
            "elasticloadbalancing:ModifyTargetGroup",
            "elasticloadbalancing:ModifyTargetGroupAttributes",
            "elasticloadbalancing:RegisterTargets",
            "elasticloadbalancing:RemoveListenerCertificates",
            "elasticloadbalancing:RemoveTags",
            "elasticloadbalancing:SetIpAddressType",
            "elasticloadbalancing:SetSecurityGroups",
            "elasticloadbalancing:SetSubnets",
            "elasticloadbalancing:SetWebACL",
            "iam:CreateServiceLinkedRole",
            "iam:GetServerCertificate",
            "iam:ListServerCertificates",
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets",
            "ssm:DescribeAssociation",
            "ssm:DescribeDocument",
            "ssm:GetDeployablePatchSnapshotForInstance",
            "ssm:GetDocument",
            "ssm:GetManifest",
            "ssm:GetParameter",
            "ssm:GetParameters",
            "ssm:ListAssociations",
            "ssm:ListInstanceAssociations",
            "ssm:PutComplianceItems",
            "ssm:PutConfigurePackageResult",
            "ssm:PutInventory",
            "ssm:UpdateAssociationStatus",
            "ssm:UpdateInstanceAssociationStatus",
            "ssm:UpdateInstanceInformation",
            "ssmmessages:CreateControlChannel",
            "ssmmessages:CreateDataChannel",
            "ssmmessages:OpenControlChannel",
            "ssmmessages:OpenDataChannel",
            "tag:GetResources",
            "tag:TagResources",
            "waf:GetWebACL",
            "wafv2:GetWebACLForResource",
            "wafv2:GetWebACL",
            "wafv2:AssociateWebACL",
            "wafv2:DisassociateWebACL",
            "waf-regional:GetWebACLForResource",
            "waf-regional:GetWebACL",
            "waf-regional:AssociateWebACL",
            "waf-regional:DisassociateWebACL"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  clusterAutoscaler:
    cpuRequest: 100m
    enabled: true
    memoryRequest: 300Mi
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  configBase: s3://clusters.k8s.acme.com/cluster1.k8s.acme.com
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: overlord-alpha
      name: alpha
    - encryptedVolume: true
      instanceGroup: overlord-beta
      name: beta
    - encryptedVolume: true
      instanceGroup: overlord-gamma
      name: gamma
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: overlord-alpha
      name: alpha
    - encryptedVolume: true
      instanceGroup: overlord-beta
      name: beta
    - encryptedVolume: true
      instanceGroup: overlord-gamma
      name: gamma
    memoryRequest: 100Mi
    name: events
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: overlord-alpha
      name: alpha
    - encryptedVolume: true
      instanceGroup: overlord-beta
      name: beta
    - encryptedVolume: true
      instanceGroup: overlord-gamma
      name: gamma
    memoryRequest: 100Mi
    name: cilium
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    nodeLocalDNS:
      enabled: true
    provider: CoreDNS
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 192.168.1.1/32
  kubernetesVersion: 1.20.7
  masterInternalName: api.internal.cluster1.k8s.acme.com
  masterPublicName: api.cluster1.k8s.acme.com
  metricsServer:
    enabled: true
  networkCIDR: 172.31.0.0/16
  networkID: vpc-31d64546
  networking:
    cilium:
      clusterName: cluster1.k8s.acme.com
      enableNodePort: true
      enableRemoteNodeIdentity: false
      etcdManaged: true
      hubble:
        enabled: true
      preallocateBPFMaps: true
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 50.19.247.202/32
  subnets:
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.32.0/19
    egress: nat-06c85206583d5d27a
    name: cluster1-alpha
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    egress: nat-06c85206583d5d27a
    name: cluster1-beta
    type: Private
    zone: us-east-1a
  - cidr: 172.20.96.0/19
    egress: nat-06c85206583d5d27a
    name: cluster1-gamma
    type: Private
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-11T07:23:42Z"
  labels:
    kops.k8s.io/cluster: cluster1.k8s.acme.com
  name: overlord-alpha
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: overlord-alpha
  role: Master
  rootVolumeSize: 16
  subnets:
  - cluster1-alpha

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-11T07:23:43Z"
  labels:
    kops.k8s.io/cluster: cluster1.k8s.acme.com
  name: overlord-beta
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: overlord-beta
  role: Master
  rootVolumeSize: 16
  subnets:
  - cluster1-beta

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-11T07:23:43Z"
  labels:
    kops.k8s.io/cluster: cluster1.k8s.acme.com
  name: overlord-gamma
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: overlord-gamma
  role: Master
  rootVolumeSize: 16
  subnets:
  - cluster1-gamma

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-11T07:23:43Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster1.k8s.acme.com
  name: spots-alpha
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5b.xlarge
  maxPrice: ".12"
  maxSize: 5
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spots-alpha
    on-demand: "false"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster1-alpha

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-11T07:23:43Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster1.k8s.acme.com
  name: spots-beta
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5n.xlarge
  maxPrice: ".16"
  maxSize: 5
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spots-beta
    on-demand: "false"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster1-beta

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-11T07:23:43Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster1.k8s.acme.com
  name: spots-gamma
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5a.xlarge
  maxPrice: ".12"
  maxSize: 5
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spots-gamma
    on-demand: "false"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster1-gamma


```

**9. Anything else do we need to know?**

![wrongvol](https://user-images.githubusercontent.com/140495/121915734-7fef9080-cd01-11eb-84ba-b0646136072a.jpg)

Now, when I go look at the overlord-gamma node, it is on the right subnet, meaning "cluster1-gamma." This looks like to be specific to the etcd volume naming.
