### ISSUE TITLE
Cannot to rollout nodes on clusters that have Spot IGs

### ISSUE THREAD

**Issue by nettoclaudio** [kubernetes/kops#11766]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.19.1 (git-8589b4d157a9cb05c54e320c77b0724c4dd094b2)
```

I think the problem is happening since we merged the PR https://github.com/kubernetes/kops/pull/9118. So we're getting this problem around the v1.18.0 release.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS and Spot integration

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```bash
KOPS_FEATURE_FLAGS="Spotinst,SpotinstOcean,SpotinstHybrid" \
kops rolling-update cluster --state s3://my-bucket --name alpha.k8s.example.com --yes
```

**5. What happened after the commands executed?**

Node validation fails when it reaches IGs managed as Spot instances. 

```
I0614 14:54:46.315524   17718 instancegroups.go:471] Cluster did not pass validation within deadline: InstanceGroup "my-spot-ig" is missing from the cloud provider.
```

**6. What did you expect to happen?**

Node validation should skip the Spot Instance Groups as they don't appear in the cloud provider.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: alpha.k8s.example.com
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public

  cloudProvider: aws

  configBase: s3://my-bucket/alpha.k8s.example.com

  etcdClusters:
  - name: main
    version: 3.3.10
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: master-us-east-1a
      volumeSize: 50

  - name: events
    version: 3.3.10
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: master-us-east-1a
      volumeSize: 100

  kubeDNS:
    provider: CoreDNS

  kubernetesVersion: 1.18.18

  masterPublicName: api.alpha.k8s.example.com
  masterInternalName: api.internal.alpha.k8s.example.com

  networkCIDR: 172.21.80.0/21
  nonMasqueradeCIDR: 10.128.0.0/12

  sshAccess:
  - 0.0.0.0/0

  subnets:
  - cidr: 172.21.80.0/24
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.21.81.0/24
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.21.83.0/24
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.21.84.0/24
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.21.85.0/24
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.21.86.0/24
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c

  networking:
    cni: {}

  topology:
    dns:
      type: Public

    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: my-spot-ig
  labels:
    kops.k8s.io/cluster: alpha.k8s.example.com
    spotinst.io/autoscaler-disabled: "false"
    spotinst.io/autoscaler-headroom-cpu-per-unit: "0"
    spotinst.io/autoscaler-headroom-mem-per-unit: "0"
    spotinst.io/autoscaler-headroom-num-of-units: "0"
    spotinst.io/autoscaler-scale-down-max-percentage: "5"
    spotinst.io/draining-timeout: "900"
    spotinst.io/hybrid: "true"
    spotinst.io/ocean-default-launchspec: "true"
    spotinst.io/ocean-instance-types-whitelist: c4.xlarge, c4.2xlarge, c4.4xlarge, c5.xlarge,
      c5.2xlarge, c5.4xlarge, c5d.xlarge, c5d.2xlarge, c5d.4xlarge, c5n.xlarge, c5n.2xlarge,
      c5n.4xlarge, h1.2xlarge, h1.4xlarge, i3.xlarge, i3.2xlarge, i3.4xlarge, i3en.xlarge,
      i3en.2xlarge, m4.xlarge, m4.2xlarge, m4.4xlarge, m5.xlarge, m5.2xlarge, m5.4xlarge,
      m5a.xlarge, m5a.2xlarge, m5a.4xlarge, m5ad.xlarge, m5ad.2xlarge, m5ad.4xlarge, m5d.xlarge,
      m5d.2xlarge, m5d.4xlarge, m5dn.xlarge, m5dn.2xlarge, m5dn.4xlarge, m5n.xlarge, m5n.2xlarge,
      m5n.4xlarge, r4.xlarge, r4.2xlarge, r4.4xlarge, r5.xlarge, r5.2xlarge, r5.4xlarge,
      r5a.xlarge, r5a.2xlarge, r5a.4xlarge, r5ad.xlarge, r5ad.2xlarge, r5ad.4xlarge, r5d.xlarge,
      r5d.2xlarge, r5d.4xlarge, r5dn.xlarge, r5dn.2xlarge, r5dn.4xlarge, r5n.xlarge, r5n.2xlarge,
      r5n.4xlarge
    spotinst.io/utilize-reserved-instances: "false"
spec:
  cloudLabels:
    k8s.io/cluster/alpha.k8s.example.com: "true"
    kubernetes.io/cluster/alpha.k8s.example.com: "true"

  machineType: c5.2xlarge

  maxSize: 100
  minSize: 1

  nodeLabels:
    kops.k8s.io/cluster: alpha.k8s.example.com
    kops.k8s.io/instancegroup: my-spot-ig

  role: Node

  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c

  taints:
  - spotInstance=true:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

N/A
