### ISSUE TITLE
Service accounts have unrestricted access on cluster

### ISSUE THREAD

**Issue by gfilis2** [kubernetes/kops#11802]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```bash
Version 1.18.2 (git-84495481e4)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```bash
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```bash
kubectl create serviceaccount test-access

kubectl get serviceaccounts test-access -n namespace_test -o jsonpath={.secrets}

export TOKEN=$(kubectl get secret test-access-ppqrl -o jsonpath={.data.token} | base64 -d)

curl https://<MYCLUSTER>/api/v1/namespaces/<ANY_NAMESPACE>/pods -H "Authorization: Bearer $TOKEN" \
   -k
```

**5. What happened after the commands executed?**
I was able to access any resource in any namespace. The above example tested against pods.

**6. What did you expect to happen?**
I was expecting to receive HTTP 403. Clusters have RBAC enabled, so by default service accounts should not have any permissions.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: MYCLUSTER
spec:
  DisableSubnetTags: true
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": [
            "arn:aws:iam::AWS_ACCOUNT_1:role/*",
            "arn:aws:iam::AWS_ACCOUNT_2:role/*",
            "arn:aws:iam::AWS_ACCOUNT_3:role/*"
          ]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://MY_BUCKET/MYCLUSTER
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 200Mi
    name: main
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 200Mi
    name: events
  iam:
    legacy: false
  kubeAPIServer:
    apiAudiences:
    - api
    - istio-ca
    appendAdmissionPlugins:
    - ExtendedResourceToleration
    disableBasicAuth: true
    oidcClientID: MY_ID
    oidcGroupsClaim: groups
    oidcIssuerURL: https://MY_OIDC
    oidcUsernameClaim: email
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    enforceNodeAllocatable: pods
    imageGCHighThresholdPercent: 75
    imageGCLowThresholdPercent: 70
    kubeReserved:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 2000Mi
    systemReserved:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 2000Mi
  kubernetesApiAccess:
  - 10.0.0.0/16
  kubernetesVersion: 1.16.15
  masterPublicName: api.MYCLUSTER
  networkCIDR: 172.16.80.0/20
  networkID: vpc-MY_VPC
  networking:
    weave:
      memoryLimit: 1G
      mtu: 8912
      npcMemoryLimit: 3G
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 172.16.0.0/16
  - 10.50.0.0/16
  sshKeyName: MY_SSH_KEY
  subnets:
  - cidr: 172.16.80.0/23
    id: subnet-1
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.16.82.0/23
    id: subnet-2
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.16.84.0/23
    id: subnet-3
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.16.93.0/25
    id: subnet-4
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.16.93.128/25
    id: subnet-5
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.16.94.0/25
    id: subnet-6
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I also encounter this issue on kubernetes v1.18 provisioned by kops as well. 
On other kubernetes clusters, not provisioned by kops I get the expected behaviour. (Unauthorized or Unauthenticated)

**Comment by olemarkus** [comment]
Can you check the logs of `kube-apiserver` and verify that it is using the flag `--authorization-mode="[Node,RBAC]"?`
If you are creating that SA in e.g default namespace without any other modification you should definitely get a 403 response.

**Comment by gfilis2** [comment]
I check kube-apiserver. It has `--authorization-mode=RBAC`.
However I do not get a 403.

**Comment by olemarkus** [comment]
Just to confirm, this is with the above cluster spec and no other resources installed into the cluster before running the command above?

In which namespace are you creating that service account?

**Comment by gfilis2** [comment]
Yes I confirm.
The issue is reproducible in any namespace. I have already tested it in more than 2 namespaces.

**Comment by olemarkus** [comment]
```
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key
```

How are you creating and provisioning these files?
