### ISSUE TITLE
Nodes Wouldn't Connect After Master Upgrade

### ISSUE THREAD

**Issue by craig-riecke** [kubernetes/kops#11917]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.21.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.20.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
$ kops edit cluster
--- Changed version from 1.18.10 to 1.20.8
$ kops update cluster --yes
$ kops rolling-update cluster --yes
``` 

**5. What happened after the commands executed?**

Master upgraded fine, then nodes went into NotReady state.

**6. What did you expect to happen?**

Master and Nodes upgraded.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-05-03T11:48:46Z"
  generation: 7
  name: REDACTED
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Unit]
      Description=Download Heptio AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/heptio-authenticator-aws
      ExecStart=/usr/local/bin/aws s3 cp --recursive s3:REDACTED/addons/authenticator /srv/kubernetes/heptio-authenticator-aws/
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /srv/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.8
  masterInternalName: REDACTED
  masterPublicName: REDACTED
  networkCIDR: 10.92.216.0/22
  networkID: REDACTED
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.92.217.0/26
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.92.217.64/26
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.92.217.128/26
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.92.217.192/26
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-05-03T11:48:46Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-05-03T11:48:46Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1c
  - us-east-1d
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Sorry, logs scrolled off screen.  

**9. Anything else do we need to know?**

After a lot of digging around, found two bad DNS entries: one for kops-controller (which was set to the placeholder address), one for api-internal (which was set to the address of one of the nodes.  Weirdly).  Once I set both of these to the master IP (we only run one master), nodes came online and upgraded.
