### ISSUE TITLE
Enabling IMDSv2 on an instance group results in new instances failing to join cluster

### ISSUE THREAD

**Issue by mikefox** [kubernetes/kops#12066]
/kind bug

**1. What `kops` version are you running? 

Version 1.20.2 (git-e6ca69f55e91f87080c897216115efb811673718)

**2. What Kubernetes version are you running?

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I wanted to enforce IMDSv2 on all EC2 instances in the cluster. Starting with the nodes I edited the instance group and added [this](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#instancemetadata) config. Then updated the cluster and performed a rolling update.

**5. What happened after the commands executed?**

The new nodes with IMDSv2 enforced wouldn't join the cluster. Also trying to SSH into the nodes to debug and the connection was refused, suggesting the SSH agent wasn't running on the instance. Rebooting the instance and terminating to force a new instance a few times and the result was the same. None of the new instances could join the cluster. I was able to recover things by removing the instance metadata config from the instance group, updating the cluster and rolling out new nodes which were able to join the cluster without a problem.

**6. What did you expect to happen?**

I expected that adding  [this](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#instancemetadata) config to the nodes spec would result in new nodes joining the cluster with IMDSv2 enforced.

**7. Please provide your cluster manifest.

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-26T13:40:49Z"
  generation: 24
  name: XXXXXX.k8s.local
spec:
  additionalPolicies:
    master: |
      [
        {
          "Sid": "kopsK8sKMSEncrypted",
          "Effect": "Allow",
          "Action": [
            "kms:CreateGrant",
            "kms:Decrypt",
            "kms:DescribeKey",
            "kms:Encrypt",
            "kms:GenerateDataKey*",
            "kms:ReEncrypt*"
          ],
          "Resource": [
            "arn:aws:kms:eu-west-2:XXXXXXXXXXX:key/14a9834c-5b9b-4761-5b9b-07917c645837"
          ]
        }
      ]
    node: |
      [
        {
          "Sid": "kopsK8sKMSEncrypted",
          "Effect": "Allow",
          "Action": [
            "kms:CreateGrant",
            "kms:Decrypt",
            "kms:DescribeKey",
            "kms:Encrypt",
            "kms:GenerateDataKey*",
            "kms:ReEncrypt*"
          ],
          "Resource": [
            "arn:aws:kms:eu-west-2:XXXXXXXXXXX:key/14a9834c-5b9b-4761-5b9b-07917c645837"
          ]
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://XXXXX/XXXX.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - XXXXXXXXXXX/32
  - XXXXXXXXXXX/32
  - XXXXXXXXXXX/32
  - XXXXXXXXXXX/32
  - XXXXXXXXXXX/32
  kubernetesVersion: 1.17.17
  masterInternalName: api.internal.XXXX.k8s.local
  masterPublicName: api.XXXX.k8s.local
  networkCIDR: 172.16.0.0/16
  networkID: vpc-a6ad06c0
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - XXXXXXXXXXX/32
  subnets:
  - cidr: 172.16.32.0/19
    id: subnet-8d8345eb
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.16.64.0/19
    id: subnet-a83ce9e0
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.16.96.0/19
    id: subnet-e43636bf
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.16.0.0/22
    id: subnet-2079be46
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.16.4.0/22
    id: subnet-d423f69c
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.16.8.0/22
    id: subnet-8cc0c0d7
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-26T13:41:34Z"
  labels:
    kops.k8s.io/cluster: XXXX.k8s.local
  name: bastions
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-eu-west-1a
  - utility-eu-west-1b
  - utility-eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-26T13:40:49Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: XXXX.k8s.local
  name: master-eu-west-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-26T13:40:50Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: XXXX.k8s.local
  name: master-eu-west-1b
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-26T13:40:50Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: XXXX.k8s.local
  name: master-eu-west-1c
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
  - eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-26T13:40:50Z"
  generation: 12
  labels:
    kops.k8s.io/cluster: XXXX.k8s.local
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-06c248f919b13997d
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    podrole: platform
  role: Node
  rootVolumeSize: 80
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I'm hoping that upgrading the cluster to 1.19 will solve this if all else fails.
