### ISSUE TITLE
arm64 AMI seems to have gone missing

### ISSUE THREAD

**Issue by yurrriq** [kubernetes/kops#12069]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.21.0 (git-1.21.0)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
1.21.3
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops update cluster --yes
```

**5. What happened after the commands executed?**
```
master-us-east-1a.spec.image: Invalid value: "099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20210518": image specified is invalid: "099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20210518"
```

**6. What did you expect to happen?**
Successful update.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: testing.nov1.srcloud.io
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20210518
  machineType: t4g.xlarge
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - t4g.xlarge
    - m6g.xlarge
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
