### ISSUE TITLE
kops creates nodes with `gp2` EBS volume type instead of `gp3` when using Spot Ocean

### ISSUE THREAD

**Issue by xdvpser** [kubernetes/kops#12149]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.20.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.20.9
Server Version: v1.20.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create -f cluster.yaml
kops update cluster --name $NAME
kops update cluster --name $NAME --yes
```
Creating cluster using Spot Ocean.

**5. What happened after the commands executed?**

kops created nodes with `gp2` EBS volume type instead of `gp3`.

**6. What did you expect to happen?**

Nodes with EBS volume type of `gp3` to be created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

This is the only thing that matters:
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-12T16:59:39Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: some.cluster.name
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210621
  machineType: t3.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeType: gp3
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Logs from `kops update cluster --name $NAME` command:
```
LaunchSpec/some.dns.name
  	...
  	RootVolumeOpts      	{"Type":"gp3","Size":128,"IOPS":null,"Throughput":null,"Optimization":null}
  	Ocean               	name:some.dns.name id:nodes.some.dns.name
```
```
Ocean/nodes.some.dns.name 
  	...
  	RootVolumeOpts      	{"Type":null,"Size":128,"IOPS":null,"Throughput":null,"Optimization":null}
  	...
```
As you see kops creates `LaunchSpec` resource with right EBS volume type, but for some unknown reason `Ocean` resource is created with type set to `null`. This results in nodes created with `gp2` EBS volume type.

**9. Anything else do we need to know?**
