### ISSUE TITLE
Add an option to create an Internal ELB for the bastion

### ISSUE THREAD

**Issue by dezmodue** [kubernetes/kops#12147]
/kind feature

Right now if the bastion is created, the ELB associated with it is always public. 
I would like to introduce an option to define a loadBalancer of type "Internal" for the bastions, similar to what is available for the api:

```
spec:
  api:
    loadBalancer:
      type: Internal
```

Motivation: we access our network through VPN, with an `Internal` bastion ELB we would be able to ssh into our nodes without leaving our private network while still preserving the bastion as a single entry point.

I tried to implement the change in two different ways.

1. Simply adding a new field at the same level as `sshAccess` to drive this behaviour, something like:

```
  sshAccess:
    - 10.1.0.0/16
  sshLoadBalancerType: Internal
```

Being a completely new field defaulted to "Public" this would be a non breaking change and it could be backported to older versions (I'd be interested in having it available in kops >=1.18).

2. Modifying the `sshAccess` field:

```
  sshAccess:
    allowList:
    - 10.1.0.0/16
    loadBalancerType: Internal
```

or

```
  sshAccess:
    allowList:
    - 10.1.0.0/16
    loadBalancer:
      type: Internal
```

This would be a breaking change for users.

I would be happy to work on a PR given some guidance on the preferred implementation
