### ISSUE TITLE
Ubuntu Images Losing Network Connectivity with Calico on Networkd Restart

### ISSUE THREAD

**Issue by choseh** [kubernetes/kops#12160]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.20.1 (git-5a27dad40a703f646433595a2a40cf94a0c43cd5)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.20.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://github.com/projectcalico/calico/issues/4779

1. kubectl run --rm -i -t busybox --image=debian:buster-slim --restart=Never -- bash
2. apt update && apt install netcat
3. establish connection to (for example) redis on aws nc redishostname 6379
4. type PING, receive +PONG from server
5. systemctl restart systemd-networkd on host node
6. type PING in debug container from 1., no +PONG is received
7. 
**5. What happened after the commands executed?**

established connections lose connectivity

**6. What did you expect to happen?**

pods should not lose connectivity

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-05-31T09:29:26Z"
  generation: 19
  name: cluster.name
spec:
  api:
    loadBalancer:
      class: Classic
      idleTimeoutSeconds: 3600
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Bill_To: "redacted"
    Product: Kubernetes Prod
  cloudProvider: aws
  configBase: s3://statestore-bucket/cluster.name
  dnsZone: zone-id
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a-1
      name: "1"
    - instanceGroup: master-eu-central-1a-2
      name: "2"
    - instanceGroup: master-eu-central-1a-3
      name: "3"
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a-1
      name: "1"
    - instanceGroup: master-eu-central-1a-2
      name: "2"
    - instanceGroup: master-eu-central-1a-3
      name: "3"
    name: events
  fileAssets:
  - content: "apiVersion: audit.k8s.io/v1alpha1\nkind: Policy\nrules: \n  - \n    level: None\n    resources: \n      - \n        group: \"\"\n        resources: \n          - endpoints\n          - services\n    users: \n      - \"system:kube-proxy\"\n    verbs: \n      - watch\n  - \n    level: None\n    namespaces: \n      - kube-system\n    resources: \n      - \n        group: \"\"\n        resources: \n          - configmaps\n    users: \n      - \"system:unsecured\"\n    verbs: \n      - get\n  -\n    level: None\n    resources:\n      - group: \"\" # core\n      - group: \"admissionregistration.k8s.io\"\n      - group: \"apiextensions.k8s.io\"\n      - group: \"apiregistration.k8s.io\"\n      - group: \"apps\"\n      - group: \"authentication.k8s.io\"\n      - group: \"authorization.k8s.io\"\n      - group: \"autoscaling\"\n      - group: \"batch\"\n      - group: \"certificates.k8s.io\"\n      - group: \"extensions\"\n      - group: \"metrics.k8s.io\"\n      - group: \"networking.k8s.io\"\n      - group: \"policy\"\n      - group: \"rbac.authorization.k8s.io\"\n    userGroups:\n      - \"system:serviceaccounts\" \n      - \"system:nodes\"\n  -\n    level: None\n    resources:\n      - group: \"\" # core\n      - group: \"admissionregistration.k8s.io\"\n      - group: \"apiextensions.k8s.io\"\n      - group: \"apiregistration.k8s.io\"\n      - group: \"apps\"\n      - group: \"authentication.k8s.io\"\n      - group: \"authorization.k8s.io\"\n      - group: \"autoscaling\"\n      - group: \"batch\"\n      - group: \"certificates.k8s.io\"\n      - group: \"extensions\"\n      - group: \"metrics.k8s.io\"\n      - group: \"networking.k8s.io\"\n      - group: \"policy\"\n      - group: \"rbac.authorization.k8s.io\"\n      - group: \"scheduling.k8s.io\"\n    users:\n      - \"system:apiserver\"\n      - \"kops\"\n  - level: None\n    userGroups: [\"system:authenticated\"]\n    nonResourceURLs:\n    - \"/api*\" # Wildcard matching.\n    - \"/version\"\n  - \n    level: None\n    resources: \n      - \n        group: \"\"\n        resources: \n          - nodes\n    users: \n      - kubelet\n    verbs: \n      - get\n  - \n    level: None\n    resources: \n      - \n        group: \"\"\n        resources: \n          - nodes\n    userGroups: \n      - \"system:nodes\"\n    verbs: \n      - get\n  - \n    level: None\n    namespaces: \n      - kube-system\n    resources: \n      - \n        group: \"\"\n        resources: \n          - endpoints\n    users: \n      - \"system:kube-controller-manager\"\n      - \"system:kube-scheduler\"\n      - \"system:serviceaccount:kube-system:endpoint-controller\"\n    verbs: \n      - get\n      - update\n  - \n    level: None\n    resources: \n      - \n        group: \"\"\n        resources: \n          - namespaces\n    users: \n      - \"system:apiserver\"\n    verbs: \n      - get\n  - \n    level: None\n    nonResourceURLs: \n      - /healthz*\n      - /version\n      - /swagger*\n  - \n    level: None\n    resources: \n      - \n        group: \"\"\n        resources: \n          - events\n  - \n    level: Metadata\n    resources: \n      - \n        group: \"\"\n        resources: \n          - secrets\n          - configmaps\n      - \n        group: authentication.k8s.io\n        resources: \n          - tokenreviews\n  - \n    level: Request\n    resources: \n      - group: \"\" # core\n      - group: \"admissionregistration.k8s.io\"\n      - group: \"apps\"\n      - group: \"authentication.k8s.io\"\n      - group: \"authorization.k8s.io\"\n      - group: \"autoscaling\"\n      - group: \"batch\"\n      - group: \"certificates.k8s.io\"\n      - group: \"extensions\"\n      - group: \"networking.k8s.io\"\n      - group: \"policy\"\n      - group: \"rbac.authorization.k8s.io\"\n    verbs: \n      - get\n      - list\n      - watch\n  - \n    level: RequestResponse\n    resources:\n      - group: \"\" # core\n      - group: \"admissionregistration.k8s.io\"\n      - group: \"apps\"\n      - group: \"authentication.k8s.io\"\n      - group: \"authorization.k8s.io\"\n      - group: \"autoscaling\"\n      - group: \"batch\"\n      - group: \"certificates.k8s.io\"\n      - group: \"extensions\"\n      - group: \"networking.k8s.io\"\n      - group: \"policy\"\n      - group: \"rbac.authorization.k8s.io\"\n  - \n    level: Metadata\n"
    name: audit-config
    path: /srv/kubernetes/audit.conf
    roles:
    - Master
  - content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "0";

      APT::Periodic::AutocleanInterval "7";
    name: unattended-upgrades-disable
    path: /etc/apt/apt.conf.d/20auto-upgrades
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.conf
    logLevel: 1
  kubeDNS:
    nodeLocalDNS:
      cpuRequest: 25m
      enabled: true
      memoryRequest: 5Mi
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    maxPods: 150
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.7
  masterInternalName: api.internal.cluster.name
  masterPublicName: api.cluster.name
  networkCIDR: 10.20.24.0/21
  networkID: vpc-id
  networking:
    calico:
      ipv4AutoDetectionMethod: can-reach=10.20.24.184
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.100.0.0/16
  - 10.0.2.0/24
  subnets:
  - cidr: 10.20.24.0/24
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 10.20.25.0/24
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 10.20.28.0/23
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.20.30.0/23
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-05-31T09:29:26Z"
  generation: 10
  labels:
    kops.k8s.io/cluster: cluster.name
  name: master-eu-central-1a-1
spec:
  associatePublicIp: false
  cloudLabels:
    Backup: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: c5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a-1
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-05-31T09:29:26Z"
  generation: 10
  labels:
    kops.k8s.io/cluster: cluster.name
  name: master-eu-central-1a-2
spec:
  associatePublicIp: false
  cloudLabels:
    Backup: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: c5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a-2
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-05-31T09:29:26Z"
  generation: 10
  labels:
    kops.k8s.io/cluster: cluster.name
  name: master-eu-central-1a-3
spec:
  associatePublicIp: false
  cloudLabels:
    Backup: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: c5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a-3
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-26T17:44:36Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: cluster.name
  name: mem
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: r5.xlarge
  maxPrice: "0.50"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - r5.xlarge
    - r5a.xlarge
    - r4.xlarge
    - m5.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: mem
    lifecycle: Ec2Spot
    node-role.kubernetes.io/mem: "true"
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  subnets:
  - eu-central-1a
  taints:
  - node-role.kubernetes.io/mem=true:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-06T08:52:17Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: cluster.name
  name: nodes-fallback
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: c5.xlarge
  maxSize: 20
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-fallback
    lifecycle: OnDemand
    node-role.kubernetes.io/worker: "true"
  role: Node
  subnets:
  - eu-central-1a
  taints:
  - node-role.kubernetes.io/worker=true:PreferNoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-06T08:43:09Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: cluster.name
  name: nodes-spot
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: c5.xlarge
  maxSize: 20
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c5.xlarge
    - m5.xlarge
    - c5a.xlarge
    - c4.xlarge
    - m4.xlarge
    - c5.2xlarge
    - c5a.2xlarge
    - m5a.2xlarge
    - m5.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-spot
    lifecycle: Ec2Spot
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  subnets:
  - eu-central-1a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I raised the original issue with the calico guys, but since this is something Ubuntu does, I think it's worth discussing with you.
Using the default ubuntu image basically renders calico unusable to a certain extent. Whenever there is an unattended-upgrade that restarts networkd, pods lose their connecticity and render established connections in a comatose state.
I have currently disabled unattended upgrades, which is not an appropriate workaround for this imho. Do other available distros have the same issue? Is there something that can be done?
Appreciate any advice, thanks.

Original Ubuntu related issue: https://discuss.linuxcontainers.org/t/systemd-update-networkd-restart-breaks-routed-containers/9979

https://github.com/projectcalico/calico/issues/4779
