### ISSUE TITLE
panic: Terraform resource names cannot start with a digit. This is a bug in Kops, please report this in a GitHub Issue. Name: 208.*.*.net

### ISSUE THREAD

**Issue by vladimirkus** [kubernetes/kops#12199]
/kind bug

Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

k8s: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

AWS

kops update cluster 208.*.*.net --yes --out output/208/ --target=terraform

Kops exited with panic

Cluster update

I'm trying to update the existing cluster to enable IRSA
Cluster spec was updated with the next:
```yaml
spec:
    serviceAccountIssuerDiscovery:
        discoveryStore: s3://public-bucket
        enableAWSOIDCProvider: true
```

and 
```yaml
iam:
    serviceAccountExternalPermissions:
      - name: accountname
        namespace: namespace
        aws:
          inlinePolicy: |-
            [
              {
                "Effect": "Allow",
                "Action": "sts:AssumeRole",
                "Resource": "arn:aws:iam::000000000:role/somerole"
              }
            ]
```

but update command fails with panic.
These are the only changes that has been made to cluster and prior to the panic.
