### ISSUE TITLE
Do not set ClusterCIDR when using CNI networking

### ISSUE THREAD

**Issue by dezmodue** [kubernetes/kops#12208]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 Version 1.18.3 (git-84495481e4) - relevant code is unchanged in master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.9

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops create cluster` with a cluster definition containing `spec.networking: cni {}`

**5. What happened after the commands executed?**
The cluster was created successfully but kube-proxy was passed the option `--cluster-cidr=100.96.0.0/11`

**6. What did you expect to happen?**
I would expect the option to be unset as I didn't specify `kubeProxy.clusterCIDR` in the cluster spec. The CNI plugin I want to use requires this option to be unset and it doesn't seem to be possible when using `spec.networking: cni: {}` 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Relevant part:
```yaml
...
  networking:
    cni: {}
...
  kubelet:
    cloudProvider: aws
    anonymousAuth: false
    featureGates:
      EphemeralContainers: "true"
      HPAScaleToZero: "true"
      ImmutableEphemeralVolumes: "true"
      ServiceTopology: "true"
  kubeProxy:
    metricsBindAddress: 0.0.0.0
    featureGates:
      EphemeralContainers: "true"
      HPAScaleToZero: "true"
      ImmutableEphemeralVolumes: "true"
      ServiceTopology: "true"
      EndpointSliceProxying: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
    featureGates:
      EphemeralContainers: "true"
      HPAScaleToZero: "true"
      ImmutableEphemeralVolumes: "true"
      ServiceTopology: "true"
  kubeScheduler:
    featureGates:
      EphemeralContainers: "true"
      HPAScaleToZero: "true"
      ImmutableEphemeralVolumes: "true"
      ServiceTopology: "true"
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
AmazonVPC networking requires --cluster-cidr to be unset - https://github.com/kubernetes/kops/blob/master/pkg/model/components/kubeproxy.go#L62-L67
Attempted a PR https://github.com/kubernetes/kops/pull/12207
