### ISSUE TITLE
Kops upgrade 1.17.x to 1.21.1, doesn't update kops-controller addon yaml

### ISSUE THREAD

**Issue by AnubhavSabharwa** [kubernetes/kops#12242]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.21.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.3

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
1. Scaled down the existing 1.17.6 cluster using autoscaling group
2. Moving all the files of existing 1.17.6 cluster from old KOPS_STATE_STORE (S3 bucket) to new s3 bucket
3. Now, replaced the cluster and instance group spec
4. kops update cluster --lifecycle-overrides InternetGateway=Ignore,IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges --yes
**5. What happened after the commands executed?**
After this, it creates the instances however, kops-controller gives issues related to sts.endpoint which was present in 1.21.0 version [https://github.com/kubernetes/kops/pull/12043](12043)
The kops-controller file is still pointing 1.21.0 , where it should be pointing to 1.21.1
**6. What did you expect to happen?**
After running update command by replacing cluster and instancegroup spec, it should update the addons to 1.21.1 version

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  generation: 1
  name: 1.21.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Internal
  assets:
    containerProxy: docker.tools.aws
  authorization:
    rbac: {}
  channel: https://nexus.tools.aws/repository/kops-channels/stable
  cloudProvider: aws
  configBase: s3://kops-us-east-1/1.21.k8s.local
  docker:
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=100m
    - max-file=3
    # skipInstall: true
    packages:
      hashAmd64: a7a0c6a2ed5148d7f0e2ce9e9efd9841949cbac2
      urlAmd64: https://nexus.tools.aws/repository/docker/docker-20.10.7.tgz
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
      kmsKeyId: keyId
      encryptedVolume: true
    - instanceGroup: master-us-east-1a
      name: a
      kmsKeyId: keyId
      encryptedVolume: true
    - instanceGroup: master-us-east-1c
      name: c
      kmsKeyId: keyId
      encryptedVolume: true
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
      kmsKeyId: keyId
      encryptedVolume: true
    - instanceGroup: master-us-east-1a
      name: a
      kmsKeyId: keyId
      encryptedVolume: true
    - instanceGroup: master-us-east-1c
      name: c
      kmsKeyId: keyId
      encryptedVolume: true
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcCAFile: /etc/kubernetes/pki/kube-apiserver/cert.pem
    oidcClientID: kubernetes
    oidcGroupsClaim: groups
    oidcGroupsPrefix: oidc
    oidcIssuerURL: https://key.dev.aws/auth/realms/master
    oidcUsernamePrefix: oidc
  kubeControllerManager:
    clusterCIDR: 172.21.128.0/17
  kubeDNS:
    # coreDNSImage: toolsdocker.tools.aws/coredns:1.6.5
    provider: CoreDNS
  kubeProxy:
    clusterCIDR: 172.21.128.0/17
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: https://nexus.tools.aws/repository/kubernetes-releases/release/v1.21.3
  masterPublicName: api.1.21.k8s.local
  networkCIDR: 10.35.8.0/21
  networkID: vpc-020d7e2b10c8f940e
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 172.21.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.1/23
    id: subnet-1
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.0.0.2/23
    id: subnet-2
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.0.0.3/23
    id: subnet-3
    name: us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

```
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-01T06:12:17Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: 1.21.k8s.local
  name: master-us-east-1a
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      update-alternatives --set arptables /usr/sbin/arptables-legacy
      update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      curl -o userdata.sh -k 'https://nexus.tools.aws/repository/userdata/1.21.1.sh'
      bash userdata.sh 'https://nexus.tools.aws'
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  iam:
    profile: DevOps-Profile
  image: ami-id
  machineType: m5.large
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-01T06:12:17Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: 1.21.k8s.local
  name: master-us-east-1b
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      update-alternatives --set arptables /usr/sbin/arptables-legacy
      update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      curl -o userdata.sh -k 'https://nexus.tools.aws/userdata/1.21.1.sh'
      bash userdata.sh 'https://nexus.tools.aws'
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  iam:
    profile: DevOps-Profile
  image: ami-id
  machineType: m5.large
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-01T06:12:17Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: 1.21.k8s.local
  name: master-us-east-1c
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      update-alternatives --set arptables /usr/sbin/arptables-legacy
      update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      curl -o userdata.sh -k 'https://nexus.tools.aws/userdata/1.21.1.sh'
      bash userdata.sh 'https://nexus.tools.aws'
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  iam:
    profile: DevOps-Profile
  image: ami-id
  machineType: m5.large
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-01T06:12:17Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: 1.21.k8s.local
  name: nodes
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      update-alternatives --set arptables /usr/sbin/arptables-legacy
      update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      curl -o userdata.sh -k 'https://nexus.tools.aws/userdata/1.21.1.sh'
      bash userdata.sh https://nexus.tools.aws
    name: myscript.sh
    type: text/x-shellscript
  associatePublicIp: false
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    # kubernetes.io/cluster/1.21.k8s.local: owned
  iam:
    profile: DevOps-Profile
  image: ami-id
  machineType: m5.large
  maxPrice: "0.21"
  maxSize: 100
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
After manually updating the kops-controller.yaml, it is giving same issue as https://github.com/kubernetes/kops/issues/12225
