### ISSUE TITLE
spec.containerd.version is ignored when using Flatcar Container Linux

### ISSUE THREAD

**Issue by 6929400** [kubernetes/kops#12250]
/kind bug

https://kops.sigs.k8s.io/cluster_spec/#configuration (https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#configuration) doesn't make clear that specifying the desired containerd version is ignored when using Flatcar Container Linux.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.21.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.20.10

**3. What cloud provider are you using?**
Google Cloud

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create mycluster --state=s3://kops-mycluster -f mycluster.yaml
kops update cluster mycluster --state=s3://kops-mycluster --yes
```

**5. What happened after the commands executed?**
Running `containerd -v` on the nodes returns the version that comes preinstalled with Kinvolk Flatcar Container Linux.

**6. What did you expect to happen?**
Running `containerd -v` on the nodes returns the version requested using `spec.containerd.version`.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-09-01T12:00:00Z"
  name: mycluster
spec:
  containerRuntime: containerd
  containerd:
    version: 1.4.9
[...]
```

Keep up the good work. :)
