### ISSUE TITLE
Kubelet unable to pass cpuCFSQuotaPeriod after k8s version >= v1.20

### ISSUE THREAD

**Issue by dntosas** [kubernetes/kops#12304]
Starting from k8s v1.20, Kubelet is not allowed to pass as flag the option `cpuCFSQuotaPeriod` as this is now only supported to be defined on [Kubelet-config-file](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file) [spec](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/).

Posting here a workaround if your setup relies on this option until Kops will add support for building a config file for Kubelet.

The error message we mitigate in here https://github.com/kubernetes/kops/pull/12292:
```
kubelet[5122]: F0909 11:49:28.458628    5122 server.go:215] invalid configuration: cpuCFSQuotaPeriod {10ms}
```

1. Using `hooks` on **cluster.spec**
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: NAME
spec:
  hooks:
    - name: kernel-cpu-cfs-quota-period-tune.service
      manifest: |
        Type=oneshot
        ExecStart=/sbin/sysctl kernel.sched_cfs_bandwidth_slice_us=25000 ; \
                  /sbin/sysctl -p
```

2. Using `sysctlParameters` on **instancegroup.spec**                  
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: NAME
spec:  
  sysctlParameters:
  - kernel.sched_cfs_bandwidth_slice_us=25000
```
