### ISSUE TITLE
Should we default creation of a bastion public hostname?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1235]
Right now you have to add this:

```
  topology:
    masters: public
    nodes: public
    bastion:
      bastionPublicName: bastion.example.com
```

Should we do this by default @kris-nova ?
