### ISSUE TITLE
AWS: Adding masters on new Subnets and AZs fails when using a NLB with error "network load balancers do not support detaching subnets"

### ISSUE THREAD

**Issue by pinaki124** [kubernetes/kops#12404]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
kops version
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
1.21.4
```
**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create cluster using the kops CLI
```
kops create cluster --name "<cluster name>" \
--cloud "aws" \
--zones "us-east-2a" \
--network-cidr "172.31.0.0/24" \
--dns "public" \
--dns-zone "<Hosted zone>" \
--associate-public-ip \
--networking "kubenet" \
--master-public-name "<master-public-name>" \
--master-size "t3.medium" \
--master-count 1 \
--master-volume-size 10 \
--node-size "t3.medium" \
--node-count 3 \
--node-volume-size 100 \
--api-loadbalancer-class "network" \
--api-loadbalancer-type "public" \
--api-ssl-certificate "<certificate ARN>"
```
```
kops update cluster --name "<cluster name>" --yes --admin
```
```
kops validate cluster --name "<cluster name>" --wait 10m
```
Cluster gets provisioned successfully - NLB gets created and healthy. NLB points to a single subnet on the single AZ as per the request - us-east-2a. All good so far...

Followed the docs here https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md to add a new master.

Pull the Kubernetes cluster definition:
```
kops get --name "<cluster name>" -o yaml > cluster-def-generated.yaml
```
Added 2 new Subnet CIDR, updated the etcdClusters block with the new AZ and updated the file cluster-def-generated.yaml
```
  subnets:
  - cidr: 172.31.0.32/27 (Existing subnet)
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.31.0.64/27 (New subnet)
    name: us-east-2b
    type: Public
    zone: us-east-2b
  - cidr: 172.31.0.96/27 (New subnet)
    name: us-east-2c
    type: Public
    zone: us-east-2c
```
```
    etcdMembers:
    - encryptedVolume: true (Existing)
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true (New)
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true (New)
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true (Existing)
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true (New)
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true (New)
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: events
```
Replace the config
```
kops replace -f cluster-def-generated.yaml
```
Create a new instance group for the new masters, by running the commands:
```
kops create instancegroup master-us-east-2b --subnet us-east-2b --role Master
```
```
kops create instancegroup master-us-east-2c --subnet us-east-2c --role Master
```
Update the cluster
```
kops update cluster -v 10 --name "<cluster name>" --yes --admin
```
**5. What happened after the commands executed?**

After the cluster update command was executed upon adding the new masters, the update kept failing with the below error:

```
network load balancers do not support detaching subnets
```
**6. What did you expect to happen?**

I expected the Network load balancer to have got updated with the 'new' subnets on the newly added availability zones, instead the process incorrectly seemed to have detected that I was removing Subnets.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Before adding the new masters - after the cluster was provisioned the first time
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-09-23T20:10:05Z"
  name: <cluster name>
spec:
  api:
    loadBalancer:
      class: Network
      sslCertificate: <certificate ARN>
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Owner: calculi
    Purpose: Local
  cloudProvider: aws
  configBase: s3://<s3 bucket>/<cluster name>
  dnsZone: <DNS hosted zone>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.4
  masterPublicName: <master public name>
  networkCIDR: 172.31.0.0/24
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.0.32/27
    name: us-east-2a
    type: Public
    zone: us-east-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-23T20:10:05Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-2a
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  rootVolumeSize: 10
  subnets:
  - us-east-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-23T20:10:06Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: nodes-us-east-2a
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-2a
  role: Node
  rootVolumeSize: 100
  subnets:
  - us-east-2a
```

After adding the new Subnets, AZs and masters, this is the cluster definition 
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-09-23T22:55:53Z"
  generation: 1
  name: <cluster name>
spec:
  api:
    loadBalancer:
      class: Network
      sslCertificate: <certificate arn>
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Owner: calculi
    Purpose: Local
  cloudProvider: aws
  configBase: s3://<s3 bucket>/<cluster name>
  dnsZone: <dns hosted zone>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.4
  masterPublicName: <master public name>
  networkCIDR: 172.31.0.0/24
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.0.32/27
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.31.0.64/27
    name: us-east-2b
    type: Public
    zone: us-east-2b
  - cidr: 172.31.0.96/27
    name: us-east-2c
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-23T22:55:54Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-2a
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  rootVolumeSize: 10
  subnets:
  - us-east-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-24T03:38:31Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2b
  role: Master
  subnets:
  - us-east-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-24T03:38:42Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-2c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2c
  role: Master
  subnets:
  - us-east-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-09-23T22:55:54Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: nodes-us-east-2a
spec:
  associatePublicIp: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-2a
  role: Node
  rootVolumeSize: 100
  subnets:
  - us-east-2a
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/pinaki124/409f0194750271321d5d141044ebd616

**9. Anything else do we need to know?**
