### ISSUE TITLE
Cluster does not start when AWS Region us-west-2 is disabled

### ISSUE THREAD

**Issue by TwoStone** [kubernetes/kops#12408]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.20.2 (git-e6ca69f55e91f87080c897216115efb811673718)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`1.20.9`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Install a new cluster with `networking.amazonvpc: {}` in an aws account where the region us-west-2 is disabled.

**5. What happened after the commands executed?**

Cluster is setup, but master nodes will not get ready because the kubelet is not able to pull the aws cni images from the ecr.
The aws-node pods fail with `failed to resolve reference "602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.7.10": unexpected status code [manifests v1.7.10]: 401 Unauthorized`

Looking at the kubelet log we see the error message:
`error getting credentials from ECR for 602401143452.dkr.ecr.us-west-2.amazonaws.com AccessDeniedException: User: arn:aws:sts::######:assumed-role/##### is not authorized to perform: ecr:GetAuthorizationToken on resource: * with an explicit deny`

**6. What did you expect to happen?**

We expect that the cluster starts without any image pull failures.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 10
  name: k8s.example.com
spec:
  additionalPolicies: {}
  api:
    loadBalancer:
      class: Network
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.k8s.example.com/k8s.example.com
  containerRuntime: containerd
  dnsZone: k8s.example.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: eu-central-1a
    - instanceGroup: master-eu-central-1b
      name: eu-central-1b
    - instanceGroup: master-eu-central-1c
      name: eu-central-1c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: eu-central-1a
    - instanceGroup: master-eu-central-1b
      name: eu-central-1b
    - instanceGroup: master-eu-central-1c
      name: eu-central-1c
    name: events
  externalPolicies: {}
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    clusterCIDR: 10.2.16.0/20
  kubeDNS:
    provider: CoreDNS
  kubelet:
    cloudProvider: aws
    evictionHard: memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    kubeReserved:
      cpu: 200m
      memory: 1.5Gi
    maxPods: 50
    systemReserved:
      cpu: 250m
      memory: 1Gi
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.9
  masterInternalName: api.internal.k8s.example.com
  masterPublicName: api.k8s.example.com
  networkCIDR: 10.2.0.0/16
  networkID: vpc-0204ecb6626b668e9
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.2.0.0/16
  serviceClusterIPRange: 10.2.32.0/20
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.2.0.0/26
    id: subnet-06f102e55dddd96f7
    name: eu-central-1a-master
    type: Private
    zone: eu-central-1a
  - cidr: 10.2.0.64/26
    id: subnet-0a1f1455775a0bdac
    name: eu-central-1b-master
    type: Private
    zone: eu-central-1b
  - cidr: 10.2.0.128/26
    id: subnet-03be8e6c77dadbbbd
    name: eu-central-1c-master
    type: Private
    zone: eu-central-1c
  - cidr: 10.2.2.0/23
    id: subnet-08fc9aa1517c15c43
    name: eu-central-1a-nodes
    type: Private
    zone: eu-central-1a
  - cidr: 10.2.4.0/23
    id: subnet-0711ced9d28a65365
    name: eu-central-1b-nodes
    type: Private
    zone: eu-central-1b
  - cidr: 10.2.6.0/23
    id: subnet-09ae702dc1f0cadf9
    name: eu-central-1c-nodes
    type: Private
    zone: eu-central-1c
  - cidr: 10.2.8.0/24
    id: subnet-0abb7873cd9663b2e
    name: eu-central-1a-utility
    type: Utility
    zone: eu-central-1a
  - cidr: 10.2.9.0/24
    id: subnet-0c9b6526a87de4f7e
    name: eu-central-1b-utility
    type: Utility
    zone: eu-central-1b
  - cidr: 10.2.10.0/24
    id: subnet-07f164177235dca15
    name: eu-central-1c-utility
    type: Utility
    zone: eu-central-1c
  topology:
    bastion:
      bastionPublicName: bastion.k8s.example.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: bastion
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastion
  role: Bastion
  subnets:
  - eu-central-1a-utility
  - eu-central-1b-utility
  - eu-central-1c-utility

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-eu-central-1a
spec:
  additionalUserData:
  - content: |
      #!/bin/bash -xe
      swapoff -a
      sysctl vm.swappiness=0
      sysctl vm.vfs_cache_pressure=50
    name: configure-swap.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: m5d.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a-master

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-eu-central-1b
spec:
  additionalUserData:
  - content: |
      #!/bin/bash -xe
      swapoff -a
      sysctl vm.swappiness=0
      sysctl vm.vfs_cache_pressure=50
    name: configure-swap.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: m5d.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b-master

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-eu-central-1c
spec:
  additionalUserData:
  - content: |
      #!/bin/bash -xe
      swapoff -a
      sysctl vm.swappiness=0
      sysctl vm.vfs_cache_pressure=50
    name: configure-swap.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: m5d.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c-master

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: nodes-eu-central-1a
spec:
  additionalUserData:
  - content: |
      #!/bin/bash -xe
      swapoff -a
      sysctl vm.swappiness=0
      sysctl vm.vfs_cache_pressure=50
    name: configure-swap.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: r5d.xlarge
  maxSize: 15
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1a
  role: Node
  subnets:
  - eu-central-1a-nodes

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: nodes-eu-central-1b
spec:
  additionalUserData:
  - content: |
      #!/bin/bash -xe
      swapoff -a
      sysctl vm.swappiness=0
      sysctl vm.vfs_cache_pressure=50
    name: configure-swap.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: r5d.xlarge
  maxSize: 15
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1b
  role: Node
  subnets:
  - eu-central-1b-nodes

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-26T10:24:11Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: nodes-eu-central-1c
spec:
  additionalUserData:
  - content: |
      #!/bin/bash -xe
      swapoff -a
      sysctl vm.swappiness=0
      sysctl vm.vfs_cache_pressure=50
    name: configure-swap.sh
    type: text/x-shellscript
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: r5d.xlarge
  maxSize: 15
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1c
  role: Node
  subnets:
  - eu-central-1c-nodes

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
