### ISSUE TITLE
awscli not available on new ubuntu images 

### ISSUE THREAD

**Issue by ilyesAj** [kubernetes/kops#12503]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
v 1.21.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Migrating from v1.18.2 to 1.19.5

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops rolling update cluster --yes 

**5. What happened after the commands executed?**
masters are stated as ready but they are not joining the cluster 

**6. What did you expect to happen?**
New created masters joins the cluster 
**7. Please provide your cluster manifest. Execute
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: xxxxxxxx
spec:
  additionalPolicies:
    node: |
      [
        {
            "Sid": "AllowKopsBucketAccess",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "arn:aws:kms:eu-west-3:xxxx"
        }
      ]
  api:
    loadBalancer:
      additionalSecurityGroups:
      - xxxxxxxx
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxxxxxxx/xxxxxxxx
  etcdClusters:
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-a
      kmsKeyId: xxxxxxxx
      name: master-a
    - encryptedVolume: true
      instanceGroup: master-b
      kmsKeyId: xxxxxxxx
      name: master-b
    - encryptedVolume: true
      instanceGroup: master-c
      kmsKeyId: xxxxxxxx
      name: master-c
    name: main
    provider: Manager
    version: 3.2.24
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-a
      kmsKeyId: xxxxxxxx
      name: master-a
    - encryptedVolume: true
      instanceGroup: master-b
      kmsKeyId: xxxxxxxx
      name: master-b
    - encryptedVolume: true
      instanceGroup: master-c
      kmsKeyId: xxxxxxxx
      name: master-c
    name: events
    provider: Manager
    version: 3.2.24
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Unit]
      Description=Download AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/aws-iam-authenticator
      ExecStart=/usr/local/bin/aws s3 cp --recursive s3://xxxxxxxx/xxxxxxxx/addons/authenticator /srv/kubernetes/aws-iam-authenticator/
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    apiAudiences:
    - api
    - istio-ca
    authenticationTokenWebhookConfigFile: /srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.15
  masterInternalName: api.internal.xxxxxxxx
  masterPublicName: api.xxxxxxxx
  networkCIDR: xx.xx.0.0/16
  networkID: vpc-0a11fb16f1f44c4d1
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: xx.xx.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: xx.xx.0.0/22
    name: bastions-eu-west-3a
    type: Utility
    zone: eu-west-3a
  - cidr: xx.xx.4.0/22
    name: bastions-eu-west-3b
    type: Utility
    zone: eu-west-3b
  - cidr: xx.xx.8.0/22
    name: bastions-eu-west-3c
    type: Utility
    zone: eu-west-3c
  - cidr: xx.xx.24.0/22
    name: master-a-eu-west-3a
    type: Private
    zone: eu-west-3a
  - cidr: xx.xx.28.0/22
    name: master-b-eu-west-3b
    type: Private
    zone: eu-west-3b
  - cidr: xx.xx.32.0/22
    name: master-c-eu-west-3c
    type: Private
    zone: eu-west-3c
  - cidr: xx.xx.48.0/20
    name: nodes-front-eu-west-3a
    type: Private
    zone: eu-west-3a
  - cidr: xx.xx.64.0/20
    name: nodes-front-eu-west-3b
    type: Private
    zone: eu-west-3b
  - cidr: xx.xx.80.0/20
    name: nodes-front-eu-west-3c
    type: Private
    zone: eu-west-3c
  - cidr: xx.xx.96.0/20
    name: nodes-back-eu-west-3a
    type: Private
    zone: eu-west-3a
  - cidr: xx.xx.112.0/20
    name: nodes-back-eu-west-3b
    type: Private
    zone: eu-west-3b
  - cidr: xx.xx.128.0/20
    name: nodes-back-eu-west-3c
    type: Private
    zone: eu-west-3c
  - cidr: xx.xx.144.0/20
    name: spot-nodes-eu-west-3a
    type: Private
    zone: eu-west-3a
  - cidr: xx.xx.160.0/20
    name: spot-nodes-eu-west-3b
    type: Private
    zone: eu-west-3b
  - cidr: xx.xx.176.0/20
    name: spot-nodes-eu-west-3c
    type: Private
    zone: eu-west-3c
  topology:
    bastion:
      bastionPublicName: bastion.xxxxxxxx
    dns:
      type: Private
    masters: private
    nodes: private
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: bastions
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - bastions-eu-west-3a
  - bastions-eu-west-3b
  - bastions-eu-west-3c
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: master-a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-a
  role: Master
  subnets:
  - master-a-eu-west-3a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: master-b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-b
  role: Master
  subnets:
  - master-b-eu-west-3b
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: master-c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-c
  role: Master
  subnets:
  - master-c-eu-west-3c
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: nodes-front
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: t3.small
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-front
    node-role.kubernetes.io/front-worker: "true"
  role: Node
  subnets:
  - nodes-front-eu-west-3a
  - nodes-front-eu-west-3b
  - nodes-front-eu-west-3c
  tagName: front-worker
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: nodes-back
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: c5.2xlarge
  maxSize: 15
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-back
    node-role.kubernetes.io/back-worker: "true"
  role: Node
  subnets:
  - nodes-back-eu-west-3a
  - nodes-back-eu-west-3b
  - nodes-back-eu-west-3c
  tagName: back-worker
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxxxxx
  name: spot-nodes
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907
  machineType: c5.2xlarge
  maxPrice: "0.20"
  maxSize: 25
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: spot-nodes
    on-demand: "false"
  role: Node
  subnets:
  - spot-nodes-eu-west-3a
  - spot-nodes-eu-west-3b
  - spot-nodes-eu-west-3c


```

**9. Anything else do we need to know?**

Starting from image : 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210907 
awscli is not installed in this version which a failure on the kops hook authenticator config used to download /srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml
![image](https://user-images.githubusercontent.com/34598860/136576147-fb993471-c459-42dc-b2cd-1e7b8e4f81d4.png)

This causes the api-server not to starting up .
