### ISSUE TITLE
Private cluster without a bastion should allow SSH via the API load balancer

### ISSUE THREAD

**Issue by alinehzat** [kubernetes/kops#12551]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
At the moment a cluster with the following spec becomes in accessible via SSH since the `sshAccess` CIDRs get applied to master & node security groups directly but they are placed in private subnets. A possible solution would be to allow port 22 incoming connections on the master security group & allow port 22 incoming connections on the API ELB from the same `sshAccess` CIDR list.

```
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**2. Feel free to provide a design supporting your feature request.**
This is a patch for getting it working with AWS. I haven't completely tested it yet and don't have enough experience with the other cloud platforms to finish it for them. I thought this may be a good option to have as part of kOps
[allow-ssh-via-api-elb.txt](https://github.com/kubernetes/kops/files/7370541/allow-ssh-via-api-elb.txt)

**3. Benefirst of this.**
- Keep masters in a private subnet.
- Avoid having a bastion node + associated ELB.
- Still be able to access the cluster from limited ip addresses
- Good half way house between Public cluster & Private cluster + bastion
