### ISSUE TITLE
CSI provisioner fails to use proxy provided via kops egressProxy.httpProxy setting

### ISSUE THREAD

**Issue by tomekit** [kubernetes/kops#12559]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.22.0 (git-8ba0d78c0be251c7dd5584d178c3e342037705df)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.22.2
Server Version: v1.22.2

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Spin up outbound proxy, e.g. using this template: https://raw.githubusercontent.com/aws-samples/outbound-vpc-filtering-proxy/master/sources/templates/outbound-proxy-CF.yaml

then spin up Kubernetes cluster using `egressProxy` setting and `egress: External` option added to subnet.

```
egressProxy:
    excludes: 127.0.0.1,localhost,api.v7.k8s.local,v7.k8s.local,100.64.0.1,100.64.0.0/10,169.254.169.254,10.107.0.0/16
    httpProxy:
      host: OutboundProxyLoadBalancer-<redacted>.elb.eu-west-1.amazonaws.com
      port: 3128
```
```
  subnets:
    - cidr: 10.107.32.0/19
      name: eu-west-1a
      type: Private
      egress: External
```
After cluster is ready, spin up PVC and sample Redis deployment:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: appname-redis-queue-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-redis-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname-redis-queue
  template:
    metadata:
      labels:
        app: appname-redis-queue
    spec:
      containers:
      - args:
        - --maxmemory
        - 256mb
        - --maxmemory-policy
        - noeviction
        - --appendonly
        - "yes"
        image: redis
        name: appname-redis-queue-compose
        ports:
          - containerPort: 6379
        resources:
          requests:
            cpu: "50m"
        volumeMounts:
          - mountPath: /data
            name: appname-redis-queue-volume
      restartPolicy: Always
      volumes:
        - name: appname-redis-queue-volume
          persistentVolumeClaim:
            claimName: appname-redis-queue-pvc
```

**5. What happened after the commands executed?**
After cluster creation and PVC deployment, CSI provisioner fails to initialize storage on AWS as it doesn't try to use defined via kops outbound proxy and fails to reach the AWS API. The scenario in which outbound proxy is used restricts outbound traffic to internet. Proxy is the only gateway to the internet.

**6. What did you expect to happen?**
CSI shall try to connect to AWS using outbound proxy. Perhaps `https_proxy` variable shall be (if it already isn't) passed inside the CSI controller.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-10-18T20:32:18Z"
  generation: 6
  name: v7.k8s.local
spec:
  additionalPolicies:
    node: |
      [
        {
        "Effect": "Allow",
        "Action": [
            "sts:AssumeRole"
        ],
        "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-store-appname-v7/v7.k8s.local
  egressProxy:
    excludes: 127.0.0.1,localhost,api.v7.k8s.local,v7.k8s.local,100.64.0.1,100.64.0.0/10,169.254.169.254,10.107.0.0/16
    httpProxy:
      host: OutboundProxyLoadBalancer-redacted.elb.eu-west-1.amazonaws.com
      port: 3128
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-eu-west-1a
          name: a
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-eu-west-1a
          name: a
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
      - NamespaceLifecycle
      - LimitRanger
      - ServiceAccount
      - PersistentVolumeLabel
      - DefaultStorageClass
      - DefaultTolerationSeconds
      - MutatingAdmissionWebhook
      - ValidatingAdmissionWebhook
      - NodeRestriction
      - ResourceQuota
      - AlwaysPullImages
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
    - 10.26.0.0/16
  kubernetesVersion: 1.22.2
  masterInternalName: api.internal.v7.k8s.local
  masterPublicName: api.v7.k8s.local
  networkCIDR: 10.107.0.0/16
  networkID: vpc-006b8fa8e28b12755
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 10.26.0.0/16
  subnets:
    - cidr: 10.107.32.0/19
      name: eu-west-1a
      type: Private
      egress: External
      zone: eu-west-1a
    - cidr: 10.107.0.0/22
      name: utility-eu-west-1a
      type: Utility
      zone: eu-west-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-18T20:32:18Z"
  labels:
    kops.k8s.io/cluster: v7.k8s.local
  name: master-eu-west-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: optional
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
    - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-18T20:32:18Z"
  labels:
    kops.k8s.io/cluster: v7.k8s.local
  name: nodes-eu-west-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: optional
  machineType: t3.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-1a
  role: Node
  subnets:
    - eu-west-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

`kubectl logs -f ebs-csi-controller-5f7b777cd5-b7xrr csi-provisioner -n kube-system`

```
I1019 19:59:18.628913       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"appname-s3-pvc", UID:"6b1c0d54-4fe3-4384-b32b-5642fdd05a7c", APIVersion:"v1", ResourceVersion:"235027", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "gp2": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1019 19:59:18.635233       1 connection.go:185] GRPC response: {}
I1019 19:59:18.635580       1 connection.go:186] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1019 19:59:18.635699       1 controller.go:753] CreateVolume failed, supports topology = true, node selected false => may reschedule = false => state = Background: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1019 19:59:18.636755       1 controller.go:1106] Temporary error received, adding PVC 9c511edf-a973-433a-b4f4-bdce941d5733 to claims in progress
W1019 19:59:18.636957       1 controller.go:958] Retrying syncing claim "9c511edf-a973-433a-b4f4-bdce941d5733", failure 8
E1019 19:59:18.637452       1 controller.go:981] error syncing claim "9c511edf-a973-433a-b4f4-bdce941d5733": failed to provision volume with StorageClass "gp2": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1019 19:59:18.637563       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"appname-redis-session-pvc", UID:"9c511edf-a973-433a-b4f4-bdce941d5733", APIVersion:"v1", ResourceVersion:"235025", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "gp2": rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**9. Anything else do we need to know?**
After adding NAT gateway and route table, so worker node can reach internet without proxy, **gp2 provisioner worked just fine**, this proves that this issue is indeed related to internet connectivity.

I think one issue is kops not passing properly proxy settings to CSI provisioner.

Second issue is that CSI provisioner poorly reports the network issues, it's hard to deduct from logs that it can't reach the AWS API.

Same behaviour can be seen using default storage class `kops-csi-1-21` as well.
