### ISSUE TITLE
error creating/updating IAMRolePolicy: LimitExceeded: Maximum policy size of 10240 bytes exceeded for role masters

### ISSUE THREAD

**Issue by jmcdonagh** [kubernetes/kops#12558]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.21.2 (git-f86388fb1ec8872b0ca1819cf98f84d18f7263a4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster --yes

**5. What happened after the commands executed?**

It hangs, unable to complete the task, repeating this:

```
W1019 13:09:54.275852 1601274 executor.go:139] error running task "IAMRolePolicy/masters.cluster" (9m58s remaining to succeed): error creating/updating IAMRolePolicy: LimitExceeded: Maximum policy size of 10240 bytes exceeded for role masters.cluster
	status code: 409, request id: 8cff1f18-f0ff-4ccf-8ff8-8a042fff80da
```

**6. What did you expect to happen?**

I expected the update to apply; the update also had nothing to do with IAM but it looks like since it's a newer kops version there is some updated IAM stuff.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-06-14T18:47:09Z"
  generation: 3
  name: cluster.clusters.com
spec:
  additionalNetworkCIDRs:
  - 172.22.0.0/16
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/ZXZZZZZZ",
            "arn:aws:route53:::hostedzone/Z22222ZZZZ"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "acm:DescribeCertificate",
            "acm:ListCertificates",
            "acm:GetCertificate",
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "cognito-idp:DescribeUserPoolClient",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CreateNetworkAclEntry",
            "ec2:CreateSecurityGroup",
            "ec2:CreateTags",
            "ec2:DeleteTags",
            "ec2:DeleteSecurityGroup",
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeAddresses",
            "ec2:DescribeInstances",
            "ec2:DescribeInstanceStatus",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeLaunchTemplateVersions",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSubnets",
            "ec2:DescribeTags",
            "ec2:DescribeVpcs",
            "ec2:ModifyInstanceAttribute",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:RevokeSecurityGroupIngress",
            "ec2:ReplaceNetworkAclEntry",
            "ec2messages:AcknowledgeMessage",
            "ec2messages:DeleteMessage",
            "ec2messages:FailMessage",
            "ec2messages:GetEndpoint",
            "ec2messages:GetMessages",
            "ec2messages:SendReply",
            "elasticloadbalancing:AddListenerCertificates",
            "elasticloadbalancing:AddTags",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:CreateRule",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DeleteRule",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:DescribeListenerCertificates",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeLoadBalancerAttributes",
            "elasticloadbalancing:DescribeRules",
            "elasticloadbalancing:DescribeSSLPolicies",
            "elasticloadbalancing:DescribeTags",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeTargetGroupAttributes",
            "elasticloadbalancing:DescribeTargetHealth",
            "elasticloadbalancing:ModifyListener",
            "elasticloadbalancing:ModifyLoadBalancerAttributes",
            "elasticloadbalancing:ModifyRule",
            "elasticloadbalancing:ModifyTargetGroup",
            "elasticloadbalancing:ModifyTargetGroupAttributes",
            "elasticloadbalancing:RegisterTargets",
            "elasticloadbalancing:RemoveListenerCertificates",
            "elasticloadbalancing:RemoveTags",
            "elasticloadbalancing:SetIpAddressType",
            "elasticloadbalancing:SetSecurityGroups",
            "elasticloadbalancing:SetSubnets",
            "elasticloadbalancing:SetWebACL",
            "iam:CreateServiceLinkedRole",
            "iam:GetServerCertificate",
            "iam:ListServerCertificates",
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets",
            "ssm:DescribeAssociation",
            "ssm:DescribeDocument",
            "ssm:GetDeployablePatchSnapshotForInstance",
            "ssm:GetDocument",
            "ssm:GetManifest",
            "ssm:GetParameter",
            "ssm:GetParameters",
            "ssm:ListAssociations",
            "ssm:ListInstanceAssociations",
            "ssm:PutComplianceItems",
            "ssm:PutConfigurePackageResult",
            "ssm:PutInventory",
            "ssm:UpdateAssociationStatus",
            "ssm:UpdateInstanceAssociationStatus",
            "ssm:UpdateInstanceInformation",
            "ssmmessages:CreateControlChannel",
            "ssmmessages:CreateDataChannel",
            "ssmmessages:OpenControlChannel",
            "ssmmessages:OpenDataChannel",
            "tag:GetResources",
            "tag:TagResources",
            "waf:GetWebACL",
            "wafv2:GetWebACLForResource",
            "wafv2:GetWebACL",
            "wafv2:AssociateWebACL",
            "wafv2:DisassociateWebACL",
            "waf-regional:GetWebACLForResource",
            "waf-regional:GetWebACL",
            "waf-regional:AssociateWebACL",
            "waf-regional:DisassociateWebACL"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:GetObject"
          ],
          "Resource": [
            "arn:aws:s3:::cluster-bot",
            "arn:aws:s3:::cluster-bot/*"
          ]
        },
        {
          "Action": "s3:*",
          "Resource": "arn:aws:s3:::bucket",
          "Effect": "Allow"
        },
        {
          "Action": "s3:*",
          "Resource": "arn:aws:s3:::bucket/*",
          "Effect": "Allow"
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/ZZZZZZZZZZZZN",
            "arn:aws:route53:::hostedzone/Z22222XZZZNN"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "acm:DescribeCertificate",
            "acm:ListCertificates",
            "acm:GetCertificate",
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "cognito-idp:DescribeUserPoolClient",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CreateNetworkAclEntry",
            "ec2:CreateSecurityGroup",
            "ec2:CreateTags",
            "ec2:DeleteTags",
            "ec2:DeleteSecurityGroup",
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeAddresses",
            "ec2:DescribeInstances",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeInstanceStatus",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeLaunchTemplateVersions",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSubnets",
            "ec2:DescribeTags",
            "ec2:DescribeVpcs",
            "ec2:ModifyInstanceAttribute",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:ReplaceNetworkAclEntry",
            "ec2:RevokeSecurityGroupIngress",
            "ec2messages:AcknowledgeMessage",
            "ec2messages:DeleteMessage",
            "ec2messages:FailMessage",
            "ec2messages:GetEndpoint",
            "ec2messages:GetMessages",
            "ec2messages:SendReply",
            "elasticloadbalancing:AddListenerCertificates",
            "elasticloadbalancing:AddTags",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:CreateRule",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DeleteRule",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:DescribeListenerCertificates",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeLoadBalancerAttributes",
            "elasticloadbalancing:DescribeRules",
            "elasticloadbalancing:DescribeSSLPolicies",
            "elasticloadbalancing:DescribeTags",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeTargetGroupAttributes",
            "elasticloadbalancing:DescribeTargetHealth",
            "elasticloadbalancing:ModifyListener",
            "elasticloadbalancing:ModifyLoadBalancerAttributes",
            "elasticloadbalancing:ModifyRule",
            "elasticloadbalancing:ModifyTargetGroup",
            "elasticloadbalancing:ModifyTargetGroupAttributes",
            "elasticloadbalancing:RegisterTargets",
            "elasticloadbalancing:RemoveListenerCertificates",
            "elasticloadbalancing:RemoveTags",
            "elasticloadbalancing:SetIpAddressType",
            "elasticloadbalancing:SetSecurityGroups",
            "elasticloadbalancing:SetSubnets",
            "elasticloadbalancing:SetWebACL",
            "iam:CreateServiceLinkedRole",
            "iam:GetServerCertificate",
            "iam:ListServerCertificates",
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets",
            "ssm:DescribeAssociation",
            "ssm:DescribeDocument",
            "ssm:GetDeployablePatchSnapshotForInstance",
            "ssm:GetDocument",
            "ssm:GetManifest",
            "ssm:GetParameter",
            "ssm:GetParameters",
            "ssm:ListAssociations",
            "ssm:ListInstanceAssociations",
            "ssm:PutComplianceItems",
            "ssm:PutConfigurePackageResult",
            "ssm:PutInventory",
            "ssm:UpdateAssociationStatus",
            "ssm:UpdateInstanceAssociationStatus",
            "ssm:UpdateInstanceInformation",
            "ssmmessages:CreateControlChannel",
            "ssmmessages:CreateDataChannel",
            "ssmmessages:OpenControlChannel",
            "ssmmessages:OpenDataChannel",
            "tag:GetResources",
            "tag:TagResources",
            "waf:GetWebACL",
            "wafv2:GetWebACLForResource",
            "wafv2:GetWebACL",
            "wafv2:AssociateWebACL",
            "wafv2:DisassociateWebACL",
            "waf-regional:GetWebACLForResource",
            "waf-regional:GetWebACL",
            "waf-regional:AssociateWebACL",
            "waf-regional:DisassociateWebACL"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  clusterAutoscaler:
    cpuRequest: 100m
    enabled: true
    memoryRequest: 300Mi
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  configBase: s3://clusters.clusters.com/cluster.clusters.com
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: overlord-alpha
      name: alpha
    - encryptedVolume: true
      instanceGroup: overlord-beta
      name: beta
    - encryptedVolume: true
      instanceGroup: overlord-gamma
      name: gamma
    manager:
      env:
      - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
        value: 2d
      - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
        value: 7d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: overlord-alpha
      name: alpha
    - encryptedVolume: true
      instanceGroup: overlord-beta
      name: beta
    - encryptedVolume: true
      instanceGroup: overlord-gamma
      name: gamma
    manager:
      env:
      - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
        value: 2d
      - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
        value: 7d
    memoryRequest: 100Mi
    name: events
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: overlord-alpha
      name: alpha
    - encryptedVolume: true
      instanceGroup: overlord-beta
      name: beta
    - encryptedVolume: true
      instanceGroup: overlord-gamma
      name: gamma
    manager:
      env:
      - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
        value: 2d
      - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
        value: 7d
    memoryRequest: 100Mi
    name: cilium
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    nodeLocalDNS:
      enabled: true
    provider: CoreDNS
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 127.0.0.1/32
  kubernetesVersion: 1.20.7
  masterInternalName: api.internal.cluster.clusters.com
  masterPublicName: api.cluster.clusters.com
  metricsServer:
    enabled: true
  networkCIDR: 172.31.0.0/16
  networkID: vpc-ffffffff
  networking:
    cilium:
      clusterName: cluster.clusters.com
      enableNodePort: true
      enableRemoteNodeIdentity: false
      etcdManaged: true
      hubble:
        enabled: true
      preallocateBPFMaps: true
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 127.0.0.1/32
  subnets:
  - cidr: 172.22.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.22.32.0/19
    egress: nat-fffffff
    name: cluster-alpha
    type: Private
    zone: us-east-1a
  - cidr: 172.22.64.0/19
    egress: nat-fffffff
    name: cluster-beta
    type: Private
    zone: us-east-1a
  - cidr: 172.22.96.0/19
    egress: nat-fffffff
    name: cluster-gamma
    type: Private
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:09Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster.clusters.com
  name: ondemand-alpha
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5n.2xlarge
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: ondemand-alpha
    on-demand: "true"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster-alpha

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:09Z"
  labels:
    kops.k8s.io/cluster: cluster.clusters.com
  name: overlord-alpha
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: overlord-alpha
  role: Master
  rootVolumeSize: 16
  subnets:
  - cluster-alpha

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:10Z"
  labels:
    kops.k8s.io/cluster: cluster.clusters.com
  name: overlord-beta
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: overlord-beta
  role: Master
  rootVolumeSize: 16
  subnets:
  - cluster-beta

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:10Z"
  labels:
    kops.k8s.io/cluster: cluster.clusters.com
  name: overlord-gamma
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5a.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: overlord-gamma
  role: Master
  rootVolumeSize: 16
  subnets:
  - cluster-gamma

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:10Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster.clusters.com
  name: spots-alpha
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: c5n.2xlarge
  maxPrice: ".23"
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: spots-alpha
    on-demand: "false"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster-alpha

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:10Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster.clusters.com
  name: spots-beta
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: m5n.2xlarge
  maxPrice: ".30"
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: spots-beta
    on-demand: "false"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster-beta

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-06-14T18:47:10Z"
  labels:
    k8s.io/cluster-autoscaler/enabled: ""
    kops.k8s.io/cluster: cluster.clusters.com
  name: spots-gamma
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: r5n.2xlarge
  maxPrice: ".30"
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: spots-gamma
    on-demand: "false"
  role: Node
  rootVolumeSize: 32
  subnets:
  - cluster-gamma

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

There is an insane amount of opportunity for data leaks in this output. If this becomes absolutely necessary I will sanitize it carefully and put it up.

**9. Anything else do we need to know?**

This happened to me the other day when re-creating my development cluster. All I had to do to fix it in that instance was remove an API call from the additional policies that looks like it was just erroneous/non-existent to begin with. It was autoscaling:DescribeInstances. I figured that was it but after removing it from the prod clusters, the problem has not gone away. I'm aware that I could externalize this somehow, but I really prefer keeping it inside kops, since we use templating.
