### ISSUE TITLE
kops edit ig nodes-eu-west-1a results in SIGSEGV panic runtime error

### ISSUE THREAD

**Issue by tomekit** [kubernetes/kops#12557]
After saving any changes made by: `EDITOR=nano kops edit ig nodes-eu-west-1a` 

I get following error:
```
Using cluster from kubectl context: v7.k8s.local

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x394490d]

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup.PopulateInstanceGroupSpec(0xc0005f8000, 0xc00078c000, 0x7f4763b3e098, 0xc0007c4630, 0xc00026f080, 0x0, 0x0, 0x0)
	upup/pkg/fi/cloudup/populate_instancegroup_spec.go:164 +0x2ed
main.updateInstanceGroup(0x5572650, 0xc0000500b0, 0x55d4308, 0xc0007f1cf0, 0xc00026f080, 0xc0005f8000, 0xc000644000, 0xc00078c000, 0x0, 0xc00075f710, ...)
	cmd/kops/edit_instancegroup.go:291 +0xab
main.RunEditInstanceGroup(0x5572650, 0xc0000500b0, 0xc0002490b0, 0x551c7e0, 0xc00000e020, 0xc0005a1720, 0x0, 0x0)
	cmd/kops/edit_instancegroup.go:268 +0xfe8
main.NewCmdEditInstanceGroup.func2(0xc0007abb80, 0xc0007c0660, 0x1, 0x1, 0x0, 0x0)
	cmd/kops/edit_instancegroup.go:107 +0x5d
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc0007abb80, 0xc0007c0640, 0x1, 0x1, 0xc0007abb80, 0xc0007c0640)
	vendor/github.com/spf13/cobra/command.go:856 +0x472
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x78169e0, 0x7866630, 0x0, 0x0)
	vendor/github.com/spf13/cobra/command.go:974 +0x375
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:902
main.Execute()
	cmd/kops/root.go:95 +0x8f
main.main()
	cmd/kops/main.go:20 +0x25
```

`kops version`
Version 1.22.0 (git-8ba0d78c0be251c7dd5584d178c3e342037705df)

Contents of IG:
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-18T20:32:18Z"
  labels:
    kops.k8s.io/cluster: v7.k8s.local
  name: nodes-eu-west-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-1a
  role: Node
  subnets:
  - eu-west-1a
```

`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
