### ISSUE TITLE
Panic when creating instancegroup

### ISSUE THREAD

**Issue by tskiridomova** [kubernetes/kops#12572]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.22.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
➜  kops kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
```
AWS
```
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create ig --name=${NAME} ig1
```
**5. What happened after the commands executed?**

```
➜  kops kops create ig --name=${NAME} ig1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x704c7c4]

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup.PopulateInstanceGroupSpec(0xc000b14000, 0xc0007375e0, {0xebc4180, 0xc000a46fc0}, 0x0)
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/upup/pkg/fi/cloudup/populate_instancegroup_spec.go:164 +0x9e4
main.RunCreateInstanceGroup({0x8d0e938, 0xc000138008}, 0xc000a3fd98, {0x8c7e9a0, 0xc00013a008}, 0xc000ab4d90)
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/cmd/kops/create_instancegroup.go:196 +0x42e
main.NewCmdCreateInstanceGroup.func3(0xc000ad0500, {0xc000af4400, 0x1, 0x2})
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/cmd/kops/create_instancegroup.go:122 +0x37
github.com/spf13/cobra.(*Command).execute(0xc000ad0500, {0xc000af43e0, 0x2, 0x2})
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xb3a2b20)
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:902
main.Execute()
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/cmd/kops/root.go:95 +0x5c
main.main()
        /private/tmp/kops-20211014-96234-1h9vxo2/kops-1.22.0/src/k8s.io/kops/cmd/kops/main.go:20 +0x1
```

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-10-21T04:08:53Z"
  name: demo.kops.xxxxx.xxxxx
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://prop-kops-state-store/demo.kops.xxxxx.xxxxx
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.22.2
  masterPublicName: api.demo.kops.xxxxx.xxxxx
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 172.20.64.0/19
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 172.20.96.0/19
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-21T04:08:53Z"
  labels:
    kops.k8s.io/cluster: demo.kops.xxxxxx.xxxxxx
  name: master-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1a
  role: Master
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-21T04:08:54Z"
  labels:
    kops.k8s.io/cluster: demo.kops.xxxxxx.xxxxxx
  name: nodes-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1a
  role: Node
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-21T04:08:54Z"
  labels:
    kops.k8s.io/cluster: demo.kops.xxxxxx.xxxxxx
  name: nodes-ap-northeast-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.medium
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1c
  role: Node
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-10-21T04:08:55Z"
  labels:
    kops.k8s.io/cluster: demo.kops.xxxxxx.xxxxxx
  name: nodes-ap-northeast-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211001
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.medium
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-northeast-1d
  role: Node
  subnets:
  - ap-northeast-1d
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
