### ISSUE TITLE
kube-proxy & kube-controller-manager cluster-cidr is incorrectly populated (==serviceClusterIPRange instead of podCIDR)

### ISSUE THREAD

**Issue by dkulchinsky** [kubernetes/kops#12607]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.21.1` via https://github.com/eddycharly/terraform-provider-kops

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`1.21.5`

**3. What cloud provider are you using?**

`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

create a new cluster with the config as described below

**5. What happened after the commands executed?**

The cluster failed to initialize, upon closer inspection we identified that `calico-node` Pods are failing on startup because they can't reach `kubernetes.default`:
```
2021-10-22 19:36:18.707 [INFO][9] startup/startup.go 465: Hit error connecting to datastore - retry error=Get "https://172.19.128.1:443/api/v1/nodes/foo": dial tcp 172.19.128.1:443: i/o timeout
```

We've looked at `kube-proxy` and noticed that it was incorrectly configured, the `--cluster-cidr` flag value was set to `serviceClusterIPRange` instead of `podCIDR`.

our kops config yaml inputs:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-10-22T11:08:24Z"
  name: sbx-awsuse2.k8s.local
spec:
  DisableSubnetTags: true
  additionalPolicies: null
  api:
    loadBalancer:
      class: Classic
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
  cloudLabels: {...}
  cloudProvider: aws
  configBase: s3://{...}/sbx-awsuse2.k8s.local
  containerRuntime: containerd
  dnsZone: sbx-awsuse2.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: master-us-east-2a-0
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: master-us-east-2b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: master-us-east-2c-2
    memoryRequest: 150Mi
    name: events
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: master-us-east-2a-0
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: master-us-east-2b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: master-us-east-2c-2
    memoryRequest: 150Mi
    name: main
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    anonymousAuth: false
  kubeDNS:
    nodeLocalDNS:
      cpuRequest: 50m
      enabled: true
      memoryRequest: 150Mi
    provider: CoreDNS
  kubeProxy:
    enabled: true
    proxyMode: ipvs
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess: [...]
  kubernetesVersion: 1.21.5
  masterPublicName: api.sbx-awsuse2.k8s.local
  networkCIDR: {...}
  networkID: {...}
  networking:
    calico: {}
  nodeTerminationHandler:
    enableSQSTerminationDraining: true
    enableScheduledEventDraining: true
    enableSpotInterruptionDraining: true
    enabled: true
    managedASGTag: sbx-awsuse2-aws-node-termination-handler/managed
    prometheusEnable: true
  nonMasqueradeCIDR: 172.18.0.0/16
  podCIDR: 172.18.0.0/17
  serviceClusterIPRange: 172.18.128.0/17
  sshAccess: [...]
  sshKeyName: sbx-awsuse2
  subnets:
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-private-us-east-2a
    type: Private
    zone: us-east-2a
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-private-us-east-2b
    type: Private
    zone: us-east-2b
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-private-us-east-2c
    type: Private
    zone: us-east-2c
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-utility-us-east-2a
    type: Utility
    zone: us-east-2a
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-utility-us-east-2b
    type: Utility
    zone: us-east-2b
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-utility-us-east-2c
    type: Utility
    zone: us-east-2c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

**6. What did you expect to happen?**

`clusterCIDR` for `kubeProxy` & `kubeControllerManager` should be the value of `podCIDR` and not `serviceClusterIPRange`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
metadata:
  creationTimestamp: "2021-10-22T11:08:24Z"
  name: sbx-awsuse2.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      crossZoneLoadBalancing: false
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
      version: v1.0.0
    manageStorageClasses: true
  cloudLabels: {...}
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: s3://{...}/sbx-awsuse2.k8s.local
  configStore: s3://{...}/sbx-awsuse2.k8s.local
  containerRuntime: containerd
  containerd:
    configOverride: |
      version = 2

      [plugins]

        [plugins."io.containerd.grpc.v1.cri"]

          [plugins."io.containerd.grpc.v1.cri".containerd]

            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"

                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
    logLevel: info
    version: 1.4.9
  disableSubnetTags: true
  dnsZone: sbx-awsuse2.k8s.local
  docker:
    skipInstall: true
  etcdClusters:
  - backups:
      backupStore: s3://{...}/sbx-awsuse2.k8s.local/backups/etcd/events
    cpuRequest: 200m
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: master-us-east-2a-0
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: master-us-east-2b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: master-us-east-2c-2
    memoryRequest: 150Mi
    name: events
    provider: Manager
    version: 3.4.13
  - backups:
      backupStore: s3://{...}/sbx-awsuse2.k8s.local/backups/etcd/main
    cpuRequest: 200m
    enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: master-us-east-2a-0
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: master-us-east-2b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: master-us-east-2c-2
    memoryRequest: 150Mi
    name: main
    provider: Manager
    version: 3.4.13
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://{...}/sbx-awsuse2.k8s.local/pki
  kubeAPIServer:
    allowPrivileged: true
    anonymousAuth: false
    apiAudiences:
    - kubernetes.svc.default
    apiServerCount: 3
    authorizationMode: Node,RBAC
    bindAddress: 0.0.0.0
    cloudProvider: aws
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    etcdServers:
    - https://127.0.0.1:4001
    etcdServersOverrides:
    - /events#https://127.0.0.1:4002
    image: k8s.gcr.io/kube-apiserver:v1.21.5
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceAccountIssuer: https://api.internal.sbx-awsuse2.k8s.local
    serviceAccountJWKSURI: https://api.internal.sbx-awsuse2.k8s.local/openid/v1/jwks
    serviceClusterIPRange: 172.18.128.0/17
    storageBackend: etcd3
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 172.18.128.0/17 # <-- this is wrong! should be: 172.18.0.0/17 (==podCIDR)
    clusterName: sbx-awsuse2.k8s.local
    configureCloudRoutes: false
    featureGates:
      CSIMigrationAWS: "true"
    image: k8s.gcr.io/kube-controller-manager:v1.21.5
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    cacheMaxConcurrent: 150
    cacheMaxSize: 1000
    cpuRequest: 100m
    domain: cluster.local
    memoryLimit: 170Mi
    memoryRequest: 70Mi
    nodeLocalDNS:
      cpuRequest: 50m
      enabled: true
      forwardToKubeDNS: false
      localIP: 169.254.20.10
      memoryRequest: 150Mi
    provider: CoreDNS
    replicas: 2
    serverIP: 172.18.128.10
  kubeProxy:
    clusterCIDR: 172.18.128.0/17 # <-- This is wrong! should be: 172.18.0.0/17 (==podCIDR)
    cpuRequest: 100m
    enabled: true
    hostnameOverride: '@aws'
    image: k8s.gcr.io/kube-proxy:v1.21.5
    logLevel: 2
    proxyMode: ipvs
  kubeScheduler:
    image: k8s.gcr.io/kube-scheduler:v1.21.5
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    anonymousAuth: false
    cgroupDriver: systemd
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 169.254.20.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      CSIMigrationAWS: "true"
      CSIMigrationAWSComplete: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 172.18.0.0/16
    podManifestPath: /etc/kubernetes/manifests
  kubernetesApiAccess: [...]
  kubernetesVersion: 1.21.5
  masterInternalName: api.internal.sbx-awsuse2.k8s.local
  masterKubelet:
    anonymousAuth: false
    cgroupDriver: systemd
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 169.254.20.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      CSIMigrationAWS: "true"
      CSIMigrationAWSComplete: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 172.18.0.0/16
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
  masterPublicName: api.sbx-awsuse2.k8s.local
  networkCIDR: {...}
  networkID: {...}
  networking:
    calico:
      encapsulationMode: ipip
      ipipMode: Always
  nodeTerminationHandler:
    cpuRequest: 50m
    enableSQSTerminationDraining: true
    enableScheduledEventDraining: true
    enableSpotInterruptionDraining: true
    enabled: true
    managedASGTag: sbx-awsuse2-aws-node-termination-handler/managed
    memoryRequest: 64Mi
    prometheusEnable: true
  nonMasqueradeCIDR: 172.18.0.0/16
  podCIDR: 172.18.0.0/17
  secretStore: s3://{...}/sbx-awsuse2.k8s.local/secrets
  serviceClusterIPRange: 172.18.128.0/17
  sshAccess:
  - 10.254.254.0/28
  - 10.254.254.16/28
  - 10.254.254.32/28
  - 10.254.254.48/28
  - 10.254.254.64/28
  - 10.254.254.80/28
  sshKeyName: sbx-awsuse2
  subnets:
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-private-us-east-2a
    type: Private
    zone: us-east-2a
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-private-us-east-2b
    type: Private
    zone: us-east-2b
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-private-us-east-2c
    type: Private
    zone: us-east-2c
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-utility-us-east-2a
    type: Utility
    zone: us-east-2a
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-utility-us-east-2b
    type: Utility
    zone: us-east-2b
  - cidr: {...}
    id: {...}
    name: sbx-awsuse2-utility-us-east-2c
    type: Utility
    zone: us-east-2c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

We were able to fix this by explicitly setting `clusterCIDR` == `podCIDR` for `kubeProxy` and `kubeControllerManager`, but seems that when kops assigns these automatically it uses the value of `serviceClusterIPRange`
