### ISSUE TITLE
Master IAMRolePolicy too long with long cluster names.

### ISSUE THREAD

**Issue by BenWolstencroft** [kubernetes/kops#12606]
/kind bug

**1. What `kops` version are you running?**
1.21.2

**2. What Kubernetes version are you running?**
1.21.4

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster --yes

**5. What happened after the commands executed?**
IAMRolePolicy/_<redacted>_. Example error: error reading actual policy document: policy size was 11655. Policy cannot exceed 10240 bytes.

**6. What did you expect to happen?**
Update to succeed

**7. Please provide your cluster manifest.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-05-22T10:30:56Z"
  name: redacted
spec:
  api:
    dns: {}
    loadBalancer:
      class: Classic
      type: Internal
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    defaultIssuer: redacted
    enabled: true
  channel: stable
  cloudLabels:
    BudgetCode: Kube
    ProjectCode: Kube-Testing-Standalone-Cluster
  cloudProvider: aws
  clusterAutoscaler:
    balanceSimilarNodeGroups: false
    cpuRequest: 100m
    enabled: true
    expander: least-waste
    memoryRequest: 300Mi
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUtilizationThreshold: "0.5"
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  configBase: s3://redacted/redacted
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::redacted:policy/Kubernetes-Cluster-Systems-MasterNodePolicy-1DXUGOJ7A8T6E
    node:
    - arn:aws:iam::redacted:policy/Kubernetes-Cluster-Systems-NodePolicy-K9TNB85U5ELB
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: systems-kubernetes
    oidcGroupsClaim: groups
    oidcIssuerURL: https://redacted/
    oidcUsernameClaim: email
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 10.0.0.0/8
  kubernetesVersion: 1.21.4
  masterInternalName: api.internal.redacted
  masterPublicName: api.redacted
  metricsServer:
    enabled: true
  networkCIDR: 10.30.4.0/22
  networkID: redacted
  networking:
    calico:
      crossSubnet: true
  nodeTerminationHandler:
    enableSQSTerminationDraining: true
    enabled: true
    managedASGTag: aws-node-termination-handler/managed
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.0.0.0/8
  sshKeyName: redacted
  subnets:
  - cidr: 10.30.4.0/23
    egress: External
    id: redacted
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.30.6.0/23
    egress: External
    id: redacted
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**9. Anything else do we need to know?**

I believe that this is due to a combination of the number of addons we have enabled, and the length of the cluster name, the cluster name is included in many of the policies to limit the resources that the permissions are granted against.

We have an identical cluster with a shorter name (40 characters long) which works (vs 43 characters, which fails)

Maybe to prevent addons growing the base policy would be to separate policies for addons out onto their own policy?
