### ISSUE TITLE
kube-apiserver etcd-client certificate expired

### ISSUE THREAD

**Issue by 2sComplement** [kubernetes/kops#12620]
/kind bug

Summary: We lost access to our kube API due to an expired etcd-client certificate used by kube-apiserver. We were able to restore access by SSHing in to the master node and manually renewing the cert.  What is the correct way to ensure this manual step is not needed?

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.17.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.17.0 (client)
1.17.6 (server)

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
This might be a bit difficult to reproduce since the cert takes a year to expire. Once it does, the apiserver will be down. SSH into a master node, and run `openssl x509 -text -noout -in /etc/kubernetes/pki/kube-apiserver/etcd-client.crt`.

**5. What happened after the commands executed?**
The cert was expired.

**6. What did you expect to happen?**
The cert should be renewed before it expires.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 2
  name: cluster.hostname.com
spec:
  additionalPolicies: {}
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Product: Product
  cloudProvider: aws
  configBase: s3://state-bucket/cluster.hostname.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesVersion: 1.17.6
  masterPublicName: api.cluster.hostname.com
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.20.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-16T15:52:50Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster.hostname.com
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-16T15:52:50Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster.hostname.com
  name: nodes
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

**9. Anything else do we need to know?**
Not sure if this is related to #8959 but the `etcd-manager` certs have not yet expired. For some reason those are valid for 2 years.  Either way, I confirmed our `etdc-manager` image to be `kopeio/etcd-manager:3.0.20200527`, so I believe we should not be affected by that issue, as per [this advisory](https://github.com/kubernetes/kops/blob/master/docs/advisories/etcd-manager-certificate-expiration.md).
