### ISSUE TITLE
Unable to create new loadbalancers in AWS

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#12671]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.23.0-alpha.2 (git-3a97dbaa8d754d6f3318890c3e9159bd5ea1282c)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster --name teestiing.k8s.local --zones eu-north-1a,eu-north-1b,eu-north-1c --master-count=3 --node-count=1 --node-size t3.small --master-size t3.small
kops update cluster teestiing.k8s.local --yes --admin=87600h
```

Then created 2 loadbalancers with proxy protocol and without:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  labels:
    app.kubernetes.io/name: nginx
  name: nginx-proxy
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: nginx
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: nginx
  type: LoadBalancer
```

**5. What happened after the commands executed?**

in loadbalancer that requested proxy protocol I can see following error in events:

```
  Warning  SyncLoadBalancerFailed   3s                 service-controller  Error syncing load balancer: failed to ensure load balancer: error creating proxy protocol policy on load balancer: "AccessDenied: User: arn:aws:sts::xxx:assumed-role/masters.teestiing.k8s.local/i-08b84e7a850dc4b2c is not authorized to perform: elasticloadbalancing:CreateLoadBalancerPolicy on resource: arn:aws:elasticloadbalancing:eu-north-1:xxx:loadbalancer/aab33a602fbeb460883035c4e3900058 because no identity-based policy allows the elasticloadbalancing:CreateLoadBalancerPolicy action\n\tstatus code: 403, request id: d6ca755e-abf1-4868-9c11-3f56898cfbae"
```

loadbalancer without proxy protocol:

```
  Warning  SyncLoadBalancerFailed   18s                service-controller  Error syncing load balancer: failed to ensure load balancer: Unable to update load balancer attributes during attribute sync: "AccessDenied: User: arn:aws:sts::xxxx:assumed-role/masters.teestiing.k8s.local/i-08b84e7a850dc4b2c is not authorized to perform: elasticloadbalancing:ModifyLoadBalancerAttributes on resource: arn:aws:elasticloadbalancing:eu-north-1:xxx:loadbalancer/a1c7da055fd134b7fba7770940a087c4 because no identity-based policy allows the elasticloadbalancing:ModifyLoadBalancerAttributes action\n\tstatus code: 403, request id: 03a6bc17-ad98-4e40-bc16-1507a1e88ef1"
```

**6. What did you expect to happen?**

I expect that we could create service type: loadbalancer in kubernetes clusters

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
