### ISSUE TITLE
kops export --admin set apiserver with port 8443 as endpoint

### ISSUE THREAD

**Issue by SCLogo** [kubernetes/kops#12695]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.22.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.22.3
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
to create cluster:
`kops create cluster {{ domain }} --encrypt-etcd-storage --container-runtime containerd --dns private --master-count {{ master_count }} --node-count 1 --kubernetes-version {{ tag_k8s_version }} --zones {{ create_zone }} --node-size {{ kops_node_instance_type }} --master-size {{ kops_master_instance_type }} --master-zones {{ create_zone }} --networking calico --topology private --cloud-labels {{ kops_cloud_labels }} --vpc {{ vpc_id.vpcs[0].vpc_id }} --subnets {{ node_subnets }} --utility-subnets {{ utility_subnets }} --ssh-public-key ~/.ssh/aws/{{ private_key_name }}.pub --api-loadbalancer-type internal --api-loadbalancer-class network --api-ssl-certificate {{ cert_arn }} --cloud aws --state {{ kops_state }} {{ generated_admin_api_access_list }} {{ generated_admin_ssh_access_list }}`
then export config

`kops export kubecfg k8s-cluster.config.mycluster.com --admin --state s3://s3-bucket`

**5. What happened after the commands executed?**

`The connection to the server api.k8s-cluster.config.mycluster.com:8443 was refused - did you specify the right host or port?`

**6. What did you expect to happen?**

able to access cluster 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-11-08T11:45:51Z"
  name: k8s-cluster.control.mycluster.com
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "kms:Decrypt",
            "kms:Encrypt"
          ],
          "Resource": [
            "arn:aws:kms:region:id:key/key-id"
          ]
        }
      ]
  api:
    loadBalancer:
      class: Network
      sslCertificate: arn:aws:acm:region:userid:certificate/cert-id
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Owner: cluster-owner
    delete: ""
    kops: k8s-cluster.control.mycluster.com
  cloudProvider: aws
  configBase: s3://s3-bucket/k8s-cluster.control.mycluster.com
  containerRuntime: containerd
  encryptionConfig: true
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-region-a
      kmsKeyId: arn:aws:kms:region:userid:key/kmskeyid
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-region-a
      kmsKeyId: arn:aws:kms:region:userid:key/kmskeyid
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    legacy: false
  kubeAPIServer:
    admissionControlConfigFile: /srv/kubernetes/admission-configuration.yaml
    appendAdmissionPlugins:
    - EventRateLimit
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/apiserver/audit.log
    auditPolicyFile: /srv/kubernetes/audit/policy-config.yaml
    auditWebhookBatchMaxWait: 5s
    auditWebhookConfigFile: /srv/kubernetes/audit/webhook-config.yaml
    authorizationMode: Node,RBAC
    disableBasicAuth: false
    enableProfiling: false
    requestTimeout: 3m0s
  kubeControllerManager:
    enableProfiling: false
    featureGates:
      RotateKubeletServerCertificate: "true"
    terminatedPodGCThreshold: 10
  kubeScheduler:
    enableProfiling: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    eventQPS: 0
    featureGates:
      RotateKubeletServerCertificate: "true"
    protectKernelDefaults: true
    readOnlyPort: 0
  kubernetesApiAccess:
  - 192.168.0.1/24
  kubernetesVersion: v1.22.3
  masterPublicName: api.k8s-cluster.control.mycluster.com
  networkCIDR: network_cidr
  networkID: vpc-0bd0f75d5f95e3e56
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 192.168.0.1/24
  subnets:
  - cidr: subnets/24
    id: subnet-id
    name: regiona
    type: Private
    zone: regiona
  - cidr: subnets/24
    id: subnet-id
    name: utility-regiona
    type: Utility
    zone: regiona
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-11-08T11:45:52Z"
  labels:
    kops.k8s.io/cluster: k8s-cluster.control.mycluster.com
  name: master-regiona
spec:
  compressUserData: true
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-regiona
  role: Master
  subnets:
  - regiona
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s-cluster.control.mycluster.com
  name: spot-fleet-computing-regiona
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "yes"
    k8s.io/cluster/k8s-cluster.control.mycluster.com: "yes"
  compressUserData: true
  iam:
    profile: arn:aws:iam::userid:instance-profile/k8s-cluster-control-mycluster-com-region.nr
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: instance_type
  maxPrice: "0.07680000000000001"
  maxSize: 20
  minSize: 0
  mixedInstancesPolicy:
    instances:
    - typea
    - typeb
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    cluster.instance.type: computing
    cluster.name: spot-fleet-computing-regiona
    cluster.node.type: spot
    kops.k8s.io/instancegroup: spot-fleet-regiona
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  rootVolumeSize: 32
  rootVolumeType: gp2
  subnets:
  - regiona
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /var/log
  volumes:
  - device: /dev/sdl
    encrypted: true
    size: 10
    type: gp2
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    cluster.instance.type: general
    kops.k8s.io/cluster: k8s-cluster.control.mycluster.com
  name: spot-fleet-general-regiona
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "yes"
    k8s.io/cluster/k8s-cluster.control.mycluster.com: "yes"
  compressUserData: true
  iam:
    profile: arn:aws:iam::userid:instance-profile/k8s-cluster-control-mycluster-com-region.nr
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: typea
  maxPrice: "0.07680000000000001"
  maxSize: 20
  minSize: 4
  mixedInstancesPolicy:
    instances:
    - typea
    - typeb
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    cluster.instance.type: general
    cluster.name: spot-fleet-general-regiona
    cluster.node.type: spot
    kops.k8s.io/instancegroup: spot-fleet-regiona
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  rootVolumeSize: 32
  rootVolumeType: gp2
  subnets:
  - regiona
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /var/log
  volumes:
  - device: /dev/sdl
    encrypted: true
    size: 10
    type: gp2
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s-cluster.control.mycluster.com
  name: spot-fleet-job-regiona
spec:
  additionalUserData:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "yes"
    k8s.io/cluster/k8s-cluster.control.mycluster.com: "yes"
  compressUserData: true
  iam:
    profile: arn:aws:iam::userid:instance-profile/k8s-cluster-control-mycluster-com-region.nr
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: typea
  maxPrice: "0.40"
  maxSize: 2
  minSize: 0
  mixedInstancesPolicy:
    instances:
    - typea
    - typeb
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    cluster.instance.type: job
    cluster.name: spot-fleet-job-regiona
    cluster.node.env: devtenant
    cluster.node.type: spot
    kops.k8s.io/instancegroup: spot-fleet-regiona
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  subnets:
  - regiona
  taints:
  - dedicated=job:NoSchedule
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /var/log
  volumes:
  - device: /dev/sdl
    encrypted: true
    size: 10
    type: gp2
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
