### ISSUE TITLE
kops error message: error listing SQS queues

### ISSUE THREAD

**Issue by github-reader** [kubernetes/kops#12693]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.21.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.5

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete cluster -y

**5. What happened after the commands executed?**
Following message was printed on screen:
error listing SQS queues: AccessDenied: Access to the resource https://sqs.ap-southeast-1.amazonaws.com/ is denied.
	status code: 403, request id: <AWS request id removed for security reasons>

**6. What did you expect to happen?**
This message does not appear. No SQS queue exists in our account. Kops also did not create one. I have checked AWS for existence of SQS queues.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: <cluster name>
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Resource": [ "*" ],
          "Action": [
            "ecr:DescribeImages",
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup"
          ]
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    zone: <dns zone>
  cloudProvider: aws
  configBase: s3://<vucket name>/<prefix>
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-1c
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-1c
      name: c
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    node:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  iam:
    allowContainerRegistry: true
    legacy: false
    serviceAccountExternalPermissions:
    - aws:
        policyARNs:
        - arn:aws:iam::<aws account id>:policy/cl1-cluster-autoscaler-policy
      name: cluster-autoscaler
      namespace: <namespace>
    - aws:
        policyARNs:
        - arn:aws:iam::<aws account id>:policy/cl-int-velero-policy
      name: velero
      namespace: <namespace>
    - aws:
        policyARNs:
        - arn:aws:iam::<aws account id>:policy/cl1-cert-manager-policy
      name: cert-manager
      namespace: <namespace>
    - aws:
        policyARNs:
        - arn:aws:iam::<aws account id>:policy/cl1-external-dns-policy
      name: external-dns
      namespace: <namespace>
    - aws:
        policyARNs:
        - arn:aws:iam::<aws account id>:policy/cl-jenkins-slave-policy
      name: jenkins-slave
      namespace: jenkins
  kubeAPIServer:
    oidcClientID: <client id>
    oidcGroupsClaim: <oidc group url>
    oidcIssuerURL: <oidc group url>
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    evictionHard: memory.available<2000Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    resolvConf: /run/systemd/resolve/resolv.conf
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.5
  masterPublicName: master-1.webapps.audi.io
  networkCIDR: 10.3.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  ntp:
    managed: false
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://<bucket name 2>
    enableAWSOIDCProvider: true
  subnets:
  - cidr: 10.3.4.0/24
    name: az-1a
    type: Private
    zone: az-1a
  - cidr: 10.3.5.0/24
    name: az-1b
    type: Private
    zone: az-1b
  - cidr: 10.3.6.0/24
    name: az-1c
    type: Private
    zone: az-1c
  - cidr: 10.3.1.0/24
    name: utility-az-1a
    type: Utility
    zone: az-1a
  - cidr: 10.3.2.0/24
    name: utility-az-1b
    type: Utility
    zone: az-1b
  - cidr: 10.3.3.0/24
    name: utility-az-1c
    type: Utility
    zone: az-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I1108 07:20:29.551399   27720 factory.go:68] state store s3://cocos-ap-int-state-store
I1108 07:20:29.555010   27720 s3context.go:328] unable to read /sys/devices/virtual/dmi/id/product_uuid, assuming not running on EC2: open /sys/devices/virtual/dmi/id/product_uuid: permission denied
I1108 07:20:29.559893   27720 s3context.go:166] got region from metadata: "ap-southeast-1"
I1108 07:20:29.776739   27720 s3context.go:213] found bucket in region "ap-southeast-1"
I1108 07:20:29.777704   27720 s3fs.go:291] Reading file "s3://cocos-ap-int-state-store/cocos-ap-int1.webapps.audi.io/config"
I1108 07:20:29.943247   27720 aws_cloud.go:1551] Querying EC2 for all valid zones in region "ap-southeast-1"
I1108 07:20:29.946936   27720 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I1108 07:20:29.997642   27720 aws_cloud.go:629] Listing all Autoscaling groups matching cluster tags
I1108 07:20:29.998901   27720 request_logger.go:45] AWS request: autoscaling/DescribeTags
I1108 07:20:30.116581   27720 aws.go:405] Querying EC2 instances
I1108 07:20:30.117033   27720 request_logger.go:45] AWS request: ec2/DescribeInstances
I1108 07:20:30.153623   27720 aws.go:719] Listing EC2 Keypairs
I1108 07:20:30.154812   27720 request_logger.go:45] AWS request: ec2/DescribeKeyPairs
I1108 07:20:30.193107   27720 securitygroup.go:129] Listing EC2 SecurityGroups
I1108 07:20:30.195668   27720 request_logger.go:45] AWS request: ec2/DescribeSecurityGroups
I1108 07:20:30.232408   27720 request_logger.go:45] AWS request: ec2/DescribeSecurityGroups
I1108 07:20:30.270718   27720 aws.go:677] Listing EC2 Volumes
I1108 07:20:30.272790   27720 request_logger.go:45] AWS request: ec2/DescribeVolumes
I1108 07:20:30.318874   27720 aws.go:996] Listing EC2 DhcpOptions
I1108 07:20:30.320393   27720 request_logger.go:45] AWS request: ec2/DescribeDhcpOptions
I1108 07:20:30.346506   27720 aws.go:1106] Listing EC2 InternetGateways
I1108 07:20:30.347319   27720 request_logger.go:45] AWS request: ec2/DescribeInternetGateways
I1108 07:20:30.384099   27720 routetable.go:36] Listing EC2 RouteTables
I1108 07:20:30.384330   27720 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I1108 07:20:30.422126   27720 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I1108 07:20:30.457873   27720 aws.go:894] Listing EC2 subnets
I1108 07:20:30.458134   27720 request_logger.go:45] AWS request: ec2/DescribeSubnets
I1108 07:20:30.500864   27720 request_logger.go:45] AWS request: ec2/DescribeRouteTables
I1108 07:20:30.553666   27720 aws.go:869] Querying Nat Gateways
I1108 07:20:30.554089   27720 request_logger.go:45] AWS request: ec2/DescribeNatGateways
I1108 07:20:30.625724   27720 vpc.go:75] Listing EC2 VPC
I1108 07:20:30.627292   27720 request_logger.go:45] AWS request: ec2/DescribeVpcs
I1108 07:20:30.657650   27720 request_logger.go:45] AWS request: ec2/DescribeVpcs
I1108 07:20:30.691001   27720 aws.go:1457] Listing all ELBs
I1108 07:20:30.692131   27720 request_logger.go:45] AWS request: elasticloadbalancing/DescribeLoadBalancers
I1108 07:20:30.811766   27720 request_logger.go:45] AWS request: elasticloadbalancing/DescribeTags
I1108 07:20:30.834115   27720 aws.go:1550] Listing all NLBs and ALBs
I1108 07:20:30.835934   27720 request_logger.go:45] AWS request: elasticloadbalancing/DescribeLoadBalancers
I1108 07:20:30.867748   27720 request_logger.go:45] AWS request: elasticloadbalancing/DescribeTags
I1108 07:20:30.895366   27720 aws.go:1632] Listing all TargetGroups
I1108 07:20:30.895769   27720 request_logger.go:45] AWS request: elasticloadbalancing/DescribeTargetGroups
I1108 07:20:30.926351   27720 request_logger.go:45] AWS request: elasticloadbalancing/DescribeTags
I1108 07:20:30.972942   27720 aws.go:1773] Querying for all route53 zones
I1108 07:20:30.974625   27720 request_logger.go:45] AWS request: route53/ListHostedZones
I1108 07:20:32.037314   27720 aws.go:1798] Querying for records in zone: "cocos-ap-int1.webapps.audi.io."
I1108 07:20:32.038439   27720 request_logger.go:45] AWS request: route53/ListResourceRecordSets
I1108 07:20:32.395126   27720 request_logger.go:45] AWS request: iam/ListInstanceProfiles
I1108 07:20:33.274917   27720 request_logger.go:45] AWS request: iam/ListRoles
I1108 07:20:33.644040   27720 request_logger.go:45] AWS request: iam/GetRole
I1108 07:20:33.888383   27720 request_logger.go:45] AWS request: iam/GetRole
I1108 07:20:34.134457   27720 request_logger.go:45] AWS request: iam/ListRoles
I1108 07:20:34.441541   27720 request_logger.go:45] AWS request: iam/GetRole
I1108 07:20:34.682599   27720 request_logger.go:45] AWS request: iam/GetRole
I1108 07:20:34.925712   27720 request_logger.go:45] AWS request: iam/GetRole
I1108 07:20:35.184326   27720 request_logger.go:45] AWS request: iam/GetRole
I1108 07:20:35.463072   27720 request_logger.go:45] AWS request: iam/ListOpenIDConnectProviders
I1108 07:20:35.687853   27720 request_logger.go:45] AWS request: iam/GetOpenIDConnectProvider
I1108 07:20:35.930169   27720 request_logger.go:45] AWS request: iam/GetOpenIDConnectProvider
I1108 07:20:36.181407   27720 request_logger.go:45] AWS request: iam/GetOpenIDConnectProvider
I1108 07:20:36.426412   27720 request_logger.go:45] AWS request: iam/GetOpenIDConnectProvider
I1108 07:20:36.668872   27720 request_logger.go:45] AWS request: iam/GetOpenIDConnectProvider
I1108 07:20:36.909556   27720 sqs.go:60] Listing SQS queues
I1108 07:20:36.912094   27720 request_logger.go:45] AWS request: sqs/ListQueues

error listing SQS queues: AccessDenied: Access to the resource https://sqs.ap-southeast-1.amazonaws.com/ is denied.
	status code: 403, request id: <AWS request id removed for security reasons>

**9. Anything else do we need to know?**
Please send information when you need additional data.
