### ISSUE TITLE
Cilium-NodeUp-Error: failed to create cgroupv2 mount unit

### ISSUE THREAD

**Issue by florianstoeber** [kubernetes/kops#12707]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.22.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.20.11

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops update cluster <cluster name> --yes --admin=87600h --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges
kops rolling-update cluster --cloudonly --master-interval=5m --node-interval=3m --yes
```
**5. What happened after the commands executed?**
The master nodes are updated and joining the cluster (they are working), the worker nodes are not joining the cluster as they are failing while nodeup phase:
```
journalctl -u kops-configuration -r
Nov 10 10:21:53 <ip> nodeup[4614]: W1110 10:21:53.905739    4614 main.go:133] got error running nodeup (will retry in 30s): error building loader: building *networking.CiliumBuilder: failed to create cgroupv2 mount unit: error checking for /run/cilium/cgroupv2: <nil>

systemctl | grep cilium
  run-cilium-cgroupv2.mount                                               loaded active     mounted         Cilium Cgroup2 mounts

journalctl -u run-cilium-cgroupv2.mount
-- Logs begin at Tue 2021-11-09 10:20:30 UTC, end at Wed 2021-11-10 10:06:12 UTC. --
Nov 09 10:21:37 <customer-ip> systemd[1]: Mounting Cilium Cgroup2 mounts...
Nov 09 10:21:37 <customer-ip> systemd[1]: Mounted Cilium Cgroup2 mounts.

ls /run/cilium/cgroupv2
cgroup.controllers  cgroup.max.depth  cgroup.max.descendants  cgroup.procs  cgroup.stat  cgroup.subtree_control  cgroup.threads  cpu.pressure  cpu.stat  init.scope  io.pressure  memory.pressure  system.slice  user.slice
```
**6. What did you expect to happen?**
The worker nodes nodeup phase should succeed as the cgroup-mount was okay (I think?). 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: "clustername"
spec:
  assets:
    containerRegistry: "ECR-REPO-LINK"
  fileAssets:
  - name: admissionConfig
    path: /srv/kubernetes/kube-apiserver/admission-config.yaml
    roles:
    - Master
    content: |
      apiVersion: apiserver.k8s.io/v1alpha1
      kind: AdmissionConfiguration
      plugins:
      - name: EventRateLimit
        path: /srv/kubernetes/kube-apiserver/eventconfig.yaml
  - name: eventConfig
    path: /srv/kubernetes/kube-apiserver/eventconfig.yaml
    roles:
    - Master
    content: |
      apiVersion: eventratelimit.admission.k8s.io/v1alpha1
      kind: Configuration
      limits:
      - type: Server
        qps: 100
        burst: 200
  - name: kubeletConfig
    path: /etc/sysctl.d/90-kubelet.conf
    content: |
      vm.overcommit_memory=1
      kernel.panic=10
      kernel.panic_on_oops=1
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  containerRuntime: containerd
  containerd:
    logLevel: info
    registryMirrors:
      docker.io:
      - https://registry-1.docker.io
      gcr.io:
      - https://gcr.io/v2
      us.gcr.io:
      - https://us.gcr.io/v2
      k8s.gcr.io:
      - https://k8s.gcr.io/v2
      quay.io:
      - https://quay.io/v2
      "*":
      - "ecrLink"
  podCIDR: "172.16.0.0/12"
  certManager:
    enabled: true
    managed: false
  docker:
    logOpt:
      - max-size=200m
  kubeDNS:
    provider: CoreDNS
    coreDNSImage: "coredns/coredns:1.8.3"
  kubeAPIServer:
    enableProfiling: false
    disableBasicAuth: true
    authorizationMode: RBAC,Node
    appendAdmissionPlugins:
      - AlwaysPullImages
      - EventRateLimit
    admissionControlConfigFile: /srv/kubernetes/kube-apiserver/admission-config.yaml
    oidcIssuerURL: "oidcIssuerURL"
    oidcClientID: "oidcClientID"
    oidcUsernameClaim: "preferred_username"
    oidcUsernamePrefix: "oidc:"
    oidcGroupsClaim: "groups"
    oidcGroupsPrefix: "oidc:"
    auditLogPath: /var/log/apiserver/audit.log
    auditLogFormat: json
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    tlsCipherSuites:
      - "tls-ciphers"
    featureGates:
      TTLAfterFinished: "true"
      EphemeralContainers: "true"
  iam:
    legacy: false
    allowContainerRegistry: true
  encryptionConfig: true
  etcdClusters:
  - etcdMembers:
    - instanceGroup: 10a-application-master
      name: a
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    - instanceGroup: 10b-application-master
      name: b
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    - instanceGroup: 10c-application-master
      name: c
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    name: main
    image: "gcr.io/etcd-development/etcd:v3.3.13"
    enableEtcdTLS: true
    enableTLSAuth: true
    provider: Manager
    version: "3.3.13"
  - etcdMembers:
    - instanceGroup: 10a-application-master
      name: a
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    - instanceGroup: 10b-application-master
      name: b
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    - instanceGroup: 10c-application-master
      name: c
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    name: events
    image: "gcr.io/etcd-development/etcd:v3.3.13"
    enableEtcdTLS: true
    enableTLSAuth: true
    provider: Manager
    version: "3.3.13"
  - etcdMembers:
    - instanceGroup: 10a-application-master
      name: a
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    - instanceGroup: 10b-application-master
      name: b
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    - instanceGroup: 10c-application-master
      name: c
      volumeType: io1
      volumeIops: 900
      volumeSize: 20
      encryptedVolume: true
    manager:
      env:
      - name: ETCD_AUTO_COMPACTION_MODE
        value: revision
      - name: ETCD_AUTO_COMPACTION_RETENTION
        value: "2500"
    name: cilium
    image: "gcr.io/etcd-development/etcd:v3.3.13"
    enableEtcdTLS: true
    enableTLSAuth: true
    provider: Manager
    version: "3.3.13"
  kubernetesApiAccess:
    - "internal-cidr"
  kubernetesVersion: "1.20.11"
  networkID: "vpc-id"
  networkCIDR: "networkcidr"
  networking:
    cilium:
      etcdManaged: true
      enableEncryption: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - "internalcidr"
  subnets:
  - id: 'subnet-id'
    name: 00a-entry
    type: Utility
    zone: eu-west-1a
  - id: 'subnet-id'
    name: 00b-entry
    type: Utility
    zone: eu-west-1b
  - id: 'subnet-id'
    name: 00c-entry
    type: Utility
    zone: eu-west-1c
  - id: 'subnet-id'
    name: 10a-application
    type: Private
    zone: eu-west-1a
  - id: 'subnet-id'
    name: 10b-application
    type: Private
    zone: eu-west-1b
  - id: 'subnet-id'
    name: 10c-application
    type: Private
    zone: eu-west-1c    
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
  kubeScheduler:
    enableProfiling: false
    featureGates:
      EphemeralContainers: "true"
  kubeControllerManager:
    enableProfiling: false
    featureGates:
      EphemeralContainers: "true"
    clusterCIDR: 100.96.0.0/11
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    readOnlyPort: 0
    protectKernelDefaults: true
    streamingConnectionIdleTimeout: "30m"
    eventQps: "0"
    featureGates:
      RotateKubeletServerCertificate: "true"
      TTLAfterFinished: "true"
      EphemeralContainers: "true"
    kubeReserved:
        cpu: "100m"
        memory: "100Mi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "100m"
        memory: "100Mi"
    systemReservedCgroup: "/system-reserved"
    tlsCipherSuites:
      - "variousciphers"
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
I don´t think that this is helpful, as the kops-commands are succeeding. If it is necessary please reach out. I am glad to help.

**9. Anything else do we need to know?**
I tried to do this with a custom AMI and the official Ubuntu AMI: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211021

Link to the discussion on Slack: https://kubernetes.slack.com/archives/C3QUFP0QM/p1636392729184400
