### ISSUE TITLE
Canal CNI not allowed with kOps 1.22.1

### ISSUE THREAD

**Issue by kforsthoevel** [kubernetes/kops#12745]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.22.1 (git-da710c931fbfe0fc8fe7bb3e2d41ba6e09c899f9)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.22.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops create -f cluster.yaml`

From cluster.yaml

```
...
networking:
  canal: {}
...
```

**5. What happened after the commands executed?**

Error: error creating cluster: spec.networking.canal: Forbidden: Canal is supported only for Kubernetes 1.21 and lower

**6. What did you expect to happen?**

Cluster should be created using Canal as CNI.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
---
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: staging.XXX
spec:
  api:
    loadBalancer:
      class: Classic
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Environment: staging
  cloudProvider: aws
  configBase: s3://XXX/staging.XXX
  containerRuntime: containerd
  clusterAutoscaler:
    enabled: true
    balanceSimilarNodeGroups: true
    scaleDownUtilizationThreshold: "0.8"
    skipNodesWithLocalStorage: false
    cpuRequest: "100m"
    memoryRequest: "800Mi"
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    node:
    - arn:aws:iam::XXX
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    featureGates:
      TTLAfterFinished: "true"
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubeDNS:
    nodeLocalDNS:
      enabled: false
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cpuCFSQuota: false
  kubernetesApiAccess:
  - xxx
  kubernetesVersion: 1.22.3
  masterInternalName: api.internal.staging.XXX
  masterPublicName: api.staging.XXX
  networkCIDR: 172.XXX/16
  networkID: vpc-XXX
  networking:
    canal: {}
  nodeTerminationHandler:
    enabled: true
    enableSQSTerminationDraining: true
    managedASGTag: kubernetes.io/cluster/staging.XXX
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 172.XXX/22
  subnets:
    - XXX
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: staging.XXX
  name: master-eu-west-1a
spec:
  additionalSecurityGroups: [sg-XXX]
  cloudLabels:
    Environment: staging
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: XXX
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: staging.XXX
  name: master-eu-west-1b
spec:
  additionalSecurityGroups: [sg-XXX]
  cloudLabels:
    Environment: staging
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: XXX
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: staging.XXX
  name: master-eu-west-1c
spec:
  additionalSecurityGroups: [sg-XXX]
  cloudLabels:
    Environment: staging
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: XXX
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
  - eu-west-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: staging.XXX
  name: nodes-eu-west-1a
spec:
  additionalSecurityGroups: [sg-XXX]
  cloudLabels:
    Environment: staging
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/staging: ""
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: XXX
  maxSize: 18
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-1a
    type: node
  role: Node
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: staging.XXX
  name: nodes-eu-west-1b
spec:
  additionalSecurityGroups: [sg-XXX]
  cloudLabels:
    Environment: staging
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/staging: ""
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: XXX
  maxSize: 18
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-1b
    type: node
  role: Node
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: staging.XXX
  name: nodes-eu-west-1c
spec:
  additionalSecurityGroups: [sg-XXX]
  cloudLabels:
    Environment: staging
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/staging: ""
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211015
  machineType: XXX
  maxSize: 18
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-west-1c
    type: node
  role: Node
  subnets:
  - eu-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Looks like support for canal has been re-enabled with kOps version `v1.23.0-alpha.2` (Upgrade Canal to v3.20 with k8s 1.22 support @rifelpet #12584), but the change never made it to kOps 1.22. I would expect to include the change for kOps 1.22 as well.
