### ISSUE TITLE
[Feature] Use Existing NAT Gateways in Shared VPC

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#1282]
**Summary:** 
When spinning up a new cluster in a Shared VPC and specifying existing subnets to use, `kops` should allow some notion of a "shared" or "existing" NAT Gateway (NGW) similar to how we can specify subnet or VPC ids to reuse. This issue extends and clarifies #1147. My use-case below assumes `private` topology. I believe this feature should only apply when using existing public subnets.  

I think there are a few potential ways to approach this- 
1. Specifying the NGW to use for each private subnet
2. Perhaps `kops` could check for the existence of NGWs in the public subnets when they are shared? 
3. Tagging the NGW in some way so that `kops` can pair up public/private subnets with an acceptable gateway

**Setup:**
My `kops` configuration looks like this: 
```
kops create cluster \
  --cloud aws \
  --topology private \
  --networking cni \
  --state $KOPS_STATE_STORE \
  --node-count $NODE_COUNT \
  --zones $ZONES \
  --master-zones $MASTER_ZONES \
  --dns-zone $DNS_ZONE \
  --node-size $NODE_SIZE \
  --master-size $MASTER_SIZE \
  -v $V_LOG_LEVEL \
  --ssh-public-key $SSH_KEY_PATH \
  --vpc $VPC_ID \
  --network-cidr $NETWORK_CIDR \
  --name $CLUSTER_NAME \
  --bastion=true \
  --kubernetes-version=1.4.7
```

I then specify subnets like so: 
```
subnets:
  - cidr: 172.20.120.0/21
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.128.0/21
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.136.0/21
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.20.32.0/21
    id: subnet-ca111111
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.40.0/21
    id: subnet-10e222222
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.20.48.0/21
    id: subnet-26333333
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
```

**Result:** 
Everything "works", the cluster initializes and `kops` creates three new private Kubernetes-only subnets, and puts my public-facing resources in the "utility" subnets. Great! It also creates 3 new NGWs and EIPs. However, my base VPC already has NGWs for each of the utility subnets that I specified in my cluster spec. So now I have two NGWs for each AZ when I think 1 should be sufficient.  

I am testing and thinking about this in the context of `kops Version git-5850d27` which is PR #1275.
