### ISSUE TITLE
KCM unable to create load balancer

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#12905]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.23.0-alpha.2 (git-v1.23.0-alpha.2999-204-g0775a4ee20)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.22.4

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create an IPv6 cluster with AWS CCM but without either AWS LBC or IRSA. 

Create a service:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test-service.REDACTED
  name: test-service
  namespace: kube-system
spec:
  type: LoadBalancer
  clusterIP: "fd00:5e4f:ce::22"
  clusterIPs:
  - "fd00:5e4f:ce::22"
  ports:
  - port: 99
```

**5. What happened after the commands executed?**

Loadbalancer is not created.

KCM logs:

```
I1207 06:37:43.869664       1 event.go:291] "Event occurred" object="kube-system/test-service" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: Unable to update load balancer attributes during attribute sync: \"AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/masters.k8s.REDACTED/i-02e2ebab48b7b424f is not authorized to perform: elasticloadbalancing:ModifyLoadBalancerAttributes on resource: arn:aws:elasticloadbalancing:us-east-1:REDACTED:loadbalancer/REDACTED because no identity-based policy allows the elasticloadbalancing:ModifyLoadBalancerAttributes action\\n\\tstatus code: 403, request id: 4f2c5186-66bb-4d3d-9f03-ebd70e81a8a0\""
```

**6. What did you expect to happen?**

Create load balancer

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.REDACTED
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudControllerManager: {}
  cloudLabels:
    REDACTED
  cloudProvider: aws
  configBase: s3://REDACTED
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    nodeLocalDNS:
      enabled: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - REDACTED
  kubernetesVersion: 1.22.4
  masterPublicName: api.k8s.REDACTED
  networkCIDR: 172.20.0.0/16
  networkID: vpc-REDACTED
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: ::/0
  sshAccess:
  - REDACTED
  subnets:
  - cidr: 172.20.32.0/19
    ipv6CIDR: /64#0
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

/cc @olemarkus
