### ISSUE TITLE
Pod may be scheduled on Nodes it will have anti-affinity on

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#12948]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.23.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.23.0

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create a cluster with an IG that has `nodeLabels: [foo: bar]`
Create a Pod (e.g through a DaemonSet) with the following:
```
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: foo
            operator: NotIn
            values:
            - bar
```
Note the `NotIn` operator being used

**5. What happened after the commands executed?**

Pod gets scheduled on the Node because kops-controller does not apply the label fast enough.
Note this is hard race as CCM and others also do initialization that blocks scheduling giving kops-controller enough time to label.
But it may still happen.

**6. What did you expect to happen?**

Pod should not get scheduled on Nodes it was not intended to run on.

**9. Anything else do we need to know?**

The way CCM goes about this is to add the taint `node.cloudprovider.kubernetes.io/uninitialized` that is removed after labelling.
I am wondering if we should do the same.
