### ISSUE TITLE
pki/kube-apiserver/etcd-client.crt expired

### ISSUE THREAD

**Issue by throrin19** [kubernetes/kops#12985]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.18.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS but I have created all the cluster using kops. Master and nodes are in EC2. I don't use EKS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

a. connect to the master node
a. run `for file in /etc/kubernetes/pki/kube-apiserver/*; do echo "$file:"; openssl x509 -in $file -text | grep 'Not Before\|Not After'; done`

**5. What happened after the commands executed?**

see the certificate `/etc/kubernetes/pki/kube-apiserver/etcd-client.crt` has expired since 08/12/2021

**6. What did you expect to happen?**

All certificates are not expired

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-05-29T15:16:16Z"
  generation: 4
  name: my.example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx-kubernetes-clusters-configs/my.example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.12
  masterInternalName: api.internal.my.example.com
  masterPublicName: api.my.example.com
  networkCIDR: X.X.X.X/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: X.X.X.X/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: X.X.X.X/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: X.X.X.X/19
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: X.X.X.X/19
    name: eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:16:17Z"
  labels:
    kops.k8s.io/cluster: my.example.com
  name: master-eu-west-1a
spec:
  image: ami-06ce3edf0cff21f07
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:16:17Z"
  labels:
    kops.k8s.io/cluster: my.example.com
  name: nodes
spec:
  image: ami-06ce3edf0cff21f07
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

It is a minimum cluster with only one master and one node to run rancher application
