### ISSUE TITLE
Pods can assume EC2 Instance Roles 

### ISSUE THREAD

**Issue by mixja** [kubernetes/kops#13078]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.22.2 (git-0f728591a29491b09d6fb61028bdf857c76f8e69)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

In a pod with AWS CLI installed and configured with default region run the following:

```
aws sts get-caller-identity
{
    "UserId": "xxxx",
    "Account": "xxx",
    "Arn": "arn:aws:sts::xxxx:assumed-role/nodes.cluster.k8s.local/i-12345678d20aa201b"
}
```

The pod has all IAM permissions assigned to the EC2 instance role

**5. What happened after the commands executed?**

n/a

**6. What did you expect to happen?**

As per https://kops.sigs.k8s.io/iam_roles/:

> As of kOps 1.22, new clusters running Kubernetes 1.22 on AWS will restrict Pod access to the instance metadata service. This means that Pods will also be prevented from directly assuming instance roles. See IAM Roles for ServiceAccounts and instance metadata documentation. Before this, all Pods running on your cluster have access to the instance IAM role. Consider enabling the protection mentioned above and use IRSA for your own workloads.

Based upon the above, pods should not be able to assume the IAM instance role of nodes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-01-03T16:25:37Z"
  name: xxxx.k8s.local
spec:
  additionalPolicies:
    bastion: xxx
    master: xxx
    node: xxx
  api:
    loadBalancer:
      class: Network
      type: Internal
  authentication:
    aws:
      image: xxxx.dkr.ecr.us-gov-west-1.amazonaws.com/kops/aws-iam-authenticator:v0.5.2-debian-stretch
  authorization:
    rbac: {}
  cloudProvider: aws
  configBase: s3://xxxx/xxxx.k8s.local
  docker:
    version: 20.10.8
  encryptionConfig: true
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    name: events
  fileAssets:
  - content: "apiVersion: apiserver.config.k8s.io/v1\nkind: AdmissionConfiguration\nplugins:\n-
      name: EventRateLimit\n  path: /srv/kubernetes/kube-apiserver/eventconfig.yaml
      \       \n"
    name: admission-control
    path: /srv/kubernetes/kube-apiserver/admission-control.yaml
    roles:
    - Master
  - content: |
      #!/bin/bash

      # Kubebench 1.1.9
      chmod -R 600 /etc/cni/net.d
    name: kubebench-permissions.sh
    path: /srv/kubernetes/kubebench-permissions.sh
  - content: |
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          scheduler.alpha.kubernetes.io/critical-pod: ""
        labels:
          k8s-app: aws-encryption-provider
        name: aws-encryption-provider
        namespace: kube-system
      spec:
        containers:
        - image: xxxx.dkr.ecr.us-gov-west-1.amazonaws.com/xxxx/aws-encryption-provider:0.0.1
          name: aws-encryption-provider
          command:
          - /aws-encryption-provider
          - --key=arn:aws-us-gov:kms:us-gov-west-1:xxxx:key/xxxx
          - --region=us-gov-west-1
          - --kms-endpoint=kms.us-gov-west-1.amazonaws.com
          - --listen=/srv/kubernetes/kube-apiserver/socket.sock
          - --health-port=:8083
          ports:
          - containerPort: 8083
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
          volumeMounts:
          - mountPath: /srv/kubernetes/kube-apiserver/
            name: kmsplugin
        hostNetwork: true
        priorityClassName: system-cluster-critical
        volumes:
        - name: kmsplugin
          hostPath:
            path: /srv/kubernetes/kube-apiserver/
            type: DirectoryOrCreate
    name: aws-encryption-provider.yaml
    path: /etc/kubernetes/manifests/aws-encryption-provider.yaml
    roles:
    - Master
  - content: |
      apiVersion: eventratelimit.admission.k8s.io/v1alpha1
      kind: Configuration
      limits:
      - type: Namespace
        qps: 50
        burst: 100
        cacheSize: 2000
      - type: User
        qps: 10
        burst: 50
    name: eventconfig.yaml
    path: /srv/kubernetes/kube-apiserver/eventconfig.yaml
    roles:
    - Master
  - content: |
      xxxx
    name: cloudwatch-agent
    path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  hooks:
  - before:
    - kubelet.service
    manifest: "Type=oneshot\nExecStart=/bin/sh /srv/kubernetes/kubebench-permissions.sh
      \ \n"
    name: kubebench-permissions.service
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControlConfigFile: /srv/kubernetes/kube-apiserver/admission-control.yaml
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    authorizationMode: Node,RBAC
    disableBasicAuth: true
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - EventRateLimit
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - AlwaysPullImages
    enableProfiling: false
    kubeletCertificateAuthority: /srv/kubernetes/ca.crt
    kubeletPreferredAddressTypes:
    - Hostname
    requestTimeout: 1m0s
    tlsCipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  kubeControllerManager:
    enableProfiling: false
    featureGates:
      RotateKubeletServerCertificate: "true"
    terminatedPodGCThreshold: 10
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubeScheduler:
    enableProfiling: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupDriver: systemd
    featureGates:
      RotateKubeletServerCertificate: "true"
    protectKernelDefaults: true
    readOnlyPort: 0
    rotateCertificates: true
    streamingConnectionIdleTimeout: 5m0s
  kubernetesApiAccess:
  - x.x.x.x/x
  kubernetesVersion: v1.22.5
  masterPublicName: api.xxxx.k8s.local
  networkCIDR: 172.16.0.0/16
  networkID: vpc-xxxx
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://xxxx-oidc
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.16.32.0/19
    id: subnet-xxxx
    name: us-gov-west-1a
    type: Private
    zone: us-gov-west-1a
  - cidr: 172.16.64.0/19
    id: subnet-xxxx
    name: us-gov-west-1b
    type: Private
    zone: us-gov-west-1b
  - cidr: 172.16.0.0/22
    id: subnet-xxxx
    name: utility-us-gov-west-1a
    type: Utility
    zone: us-gov-west-1a
  - cidr: 172.16.4.0/22
    id: subnet-xxxx
    name: utility-us-gov-west-1b
    type: Utility
    zone: us-gov-west-1b
  sysctlParameters:
  - vm.overcommit_memory=1
  - kernel.panic=10
  - kernel.panic_on_oops=1
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-03T16:25:38Z"
  labels:
    kops.k8s.io/cluster: xxxx.k8s.local
  name: master-us-gov-west-1a
spec:
  additionalSecurityGroups:
  - sg-xxxx
  additionalUserData:
  - content: |
      #cloud-config
      runcmd:
        - xxxx
    name: cloudconfig.txt
    type: text/cloud-config
  image: ami-xxxx
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-gov-west-1a
  role: Master
  rootVolumeSize: 80
  rootVolumeType: gp3
  subnets:
  - us-gov-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-03T16:25:38Z"
  labels:
    kops.k8s.io/cluster: xxxx.k8s.local
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-xxxx
  additionalUserData:
  - content: |
      #cloud-config
      runcmd:
        - xxxxx
    name: cloudconfig.txt
    type: text/cloud-config
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
  externalLoadBalancers:
  - targetGroupArn: arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:xxxx:targetgroup/tf-xxxx/xxxx
  image: ami-xxxx
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 128
  rootVolumeType: gp3
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-03T16:25:38Z"
  labels:
    kops.k8s.io/cluster: xxxxx.k8s.local
  name: nodes-xlarge
spec:
  additionalSecurityGroups:
  - sg-xxxx
  additionalUserData:
  - content: |
      #cloud-config
      runcmd:
        -xxxxx
    name: cloudconfig.txt
    type: text/cloud-config
  cloudLabels:
    instance-type: m5-xlarge
    k8s.io/cluster-autoscaler/enabled: ""
  externalLoadBalancers:
  - targetGroupArn: arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:xxxx:targetgroup/tf-xxxx/xxxx
  image: ami-xxxx
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-xlarge
  role: Node
  rootVolumeSize: 128
  rootVolumeType: gp3
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Please advise any commands that should be run.

**9. Anything else do we need to know?**

I note in the YAML output in no. 7 above that the following settings are not showing, which ARE defined in the cluster spec:

```
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
```

Is this because this is the default setting in pops v1.22?

**Comment by olemarkus** [comment]
If you use `kops create cluster` then max hop limit should be added to the instancegroup spec. If you provide your own instance group spec, you need to provide this yourself.

**Comment by mixja** [comment]
OK after applying setting in the correct scope I can no longer access the instance role, but according to the docs, this should be the default configuration on node instance groups:

```
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
```
