### ISSUE TITLE
Cannot enable IRSA on existing cluster

### ISSUE THREAD

**Issue by dmitriishaburov** [kubernetes/kops#13101]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.21.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.22.3
Server Version: v1.21.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

On existing cluster:
- Enable IRSA:
```
serviceAccountIssuerDiscovery:
  discoveryStore: s3://our-discovery-bucket/
  enableAWSOIDCProvider: true
```
- Try to update cluster:
``` 
# kops update cluster cluster
-   serviceAccountIssuer: https://api.internal.cluster.com
+   serviceAccountIssuer: https://our-discovery-bucket/
+   serviceAccountJWKSURI: https://our-discovery-bucket/openid/v1/jwks
-   serviceAccountJWKSURI: https://api.internal.cluster.com/openid/v1/jwks

# kops update cluster cluster --yes
# kops rolling-update cluster --yes
Cluster did not pass validation, will retry in "30s": system-node-critical pod "calico-node-r4pvs" is not ready (calico-node).
Cluster did not pass validation, will retry in "30s": system-node-critical pod "calico-node-r4pvs" is not ready (calico-node).

# kubectl logs calico-node-r4pvs
2022-01-13 13:25:00.297 [INFO][9] startup/startup.go 450: Checking datastore connection
2022-01-13 13:25:00.321 [WARNING][9] startup/startup.go 462: Connection to the datastore is unauthorized error=connection is unauthorized: Unauthorized
2022-01-13 13:25:00.321 [WARNING][9] startup/startup.go 1347: Terminating
Calico node failed to start
```

**5. What happened after the commands executed?**

Cluster failed to update, was forced to rollback changes with verification disabled.

**6. What did you expect to happen?**

Cluster updated successfuly and I'm able to configure IRSA

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
---
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: # removed
spec:
  additionalPolicies:
    node: # removed
  DisableSubnetTags: true
  api:
    loadBalancer:
      type: Internal
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubeDNS:
    provider: CoreDNS
    nodeLocalDNS:
      enabled: true
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  cloudLabels:
    Creator: kops
    Owner: # removed
    Project: # removed
    Repository: # removed
  configBase: # removed
  containerRuntime: docker
  dnsZone: # removed
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - instanceGroup: master-eu-central-1a
          name: a
        - instanceGroup: master-eu-central-1b
          name: b
        - instanceGroup: master-eu-central-1c
          name: c
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - instanceGroup: master-eu-central-1a
          name: a
        - instanceGroup: master-eu-central-1b
          name: b
        - instanceGroup: master-eu-central-1c
          name: c
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: 1.21.6
  masterPublicName: # removed
  networkCIDR: # removed
  networkID: # removed
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - # removed
  subnets:
    - cidr: # removed
      id: # removed
      name: eu-central-1a
      type: Private
      zone: eu-central-1a
    - cidr: # removed
      id: # removed
      name: eu-central-1b
      type: Private
      zone: eu-central-1b
    - cidr: # removed
      id: # removed
      name: eu-central-1c
      type: Private
      zone: eu-central-1c
    - cidr: # removed
      id: # removed
      name: utility-eu-central-1a
      type: Utility
      zone: eu-central-1a
    - cidr: # removed
      id: # removed
      name: utility-eu-central-1b
      type: Utility
      zone: eu-central-1b
    - cidr: # removed
      id: # removed
      name: utility-eu-central-1c
      type: Utility
      zone: eu-central-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
  clusterAutoscaler:
    enabled: true
    balanceSimilarNodeGroups: true
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: false
  nodeTerminationHandler:
    enabled: true
    enableScheduledEventDraining: true
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  serviceAccountIssuerDiscovery:
    discoveryStore: # removed
    enableAWSOIDCProvider: true
```
