### ISSUE TITLE
is not authorized to perform: elasticloadbalancing:ModifyListener

### ISSUE THREAD

**Issue by throrin19** [kubernetes/kops#13117]
/kind bug

**1. What `kops` version are you running? 1.22.2

**2. What Kubernetes version are you running? 

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T14:47:10Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- Upgrade my cluster to 1.19 to 1.20
- Fix all ingress-nginx part

**5. What happened after the commands executed?**

- Have an error in intress-service due to IAM policy :  

```
Error updating load balancer with new hosts map[ip-xxx.xxx.xxx.xxx.xxx.compute.internal:{}]: error updating load balancer listener: "AccessDenied: User: arn:aws:sts::xxxxxxxxx:assumed-role/masters.rancher-mgmt.aquassay.net/i-xxxxxxxxx is not authorized to perform: elasticloadbalancing:ModifyListener on resource: arn:aws:elasticloadbalancing:eu-west-1:xxxxxxxxx:listener/net/xxxxxxxxx/xxxxxxxxx/xxxxxxxxx because no identity-based policy allows the elasticloadbalancing:ModifyListener action\n\tstatus code: 403, request id: xxxx-xxxx-xxxx-xxxx"
```

**6. What did you expect to happen?**

All this part works fine

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-05-29T15:16:16Z"
  generation: 7
  name: my-cluster.local
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-bucket/my-cluster.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.14
  masterInternalName: api.internal.my-cluster.local
  masterPublicName: api.my-cluster.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: 172.20.96.0/19
    name: eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:16:17Z"
  labels:
    kops.k8s.io/cluster: my-cluster.local
  name: master-eu-west-1a
spec:
  image: ami-06ce3edf0cff21f07
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:16:17Z"
  labels:
    kops.k8s.io/cluster: my-cluster.local
  name: nodes
spec:
  image: ami-06ce3edf0cff21f07
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I don't know if the problem is from ingress-nginx or kops but, I think,  the problem is on the master IAM role. But the master role have the correct rights. The only things, I think made this error, are the conditions 

```json
{
    "Statement": [
        {
            "Action": "ec2:AttachVolume",
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/KubernetesCluster": "my-cluster.local",
                    "aws:ResourceTag/k8s.io/role/master": "1"
                }
            },
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        },
        {
            "Action": [
                "s3:Get*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::my-bucket/my-cluster.local/*"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::my-bucket/my-cluster.local/backups/etcd/main/*"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::my-bucket/my-cluster.local/backups/etcd/events/*"
        },
        {
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetEncryptionConfiguration",
                "s3:ListBucket",
                "s3:ListBucketVersions"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::my-bucket"
            ]
        },
        {
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:GetHostedZone"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:route53:::hostedzone/XXXXXXXX"
            ]
        },
        {
            "Action": [
                "route53:GetChange"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:route53:::change/*"
            ]
        },
        {
            "Action": [
                "route53:ListHostedZones",
                "route53:ListTagsForResource"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        },
        {
            "Action": "ec2:CreateTags",
            "Condition": {
                "StringEquals": {
                    "ec2:CreateAction": [
                        "CreateVolume",
                        "CreateSnapshot"
                    ]
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:*:volume/*",
                "arn:aws:ec2:*:*:snapshot/*"
            ]
        },
        {
            "Action": "ec2:CreateTags",
            "Condition": {
                "StringEquals": {
                    "ec2:CreateAction": [
                        "CreateVolume",
                        "CreateSnapshot"
                    ]
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:*:volume/*",
                "arn:aws:ec2:*:*:snapshot/*"
            ]
        },
        {
            "Action": "ec2:DeleteTags",
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/KubernetesCluster": "my-cluster.local"
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:*:volume/*",
                "arn:aws:ec2:*:*:snapshot/*"
            ]
        },
        {
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "ec2:CreateSecurityGroup",
                "ec2:CreateTags",
                "ec2:DescribeAccountAttributes",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstances",
                "ec2:DescribeLaunchTemplateVersions",
                "ec2:DescribeRegions",
                "ec2:DescribeRouteTables",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DescribeVolumesModifications",
                "ec2:DescribeVpcs",
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:DescribeRepositories",
                "ecr:GetAuthorizationToken",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:ListImages",
                "elasticloadbalancing:AddTags",
                "elasticloadbalancing:CreateListener",
                "elasticloadbalancing:CreateTargetGroup",
                "elasticloadbalancing:DescribeListeners",
                "elasticloadbalancing:DescribeLoadBalancerAttributes",
                "elasticloadbalancing:DescribeLoadBalancerPolicies",
                "elasticloadbalancing:DescribeLoadBalancers",
                "elasticloadbalancing:DescribeTargetGroups",
                "elasticloadbalancing:DescribeTargetHealth",
                "elasticloadbalancing:RegisterTargets",
                "iam:GetServerCertificate",
                "iam:ListServerCertificates",
                "kms:DescribeKey",
                "kms:GenerateRandom"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "ec2:AttachVolume",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateRoute",
                "ec2:DeleteRoute",
                "ec2:DeleteSecurityGroup",
                "ec2:DeleteVolume",
                "ec2:DetachVolume",
                "ec2:ModifyInstanceAttribute",
                "ec2:ModifyVolume",
                "ec2:RevokeSecurityGroupIngress",
                "elasticloadbalancing:AddTags",
                "elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
                "elasticloadbalancing:AttachLoadBalancerToSubnets",
                "elasticloadbalancing:ConfigureHealthCheck",
                "elasticloadbalancing:CreateLoadBalancerListeners",
                "elasticloadbalancing:CreateLoadBalancerPolicy",
                "elasticloadbalancing:DeleteListener",
                "elasticloadbalancing:DeleteLoadBalancer",
                "elasticloadbalancing:DeleteLoadBalancerListeners",
                "elasticloadbalancing:DeleteTargetGroup",
                "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                "elasticloadbalancing:DeregisterTargets",
                "elasticloadbalancing:DetachLoadBalancerFromSubnets",
                "elasticloadbalancing:ModifyListener",
                "elasticloadbalancing:ModifyLoadBalancerAttributes",
                "elasticloadbalancing:ModifyTargetGroup",
                "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                "elasticloadbalancing:RegisterTargets",
                "elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer",
                "elasticloadbalancing:SetLoadBalancerPoliciesOfListener"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/KubernetesCluster": "my-cluster.local"
                }
            },
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "ec2:CreateSecurityGroup",
                "ec2:CreateVolume",
                "elasticloadbalancing:CreateListener",
                "elasticloadbalancing:CreateLoadBalancer",
                "elasticloadbalancing:CreateTargetGroup"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/KubernetesCluster": "my-cluster.local"
                }
            },
            "Effect": "Allow",
            "Resource": "*"
        }
    ],
    "Version": "2012-10-17"
}
```

**Comment by olemarkus** [comment]
In an effort to tighten the permissions, the NLB permissions may have gotten too tight. There are no e2e testes from kubernetes to test NLBs, unfortunately.

**Comment by throrin19** [comment]
You think, in that case, I remove the concitions part to test if it's the problem ?

But it works fine with kubernetes 1.19. It's weird the problem occured with the kubernetes upgrade. The policy is untouched

**Comment by throrin19** [comment]
I've updated to ingress-nginx 1.0.5 and now I have the ingress blocked to Ensuring LoadBalancer, without any log

**Comment by olemarkus** [comment]
Try something like `kubectl logs -n kube-system -l k8s-app=kube-controller-manager`

**Comment by throrin19** [comment]
After remove the condition part, it works fine. Their is a change about that in kubernetes 1.20 ?

**Comment by olemarkus** [comment]
One thing to keep in mind is that KCM will have a brief period when it doesn't have the tags needed (it creates the LB, then tag), so you will see this error intermittently. But it should go away and the LB should work.
Looking at the permissions 1.22.2 generates, it does look correct.

**Comment by throrin19** [comment]
It seems like witchcraft with sometimes it works or not

**Comment by olemarkus** [comment]
Does that mean you are seeing non-working ELBs after several minutes?

**Comment by throrin19** [comment]
The only solution for me was to remove the conditions of the IAM rights

**Comment by olemarkus** [comment]
Right. It seems like KCM isn't tagging listeners at all. I'll remove the condition on the listener actions for now.

**Comment by throrin19** [comment]
But the weird part is : it works fine when I upgrade to kubernetes 1.19 several minutes before upgrade to 1.20

**Comment by spohner** [comment]
We encountered the same issue. Ended up adding to the additionalPolicies/master spec for now:

`additionalPolicies:
   masters:
        {
            "Action": "elasticloadbalancing:ModifyListener",
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        }
      `

We were afraid that removing the condition manually will get reverted with a kops update. It would also be less tight in regards to the IAM rights.

**Comment by Tinche** [comment]
Just had a nasty surprise due to this. @spohner thanks for the lifesaving snippet!

**Comment by arpanadhikari** [comment]
> Right. It seems like KCM isn't tagging listeners at all. I'll remove the condition on the listener actions for now.

I'd be happy to make a PR for it if this isn't already in the works.

**Comment by olemarkus** [comment]
This should already have been fixed in kops 1.22.4.

If there are still issues with this, do reopen or file a new bug.

/close

**Comment by Eugst** [comment]
@olemarkus I faced with the same problem after upgrading kops from 1.21.x version to 1.24.2

> Error updating load balancer with new hosts map[ip-1111.ec2.internal:{} ip-1111.ec2.internal:{} ip-1111.ec2.internal:{} ip-1111.ec2.internal:{} ip-1111.ec2.internal:{} ip-1111.ec2.internal:{}]: error updating load balancer listener: "AccessDenied: User: arn:aws:sts::1111:assumed-role/masters.cl1.dev.cxl.io/1111 is not authorized to perform: elasticloadbalancing:ModifyListener on resource: arn:aws:elasticloadbalancing:region:1111:listener/net/1111/1111/1111 because no identity-based policy allows the elasticloadbalancing:ModifyListener action\n\tstatus code: 403, request id: 1111"

**Comment by olemarkus** [comment]
@Eugst Can you confirm the problem persists longer than 10 min? There is some delay on the AWS side on picking up the permissions after tagging.

**Comment by Eugst** [comment]
Yes. As the listener doesn’t have tag. And modifying permission has condition to master tag. So it won’t ever work. The additional policy helped.

**Comment by olemarkus** [comment]
Can you upgrade to 1.24.2 and confirm you still have the same issue?

**Comment by Eugst** [comment]
@olemarkus as I mentioned above, I have this issue after upgrade to 1.24.2

**Comment by Eugst** [comment]
@olemarkus 
```
apiVersion: v1
kind: Service
metadata:
  name: ambassador-next
  namespace: ambassador-next
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: ambassador-next
      config:
        use_proxy_proto: false
        use_remote_address: true
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: ambassador-next
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: >-
      arn:aws:acm:us-east-1:1111:certificate/1-2-3-4-5
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  selfLink: /api/v1/namespaces/ambassador-next/services/ambassador-next
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/instance: ambassador-next
    app.kubernetes.io/name: ambassador
  type: LoadBalancer

```
