### ISSUE TITLE
Resource on AWS for masterPublicName

### ISSUE THREAD

**Issue by aliartiza75** [kubernetes/kops#13129]
/kind bug

Hi,

I have deployed a k8s cluster for testing. Everything is working fine. 

In the **kubeconfig**, I found out that there is a **server** attribute under **cluster** configuration. It refers to a URL **_https://api.test-cluser-name_**. This URL points to the master node. 

I want to know how this URL is generated because there is no entry added on AWS (in the hosted zone). I have also checked the EC2 instance configuration and was not able to find this DNS entry and no load balancer resource is created.

I have also checked these documentations:

1. [ClusterSpec](https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#ClusterSpec).
2. Cluster resource [docs](https://kops.sigs.k8s.io/cluster_spec/#api).

I want to understand how this works. I have further details below, please ignore the k8s and kops version, I know it's an old version. I deployed this cluster for testing a few things.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.15.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.13.12

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
NIL

**5. What happened after the commands executed?**
NIL

**6. What did you expect to happen?**
NIL

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
NAME				CLOUD	ZONES
test-cluser-name	aws	us-west-2a

Instance Groups
NAME			ROLE	MACHINETYPE	MIN	MAX	ZONES
master-us-west-2a	Master	m3.medium	1	1	us-west-2a
nodes			Node	t2.medium	2	2	us-west-2a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

No logs needed

**9. Anything else do we need to know?**
NIL

Thanks

**Comment by aliartiza75** [comment]
Hi @olemarkus,

Can you or someone from your team provide me with some pointers about where to look? 

thank you.

**Comment by aliartiza75** [comment]
Cluster Manifest:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-01-18T15:43:49Z"
  generation: 3
  name: test-k8s.xyz.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://test-k8s.xyz.com/test-k8s.xyz.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - X.X.X.X/32
  kubernetesVersion: 1.13.12
  masterInternalName: api.internal.test-k8s.xyz.com
  masterPublicName: api.test-k8s.xyz.com
  networkCIDR: X.X.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: X.X.0.0/10
  sshAccess:
  - X.X.X.X/32
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

```
