### ISSUE TITLE
deploy on t2.micro dont get healthy

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [kubernetes/kops#13148]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.22.3 (git-241bfeba5931838fd32f2260aff41dd89a585fba)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster \
    --zones=us-east-1a \
    --node-size $NODE_SIZE \
    --master-size $MASTER_SIZE \
    ${NAME}
**5. What happened after the commands executed?**
if  MASTER_SIZE is t2.micro cluster don't get healthy and it returns:
```
INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1a       Master  t2.micro        1       1       us-east-1a
nodes-us-east-1a        Node    t2.micro        1       1       us-east-1a

NODE STATUS
NAME                            ROLE    READY
ip-172-20-39-241.ec2.internal   master  True
ip-172-20-41-47.ec2.internal    node    False

VALIDATION ERRORS
KIND    NAME                                                                    MESSAGE
Node    ip-172-20-41-47.ec2.internal                                            node "ip-172-20-41-47.ec2.internal" of role "node" is not ready
Pod     kube-system/coredns-5dc785954d-rvkzm                                    system-cluster-critical pod "coredns-5dc785954d-rvkzm" is pending
Pod     kube-system/coredns-autoscaler-84d4cfd89c-2xvgw                         system-cluster-critical pod "coredns-autoscaler-84d4cfd89c-2xvgw" is pending
Pod     kube-system/kube-controller-manager-ip-172-20-39-241.ec2.internal       system-cluster-critical pod "kube-controller-manager-ip-172-20-39-241.ec2.internal" is not ready (kube-controller-manager)

Validation Failed
W0124 15:52:12.751853  976986 validate_cluster.go:232] (will retry): cluster not yet healthy
Error: Validation failed: wait time exceeded during validation

```
**6. What did you expect to happen?**
cluster should be created as expected
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-01-24T18:37:53Z"
  name: cluster.dev.cryptween.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://dev-k8s/cluster.dev.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.22.5
  masterPublicName: api.cluster.dev.cryptween.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-24T18:37:54Z"
  labels:
    kops.k8s.io/cluster: cluster.dev.cryptween.com
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211118
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-01-24T18:37:54Z"
  labels:
    kops.k8s.io/cluster: cluster.dev.cryptween.com
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211118
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

```
```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
https://gist.github.com/israel-gonzalezmedina/4297740d57f3ab4d9f50d0ce8d021598
**9. Anything else do we need to know?**
