### ISSUE TITLE
Get https://127.0.0.1:4001/health: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by gmairi** [kubernetes/kops#13239]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.3 (git-298c2fce8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops validate cluster
kubectl get componentstatus
find /mnt/ -type f -name me.crt -print -exec openssl x509 -enddate -noout -in {} \; (on the effected master node)

**5. What happened after the commands executed?**
```
kops validate cluster

NAME                                 ROLE    READY
ip-< master1 >.compute.internal     master   True
ip-< master2 >.compute.internal     master   True
ip-< master3>.compute.internal     master   Unknown 
ip-< worker1 >.compute.internal     node     True
ip-< worker2 >.compute.internal     node     True

VALIDATION ERRORS
KIND            NAME                                            MESSAGE
ComponentStatus etcd-0                                          component "etcd-0" is unhealthy
ComponentStatus etcd-1                                          component "etcd-1" is unhealthy
Node            ip-< master1 >.compute.internal     master "< master1 >.compute.internal" is not ready
```
kubectl get componentstatus
```
NAME                 STATUS      MESSAGE                                                                 ERROR
scheduler            Healthy     ok
etcd-1               Unhealthy   Get https://127.0.0.1:4002/health: remote error: tls: bad certificate
controller-manager   Healthy     ok
etcd-0               Unhealthy   Get https://127.0.0.1:4001/health: remote error: tls: bad certificate
```
find /mnt/ -type f -name me.crt -print -exec openssl x509 -enddate -noout -in {} \;
```
/mnt/master-vol-<randomnumber>-g/peers/me.crt
notAfter=Feb  2 05:25:21 2023 GMT

/mnt/master-vol-<randomnumber>/peers/me.crt
notAfter=Feb  2 05:24:09 2023 GMT
```
Didnt find any certificate expiry issue running above command

**6. What did you expect to happen?**
Master node to join the cluster and for the cluster to be validated successfully

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-02-01T04:52:08Z"
  generation: 3
  name: <redacted>
spec:
  api:
    loadBalancer:
      sslCertificate: <redacted>
      type: <redacted>
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Env: <redacted>
    Owner: <redacted>
  cloudProvider: aws
  configBase: s3://<redacted>/<redacted>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - <redacted>
  kubernetesVersion: 1.15.7
  masterInternalName: api.internal.<redacted>
  masterPublicName: api.<redacted>
  networkCIDR: <redacted>
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - <redacted>
  subnets:
  - cidr: <redacted>
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: <redacted>
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: <redacted>
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: <redacted>
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: <redacted>
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: <redacted>
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    bastion:
      bastionPublicName: bastion.<redacted>
    dns:
      type: <redacted>
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-01T04:52:09Z"
  labels:
    kops.k8s.io/cluster: <redacted>
  name: bastions
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-west-2a
  - utility-us-west-2b
  - utility-us-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-01T04:52:08Z"
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-01T04:52:08Z"
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-01T04:52:09Z"
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-01T04:52:09Z"
  generation: 22
  labels:
    kops.k8s.io/cluster: <redacted>
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I0212 06:33:37.732340    7130 round_trippers.go:419] curl -k -v -XGET  -H "User-Agent: kubectl/v1.15.0 (linux/amd64) kubernetes/e8462b5" -H "Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json" -H "Authorization: Basic <redacted>" 'https://api.<redacted>/api/v1/componentstatuses?limit=500'
I0212 06:33:37.748083    7130 round_trippers.go:438] GET https://api.<redacted>/api/v1/componentstatuses?limit=500 200 OK in 15 milliseconds
I0212 06:33:37.748159    7130 round_trippers.go:444] Response Headers:
I0212 06:33:37.748193    7130 round_trippers.go:447]     Date: Sat, 12 Feb 2022 06:33:37 GMT
I0212 06:33:37.748221    7130 round_trippers.go:447]     Content-Length: 945
I0212 06:33:37.748259    7130 round_trippers.go:447]     Content-Type: application/json
I0212 06:33:37.748329    7130 request.go:947] Response Body: {"kind":"ComponentStatusList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/componentstatuses"},"items":[{"metadata":{"name":"scheduler","selfLink":"/api/v1/componentstatuses/scheduler","creationTimestamp":null},"conditions":[{"type":"Healthy","status":"True","message":"ok"}]},{"metadata":{"name":"controller-manager","selfLink":"/api/v1/componentstatuses/controller-manager","creationTimestamp":null},"conditions":[{"type":"Healthy","status":"True","message":"ok"}]},{"metadata":{"name":"etcd-0","selfLink":"/api/v1/componentstatuses/etcd-0","creationTimestamp":null},"conditions":[{"type":"Healthy","status":"False","message":"Get https://127.0.0.1:4001/health: remote error: tls: bad certificate"}]},{"metadata":{"name":"etcd-1","selfLink":"/api/v1/componentstatuses/etcd-1","creationTimestamp":null},"conditions":[{"type":"Healthy","status":"False","message":"Get https://127.0.0.1:4002/health: remote error: tls: bad certificate"}]}]}
I0212 06:33:37.750997    7130 table_printer.go:43] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table
I0212 06:33:37.751124    7130 table_printer.go:43] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table
I0212 06:33:37.751228    7130 table_printer.go:43] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table
I0212 06:33:37.751303    7130 table_printer.go:43] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table
NAME                 STATUS      MESSAGE                                                                 ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-0               Unhealthy   Get https://127.0.0.1:4001/health: remote error: tls: bad certificate
etcd-1               Unhealthy   Get https://127.0.0.1:4002/health: remote error: tls: bad certificate

**9. Anything else do we need to know?**
I have come across issue with certificate rotation last year and resolved it following the article - https://kops.sigs.k8s.io/advisories/etcd-manager-certificate-expiration/
