### ISSUE TITLE
Ability to compress audit logs

### ISSUE THREAD

**Issue by dannyharding10** [kubernetes/kops#13348]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I would like to be able to compress audit log files. On the [kube-apiserver spec](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), it says there is a flag called `--audit-log-compress`, but `kops edit cluster` will not let me add 
```
kubeAPIServer:
  auditLogCompress: true
```

**2. Feel free to provide a design supporting your feature request.**
I would expect to be able to use this feature just like the other audit log flags:

```
  kubeAPIServer:
    auditLogCompress: true
    auditLogMaxAge: 90
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
```
