### ISSUE TITLE
Cluster containers get DNS errors on some nodes

### ISSUE THREAD

**Issue by dmcnaught** [kubernetes/kops#13355]
/kind bug

Posted on Feb 14th to #kops-users 
https://kubernetes.slack.com/archives/C3QUFP0QM/p1644873024248629
Hi all,
One of our four cluster seems to be having DNS issues with messages like “Temporary failure in name resolution”, “Error: getaddrinfo EAI_AGAIN”.
We see the error on 2 or 3 of our 40 nodes at a time, so I’m wondering if we’re hitting some sort of limit. Doesn’t seem like it would be the known issue with systemd-resolved
The cluster is running kops private topology, coredns, kops 1.21.4 k8s 1.21.8,
When we do dns debugging, the dns works from dnsutils (https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops version
Version 1.21.4 (git-53e6bf3e5b0a77c78df2a7c60baca6e926fd5105)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
» kubectl version                                                                                                                                                     1 ↵
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Happens to our apps running in K8s, seems to be happening all the time.

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 40
  name: kubernetes.dev1.ourdomain.com
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["ec2:AttachVolume"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["ec2:DetachVolume"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  clusterAutoscaler:
    balanceSimilarNodeGroups: false
    cpuRequest: 100m
    enabled: true
    expander: least-waste
    image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.2
    memoryRequest: 300Mi
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  configBase: s3://ourdomain-kubernetes-state-store-nonprod/kubernetes.dev1.ourdomain.com
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::ourdomain:policy/k8s-cluster-autoscaler-perms-policy
    node:
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::ourdomain:policy/k8s-cluster-autoscaler-perms-policy
    - arn:aws:iam::ourdomain:policy/k8s-ingressController-iam-policy
  fileAssets:
  - content: |
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: None
          users:
            - kops
            - kubelet
            - system:apiserver
            - system:kube-apiserver
            - system:kube-controller-manager
            - system:kube-proxy
            - system:kube-scheduler
            - system:serviceaccount:default:newrelic
            - system:serviceaccount:default:splunk-connect-splunk-kubernetes-metrics
            - system:serviceaccount:default:splunk-connect-splunk-kubernetes-objects
            - system:serviceaccount:deis:deis-builder
            - system:serviceaccount:deis:deis-logger-fluentd
            - system:serviceaccount:deis:deis-monitor-telegraf
            - system:serviceaccount:deis:deis-router
            - system:serviceaccount:deis:deis-workflow-manager
            - system:serviceaccount:kube-system:alb-ingress
            - system:serviceaccount:kube-system:cluster-autoscaler
            - system:serviceaccount:kube-system:cronjob-controller
            - system:serviceaccount:kube-system:daemon-set-controller
            - system:serviceaccount:kube-system:deployment-controller
            - system:serviceaccount:kube-system:dns-controller
            - system:serviceaccount:kube-system:endpoint-controller
            - system:serviceaccount:kube-system:generic-garbage-collector
            - system:serviceaccount:kube-system:heapster
            - system:serviceaccount:kube-system:horizontal-pod-autoscaler
            - system:serviceaccount:kube-system:kube-dns
            - system:serviceaccount:kube-system:kube-dns-autoscaler
            - system:serviceaccount:kube-system:metrics-server
            - system:serviceaccount:kube-system:node-controller
            - system:serviceaccount:kube-system:namespace-controller
            - system:serviceaccount:kube-system:pod-garbage-collector
            - system:serviceaccount:kube-system:resourcequota-controller
            - system:serviceaccount:kube-system:replicaset-controller
            - system:serviceaccount:kube-system:route-controller
            - system:serviceaccount:kube-system:service-controller
            - system:serviceaccount:kube-system:tiller-deploy
            - system:serviceaccount:kube-system:ttl-controller
            - system:serviceaccount:kube-system:weave-net
            - system:serviceaccount:monitoring:kube-state-metrics
            - system:serviceaccount:monitoring:node-exporter
            - system:serviceaccount:monitoring:prometheus-k8s
            - system:serviceaccount:monitoring:prometheus-operator
            - system:serviceaccount:default:splunk-connect-splunk-kubernetes-logging
            - system:unsecured
        - level: Metadata
          omitStages:
            - "RequestReceived"
    name: audit-policy-file
    path: /srv/kubernetes/audit.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-dev1-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
  kubeControllerManager:
    authenticationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
    authorizationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
    horizontalPodAutoscalerUseRestClients: true
  kubeDNS:
    provider: CoreDNS
  kubeScheduler:
    authenticationKubeconfig: /var/lib/kube-scheduler/kubeconfig
    authorizationKubeconfig: /var/lib/kube-scheduler/kubeconfig
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - x.x.x.x/32
  kubernetesVersion: 1.21.8
  masterInternalName: api.internal.kubernetes.dev1.ourdomain.com
  masterPublicName: api.kubernetes.dev1.ourdomain.com
  metricsServer:
    enabled: true
    insecure: false
  networkCIDR: <redacted>.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 2
  sshAccess:
  - 10.5.0.0/16
  subnets:
  - cidr: <redacted>/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: <redacted>/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: <redacted>/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: <redacted>/19
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: <redacted>/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: <redacted>/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: <redacted>/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: <redacted>/22
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
