### ISSUE TITLE
1.23 AWS route controller creating and deleting routes in a loop due to node names being instance id

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kops#13376]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.23.0 (git-a067cd7742a497a5c512762b9880664d865289f1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster --state "${KOPS_STATE_FILE}" \
      --ssh-public-key="${SSH_KEY_PATH}".pub \
      --kubernetes-version=1.23.4 \
      --dry-run \
      -o yaml \
      "${CLUSTER_NAME}" > "${CLUSTER_FILE}"

< edited the file to add 
    cloudProvider: external
to kubelet, kubeapiserver and kubecontrollermanager >

kops create --state "${KOPS_STATE_FILE}" -f "${CLUSTER_FILE}"

**5. What happened after the commands executed?**

Cluster created and in the aws-cloud-controller logs it creates and deletes routes in a loop

```
I0316 19:44:28.088941       1 route_controller.go:247] Deleting route test-cluster-mar154.k8s.local-100.96.1.0/24 100.96.1.0/24
I0316 19:44:28.089211       1 route_controller.go:194] Creating route for node i-001ab2674ef942145 100.96.0.0/24 with hint 24e777a5-cba7-4079-82c6-57d215eb4865, throttled 12.167µs
I0316 19:44:28.089336       1 route_controller.go:247] Deleting route test-cluster-mar154.k8s.local-100.96.0.0/24 100.96.0.0/24
I0316 19:44:28.089553       1 route_controller.go:194] Creating route for node i-001c99c6268df2574 100.96.1.0/24 with hint bd6fb3d1-708e-45ef-8019-01090827d461, throttled 7.718µs
I0316 19:44:28.306218       1 route_controller.go:251] Deleted route test-cluster-mar154.k8s.local-100.96.1.0/24 100.96.1.0/24 after 217.278782ms
I0316 19:44:28.321762       1 route_controller.go:251] Deleted route test-cluster-mar154.k8s.local-100.96.0.0/24 100.96.0.0/24 after 232.83285ms
I0316 19:44:28.838736       1 route_controller.go:214] Created route for node i-001ab2674ef942145 100.96.0.0/24 with hint 24e777a5-cba7-4079-82c6-57d215eb4865 after 749.577905ms
I0316 19:44:29.094719       1 route_controller.go:214] Created route for node i-001c99c6268df2574 100.96.1.0/24 with hint bd6fb3d1-708e-45ef-8019-01090827d461 after 1.005167423s
```
**6. What did you expect to happen?**

aws-cloud-controller logs should not create and delete routes in a loop

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
~ $ kops get cluster --state s3://aws-ebs-csi-driver-e2e test-cluster-mar154.k8s.local -o yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-03-16T18:15:13Z"
  name: test-cluster-mar154.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
  cloudControllerManager:
    cloudProvider: aws
  cloudProvider: aws
  configBase: s3://wongma7/test-cluster-mar154.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    cloudProvider: external
  kubeControllerManager:
    cloudProvider: external
  kubelet:
    anonymousAuth: false
    cloudProvider: external
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.4
  masterPublicName: api.test-cluster-mar154.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The issue is because in kops 1.23 the node names are instance IDs which violates the assumption by the AWS ListRoutes implementation that node names are privateDNS.

I patched route controller to add a line here https://github.com/kubernetes/kubernetes/blob/release-1.23/staging/src/k8s.io/cloud-provider/controllers/route/route_controller.go#L231 to help illustrate:
```
			klog.Infof("nodeName %q not in nodeRoutesStatuses %v", nodeName, nodeRoutesStatuses)
```
It prints:
```
I0316 19:47:58.307784       1 route_controller.go:231] nodeName "ip-172-20-52-4.us-west-2.compute.internal" not in nodeRoutesStatuses map[i-001ab2674ef942145:map[100.96.0.0/24:false] i-001c99c6268df2574:map[100.96.1.0/24:false]]
```

The loop:

1. First route controller creates a route for each node and populates nodeRoutesStatuses accordingly where the keys are node names and node names are instance IDs. https://github.com/kubernetes/kubernetes/blob/release-1.23/staging/src/k8s.io/cloud-provider/controllers/route/route_controller.go#L154

2. Next it iterates through the list of `routes` returned by AWS ListRoutes implementation where each `route.TargetNode` is set to instance private DNS: https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws_routes.go#L117 / https://github.com/kubernetes/kubernetes/blob/release-1.23/staging/src/k8s.io/cloud-provider/controllers/route/route_controller.go#L237.

3. For each of these `routes`, route controller checks if it is present in nodeRoutesStatuses and deletes the route if it is not there. It assumes that route.TargetNode == nodeName and indexes nodeRoutesStatuses by route.TargetNode. But this is not true because private DNS != instance ID. So route controller's check always fails. It immediately deletes the routes it just created in 1.
