### ISSUE TITLE
Master and nodes not joining the cluster

### ISSUE THREAD

**Issue by nicolasespiau** [kubernetes/kops#13399]
Hi,

I've been trying to deploy a cluster in a private environment on AWS these last 2 weeks and I'm getting crazy here, I'd love to have some help.

I have a VPC with 2 private subnets where traffic is routed to a NATGW. There is no network problem in this issue.

I've created a cluster with the manifest attached, and master and nodes as well.

When I deploy the cluster, the kube-apiserver starts so I have access to kubectl commands, but no nodes are joining. Not the master, nor the workers.

I've tried many things, but no matter what it always end with a 403 error when kubelet tries to add master to cluster.

Sometimes I have errors like `E0322 01:47:40.893163    4647 kubelet_node_status.go:93] "Unable to register node with API server" err="nodes \"ip-10-1-1-248.eu-west-1.compute.internal\" is forbidden: node \"ip-10-1-1-248.myprivatehostedzone.priv\" is not allowed to modify node \"ip-10-1-1-248.eu-west-1.compute.internal\"" node="ip-10-1-1-248.eu-west-1.compute.internal"`

Here I can see that my instance does not have the proper name, and I don't how it got this hostname instead of `ip-10-1-1-248.eu-west-1.compute.internal`, but in other cases the 403 error is due to RBAC.

I tried to add `system:nodes` group in the clusterrolebinding `system:node` which didn't have a `subjects` field, but it did not solve the case:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-03-21T14:12:40Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node
  resourceVersion: "46593"
  uid: 1a186502-5cb3-4a6c-b48f-731419eb887e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
# the whole subjects part was missing
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
```

Sometimes I have NODE DENY errors, sometimes I have an error telling me that there is no RBAC authorization for that node to perform a POST /api/nodes or GET /api/csinodes:

Before modifying clusterrolebinding:
`NODE DENY: 'ip-10-1-1-14.myprivatehostedzone.priv' &authorizer.AttributesRecord{User:(*user.DefaultInfo)(0xc007892b00), Verb:"get", Namespace:"", APIGroup:"storage.k8s.io", APIVersion:"v1", Resource:"csinodes", Subresource:"", Name:"ip-10-1-1-14.eu-west-1.compute.internal", ResourceRequest:true, Path:"/apis/storage.k8s.io/v1/csinodes/ip-10-1-1-14.eu-west-1.compute.internal"}`

After:
`E0322 02:24:35.179113   17340 kubelet_node_status.go:93] "Unable to register node with API server" err="nodes \"ip-10-1-1-14.eu-west-1.compute.internal\" is forbidden: node \"ip-10-1-1-14.myprivatehostedzone.priv\" is not allowed to modify node \"ip-10-1-1-14.eu-west-1.compute.internal\"" node="ip-10-1-1-14.eu-west-1.compute.internal"`

I've put in comment the different options I tried with and without.

cluster.yaml:
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: pprd.myprivatehostedzone.priv
spec:
  api:
    loadBalancer:
      class: Network
      type: Internal
      additionalSecurityGroups:
      - sg-xxxxx
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://pathtostore
  containerRuntime: docker
  docker:
    execOpt:
    - native.cgroupdriver=cgroupfs
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
      volumeType: gp3
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
      volumeType: gp3
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::XXXX:policy/AssumeRole
    node:
    - arn:aws:iam::XXXX:policy/AssumeRole
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    anonymousAuth: false
#    authorizationMode: RBAC,Node
    logLevel: 8
    cloudProvider: aws
#    enableAdmissionPlugins:
#    - NodeRestriction
  kubelet:
    cgroupDriver: cgroupfs
    anonymousAuth: false
    logLevel: 8
#    cloudProvider: aws
#  masterKubelet:
#    cgroupDriver: cgroupfs
#    anonymousAuth: false
#    cloudProvider: aws
#    clusterDNS: 100.64.0.10
#    clusterDomain: cluster.local
#    enableDebuggingHandlers: true
 #   evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
#    featureGates:
#      CSIMigrationAWS: "true"
#      InTreePluginAWSUnregister: "true"
#    hostnameOverride: '@aws'
#    kubeconfigPath: /var/lib/kubelet/kubeconfig
#    logLevel: 8
#    networkPluginName: cni
#    nonMasqueradeCIDR: 100.64.0.0/10
#    podInfraContainerImage: k8s.gcr.io/pause:3.5
#    podManifestPath: /etc/kubernetes/manifests
#    protectKernelDefaults: true
#    registerSchedulable: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.22.7
  masterInternalName: api.internal.pprd.myprivatehostedzone.priv
  masterPublicName: api.pprd.myprivatehostedzone.priv
  networkCIDR: 10.1.0.0/16
  networkID: vpc-NNNN
  networking:
    calico: {}
#    crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: kube_pprd
  subnets:
  - cidr: 10.1.1.0/24
    id: subnet-NNNN
    # egress: nat-XXXX
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.1.3.0/24
    # egress: nat-XXXX
    id: subnet-NNNN
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

master.yaml
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: pprd.myprivatehostedzone.priv
  name: master-eu-west-1a
spec:
  additionalSecurityGroups:
  - sg-nnnn
  associatePublicIp: false
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  rootVolumeType: gp3
  subnets:
  - eu-west-1a
  kubelet:
    cloudProvider: aws
  kubeApiServer:
    cloudProvider: aws
```
