### ISSUE TITLE
1.22.0 Release Required actions missing NodeLocalDNS BC

### ISSUE THREAD

**Issue by jorge07** [kubernetes/kops#13442]
/kind bug

**3. What cloud provider are you using?**

Cluster upgrade from 1.21 to 1.22.x

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

cluster upgrade

**5. What happened after the commands executed?**

NodeLocalDNS stops forwarding to kubedns

**6. What did you expect to happen?**

Keep same behaviour as in 1.21

**7. Please provide your cluster manifest. Execute

```yaml
  kubeDNS:
    provider: CoreDNS
    coreDNSImage: k8s.gcr.io/coredns/coredns:v1.8.4
    nodeLocalDNS:
      enabled: true
```

`forwardToKubeDNS` default was behaviour was acting as `true`

**9. Anything else do we need to know?**

Add a note to `Required actions` section on the release of 1.22.0 for the next one to be aware of that important change on the behaviour.
