### ISSUE TITLE
DNS controller crashes when running in Digital Ocean with multiple masters

### ISSUE THREAD

**Issue by zak905** [kubernetes/kops#13441]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.23.0 (git-a067cd7742a497a5c512762b9880664d865289f1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-17T03:51:43Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

Digital Ocean

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

A simple way to reproduce this issue is to create a cluster in Digital ocean with multiple masters

for example:
``` 
kops create cluster --cloud=digitalocean --name=app.test.com --networking=flannel --master-count=3 --api-loadbalancer-type=public --node-size=s-2vcpu-4gb --image=debian-11-x64 --node-count=2 --zones=fra1 --ssh-public-key=~/.ssh/kops_rsa.pub
```

**5. What happened after the commands executed?**

First thing that I noticed was that:
* DNS records in Digital Ocean are not updated properly, there is only one record `api.app.test.com` and it does not have the right load balancer address but rather the placeholder address here https://github.com/kubernetes/kops/blob/master/dnsprovider/pkg/dnsprovider/providers/do/dns.go#L39
* This says that something went wrong or the domain update process was interupted
* After checking the dns controller pod logs I discovered that a panic was happening

**6. What did you expect to happen?**

To have two DNS record in Digital Ocean with correct IPs as values
one for api.test.app.com 
and one for api.internal.app.com

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-03-28T13:20:31Z"
  name: app.test.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: digitalocean
  configBase: s3://bucket/app.test.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-fra1-1
      name: etcd-1
    - instanceGroup: master-fra1-2
      name: etcd-2
    - instanceGroup: master-fra1-3
      name: etcd-3
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-fra1-1
      name: etcd-1
    - instanceGroup: master-fra1-2
      name: etcd-2
    - instanceGroup: master-fra1-3
      name: etcd-3
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.5
  masterPublicName: api.app.test.com
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - name: fra1
    region: fra1
    type: Public
    zone: fra1
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

this is the log output of the dns controller pod when running `kubectl get po dns-controller-{id} -n kube-system` 

```
I0328 17:06:06.699491       1 dnscontroller.go:324] Applying DNS changeset for zone my-domain.com::mydomain.com
I0328 17:06:06.699697       1 dns.go:323] applying changes in record change set
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1598205]

goroutine 28 [running]:
k8s.io/kops/dnsprovider/pkg/dnsprovider/providers/do.(*resourceRecordChangeset).applyResourceRecordSet(0xc0002f7dc0, {0x0, 0x0})
	dnsprovider/pkg/dnsprovider/providers/do/dns.go:390 +0x45
k8s.io/kops/dnsprovider/pkg/dnsprovider/providers/do.(*resourceRecordChangeset).Apply(0xc0002f7dc0, {0x1, 0x1})
	dnsprovider/pkg/dnsprovider/providers/do/dns.go:338 +0x525
k8s.io/kops/dns-controller/pkg/dns.(*DNSController).runOnce(0xc000348360)
	dns-controller/pkg/dns/dnscontroller.go:325 +0x112a
k8s.io/kops/dns-controller/pkg/dns.(*DNSController).runWatcher(0xc000348360, 0x0)
	dns-controller/pkg/dns/dnscontroller.go:120 +0x2f
created by k8s.io/kops/dns-controller/pkg/dns.(*DNSController).Run
	dns-controller/pkg/dns/dnscontroller.go:112 +0xc9
```

**9. Anything else do we need to know?**

After doing some investigation, it seems like:

* This happens when updating/creating records for the private api server, so api.internal.*
* For DO case, there are 3 IPs returned (one for each master), so I see this message in the logs: Adding DNS changes to batch {A [api.internal.app.test.com]().} [10.114.0.10 10.114.0.11 10.114.0.12]
* a nil error happens when calling new here with more than one record https://github.com/kubernetes/kops/blob/master/dnsprovider/pkg/dnsprovider/providers/do/dns.go#L226
* once it returns a nil, the dns controllers upserts a nil value here https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/dns/dnscontroller.go#L588
* finally when the Apply is invoked here https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/dns/dnscontroller.go#L325 the panic happens
