### ISSUE TITLE
Help needed: PersistentVolumeClaim annotated with storage-provisioner "ebs.csi.aws.com" although it is disabled

### ISSUE THREAD

**Issue by djablonski-moia** [kubernetes/kops#13466]
I'm facing a problem with setting up a new cluster with kOps 1.23.0. When creating the cluster, we have
```
  cloudConfig:
    awsEBSCSIDriver:
      enabled: false
```
This is needed for consistency between clusters for the time being.

We also have the following `StorageClass` defined: 

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
parameters:
  encrypted: "true"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Now, when creating a `PersistentVolumeClaim` like this

```
apiVersion: v1
kind: PersistentVolumeClaim
  name: my-pv
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ssd
  volumeMode: Filesystem
```

it somehow gets these annotations added:

```
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
```

And in the end, the PVC gets stuck in `Pending` state, as it expects the (disabled) AWS EBS CSI driver to create the PV.

This setup worked fine in kOps 1.22.3.

Can someone help, or at least explain why (and by which component) this is happening?
