### ISSUE TITLE
GPU node does not join the cluster after autoscaling

### ISSUE THREAD

**Issue by ptdtan** [kubernetes/kops#13468]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.23.0 (git-a067cd7742a497a5c512762b9880664d865289f1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.0
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create gpu instance group following https://github.com/kubernetes/kops/blob/master/docs/gpu.md.
Then create a test pod follow this recipe

```
---
apiVersion: v1
kind: Pod
metadata:
  name: diego-cuda-vector-add
spec:
  runtimeClassName: nvidia
  nodeSelector:
    instancetype: g4dn.xlarge
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  restartPolicy: OnFailure
  containers:
    - name: gpu
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1
```
**5. What happened after the commands executed?**
The Gpu node was triggered autoscaling. But it didn't join the cluster

**6. What did you expect to happen?**
The GPU node starts and joins the cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-03-20T17:12:00Z"
  generation: 1
  name: datascience-3.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-bucket/datascience-3.k8s.local
  containerd:
    nvidiaGPU:
      enabled: true
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::45300xxxxxx:policy/minimal-autoscaling
    - arn:aws:iam::45300xxxxxx:policy/AWSLoadBalancerControllerIAMPolicy
    node:
    - arn:aws:iam::45300xxxxxx:policy/minimal-autoscaling
    - arn:aws:iam::45300xxxxxx:policy/AWSLoadBalancerControllerIAMPolicy
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.21.0
  masterInternalName: api.internal.datascience-3.k8s.local
  masterPublicName: api.datascience-3.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
It successfully scaled up and join the cluster once. But after the scale down, the GPU nodes couldn't join the cluster ever again. 
I use Warmpool. When the node GPU node is initializing, I ssh to the node and found that the kubelet service doesn't exist. Is that normal?

@olemarkus
