### ISSUE TITLE
FeatureGate settings not passed to kube-controller-manager pods

### ISSUE THREAD

**Issue by djablonski-moia** [kubernetes/kops#13473]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.23.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops create cluster -f cluster-spec.yaml`

**5. What happened after the commands executed?**

The `kube-controller-manager` pods did not have the arg `--feature-gates=CSIMigrationAWS=false` set, while on the `kube-apiserver`, I see the expected arg `--feature-gates=EphemeralContainers=true`

**6. What did you expect to happen?**

I was expecting to see the flag `--feature-gates=CSIMigrationAWS=false` on the `kube-controller-manager` pods.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: my-cluster
spec:
  ...
  kubeAPIServer:
    ...
    featureGates:
      EphemeralContainers: "true"
      ..
  kubeControllerManager:
    featureGates:
      CSIMigrationAWS: "false"
  ...
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
