### ISSUE TITLE
Master nodes on AWS not joining the cluster after upgrade to kops 1.23.0

### ISSUE THREAD

**Issue by aharonh** [kubernetes/kops#13492]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.23.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.8

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops upgrade cluster test.com --yes
kops update cluster test.com --yes
kops rolling-update cluster test.com --instance-group master-us-east-1b --yes
```

**5. What happened after the commands executed?**

the cluster did not pass the validation, the replaced upgraded node did not join back the cluster

**6. What did you expect to happen?**

the upgraded node joins the cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-02-08T13:30:13Z"
  generation: 78
  name: test.com
spec:
  DisableSubnetTags: true
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": [
              "route53:ChangeResourceRecordSets",
              "route53:ListResourceRecordSets",
              "route53:GetHostedZone"
          ],
          "Resource": [
              "arn:aws:route53:::hostedzone/Z03047592P43JSA8N9YP2"
          ]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Internal
      useForInternalApi: true
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: false
  cloudLabels:
    env: dev
  cloudProvider: aws
  clusterAutoscaler:
    awsUseStaticInstanceList: false
    balanceSimilarNodeGroups: true
    enabled: true
    expander: random
    image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.2
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUtilizationThreshold: "0.5"
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: true
  configBase: s3://dev-state/kops/test.com
  dnsZone: test.com
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1f
      name: c
    name: main
    version: 3.3.10
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1f
      name: c
    name: events
    version: 3.3.10
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
  kubeControllerManager:
    featureGates:
      CSIMigration: "true"
      CSIMigrationAWS: "true"
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    metricsBindAddress: 0.0.0.0:10249
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      CSIMigration: "true"
      CSIMigrationAWS: "true"
    resolvConf: /run/systemd/resolve/resolv.conf
    runtimeRequestTimeout: 10m0s
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.23.5
  masterInternalName: api.test.com
  masterPublicName: api.test.com
  networkCIDR: 10.40.0.0/16
  networkID: vpc-096f9b1db861e910d
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://discovery-store-test
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.40.32.0/20
    id: subnet-05c88f64a5cec702d
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.40.64.0/20
    id: subnet-0f03514823d94ac94
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.40.160.0/20
    id: subnet-00198165a03be7cc9
    name: us-east-1f
    type: Private
    zone: us-east-1f
  - cidr: 10.40.48.0/24
    id: subnet-0eaef57bade69baaa
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.40.80.0/24
    id: subnet-0e08ba1ce3cc211c0
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.40.176.0/24
    id: subnet-0c6f2d0af0a2f336f
    name: utility-us-east-1f
    type: Utility
    zone: us-east-1f
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  updatePolicy: external
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

- new worker nodes sucessfuly join the cluster
- the AWS EBS CSI Driver is installed using helm chart and not using kops. not sure if important, mentioning anyways.
- ssh into the new master node uncovered that the kube-apiserver was not starting due to failed connection to etcd
- etcdctl ran inside etcd-manager 'main' and 'events' container in the new node did not connect. in old (non rolled) master nodes it connects and is able to list member nodes. when ran from an old node's etcd-manager containers, all three etcd members show up in the etcd cluster members list with state started in both etcd clusters 'main' and 'events'.
- the /etc/hosts file inside of the new node etcd-manager containers has different content than in the old nodes - it has 5 ip addresses, one for the new node itself and two for each old  master nodes. it has one entry for each private ip of each network interface of the other two master nodes. the other two (non-rolled master nodes) that worked as expected had appended semicolon followed by a port number (???) in the ip address column in the /etc/hosts file. 
- I manually defined in AWS route53 the six dns A records for etcd-a.internal.test.com, etcd-b.internal.test.com,etcd-c.internal.test.com and etcd-events-a.internal.test.com etcd-events-b.internal.test.com etcd-events-c.internal.test.com. after this, the /etc/hosts file were changed by etcd-manager to having 3 entries - one for each of the master hosts - on all three master nodes etcd-manager containers (all 6 of them). at this point, etcdctl could connect to the etcd in the new node etcd-manager containers. 
- now the kube-apiserver got up but kubelet is complaining with the following errors in loop:

Apr 13 10:53:56 ip-10-40-37-192 kubelet[718]: I0413 10:53:56.922785     718 csi_plugin.go:1063] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-10-40-37-192.ec2.internal" is forbidden: User "system:node:ip-10-40-37-192" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node
Apr 13 10:53:56 ip-10-40-37-192 kubelet[718]: E0413 10:53:56.985725     718 kubelet.go:2422] "Error getting node" err="node \"ip-10-40-37-192.ec2.internal\" not found"

- due to the above error, I have noticed that the kubelet in the new node has --hostname-override parameter changed from ip-10-40-X-Y.ec2.internal (as it is on the older nodes) to the form without ec.internal ip-10-40-X-Y (where X and Y are concrete numbers of the ip address). I tried manually changing the unit file to have the hostname-override the same as the old one, but that did not have any effect so I reverted this change. 

the questions:
- how to avoid adding manually those dns entries and get etcd on the new node available for kube-apiserver to connect it? the entries will be removed on restart by protokube as it has --remove-dns-names flag with all the above names specified,
- how to get the new master node(s) rejoin the cluster?
