### ISSUE TITLE
AWS LBC 2.2 -> 2.4 tagging permission problems

### ISSUE THREAD

**Issue by argoyle** [kubernetes/kops#13563]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.21.4 and 1.23.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.11

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Created a new cluster using kOps 1.21.4 with AWS LBC using IRSA, deployed a small echo-server with an ingress and checked that it responded, updated the cluster using kOps 1.22.4 still using K8S 1.21.11.

**5. What happened after the commands executed?**
AWS LBC fails to add tags to loadbalancer, target groups, security groups, listeners and listener rules.

**6. What did you expect to happen?**
Tagging of resources to succeed and AWS LBC still functioning

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 2
  name: k8s.xxx
spec:
  additionalPolicies:
    master: '[{"Action":["acm:ListCertificates","acm:DescribeCertificate"],"Effect":"Allow","Resource":"*"},{"Action":["s3:GetObject"],"Effect":"Allow","Resource":["arn:aws:s3:::72490225xxxx-eu-north-1-kops-storage/k8s.xxx-addons/*"]}]'
  addons:
  - manifest: s3://72490225xxxx-eu-north-1-kops-storage/k8s.xxx-addons/addon.yaml
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
    managed: true
  channel: stable
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: false
  configBase: s3://72490225xxxx-eu-north-1-kops-storage/k8s.xxx
  dnsZone: xxx
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-north-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-north-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-north-1c
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-north-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-north-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-north-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    serviceAccountExternalPermissions:
    - aws:
        inlinePolicy: |2
              [
                {
                  "Effect": "Allow",
                  "Action": [
                    "route53:ChangeResourceRecordSets"
                  ],
                  "Resource": [
                    "arn:aws:route53:::hostedzone/*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "route53:ListHostedZones",
                    "route53:ListResourceRecordSets"
                  ],
                  "Resource": [
                    "*"
                  ]
                }
              ]
      name: external-dns
      namespace: kube-system
    - aws:
        inlinePolicy: |2
              [
                {
                  "Effect": "Allow",
                  "Action": [
                    "secretsmanager:GetRandomPassword",
                    "secretsmanager:GetResourcePolicy",
                    "secretsmanager:GetSecretValue",
                    "secretsmanager:DescribeSecret",
                    "secretsmanager:ListSecretVersionIds",
                    "secretsmanager:ListSecrets"
                  ],
                  "Resource": "*"
                }
              ]
      name: kubernetes-external-secrets
      namespace: kube-system
    useServiceAccountExternalPermissions: true
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.11
  masterPublicName: api.k8s.xxx
  metricsServer:
    enabled: true
    insecure: false
  networkCIDR: 172.20.0.0/16
  networkID: vpc-0b65dcbe6fefa08d8
  networking:
    calico: {}
  nodeTerminationHandler:
    enableRebalanceDraining: true
    enableRebalanceMonitoring: true
    enableSQSTerminationDraining: true
    enableSpotInterruptionDraining: false
    enabled: true
    managedASGTag: aws-node-termination-handler/managed
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://k8s-xxx-irsa-issuer
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.0.0/19
    id: subnet-0f1dd4f9aee870b6e
    name: utility-eu-north-1a
    type: Utility
    zone: eu-north-1a
  - cidr: 172.20.32.0/19
    id: subnet-06b1f5443a3b808b4
    name: utility-eu-north-1b
    type: Utility
    zone: eu-north-1b
  - cidr: 172.20.64.0/19
    id: subnet-0b156b5df12cdad7b
    name: utility-eu-north-1c
    type: Utility
    zone: eu-north-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-03-29T04:29:45Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: k8s.xxx
  name: master-eu-north-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  machineType: t3.medium
  maxPrice: "0.03"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1a
  role: Master
  subnets:
  - utility-eu-north-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-03-29T04:29:45Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: k8s.xxx
  name: master-eu-north-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  machineType: t3.medium
  maxPrice: "0.03"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1b
  role: Master
  subnets:
  - utility-eu-north-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-03-29T04:29:45Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: k8s.xxx
  name: master-eu-north-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  machineType: t3.medium
  maxPrice: "0.03"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1c
  role: Master
  subnets:
  - utility-eu-north-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-03-29T04:29:45Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: k8s.xxx
  name: nodes-a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/k8s.xxx: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  machineType: t3.medium
  maxPrice: "0.03"
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-a
  role: Node
  subnets:
  - utility-eu-north-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-03-29T04:29:45Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: k8s.xxx
  name: nodes-b
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/k8s.xxx: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  machineType: t3.medium
  maxPrice: "0.03"
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-b
  role: Node
  subnets:
  - utility-eu-north-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-03-29T04:29:45Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: k8s.xxx
  name: nodes-c
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/k8s.xxx: "true"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220308
  machineType: t3.medium
  maxPrice: "0.03"
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-c
  role: Node
  subnets:
  - utility-eu-north-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Creating a fresh cluster using 1.23.1 works perfectly and running the following script before upgrading works as well:
```shell
#!/usr/bin/env bash

CLUSTER="$1"
REGION=${2:-$AWS_REGION}

function has_tag() {
  arn=$1
  aws elbv2 --region "${REGION}" describe-tags --resource-arns "$arn" --output text --query 'TagDescriptions[*].Tags[*].[Key,Value]' | grep -Ec "elbv2.k8s.aws/cluster\s+${CLUSTER}"
}

LBS=$(aws elbv2 --region "${REGION}" describe-load-balancers --query 'LoadBalancers[*].LoadBalancerArn' --output text)

for arn in ${LBS}; do
  count=$(has_tag "$arn")
  if [ "$count" -eq 1 ]; then
    aws elbv2 --region "${REGION}" add-tags --resource-arns "$arn" --tags "Key=KubernetesCluster,Value=${CLUSTER}"
  fi

  tgs=$(aws elbv2 --region "${REGION}" describe-target-groups --load-balancer-arn "$arn" --output text --query 'TargetGroups[*].TargetGroupArn')
  for tg in ${tgs}; do
    count=$(has_tag "$tg")
    if [ "$count" -eq 1 ]; then
      aws elbv2 --region "${REGION}" add-tags --resource-arns "$tg" --tags "Key=KubernetesCluster,Value=${CLUSTER}"
    fi
  done

  listeners=$(aws elbv2 --region "${REGION}" describe-listeners --load-balancer-arn "$arn" --output text --query 'Listeners[*].ListenerArn')
  for listener in ${listeners}; do
    count=$(has_tag "$listener")
    if [ "$count" -eq 1 ]; then
      aws elbv2 --region "${REGION}" add-tags --resource-arns "$listener" --tags "Key=KubernetesCluster,Value=${CLUSTER}"
    fi

    rules=$(aws elbv2 --region "${REGION}" describe-rules --listener-arn "$listener" --output text --query 'Rules[*].RuleArn')
    for rule in ${rules}; do
      count=$(has_tag "$rule")
      if [ "$count" -eq 1 ]; then
        aws elbv2 --region "${REGION}" add-tags --resource-arns "$rule" --tags "Key=KubernetesCluster,Value=${CLUSTER}"
      fi
    done
  done
done

sgs=$(aws ec2 describe-security-groups --region "${REGION}" --filter "Name=tag:elbv2.k8s.aws/cluster,Values=${CLUSTER}" --output text --query 'SecurityGroups[*].GroupId')
for sg in $sgs; do
  aws ec2 --region "$REGION" create-tags --resources "$sg" --tags "Key=KubernetesCluster,Value=${CLUSTER}"
done
```
