### ISSUE TITLE
grpc: addrConn.createTransport failed to connect to {127.0.0.1:4001 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...

### ISSUE THREAD

**Issue by bhavesh0124** [kubernetes/kops#13657]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.23.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
aws s3 mb s3://test4.k8s.local 
export KOPS_STATE_STORE=s3://test4.k8s.local 
sudo kops create cluster --name=test4.k8s.local --zones=us-east-2b --node-count=2 --node-size=t2.micro --networking calico
sudo kops get cluster 
sudo kops update cluster test4.k8s.local  --yes --admin
sudo kops rolling-update cluster test4.k8s.local  --yes 

When i was going to the elb ip address using sudo kubectl cluster-info: 

I was getting unauthorized error with code 401,

Then i did ssh in master server and went to "sudo cat /var/log/kube-apiserver.log | grep fail"

**5. What happened after the commands executed?**
Then i see this error, and im not able to access the kubernetes dashboard, it gives unauthorized error

**6. What did you expect to happen?**
I expect to see the kubernetes dashboard through the cluster-info address but i get unauthorized error

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```



apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-05-16T18:16:38Z"
  name: test4.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://test4.k8s.local/test4.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.6
  masterPublicName: api.test4.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-05-16T18:16:38Z"
  labels:
    kops.k8s.io/cluster: test4.k8s.local
  name: master-us-east-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220404
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2b
  role: Master
  subnets:
  - us-east-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-05-16T18:16:38Z"
  labels:
    kops.k8s.io/cluster: test4.k8s.local
  name: nodes-us-east-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220404
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.micro
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-2b
  role: Node
  subnets:
  - us-east-2b


```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
