### ISSUE TITLE
I am using kops to provision cluster, few of the master as well as nodes are going into 'NotReady' state

### ISSUE THREAD

**Issue by Pra9jha** [kubernetes/kops#13668]
1.What kops version are you running? The command kops version, will display
this information.
Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)

2. What Kubernetes version are you running? kubectl version will print the
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What is cluster configuration ? kops edit cluster cluster.dev print 
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-05-19T04:31:08Z"
  name: cluster.dev
spec:
  api:
    loadBalancer:
      class: Classic
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Project: dev-engagedly-infra
    owner: Devops
  cloudProvider: aws
  configBase: s3://kops/cluster.devtest
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-west-2a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-west-2b-2
      name: b-2
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-west-2a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-west-2b-2
      name: b-2
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.6
  masterInternalName: api.internal.cluster.dev
  masterPublicName: api.cluster.dev
  networkCIDR: 172.31.0.0/16
  networkID: vpc-38df6940
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.31.64.0/24
    id: subnet-{value}
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.31.48.0/20
    id: subnet-5ce4c917768945
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 172.31.16.0/20
    id: subnet-{value}
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 172.31.120.0/24
    id: subnet-{value}
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

I have also tried with different instance type and different instance size. 
once I login to the Instance with NotReady state and run "sudo service kubelet restart" it goes into ready state.
