### ISSUE TITLE
Cilium configuration for host routing as BPF 

### ISSUE THREAD

**Issue by arunporwal** [kubernetes/kops#13725]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I have just used `kops create cluster` with cilium below config.
```
kubeProxy:
    enabled: false
  networking:
    cilium:
      enableNodePort: true
      etcdManaged: true
      hubble:
        enabled: true
```

**5. What happened after the commands executed?**
it created the cluster but according to doc there is no option for setting `host routing` to BPF. it is using host routing as `Legacy`.

**6. What did you expect to happen?**
There must be some configuration to support that feature. as it will improve lots of performance. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-05-24T07:19:44Z"
  name: stage.nonprod.tools.kops
spec:
  api:
    loadBalancer:
      class: Classic
      crossZoneLoadBalancing: true
      type: Internal
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: false
    disableSecurityGroupIngress: true
    elbSecurityGroup: sg-******
    manageStorageClasses: true
  cloudLabels:
    BillingTeam: tools
    BusinessUnit: saas
    Env: stage    
    SlackGroup: tools-alerts
    Team: tools
  cloudProvider: aws
  clusterAutoscaler:
    awsUseStaticInstanceList: false
    balanceSimilarNodeGroups: false
    cpuRequest: 100m
    enabled: true
    expander: least-waste
    image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.2
    maxNodeProvisionTime: 15m0s
    memoryRequest: 300Mi
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUtilizationThreshold: "0.5"
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  clusterDNSDomain: cluster.local
  configBase: s3://bucket/stage.nonprod.tools.kops
  configStore: s3://bucket/stage.nonprod.tools.kops
  containerRuntime: containerd
  containerd:
    logLevel: info
    version: 1.4.12
  dnsZone: Z10340711M28ODEIB9YON
  docker:
    skipInstall: true
  etcdClusters:
  - backups:
      backupStore: s3://bucket/stage.nonprod.tools.kops/backups/etcd/main
    cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: stage-us-east-1a
      name: a
      volumeSize: 30
      volumeType: gp3
    - encryptedVolume: true
      instanceGroup: stage-us-east-1b
      name: b
      volumeSize: 30
      volumeType: gp3
    - encryptedVolume: true
      instanceGroup: stage-us-east-1c
      name: c
      volumeSize: 30
      volumeType: gp3
    memoryRequest: 100Mi
    name: main
    version: 3.4.13
  - backups:
      backupStore: s3://bucket/stage.nonprod.tools.kops/backups/etcd/events
    cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: stage-us-east-1a
      name: a
      volumeSize: 30
      volumeType: gp3
    - encryptedVolume: true
      instanceGroup: stage-us-east-1b
      name: b
      volumeSize: 30
      volumeType: gp3
    - encryptedVolume: true
      instanceGroup: stage-us-east-1c
      name: c
      volumeSize: 30
      volumeType: gp3
    memoryRequest: 100Mi
    name: events
    version: 3.4.13
  - backups:
      backupStore: s3://bucket/stage.nonprod.tools.kops/backups/etcd/cilium
    cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: stage-us-east-1a
      name: a
      volumeSize: 30
      volumeType: gp3
    - encryptedVolume: true
      instanceGroup: stage-us-east-1b
      name: b
      volumeSize: 30
      volumeType: gp3
    - encryptedVolume: true
      instanceGroup: stage-us-east-1c
      name: c
      volumeSize: 30
      volumeType: gp3
    manager:
      env:
      - name: ETCD_AUTO_COMPACTION_MODE
        value: revision
      - name: ETCD_AUTO_COMPACTION_RETENTION
        value: "2500"
    memoryRequest: 100Mi
    name: cilium
    version: 3.4.13
  externalDns:
    provider: dns-controller
  externalPolicies:
    node:
    - arn:aws:iam::*****:policy/somepolicy
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://bucket/stage.nonprod.tools.kops/pki
  kubeAPIServer:
    allowPrivileged: true
    anonymousAuth: false
    apiAudiences:
    - kubernetes.svc.default
    apiServerCount: 3
    authorizationMode: Node,RBAC
    bindAddress: 0.0.0.0
    cloudProvider: aws
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    etcdServers:
    - https://127.0.0.1:4001
    etcdServersOverrides:
    - /events#https://127.0.0.1:4002
    image: k8s.gcr.io/kube-apiserver:v1.21.4
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceAccountIssuer: https://api.internal.stage.nonprod.tools.kops
    serviceAccountJWKSURI: https://api.internal.stage.nonprod.tools.kops/openid/v1/jwks
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd3
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: stage.nonprod.tools.kops
    configureCloudRoutes: false
    image: k8s.gcr.io/kube-controller-manager:v1.21.4
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    cacheMaxConcurrent: 150
    cacheMaxSize: 1000
    cpuRequest: 100m
    domain: cluster.local
    memoryLimit: 170Mi
    memoryRequest: 70Mi
    nodeLocalDNS:
      cpuRequest: 25m
      enabled: false
      image: k8s.gcr.io/dns/k8s-dns-node-cache:1.21.3
      memoryRequest: 5Mi
    provider: CoreDNS
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    enabled: false
    image: k8s.gcr.io/kube-proxy:v1.21.4
    logLevel: 2
    metricsBindAddress: 0.0.0.0
  kubeScheduler:
    image: k8s.gcr.io/kube-scheduler:v1.21.4
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupDriver: systemd
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: k8s.gcr.io/pause:3.6
    podManifestPath: /etc/kubernetes/manifests
    shutdownGracePeriod: 30s
    shutdownGracePeriodCriticalPods: 10s
  kubernetesApiAccess:
  - 172.18.72.0/22
  kubernetesVersion: 1.21.4
  masterInternalName: api.internal.stage.nonprod.tools.kops
  masterKubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupDriver: systemd
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: k8s.gcr.io/pause:3.6
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
    shutdownGracePeriod: 30s
    shutdownGracePeriodCriticalPods: 10s
  masterPublicName: api.stage.nonprod.tools.kops
  metricsServer:
    enabled: true
    insecure: false
  networkCIDR: 172.18.72.0/22
  networkID: vpc-071fe9cfddac275d3
  networking:
    cilium:
      agentPrometheusPort: 9090
      bpfCTGlobalAnyMax: 262144
      bpfCTGlobalTCPMax: 524288
      bpfLBAlgorithm: random
      bpfLBMaglevTableSize: "16381"
      bpfLBMapMax: 65536
      bpfNATGlobalMax: 524288
      bpfNeighGlobalMax: 524288
      bpfPolicyMapMax: 16384
      clusterName: default
      cpuRequest: 25m
      disableCNPStatusUpdates: true
      disableMasquerade: false
      enableBPFMasquerade: false
      enableEndpointHealthChecking: true
      enableL7Proxy: true
      enableNodePort: true
      enableRemoteNodeIdentity: true
      etcdManaged: true
      hubble:
        enabled: true
      identityAllocationMode: crd
      identityChangeGracePeriod: 5s
      ipam: kubernetes
      memoryRequest: 128Mi
      monitorAggregation: medium
      sidecarIstioProxyImage: cilium/istio_proxy
      toFqdnsDnsRejectResponseCode: refused
      tunnel: vxlan
      version: v1.10.5
  nodeTerminationHandler:
    cpuRequest: 50m
    enableRebalanceDraining: false
    enableRebalanceMonitoring: false
    enableSQSTerminationDraining: true
    enableScheduledEventDraining: false
    enableSpotInterruptionDraining: true
    enabled: true
    managedASGTag: aws-node-termination-handler/managed
    memoryRequest: 64Mi
    prometheusEnable: false
  nonMasqueradeCIDR: 100.64.0.0/10
  podCIDR: 100.96.0.0/11
  secretStore: s3://bucket/stage.nonprod.tools.kops/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
  - 172.18.72.0/22
  sshKeyName: ******
  subnets:
  - cidr: 172.18.72.64/26
    egress: nat-******
    id: subnet-*********
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.18.73.64/26
    egress: nat-******
    id: subnet-*********
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.18.74.64/26
    egress: nat-*******
    id: subnet-*********
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.18.72.0/26
    id: subnet-*********
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.18.73.0/26
    id: subnet-*********
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.18.74.0/26
    id: subnet-*********
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
https://docs.cilium.io/en/v1.11/operations/performance/tuning/#ebpf-host-routing
https://docs.cilium.io/en/stable/concepts/networking/routing/#native-routing
it will require few options as 
```
auto-direct-node-routes: true
tunnel: disabled: Enable native routing mode.
ipv4-native-routing-cidr: x.x.x.x/y: Set the CIDR in which native routing can be performed.
```
