### ISSUE TITLE
Kops 1.23.* runc hash is not right inside nodeup

### ISSUE THREAD

**Issue by adityanmishra** [kubernetes/kops#13746]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.23.1 and 1.23.2
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.23.7
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops rolling-update --yes
**5. What happened after the commands executed?**
We run kops where there is no internet access. We are able to run kops without any problem till 1.22.5 version
when a new master comes up i see below error
Jun 07 15:21:42 ip-10-****.ec2.internal nodeup[3095]: I0607 15:21:42.325709    3095 assetstore.go:340] added asset "runc" for &{"/var/cache/nodeup/extracted/sha256:a64568c8ce792dd73859ce5f336d5485fcbceab15dc3e06d5d1bc1c3353fa20f_cri-containerd-cni-1_6_6-linux-amd64_tar_gz/usr/local/sbin/runc"}
Jun 07 15:21:42 ip-10-***.ec2.internal nodeup[3095]: I0607 15:21:42.325769    3095 files.go:136] Hash did not match for "/var/cache/nodeup/sha256:ab1c67fbcbdddbe481e48a55cf0ef9a86b38b166b5079e0010737fd87d7454bb_runc_amd64": actual=sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 vs expected=sha256:ab1c67fbcbdddbe481e48a55cf0ef9a86b38b166b5079e0010737fd87d7454bb
Jun 07 15:21:42 ip-10-****.ec2.internal nodeup[3095]: I0607 15:21:42.325820    3095 http.go:82] Downloading "https://github.com/opencontainers/runc/releases/download/v1.1.0/runc.amd64"
**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-06-06T14:17:43Z"
  generation: 5
  name: testkops.k8s.local
spec:
  api:
    loadBalancer:
      class: Network
      type: Internal
  assets:
    containerProxy: ***
  authorization:
    rbac: {}
  channel: https://***/stable
  cloudLabels:
    ClusterName: testkops.k8s.local
    Department: ****
    NonStop: "True"
    Platform: ****
  cloudProvider: aws
  configBase: s3://****/testkops.k8s.local
  containerRuntime: containerd
  containerd:
    packages:
      hashAmd64: a64568c8ce792dd73859ce5f336d5485fcbceab15dc3e06d5d1bc1c3353fa20f
      urlAmd64: https://****/containerd/v1.6.6/cri-containerd-cni-1.6.6-linux-amd64.tar.gz
    registryMirrors:
      '*':
      - https://****
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-2
      name: a-2
    manager:
      env:
      - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
        value: 3d
      - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
        value: 7d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: master-us-east-1a-2
      name: a-2
    memoryRequest: 100Mi
    name: events
  fileAssets:
  - content: "apiVersion: audit.k8s.io/v1\nkind: Policy\nrules:\n- level: RequestResponse\n
      \ resources:\n  - group: \"\"\n    resources: [\"deployments\"]\n- level: Request\n
      \ resources:\n  - group: \"\"\n    resources: [\"configmaps\"]\n  namespaces:
      [\"kube-system\"]\n- level: Metadata\n  resources:\n  - group: \"\"\n    resources:
      [\"configmaps\", \"secrets\"] \n"
    name: audit-policy-config
    path: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - AlwaysPullImages
    - NodeRestriction
    auditLogMaxAge: 5
    auditLogMaxBackups: 2
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    enableProfiling: false
    oidcClientID: kubernetes-client
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'oidc:'
    oidcIssuerURL: https://*****/auth/realms/master
    oidcUsernameClaim: preferred_username
    oidcUsernamePrefix: 'oidc:'
  kubeControllerManager:
    clusterCIDR: 172.21.128.0/17
    enableProfiling: false
    terminatedPodGCThreshold: 5
  kubeDNS:
    coreDNSImage: ****/coredns/coredns:v1.9.1
    memoryLimit: 2Gi
    provider: CoreDNS
  kubeProxy:
    clusterCIDR: 172.21.128.0/17
  kubeScheduler:
    enableProfiling: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    eventQPS: 0
    protectKernelDefaults: true
    readOnlyPort: 0
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: https://*****/repository/kubernetes-releases/release/v1.23.7
  masterInternalName: api.internal.testkops.k8s.local
  masterPublicName: api.testkops.k8s.local
  networkCIDR: ****24
  networkID: vpc-****
  networking:
    calico:
      awsSrcDstCheck: Disable
      crossSubnet: true
      encapsulationMode: ipip
      typhaReplicas: 3
  nonMasqueradeCIDR: 172.21.0.0/16
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: ****
  subnets:
  - cidr: ****/25
    id: subnet-*****
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: **/25
    id: subnet-**
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: *****/25
    id: subnet-**
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: ****/25
    id: subnet-****
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Our kops cluster runs in offline mode without any internet access
