### ISSUE TITLE
Calico CNI failure. Master fails to join cluster.

### ISSUE THREAD

**Issue by ctrl-man** [kubernetes/kops#13944]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.22.5

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops rolling-update cluster --state s3://clusters.name.io (Updated kops from version 1.21.2 to 1.22.5)

kops rolling-update cluster --state s3://clusters.name.io --instance-group master-us-west-2a --yes (The first master upgraded kops ok)

kops rolling-update cluster --state s3://clusters.name.io --instance-group master-us-west-2b --yes (Rolling the second master resulted in the master not rejoining the cluster.)

There is a 3rd master that has not been updated yet.

**5. What happened after the commands executed?**
The master-us-west-2b node did not rejoin the cluster.  

ssh into a working master
```
crictl ps -a
CONTAINER           IMAGE               CREATED             STATE               NAME                           ATTEMPT             POD ID
3cc5bf6d22f3f       77a8908a12e35       22 hours ago        Running             liveness-probe                 0                   b5b7b755d03fe
cf04e5d9ff6ed       ef2b13b2a0667       22 hours ago        Running             node-driver-registrar          0                   b5b7b755d03fe
1bc2c3d001024       6abafd7e83b9a       22 hours ago        Running             node-problem-detector          0                   de6d331e369db
0e86790f93b2f       bc055a5c628ad       22 hours ago        Running             ebs-plugin                     0                   b5b7b755d03fe
71d5acb14605e       1ebc24a702ef9       22 hours ago        Running             kiam-server                    0                   e4b1c1a7a67f8
03ac98a4cff02       2fdf74cb537cc       22 hours ago        Running             calico-node                    0                   38c419ba9c9ee
5d92f2aaa00e4       56f85e4b8ef56       22 hours ago        Running             aws-iam-authenticator          0                   ed300f05b8c6e
322a0084163af       983ee5a079409       22 hours ago        Exited              flexvol-driver                 0                   38c419ba9c9ee
3c522b1efbee3       685a73a3c754b       22 hours ago        Running             kube-rbac-proxy                0                   6a2656afb0dd7
3e59385b834bc       4169446d1ad7e       22 hours ago        Running             aws-node-termination-handler   0                   d5ce99f53db08
9d41ac250b7e0       4f12f1ddc0228       22 hours ago        Running             kops-controller                0                   61178dff2396d
d756101e37400       73dc08b04b58c       22 hours ago        Exited              install-cni                    0                   38c419ba9c9ee
2af79856a010a       73dc08b04b58c       22 hours ago        Exited              upgrade-ipam                   0                   38c419ba9c9ee
03432261c1b33       8aeab82543463       22 hours ago        Running             node-cache                     0                   a5c08fa68d595
7cdf0685fcb6b       1dbe0e9319764       22 hours ago        Running             node-exporter                  0                   6a2656afb0dd7
5e27896719333       63fab16fc008c       22 hours ago        Running             filebeat                       0                   2747dd99076c1
a8026637e2020       eeb3ff9374071       22 hours ago        Running             kube-controller-manager        1                   b6f3676d253db
14d2313e389c9       bc19ae37473ed       22 hours ago        Running             healthcheck                    0                   be05fb4b5dec9
2518d6eb720c2       eeb3ff9374071       22 hours ago        Exited              kube-controller-manager        0                   b6f3676d253db
905f4ca179ca8       ab8993ba3211b       22 hours ago        Running             kube-proxy                     0                   c15757bcedab6
764898eec7444       f57d734dc1007       22 hours ago        Running             etcd-manager                   0                   e5e30c4589457
97488d479d46f       f57d734dc1007       22 hours ago        Running             etcd-manager                   0                   ca159d1014a6c
9468c1accb546       2f776f4731317       22 hours ago        Running             kube-scheduler                 0                   a9560ca73e098
a6241f9338853       704b64a9bcd2f       22 hours ago        Running             kube-apiserver                 0                   be05fb4b5dec9
```
ssh into the broken master:
```
crictl ps -a
CONTAINER           IMAGE               CREATED              STATE               NAME                      ATTEMPT             POD ID
85675d9972622       eeb3ff9374071       About a minute ago   Exited              kube-controller-manager   42                  78d827edca4f0
64c99d739c970       704b64a9bcd2f       5 minutes ago        Exited              kube-apiserver            39                  cfc32618101cf
9383a79f5abd5       bc19ae37473ed       About an hour ago    Running             healthcheck               0                   cfc32618101cf
987681e472f59       f57d734dc1007       About an hour ago    Running             etcd-manager              0                   85e50b517eebd
545a74598b98a       ab8993ba3211b       About an hour ago    Running             kube-proxy                0                   96d7ed2db0626
fddf7ba80d4ac       f57d734dc1007       About an hour ago    Running             etcd-manager              0                   38610b7677de3
4270507df05bc       2f776f4731317       About an hour ago    Running             kube-scheduler            0                   8de02464e2b37
```
install-cni and calico-node containers not running on the broken master.
/etc/cni/net.d is empty
Missing /opt/cni/bin/calico and /opt/cni/bin/calico-ipam

```
journalctl -u containerd.service  | grep CRI
Jul 04 22:26:19 ip-10-1-90-185 containerd[6790]: time="2022-07-04T22:26:19.366687657Z" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
```

At this point, below is the output from kops rolling-update cluster --state s3://clusters.name.io
```
NAME			STATUS		NEEDUPDATE	READY	MIN	TARGET	MAX	NODES
master-us-west-2a	Ready		0		1	1	1	1	1
master-us-west-2b	Ready		0		1	1	1	1	0
master-us-west-2c	NeedsUpdate	1		0	1	1	1	1
```

**6. What did you expect to happen?**
Expected master-us-west-2b to join successfully like master-us-west-2a

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: us-west-2.prod.name.io
spec:
  api:
    loadBalancer:
      additionalSecurityGroups:
      - sg-079e986bbfb4c9c46
      class: Network
      crossZoneLoadBalancing: true
      idleTimeoutSeconds: 600
      sslCertificate: arn:aws:acm:us-west-2:000000000000:certificate/6c795b4d-acf1-4068-bff4-6ddc8236dc91
      type: Internal
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.name.io/us-west-2.prod.name.io
  etcdClusters:
  - cpuRequest: 600m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: main
    volumeSize: 20
  - cpuRequest: 400m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
    volumeSize: 20
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta2: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubeDNS:
    nodeLocalDNS:
      cpuRequest: 25m
      enabled: true
      memoryRequest: 5Mi
    provider: CoreDNS
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesVersion: 1.21.10
  masterPublicName: api.us-west-2.prod.name.io
  networkCIDR: 10.1.0.0/16
  networkID: vpc-0d0283e5e6848c7ca
  networking:
    calico:
      majorVersion: v3
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - id: subnet-0e093db37e663355c
    name: public-production-a
    type: Utility
    zone: us-west-2a
  - id: subnet-02a5992d86c7cc4ae
    name: public-production-b
    type: Utility
    zone: us-west-2b
  - id: subnet-02e757a485ffc5286
    name: public-production-c
    type: Utility
    zone: us-west-2c
  - id: subnet-05f8bbbc4448f876f
    name: private-production-a
    type: Private
    zone: us-west-2a
  - id: subnet-00f5a18e2f7acef7d
    name: private-production-b
    type: Private
    zone: us-west-2b
  - id: subnet-0caa36c96a888dcc4
    name: private-production-c
    type: Private
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: master-us-west-2a
spec:
  additionalSecurityGroups:
  - sg-03c003ae3cb226f32
  cloudLabels:
    name:app: kubernetes
    name:component: master
    name:env: production
    name:instance: production
    name:team: infrastructure
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private-production-a
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: master-us-west-2b
spec:
  additionalSecurityGroups:
  - sg-03c003ae3cb226f32
  cloudLabels:
    name:app: kubernetes
    name:component: master
    name:env: production
    name:instance: production
    name:team: infrastructure
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private-production-b
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: master-us-west-2c
spec:
  additionalSecurityGroups:
  - sg-03c003ae3cb226f32
  cloudLabels:
    name:app: kubernetes
    name:component: master
    name:env: production
    name:instance: production
    name:team: infrastructure
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private-production-c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: development
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.2xlarge
  maxSize: 50
  minSize: 5
  role: Node
  subnets:
  - private-production-a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-datasci
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name.io/team: datasci
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: data
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.4xlarge
  maxSize: 5
  minSize: 0
  nodeLabels:
    kubernetes.io/role: datasci
    node.name.io/role: datasci
  role: Node
  rootVolumeSize: 200
  rootVolumeType: gp2
  subnets:
  - private-production-a
  taints:
  - node.name.io/role=datasci:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-datasci-large
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name.io/team: datasci
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: data
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.8xlarge
  maxSize: 3
  minSize: 0
  nodeLabels:
    kubernetes.io/role: datasci-large
    node.name.io/role: datasci-large
  role: Node
  rootVolumeSize: 200
  rootVolumeType: gp2
  subnets:
  - private-production-a
  taints:
  - node.name.io/role=datasci-large:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-datasci-metal
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name.io/team: datasci
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: data
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: c5.metal
  maxSize: 3
  minSize: 0
  nodeLabels:
    kubernetes.io/role: datasci-metal
    node.name.io/role: datasci-metal
  role: Node
  rootVolumeSize: 200
  rootVolumeType: gp2
  subnets:
  - private-production-a
  taints:
  - node.name.io/role=datasci-metal:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-datasci-graphic
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name.io/team: datasci
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: data
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: p2.xlarge
  maxSize: 3
  minSize: 0
  nodeLabels:
    kubernetes.io/role: datasci-graphic
    node.name.io/role: datasci-graphic
  role: Node
  rootVolumeSize: 200
  rootVolumeType: gp2
  subnets:
  - private-production-a
  taints:
  - node.name.io/role=datasci-graphic:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: ci-node
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: development
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  maxSize: 5
  minSize: 3
  mixedInstancesPolicy:
    instances:
    - t3.2xlarge
    - c5a.2xlarge
    - m5a.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    kubernetes.io/role: ci-node
    node.name.io/role: ci-node
  role: Node
  subnets:
  - private-production-a
  taints:
  - node.name.io/role=ci-node:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-multi
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: development
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5.2xlarge
  maxSize: 10
  minSize: 3
  nodeLabels:
    kubernetes.io/role: multi
    node.name.io/role: multi
  role: Node
  subnets:
  - private-production-a
  - private-production-b
  - private-production-c
  taints:
  - node.name.io/role=multi:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-eck-single
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: development
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5a.2xlarge
  maxSize: 50
  minSize: 3
  nodeLabels:
    kubernetes.io/role: eck-single
    node.name.io/role: eck-single
  role: Node
  subnets:
  - private-production-a
  suspendProcesses:
  - AZRebalance
  taints:
  - node.name.io/role=eck-single:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-eck-double
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: development
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  machineType: m5a.2xlarge
  maxSize: 30
  minSize: 3
  nodeLabels:
    kubernetes.io/role: eck-double
    node.name.io/role: eck-double
  role: Node
  subnets:
  - private-production-a
  - private-production-b
  suspendProcesses:
  - AZRebalance
  taints:
  - node.name.io/role=eck-double:NoSchedule
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: us-west-2.prod.name.io
  name: nodes-spot
spec:
  additionalSecurityGroups:
  - sg-0b30a884af7afabec
  - sg-000a7f540a0ce9bad
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/us-west-2.prod.name.io: ""
    name:app: kubernetes
    name:component: node
    name:env: production
    name:instance: production
    name:team: development
  externalLoadBalancers:
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/priv-prod-ingress-tg/a64f5868bce4fb6b
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-ingress-tg/dabe7c102c093fed
  - targetGroupArn: arn:aws:elasticloadbalancing:us-west-2:000000000000:targetgroup/pub-prod-high-timeout-ingress-tg/4724d2a55802b322
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  kubernetesVersion: 1.21.10
  maxSize: 30
  minSize: 0
  mixedInstancesPolicy:
    instances:
    - t3.2xlarge
    - c5.2xlarge
    - m5.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    kubernetes.io/role: spot
    node.name.io/role: spot
  role: Node
  subnets:
  - private-production-a
  taints:
  - node.name.io/role=spot:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
https://gitlab.com/-/snippets/2364856

**9. Anything else do we need to know?**
