### ISSUE TITLE
Pods not trusting kops kubernetes api certificate

### ISSUE THREAD

**Issue by clayrisser** [kubernetes/kops#13947]
/kind bug

Apps running in pods are unable to trust the kubernetes api certificate. Even a basic curl command fails to trust the certificate.

```sh
curl https://kubernetes.default
```

```
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
    1.23.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
   v1.21.12

**3. What cloud provider are you using?**
    AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
    ```
    curl https://kubernetes.default
    ```

**5. What happened after the commands executed?**

**6. What did you expect to happen?**
    I expected a response from the server

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-07-05T16:48:20Z"
  name: kops-0.k8s.risserlabs.com
spec:
  additionalPolicies: null
  api:
    dns: {}
  authentication:
    aws:
      backendMode: CRD
      clusterID: kops-0.k8s.risserlabs.com
      identityMappings:
      - arn: arn:aws:iam::972093907905:role/kops-0.k8s.risserlabs.com
        groups:
        - system:masters
        username: eks-internal
  authorization:
    alwaysAllow: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
    managed: true
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
    manageStorageClasses: true
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    expander: least-waste
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUtilizationThreshold: "0.5"
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  dnsZone: k8s.risserlabs.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-0
      name: master-0
    name: main
  - etcdMembers:
    - instanceGroup: master-0
      name: master-0
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    nodeLocalDNS:
      enabled: true
      forwardToKubeDNS: true
    provider: CoreDNS
  kubernetesVersion: v1.21.12
  masterPublicName: api.kops-0.k8s.risserlabs.com
  networkCIDR: 10.0.0.0/16
  networkID: vpc-081983cf92807511d
  networking:
    calico: {}
  nodeProblemDetector:
    enabled: true
  nodeTerminationHandler:
    enableSQSTerminationDraining: true
    enableSpotInterruptionDraining: true
    enabled: true
    managedASGTag: aws-node-termination-handler/managed
  nonMasqueradeCIDR: 100.64.0.0/10
  podIdentityWebhook:
    enabled: true
  snapshotController:
    enabled: true
  sshKeyName: nodes.kops-0.k8s.risserlabs.com
  subnets:
  - cidr: 10.0.0.0/19
    id: subnet-02abe164a69a56b9f
    name: subnet-02abe164a69a56b9f
    type: Private
    zone: us-east-2a
  - cidr: 10.0.32.0/19
    id: subnet-06ab66ec752ec1051
    name: subnet-06ab66ec752ec1051
    type: Private
    zone: us-east-2b
  - cidr: 10.0.64.0/19
    id: subnet-0b6bc8d0b57517fc1
    name: subnet-0b6bc8d0b57517fc1
    type: Private
    zone: us-east-2c
  - cidr: 10.0.224.0/19
    id: subnet-042080024f8199cf5
    name: subnet-042080024f8199cf5
    type: Public
    zone: us-east-2a
  - cidr: 10.0.192.0/19
    id: subnet-0c1efc5cd86bb9fe0
    name: subnet-0c1efc5cd86bb9fe0
    type: Public
    zone: us-east-2b
  - cidr: 10.0.160.0/19
    id: subnet-058f0d99e6fe6311b
    name: subnet-058f0d99e6fe6311b
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The kops cluster was created just fine and I can communicate with it fine. However some apps fail to communicate with the kubernetes api due to the fact that they are unable to trust the kubernetes api certificate. How do I configure kops so all the apps trust the kubernetes api certificate?
