### ISSUE TITLE
Upgrading kops from 1.22.5 to 1.23.2 results in Master nodes not joining the cluster

### ISSUE THREAD

**Issue by Vonmaterhorn** [kubernetes/kops#13999]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.23.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Version 1.23.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
````shell
kops update cluster --name ${CLUSTER_NAME} --yes
kops rolling-update cluster --instance-group-roles Master --yes --name ${CLUSTER_NAME}
````

**5. What happened after the commands executed?**
Master nodes begin being drained, first one is removed from cluster, but the replacement doesn't join.

**6. What did you expect to happen?**
Master nodes are replaced with new ones running the updated version, and join the cluster successfully. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: <cluster-name>
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": "ec2:DescribeTags",
          "Resource": "*"
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": ["arn:aws:iam::<AWS ID>:role/kube2iam/kube2iam-staging-*"]
        },
        {
          "Effect": "Allow",
          "Action": "ec2:CreateTags",
          "Resource": "arn:aws:ec2:*:*:volume/*"
        },
        {
          "Effect": "Allow",
          "Action": [
            "ec2:DescribeVolumes",
            "ec2:DescribeTags"
          ],
          "Resource": "*"
        }
      ]
  additionalSans:
  - SAN1
  - SAN2
  - SAN3
  api:
    loadBalancer:
      additionalSecurityGroups:
      - <REDACTED>
      class: Classic
      idleTimeoutSeconds: 1800
      type: Internal
  authorization:
    rbac: {}
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
  cloudLabels:
    salsify:environment: staging
    salsify:owner: devops
    salsify:platform: kubernetes
  cloudProvider: aws
  clusterAutoscaler:
    cpuRequest: 100m
    enabled: true
    memoryRequest: 512Mi
    scaleDownUtilizationThreshold: "0.3"
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: true
  configBase: s3://<BUCKET NAME>
  containerRuntime: containerd
  containerd:
    registryMirrors:
      docker.io:
      - https://mirror.gcr.io
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
      volumeSize: 100
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
      volumeSize: 100
    name: events
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/bin/bash -c <REDACTED>
    name: tag-ebs-voumes
    roles:
    - Node
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    <REDACTED>
  kubeDNS:
    coreDNSImage: coredns/coredns:1.8.6
    externalCoreFile: |
      (base) {
        prometheus :9153
        errors
        cache
        loop
        loadbalance round_robin
        reload
        log . {
          class error
        }
      }
      .:53 {
        import base
        autopath @kubernetes
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        forward . 8.8.8.8 8.8.4.4
      }
    nodeLocalDNS:
      cpuRequest: 25m
      enabled: true
      memoryRequest: 5Mi
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
  kubernetesApiAccess:
  - <REDACTED>
  kubernetesVersion: 1.23.8
  masterInternalName: <REDACTED>
  masterPublicName: <REDACTED>
  networkCIDR: 10.129.0.0/16
  networkID: <REDACTED>
  networking:
    canal: {}
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: <REDACTED>
  sshAccess:
  - <REDACTED>
  sshKeyName: <REDACTED>
  subnets:
  - cidr: 10.129.0.0/24
    id: <REDACTED>
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.129.16.0/24
    id: <REDACTED>
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.129.32.0/24
    id: <REDACTED>
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.129.48.0/24
    id: <REDACTED>
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.129.64.0/24
    id: <REDACTED>
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.129.80.0/24
    id: <REDACTED>
    name: us-east-1f
    type: Private
    zone: us-east-1f
  - cidr: 10.129.96.0/24
    id: <REDACTED>
    name: crawling-us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.129.112.0/24
    id: <REDACTED>
    name: crawling-us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.129.4.0/24
    id: <REDACTED>
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.129.20.0/24
    id: <REDACTED>
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.129.36.0/24
    id: <REDACTED>
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.129.52.0/24
    id: <REDACTED>
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 10.129.68.0/24
    id: <REDACTED>
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  - cidr: 10.129.84.0/24
    id: <REDACTED>
    name: utility-us-east-1f
    type: Utility
    zone: us-east-1f
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-11T09:21:22Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-1a
spec:
  additionalSecurityGroups:
  - <REDACTED>
  associatePublicIp: false
  cloudLabels:
    type: master
  image: <REDACTED>
  machineType: t3.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-11T09:21:22Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-1b
spec:
  additionalSecurityGroups:
  - <REDACTED>
  associatePublicIp: false
  cloudLabels:
    type: master
  image: <REDACTED>
  machineType: t3.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-11T09:21:22Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-east-1c
spec:
  additionalSecurityGroups:
  - <REDACTED>
  associatePublicIp: false
  cloudLabels:
    type: master
  image: <REDACTED>
  machineType: t3.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-07-11T09:21:23Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: standard-nodes
spec:
  additionalSecurityGroups:
  - <REDACTED>
  associatePublicIp: false
  image: <REDACTED>
  machineType: t3a.2xlarge
  maxPrice: "0.30"
  maxSize: 45
  minSize: 25
  role: Node
  rootVolumeIops: 4000
  rootVolumeSize: 500
  rootVolumeThroughput: 250
  rootVolumeType: gp3
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1f
  suspendProcesses:
  - AZRebalance
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
````shell
 rolling-update cluster --instance-group-roles Master --yes --name ${CLUSTER_NAME}
(...)
I0705 05:18:56.116222     212 instancegroups.go:467] Validating the cluster.
I0705 05:18:57.375133     212 instancegroups.go:500] Cluster validated.
(...)
I0705 05:34:01.398444     212 instancegroups.go:523] Cluster did not pass validation, will retry in "30s": machine "<instanceID>" has not yet joined cluster.
I0705 05:34:32.597765     212 instancegroups.go:520] Cluster did not pass validation within deadline: machine "<instanceID>" has not yet joined cluster.
E0705 05:34:32.597794     212 instancegroups.go:472] Cluster did not validate within 15m0s
````
Node logs display these errors:
````shell
Jul  6 11:19:41 ip-10-129-0-111 kubelet[7143]: I0706 11:19:41.710288    7143 csi_plugin.go:1063] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-10-129-0-111.ec2.internal" is forbidden: User "system:node:<InstanceID>" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node
Jul  6 11:19:43 ip-10-129-0-111 kubelet[7143]: I0706 11:19:43.041091    7143 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-129-0-111.ec2.internal"
Jul  6 11:19:43 ip-10-129-0-111 kubelet[7143]: E0706 11:19:43.053146    7143 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes \"ip-10-129-0-111.ec2.internal\" is forbidden: node \"<InstanceID>\" is not allowed to modify node \"ip-10-129-0-111.ec2.internal\"" node="ip-10-129-0-111.ec2.internal"
Jul  6 11:19:43 ip-10-129-0-111 kubelet[7143]: E0706 11:19:43.128541    7143 kubelet.go:2466] "Error getting node" err="node \"ip-10-129-0-111.ec2.internal\" not found"
````

**9. Anything else do we need to know?**
This happened on a staging cluster, where we test our upgrade paths. Cluster went from 1.21 to 1.22 no problem, but going from 1.22 to 1.23 produced the errors described.
After testing in an isolated environment, from a freshly created kops cluster running 1.22.5, a similar manifest was used to successfully upgrade to 1.23.2.

We've tested some other suggestions, such as specifying `spec.cloudControllerManager.cloudProvider: aws`, which worked on the staging cluster (where this was first tested), but failed in a second staging cluster (in the same circumstances).

The only difference between the clusters that failed and the one that succeeded, is that the successful one was brand new, built from scratch for testing purposes.
