### ISSUE TITLE
Calico 1.23 (kops 1.24) failure

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#14068]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
v1.24.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.24.3
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
n/a see below
**5. What happened after the commands executed?**
Calico nodes continuously restart
**6. What did you expect to happen?**
Calico to properly stay up
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 1
  name: << Redact >>
spec:
  # Redacting all but networking since I think this is just a calico regression
  networking:
    calico:
      crossSubnet: true
      prometheusGoMetricsEnabled: true
      prometheusMetricsEnabled: true
      prometheusProcessMetricsEnabled: true
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
We run into the same errors as https://github.com/projectcalico/calico/issues/6442 
**9. Anything else do we need to know?**

This was not reproducable when spinning up a new cluster in kops 1.24 or upgrading a kops 1.23 cluster to 1.24, however when upgrading a cluster from 1.21->1.22->1.23->1.24 this was reproduced.

We were able to resolve it adding the following value to the `default-ipv4-ippool` `ippools.crd.projectcalico.org` object:
```
vxlanMode: Never
```
It was not populated on older cluster but on newer cluster this had already been populated.

For now, we're going to hard code calico version as v3.22.4 which seems to work on kops 1.24 but I just wanted to post this as a reference if anyone else runs into it.
