### ISSUE TITLE
Cluster config nvidiaGPU specify image

### ISSUE THREAD

**Issue by cabal-daniel** [kubernetes/kops#14103]
I'm not sure if this is already implemented but I can't find anything in the docs or grepping through the repo.

I'm wondering if we can specify the `nvidia-device-plugin` image in the kops config option
```
  containerd:
    nvidiaGPU:
      enabled: true
```

via something like
```
  containerd:
    nvidiaGPU:
      enabled: true
      image: docker.io/nvidia/k8s-device-plugin:v0.12.0
```

The current most up-to-date master branch kops deploys `docker.io/nvidia/k8s-device-plugin:v0.10.0` which is kind of out-of-date and doesn't support the latest CUDA. Does this option exist? Thank you for your time.
