### ISSUE TITLE
EBS CSI Controller timeout connecting to K8S API after 1.23 -> 1.24 upgrade

### ISSUE THREAD

**Issue by zhming0** [kubernetes/kops#14126]
/kind bug

**1. What `kops` version are you running?**
`1.24.1`

**2. What Kubernetes version are you running?**

Client Version: v1.24.3
Server Version: v1.24.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Just a very typical major version bump process.
* I Set the AMI image to latest Ubunto image `ubuntu-jammy-22.04-amd64-server-20220810`.
* Set k8s version to latest: 1.24.3 via the config file. 
```
kops replace -f cluster.yaml
kops update cluster k8s.xxxxxx.com --yes
kops rolling-update cluster --yes
```

**5. What happened after the commands executed?**

Failed on the first admin node replacement process, due to both ebs-csi-node and ebs-csi-controller being crashlooping.
The error on these pods are both: 

`panic: error getting Node i-0f31cfb110bcXXXX: Get "https://100.64.0.1:443/api/v1/nodes/i-0f31cfb110bceXXXX": dial tcp 100.64.0.1:443: i/o timeout`

**6. What did you expect to happen?**

CSI Node and CSI Controller both working normal as before.

**7. Please provide your cluster manifest.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: k8s.xxxxxx.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  containerRuntime: containerd # It was Docker but it was deprecated.
  configBase: s3://xxxxxxxx
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:8081
      - name: ETCD_METRICS
        value: basic
      - name: ETCD_MANAGER_HOURLY_BACKUPS_RETENTION
        value: 7d
      - name: ETCD_MANAGER_DAILY_BACKUPS_RETENTION
        value: 30d
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    # These are for metrics-server to work
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubeProxy:
    # Default is 172.xx.xx.xx which is too strict causing prometheus to get Connection refused
    metricsBindAddress: 0.0.0.0
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.24.3
  masterPublicName: api.k8s.xxxxxxxx.com
  networkCIDR: 172.20.0.0/16
  networking:
    cilium: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

# Master IG

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s.xxxxxxx.com
  name: master-us-west-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220810
  machineType: t3.medium
  rootVolumeSize: 20
  rootVolumeType: gp3
  maxPrice: "0.02"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

# Bastion IG
# only used as reverse proxy purpose

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s.xxxxxxx.com
  name: spot-bastion
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220810
  machineType: t3a.micro
  maxSize: 1
  minSize: 1
  maxPrice: "0.0050"
  rootVolumeSize: 20
  rootVolumeType: gp3
  # A hand-mand SG for proxy's because I want traffic to reach
  # this IG directly
  securityGroupOverride: sg-00ad060b54f99744e
  nodeLabels:
    kops.k8s.io/instancegroup: spot-bastion
    bastion: "true"
  taints:
  # Unless a pod telerate bastion=true, it's unlikely to be scheduled here
  - bastion=true:PreferNoSchedule
  role: Node
  subnets:
  - us-west-2a

---

# Main IG for worker

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s.xxxxxx.com
  name: spot-ig
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220810
  machineType: t3a.medium
  maxSize: 3
  minSize: 3
  maxPrice: "0.02"
  rootVolumeSize: 20
  rootVolumeType: gp3
  nodeLabels:
    kops.k8s.io/instancegroup: spot-ig
  role: Node
  subnets:
  - us-west-2a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

* When I view the pods on the master node, I notice the failing pods all have different IP pattern. 

<img width="289" alt="Screen Shot 2022-08-14 at 10 58 31 pm" src="https://user-images.githubusercontent.com/1054703/184538058-2555ff82-faad-4da7-b07d-9315bfa75872.png">

* All CSI Node pods that are sitting in 1.23 nodes are working fine. 
* I have been running kops/kubernetes combo since 1.17 and I upgraded through every major version changes. This is the only time where I feel I am truly stuck.
