### ISSUE TITLE
duration parser fails for certain values in validation

### ISSUE THREAD

**Issue by kilpatty** [kubernetes/kops#14128]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.24.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.24.3

**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit cluster --name ${NAME}
**5. What happened after the commands executed?**
Kops failed to validate cluster configuration

**6. What did you expect to happen?**
The cluster configuration would save normally.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Using the snippets from here: https://kops.sigs.k8s.io/cluster_spec/#compute-resources-reservation and here: https://kops.sigs.k8s.io/cluster_spec/#compute-resources-reservation
```yaml
  kubelet:
    anonymousAuth: false
    enableCustomMetrics: true
    enforceNodeAllocatable: pods,system-reserved,kube-reserved
    kubeReserved:
      cpu: "1"
      ephemeral-storage: 1Gi
      memory: 2Gi
    kubeReservedCgroup: /kube-reserved
    shutdownGracePeriod: 60s
    systemReservedCgroup: /system-reserved

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
can't get past saving so don't have this. 
**9. Anything else do we need to know?**

When I try to save a metav1.Duration with values such as "60s" or "1m" it fails to validate the duration and will pull in other fields and declare them invalid. E.g. Here is the output when I use `shutdownGracePeriod: 60s`

```
# Found fields that are not recognized
# ...
#         memory: 2Gi
#       kubeReservedCgroup: /kube-reserved
# +     shutdownGracePeriod: 60s
# -     shutdownGracePeriod: 1m0s
#       systemReservedCgroup: /system-reserved
#     kubernetesApiAccess:
# ...
```

I get similar output if I set shutdownGracePeriod to `1m` without the `0s` suffix. 

This is more just an issue that occasionally "invalid" durations are found in the documentation e.g. https://kops.sigs.k8s.io/cluster_spec/#graceful-node-shutdown which had me quite confused for awhile since 60s seems like a valid duration.

I am happy to submit some PRs to the documentation to fix these just let me know if that is the path you want to take!
