### ISSUE TITLE
dns-controller: tries to add CNAME and A records for ingress resources

### ISSUE THREAD

**Issue by pingles** [kubernetes/kops#1413]
We see lots of Route 53 errors when the controller attempts to queue both CNAME and A records for ingress resources. We're using both dns-controller and nginx ingress controller on AWS.

For example, if we have an Ingress resource defined as `logs.usw.co` the resource status is updated with both hostname and ip values:

```yaml
status:
  loadBalancer:
    ingress:
    - hostname: foo-1234.eu-west-1.elb.amazonaws.com
    - ip: 172.20.10.67
```

As dns-controller runs it'll attempt to set both [CNAME](https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/watchers/ingresscontroller.go#L141) and [A](https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/watchers/ingresscontroller.go#L148) records.

I've no idea whether the expectation is that ingress resources would only ever have `IP` _or_ `Hostname` specified but it may be worth changing the conditional to prefer CNAME if specified?
