### ISSUE TITLE
Rolling update cannot drain master

### ISSUE THREAD

**Issue by atze234** [kubernetes/kops#14172]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.24.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.24.3

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops rolling-update cluster --name=xxx --state=s3://xxx --instance-group-roles master --force --yes`
**5. What happened after the commands executed?**
When doing a rolling update targeting my single-master cluster kops is `Deregistering instance from classic loadBalancers´ for the api. After that kops is trying to drain the master node, but cannot do that because its getting timeout to the api then. 
For me this was introduced with kops 1.24.1. It worked well till kops v1.23. I cannot remember i saw that "Deregistering" before. 
Example:
```
kops rolling-update cluster --name=xxx --state=s3://xxx --instance-group-roles master --force --yes
[...]
I0824 11:27:04.545647    4448 instancegroups.go:470] Validating the cluster.
I0824 11:27:05.618936    4448 instancegroups.go:503] Cluster validated.
I0824 11:27:05.618956    4448 instancegroups.go:311] Tainting 1 node in "master-eu-central-1a" instancegroup.
I0824 11:27:05.669012    4448 instancegroups.go:400] Draining the node: "i-0a8427353bc67b3a7".
I0824 11:27:05.808965    4448 aws_cloud.go:624] Deregistering instance from classic loadBalancers: [api-xxx-3p1grq]
[...wait 2 minutes...]
Error: master not healthy after update, stopping rolling-update: "failed to drain node \"i-0a8427353bc67b3a7\": error draining node: Get \"https://api.xxx/api/v1/pods?fieldSelector=spec.nodeName%3Di-0a8427353bc67b3a7\": EOF"
```

**6. What did you expect to happen?**
Rolling Update of master node
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-01-04T09:09:20Z"
  generation: 27
  name: <redacted>
spec:
  api:
    loadBalancer:
      class: Classic
      idleTimeoutSeconds: 3600
      type: Internal
  authentication:
    aws:
      backendMode: EKSConfigMap
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    <redacted>
  cloudProvider: aws
  configBase: s3://<redacted>/<redacted>
  dnsZone: <redacted>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit.conf
  kubeDNS:
    nodeLocalDNS:
      cpuRequest: 25m
      enabled: true
      memoryRequest: 5Mi
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.24.3
  masterInternalName: api.internal.<redacted>
  masterPublicName: api.<redacted>
  networkCIDR: <redacted>
  networkID: <redacted>
  networking:
    calico:
      ipv4AutoDetectionMethod: can-reach=<redacted>
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - <redacted>
  subnets:
  - cidr: <redacted>
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: <redacted>
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: <redacted>
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: <redacted>
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
  updatePolicy: external

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-01-04T09:39:59Z"
  generation: 26
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-eu-central-1a
spec:
  cloudLabels:
    <redacted>
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220615
  machineType: m5.large
  maxPrice: "0.20"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c5.large
    - m5.large
    - c4.large
    - m4.large
    onDemandAboveBase: 0
    onDemandBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

```

As a workaround i have to terminate the master node manually and then everything works fine.
