### ISSUE TITLE
nodeup config hash mismatch (was x, expected y)

### ISSUE THREAD

**Issue by defaultbr** [kubernetes/kops#14249]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Client version: 1.24.2 (git-v1.24.2)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-18T02:29:34Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster --name k8s-ohio --config cluster.yml --state=s3://kops-state --yes`

**5. What happened after the commands executed?**

```
Instances are unable to sync with the kops state 

 nodeup[1292]: I0908 22:15:40.496768    1292 s3fs.go:329] Reading file "s3://kops-state/k8s-ohiocluster-completed.spec"

nodeup[1292]: I0908 22:15:40.511743    1292 s3fs.go:329] Reading file "s3://kops-state/k8s-ohio/igconfig/node/nodes-general/nodeupconfig.yaml"

nodeup[1292]: W0908 22:15:40.527898    1292 main.go:133] got error running nodeup (will retry in 30s): nodeup config hash mismatch (was "soJZjzaL3uTQz2mhuA5v9xQsE5wrlIbpRp0o+kjpCFw=", expected "IZPaCZRvIpKms2Tc0GtqhWgtJxqi0BcSSAvx7m99z6g=")
systemd[1]: Starting Cleanup of Temporary Directories...
systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
```

**6. What did you expect to happen?**

Instances up and no error about hash mismatch

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s-ohio
spec:
  containerd:
    version: 1.6.6
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig: {}
  cloudProvider: aws
  configBase: s3://kops-state/k8s-ohio
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://k8s-ohio-iam
    enableAWSOIDCProvider: true
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: ***
    oidcIssuerURL: ***
    oidcUsernameClaim: email
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.7
  masterPublicName: api.k8s-ohio***
  networkCIDR: ***
  networkID: vpc-07fe340
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: ....
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
    ....
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
  hooks:
  - name: node-exporter
    roles:
    - Node
    - Master
    before:
    - kubelet.service
    manifest: |
      ...

```
