### ISSUE TITLE
kops 1.25, updating clusters does not work if ig has taints

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#14285]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

commit https://github.com/kubernetes/kops/commit/ce73a5b830d625122e12fa8bd40bfeeaae348581 from release-1.25

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.25.1

**3. What cloud provider are you using?**

openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops edit cluster --set=spec.kubernetesVersion=1.25.1
kops update cluster --yes
kops rolling-update cluster --yes
```

**5. What happened after the commands executed?**

the ig spec before command executed

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-10T08:29:37Z"
  generation: 9
  labels:
    kops.k8s.io/cluster: sre-ci.k8s.local
  name: e2etest
spec:
  cloudLabels:
    kopsGroupName: e2etest
  image: ubuntu-2004-200622-devops
  machineType: m1.large
  manager: CloudGroup
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: e2etest
  role: Node
  subnets:
  - espsti
  - esptnl
  - helpa
  taints:
  - e2etest:NoSchedule
```

after

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-10T08:29:37Z"
  generation: 10
  labels:
    kops.k8s.io/cluster: sre-ci.k8s.local
  name: e2etest
spec:
  cloudLabels:
    kopsGroupName: e2etest
  image: ubuntu-2004-010922-devops
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    evictionHard: memory.available<5%,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionMinimumReclaim: nodefs.available=1Gi,imagefs.available=2Gi
    nodeLabels:
      kops.k8s.io/instancegroup: e2etest
      node-role.kubernetes.io/node: ""
    systemReserved:
      memory: 512Mi
    taints:
    - e2etest:NoSchedule
  machineType: m1.large
  manager: CloudGroup
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: e2etest
  role: Node
  subnets:
  - espsti
  - esptnl
  - helpa
  taints:
  - e2etest:NoSchedule
```

However, because ig now contains taints twice it leads to situation that this does not work. When e2etest instance starts again the result is that its not coming online.

The error from machine log:

```
Sep 17 04:37:15 e2etest-8jyglf kubelet[101939]: E0917 04:37:15.627003  101939 run.go:74] "command failed" err="failed to parse kubelet flag: invalid argument \"e2etest:NoSchedule,e2etest:NoSchedule\" for \"--register-with-taints\" flag: duplicated taints with the same key and effect: {e2etest  NoSchedule <nil>}"
```
