### ISSUE TITLE
IPv6: Unable to create internal loadbalancer for Service in cluster with public topology

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/kops#14451]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.26.0-alpha.1 (git-v1.26.0-alpha.1-137-g21ac145028)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.23.0

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Created IPv6 cluster with public topology.

Deployed the following:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: tls-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
spec:
  selector:
    app: tls-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-app
  template:
    metadata:
      labels:
        app: tls-app
        product: cloud15
        team: cloud15
    spec:
      containers:
        - name: tls-app
          image: gcr.io/k8s-staging-ingressconformance/echoserver:v20220815-e21d1a4
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
```

**5. What happened after the commands executed?**

AWS LBC created an NLB, but the NLB got stuck in "Provisioning" state.

**6. What did you expect to happen?**

AWS LBC creates working load balancer.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Related to kubernetes-sigs/aws-load-balancer-controller#2848

The NLB failed to complete provisioning because it was a dual-stack non-internet-facing NLB created in a Subnet with IPv6 ingress from the public internet.

I think in IPv6 public topology we might need to create a set of "dualstack-utility" subnets for internal load balancers. These would have no ingress from the Internet, would be dual-stack, and would not be used for nodes.
