### ISSUE TITLE
Could we have a single master instance group in multiple AZs?

### ISSUE THREAD

**Issue by rokka-n** [kubernetes/kops#1448]
I'd like to create a cluster with 3 master nodes and 3 workers in **existing** vpc with existing private subnets. All nodes, master and workers should be in the same subnet. The reason? It's not reusing NATgateways as far as I can see, so the first cluster provisioning going to hit all the sort of aws limits.

Is it possible to do with current version?

Also, what's the reason 3 ASG being created?
Actually 4! 1 per master plus one for 3 workers. Makes no sense.

**Comment by rokka-n** [comment]
```
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
And yet it creates a public loadbalancer for master :(
