### ISSUE TITLE
NTH Deployment is not exposing Prometheus metrics

### ISSUE THREAD

**Issue by guusvw** [kubernetes/kops#14490]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.24.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5", GitCommit:"e979822c185a14537054f15808a118d7fcce1d6e", GitTreeState:"clean", BuildDate:"2022-09-14T16:35:41Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

* Node Termination Handler is installed
* NTH Deployment didn't set the ENV `ENABLE_PROMETHEUS_SERVER` to `"true"`

**6. What did you expect to happen?**

* `ENABLE_PROMETHEUS_SERVER` is set to `"true"`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: cluster.trip.***.io
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
  cloudControllerManager:
    cloudProvider: aws
  cloudLabels:
    Environment: poc
    Owner: Trip
  cloudProvider: aws
  configBase: s3://k8s.trip.***.io/cluster.trip.***.io
  containerRuntime: containerd
  dnsZone: trip.poc.moia-group.io
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 640Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 192Mi
    name: events
  fileAssets:
  - content: |
      ---
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        # The following requests were manually identified as high-volume and low-risk,
        # so drop them.
        - level: None
          resources:
            - group: ""
              resources:
                - endpoints
                - services
                - services/status
          users:
            - 'system:kube-proxy'
          verbs:
            - watch

        - level: None
          resources:
            - group: ""
              resources:
                - nodes
                - nodes/status
          userGroups:
            - 'system:nodes'
          verbs:
            - get

        - level: None
          namespaces:
            - kube-system
          resources:
            - group: ""
              resources:
                - endpoints
          users:
            - 'system:kube-controller-manager'
            - 'system:kube-scheduler'
            - 'system:serviceaccount:kube-system:endpoint-controller'
          verbs:
            - get
            - update

        - level: None
          resources:
            - group: ""
              resources:
                - namespaces
                - namespaces/status
                - namespaces/finalize
          users:
            - 'system:apiserver'
          verbs:
            - get

        # Don't log HPA fetching metrics.
        - level: None
          resources:
            - group: metrics.k8s.io
          users:
            - 'system:kube-controller-manager'
          verbs:
            - get
            - list

        # Don't log these read-only URLs.
        - level: None
          nonResourceURLs:
            - '/healthz*'
            - /version
            - '/swagger*'

        # Don't log events requests.
        - level: None
          resources:
            - group: ""
              resources:
                - events

        # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
        - level: Request
          omitStages:
            - RequestReceived
          resources:
            - group: ""
              resources:
                - nodes/status
                - pods/status
          users:
            - kubelet
            - 'system:node-problem-detector'
            - 'system:serviceaccount:kube-system:node-problem-detector'
          verbs:
            - update
            - patch

        - level: Request
          omitStages:
            - RequestReceived
          resources:
            - group: ""
              resources:
                - nodes/status
                - pods/status
          userGroups:
            - 'system:nodes'
          verbs:
            - update
            - patch

        # deletecollection calls can be large, don't log responses for expected namespace deletions
        - level: Request
          omitStages:
            - RequestReceived
          users:
            - 'system:serviceaccount:kube-system:namespace-controller'
          verbs:
            - deletecollection

        # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
        # so only log at the Metadata level.
        - level: Metadata
          omitStages:
            - RequestReceived
          resources:
            - group: ""
              resources:
                - secrets
                - configmaps
            - group: authentication.k8s.io
              resources:
                - tokenreviews
        # Get repsonses can be large; skip them.
        - level: Request
          omitStages:
            - RequestReceived
          resources:
            - group: ""
            - group: admissionregistration.k8s.io
            - group: apiextensions.k8s.io
            - group: apiregistration.k8s.io
            - group: apps
            - group: authentication.k8s.io
            - group: authorization.k8s.io
            - group: autoscaling
            - group: batch
            - group: certificates.k8s.io
            - group: extensions
            - group: metrics.k8s.io
            - group: networking.k8s.io
            - group: policy
            - group: rbac.authorization.k8s.io
            - group: scheduling.k8s.io
            - group: settings.k8s.io
            - group: storage.k8s.io
          verbs:
            - get
            - list
            - watch

        # Default level for known APIs
        - level: RequestResponse
          omitStages:
            - RequestReceived
          resources:
            - group: ""
            - group: admissionregistration.k8s.io
            - group: apiextensions.k8s.io
            - group: apiregistration.k8s.io
            - group: apps
            - group: authentication.k8s.io
            - group: authorization.k8s.io
            - group: autoscaling
            - group: batch
            - group: certificates.k8s.io
            - group: extensions
            - group: metrics.k8s.io
            - group: networking.k8s.io
            - group: policy
            - group: rbac.authorization.k8s.io
            - group: scheduling.k8s.io
            - group: settings.k8s.io
            - group: storage.k8s.io

        # Default level for all other requests.
        - level: Metadata
          omitStages:
            - RequestReceived
    name: kubernetes-audit
    path: /srv/kubernetes/kube-apiserver/audit.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
    apiAudiences:
    - api
    - istio-ca
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit.yaml
    disableBasicAuth: true
    enableProfiling: false
    featureGates:
      EphemeralContainers: "true"
    oidcClientID: ***
    oidcGroupsClaim: groups
    oidcIssuerURL: https://***.okta.com
    oidcUsernameClaim: email
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountJWKSURI: https://kubernetes.default.svc/openid/v1/jwks
  kubeControllerManager:
    enableProfiling: false
    featureGates:
      InTreePluginAWSUnregister: "true"
    horizontalPodAutoscalerDownscaleStabilization: 10m0s
  kubeDNS:
    coreDNSImage: coredns/coredns:1.8.3
    provider: CoreDNS
  kubeScheduler:
    enableProfiling: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    clientCaFile: /srv/kubernetes/ca.crt
    featureGates:
      EphemeralContainers: "true"
      InTreePluginAWSUnregister: "true"
    kubeReserved:
      cpu: 100m
      memory: 1024Mi
    protectKernelDefaults: true
    readOnlyPort: 0
    systemReserved:
      cpu: 100m
      memory: 1024Mi
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.24.5
  masterInternalName: api.internal.cluster.trip.***.io
  masterPublicName: api.cluster.trip.***.io
  networkCIDR: 172.20.0.0/16
  networking:
    canal: {}
  nodeTerminationHandler:
    cpuRequest: 50m
    enableRebalanceMonitoring: true
    enableSQSTerminationDraining: true
    enabled: true
    prometheusEnable: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 255.255.255.255/32
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.20.96.0/19
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.20.0.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.20.4.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.20.8.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  sysctlParameters:
  - vm.overcommit_memory=1
  - kernel.panic=10
  - kernel.panic_on_oops=1
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-02T15:27:27Z"
  labels:
    kops.k8s.io/cluster: cluster.trip.***.io
  name: e2e-test
spec:
  additionalUserData:
  - content: |
      package_update: true
      packages: auditd
    name: auditd
    type: text/cloud-config
  image: ***/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220901
    moia-1662975122-encrypted
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m5a.large
  maxSize: 2
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: e2e-test
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-02T15:27:26Z"
  labels:
    kops.k8s.io/cluster: cluster.trip.***.io
  name: master-eu-central-1a
spec:
  additionalUserData:
  - content: |
      package_update: true
      packages: auditd
    name: auditd
    type: text/cloud-config
  image: ***/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220901
    moia-1662975122-encrypted
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-02T15:27:26Z"
  labels:
    kops.k8s.io/cluster: cluster.trip.***.io
  name: master-eu-central-1b
spec:
  additionalUserData:
  - content: |
      package_update: true
      packages: auditd
    name: auditd
    type: text/cloud-config
  image: ***/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220901
    moia-1662975122-encrypted
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-02T15:27:27Z"
  labels:
    kops.k8s.io/cluster: cluster.trip.***.io
  name: master-eu-central-1c
spec:
  additionalUserData:
  - content: |
      package_update: true
      packages: auditd
    name: auditd
    type: text/cloud-config
  image: ***/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220901
    moia-1662975122-encrypted
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-02T15:27:27Z"
  labels:
    kops.k8s.io/cluster: cluster.trip.***.io
  name: nodes
spec:
  additionalUserData:
  - content: |
      package_update: true
      packages: auditd
    name: auditd
    type: text/cloud-config
  image: ***/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220901
    moia-1662975122-encrypted
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m5a.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rollingUpdate:
    maxSurge: 1
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-02T15:27:27Z"
  labels:
    kops.k8s.io/cluster: cluster.trip.***.io
  name: spot
spec:
  additionalUserData:
  - content: |
      package_update: true
      packages: auditd
    name: auditd
    type: text/cloud-config
  image: ***/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220901
    moia-1662975122-encrypted
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m5a.2xlarge
  maxPrice: "0.46"
  maxSize: 6
  minSize: 3
  mixedInstancesPolicy:
    instances:
    - m6i.2xlarge
    - m5a.2xlarge
    - m5.2xlarge
    - m4.2xlarge
    - t3.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 15
  nodeLabels:
    kops.k8s.io/instancegroup: spot
  role: Node
  rollingUpdate:
    maxSurge: 1
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Short story, we installed NTH via the kOps addon, enabled the Prometheus in the cluster config, seems to work in the rendered cluster spec but not got rendered into the k8s manifest and still setting the ENV `ENABLE_PROMETHEUS_SERVER` to `"false"`, which should be `"true"` (and also works, if we set it manually to `"true"`).
