### ISSUE TITLE
Unable to run kubelet due to etcd failure after the kops update cluster to latest

### ISSUE THREAD

**Issue by Amithpn** [kubernetes/kops#14523]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.25

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.22

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster
kops update cluster --yes

**5. What happened after the commands executed?**
Unable to run the kubectl commands.
ubuntu@i-0faf30beb7dfe1a18:~$ kubectl get nodes
The connection to the server 127.0.0.1 was refused - did you specify the right host or port?
ubuntu@i-0faf30beb7dfe1a18:~$

I see in one of the master the kubelet is unable to start due to error in running etcd cluster. Etcd is failing to start afger the upgrade from v2.2.1 to 3.x.x

**6. What did you expect to happen?**
kubectl commands should work

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
kops get --name uswest2b.testing.server.com -o yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-08-09T20:22:55Z"
  generation: 7
  name: uswest2b.testing.server.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://
  dnsZone: 
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.0
  masterInternalName: api.internal.uswest2b.testing.server.com
  masterPublicName: api.uswest2b.testing.server.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-09T20:22:55Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: uswest2b.testing.server.com
  name: master-us-west-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220924
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-09T20:22:55Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: uswest2b.testing.server.com
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220924
  machineType: m4.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2b

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

2022-11-10 07:27:59.732094 I | etcdmain: etcd Version: 2.2.1
2022-11-10 07:27:59.732098 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2022-11-10 07:27:59.732102 I | etcdmain: Go Version: go1.15.7
2022-11-10 07:27:59.732106 I | etcdmain: Go OS/Arch: linux/amd64
2022-11-10 07:27:59.732110 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2022-11-10 07:27:59.732167 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2022-11-10 07:27:59.732495 I | etcdmain: peerTLS: cert = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/peers/me.crt, key = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/peers/me.key, ca = , trusted-ca = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/peers/ca.crt, client-cert-auth = true
2022-11-10 07:27:59.732506 W | etcdmain: The scheme of peer url http://0.0.0.0:2380 is http while peer key/cert files are presented. Ignored peer key/cert files.
2022-11-10 07:27:59.732690 I | etcdmain: listening for peers on http://0.0.0.0:2380
2022-11-10 07:27:59.732709 I | etcdmain: clientTLS: cert = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/clients/server.crt, key = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/clients/server.key, ca = , trusted-ca = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/clients/ca.crt, client-cert-auth = true
2022-11-10 07:27:59.732985 I | etcdmain: listening for client requests on https://0.0.0.0:4001
2022-11-10 07:27:59.733093 I | etcdmain: stopping listening for client requests on https://0.0.0.0:4001
2022-11-10 07:27:59.733104 I | etcdmain: stopping listening for peers on http://0.0.0.0:2380
2022-11-10 07:27:59.733110 C | etcdmain: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given urls
I1110 07:27:59.775220    7833 controller.go:395] spec member_count:1 etcd_version:"3.4.13"
I1110 07:27:59.775439    7833 controller.go:443] mismatched version for peer peer{id:"etcd-b" endpoints:"172.20.63.229:3996" }: want "3.4.13", have "2.2.1"
I1110 07:27:59.775483    7833 controller.go:449] can't do in-place upgrade from "2.2.1" -> "3.4.13"
I1110 07:27:59.775530    7833 commands.go:41] refreshing commands
I1110 07:27:59.884496    7833 vfs.go:120] listed commands in s3://clusters.demo.scene.iot.nokia.com/uswest2b.demo.scene.iot.nokia.com/backups/etcd/main/control: 0 commands
I1110 07:27:59.884527    7833 s3fs.go:290] Reading file "s3://uswest2b.testing.server.com/backups/etcd/main/control/etcd-cluster-spec"
W1110 07:27:59.892198    7833 controller.go:165] **unexpected error running etcd cluster reconciliation loop: etcd has 0 members registered; must issue restore-backup command to proceed**

**9. Anything else do we need to know?**
I see error in the etcd.log:
`
2022-11-10 07:27:59.732094 I | etcdmain: etcd Version: 2.2.1
2022-11-10 07:27:59.732098 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2022-11-10 07:27:59.732102 I | etcdmain: Go Version: go1.15.7
2022-11-10 07:27:59.732106 I | etcdmain: Go OS/Arch: linux/amd64
2022-11-10 07:27:59.732110 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2022-11-10 07:27:59.732167 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2022-11-10 07:27:59.732495 I | etcdmain: peerTLS: cert = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/peers/me.crt, key = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/peers/me.key, ca = , trusted-ca = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/peers/ca.crt, client-cert-auth = true
2022-11-10 07:27:59.732506 W | etcdmain: The scheme of peer url http://0.0.0.0:2380 is http while peer key/cert files are presented. Ignored peer key/cert files.
2022-11-10 07:27:59.732690 I | etcdmain: listening for peers on http://0.0.0.0:2380
2022-11-10 07:27:59.732709 I | etcdmain: clientTLS: cert = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/clients/server.crt, key = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/clients/server.key, ca = , trusted-ca = /rootfs/mnt/master-vol-0d34f4a9906528017/pki/etcd-cluster-token-etcd/clients/ca.crt, client-cert-auth = true
2022-11-10 07:27:59.732985 I | etcdmain: listening for client requests on https://0.0.0.0:4001
2022-11-10 07:27:59.733093 I | etcdmain: stopping listening for client requests on https://0.0.0.0:4001
2022-11-10 07:27:59.733104 I | etcdmain: stopping listening for peers on http://0.0.0.0:2380
2022-11-10 07:27:59.733110 C | etcdmain: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given urls
I1110 07:27:59.775220    7833 controller.go:395] spec member_count:1 etcd_version:"3.4.13"
I1110 07:27:59.775439    7833 controller.go:443] mismatched version for peer peer{id:"etcd-b" endpoints:"172.20.63.229:3996" }: want "3.4.13", have "2.2.1"
I1110 07:27:59.775483    7833 controller.go:449] can't do in-place upgrade from "2.2.1" -> "3.4.13"
I1110 07:27:59.775530    7833 commands.go:41] refreshing commands
I1110 07:27:59.884496    7833 vfs.go:120] listed commands in s3://clusters.demo.scene.iot.nokia.com/uswest2b.demo.scene.iot.nokia.com/backups/etcd/main/control: 0 commands
I1110 07:27:59.884527    7833 s3fs.go:290] Reading file "s3://uswest2b.testing.server.com/backups/etcd/main/control/etcd-cluster-spec"
W1110 07:27:59.892198    7833 controller.go:165] **unexpected error running etcd cluster reconciliation loop: etcd has 0 members registered; must issue restore-backup command to proceed**

`

Can someone please help resolve this issue as im trying the same from past few days without any success
