### ISSUE TITLE
AWS: Unable to SSH into cluster created with shared private subnet

### ISSUE THREAD

**Issue by gopinatht** [kubernetes/kops#1476]
We cannot access the nodes or the master created in a shared VPC with pre-existing private subnet because the security groups for the master and nodes do not support port 22. Here is what my config looks like

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2017-01-14T00:10:01Z"
  name: <URL>
spec:
  api:
    loadBalancer:
      type: Internal
  channel: alpha
  cloudProvider: aws
  configBase: s3://S3STORE/S3NAME
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: us-east-1e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: us-east-1e
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.5.1
  masterInternalName: api.internal.<URL>
  masterPublicName: api.<URL>
  networkCIDR: 10.44.76.0/23
  networkID: vpc-xxxxxxxx
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.44.76.0/25
    id: subnet-xxxxxxxx
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.44.76.0/25
    id: subnet-xxxxxxxx
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

I spoke to @justinsb on slack and he suggested that I open an issue so here it is.
