### ISSUE TITLE
AWS: Need ability to specify subnet for kubernetes master ELB

### ISSUE THREAD

**Issue by gopinatht** [kubernetes/kops#1477]
When we create a cluster, in a VPC with a mix of private and public subnets, we would like to be able to setup the cluster in the private subnet (we can do this now) while being able to create the ELB fir the master in the public subnet (we cannot do this). T

here is no way right now to specify the subnet for the ELBs.

I briefly discussed this with @justinsb and he suggested that I log a bug.

**Comment by kris-nova** [comment]
Is this different than the hybrid topology we have discussed with masters in a public subnet, and nodes in a private subnet?

**Comment by gopinatht** [comment]
@kris-nova In my case, the master and minions are in private subnet. Only the ELBs (potentially) and Bastion servers are in public subnet

**Comment by kris-nova** [comment]
@gopinatht 

So we want an ELB going from the outside to the master subnet, even though the only thing in the master subnet(s) are the bastion servers? Sorry, just want to make sure I am understanding what we are going for here. This isn't impossible, I just want to be clear what we are talking about designing is all.

**Comment by justinsb** [comment]
Also, when I do:

`kops create cluster -topology private --bastion ...`

I get...

* masters with no public IPs in a private subnet
* nodes with no public IPs in a private subnet
* bastion with no public IPs in a private subnet
* An ELB for the API, in the public subnet
* An ELB for the bastions, in the public subnet

When we talked on slack it sounded like this wasn't working though?  Can you clarify what is different from what you want?

What we _can't_ do right now is set up an ELB in a private subnet, I think.

**Comment by gopinatht** [comment]
@justinsb Are you using a shared VPC with a shared private (for master and minions) and shared public subnets (for bastion and master ELB)? Here is what my command looks like right now: 

`${KOPSPATH}/kops create --v=8 cluster --channel "alpha" --topology private --image ami-6d1c2007 --vpc vpc-cb311faf --network-cidr "10.44.76.0/23" --networking weave --bastion --ssh-public-key "~/.ssh/wops-dmgcloudsvc-nonprod.pub" --zones us-east-1e ${EXPNAME}`

This creates a master ELB that is internet facing but in my shared private subnet and that does not work. So, I either need a way to specify on the command line the type of master ELB (internal/internet-facing) or be able to specify the subnet in which the ELB is created as a public subnet so the ELB is accessible. For now, I just edit the config to manually change it to Internal for it to work. After all my edits my config looks like this:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2017-01-17T20:59:02Z"
  name: <URL>
spec:
  api:
    loadBalancer:
      type: Internal
  channel: alpha
  cloudProvider: aws
  configBase: s3://S3STORE/<URL>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: us-east-1e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: us-east-1e
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.5.2
  masterInternalName: k8smaster.internal.<URL>
  masterPublicName: k8smaster.<URL>
  networkCIDR: 10.44.76.0/23
  networkID: vpc-aaaaaaaa
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.44.76.0/25
    id: subnet-xxxxxxxx
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.44.77.128/26
    id: subnet-yyyyyyyy
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    bastion:
      bastionPublicName: bastion.<URL>
    dns:
      type: Public
    masters: private
    nodes: private
```

Please notice the subnet specifications. I use a pre-existing shared private subnet for `Private` and another public subnet for `Utility`.

The bottomline is that the subnets are not created for me by kops. I use pre-existing ones.

Hope this clarifies.
