### ISSUE TITLE
Enable cluster autoscaler metrics scraping via service monitor

### ISSUE THREAD

**Issue by Schmitze333** [kubernetes/kops#15065]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
The Kubernetes Cluster Autoscaler offers the possibility to scrape its metrics based on a service monitor. (see [here](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/servicemonitor.yaml))
However, when setting up cluster autoscaler with kOps, one has to provide an additional scrape config in order to get the metrics.
It would be handy to utilize a service monitor also via kOps.

**2. Feel free to provide a design supporting your feature request.**
Extend the `clusterAutoscaler` sections with an optional `serviceMonitor` section:
```yaml
spec:
  clusterAutoscaler:
    enabled: true   
    serviceMonitor:
      enabled: true
      namespace: monitoring
      scrapeInterval: 60s
```
`namespace` and `scrapeInterval` are reasonable options that one might possibly specify.
