### ISSUE TITLE
ig nodeLabels not passed to kubernetes nodes in OpenStack

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#15090]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

release-1.26

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.26.1

**3. What cloud provider are you using?**

openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

created cluster with instancegroup spec:

```
% kops get ig highmem-espsti -o yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-29T13:57:28Z"
  generation: 15
  labels:
    kops.k8s.io/cluster: sre-ci.k8s.local
  name: highmem-espsti
spec:
  cloudLabels:
    kopsGroupName: highmem-espsti
  image: ubuntu-2004-010123-devops
  machineType: m1.xlarge
  manager: CloudGroup
  maxSize: 4
  minSize: 4
  nodeLabels:
    nodetype: highmem
    kops.k8s.io/instancegroup: highmem-espsti
  role: Node
  subnets:
  - espsti
  taints:
  - highmem:NoSchedule
```

**5. What happened after the commands executed?**

node labels are not added to kubernetes nodes as before.

```
% kubectl describe node highmem-espsti-n5czqf
Name:               highmem-espsti-n5czqf
Roles:              node
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m1.xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=regionOne
                    failure-domain.beta.kubernetes.io/zone=espsti
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=highmem-espsti-n5czqf
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/node=
                    node.kubernetes.io/instance-type=m1.xlarge
                    topology.cinder.csi.openstack.org/zone=espsti
                    topology.kubernetes.io/region=regionOne
                    topology.kubernetes.io/zone=espsti
```

**6. What did you expect to happen?**

I expect that instancegroup spec nodeLabels are passed to kubernetes nodes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
