### ISSUE TITLE
Openstack CCM should have --cluster-name defined

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#15108]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Like discussed in https://github.com/kubernetes/kops/pull/15095#issuecomment-1414352848 we should have `--cluster-name` defined in our clusters if we want to run multiple Kubernetes clusters in same project.

**2. Feel free to provide a design supporting your feature request.**

Currently when its not enabled it uses default value `kubernetes` and we cannot modify the flag for existing clusters. I am not 100% sure but we could try populating the https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L676 value in https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/new_cluster.go#L326 and see will it be added to ccm configuration.

**Comment by zetaab** [comment]
ping @ederst I did this as separate issue

**Comment by zetaab** [comment]
AWS for instance generates it on the fly in https://github.com/kubernetes/kops/blob/b959df1ecb4fa66e17bb0b5738e562e6e3d56279/pkg/model/components/awscloudcontrollermanager.go#L56

However, if we do it in similar way it will be applied to existing clusters.. and it will not work

**Comment by zetaab** [comment]
actually we could define it easily here https://github.com/kubernetes/kops/blob/master/pkg/model/components/openstack.go#L59 but how to avoid adding that to existing clusters?

**Comment by ederst** [comment]
Wouldn't something like [this here](https://github.com/kubernetes/kops/commit/619721debe9ad3fc077c1bda083e61af05746e4b) do the trick in only populating it for new clusters?

https://github.com/kubernetes/kops/blob/619721debe9ad3fc077c1bda083e61af05746e4b/upup/pkg/fi/cloudup/new_cluster.go#L326-L330

https://github.com/kubernetes/kops/blob/619721debe9ad3fc077c1bda083e61af05746e4b/upup/pkg/fi/cloudup/new_cluster.go#L1436-L1442

Results in:

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: my.test.cluster.k8s.local
spec:
 # ...
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        clusterName: my.test.cluster.k8s.local
        ignore-volume-az: false
  # ...
  cloudControllerManager:
    clusterName: my.test.cluster.k8s.local
  # ...
```

Although, doing it in https://github.com/kubernetes/kops/blob/master/pkg/model/components/openstack.go#L59 would be less "verbose", because this part populates the `complete-cluster.spec` as far as I understand? Thus it would not show up in the generated cluster config unless a user actively sets it to something different.

But doing it in this part I am not sure how to populate the value only when the cluster gets created. I mean in theory there could be a flag/value in the OpenStack provider config which is set to true/clusterName and is only set when a cluster gets newly created, but then again, why not set it directly in the right places like in the example above?

Or maybe just not do the value in `BlockStorage` and only use `ExternalCloudController.ClusterName` for setting all the cluster name flags for the OCCM components (occm, cinder-csi-plugin, snapshotter, etc.)?
