### ISSUE TITLE
kubelet cgroups misconfigured

### ISSUE THREAD

**Issue by heybronson** [kubernetes/kops#15167]
/kind bug

Cgroups are inconsistent between the kops and kubelet configurations. Sections of kops will append `.slice` to the runtime and kubelet cgroups, yet not append `.slice` when translating kops configurations to flags for kubelet.

This leads to inconsistencies in cgroup names (note no .slice suffix for kubelet-cgroups and runtime-cgroups):
```
cat /etc/sysconfig/kubelet
DAEMON_ARGS="--anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --cgroup-root=/ --client-ca-file=/srv/kubernetes/ca.crt --cloud-provider=external --cluster-dns=172.20.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --feature-gates=CSIMigrationAWS=true,InTreePluginAWSUnregister=true --hostname-override=i-0c446642909c77111 --kube-reserved-cgroup=/podruntime.slice --kube-reserved=cpu=500m,memory=500Mi --kubeconfig=/var/lib/kubelet/kubeconfig --kubelet-cgroups=/podruntime --max-pods=17 --pod-infra-container-image=registry.k8s.io/pause:3.6@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db --pod-manifest-path=/etc/kubernetes/manifests --protect-kernel-defaults=true --register-schedulable=true --register-with-taints=node-role.kubernetes.io/control-plane=:NoSchedule --resolv-conf=/run/systemd/resolve/resolv.conf --runtime-cgroups=/podruntime --v=2 --volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec/ --cloud-config=/etc/kubernetes/in-tree-cloud.config --node-ip=172.20.39.57 --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock --tls-cert-file=/srv/kubernetes/kubelet-server.crt --tls-private-key-file=/srv/kubernetes/kubelet-server.key --config=/var/lib/kubelet/kubelet.conf"
HOME="/root"
```

Yet in the cgroup units:
```
cat containerd.service kubelet.service |grep -i slice
Slice=podruntime.slice
Slice=podruntime.slice

cat podruntime.slice
[Unit]
Documentation=man:systemd.special(7)
Before=slices.target
DefaultDependencies=no
```

Issue is likely because we're directly building kubelet flags using the kops kubelet config: https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kubelet.go#L277

Yet when building systemd slices we're appending `.slice` to the name: https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/kubelet.go#L702-L705

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.25.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
The issue remains the same across k8s version, but using 1.24.7

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops update cluster --yes && kops rolling-update cluster --yes`

**6. What did you expect to happen?**
A single `podruntime.slice` cgroup is created and `--kubelet-cgroups=/podruntime.slice`, `--runtime-cgroups=/podruntime.slice` is in kubelet args.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-05-11T22:35:23Z"
  generation: 36
  name: <REDACTED>
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
      useForInternalApi: true
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
      managed: true
      podAnnotations:
        test: test
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
  configBase: <REDACTED>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    cgroupDriver: systemd
    kubeReserved:
      cpu: 500m
      memory: 500Mi
    kubeReservedCgroup: /podruntime.slice
    kubeletCgroups: /podruntime
    runtimeCgroups: /podruntime
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.24.7
  masterInternalName: <REDACTED>
  masterPublicName: <REDACTED>
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
