### ISSUE TITLE
Cluster break when multiple master node goes down 

### ISSUE THREAD

**Issue by Bharat-vyas1** [kubernetes/kops#15168]
/kind bug

I am using KOPS-1.25.3 and v1.25.6 of kubectl with AWS as a cloud provider 

I created a multi master kubernetes cluster in a pre-created VPC (Private topology) with NAT-Instance in one AZ that can be used for all private subnets.
To be more clear I am using this command - 

kops create cluster --name kops-cluster.sheershjain.live --cloud=aws  --zones=us-east-1a,us-east-1b,us-east-1c --node-count=3  --node-size=t2.micro  --node-volume-size=10  --node-security-groups=sg-0d97ebe0e  --master-size=t2.medium   --master-count=3   --master-volume-size=10  --master-security-groups=sg-095336030  --master-zones=us-east-1a,us-east-1b,us-east-1c  --dns-zone=[MYDOMAIN.com](http://mydomain.com/)   --topology=private  --vpc=MYVPC   --networking=calico --subnets=MY_SUBNET1,MY_SUBNET2,MY_SUBNET3  --utility-subnets=MY_SUBNET1,MY_SUBNET2,MY_SUBNET3   --ssh-public-key=./id_rsa.pub

Everything is working file, I created PODS and test them, try to stop couple of nodes and it was also working fine, load balance the containers on running nodes, and spin up new nodes  

**Issue -** 
I tried to stop 1 master from 3, the cluster is working fine, but as soon as I stopped 2 master out of 3, the cluster break for sometime and I was not able to use kubectl command (Timeout kind of issue) for all kubectl commands 
I waited for sometime and then it's started working again 
Nothing from my side, ASG just spin up 2 new master that I deleted manually and I kubectl command started working  

I was deploying the cluster with 3 Master nodes in 3 different AZ, stopped 2 masters and it was causing issues, once those 2 master up (With ASG) kubectl command started working again  

Is that the default behaviour ? I was expecting that we can run the cluster and kubectl commands with even single master as well 
If yes then why it was not working in my case 

I am sharing my cluaster.yaml file below ---

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  name: 
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://
  dnsZone: 
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.25.6
  masterPublicName: 
  networkCIDR: 172.18.0.0/16
  networkID: 
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.18.64.0/20
    id: 
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.18.80.0/20
    id: 
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.18.96.0/20
    id: 
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.18.64.0/20
    id: 
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.18.80.0/20
    id: 
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.18.96.0/20
    id: 
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  labels:
    kops.k8s.io/cluster: 
  name: master-us-east-1a
spec:
  additionalSecurityGroups:
  - sg-09533603
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 10
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  labels:
    kops.k8s.io/cluster: 
  name: master-us-east-1b
spec:
  additionalSecurityGroups:
  - sg-0953360303
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 10
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  labels:
    kops.k8s.io/cluster: 
  name: master-us-east-1c
spec:
  additionalSecurityGroups:
  - sg-0953360303
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 10
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  labels:
    kops.k8s.io/cluster: 
  name: nodes-us-east-1a
spec:
  additionalSecurityGroups:
  - sg-0d97ebe0ef
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  labels:
    kops.k8s.io/cluster: 
  name: nodes-us-east-1b
spec:
  additionalSecurityGroups:
  - sg-0d97ebe
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-02-17T07:21:35Z"
  labels:
    kops.k8s.io/cluster: 
  name: nodes-us-east-1c
spec:
  additionalSecurityGroups:
  - sg-0d97ebe0e
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
  - us-east-1c

```
