### ISSUE TITLE
Using Kops to create only specific resources

### ISSUE THREAD

**Issue by denis-singh** [kubernetes/kops#1519]
Is there a way to use kops without having to create the entire networking stack? For instance setting it up to not create the Subnets, Route tables, igw's etc. I want to launch a cluster in an existing VPC and use the existing subnets, route tables, etc.

**Comment by gopinatht** [comment]
@denis-singh Yes, but it needs a bit of work tough. I use a command like this to get most of the settings in place: `${KOPSPATH}/kops create --v=8 cluster --channel "alpha" --topology private --image ami-6d1c2007 --vpc vpc-xxxxxxxx --network-cidr "10.44.76.0/23" --networking calico --bastion --ssh-public-key "~/.ssh/MySSHKeyFile.pub" --zones us-east-1e ${CLUSTERNAME}`

I then edit the generated config using the `${KOPSPATH}/kops edit cluster ${CLUSTERNAME}` command. I specifically adjust the Subnet settings to have the right CIDR and subnet name. My subnet settings end up looking like this:

```
subnets:
  - cidr: 10.44.76.0/25
    id: subnet-xxxxxxxx
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.44.77.128/26
    id: subnet-yyyyyyyy
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
```

I do see that kops generates its own Security groups and I am OK with it.

Also, in my case, I use one zone with a private subnet and a public subnet (for utility). But your subnets will expand with the increase in number of zones.
