### ISSUE TITLE
"subnet changes on LoadBalancer not yet implemented" when --vpc and --networking-cidr set

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kops#1525]
**Kops Version**: 1.5.0-alpha3

We're hitting an issue deploying a kops cluster to an existing AWS VPC. This configuration works when we _do not_ use an existing VPC. Here's the error message:

```
W0118 06:33:47.378316   14403 executor.go:109] error running task "LoadBalancer/bastion.africa.k8s.production.saltside.net" (1m56s remaining to succeed): subnet changes on LoadBalancer not yet implemented
W0118 06:33:47.378416   14403 executor.go:109] error running task "LoadBalancer/api.africa.k8s.production.saltside.net" (1m56s remaining to succeed): subnet changes on LoadBalancer not yet implemented
```

The command itself:

```
kops create cluster \
  --yes \
  --bastion \
  --topology=private \
  --networking=weave \
  --associate-public-ip=false \
  --cloud=aws \
  --zones=eu-west-1a,eu-west-1b,eu-west-1c \
  --ssh-public-key=~/k8s_node_key.pub  \
  --dns-zone=CENSORED \
  --vpc=vpc-a0fadcc4 \
  --network-cidr=10.0.0.0/16 \
  --name=CENSORED
```

**Comment by gopinatht** [comment]
@ahawkins FWIW, I edit the config after I run a similar command to adjust the subnet settings: Specifically, I add the `id: subnet-xxxxxxxx` to specify the subnet name and make sure the subnet CIDR is correct. My subnet settings end up looking like this: 

```
subnets:
  - cidr: 10.44.76.0/25
    id: subnet-xxxxxxxx
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.44.77.128/26
    id: subnet-yyyyyyyy
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
```

In my case, I use one zone with a a private subnet and a public subnet (for utility). But your subnet will expand with the increase in number of zones.

On another note, if you are using a pre-existing subnet, weave does not work yet. I logged a bug for it: https://github.com/kubernetes/kops/issues/1514

Calico works though.

**Comment by justinsb** [comment]
I am pretty sure this is fixed in beta1 and will be fixed in 1.5.0.  We've also added more logging.  I'm going to close, but please do comment / reopen if you see it again.

**Comment by kaspernissen** [comment]
I'm experiencing a similar issue.

**Kops version:** 1.5.1

I'm trying to spin up a cluster in an already existing VPC with already existing subnets and NAT Gateways. The error I'm seeing are: 

```
I0213 09:29:52.233754   21275 executor.go:91] Tasks: 84 done / 92 total; 2 can run
W0213 09:29:52.652833   21275 executor.go:109] error running task "LoadBalancer/api.k8s.prod.example.com" (9m35s remaining to succeed): subnet changes on LoadBalancer not yet implemented: actual=[subnet-8f4001d7 subnet-9b97afed subnet-daf8fdbe] -> expected=[subnet-02707667 subnet-7fbd8409 subnet-fc2d6ba4]
W0213 09:29:52.652867   21275 executor.go:109] error running task "LoadBalancer/bastion.k8s.prod.example.com" (9m35s remaining to succeed): subnet changes on LoadBalancer not yet implemented: actual=[subnet-8f4001d7 subnet-9b97afed subnet-daf8fdbe] -> expected=[subnet-02707667 subnet-7fbd8409 subnet-fc2d6ba4]
I0213 09:29:52.652883   21275 executor.go:124] No progress made, sleeping before retrying 2 failed task(s)
```

Here is what I do:

1.  Export the following variables:
```
export CLUSTER_NAME=<NAME_OF_MY_CLUSTER>
export KOPS_STATE_STORE=s3://<OUR_S3_BUCKET>
export VPC_ID=vpc-95c995f0
export DNS_ZONE=Z1XENEA6BQBTQ6

```
2. Create the cluster
```
kops create cluster \
    --node-count 3 \
    --zones eu-west-1a,eu-west-1b,eu-west-1c \
    --master-zones eu-west-1a,eu-west-1b,eu-west-1c \
    --dns-zone=${DNS_ZONE} \
    --node-size t2.large \
    --master-size t2.medium \
    --topology private \
    --networking weave \
    --ssh-public-key <OUR_KEY> \
    --vpc=${VPC_ID} \
    --admin-access <OUR_IP> \
    --bastion \
    ${CLUSTER_NAME}
```

3. Then i realized i wanted different instance types, so I updated those
```
$ kops edit ig --name=<NAME OF CLUSTER> nodes
$ kops edit ig --name=<NAME OF CLUSTER> master-eu-west-1a
$ kops edit ig --name=<NAME OF CLUSTER> master-eu-west-1b
$ kops edit ig --name=<NAME OF CLUSTER> master-eu-west-1c
```
The changes results in: 
```
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
bastions		Bastion	t2.micro	1	1	utility-eu-west-1a,utility-eu-west-1b,utility-eu-west-1c
master-eu-west-1a	Master	m3.medium	1	2	eu-west-1a
master-eu-west-1b	Master	m3.medium	1	2	eu-west-1b
master-eu-west-1c	Master	m3.medium	1	2	eu-west-1c
nodes			Node	m3.large	3	8	eu-west-1a,eu-west-1b,eu-west-1c
```

4. Then i change the clusters subnet to match my existing setup with the following:
```
    subnets:
    - id: subnet-00707665
      egress: nat-0de2390dfa6ab3c6e
      name: eu-west-1a
      type: Private
      zone: eu-west-1a
    - id: subnet-f1b79886
      egress: nat-016adb6fc3fd1efc7
      name: eu-west-1b
      type: Private
      zone: eu-west-1b
    - id: subnet-232d6b7b
      egress: nat-0480093fca5b06a9a
      name: eu-west-1c
      type: Private
      zone: eu-west-1c
    - id: subnet-02707667
      name: utility-eu-west-1a
      type: Utility
      zone: eu-west-1a
    - id: subnet-7fbd8409
      name: utility-eu-west-1b
      type: Utility
      zone: eu-west-1b
    - id: subnet-fc2d6ba4
      name: utility-eu-west-1c
      type: Utility
      zone: eu-west-1c
```

5. The run `kops update cluster .. `
Kops explains that it will modify the loadbalancers:
```
  LoadBalancer/api.k8s.prod.example.com
  	Subnets             	 [id:subnet-8f4001d7, id:subnet-9b97afed, id:subnet-daf8fdbe] -> [name:utility-eu-west-1a.k8s.prod.example.com id:subnet-02707667, name:utility-eu-west-1b.k8s.prod.example.com id:subnet-7fbd8409, name:utility-eu-west-1c.k8s.prod.example.com id:subnet-fc2d6ba4]
  	SecurityGroups      	 [id:sg-5f2f1f39] -> [name:api-elb.k8s.prod.example.com]

  LoadBalancer/bastion.k8s.prod.example.com
  	Subnets             	 [id:subnet-8f4001d7, id:subnet-9b97afed, id:subnet-daf8fdbe] -> [name:utility-eu-west-1a.k8s.prod.example.com id:subnet-02707667, name:utility-eu-west-1b.k8s.prod.example.com id:subnet-7fbd8409, name:utility-eu-west-1c.k8s.prod.example.com id:subnet-fc2d6ba4]
  	SecurityGroups      	 [id:sg-5a2f1f3c] -> [name:bastion-elb.k8s.prod.example.com]
```
