### ISSUE TITLE
Set httpPutResponseHopLimit greater than1 when clusterautoscaler is enabled

### ISSUE THREAD

**Issue by JJotah** [kubernetes/kops#15330]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
On kops when you edit the cluster and you want to enable clusterautoscaler with IMDSv2 we should to mention that on instancegroups the key httpPutResponseHopLimit should be greater than 1. Following the AWS docs we set to 2 the httpPutResponseHopLimit if not will not work the cluster autoscaler.

**2. Feel free to provide a design supporting your feature request.**
I will change it on kops and give you a PR of that.

**Comment by olemarkus** [comment]
Is this purely documentation or something more?

**Comment by JJotah** [comment]
> Is this purely documentation or something more?

I want to add new func to validate if clusterAutoscaler is enabled and httpPutResponseHopLimit is set should be greater than 1 or what do you think?, @olemarkus

**Comment by olemarkus** [comment]
If cluster autoscaler is enabled, it either runs on the control plane where httpPutResponseHopLimit  is set to 3. If not it runs using IRSA where IMDS is not relevant.

**Comment by JJotah** [comment]
> If cluster autoscaler is enabled, it either runs on the control plane where httpPutResponseHopLimit is set to 3. If not it runs using IRSA where IMDS is not relevant.

Yesterday I was trying to make it works with this configuration

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: NAME
spec:
  clusterAutoscaler:
    enabled: true
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
    cpuRequest: "100m"
    memoryRequest: "300Mi"
```

and on instance groups:

```yaml
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: NAME
  name: Name
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
```

And with this configuration failed because following the [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#configuring-instance-metadata-options) and following the [clusterAutoscaler docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#common-notes-and-gotchas)

So I think that validation/instancegroup.go we can add something like this && update documentation on instancegroups.

**Comment by olemarkus** [comment]
It's usually best to use kOps default for instance metadata settings. But there is no harm to add validation if done correctly. I could imagine something like "if IRSA is not enabled, all instance groups without taints must have httpPutResponseHopLimit > 2"

**Comment by JJotah** [comment]
> It's usually best to use kOps default for instance metadata settings. But there is no harm to add validation if done correctly. I could imagine something like "if IRSA is not enabled, all instance groups without taints must have httpPutResponseHopLimit > 2"

Sure, I'm agree with you but you know the security team wants to enable it hahaha 
I will change and add new doc on InstanceGroup

**Comment by olemarkus** [comment]
Yeah. For security reasons you should really switch to IRSA.

**Comment by JJotah** [comment]
I've enabled IRSA yesterday following [your doc](https://dev.to/olemarkus/zero-configuration-irsa-on-kops-1po1) but I was not able to make clusterAutoscaler works with IRSA.
Checking the logs seems like podIdentityWebhook was working correctly and send info into clusterAutoscaler but the failure that I receive was: 
```bash
Failed to regenerate ASG cache: NoCredentialProviders: no valid providers in chain. Deprecated.  For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by JJotah** [comment]
> podIdentityWebhook is not used for kops addons. kOps automatically add the necessary details. Follow these docs:

So you said that if I enabled 

```yaml
spec:
  iam:
    useServiceAccountExternalPermissions: true
```

with 

```yaml
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: NAME
  name: Name
spec:
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
```

ClusterAutoscaler should work?

**Comment by olemarkus** [comment]
Yeah. Plus 
```
spec:
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://publicly-readable-store
    enableAWSOIDCProvider: true
```
