### ISSUE TITLE
OpenStack: Cannot install cluster with public domain name 

### ISSUE THREAD

**Issue by fchiacchiaretta** [kubernetes/kops#15337]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```shell
$ kops version 
Client version: 1.26.2 (git-v1.26.2)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

kubernetesVersion: 1.26.3

**3. What cloud provider are you using?**
OpenStack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
1. Create an OpenStack project and Designate zone for `cluster.example.com.`
2. Create a cluster spec
    ```shell
    $ export KOPS_STATE_STORE=swift://kops-state-store
    $ source my-app-cred-openrc.sh
    $ kops create cluster cluster.example.com \
      --cloud openstack \
      --state ${KOPS_STATE_STORE} \
      --zones nova \
      --network-cidr 192.168.0.0/24 \
      --image ubuntu-22.04.2 \
      --master-count=3 \
      --node-count=2 \
      --node-size m1.large \
      --master-size m1.medium \
      --etcd-storage-type default \
      --api-loadbalancer-type public \
      --topology private \
      --bastion \
      --ssh-public-key id_rsa.pub \
      --networking cilium \
      --os-ext-net my-floating-network \
      --os-octavia=true \
      --os-octavia-provider=amphorav2 \
      --dry-run \
      -o yaml > cluster-spec.yaml
    ```
3. Verify the generated spec has:
    ```yaml
    spec:
      masterPublicName: api.cluster.example.com
      topology:
        bastion:
          bastionPublicName: bastion.cluster.example.com
        dns:
          type: Public
    ```
4. Create the cluster with
    ```shell
    $ kops create -f cluster-spec.yaml
    $ kops update cluster --name cluster.example.com --yes
    ```
    This step will stop complaining that dns-controller has no support for provider Openstack

**5. What happened after the commands executed?**
No cluster has been initialized.
I also tried
* using `external-dns` as controller
    ```yaml
    spec:
      externalDns:
        provider: external-dns
    ```
    but it doesn't support openstack provider as well (it actually does upstream, but no support is configured in kops)
* disabling `external-dns`
    ```yaml
    spec:
      externalDns:
        disable: true
    ```
    in this case all resources are created (network, load balancer, instances, etc.), but only 2 placeholder DNS records are created in Designate zone (`api.internal.cluster.example.com` and `kops-controller.internal.cluster.example.com`) and values are never updated, resulting in k8s cluster failing to initialize CNI, join nodes etc.

**6. What did you expect to happen?**
kops creates and updates public and internal DNS records for zone `cluster.example.com`, allowing the k8s cluster to initialize and operate properly.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: cluster.example.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        clusterName: cluster.example.com
        ignore-volume-az: false
      loadbalancer:
        floatingNetwork: my-floating-network
        method: ROUND_ROBIN
        provider: amphorav2
        useOctavia: true
      monitor:
        delay: 15s
        maxRetries: 3
        timeout: 10s
      router:
        externalNetwork: my-floating-network
  cloudControllerManager:
    clusterName: cluster.example.com
  cloudProvider: openstack
  configBase: swift://kops-state-store/cluster.example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-nova-1
      name: etcd-1
      volumeType: default
    - instanceGroup: control-plane-nova-2
      name: etcd-2
      volumeType: default
    - instanceGroup: control-plane-nova-3
      name: etcd-3
      volumeType: default
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-nova-1
      name: etcd-1
      volumeType: default
    - instanceGroup: control-plane-nova-2
      name: etcd-2
      volumeType: default
    - instanceGroup: control-plane-nova-3
      name: etcd-3
      volumeType: default
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubeDNS:
    provider: CoreDNS
    nodeLocalDNS:
      enabled: true
      memoryRequest: 5Mi
      cpuRequest: 25m
  kubernetesVersion: 1.26.3
  masterPublicName: api.cluster.example.com
  networkCIDR: 192.168.0.0/24
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 192.168.0.32/27
    name: nova
    type: Private
    zone: nova
  - cidr: 192.168.0.0/30
    name: utility-nova
    type: Utility
    zone: nova
  topology:
    bastion:
      bastionPublicName: bastion.cluster.example.com
    dns:
      type: Public
    masters: private
    nodes: private
  certManager:
    enabled: true
  metricsServer:
    enabled: true
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.example.com
  name: control-plane-nova-1
spec:
  image: ubuntu-22.04.2
  machineType: m1.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.example.com
  name: control-plane-nova-2
spec:
  image: ubuntu-22.04.2
  machineType: m1.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.example.com
  name: control-plane-nova-3
spec:
  image: ubuntu-22.04.2
  machineType: m1.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.example.com
  name: nodes-nova
spec:
  image: ubuntu-22.04.2
  machineType: m1.large
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.example.com
  name: bastions
spec:
  image: ubuntu-22.04.2
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m1.medium
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.example.com
  name: admin
spec:
  publicKey: my-ssh-key
```

We have a quite complete OpenStack Designate setup, with Neutron integration for Designate (DNS records are created from floating IP information for example) and so we can do all the needed testing to work out a better integration.
