### ISSUE TITLE
AWS: 1.26.x Broke kops export kubecfg when the existing cluster has DNS

### ISSUE THREAD

**Issue by geanpalacios** [kubernetes/kops#15354]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.26.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21.14

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops export kubecfg --admin=1h0m0s

**5. What happened after the commands executed?**
The exported kubeconfig file contains a reference to the ELB dns instead of the public API dns (which is an alias for the elb) but, the cluster certificate doesn't include the ELB name in the domains causing other commands such as `kops validate cluster` to fail because of it:
```
Error: Validation failed: unexpected error during validation: error listing nodes: Get "https://api-cluster-*********.us-east-1.elb.amazonaws.com/api/v1/nodes": x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, api.cluster.domain, api.internal.cluster.domain, not api-cluster-********.us-east-1.elb.amazonaws.com
```

**6. What did you expect to happen?**
the exported kubeconfig when running `kops export kubecfg ...` to contain the valid DNS name of the cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
ClusterName as positional argument is deprecated and will be removed in a future version

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: cluster.domain
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt*",
            "kms:GenerateDataKey*",
            "kms:DescribeKey",
            "kms:CreateGrant",
            "kms:ListGrants",
            "kms:RevokeGrant"
          ],
          "Resource": [
            "arn:aws:kms:us-east-1:*:key/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": ["autoscaling:Describe*"],
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": ["ec2:CreateTags"],
          "Resource": "arn:aws:ec2:*:*:volume/*"
        },
        {
          "Action": [
              "s3:GetBucketLocation"
          ],
          "Effect": "Allow",
          "Resource": [
              "arn:aws:s3:::logs-3rd-party-***-us-east-1",
              "arn:aws:s3:us-east-1:***:accesspoint/logs-3rd-party-k8saudit-us-east-1"
          ]
        },
        {
          "Action": [
              "s3:GetObject",
              "s3:PutObject",
              "s3:PutObjectAcl",
              "s3:AbortMultipartUpload",
              "s3:ListMultipartUploadParts"
          ],
          "Effect": "Allow",
          "Resource": [
              "arn:aws:s3:::logs-3rd-party-***-us-east-1/*",
              "arn:aws:s3:us-east-1:***:accesspoint/logs-3rd-party-k8saudit-us-east-1/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
              "ecr:GetAuthorizationToken",
              "ecr:BatchCheckLayerAvailability",
              "ecr:GetDownloadUrlForLayer",
              "ecr:GetRepositoryPolicy",
              "ecr:DescribeRepositories",
              "ecr:ListImages",
              "ecr:BatchGetImage"
          ],
          "Resource": [
              "*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
              "firehose:PutRecordBatch"
          ],
          "Resource": [
              "*"
          ]
        }
      ]
    node: |
      [
        {
          "Action": ["sts:AssumeRole"],
          "Effect": "Allow",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt*",
            "kms:GenerateDataKey*",
            "kms:DescribeKey",
            "kms:CreateGrant",
            "kms:ListGrants",
            "kms:RevokeGrant"
          ],
          "Resource": [
            "arn:aws:kms:us-east-1:*:key/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": ["autoscaling:Describe*"],
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": ["ec2:CreateTags"],
          "Resource": "arn:aws:ec2:*:*:volume/*"
        },
        {
          "Effect": "Allow",
          "Action": [
              "ecr:GetAuthorizationToken",
              "ecr:BatchCheckLayerAvailability",
              "ecr:GetDownloadUrlForLayer",
              "ecr:GetRepositoryPolicy",
              "ecr:DescribeRepositories",
              "ecr:ListImages",
              "ecr:BatchGetImage"
          ],
          "Resource": [
              "*"
          ]
        }
      ]
  addons:
  - manifest: s3://kops-cluster.domain/cluster.domain/addons/storageclass-gp2-wait-for-first-consumer.yaml
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Chargeback: base
    ClientId: shared
    Component: ***
    Department: "***"
    Environment: Development
    ManagedServiceLevel: Immutable Enhanced
    Product: ***
    cmapplication: ***
    cmenv: Development
    cmlayer: Infra
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    memoryRequest: 1536Mi
  configBase: s3://kops-cluster.domain/cluster.domain
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    manager:
      env:
      - name: ETCD_LISTEN_METRICS_URLS
        value: http://0.0.0.0:2379
      - name: ETCD_METRICS
        value: extensive
    memoryRequest: 875Mi
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 300Mi
    name: events
  fileAssets:
  - content: |
      apiVersion: apiserver.k8s.io/v1alpha1
      kind: AdmissionConfiguration
      plugins:
      - name: EventRateLimit
        path: event-rate-limit.yaml
    name: admissionControl
    path: /srv/kubernetes/kube-apiserver/admission-control.yaml
    roles:
    - Master
  - content: |
      apiVersion: eventratelimit.admission.k8s.io/v1alpha1
      kind: Configuration
      limits:
      - type: Namespace
        qps: 100
        burst: 1000
        cacheSize: 2000
      - type: User
        qps: 100
        burst: 1000
    name: eventRateLimit
    path: /srv/kubernetes/kube-apiserver/event-rate-limit.yaml
    roles:
    - Master
  - content: |
      apiVersion: audit.k8s.io/v1 # This is required.
      kind: Policy
      # Don't generate audit events for all requests in RequestReceived stage.
      omitStages:
        - "RequestReceived"
      rules:
        # Log pod changes at RequestResponse level
        - level: RequestResponse
          resources:
          - group: ""
            # Resource "pods" doesn't match requests to any subresource of pods,
            # which is consistent with the RBAC policy.
            resources: ["pods"]
        # Log "pods/log", "pods/status" at Metadata level
        - level: Metadata
          resources:
          - group: ""
            resources: ["pods/log", "pods/status"]

        # Don't log requests to a configmap called "controller-leader"
        - level: None
          resources:
          - group: ""
            resources: ["configmaps"]
            resourceNames: ["controller-leader"]

        # Don't log watch requests by the "system:kube-proxy" on endpoints or services
        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
          - group: "" # core API group
            resources: ["endpoints", "services"]

        # Don't log authenticated requests to certain non-resource URL paths.
        - level: None
          userGroups: ["system:authenticated"]
          nonResourceURLs:
          - "/api*" # Wildcard matching.
          - "/version"

        # Log the request body of configmap changes in kube-system.
        - level: Request
          resources:
          - group: "" # core API group
            resources: ["configmaps"]
          # This rule only applies to resources in the "kube-system" namespace.
          # The empty string "" can be used to select non-namespaced resources.
          namespaces: ["kube-system"]

        # Log configmap and secret changes in all other namespaces at the Metadata level.
        - level: Metadata
          resources:
          - group: "" # core API group
            resources: ["secrets", "configmaps"]

        # Log all other resources in core and extensions at the Request level.
        - level: Request
          resources:
          - group: "" # core API group
          - group: "extensions" # Version of group should NOT be included.

        # A catch-all rule to log all other requests at the Metadata level.
        - level: Metadata
          # Long-running requests like watches that fall under this rule will not
          # generate an audit event in RequestReceived.
          omitStages:
            - "RequestReceived"
    name: kubeApiServerAdvancedAuditing
    path: /srv/kubernetes/kube-apiserver/audit-policy.yaml
    roles:
    - Master
  hooks:
  - manifest: |
      [Unit]
      Description=Manage Tenable Nessus Agent

      [Service]
      Type=oneshot
      RemainAfterExit=true

      ExecStartPre=curl https://***/public/nessus/agent/NessusAgent-10.0.1-ubuntu1110_amd64.deb --output /tmp/NessusAgent.deb
      ExecStartPre=dpkg -i /tmp/NessusAgent.deb
      ExecStartPre=rm /tmp/NessusAgent.deb
      ExecStart=systemctl start nessusagent.service
      ExecStartPost=/opt/nessus_agent/sbin/nessuscli agent link --cloud --key="***" --name="***$(hostname)" --groups="***,***,***,DEV,Scan1"

      TimeoutStopSec=15s
      ExecStop=/opt/nessus_agent/sbin/nessuscli agent unlink --force

      [Install]
      WantedBy=multi-user.target
    name: nessusagent-installer.service
    roles:
    - Node
    - Master
    useRawManifest: true
  - manifest: |
      [Unit]
      Description=Ensure rsyslog files are readable by fluent-bit
      Before=logrotate.service rsyslog.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes

      ExecStartPre=mkdir -p /var/log/aide /var/log/clamav
      ExecStartPre=touch /var/log/aide/aide-scan.log /var/log/clamav/clamav-scan.log
      ExecStartPre=perl -pi -e 's,FileCreateMode .*,FileCreateMode 0644,' /etc/rsyslog.conf
      ExecStartPre=perl -pi -e 's,{,{\n\tcreate 0644 syslog adm,' /etc/logrotate.d/rsyslog
      ExecStart=find /var/log/ -type f -user syslog -exec chmod 0644 {} ';'

      [Install]
      WantedBy=multi-user.target
    name: rsyslog-fluentbit-permissions.service
    roles:
    - Node
    - Master
    useRawManifest: true
  iam:
    legacy: false
  kubeAPIServer:
    admissionControlConfigFile: /srv/kubernetes/kube-apiserver/admission-control.yaml
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy.yaml
    authorizationMode: Node,RBAC
    enableAdmissionPlugins:
    - AlwaysPullImages
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - EventRateLimit
    - LimitRanger
    - NamespaceLifecycle
    - NodeRestriction
    - PersistentVolumeLabel
    - PodNodeSelector
    - PodTolerationRestriction
    - ResourceQuota
    - ServiceAccount
    featureGates:
      AdvancedAuditing: "true"
    memoryRequest: 2093796556800m
    oidcClientID: ***
    oidcGroupsClaim: groups
    oidcIssuerURL: https://***/oauth2/****
    oidcUsernameClaim: k8s_user
  kubeControllerManager:
    terminatedPodGCThreshold: 10
  kubeDNS:
    externalCoreFile: |-
      (global) {
        cache
        errors
        log . {
          class error
        }
        prometheus :9153
      }

      ec2.internal. {
        import global

        health :8084
        forward . 169.254.169.253
      }

      . {
        import global

        health {
          lameduck 5s
        }

        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }

        loadbalance
        loop
        ready
        reload

        forward . 1.1.1.1 8.8.8.8 8.8.4.4 9.9.9.9
      }
    nodeLocalDNS:
      enabled: true
      forwardToKubeDNS: true
    provider: CoreDNS
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    readOnlyPort: 0
    registryBurst: 100
    registryPullQPS: 20
    tlsCipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_256_GCM_SHA384
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.14
  masterInternalName: api.internal.cluster.domain
  masterPublicName: api.cluster.domain
  metricsServer:
    enabled: true
    insecure: true
  networkCIDR: 10.147.32.0/20
  networkID: vpc-***
  networking:
    flannel:
      backend: vxlan
  nodeTerminationHandler:
    enabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.147.36.0/24
    id: subnet-***
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.147.37.0/24
    id: subnet-***
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.147.38.0/24
    id: subnet-***
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.147.32.0/24
    egress: nat-***
    id: subnet-***
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.147.33.0/24
    egress: nat-***
    id: subnet-***
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.147.34.0/24
    egress: nat-***
    id: subnet-***
    name: us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.cluster.domain
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T14:26:42Z"
  labels:
    kops.k8s.io/cluster: cluster.domain
  name: master-us-east-1a
spec:
  cloudLabels:
    LayerDetail: kubernetes-master
  image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeOptimization: true
  subnets:
  - us-east-1a
  sysctlParameters:
  - net.ipv6.conf.all.disable_ipv6=1
  - net.ipv6.conf.default.disable_ipv6=1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T14:26:42Z"
  labels:
    kops.k8s.io/cluster: cluster.domain
  name: master-us-east-1b
spec:
  cloudLabels:
    LayerDetail: kubernetes-master
  image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeOptimization: true
  subnets:
  - us-east-1b
  sysctlParameters:
  - net.ipv6.conf.all.disable_ipv6=1
  - net.ipv6.conf.default.disable_ipv6=1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T14:26:42Z"
  labels:
    kops.k8s.io/cluster: cluster.domain
  name: master-us-east-1c
spec:
  cloudLabels:
    LayerDetail: kubernetes-master
  image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeOptimization: true
  subnets:
  - us-east-1c
  sysctlParameters:
  - net.ipv6.conf.all.disable_ipv6=1
  - net.ipv6.conf.default.disable_ipv6=1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T14:26:42Z"
  labels:
    kops.k8s.io/cluster: cluster.domain
  name: nodes-us-east-1a
spec:
  cloudLabels:
    LayerDetail: kubernetes-node
    k8s.io/cluster-autoscaler/cluster.domain: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
  image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  maxSize: 4
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - m6a.2xlarge
    - m6i.2xlarge
    - m5.2xlarge
    - m5a.2xlarge
    - m5d.2xlarge
    - m5zn.2xlarge
    - m6id.2xlarge
    - r5.2xlarge
    - r5a.2xlarge
    - r5ad.2xlarge
    - r5b.2xlarge
    - r5d.2xlarge
    - r5dn.2xlarge
    - r5n.2xlarge
    - r6a.2xlarge
    - r6i.2xlarge
    - r6id.2xlarge
    - t3.2xlarge
    - t3a.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 1
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    autoscalegroup: nodes
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  rollingUpdate:
    maxSurge: 50%
  rootVolumeOptimization: true
  rootVolumeSize: 100
  subnets:
  - us-east-1a
  sysctlParameters:
  - net.core.dev_weight=3072
  - net.core.netdev_budget=12288
  - net.core.somaxconn=65536
  - net.ipv6.conf.all.disable_ipv6=1
  - net.ipv6.conf.default.disable_ipv6=1
  - net.netfilter.nf_conntrack_expect_max=2048

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T14:26:43Z"
  labels:
    kops.k8s.io/cluster: cluster.domain
  name: nodes-us-east-1b
spec:
  cloudLabels:
    LayerDetail: kubernetes-node
    k8s.io/cluster-autoscaler/cluster.domain: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
  image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  maxSize: 4
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - m6a.2xlarge
    - m6i.2xlarge
    - m5.2xlarge
    - m5a.2xlarge
    - m5d.2xlarge
    - m5zn.2xlarge
    - m6id.2xlarge
    - r5.2xlarge
    - r5a.2xlarge
    - r5ad.2xlarge
    - r5b.2xlarge
    - r5d.2xlarge
    - r5dn.2xlarge
    - r5n.2xlarge
    - r6a.2xlarge
    - r6i.2xlarge
    - r6id.2xlarge
    - t3.2xlarge
    - t3a.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 1
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    autoscalegroup: nodes
    kops.k8s.io/instancegroup: nodes-us-east-1b
  role: Node
  rollingUpdate:
    maxSurge: 50%
  rootVolumeOptimization: true
  rootVolumeSize: 100
  subnets:
  - us-east-1b
  sysctlParameters:
  - net.core.dev_weight=3072
  - net.core.netdev_budget=12288
  - net.core.somaxconn=65536
  - net.ipv6.conf.all.disable_ipv6=1
  - net.ipv6.conf.default.disable_ipv6=1
  - net.netfilter.nf_conntrack_expect_max=2048

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T14:26:43Z"
  labels:
    kops.k8s.io/cluster: cluster.domain
  name: nodes-us-east-1c
spec:
  cloudLabels:
    LayerDetail: kubernetes-node
    k8s.io/cluster-autoscaler/cluster.domain: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
  image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  maxSize: 4
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - m6a.2xlarge
    - m6i.2xlarge
    - m5.2xlarge
    - m5a.2xlarge
    - m5d.2xlarge
    - m5zn.2xlarge
    - m6id.2xlarge
    - r5.2xlarge
    - r5a.2xlarge
    - r5ad.2xlarge
    - r5b.2xlarge
    - r5d.2xlarge
    - r5dn.2xlarge
    - r5n.2xlarge
    - r6a.2xlarge
    - r6i.2xlarge
    - r6id.2xlarge
    - t3.2xlarge
    - t3a.2xlarge
    onDemandAboveBase: 0
    onDemandBase: 1
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    autoscalegroup: nodes
    kops.k8s.io/instancegroup: nodes-us-east-1c
  role: Node
  rollingUpdate:
    maxSurge: 50%
  rootVolumeOptimization: true
  rootVolumeSize: 100
  subnets:
  - us-east-1c
  sysctlParameters:
  - net.core.dev_weight=3072
  - net.core.netdev_budget=12288
  - net.core.somaxconn=65536
  - net.ipv6.conf.all.disable_ipv6=1
  - net.ipv6.conf.default.disable_ipv6=1
  - net.netfilter.nf_conntrack_expect_max=2048
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
