### ISSUE TITLE
"Error: uploading object to S3 bucket" when using Terraform "The bucket does not allow ACLs"

### ISSUE THREAD

**Issue by JustinLex** [kubernetes/kops#15353]
/kind bug

I'm trying to use kOps 1.26.2 to generate terraform code for a new IPv6 Kubernetes cluster on AWS.

I ran the following kOps command to generate the Terraform config:
```commandline
kops create cluster \
  --name=${NAME} \
  --state=${KOPS_STATE_STORE} \
  --dns-zone=${NAME}\
  --ipv6 \
  --topology private \
  --cloud=aws \
  --node-count 4 \
  --zones us-west-2a,us-west-2b,us-west-2c,us-west-2d \
  --control-plane-zones us-west-2a,us-west-2b,us-west-2c \
  --discovery-store=${KOPS_STATE_STORE}/${NAME}/discovery \
  --node-size m6a.large \
  --master-size m6a.large \
  --network-id ${VPC_ID} \
  --out=. \
  --target=terraform
```

The console output of `kops create` was this:
```
I0428 10:31:31.077373  217521 new_cluster.go:1354] Cloud Provider ID: "aws"
I0428 10:31:33.005683  217521 subnets.go:185] Assigned CIDR 10.0.32.0/19 to subnet dualstack-us-west-2a
I0428 10:31:33.005735  217521 subnets.go:185] Assigned CIDR 10.0.64.0/19 to subnet dualstack-us-west-2b
I0428 10:31:33.005761  217521 subnets.go:185] Assigned CIDR 10.0.96.0/19 to subnet dualstack-us-west-2c
I0428 10:31:33.005784  217521 subnets.go:185] Assigned CIDR 10.0.128.0/19 to subnet dualstack-us-west-2d
I0428 10:31:33.005811  217521 subnets.go:199] Assigned CIDR 10.0.0.0/22 to subnet utility-us-west-2a
I0428 10:31:33.005835  217521 subnets.go:199] Assigned CIDR 10.0.4.0/22 to subnet utility-us-west-2b
I0428 10:31:33.005858  217521 subnets.go:199] Assigned CIDR 10.0.8.0/22 to subnet utility-us-west-2c
I0428 10:31:33.005881  217521 subnets.go:199] Assigned CIDR 10.0.12.0/22 to subnet utility-us-west-2d
I0428 10:31:50.084774  217521 issuerdiscovery.go:95] serviceAccountIssuers bucket "REDACTED" is not public; will use object ACL
I0428 10:31:50.854834  217521 executor.go:111] Tasks: 0 done / 186 total; 60 can run
W0428 10:31:51.551592  217521 vfs_castore.go:383] CA private key was not found
I0428 10:31:51.553119  217521 keypair.go:224] Issuing new certificate: "etcd-manager-ca-events"
I0428 10:31:51.557757  217521 keypair.go:224] Issuing new certificate: "etcd-peers-ca-events"
I0428 10:31:51.708004  217521 keypair.go:224] Issuing new certificate: "etcd-peers-ca-main"
I0428 10:31:51.715564  217521 keypair.go:224] Issuing new certificate: "apiserver-aggregator-ca"
I0428 10:31:51.717156  217521 keypair.go:224] Issuing new certificate: "etcd-manager-ca-main"
I0428 10:31:51.727082  217521 keypair.go:224] Issuing new certificate: "etcd-clients-ca"
W0428 10:31:51.915905  217521 vfs_castore.go:383] CA private key was not found
I0428 10:31:52.103196  217521 keypair.go:224] Issuing new certificate: "kubernetes-ca"
I0428 10:31:52.197868  217521 keypair.go:224] Issuing new certificate: "service-account"
I0428 10:31:55.188032  217521 executor.go:111] Tasks: 60 done / 186 total; 36 can run
I0428 10:31:55.642946  217521 executor.go:111] Tasks: 96 done / 186 total; 43 can run
I0428 10:31:55.646279  217521 executor.go:111] Tasks: 139 done / 186 total; 11 can run
I0428 10:31:56.465822  217521 executor.go:111] Tasks: 150 done / 186 total; 22 can run
I0428 10:31:57.574561  217521 executor.go:111] Tasks: 172 done / 186 total; 7 can run
I0428 10:31:57.576092  217521 executor.go:111] Tasks: 179 done / 186 total; 7 can run
I0428 10:31:57.577484  217521 executor.go:111] Tasks: 186 done / 186 total; 0 can run
I0428 10:31:57.597911  217521 target.go:116] Terraform output is in .
I0428 10:31:57.655858  217521 update_cluster.go:323] Exporting kubeconfig for cluster
W0428 10:31:57.861063  217521 create_kubecfg.go:69] Did not find API endpoint; may not be able to reach cluster
kOps has set your kubectl context to production.REDACTED.k8s.local
```

However, when applying the terraform module it generated (the module is called from a bigger terraform module that created the S3 buckets and VPC), Terraform Cloud gives the following errors: 
```json
{"@level":"error","@message":"Error: uploading object to S3 bucket (REDACTED-kops-state-store): AccessControlListNotSupported: The bucket does not allow ACLs\n\tstatus code: 400, request id: REDACTED, host id: REDACTED","@module":"terraform.ui","@timestamp":"2023-04-28T09:12:02.370791Z","diagnostic":{"severity":"error","summary":"uploading object to S3 bucket (REDACTED-kops-state-store): AccessControlListNotSupported: The bucket does not allow ACLs\n\tstatus code: 400, request id: REDACTED, host id: REDACTED","detail":"","address":"module.kops_production.aws_s3_object.keys-json","range":{"filename":"modules/kops_production/kubernetes.tf","start":{"line":1630,"column":38,"byte":78778},"end":{"line":1630,"column":39,"byte":78779}},"snippet":{"context":"resource \"aws_s3_object\" \"keys-json\"","code":"resource \"aws_s3_object\" \"keys-json\" {","start_line":1630,"highlight_start_offset":37,"highlight_end_offset":38,"values":[]}},"type":"diagnostic"}
{"@level":"error","@message":"Error: uploading object to S3 bucket (REDACTED-kops-state-store): AccessControlListNotSupported: The bucket does not allow ACLs\n\tstatus code: 400, request id: REDACTED, host id: REDACTED","@module":"terraform.ui","@timestamp":"2023-04-28T09:12:02.397289Z","diagnostic":{"severity":"error","summary":"uploading object to S3 bucket (REDACTED-kops-state-store): AccessControlListNotSupported: The bucket does not allow ACLs\n\tstatus code: 400, request id: REDACTED, host id: REDACTED","detail":"","address":"module.kops_production.aws_s3_object.discovery-json","range":{"filename":"modules/kops_production/kubernetes.tf","start":{"line":1608,"column":43,"byte":77808},"end":{"line":1608,"column":44,"byte":77809}},"snippet":{"context":"resource \"aws_s3_object\" \"discovery-json\"","code":"resource \"aws_s3_object\" \"discovery-json\" {","start_line":1608,"highlight_start_offset":42,"highlight_end_offset":43,"values":[]}},"type":"diagnostic"}
```

Because of this, two files are not uploaded to the S3 bucket, that should be uploaded.

I suspect that this is related to a breaking change that AWS made to the S3 API in April 2023, which affects how ACLs can be used in terraform.

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

https://github.com/hashicorp/terraform-provider-aws/issues/28353

Here are the terraform resources that were used to create the state-store bucket:
```terraform
resource "aws_s3_bucket" "state_store" {
  bucket = "${local.name}-kops-state-store"

  tags = {
    Name        = "${local.name}-kops-state-store"
  }
}
resource "aws_s3_bucket_versioning" "state_store" {
  bucket = aws_s3_bucket.state_store.id
  versioning_configuration {
    status = "Enabled"
  }
}
```

And here are the terraform resources that kOps created that are failing:
```terraform
resource "aws_s3_object" "discovery-json" {
  acl      = "public-read"
  bucket   = "REDACTED-kops-state-store"
  content  = file("${path.module}/data/aws_s3_object_discovery.json_content")
  key      = "production.REDACTED.k8s.local/discovery/production.REDACTED.k8s.local/.well-known/openid-configuration"
  provider = aws.files
}
resource "aws_s3_object" "keys-json" {
  acl      = "public-read"
  bucket   = "REDACTED-kops-state-store"
  content  = file("${path.module}/data/aws_s3_object_keys.json_content")
  key      = "production.REDACTED.k8s.local/discovery/production.REDACTED.k8s.local/openid/v1/jwks"
  provider = aws.files
}

```

Here is the Cluster YAML kOps generated:

```yaml
kind: Cluster
metadata:
  creationTimestamp: "2023-04-28T08:31:34Z"
  name: production.REDACTED.k8s.local
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudControllerManager: {}
  cloudProvider: aws
  configBase: s3://REDACTED-kops-state-store/production.REDACTED.k8s.local
  dnsZone: production.REDACTED.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.26.3
  networkCIDR: 10.0.0.0/16
  networkID: vpc-REDACTED
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: ::/0
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://REDACTED-kops-state-store/production.REDACTED.k8s.local/discovery/production.REDACTED.k8s.local
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - ipv6CIDR: /64#0
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - ipv6CIDR: /64#1
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - ipv6CIDR: /64#2
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - ipv6CIDR: /64#3
    name: us-west-2d
    type: Private
    zone: us-west-2d
  - cidr: 10.0.32.0/19
    ipv6CIDR: /64#4
    name: dualstack-us-west-2a
    type: DualStack
    zone: us-west-2a
  - cidr: 10.0.64.0/19
    ipv6CIDR: /64#5
    name: dualstack-us-west-2b
    type: DualStack
    zone: us-west-2b
  - cidr: 10.0.96.0/19
    ipv6CIDR: /64#6
    name: dualstack-us-west-2c
    type: DualStack
    zone: us-west-2c
  - cidr: 10.0.128.0/19
    ipv6CIDR: /64#7
    name: dualstack-us-west-2d
    type: DualStack
    zone: us-west-2d
  - cidr: 10.0.0.0/22
    ipv6CIDR: /64#8
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.0.4.0/22
    ipv6CIDR: /64#9
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 10.0.8.0/22
    ipv6CIDR: /64#a
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  - cidr: 10.0.12.0/22
    ipv6CIDR: /64#b
    name: utility-us-west-2d
    type: Utility
    zone: us-west-2d
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:36Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: control-plane-us-west-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - dualstack-us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:36Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: control-plane-us-west-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - dualstack-us-west-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:36Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: control-plane-us-west-2c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - dualstack-us-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:37Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: nodes-us-west-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:37Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: nodes-us-west-2b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:38Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: nodes-us-west-2c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-28T08:31:38Z"
  labels:
    kops.k8s.io/cluster: production.REDACTED.k8s.local
  name: nodes-us-west-2d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6a.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2d

```
