### ISSUE TITLE
OpenStack: kOps cannot create router when LB support is disabled

### ISSUE THREAD

**Issue by ederst** [kubernetes/kops#15401]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Client version: 1.26.3 (git-v1.26.3)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
1.26.x
```

**3. What cloud provider are you using?**

`openstack`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops update cluster --yes
```

Configure a cluster where kOps has to provision the network by itself but without letting kOps provision an LB; excerpt:

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: some-test-cluster.k8s.local
spec:
  api: {}
  cloudConfig:
    openstack
      router:
        externalNetwork: <name or id of extnet>
  cloudProvider: openstack
  # do not set to let kOps provision network
  # networkID: <TBD>
```

**5. What happened after the commands executed?**

```
goroutine 325 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/openstack.(*openstackCloud).GetExternalNetwork(0x140014afa40?)
        k8s.io/kops/upup/pkg/fi/cloudup/openstack/network.go:154 +0x20
k8s.io/kops/upup/pkg/fi/cloudup/openstacktasks.(*Router).RenderOpenstack(0x5?, 0x14000d38170, 0x14001054d80?, 0x14001716540, 0x2?)
        k8s.io/kops/upup/pkg/fi/cloudup/openstacktasks/router.go:103 +0x320
```

**6. What did you expect to happen?**

I expected kOps to provision the cluster and its infrastructure - network, router, nodes, etc.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

see above

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

-

**9. Anything else do we need to know?**

The problem seems to be that when kOps does not manage the LBs it will not set the `openstackCloud.extNetworkName`:

https://github.com/kubernetes/kops/blob/3b5c99d3c5025b604d426a7f0c79d066ce2ad755/upup/pkg/fi/cloudup/openstack/cloud.go#L450-L466

This leads to the the nil pointer here:

https://github.com/kubernetes/kops/blob/3b5c99d3c5025b604d426a7f0c79d066ce2ad755/upup/pkg/fi/cloudup/openstack/network.go#L153-L155

This was probably introduced with https://github.com/kubernetes/kops/pull/14742 which mitigated some issues of https://github.com/kubernetes/kops/issues/14546.

The solution to the bug would be to set the `extNetworkName` even if LB support is not wanted, so that the router can be created.
