### ISSUE TITLE
No OpenIDConnect provider found - After enabling pod identity webhook

### ISSUE THREAD

**Issue by DekelDevunet** [kubernetes/kops#15429]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.26.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.24.3

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I am trying to add to existing kops cluster pod identity webhook feature following the next blog post https://dev.to/olemarkus/zero-configuration-irsa-on-kops-1po1.

My configuration is as follow:

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s
spec:
  api:
    loadBalancer:
      class: Network
      type: Internal
  authorization:
    rbac: {}
  certManager:
    enabled: true
    managed: true
  channel: stable
  cloudProvider: aws
  configBase: s3://bucket
  dnsZone: dnszone
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    serviceAccountExternalPermissions:
    - aws:
        policyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      name: pod-identity-webhook-test
      namespace: default
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.24.3
  networkCIDR: 172.30.0.0/16
  networkID: vpc
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  podIdentityWebhook:
    enabled: true
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://public-bucket-oidc
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.30.20.0/24
    egress: nat
    name: eu-west-2a
    type: Private
    zone: eu-west-2a
  - cidr: 172.30.21.0/27
    name: utility-eu-west-2a
    type: Utility
    zone: eu-west-2a
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```  

yaml to check IRSA:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-identity-webhook-test
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-identity-webhook-test
  namespace: default
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
    - sleep
    - "300"
  serviceAccountName: "pod-identity-webhook-test"
```

**5. What happened after the commands executed?**
Pod identity webhook and cert-manager pods are available but when testing `kubectl exec -it -n default pod-identity-webhook-test -- aws sts get-caller-identity`  the IRSA I am getting the following error:

```
An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: No OpenIDConnect provider found in your account for https://api.k8s
```

**6. What did you expect to happen?**
I expected to get caller identity

**7. Anything else do we need to know?**
I want to emphasis that I am working on cluster that currently doesn't have IRSA enabled and I am trying to enabled it.

**Comment by olemarkus** [comment]
podIdentityWebhook doesn't use IRSA. It doesn't require talking to the AWS APIs.

**Comment by DekelDevunet** [comment]
@olemarkus So, what am I missing?

**Comment by olemarkus** [comment]
I don't see anything in your description above that isn't working as expected. You are only doing an STS call from a pod that doesn't have an IAM role (and shouldn't have one). Try doing that from a Pod that has one instead.

**Comment by DekelDevunet** [comment]
@olemarkus Thanks for the help. 

I updated the test service account with the following setup:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-identity-webhook-test
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1111111111111:role/pod-identity-webhook-test.default.sa.k8s-cluster
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-identity-webhook-test
  namespace: default
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
    - sleep
    - "300"
  serviceAccountName: "pod-identity-webhook-test"
```

But the issue is still there.

I will also add that on the Kubernetes API server, there is no mention to oidc args (https://kops.sigs.k8s.io/cluster_spec/#oidc-flags-for-open-id-connect-tokens). 

I tried to add to the cluster yaml the following:
```
[...]
  kubeAPIServer:
    oidcClientID: kubernetes
    oidcIssuerURL: https://public-bucket-oidc.s3.eu-west-2.amazonaws.com
[...]
```
