### ISSUE TITLE
Metrics server pods are not created

### ISSUE THREAD

**Issue by rodorgas** [kubernetes/kops#15442]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.26.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.26.5

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I upgraded Kubernetes with `kops upgrade cluster`. After that, metrics server stopped working.

**5. What happened after the commands executed?**
Upgrade went ok, but metrics server stopped working. For example, pods are not created:

```
$ kubectl get pods -n kube-system
E0523 12:19:49.672992   34311 memcache.go:287] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0523 12:19:49.851728   34311 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0523 12:19:50.008474   34311 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0523 12:19:50.162006   34311 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
NAME                                          READY   STATUS    RESTARTS   AGE
aws-cloud-controller-manager-86vbg            1/1     Running   0          14m
calico-kube-controllers-59d58646f4-96k24      1/1     Running   0          19m
calico-node-5k2pd                             1/1     Running   0          6m51s
calico-node-l9q7m                             1/1     Running   0          14m
calico-node-wp5kt                             1/1     Running   0          10m
cert-manager-69fc68cbb6-jkpw9                 1/1     Running   0          19m
cert-manager-cainjector-7c4676959f-s44vx      1/1     Running   0          19m
cert-manager-webhook-6578d57db6-9ntl9         1/1     Running   0          19m
coredns-6fc48fb996-2q5tt                      1/1     Running   0          5m14s
coredns-6fc48fb996-r4f5w                      1/1     Running   0          4m1s
coredns-autoscaler-5fc98c7959-9jh6g           1/1     Running   0          5m15s
dns-controller-69f4974b6f-zrnkb               1/1     Running   0          19m
ebs-csi-controller-84f5bbc6b4-8f9jk           5/5     Running   0          13m
ebs-csi-node-cglhh                            3/3     Running   0          14m
ebs-csi-node-dqghc                            3/3     Running   0          6m51s
ebs-csi-node-f9nhk                            3/3     Running   0          10m
etcd-manager-events-i-0e3400820560f69cb       1/1     Running   0          14m
etcd-manager-main-i-0e3400820560f69cb         1/1     Running   0          13m
kops-controller-h4mds                         1/1     Running   0          14m
kube-apiserver-i-0e3400820560f69cb            2/2     Running   0          15m
kube-controller-manager-i-0e3400820560f69cb   1/1     Running   0          13m
kube-proxy-i-072debe3997e3aadc                1/1     Running   0          6m50s
kube-proxy-i-0e3400820560f69cb                1/1     Running   0          14m
kube-proxy-i-0fd9a267e4f83093d                1/1     Running   0          10m
kube-scheduler-i-0e3400820560f69cb            1/1     Running   0          14m
kube-state-metrics-f46f447f5-pl6h7            1/1     Running   0          5m14s
```

**6. What did you expect to happen?**
I expected metrics server to work, like it was before the upgrade.

```
$ kubectl top pods
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-10-21T21:29:37Z"
  generation: 9
  name: example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: s3://example.com/example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-2a
      name: a
    memoryRequest: 100Mi
    name: events
  externalDns:
    watchIngress: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.26.5
  masterPublicName: api.example.com
  metricsServer:
    enabled: true
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-10-21T21:29:38Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: example.com
  name: master-us-east-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230502
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-10-21T21:29:38Z"
  generation: 13
  labels:
    kops.k8s.io/cluster: example.com
  name: nodes-us-east-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230502
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3a.medium
  maxSize: 2
  minSize: 2
  role: Node
  rootVolumeSize: 64
  subnets:
  - us-east-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**
The service is created, but there are no pods. Are there any tips for debugging this issue? Without pods I can't look at logs.
```
$ kubectl get service metrics-server -n kube-system
E0523 12:28:33.191542   35151 memcache.go:287] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0523 12:28:33.517819   35151 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0523 12:28:33.679998   35151 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0523 12:28:33.836750   35151 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
metrics-server   ClusterIP   100.69.1.148   <none>        443/TCP   213d
```

I tried to terminate the instances and let kOps recreate them several times, with the same result.
