### ISSUE TITLE
Pods with PVC can't be scheduled due to missing csi.hetzner.cloud driver in node

### ISSUE THREAD

**Issue by AlessandroSechi** [kubernetes/kops#15550]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.26.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 
 ```
 Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
 ```

**3. What cloud provider are you using?**

Hetzner

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Added a new node to a 2 nodes cluster with `kops edit ig my-node`, then `minSize: 3` and `maxSize: 3`
Applied changes with `kops update cluster --yes`

Then `kops validate cluster` returns `Your cluster cluster1.fsn1.hetzner.mywebsite.com is ready`

**5. What happened after the commands executed?**

No pods which uses PVC can be scheduled. In `describe pod` I see

```
Warning  FailedAttachVolume  5s    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-60560158-d8b4-4908-aa6f-8df0c53d810e" : rpc error: code = NotFound desc = failed to publish volume: volume not found
AttachVolume.Attach failed for volume "pvc-60560158-d8b4-4908-aa6f-8df0c53d810e" : CSINode nodes-fsn1-67d56c4deadcd70f does not contain driver csi.hetzner.cloud
```

**6. What did you expect to happen?**

Have ability to run pods using PVC

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-05-04T18:26:50Z"
  name: cluster1.fsn1.hetzner.mywebsite.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: hetzner
  configBase: do://hetznerk8skopscluster/cluster1.fsn1.hetzner.mywebsite.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-fsn1-1
      name: etcd-1
    - instanceGroup: control-plane-fsn1-2
      name: etcd-2
    - instanceGroup: control-plane-fsn1-3
      name: etcd-3
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-fsn1-1
      name: etcd-1
    - instanceGroup: control-plane-fsn1-2
      name: etcd-2
    - instanceGroup: control-plane-fsn1-3
      name: etcd-3
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.26.3
  networkCIDR: 10.10.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - name: fsn1
    type: Public
    zone: fsn1
  topology:
    dns:
      type: None
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-04T18:26:51Z"
  labels:
    kops.k8s.io/cluster: cluster1.fsn1.hetzner.mywebsite.com
  name: control-plane-fsn1-1
spec:
  image: debian-11
  machineType: cpx11
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - fsn1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-04T18:26:51Z"
  labels:
    kops.k8s.io/cluster: cluster1.fsn1.hetzner.mywebsite.com
  name: control-plane-fsn1-2
spec:
  image: debian-11
  machineType: cpx11
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - fsn1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-04T18:26:51Z"
  labels:
    kops.k8s.io/cluster: cluster1.fsn1.hetzner.mywebsite.com
  name: control-plane-fsn1-3
spec:
  image: debian-11
  machineType: cpx11
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - fsn1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-04T18:26:51Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster1.fsn1.hetzner.mywebsite.com
  name: nodes-fsn1
spec:
  image: debian-11
  machineType: cpx21
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - fsn1
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
