### ISSUE TITLE
MIME Headers in Startup Script causing "Command not found" error

### ISSUE THREAD

**Issue by volade** [kubernetes/kops#15589]
/kind bug

I'm using Kops on GCE. I'm able to successfully set up a cluster but there appears to be a bug when I use additionalUserData to add custom code to the metadata startup script.

The MIME headers are getting included in the script which then throws a "command not found" error since it attempts to execute those headers as shell commands.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.26.4

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.26.6

**3. What cloud provider are you using?**

GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create -f desktop-kops.yml --state ${KOPS_STATE_STORE}
kops update cluster --name sample.k8s.local --yes --state ${KOPS_STATE_STORE} --admin

**5. What happened after the commands executed?**

The Cluster gets created successfully but the startup script has the MIME headers in it which causes problems.

**6. What did you expect to happen?**

I expected the command I added via the additionalUserData key to run at startup. I see it added to the startup script but the fact the MIME headers are there causes the script to fail.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: sample.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  kubernetesApiAccess:
  - 0.0.0.0/0
  sshAccess:
  - 0.0.0.0/0
  project: ubuntu-desktop-migration
  subnets:
  - cidr: 10.10.0.0/21
    name: node-subnet
    type: Public
    region: us-central1
    stackType: IPV4_ONLY
    natGateway: true
    PublicIp: 34.xxx.xx.xx
  cloudProvider: gce
  etcdClusters:
  - etcdMembers:
    - instanceGroup: controller-instance
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: controller-instance
      name: a
    name: events
  networking:
    calico: {}
  metricsServer:
    enabled: true
    insecure: true
  kubeDNS:
    provider: coredns
  kubelet:
    anonymousAuth: false
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: sample.k8s.local
  name: controller-instance
spec:
  additionalUserData:
  - name: arunstartupctrl.sh
    type: text/x-shellscript
    content: |
      #!/bin/bash
       sudo chmod 1777 /tmp
  role: ControlPlane
  image: ubuntu-os-cloud/ubuntu-2204-jammy-v20230616
  rootVolume: 20
  associatePublicIP: true
  machineType: e2-standard-4
  minSize: 1
  maxSize: 1
  gcpProvisioningModel: STANDARD
  zones: 
  - us-central1-a
  subnets:
  - node-subnet
  
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: sample.k8s.local
  name: node-instance
spec:
  role: Node
  image: ubuntu-os-cloud/ubuntu-2204-jammy-v20230616
  rootVolume: 30
  associatePublicIP: false
  machineType: e2-standard-8
  minSize: 1
  maxSize: 10
  gcpProvisioningModel: SPOT
  zones:
  - us-central1-a
  subnets:
  - node-subnet
  additionalUserData:
  - name: arunstartupnodes.sh
    type: text/x-shellscript
    content: |
      #!/bin/bash
      sudo chmod 1777 /tmp

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

When I remove the additionalUserData part of the yml file the startup script doesn't have any MIME headers and runs successfully. 

startup script **with** additionalUserData:
```
startup-script	
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Disposition: attachment; filename="nodeup.sh"
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

```
startup script **without** additionalUserData:
```
startup-script	
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
```
