### ISSUE TITLE
OpenStack - kops does not add rules for load balancers

### ISSUE THREAD

**Issue by valentin-ricard** [kubernetes/kops#15582]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
v1.26.2
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.26.5
**3. What cloud provider are you using?**
OpenStack (infomaniak)
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create a cluster, following the tutorial, and once that is done, create a load-balancer inside k8s, with the following manifest:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: service-2
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
```

**5. What happened after the commands executed?**
The load-balancer is created correctly, but it immediately goes into error mode after deployment because it cannot communicate with the nodes on the given port.

This is due to the default security group configuration, that does not include the `NodePort` range for communication with the load-balancer.
**6. What did you expect to happen?**
The loadbalancer should connect directly, instead of having to manually create a security group rule, that will have to be added again at each update: 
```
Will delete items:
  SecurityGroupRule     port=30000-32767 protocol=tcp ip=10.1.0.0/16 securitygroup=nodes.clustername.k8s.local
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-07-02T15:18:16Z"
  generation: 2
  name: clustername.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        clusterName: clustername.k8s.local
        ignore-volume-az: true
        override-volume-az: nova
      loadbalancer:
        floatingNetwork: ext-floating1
        floatingNetworkID: 0f9c3806-bd21-490f-918d-4a6d1c648489
        method: ROUND_ROBIN
        provider: octavia
        useOctavia: true
      monitor:
        delay: 15s
        maxRetries: 3
        timeout: 10s
      router:
        dnsServers: dns1,dns2
        externalNetwork: ext-floating1
  cloudControllerManager:
    clusterName: clustername.k8s.local
  cloudProvider: openstack
  configBase: swift://kops/clustername.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-dc3-a-04
      name: etcd-04
      volumeType: CEPH_1_perf1
    - instanceGroup: control-plane-dc3-a-09
      name: etcd-09
      volumeType: CEPH_1_perf1
    - instanceGroup: control-plane-dc3-a-10
      name: etcd-10
      volumeType: CEPH_1_perf1
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-dc3-a-04
      name: etcd-04
      volumeType: CEPH_1_perf1
    - instanceGroup: control-plane-dc3-a-09
      name: etcd-09
      volumeType: CEPH_1_perf1
    - instanceGroup: control-plane-dc3-a-10
      name: etcd-10
      volumeType: CEPH_1_perf1
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.26.5
  networkCIDR: 10.1.0.0/24
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.1.0.32/27
    name: dc3-a-04
    type: Private
    zone: dc3-a-04
  - cidr: 10.1.0.64/27
    name: dc3-a-09
    type: Private
    zone: dc3-a-09
  - cidr: 10.1.0.96/27
    name: dc3-a-10
    type: Private
    zone: dc3-a-10
  - cidr: 10.1.0.0/30
    name: utility-dc3-a-04
    type: Utility
    zone: dc3-a-04
  - cidr: 10.1.0.4/30
    name: utility-dc3-a-09
    type: Utility
    zone: dc3-a-09
  - cidr: 10.1.0.8/30
    name: utility-dc3-a-10
    type: Utility
    zone: dc3-a-10
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-02T15:18:16Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: control-plane-dc3-a-04
spec:
  image: Debian 11 bullseye
  machineType: a2-ram4-disk20-perf1
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - dc3-a-04

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-02T15:18:16Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: control-plane-dc3-a-09
spec:
  image: Debian 11 bullseye
  machineType: a2-ram4-disk20-perf1
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - dc3-a-09

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-02T15:18:17Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: control-plane-dc3-a-10
spec:
  image: Debian 11 bullseye
  machineType: a2-ram4-disk20-perf1
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - dc3-a-10

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-02T15:18:17Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: nodes-dc3-a-04
spec:
  image: Debian 11 bullseye
  machineType: a1-ram2-disk20-perf1
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - dc3-a-04

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-02T15:18:17Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: nodes-dc3-a-09
spec:
  image: Debian 11 bullseye
  machineType: a1-ram2-disk20-perf1
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - dc3-a-09

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-07-02T15:18:17Z"
  labels:
    kops.k8s.io/cluster: clustername.k8s.local
  name: nodes-dc3-a-10
spec:
  image: Debian 11 bullseye
  machineType: a1-ram2-disk20-perf1
  maxSize: 0
  minSize: 0
  role: Node
  subnets:
  - dc3-a-10
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Is it applicable here?

**9. Anything else do we need to know?**
Adding a way to set custom rules directly to the config would also resolve the issue.

**Comment by valentin-ricard** [comment]
Found a solution for this.
While this is not documented, there is an option in the ClusterSpec that allows for exactly that:
```yaml
spec:
  nodePortAccess:
  - 10.1.0.0/16
```
