### ISSUE TITLE
Cannot use same Instance ID as `egress` across multiple subnets

### ISSUE THREAD

**Issue by m1n-q** [kubernetes/kops#15624]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.26.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.26.6

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Want to use shared NAT instance between subnets

`kops edit cluster`, and set same ID to each subnet egresses
```yaml
...
  subnets:
  - cidr: 172.20.32.0/19
    egress: i-987654321
    name: ap-northeast-2a
    type: Private
    zone: ap-northeast-2a
  - cidr: 172.20.64.0/19
    egress: i-987654321
    name: ap-northeast-2c
    type: Private
    zone: ap-northeast-2c
...
```
and `kops update cluster --yes --admin`

**5. What happened after the commands executed?**

```

F0712 18:15:51.599311   12356 task.go:133] found duplicate tasks with name "Instance/i-987654321": *awstasks.Instance {"ID":"i-987654321","Lifecycle":"Sync","UserData":null,"Subnet":null,"PrivateIPAddress":null,"Name":"i-987654321","Tags":null,"Shared":true,"ImageID":null,"InstanceType":null,"SSHKey":null,"SecurityGroups":null,"AssociatePublicIP":null,"IAMInstanceProfile":null} and 
*awstasks.Instance {"ID":"i-987654321","Lifecycle":"Sync","UserData":null,"Subnet":null,"PrivateIPAddress":null,"Name":"i-987654321","Tags":null,"Shared":true,"ImageID":null,"InstanceType":null,"SSHKey":null,"SecurityGroups":null,"AssociatePublicIP":null,"IAMInstanceProfile":null}
```

**6. What did you expect to happen?**

Share my existing NAT Instance between all private subnets.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-04-17T06:22:01Z"
  generation: 14
  name: backend-cluster.k8s.local
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: <s3://>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.26.6
  metricsServer:
    enabled: true
  networkCIDR: 172.20.0.0/16
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  podIdentityWebhook:
    enabled: true
  serviceAccountIssuerDiscovery:
    discoveryStore: <s3://>
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    egress: i-987654321
    name: ap-northeast-2a
    type: Private
    zone: ap-northeast-2a
  - cidr: 172.20.64.0/19
    egress: i-987654321
    name: ap-northeast-2c
    type: Private
    zone: ap-northeast-2c
  - cidr: 172.20.0.0/22
    name: utility-ap-northeast-2a
    type: Utility
    zone: ap-northeast-2a
  - cidr: 172.20.4.0/22
    name: utility-ap-northeast-2c
    type: Utility
    zone: ap-northeast-2c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-17T06:22:01Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: backend-cluster.k8s.local
  name: control-plane-ap-northeast-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230616
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-northeast-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-17T06:22:02Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: backend-cluster.k8s.local
  name: nodes-ap-northeast-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230616
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - ap-northeast-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-04-17T06:22:02Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: backend-cluster.k8s.local
  name: nodes-ap-northeast-2c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230616
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3a.small
  maxSize: 0
  minSize: 0
  role: Node
  subnets:
  - ap-northeast-2c

```
