### ISSUE TITLE
ClusterID missing in Cilium

### ISSUE THREAD

**Issue by zadjadr** [kubernetes/kops#15633]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
this information.**

`Client version: 1.26.4 (git-v1.26.4)`

**2. What Kubernetes version are you running? `kubectl version` will print the
version if a cluster is running or provide the Kubernetes version specified as
a `kops` flag.**

```
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.3",
    "gitCommit": "25b4e43193bcda6c7328a6d147b1fb73a33f1598",
    "gitTreeState": "archive",
    "buildDate": "2023-06-15T16:18:27Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.3",
    "gitCommit": "25b4e43193bcda6c7328a6d147b1fb73a33f1598",
    "gitTreeState": "clean",
    "buildDate": "2023-06-14T09:47:40Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**3. What cloud provider are you using?**

`openstack`

**4. What commands did you run? What is the simplest way to reproduce this issue?**

After creating a cluster with cilium CNI and adding the `spec.networking.cilium.clusterName`, try to activate the cluster mesh:

```bash
cilium clustermesh enable --service-type LoadBalancer
```

**5. What happened after the commands executed?**

```bash
$ cilium clustermesh enable --service-type LoadBalancer

⚠️  Cluster not configured for clustermesh, use '--cluster-id' and '--cluster-name' with 'cilium install'. External workloads may still be configured.
```

**6. What did you expect to happen?**

I expected to have the `spec.networking.cilium.clusterID` setting in kops.

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: mycluster
spec:
  networking:
    cilium:
      clusterName: mycluster
      clusterID: 1 # expected to have this
 ```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
  labels:
    addon.kops.k8s.io/name: networking.cilium.io
    app.kubernetes.io/managed-by: kops
    role.kubernetes.io/networking: '1'
data:
  cluster-id: '1'  # expected this
  cluster-name: mycluster
```

**7. Please provide your cluster manifest.**

Execute
`kops get --name my.example.com -o yaml` to display your cluster manifest.
You may want to remove your cluster name and other sensitive information.\*\*

Here is the relevant part

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: mycluster
spec:
  networking:
    cilium:
      clusterName: mycluster
      clusterID: 1 # expected to have this
 ```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I fixed this by adding the `cluster-id` field to the config and restarting all cilium related workloads.

```bash
kubectl patch configmap cilium-config -n kube-system -p '{"data": {"cluster-id": "1"}}'
```
