### ISSUE TITLE
Request for guidance - pre-caching large container images on AWS AMIs for worker nodes

### ISSUE THREAD

**Issue by plaformsre** [kubernetes/kops#15696]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I would need your guidance on the best approach on how to pre-install container.d on the KOPS K8S worker node's AWS AMI (e.g. Ubuntu) so we can pre-cache large container images that might take a significant time for users. We would pull containers during the AMI creation/baking process using e.g. ctr.

**2. Feel free to provide a design supporting your feature request.**
we would need to know, if we could pre-install container.d without making the AMI failing when the worker node joins the Kubernetes cluster and boostraps. We would like to bring the cached layers on container.d on the AMI before the new worker node joins the cluster. This would significantly improve the user experience with large session images.

I worry, if the pre-installation of container.d and eventually not matching the correct version of container.d might cause future issues when the new worker nodes joins the K8S clyster and boostraps.

I would appreciate your guidance how best to approach worker nodes with pre-caching container.d container images.

Thank you.

**Comment by hakman** [comment]
I would suggest to bundle the container images as .tar files and use [additionalUserData](https://kops.sigs.k8s.io/instance_groups/#additionaluserdata) to load the images on boot:
```sh
ctr -n k8s.io image import <bundled_image.tar>
```

**Comment by johngmyers** [comment]
You can get a list of the container images to bake into your AMIs with [`kops get assets`](https://kops.sigs.k8s.io/cli/kops_get_assets/)

**Comment by hakman** [comment]
> Hi @hakman ,
> With that approach we would be still adding additional time to transfer the compressed files onto every single worker node and again, that would take in our case more than 5 minutes (for a new node).

How did you reach this conclusion?
I suggested to put the container images on your custom AMI, and just import them at boot time.

**Comment by wlawton** [comment]
I have a similar use case to @plaformsre in that I need my nodes to launch and startup as quickly as possible due to a sudden and rapid scaling of pods which requires a corresponding rapid scale-out of host nodes. To facilitate this we are using the warm pool feature of AWS autoscaling groups and have configured additionalUserData in the kops configuration to install nerdctl and pull images from AWS ECR. Our use case is not suitable for pre-loading a 'golden' AMI with the images since the image tags are highly dynamic. The image tags are sourced from AWS System Manager parameters, which are accessed via aws cli commands in the additionalUserData script.

If our additionalUserData script executes before nodeup.sh then we run into the containerd not installed yet problem, as highlighted by @plaformsre. If the additionalUserData script executes after nodeup.sh, the first nerdctl pull requests starts and appears to be going well according to cloud-init-output.log, but is then interrupted with a timeout error on /run/containerd/containerd.sock. My speculation is that this has occurred because the containerd process has been stopped as part of the node shut down process, which is happening because the nodeup.sh script completed the warm-pool lifecycle event indicating that the AWS ASG can now stop the warmed node.

Here is the relevant snipped from the log:
```
...
layer-sha256:5c12815fee558b157dee7f7509dedbaba0a8379098858a65ec869e1f1526ea0c:    done           |ESC[32m++++++++++++++++++++++++++++++++++++++ESC[0m| 
elapsed: 1.0 s                                                                    total:  11.0 M (11.0 MiB/s)                                      
time="2023-12-21T13:36:31Z" level=fatal msg="connection error: desc = \"transport: error while dialing: dial unix:///run/containerd/containerd.sock: timeout\": unavailable"
time="2023-12-21T13:36:31Z" level=fatal msg="cannot access containerd socket \"/run/containerd/containerd.sock\": no such file or directory"
...
```
I seem to be stuck between a rock and a hard place in terms of when my additional user data script is executed.

**Comment by wlawton** [comment]
I've just experimented by having my additionalUserData script install containerd, run the nerdctl pull commands and then uninstalling containerd again and it caused the nodeup process to get stuck at the point when it needs to restart containerd.service due to it having masked state. So I went back to my  additionalUserData script and added systemctl unmask containerd after apt remove -y containerd and subsequently the nodeup process works through to completion. So could be a good workaround.

**Comment by diversario** [comment]
We got it to work this way (this is ansible, but easy to translate into something else):

```yaml

- name: Install nerdctl
  unarchive:
    src: "https://github.com/containerd/nerdctl/releases/download/v{{ version }}/nerdctl-{{ version }}-linux-{{ cpu_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: true
  vars:
    version: 1.7.0

- name: Configure docker ECR auth
  shell: |
    mkdir -p /root/.docker
    echo '{"credsStore": "ecr-login"}' > /root/.docker/config.json

- name: Pre-pull container images
  loop: "{{ images }}"
  shell: |
    nerdctl -n k8s.io image pull {{ item }}
  vars:
    images:
    # if container spec uses sha you must specify it here as well
    # tag without the sha is optional in that case
    # check the actual pods to see what's being used
    - quay.io/cilium/cilium:v1.12.7
    - quay.io/cilium/cilium:v1.12.7@sha256:8cb6b4742cc27b39e4f789d282a1fc2041decb6f5698bfe09112085a07b1fd61

    # etc

# kops will install containerd and stuff
- name: Remove Docker
  apt:
    pkg:
    - docker.io
    - amazon-ecr-credential-helper
    state: absent
    autoremove: yes

- name: Unconfigure docker ECR auth
  file:
    path: /root/.docker
    state: absent

# uninstalling containerd makes the service "masked", meaning it won't start
- name: Unmask containerd service
  shell: |
    systemctl unmask containerd
```

This is with kops `1.26.3`.
