### ISSUE TITLE
Hetzner Cloud NodePort Access: rules contain duplicates (invalid_input)

### ISSUE THREAD

**Issue by marcopalmisano** [kubernetes/kops#15763]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
v1.27.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.27.3

**3. What cloud provider are you using?**
Hetzner

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Specify in cluster spec attribute `nodePortAccess` and try to add a rule.

**5. What happened after the commands executed?**
After specifying `nodePortAccess` rules, kOps started giving to me following error:
`error running task "Firewall/<my-cluster-name>" (56s remaining to succeed): rules contain duplicates (invalid_input)`

**6. What did you expect to happen?**
It should add specified firewall rules to nodes firewall.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 2
  name: my-cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: hetzner
  configBase: s3://kopsclusters/my-cluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: my-cluster-master-1
      name: etcd-0
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: my-cluster-master-1
      name: etcd-0
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.27.3
  networkCIDR: 10.1.0.0/16
  networking:
    calico: {}
  nodePortAccess:
  - 1.2.3.4/32
  - 1.2.3.4/32
  nonMasqueradeCIDR: 172.16.0.0/12
  sshAccess:
  - 1.2.3.4/32
  sshKeyName: sshpublickey
  subnets:
  - name: fsn1
    type: Private
    zone: fsn1
  topology:
    dns:
      type: None
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-08-10T14:19:57Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: my-cluster-master-1
spec:
  detailedInstanceMonitoring: true
  image: ubuntu-22.04
  machineType: cx21
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - fsn1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-08-10T14:19:58Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: my-cluster-nodes
spec:
  detailedInstanceMonitoring: true
  image: ubuntu-22.04
  machineType: cx41
  maxSize: 6
  minSize: 4
  role: Node
  subnets:
  - fsn1

```
