### ISSUE TITLE
healthCheckNodePort not working after upgrade to v1.24.14

### ISSUE THREAD

**Issue by viniciusps** [kubernetes/kops#15812]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`v1.25.2`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`v1.24.14`

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  creationTimestamp: null
  generation: 1
  name: xx
spec:
  additionalPolicies:
    master: |
      [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "elasticloadbalancing:ModifyLoadBalancerAttributes"
            ],
            "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      class: Classic
      type: Public
  assets:
    fileRepository: https://xx-assets
  authentication: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
      managed: false
  cloudProvider: aws
  configBase: s3://xx
  configStore: s3://xx
  dnsZone: xx
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: false
      instanceGroup: master-ap-southeast-2a
      name: a
      volumeSize: 128
    - encryptedVolume: false
      instanceGroup: master-ap-southeast-2b
      name: b
      volumeSize: 128
    - encryptedVolume: false
      instanceGroup: master-ap-southeast-2c
      name: c
      volumeSize: 128
    name: main
    version: 3.2.24
  - etcdMembers:
    - encryptedVolume: false
      instanceGroup: master-ap-southeast-2a
      name: a
    - encryptedVolume: false
      instanceGroup: master-ap-southeast-2b
      name: b
    - encryptedVolume: false
      instanceGroup: master-ap-southeast-2c
      name: c
    name: events
    version: 3.2.24
  fileAssets:
  - content: |
      apiVersion: audit.k8s.io/v1
      kind: Policy
      omitStages:
        - RequestReceived
      rules:
        - level: Metadata
    name: audit-policy-config
    path: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://xx/pki
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - ResourceQuota
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - TaintNodesByCondition
    - PersistentVolumeClaimResize
    - PodNodeSelector
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    disableBasicAuth: true
    featureGates:
      ExpandPersistentVolumes: "true"
    logLevel: 1
    oidcClientID: xxi.apps.googleusercontent.com
    oidcIssuerURL: https://accounts.google.com
    oidcUsernameClaim: email
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
    logLevel: 1
    nodeLocalDNS:
      enabled: false
    provider: CoreDNS
  kubeProxy:
    featureGates:
      ExpandPersistentVolumes: "true"
    logLevel: 1
    metricsBindAddress: 0.0.0.0
  kubeScheduler:
    featureGates:
      ExpandPersistentVolumes: "true"
    leaderElection:
      leaderElect: true
    logLevel: 1
    usePolicyConfigMap: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    featureGates:
      ExpandPersistentVolumes: "true"
    kubeletCgroups: /lib/systemd/system/system.slice
    logLevel: 1
    runtimeCgroups: /lib/systemd/system/system.slice
  kubernetesVersion: 1.24.14
  masterKubelet:
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    kubeletCgroups: /lib/systemd/system/system.slice
    logLevel: 1
    runtimeCgroups: /lib/systemd/system/system.slice
  masterPublicName: xx
  networkCIDR: xx/20
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://xx/secrets
  serviceClusterIPRange: xx/13
  sshAccess:
  - xx/32
  - xx/32
  subnets:
  - cidr: xx/23
    name: ap-southeast-2a
    type: Private
    zone: ap-southeast-2a
  - cidr: xx/23
    name: ap-southeast-2b
    type: Private
    zone: ap-southeast-2b
  - cidr: xx/23
    name: ap-southeast-2c
    type: Private
    zone: ap-southeast-2c
  - cidr: xx/26
    name: utility-ap-southeast-2a
    type: Utility
    zone: ap-southeast-2a
  - cidr: xx/26
    name: utility-ap-southeast-2b
    type: Utility
    zone: ap-southeast-2b
  - cidr: xx/26
    name: utility-ap-southeast-2c
    type: Utility
    zone: ap-southeast-2c
  topology:
    bastion:
      bastionPublicName: XXXXX
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Hi,

I just found a weird issue happening with our K8s cluster and the Network. This could be the Kops CNI configuration or not. I would like your help on this.

We have upgraded our cluster from v1.23.13 to v1.24.14 using kops (Currently not all worker nodes are running v1.24.14, some of them are still v1.23.13).

We have a Gloo Edge API gateway cluster which creates a AWS NLB and the services are exposed to the internet. Currently, when the Gloo edge pods are scheduled in the nodes running v1.24.14 the healthCheckNodePort fails, but when it gets scheduled on the nodes running v1.23.13 it works fine.

See my service config below:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: gloo
    argocd.argoproj.io/instance: gloo-dev
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: gloo-system-dev
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 100.67.139.1
  clusterIPs:
  - 100.67.139.1
  externalTrafficPolicy: Local
  healthCheckNodePort: 30672
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32594
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30451
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxx.elb.ap-southeast-2.amazonaws.com
```

The endpoints are:

```
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: gloo
    argocd.argoproj.io/instance: gloo-dev
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: gloo-system-dev

subsets:
- addresses:
  - ip: 100.96.36.59
    nodeName: yy.ap-southeast-2.compute.internal
    targetRef:
      kind: Pod
      name: gateway-proxy-668bf69f74-6gb6q
      namespace: gloo-system-dev
  - ip: 100.97.70.43
    nodeName:x.ap-southeast-2.compute.internal
    targetRef:
      kind: Pod
      name: gateway-proxy-668bf69f74-gdwnm
      namespace: gloo-system-dev
  ports:
  - name: https
    port: 8443
    protocol: TCP
  - name: http
    port: 8080
    protocol: TCP
```

Connecting to the yy instance (Running v1.24.14) I get:

```
ubuntu@yy:~$ curl localhost:30672/healthz
{
        "service": {
                "namespace": "gloo-system-dev",
                "name": "gateway-proxy"
        },
        "localEndpoints": 0
```

And connecting to the xx instance (Running v1.23.13) I get:

```
{
        "service": {
                "namespace": "gloo-system-dev",
                "name": "gateway-proxy"
        },
        "localEndpoints": 1
```

Working node:

`containerd github.com/containerd/containerd v1.6.8 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6`
`sh-4.4# calico-node -v
v3.23.5`

Non working node:

`containerd github.com/containerd/containerd v1.6.21 3dce8eb055cbb6872793272b4f20ed16117344f8`
`sh-4.4# calico-node --v      
v3.23.5`

My CNI network config:

```yaml
apiVersion: v1
data:
  canal_iface: ""
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "host-local",
              "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
  masquerade: "true"
  net-conf.json: |
    {
      "Network": "100.64.0.0/10",
      "Backend": {
        "Type": "vxlan"
      }
    }
  typha_service_name: none
  veth_mtu: "1440"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    addon.kops.k8s.io/name: networking.projectcalico.org.canal
    app.kubernetes.io/managed-by: kops
    role.kubernetes.io/networking: "1"
  name: canal-config
  namespace: kube-system
```

One interesting thing that I noticed is that the iptable rules are different:

Working node contains this rule that the non working node does not:

```
KUBE-MARK-MASQ  tcp  --  127.0.0.0/8          0.0.0.0/0            /* gloo-system-dev/gateway-proxy:https */ tcp dpt:30451
KUBE-MARK-MASQ  tcp  --  127.0.0.0/8          0.0.0.0/0            /* gloo-system-dev/gateway-proxy:http */ tcp dpt:32594
```

Non working node contains this rule that the working node does not:

```
KUBE-MARK-DROP  all  --  0.0.0.0/0            0.0.0.0/0            /* gloo-system-dev/gateway-proxy:http has no local endpoints */
KUBE-MARK-DROP  all  --  0.0.0.0/0            0.0.0.0/0            /* gloo-system-dev/gateway-proxy:https has no local endpoints */
```

I know this seems to not be an issue with kops, however I have seen https://kops.sigs.k8s.io/releases/1.26-notes/#other-breaking-changes that the CNI config is changing and also https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ Kubernetes 1.24 deprecated the use of `network-plugin`.

So I was wondering if is something that kops missed while I performed the upgrade or it is a configuration that I need to add. It is not clear to be by looking at the docs.

I would appreciate if someone could help me with this. Thank you.
