### ISSUE TITLE
Worker nodes get created but not listed after adding Cluster Autoscaler

### ISSUE THREAD

**Issue by volade** [kubernetes/kops#15820]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.27.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.27.3
Server Version: v1.27.4
Kustomize Version: v5.0.1

**3. What cloud provider are you using?**

GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create
kops update

kubectl get nodes -owide

**5. What happened after the commands executed?**

The cluster gets created. When I run "kubectl get nodes" it lists only the control plane node but none of the workers even though I see them in the GCE Compute VMs UI.

**6. What did you expect to happen?**

I expect all the nodes to be listed and showing they are in "ready" state when I run kubectl get nodes.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: desktop.k8s.local
spec:
  networkID: desktop-vpc
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  kubernetesApiAccess:
  - 0.0.0.0/0
  sshAccess:
  - 0.0.0.0/0
  project: xxxxx-migration
  subnets:
  - cidr: 10.10.0.0/24
    name: node-subnet
    id: desktop-subnet
    type: Private
    region: us-central1
    stackType: IPV4_ONLY
  cloudProvider: gce
  etcdClusters:
  - etcdMembers:
    - instanceGroup: controller-instance
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: controller-instance
      name: a
    name: events
  networking:
    calico:
      networkCIDR: xxx.xxx.0.0/16
  metricsServer:
    enabled: true
    insecure: true
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
  clusterAutoscaler:
    enabled: true
    expander: price
    balanceSimilarNodeGroups: false
    scaleDownUtilizationThreshold: "0.5"
    skipNodesWithSystemPods: true
    skipNodesWithLocalStorage: false
    newPodScaleUpDelay: 0s
    scaleDownDelayAfterAdd: 10m0s
    scaleDownUnneededTime: 10m0s
    scaleDownUnreadyTime: 20m0s
    image: ubuntu-os-cloud/ubuntu-2204-jammy-v20230616
    cpuRequest: "100m"
    memoryRequest: "300Mi"
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I have 2 instance groups; one for the control plane and the other for the workers. 

Control Plane 

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: desktop.k8s.local
  name: controller-instance
spec:
  role: ControlPlane
  image: ubuntu-os-cloud/ubuntu-2204-jammy-v20230616
  rootVolume: 20
  associatePublicIp: true
  machineType: n1-standard-1
  minSize: 1
  maxSize: 1
  gcpProvisioningModel: STANDARD
  zones: 
  - us-central1-a
  subnets:
  - node-subnet
  autoscale: false
  hooks:
  - name: startup-ctrl.service
    manifest: |
      ExecStart=/bin/bash -c 'usr/bin/curl -H'

```

Worker Instance

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: desktop.k8s.local
  name: node-instance
spec:
  role: Node
  image: ubuntu-os-cloud/ubuntu-2204-jammy-v20230616
  rootVolume: 30
  associatePublicIp: false
  machineType: e2-standard-4
  minSize: 2
  maxSize: 10
  gcpProvisioningModel: 'SPOT'
  zones:
  - us-central1-a
  subnets:
  - node-subnet
  autoscale: true
  hooks:
  - name: startup-node.service
    manifest: |
      ExecStart=/bin/bash -c 'usr/bin/curl -H 

```
