### ISSUE TITLE
GPU Support  1.27.1 not working

### ISSUE THREAD

**Issue by danLee3** [kubernetes/kops#15898]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Client version: 1.27.1 (git-v1.27.1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27.1

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster \
  --name=$KOPS_CLUSTER_NAME \
  --state=$KOPS_STATE_STORE \
  --zones=$ZONES \
  --node-size=$NODE_SIZE \
  --node-count=2 \
  --master-size=$MASTER_SIZE \
  --master-count=1 \
  --kubernetes-version=1.27.1 \
  --discovery-store=$KOPS_OIDC_STORE
```

[ cluster.yaml ]
```
  containerd:
    nvidiaGPU:
      enabled: true
```

[ ig.yaml ]
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-09-11T07:21:24Z"
  labels:
    kops.k8s.io/cluster: *
  name: gpu1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230728
  kubelet:
    anonymousAuth: false
    nodeLabels:
      node-role.kubernetes.io/node: ""
  machineType: p2.xlarge
  manager: CloudGroup
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: gpu1
  role: Node
  subnets:
  - ap-northeast-2a
  - ap-northeast-2b
  - ap-northeast-2c
```

**5. What happened after the commands executed?**

nvidia-device-plugin-daemonset error

```
  │ Events:                                                                                                                                                                 
│   Type     Reason     Age                From               Message                                                                                                     
│   ----     ------     ----               ----               -------                                                                                                     
│   Normal   Scheduled  77s                default-scheduler  Successfully assigned kube-system/nvidia-device-plugin-daemonset-fg9zz to i-0e3e38ee421460906               
│   Normal   Pulling    57s                kubelet            Pulling image "nvcr.io/nvidia/k8s-device-plugin:v0.12.2@sha256:4918fdb36600589793b6a4b96be874a673c407e85c2  
│ cf707277e532e2d8a2231"                                                                                                                                                  
│   Normal   Pulled     46s                kubelet            Successfully pulled image "nvcr.io/nvidia/k8s-device-plugin:v0.12.2@sha256:4918fdb36600589793b6a4b96be874a  
│ 673c407e85c2cf707277e532e2d8a2231" in 7.240642596s (10.482603363s including waiting)                                                                                    
│   Normal   Created    23s (x3 over 46s)  kubelet            Created container nvidia-device-plugin-ctr                                                                  
│   Normal   Pulled     23s (x2 over 39s)  kubelet            Container image "nvcr.io/nvidia/k8s-device-plugin:v0.12.2@sha256:4918fdb36600589793b6a4b96be874a673c407e85  
│ c2cf707277e532e2d8a2231" already present on machine                                                                                                                     
│   Warning  Failed     20s (x3 over 40s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc creat  
│ e failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mo  
│ de as 'legacy'                                                                                                                                                          
│ nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown                                                                                      
│   Warning  BackOff  9s (x4 over 36s)  kubelet  Back-off restarting failed container nvidia-device-plugin-ctr in pod nvidia-device-plugin-daemonset-fg9zz_kube-system(e  
│ 60895d5-35d4-4764-8e9f-c37fd68931ca)                                                                                                                                    
│                                                 
```

**6. What did you expect to happen?**

Capacity:
  cpu:                4
  ephemeral-storage:  9983232Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32796292Ki
  nvidia.com/gpu:     1 <- this one
  pods:               110

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-09-11T04:41:15Z"
  generation: 3
  name: ***
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: ***
  containerd:
    nvidiaGPU:
      enabled: true
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-2b
      name: b
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-2b
      name: b
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.27.1
  masterPublicName: api.k8s.harryham.com
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://oidc-bucket-dan/k8s.harryham.com
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20
    name: ap-northeast-2a
    type: Public
    zone: ap-northeast-2a
  - cidr: 172.20
    name: ap-northeast-2b
    type: Public
    zone: ap-northeast-2b
  - cidr: 172.20
    name: ap-northeast-2c
    type: Public
    zone: ap-northeast-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

[ gpu node ssh ]

```
cat config.toml 
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.9@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v1"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
            SystemdCgroup = true

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
ubuntu@i-0af87fe076a1bec:/etc/containerd$ pwd
/etc/containerd
```
