### ISSUE TITLE
zone filed should be changed to subnetName inside Instance group YAML

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kops#1593]
Use case:
I have 2 subnets in the same zone. When I edit the cluster YAML I specified that it linked to 2 subnets with different CIDR in the same zone but with different names.

In order to setup a single instance group to work concurrent on these 2 subnet I had to specified in the instance-group YAML the subnets name instead of the zone (as the field called).

**Comment by justinsb** [comment]
Is this with recent code?  The field name in the instance group is now subnets:

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/instancegroup.go#L71

e.g.
```
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
  machineType: m3.medium
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-east-1c
```
