### ISSUE TITLE
delete instancegroup removes the instancegroup instantly, even when --yes is not passed

### ISSUE THREAD

**Issue by CalebEubanksBL** [kubernetes/kops#15936]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Client version: 1.26.2 (git-1d81f3a)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops delete instancegroup <ig name> --name <cluster name> --state <state store>
```

**5. What happened after the commands executed?**

The AutoScalingGroup in AWS began being deleted instantly, rather than allowing me to export to terraform via `kops export`

**6. What did you expect to happen?**

I expected the change to be staged, so I could introduce infrastructure changes via exporting to terraform, then applying the changes.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-02-18T11:20:16Z"
  generation: 5
  name: cluster.company.io
spec:
  api:
    loadBalancer:
      class: Network
      sslCertificate: arn:aws:acm:us-east-1:663151050986:certificate/15795767-40ae-420a-a2cf-876532d9ab09
      type: Public
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://company-k8-kops-store/cluster.company.io
  dnsZone: cluster.company.io
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1d
      name: d
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1d
      name: d
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    serviceAccountExternalPermissions:
    - aws:
        policyARNs:
        - arn:aws:iam::663151050986:policy/company_project_policy
      name: company-project-sa
      namespace: dev
    - aws:
        policyARNs:
        - arn:aws:iam::663151050986:policy/company_project_policy
      name: company-project-sa
      namespace: staging
    - aws:
        policyARNs:
        - arn:aws:iam::663151050986:policy/company_project_policy
      name: company-project-sa
      namespace: live
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.22.6
  masterPublicName: api.cluster.company.io
  networkCIDR: 172.21.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://company-k8-kops-irsa-store
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.21.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.21.64.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.21.96.0/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 172.21.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.21.4.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 172.21.8.0/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  topology:
    bastion:
      bastionPublicName: bastion.cluster.company.io
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:20:17Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: bastions
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - us-east-1a
  - us-east-1c
  - us-east-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:25:47Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: infra-nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    company/nodetype: infrastructure
    kops.k8s.io/instancegroup: infra-nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:25:10Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: infra-nodes-us-east-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    company/nodetype: infrastructure
    kops.k8s.io/instancegroup: infra-nodes-us-east-1d
  role: Node
  subnets:
  - us-east-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:20:16Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:20:16Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: master-us-east-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:20:16Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: master-us-east-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1d
  role: Master
  subnets:
  - us-east-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-02-18T11:20:17Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220131
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t2.large
  maxSize: 4
  minSize: 4
  nodeLabels:
    company/nodetype: application
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-24T17:53:48Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: nodes-us-east-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230502
  machineType: t2.large
  manager: CloudGroup
  maxSize: 2
  minSize: 2
  nodeLabels:
    company/nodetype: application
    kops.k8s.io/instancegroup: nodes-us-east-1c
  role: Node
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-25T01:00:30Z"
  labels:
    kops.k8s.io/cluster: cluster.company.io
  name: nodes-us-east-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230502
  kubelet:
    anonymousAuth: false
    nodeLabels:
      kubernetes.io/role: node
      node-role.kubernetes.io/node: ""
  machineType: t2.large
  manager: CloudGroup
  maxSize: 3
  minSize: 3
  nodeLabels:
    company/nodetype: application
    kops.k8s.io/instancegroup: nodes-us-east-1d
  role: Node
  subnets:
  - us-east-1d
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
kops delete instancegroup project-nodes-us-east-1d --name cluster.company.io --state s3://company-k8-kops-store
Do you really want to delete instance group "project-nodes-us-east-1d"? This action cannot be undone. (y/N)
y
InstanceGroup "project-nodes-us-east-1d" found for deletion
W0919 14:58:07.424431   29224 aws_cloud.go:1004] Skipping ASG arn:aws:autoscaling:us-east-1:123123123123:autoScalingGroup:dfaces19a-cdc1-4da3-12323123dsf:autoScalingGroupName/project-nodes-us-east-1a.cluster.company.io (which matches tags): Delete in progress
I0919 14:58:07.787296   29224 delete.go:54] Deleting "project-nodes-us-east-1d"

Deleted InstanceGroup: "project-nodes-us-east-1d"
```

**9. Anything else do we need to know?**

The [docs](https://kops.sigs.k8s.io/cli/kops_delete_instancegroup/) indicate the `--yes` flag is what dictates if this action should be taken immediately, yet the instancegroup was removed immediately despite its absence.

Even if this is the intended behavior, the docs should be updated to very clearly spell out that this WILL take actions immediately.
