### ISSUE TITLE
pod-identity-webhook Prometheus port missing on service?

### ISSUE THREAD

**Issue by hoepfnerj** [kubernetes/kops#15946]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.26.5

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.26.8

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`spec.podIdentityWebhook.enabled = true`

**5. What happened after the commands executed?**

The deployment `pod-identity-webhook` was installed. The service `pod-identity-webhook` is created with Prometheus annotations, but it seems that the port 9999 for Prometheus is missing from the `spec.ports` section:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9999"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    addon.kops.k8s.io/name: eks-pod-identity-webhook.addons.k8s.io
    app.kubernetes.io/managed-by: kops
    k8s-addon: eks-pod-identity-webhook.addons.k8s.io
  name: pod-identity-webhook
  namespace: kube-system
spec:
  clusterIP: x.x.x.x
  clusterIPs:
  - x.x.x.x
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: pod-identity-webhook
  sessionAffinity: None
  type: ClusterIP
```

**6. What did you expect to happen?**

The port 9999 ist defined in the service.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

see above

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

-

**9. Anything else do we need to know?**

The ConfigMap `pod-identity-webhook` has these Prometheus annotations as well. Is this on purpose?
