### ISSUE TITLE
Controller reconciler error due Missing Karpenter permission 

### ISSUE THREAD

**Issue by ndallavalentina** [kubernetes/kops#15978]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.26.5
k8s 1.26.7

Tested and there is the same issue on 1.28

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Install karpenter via kops's addons then use this example 

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: nodes-eu-west-2a
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 64Gi
        volumeType: gp3
        deleteOnTermination: true
        kmsKeyID: ""
        iops: 10000
        encrypted: true
        throughput: 125
  subnetSelector:
    KubernetesCluster: 'test-cluster-test.dev.test.io'
    kubernetes.io/cluster/test-cluster-test.dev.test.io: '*'
  securityGroupSelector:
    Name: 'nodes.test-cluster-test.dev.test.io'
  instanceProfile: "nodes.test-cluster-test.dev.test.io"
```
without use `launchTemplate` created by kops initially 

**5. What happened after the commands executed?**

Error in the Karpenter's logs

```
ERROR	controller	Reconciler error	{"commit": "30fa8f3-dirty", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "Machine": {"name":"nodes-eu-west-2a-8c6nr"}, "namespace": "", "name": "nodes-eu-west-2a-8c6nr", "reconcileID": "xxxx-xxx-xxxx-xxxxx-xxxxxxx", "error": "creating machine, creating instance, getting launch template configs, getting launch templates, creating launch template, UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 
xxxxxx
status code: 403, request id: xxxxx
````

**6. What did you expect to happen?**
create a new template on Aws Ec2 - Launch template section

**9. Anything else do we need to know?**
I can see this change https://github.com/kubernetes/kops/blob/e12f3dc07b66737c3b853920950d8621f62967f0/pkg/model/components/addonmanifests/karpenter/iam.go#L51 not sure why are comment out these permissions? Probably as it is not supported or is there any templating creation issue with kops/karpenters via `instanceProfile`?

I don't want to use a default launch template as it is not configurable like the AIM, EBS etc..
