### ISSUE TITLE
ebs-csi-controller update strategy conflicts with logging

### ISSUE THREAD

**Issue by andsens** [kubernetes/kops#15998]
/kind bug

kops: `Client version: 1.28.0 (git-v1.28.0)`
kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:09Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

on AWS.

---

I am 100% certain that I didn't add these parameters, but I can also not find them anywhere in the kops repo, so take this with a grain of salt:

It seems the ebs-csi-controller deployment is set up with 2 replicas and a rolling update with a `maxSurge` and `maxUnavailable` of 25%:

```
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ebs-csi-controller
      app.kubernetes.io/instance: aws-ebs-csi-driver
      app.kubernetes.io/name: aws-ebs-csi-driver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

On my cluster this resulted in the controller not being able to roll over to a new deployment (not sure why it did that to begin with though), because the controller itself seems to wait to signal readiness until it has acquired a controller-lock. With the above parameters this can never happen, because k8s does not terminate the previous controller until the new one has started up.

Changing the parameters to 50% fixes this issue.

Again, all of this happened in a rather hectic attempt to get this working again, and I don't have enough insight into the entire setup to be certain that my fix works the way I think it does. It could also be that changing a deployment parameter caused a new rollover, which fixed things. On the surface though I believe this makes sense, hopefully someone with better insight can confirm or refute.
