### ISSUE TITLE
Kops addons karpenter cannot overwrite provisioner's configuration

### ISSUE THREAD

**Issue by ndallavalentina** [kubernetes/kops#16017]
/kind feature

On the Karpenter Kops's addons, it is not possible to overwrite the provisioner's configurations listed here: 

https://karpenter.sh/docs/concepts/provisioners/

This is the affected template, It would be great that this template contain the parameter configuration that we want to overwrite/configure:
https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template#L1811

example:

```
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
or 
# If omitted, the feature is disabled and nodes will never expire.  If set to less time than it requires for a node
# to become ready, the node may expire before any pods successfully start.
ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;

# If omitted, the feature is disabled, nodes will never scale down due to low utilization
ttlSecondsAfterEmpty: 30
```
