### ISSUE TITLE
Enabling hubble-metrics should create a headless service with annotations for prometheus

### ISSUE THREAD

**Issue by krillerdk** [kubernetes/kops#16032]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.27.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27.4

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create a cluster with cilium and hubble metrics enabled:

```yaml
  networking:
    cilium:
      enablePrometheusMetrics: true
      hubble:
        enabled: true
        metrics:
        - dns
        - drop
        - tcp
        - flow
        - icmp
        - http
```

**5. What happened after the commands executed?**

cilium agents serves cilium agent metrics on port 9090  and hubble metrics on port 9091. Prometheus only scrapes port 9090 since the pods have these annotations:

```yaml
metadata:
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
```
As there is no official way to add extra ports using extra annotations on the pods, the cilium helm chart will create a headless service named "hubble-metrics" that includes the annotations to allow prometheus to discover the endpoint correctly

**6. What did you expect to happen?**
I expected kops to also create the same headless service as the cilium helm chart. Adding the following service by hand caused the metrics to be correctly scraped by prometheus:

```yaml
kind: Service
apiVersion: v1
metadata:
  namespace: kube-system
  name: hubble-metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9091'
spec:
  clusterIP: "None"
  selector:
    k8s-app: cilium
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      name: hubble-metrics
```
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2023-05-30T13:43:11Z"
  generation: 21
  name: XXXXXXXX
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  configBase: s3:/XXXXXXXX/XXXXXXXX
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: XXXXXXXX
      name: b
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: XXXXXXXX
      name: b
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    - arn:aws:iam::XXXXXXXX:policy/ThanosS3Access
    node:
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    - arn:aws:iam::XXXXXXXX:policy/ThanosS3Access
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.27.4
  masterPublicName: XXXXXXXX
  metricsServer:
    enabled: true
    insecure: false
  networkCIDR: XXXXXXXX
  networkID: XXXXXXXX
  networking:
    cilium:
      enableNodePort: true
      enablePrometheusMetrics: true
      hubble:
        enabled: true
        metrics:
        - dns
        - drop
        - tcp
        - flow
        - icmp
        - http
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: XXXXXXXX
    egress: nat-XXXXXXXX
    id: XXXXXXXX
    name: XXXXXXXX
    type: Private
    zone: eu-central-1b
  - cidr: XXXXXXXX
    id: XXXXXXXX
    name: XXXXXXXX
    type: Utility
    zone: eu-central-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-30T13:43:11Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: XXXXXXXX
  name: XXXXXXXX
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230711
  instanceMetadata:
    httpPutResponseHopLimit: 2
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - XXXXXXXX

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-30T13:43:11Z"
  generation: 13
  labels:
    kops.k8s.io/cluster: XXXXXXXX
  name: XXXXXXXX
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230711
  instanceMetadata:
    httpPutResponseHopLimit: 2
  machineType: t3a.large
  maxSize: 9
  minSize: 3
  role: Node
  subnets:
  - XXXXXXXX
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
