### ISSUE TITLE
Protokube - error applying channel

### ISSUE THREAD

**Issue by ScOut3R** [kubernetes/kops#16046]
/kind bug

I am not sure if this is a bug or just an issue with my system. Any help or suggestion would be greatly appreciated.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.27.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

The issue might have started earlier, but I noticed it while upgrading the cluster to 1.27.7 from 1.26.9 and kops from 1.26.6 to 1.27.1.

**5. What happened after the commands executed?**

Protokube tries to load the `bootstrap-channel.yaml` from S3, but logs `kube_boot.go:89] error applying channel "s3://k8skopsstatestoreb8ef09a2-bucket83908e77-mmtvj3p0tin3/dev.kops.playhq.cloud/addons/bootstrap-channel.yaml": error running channels: exit status 1`

**6. What did you expect to happen?**

I expected no error.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
spec:
  api:
    loadBalancer:
      type: Internal
      class: Network
      idleTimeoutSeconds: 60
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
    managed: false
  channel: stable
  cloudConfig:
    manageStorageClasses: false
    awsEBSCSIDriver:
      enabled: true
      managed: false
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    expander: least-waste
    balanceSimilarNodeGroups: true
    awsUseStaticInstanceList: false
    scaleDownUtilizationThreshold: "0.7"
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: false
    newPodScaleUpDelay: 10s
    scaleDownDelayAfterAdd: 10m0s
    cpuRequest: "100m"
    memoryRequest: "300Mi"
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
      encryptedVolume: true
      volumeType: gp3
    - instanceGroup: master-ap-southeast-2b
      name: b
      encryptedVolume: true
      volumeType: gp3
    - instanceGroup: master-ap-southeast-2c
      name: c
      encryptedVolume: true
      volumeType: gp3
    memoryRequest: 2Gi
    name: main
    manager:
      env:
        - name: ETCD_LISTEN_METRICS_URLS
          value: http://0.0.0.0:8081
        - name: ETCD_METRICS
          value: basic
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-southeast-2a
      name: a
      encryptedVolume: true
      volumeType: gp3
    - instanceGroup: master-ap-southeast-2b
      name: b
      encryptedVolume: true
      volumeType: gp3
    - instanceGroup: master-ap-southeast-2c
      name: c
      encryptedVolume: true
      volumeType: gp3
    memoryRequest: 1Gi
    name: events
    manager:
      env:
        - name: ETCD_LISTEN_METRICS_URLS
          value: http://0.0.0.0:8082
        - name: ETCD_METRICS
          value: basic
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    enforceNodeAllocatable: "pods"
    featureGates:
      InTreePluginAWSUnregister: "true"
    imageGCHighThresholdPercent: 75
    imageGCLowThresholdPercent: 70
    kubeReserved:
        cpu: "200m"
        memory: "1Gi"
        ephemeral-storage: "1Gi"
    kubeReservedCgroup: "/kube-reserved"
    kubeletCgroups: "/kube-reserved"
    podPidsLimit: 1024
    runtimeCgroups: "/kube-reserved"
    systemReserved:
        cpu: "200m"
        memory: "1Gi"
        ephemeral-storage: "1Gi"
    systemReservedCgroup: "/system-reserved"
  kubeAPIServer:
    memoryRequest: 8Gi
    memoryLimit: 8Gi
    eventTTL: 6h0m0s
    featureGates:
      InTreePluginAWSUnregister: "true"
  kubeControllerManager:
    featureGates:
      InTreePluginAWSUnregister: "true"
  kubernetesVersion: 1.27.7
  kubeDNS:
    provider: CoreDNS
    nodeLocalDNS:
      enabled: true
      memoryRequest: 30Mi
      cpuRequest: 25m
  kubeProxy:
    proxyMode: ipvs
  kubeScheduler:
    featureGates:
      InTreePluginAWSUnregister: "true"
  metricsServer:
    enabled: true
    insecure: false
  networking:
    calico:
      encapsulationMode: vxlan
      mtu: 8951
      typhaReplicas: 3
  nodeProblemDetector:
    enabled: true
    memoryRequest: 32Mi
    cpuRequest: 10m
  nodeTerminationHandler:
    enabled: true
    enableSQSTerminationDraining: true
    managedASGTag: "aws-node-termination-handler/managed"
  # https://tools.ietf.org/html/rfc6598#section-7
  nonMasqueradeCIDR: 100.64.0.0/10
  podIdentityWebhook:
    enabled: true
  serviceAccountIssuerDiscovery:
    enableAWSOIDCProvider: true
  snapshotController:
    enabled: true
```

And the `bootstrap-channel.yaml` file:
```yaml
kind: Addons
metadata:
  creationTimestamp: null
  name: bootstrap
spec:
  addons:
  - id: k8s-1.16
    manifest: kops-controller.addons.k8s.io/k8s-1.16.yaml
    manifestHash: ff67e831a385c35e288a7794a3a370264742d9f7c32a16c139acb6db52db1997
    name: kops-controller.addons.k8s.io
    needsRollingUpdate: control-plane
    selector:
      k8s-addon: kops-controller.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.12
    manifest: coredns.addons.k8s.io/k8s-1.12.yaml
    manifestHash: 9e04bbb03f9e5e62e8a246a96f73e8aaa31bf1d3284346c335774df5f7c3495d
    name: coredns.addons.k8s.io
    selector:
      k8s-addon: coredns.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.9
    manifest: kubelet-api.rbac.addons.k8s.io/k8s-1.9.yaml
    manifestHash: 01c120e887bd98d82ef57983ad58a0b22bc85efb48108092a24c4b82e4c9ea81
    name: kubelet-api.rbac.addons.k8s.io
    selector:
      k8s-addon: kubelet-api.rbac.addons.k8s.io
    version: 9.99.0
  - manifest: limit-range.addons.k8s.io/v1.5.0.yaml
    manifestHash: 2d55c3bc5e354e84a3730a65b42f39aba630a59dc8d32b30859fcce3d3178bc2
    name: limit-range.addons.k8s.io
    selector:
      k8s-addon: limit-range.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.12
    manifest: dns-controller.addons.k8s.io/k8s-1.12.yaml
    manifestHash: c2abd7a216533f237e4c425a8890abc6822fa773ec7c52b3fc434b3e394619c6
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.12
    manifest: nodelocaldns.addons.k8s.io/k8s-1.12.yaml
    manifestHash: 7af8058a8032e1f46dffeecd0f1539d628bf525cadb17a9e375c0c27176c441c
    name: nodelocaldns.addons.k8s.io
    needsRollingUpdate: all
    selector:
      k8s-addon: nodelocaldns.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.15
    manifest: cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml
    manifestHash: a447e25a6a3793b7d0205abcbe55a5410949f8152de7f2656376b0decc04998f
    name: cluster-autoscaler.addons.k8s.io
    selector:
      k8s-addon: cluster-autoscaler.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.11
    manifest: metrics-server.addons.k8s.io/k8s-1.11.yaml
    manifestHash: ad25beb6dd7f245793d022efb0d142ff72744cd28c1ff0c17e064db4379c9382
    name: metrics-server.addons.k8s.io
    needsPKI: true
    selector:
      k8s-app: metrics-server
    version: 9.99.0
  - id: k8s-1.11
    manifest: node-termination-handler.aws/k8s-1.11.yaml
    manifestHash: 463f0bd528db7ddccd0b2c13ac4ae054af0017abb80728f77e2b50a47253c743
    name: node-termination-handler.aws
    prune:
      kinds:
      - kind: ConfigMap
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - kind: Service
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - kind: ServiceAccount
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: apps
        kind: DaemonSet
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: apps
        kind: Deployment
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: apps
        kind: StatefulSet
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: policy
        kind: PodDisruptionBudget
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: rbac.authorization.k8s.io
        kind: Role
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
      - group: rbac.authorization.k8s.io
        kind: RoleBinding
        labelSelector: addon.kops.k8s.io/name=node-termination-handler.aws,app.kubernetes.io/managed-by=kops
    selector:
      k8s-addon: node-termination-handler.aws
    version: 9.99.0
  - id: k8s-1.17
    manifest: node-problem-detector.addons.k8s.io/k8s-1.17.yaml
    manifestHash: baae1afe4f61e36b96e7d77bd76c9c33c7c0de281c21fea1d36949ca731dd533
    name: node-problem-detector.addons.k8s.io
    selector:
      k8s-addon: node-problem-detector.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.19
    manifest: aws-load-balancer-controller.addons.k8s.io/k8s-1.19.yaml
    manifestHash: d81c123c3052593cf7e408b201be502f880eef6239bebf2fe5b99020e2d40a30
    name: aws-load-balancer-controller.addons.k8s.io
    needsPKI: true
    selector:
      k8s-addon: aws-load-balancer-controller.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.16
    manifest: eks-pod-identity-webhook.addons.k8s.io/k8s-1.16.yaml
    manifestHash: fa5d3a18e82ae6b2c9adc33ca25bcd03525e14605643524ca20ffdb40c979e12
    name: eks-pod-identity-webhook.addons.k8s.io
    needsPKI: true
    selector:
      k8s-addon: eks-pod-identity-webhook.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.25
    manifest: networking.projectcalico.org/k8s-1.25.yaml
    manifestHash: 1dc0924e64fe48eb95e584ab789f797e8a004fc87ccdd2aed5a2cdb64e72cde4
    name: networking.projectcalico.org
    prune:
      kinds:
      - kind: ConfigMap
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - kind: Service
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - kind: ServiceAccount
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
      - group: apps
        kind: DaemonSet
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: apps
        kind: Deployment
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: apps
        kind: StatefulSet
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
      - group: policy
        kind: PodDisruptionBudget
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
        namespaces:
        - kube-system
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
      - group: rbac.authorization.k8s.io
        kind: Role
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
      - group: rbac.authorization.k8s.io
        kind: RoleBinding
        labelSelector: addon.kops.k8s.io/name=networking.projectcalico.org,app.kubernetes.io/managed-by=kops
    selector:
      role.kubernetes.io/networking: "1"
    version: 9.99.0
  - id: k8s-1.18
    manifest: aws-cloud-controller.addons.k8s.io/k8s-1.18.yaml
    manifestHash: c2110c35e17e34803a65b5a86fcc766f3a1cb0e648e098a6e6fc98e56c5c7829
    name: aws-cloud-controller.addons.k8s.io
    selector:
      k8s-addon: aws-cloud-controller.addons.k8s.io
    version: 9.99.0
  - id: k8s-1.20
    manifest: snapshot-controller.addons.k8s.io/k8s-1.20.yaml
    manifestHash: ffd0583173236566c0315a3dcad5bb5ee23f43a0eedd83b7049be7dea4099110
    name: snapshot-controller.addons.k8s.io
    needsPKI: true
    selector:
      k8s-addon: snapshot-controller.addons.k8s.io
    version: 9.99.0
```
