### ISSUE TITLE
Cilium , No IP's left to assign on aws instances

### ISSUE THREAD

**Issue by victorgitmain** [kubernetes/kops#16064]
/kind bug
Running on AWS ec2 instances with cilium for network.
Sometimes newly created pods will get stuck indefinitely in "ContainerCreating" state.
When using: 
```
kubectl describe pod $POD_NAME
```
We get: 
```
  Warning  FailedCreatePodSandBox  2s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0f06846efa22ac25671ad6657f3540a4f4f9879c345b4ebeb7331769fffdd24f": plugin type="cilium-cni" name="cilium" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure 
```
after check we indeed see that the maximum number of pods has been scheduled
but because the instance still has resources left, pods still get scheduled on those instances 
and get stuck in "ContainerCreating"

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.
```
Client version: 1.28.0 (git-v1.28.0)
Last applied server version: 1.28.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
2.
```
1.27.6
```

**3. What cloud provider are you using?**
3.
```
AWS
```
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
   Use AWS for cloud provider with networking set to Cilium 
   Use small instance type with low amount of "Maximum network interfaces"
   happened on "r5.large,m5.large" can happen on any node as long there is enough space to 
   schedule the pods.
   Create large amount of small pods and see that they get scheduled to Instances with no IPs 
   left.
   Can use following Yaml:
```
kubectl apply -f nginx.yaml
```
   ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 200
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - containerPort: 80
   ```
**5. What happened after the commands executed?**
Pods got stuck in "ContainerCreating" state with
```
  Warning  FailedCreatePodSandBox  2s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0f06846efa22ac25671ad6657f3540a4f4f9879c345b4ebeb7331769fffdd24f": plugin type="cilium-cni" name="cilium" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure 
```

**6. What did you expect to happen?**
Pods to get scheduled on Instances with sufficient amount of IP's or for new nodes to be provisioned and get scheduled on those nodes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: "***"
spec:
  DisableSubnetTags: true
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      class: Network
      type: Internal
  authentication:
    aws:
      backendMode: CRD,MountedFile
      clusterID: "***"
      identityMappings:
      - arn: "***"
        groups:
        - system:masters
        username: admin
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enableWAFv2: true
    enabled: true
  certManager:
    enabled: true
    managed: false
  channel: stable
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
    manageStorageClasses: false
  cloudControllerManager:
    cloudProvider: aws
  cloudLabels:
    env: "***"
  cloudProvider: aws
  clusterAutoscaler:
    awsUseStaticInstanceList: false
    balanceSimilarNodeGroups: true
    enabled: true
    scaleDownDelayAfterAdd: 30s
    scaleDownUtilizationThreshold: "1"
    skipNodesWithLocalStorage: false
  configBase: s3://"***"
  dnsZone: "***"
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1f
      name: c
    manager:
      backupRetentionDays: 90
      logLevel: 1
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1f
      name: c
    manager:
      backupRetentionDays: 90
      logLevel: 1
    name: events
  externalDns:
    provider: dns-controller
    watchIngress: true
  fileAssets:
  - content: |
      # This policy is loaded into the master-ig templates
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        # The following requests were manually identified as high-volume and low-risk,
        # so drop them.
        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
            - group: "" # core
              resources: ["endpoints", "services", "services/status"]
        - level: None
          # Ingress controller reads 'configmaps/ingress-uid' through the unsecured port.
          # TODO(#46983): Change this to the ingress controller service account.
          users: ["system:unsecured"]
          namespaces: ["kube-system"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["configmaps"]
        - level: None
          users: ["kubelet"] # legacy kubelet identity
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["nodes", "nodes/status"]
        - level: None
          userGroups: ["system:nodes"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["nodes", "nodes/status"]
        - level: None
          users:
            - system:kube-controller-manager
            - system:kube-scheduler
            - system:serviceaccount:kube-system:endpoint-controller
          verbs: ["get", "update"]
          namespaces: ["kube-system"]
          resources:
            - group: "" # core
              resources: ["endpoints"]
        - level: None
          users: ["system:apiserver"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
        - level: None
          users: ["cluster-autoscaler"]
          verbs: ["get", "update"]
          namespaces: ["kube-system"]
          resources:
            - group: "" # core
              resources: ["configmaps", "endpoints"]
        # Don't log HPA fetching metrics.
        - level: None
          users:
            - system:kube-controller-manager
          verbs: ["get", "list"]
          resources:
            - group: "metrics.k8s.io"
        # Don't log these read-only URLs.
        - level: None
          nonResourceURLs:
            - /healthz*
            - /version
            - /swagger*
        # Don't log events requests.
        - level: None
          resources:
            - group: "" # core
              resources: ["events"]
        # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
        - level: Request
          users:
            [
              "kubelet",
              "system:node-problem-detector",
              "system:serviceaccount:kube-system:node-problem-detector",
            ]
          verbs: ["update", "patch"]
          resources:
            - group: "" # core
              resources: ["nodes/status", "pods/status"]
          omitStages:
            - "RequestReceived"
        - level: Request
          userGroups: ["system:nodes"]
          verbs: ["update", "patch"]
          resources:
            - group: "" # core
              resources: ["nodes/status", "pods/status"]
          omitStages:
            - "RequestReceived"
        # deletecollection calls can be large, don't log responses for expected namespace deletions
        - level: Request
          users: ["system:serviceaccount:kube-system:namespace-controller"]
          verbs: ["deletecollection"]
          omitStages:
            - "RequestReceived"
        # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
        # so only log at the Metadata level.
        - level: Metadata
          resources:
            - group: "" # core
              resources: ["secrets", "configmaps"]
            - group: authentication.k8s.io
              resources: ["tokenreviews"]
          omitStages:
            - "RequestReceived"
        # Get repsonses can be large; skip them.
        - level: Request
          verbs: ["get", "list", "watch"]
          resources:
            - group: "" # core
            - group: "admissionregistration.k8s.io"
            - group: "apiextensions.k8s.io"
            - group: "apiregistration.k8s.io"
            - group: "apps"
            - group: "authentication.k8s.io"
            - group: "authorization.k8s.io"
            - group: "autoscaling"
            - group: "batch"
            - group: "certificates.k8s.io"
            - group: "extensions"
            - group: "metrics.k8s.io"
            - group: "networking.k8s.io"
            - group: "node.k8s.io"
            - group: "policy"
            - group: "rbac.authorization.k8s.io"
            - group: "scheduling.k8s.io"
            - group: "settings.k8s.io"
            - group: "storage.k8s.io"
          omitStages:
            - "RequestReceived"
        # Default level for known APIs
        - level: RequestResponse
          resources:
            - group: "" # core
            - group: "admissionregistration.k8s.io"
            - group: "apiextensions.k8s.io"
            - group: "apiregistration.k8s.io"
            - group: "apps"
            - group: "authentication.k8s.io"
            - group: "authorization.k8s.io"
            - group: "autoscaling"
            - group: "batch"
            - group: "certificates.k8s.io"
            - group: "extensions"
            - group: "metrics.k8s.io"
            - group: "networking.k8s.io"
            - group: "node.k8s.io"
            - group: "policy"
            - group: "rbac.authorization.k8s.io"
            - group: "scheduling.k8s.io"
            - group: "settings.k8s.io"
            - group: "storage.k8s.io"
          omitStages:
            - "RequestReceived"
        # Default level for all other requests.
        - level: Metadata
          omitStages:
            - "RequestReceived"
    name: audit-policy
    path: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    roles:
    - ControlPlane
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
  kubeControllerManager:
    horizontalPodAutoscalerTolerance: 1m
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    resolvConf: /run/systemd/resolve/resolv.conf
    runtimeRequestTimeout: 10m0s
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.27.6
  masterPublicName: "***"
  metricsServer:
    enabled: true
    insecure: false
  networkCIDR: 10.40.0.0/16
  networkID: "***"
  networking:
    cilium:
      clusterName: "***"
      enableEncryption: true
      enableL7Proxy: false
      enableNodePort: true
      encryptionType: wireguard
      hubble:
        enabled: true
      ipam: eni
  nodeProblemDetector:
    cpuRequest: 10m
    enabled: true
    memoryRequest: 32Mi
  nodeTerminationHandler:
    cpuRequest: 50m
    enableRebalanceDraining: true
    enableRebalanceMonitoring: true
    enableSQSTerminationDraining: false
    enableScheduledEventDraining: true
    enableSpotInterruptionDraining: true
    enabled: true
    managedASGTag: aws-node-termination-hanlder-managed
    memoryRequest: 64Mi
    prometheusEnable: true
  nonMasqueradeCIDR: 100.64.0.0/10
  podIdentityWebhook:
    enabled: true
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://"***"
    enableAWSOIDCProvider: true
  snapshotController:
    enabled: true
  subnets:
  - cidr: 10.40.32.0/20
    id: "***"
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.40.64.0/20
    id: "***"
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.40.160.0/20
    id: "***"
    name: us-east-1f
    type: Private
    zone: us-east-1f
  topology:
    dns:
      type: Public
  updatePolicy: external
```

machine types we use in our Instance Group:
```
m5a.large,m5a.xlarge,m5a.2xlarge,m5.large,m5.xlarge,m5.2xlarge,m4.large,m4.xlarge,m4.2xlarge,t3.medium,t3a.medium,t3.large,t3a.large,t3.xlarge,t3a.xlarge,t3.2xlarge,t3a.2xlarge,r5a.large,r5a.xlarge,r5a.2xlarge,r5.large,r5.xlarge,r5.2xlarge,c5.large,c5.xlarge,c5.2xlarge,c5a.large,c5a.xlarge,c5a.2xlarge
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
kubelet logs 
```
Oct 26 08:27:38 ip-10-40-174-79 kubelet[3661]: I1026 08:27:38.615742    3661 kubelet.go:2343] "SyncLoop ADD" source="api" pods=[kube-system/nginx-deployment-7f7c8d6f4d-pcqlw]
Oct 26 08:27:38 ip-10-40-174-79 kubelet[3661]: I1026 08:27:38.615806    3661 topology_manager.go:212] "Topology Admit Handler" podUID=0dab0a01-714b-4d0c-b8af-df22041a82da podNamespace="kube-system" podName="nginx-deployment-7f7c8d6f4d-pcqlw"
Oct 26 08:27:38 ip-10-40-174-79 kubelet[3661]: I1026 08:27:38.671426    3661 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-9pb29\" (UniqueName: \"kubernetes.io/projected/0dab0a01-714b-4d0c-b8af-df22041a82da-kube-api-access-9pb29\") pod \"nginx-deployment-7f7c8d6f4d-pcqlw\" (UID: \"0dab0a01-714b-4d0c-b8af-df22041a82da\") " pod="kube-system/nginx-deployment-7f7c8d6f4d-pcqlw"
Oct 26 08:27:38 ip-10-40-174-79 kubelet[3661]: I1026 08:27:38.771842    3661 reconciler_common.go:231] "operationExecutor.MountVolume started for volume \"kube-api-access-9pb29\" (UniqueName: \"kubernetes.io/projected/0dab0a01-714b-4d0c-b8af-df22041a82da-kube-api-access-9pb29\") pod \"nginx-deployment-7f7c8d6f4d-pcqlw\" (UID: \"0dab0a01-714b-4d0c-b8af-df22041a82da\") " pod="kube-system/nginx-deployment-7f7c8d6f4d-pcqlw"
Oct 26 08:27:38 ip-10-40-174-79 kubelet[3661]: I1026 08:27:38.781550    3661 operation_generator.go:718] "MountVolume.SetUp succeeded for volume \"kube-api-access-9pb29\" (UniqueName: \"kubernetes.io/projected/0dab0a01-714b-4d0c-b8af-df22041a82da-kube-api-access-9pb29\") pod \"nginx-deployment-7f7c8d6f4d-pcqlw\" (UID: \"0dab0a01-714b-4d0c-b8af-df22041a82da\") " pod="kube-system/nginx-deployment-7f7c8d6f4d-pcqlw"
Oct 26 08:27:38 ip-10-40-174-79 kubelet[3661]: I1026 08:27:38.941632    3661 util.go:30] "No sandbox for pod can be found. Need to start a new one" pod="kube-system/nginx-deployment-7f7c8d6f4d-pcqlw"
Oct 26 08:27:39 ip-10-40-174-79 kubelet[3661]: E1026 08:27:39.041646    3661 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"b7245c86a1c69d4aab90fde373b16fa4c75784418819e49514bfc2582aa97c90\": plugin type=\"cilium-cni\" name=\"cilium\" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  No more IPs available" pod="kube-system/nginx-deployment-7f7c8d6f4d-pcqlw"
Oct 26 08:27:39 ip-10-40-174-79 kubelet[3661]: E1026 08:27:39.041898    3661 kuberuntime_manager.go:1122] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"b7245c86a1c69d4aab90fde373b16fa4c75784418819e49514bfc2582aa97c90\": plugin type=\"cilium-cni\" name=\"cilium\" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  No more IPs available" pod="kube-system/nginx-deployment-7f7c8d6f4d-pcqlw"

```
```
nginx-deployment-7f7c8d6f4d-zb7c2                      0/1     ContainerCreating   0          4m40s
```
kube-scheduler log seems to have no issue with problematic pods
```
I1026 05:50:49.264352      11 schedule_one.go:252] "Successfully bound pod to node" pod="metrics/nginx-deployment-7f7c8d6f4d-zb7c2" node="i-0f612f5ce6a0ac1b7" evaluatedNodes=10 feasibleNodes=4
```

**9. Anything else do we need to know?**
A good fix would be for somehow not to schedule pods on instances that don't have sufficient IP's

some solutions have been discussed here:
https://github.com/cilium/cilium/issues/10426
https://github.com/cilium/cilium/issues/22054
