### ISSUE TITLE
coredns and coredns-autoscaler not default set nodeAffinity and tolerations like dns-controller

### ISSUE THREAD

**Issue by dannyeuu** [kubernetes/kops#16080]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.27.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.27.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
NDA

**5. What happened after the commands executed?**
NDA

**6. What did you expect to happen?**
NDA

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
NDA

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
NDA

**9. Anything else do we need to know?**
The problem is that on workers spot, running application like airflow, the coredns is free to join any node, sometimes coredns join a spot worker and the entire application restarts and lose connection to database.

Adding the `nodeAffinity` and `tolerations` like deployment of `dns-controller`

```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
```

```yaml
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
      - key: node.kubernetes.io/not-ready
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
```

it may be a bug cuz like the dns-controller, coredns and coredns-autoscaller must the same behavior, to keep in master nodes
