### ISSUE TITLE
KOPS worker nodes distribution with ASG's with N subnets.

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/kops#16180]
/kind feature

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Latest , as we use this for K8s Scalability Load tests on AWS for [pre-submits](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kops/build_jobs.py#L1439-L1506) and [periodics](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-ec2.yaml#L30-L131)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

I think currently it spins off `1.29` i believe

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Cluster is spun using this `run_test.sh` file using kubetes2 kops [here](https://github.com/kubernetes/kops/blob/master/tests/e2e/scenarios/scalability/run-test.sh#L170-L177)

**5. What happened after the commands executed?**

So, as I understand it, basically the way KOPS create instance groups/ASG's for worker nodes is that, it takes all the list of CIDR's  passed to KOPS and creates VPC and subnets across different AZ's more or less evenly. Also, it divides the total number of nodes by 3 and creates them across three ASG's to evenly balance the nodes across ASG's.

Even though it's trying to balance the nodes across ASG's, the problem is that at the time of creating an ASG, it creates a `Single AZ ASG`, but `not Multi-AZ ASG`, i.e; it will pass all the subnets that are part of Single AZ to each ASG, there by limiting that respective ASG to subnets from with in that AZ's no matter how many subnets KOPS had created across different AZ's.

The issue with this is that, given it's a `Single AZ ASG and not Multi AZ ASG`, ASG on server side is picking up randomly a subnet in that AZ for that ASG to launch an instance until it's run out of IP's more or less, before it moves on to another subnet for the same ASG to launch an instance and this leads to filling up of single subnet even though we have other free subnets lying around in the same AZ. If we would have created this ASG across multi AZ subnets, ASG on server side would be obligated to balance the nodes across these subnets and will help effectively use these subnets/cidr blocks we are passing [here](https://github.com/kubernetes/kops/blob/master/tests/e2e/scenarios/scalability/run-test.sh#L89) 

This issue is more prone on large scale clusters like our 5k load test we run on AWS using KOPS because, we use Prefix delegation feature, and our component will try to pick `/28 CIDR blocks` from the subnet and attach as prefixes to the instance. As more instance join the subnet and/or as pods churn, this will lead to fragmentation of subnets  and there by EC2 thinks there is no available `/28 CIDR blocks` and ends up throwing `Insufficient CIDR block errors on client side` and CNI goes into this loop of trying to attach prefixes to do it's job as instances/pods come up by making AssignIPAddress calls and ends up getting throttled and might end up affecting other components required this EC2 API.

In one of the test failure I looked at, ASG ended up creating 1183 instances out of 1666 instances in one subnet and it ran out `/28 CIDR` blocks in that particular subnet and ended up causing test failures because Nodes/pods were not joining/scheduled as EC2 is throwing `Insufficient CIDR blocks`.

See this for [example](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1733729401608081408/artifacts/instancegroups.yaml)

ASG is created with Single AZ

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-12-10T06:11:13Z"
  labels:
    kops.k8s.io/cluster: scale-1000.periodic.test-cncf-aws.k8s.io
  name: nodes-us-east-2a
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3a.medium
  maxSize: 1667
  minSize: 1667
  mixedInstancesPolicy:
    instances:
    - t3a.medium
    - t3.medium
    - t2.medium
    - t3a.large
    - c5a.large
    - t3.large
    - c5.large
    - m5a.large
    - m6a.large
    - m5.large
    - c4.large
    - c7a.large
    - r5a.large
    - r6a.large
    - m7a.large
  role: Node
  rootVolumeSize: 20
  subnets:
  - us-east-2a-1
  - us-east-2a-4
  - us-east-2a-7
  - us-east-2a-10
  ```
  
  ```
  apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-12-10T06:11:13Z"
  labels:
    kops.k8s.io/cluster: scale-1000.periodic.test-cncf-aws.k8s.io
  name: nodes-us-east-2b
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3a.medium
  maxSize: 1667
  minSize: 1667
  mixedInstancesPolicy:
    instances:
    - t3a.medium
    - t3.medium
    - t2.medium
    - t3a.large
    - c5a.large
    - t3.large
    - c5.large
    - m5a.large
    - m6a.large
    - m5.large
    - c4.large
    - c7a.large
    - r5a.large
    - r6a.large
    - m7a.large
  role: Node
  rootVolumeSize: 20
  subnets:
  - us-east-2b-2
  - us-east-2b-5
  - us-east-2b-8
  - us-east-2b-11
```
---
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-12-10T06:11:13Z"
  labels:
    kops.k8s.io/cluster: scale-1000.periodic.test-cncf-aws.k8s.io
  name: nodes-us-east-2c
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3a.medium
  maxSize: 1666
  minSize: 1666
  mixedInstancesPolicy:
    instances:
    - t3a.medium
    - t3.medium
    - t2.medium
    - t3a.large
    - c5a.large
    - t3.large
    - c5.large
    - m5a.large
    - m6a.large
    - m5.large
    - c4.large
    - c7a.large
    - r5a.large
    - r6a.large
    - m7a.large
  role: Node
  rootVolumeSize: 20
  subnets:
  - us-east-2c-3
  - us-east-2c-6
  - us-east-2c-9
  - us-east-2c-12
  ```

**6. What did you expect to happen?**

We want KOPS to support ASG's with Multi-AZ so we don't run into these issues at scale and subnets are used efficiently.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1733729401608081408/artifacts/instancegroups.yaml

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
No
