### ISSUE TITLE
Missing S3 variables on node Openstack cloud-init metadata

### ISSUE THREAD

**Issue by happycouak** [kubernetes/kops#16197]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.28.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4
**3. What cloud provider are you using?**
openstack
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
export NAME=my-cluster.k8s.local
export KOPS_STATE_STORE=xxx

export S3_REGION=xxx
export S3_ACCESS_KEY_ID=xxx
export S3_SECRET_ACCESS_KEY=xxx
export S3_ENDPOINT=xxx

export AWS_DEFAULT_REGION=xxx
export AWS_REGION=xxx
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx

kops create cluster \
  --cloud openstack \
  --name $NAME \
  --state ${KOPS_STATE_STORE} \
  --zones nova \
  --network-cidr 10.0.0.0/24 \
  --image jammy \
  --control-plane-count=3 \
  --control-plane-size nova.2xsmall \
  --node-count=1 \
  --node-size nova.tiny \
  --etcd-storage-type cinder-ssd1 \
  --topology public \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking calico \
  --os-ext-net floating-ip \
  --os-octavia=False \
  --os-kubelet-ignore-az=true \
  --api-loadbalancer-type="" \
  --os-dns-servers=8.8.8.8,8.8.4.4 \
  --dns=public

kops update cluster --name $NAME --yes --admin

kops validate cluster
```
**5. What happened after the commands executed?**
```
Using cluster from kubectl context: my-cluster.k8s.local

Validating cluster my-cluster.k8s.local

INSTANCE GROUPS
NAME                    ROLE            MACHINETYPE             MIN     MAX     SUBNETS
control-plane-nova-1    ControlPlane    nova.2xsmall      1       1       nova
control-plane-nova-2    ControlPlane    nova.2xsmall      1       1       nova
control-plane-nova-3    ControlPlane    nova.2xsmall      1       1       nova
nodes-nova              Node            nova.tiny         1       1       nova

NODE STATUS
NAME                            ROLE            READY
control-plane-nova-1-qgp9up     control-plane   True
control-plane-nova-2-pgkcpz     control-plane   True
control-plane-nova-3-xpz7rd     control-plane   True

VALIDATION ERRORS
KIND    NAME                                    MESSAGE
Machine 592a6ea9-5af5-460c-8ca2-af76cd085f6b    machine "592a6ea9-5af5-460c-8ca2-af76cd085f6b" has not yet joined cluster

Validation Failed
Error: validation failed: cluster not yet healthy
```

Logs on machine 592a6ea9-5af5-460c-8ca2-af76cd085f6b

```
Jan 01 15:30:01 nodes-nova-e9ychk nodeup[1047]: caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
```

S3* variable are missing in /etc/sysconfig/kops-configuration on the node, and also in cloud-init metadata when running 
```
curl http://169.254.169.254/openstack/latest/user_data
```

**6. What did you expect to happen?**

nodeup process deploys node successfully.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2024-01-01T14:46:43Z"
  name: my-cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        clusterName: my-cluster.k8s.local
        ignore-volume-az: true
      monitor:
        delay: 15s
        maxRetries: 3
        timeout: 10s
      router:
        dnsServers: 8.8.8.8,8.8.4.4
        externalNetwork: floating-ip
  cloudControllerManager:
    clusterName: my-cluster.k8s.local
  cloudProvider: openstack
  configBase: s3://xxx
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-nova-1
      name: etcd-1
      volumeType: cinder-ssd1
    - instanceGroup: control-plane-nova-2
      name: etcd-2
      volumeType: cinder-ssd1
    - instanceGroup: control-plane-nova-3
      name: etcd-3
      volumeType: cinder-ssd1
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-nova-1
      name: etcd-1
      volumeType: cinder-ssd1
    - instanceGroup: control-plane-nova-2
      name: etcd-2
      volumeType: cinder-ssd1
    - instanceGroup: control-plane-nova-3
      name: etcd-3
      volumeType: cinder-ssd1
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.28.4
  masterPublicName: api.my-cluster.k8s.local
  networkCIDR: 10.10.0.0/24
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.10.0.0/24
    name: nova
    type: Public
    zone: nova
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-01-01T14:46:43Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: control-plane-nova-1
spec:
  image: jammy
  machineType: nova1.2xsmall
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-01-01T14:46:43Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: control-plane-nova-2
spec:
  image: jammy
  machineType: nova1.2xsmall
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-01-01T14:46:44Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: control-plane-nova-3
spec:
  image: jammy
  machineType: nova1.2xsmall
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-01-01T14:46:44Z"
  labels:
    kops.k8s.io/cluster: my-cluster.k8s.local
  name: nodes-nova
spec:
  image: jammy
  machineType: nova1.tiny
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - nova

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Note that S3* variables are presents on ctrl plane machines and they deploys well.
