### ISSUE TITLE
Switch from Cluster Autoscaler to Karpenter on AWS does not register nodes on target groups

### ISSUE THREAD

**Issue by alex-voigt** [kubernetes/kops#16235]
We are currently struggling to switch from a working Cluster Autoscaler setup to Karpenter on AWS using kOps. After manually disabling CAS and deleting the ASGs Karpenter took control over the instance groups and simply works, but the new nodes are not registered in the specified target groups.

The InstanceGroup config uses the externalLoadBalancers with targetGroupArn (which worked with CAS before):
```yaml
externalLoadBalancers:
- targetGroupArn: arn:aws:elasticloadbalancing:eu-central-1.some-id
- targetGroupArn: arn:aws:elasticloadbalancing:eu-central-1.another-id
```

What else is needed to make them register?
