### ISSUE TITLE
Support dns=none with Terraform

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#16328]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Kops' dns=none doesn't work with terraform ([example prow failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-scenario-terraform/1755216246539816960)). In the terraform plan output, base64 decoding the aws_launch_template's user_data reveals:

```yaml
ClusterName: e2e-e2e-kops-scenario-terraform.test-cncf-aws.k8s.io
ConfigServer:
  servers:
  - https://kops-controller.internal.e2e-e2e-kops-scenario-terraform.test-cncf-aws.k8s.io:3988/
```

This DNS record doesn't exist in any DNS zone with dns=none, nor does nodeup know what it should resolve to in order to add an /etc/hosts entry. 

The userdata should be using the ELB's DNS name like `api-e2e-e2e-kops-aws-arm6-i3jlo6-e2dab7cbf5eb0e5a.elb.eu-central-1.amazonaws.com`

**2. Feel free to provide a design supporting your feature request.**

Implementing this is a bit tricky because the userdata needs to change only for --target=terraform - it will need to conditionally include interpolation like:

```yaml
ConfigServer:
  servers:
  - https://${aws_lb.api-e2e-e2e-kops-scenario-terraform-test-cncf-aws-k8s-io.dns_name}:3988/
```

We should also document this limitation (and even add `update cluster --target terraform` validation) until it is supported.
