### ISSUE TITLE
Provisioing m7i.large instances in us-east-1 reverting to old instance type

### ISSUE THREAD

**Issue by jgrasett** [kubernetes/kops#16716]
Running:
kops version:
 v1.28.5
kubernetes version:
1.28.11
on:
AWS

Changes made:
Edit instance group and specify new instance type, replacing t3.large with m7i.large (this during overall kubernetes upgrade from 1.27.x to 1.28.x)

What I did:
Run rolling update on instance group. (this is final update after cluster and all other instance groups)

What Happened:
Instances are replaced with new kubernetes version, but old instance type of t3.large

What I expected:
Instances replaced with new kubernetes version and new instance type.

instance group:

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-19T12:09:32Z"
  generation: 31
  labels:
    kops.k8s.io/cluster:  <redacted>
  name: <redacted>
spec:
  image: ami-087ae2c33ef6846c9
  machineType: m7i.large
  maxSize: 95
  minSize: 90
  nodeLabels:
    kops.k8s.io/instancegroup: <redacted>
  role: Node
  rollingUpdate:
    maxSurge: 20
    maxUnavailable: 10
  subnets:
  - us-east-1f

```
