### ISSUE TITLE
Missing Services in AWS Cluster When 'hostedZoneIDs' Parameter Used with Kops to create cluster with kubernetes 1.29

### ISSUE THREAD

**Issue by FleischerT** [kubernetes/kops#16806]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.29.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.29.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I executed the command
```bash
kops create -f kops.yaml
```
, with cert-manager activated as a plugin and the
hostedZoneIDs
parameter included in the cluster manifest (see Point 7).

**5. What happened after the commands executed?**

The cluster is starting up, but some of the services, most notably the cert-manager-webhook service, are missing.

**6. What did you expect to happen?**

The cluster starts up, is healthy, and no services are missing.

**7. Please provide your cluster manifest. **

```yaml
spec:
  certManager:
    enabled: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    hostedZoneIDs:
    - ZONEID !The correct one is removed for privacy!
  iam:
    useServiceAccountExternalPermissions: true
```

**9. Anything else do we need to know?**

I've tried many things, but every time I set the 'hostedZoneIDs' parameter, the cluster does not become fully operable. If I remove that parameter, then the cluster is created correctly and operates without any issues.

I also looked into the cert-manager code and can't find the 'hostedZoneIDs' parameter.
