### ISSUE TITLE
[ROOT VOLUME] Missing labels on root volumes on Nodes

### ISSUE THREAD

**Issue by dannyeuu** [kubernetes/kops#16908]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
On our FINOPS reports, the EBS of root volumes on all nodes is missing labels. The EBS of CSIs has labels right, but the root does not. We use kOps on AWS with SpotInst.

**2. Feel free to provide a design supporting your feature request.**
Apply the same `nodelabels` to root volume, and add a feature like `rootvolumelabels` on instance groups to add others labels

**Comment by hakman** [comment]
FYI @yehielnetapp

**Comment by vitaliyf** [comment]
If I understand you correctly, `cloudLabels` will do what you are missing:

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.our.cluster.name
  name: control-plane-aws-region-1
spec:
  cloudLabels:
    Environment: production
    Role: k8s
    Something: else
  role: Master
  other: values-here
```

This will add Environment/Role/Something tags to the instance and its volumes for this instancegroup, including even etcd's EBS volumes.
