### ISSUE TITLE
Nodeup (`kops-configuration.service`) fails with `dns=none`

### ISSUE THREAD

**Issue by unexge** [kubernetes/kops#16935]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`v1.28.5` also reproduced with `v1.30.1`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`v1.28.13`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster \
    --state s3://mountpoint-s3-csi-driver-kops-state-store \
    --zones us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1f \
    --node-count=3 --node-size=c5.large \
    --image=ami-06b21ccaeff8cd686 --kubernetes-version=1.28.13 \
    --dry-run --cloud aws -o yaml \
        s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
```
See https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/tests/e2e-kubernetes/scripts/kops.sh#L46-L56

**5. What happened after the commands executed?**

`kops validate cluster --wait 15m` fails after 15m with:

```
VALIDATION ERRORS
KIND    NAME                                            MESSAGE
Machine i-0211d24650a043c04                             machine "i-0211d24650a043c04" has not yet joined cluster
Machine i-0397f8bb78c4c36c9                             machine "i-0397f8bb78c4c36c9" has not yet joined cluster
Machine i-0baf7add6c85c881b                             machine "i-0baf7add6c85c881b" has not yet joined cluster
Pod     kube-system/coredns-78ccb5b8c5-hdwpv            system-cluster-critical pod "coredns-78ccb5b8c5-hdwpv" is pending
Pod     kube-system/coredns-autoscaler-55c99b49b7-np8mx system-cluster-critical pod "coredns-autoscaler-55c99b49b7-np8mx" is pending

Validation Failed
W1106 16:21:44.017841   92431 validate_cluster.go:234] (will retry): cluster not yet healthy
Error: validation failed: wait time exceeded during validation
```

**6. What did you expect to happen?**

Expected nodes to join to the cluster. The weird thing is it was working 2 weeks ago, and nothing changed on the CI since.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2024-11-06T16:02:31Z"
  name: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
spec:
  additionalPolicies:
    node: |-
      [
        {
          "Effect": "Allow",
          "Action": [
            "s3:*",
            "s3express:*"
          ],
          "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mountpoint-s3-csi-driver-kops-state-store/s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.28.13
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.0.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.32.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 172.20.64.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 172.20.96.0/19
    name: us-east-1d
    type: Public
    zone: us-east-1d
  - cidr: 172.20.128.0/19
    name: us-east-1f
    type: Public
    zone: us-east-1f
  topology:
    dns:
      type: None

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-06T16:02:33Z"
  labels:
    kops.k8s.io/cluster: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  name: control-plane-us-east-1a
spec:
  image: ami-06b21ccaeff8cd686
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-06T16:02:33Z"
  labels:
    kops.k8s.io/cluster: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  name: nodes-us-east-1a
spec:
  image: ami-06b21ccaeff8cd686
  instanceMetadata:
    httpPutResponseHopLimit: 3
  machineType: c5.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-06T16:02:34Z"
  labels:
    kops.k8s.io/cluster: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  name: nodes-us-east-1b
spec:
  image: ami-06b21ccaeff8cd686
  instanceMetadata:
    httpPutResponseHopLimit: 3
  machineType: c5.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-06T16:02:34Z"
  labels:
    kops.k8s.io/cluster: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  name: nodes-us-east-1c
spec:
  image: ami-06b21ccaeff8cd686
  instanceMetadata:
    httpPutResponseHopLimit: 3
  machineType: c5.large
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-06T16:02:34Z"
  labels:
    kops.k8s.io/cluster: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  name: nodes-us-east-1d
spec:
  image: ami-06b21ccaeff8cd686
  instanceMetadata:
    httpPutResponseHopLimit: 3
  machineType: c5.large
  maxSize: 0
  minSize: 0
  role: Node
  subnets:
  - us-east-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-06T16:02:35Z"
  labels:
    kops.k8s.io/cluster: s3-csi-cluster-kops-amazonlinux2-x86-1-28-13.k8s.local
  name: nodes-us-east-1f
spec:
  image: ami-06b21ccaeff8cd686
  instanceMetadata:
    httpPutResponseHopLimit: 3
  machineType: c5.large
  maxSize: 0
  minSize: 0
  role: Node
  subnets:
  - us-east-1f

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Ran one of the failed nodes:
```
$ journalctl -u kops-configuration.service 
Nov 06 16:07:02 i-0baf7add6c85c881b.ec2.internal systemd[1]: Starting kops-configuration.service - Run kOps bootstrap (nodeup)...
Nov 06 16:07:02 i-0baf7add6c85c881b.ec2.internal nodeup[1829]: nodeup version 1.29.2 (git-v1.29.2)
Nov 06 16:08:19 i-0baf7add6c85c881b.ec2.internal nodeup[1829]: W1106 16:08:19.263342    1829 main.go:133] got error running nodeup (will retry in 30s): failed to get node config from server: Post "https://172.20.107.157:3988/bootstrap": context deadline exceeded (Client.Timeout exceeded while awaiting headers); Post "https://172.20.12.152:3988/bootstrap": context deadline exceeded (Client.Timeout exceeded while awaiting headers); Post "https://172.20.157.230:3988/bootstrap": context deadline exceeded (Client.Timeout exceeded while awaiting headers); Post "https://172.20.46.209:3988/bootstrap": context deadline exceeded (Client.Timeout exceeded while awaiting headers); Post "https://172.20.70.75:3988/bootstrap": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Nov 06 16:09:30 i-0baf7add6c85c881b.ec2.internal systemd[1]: kops-configuration.service: Main process exited, code=killed, status=15/TERM
Nov 06 16:09:30 i-0baf7add6c85c881b.ec2.internal systemd[1]: kops-configuration.service: Failed with result 'signal'.
Nov 06 16:09:30 i-0baf7add6c85c881b.ec2.internal systemd[1]: Stopped kops-configuration.service - Run kOps bootstrap (nodeup).
```

**9. Anything else do we need to know?**

After restarting `kops-configuration.service` service, it works:
```
...
Nov 06 16:28:48 i-0baf7add6c85c881b.ec2.internal nodeup[2862]: success
```
I'd like to avoid doing that because we create and destroy kOps clusters as part of our CI to test our software.
