### ISSUE TITLE
Add healthcheck protocol choice on APISpec for loadbalancers

### ISSUE THREAD

**Issue by yelaissaoui** [kubernetes/kops#17145]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
In Kubernetes v1.30, some ciphers used by AWS SSL healthcheck for the CLB are now classified as insecure by the kube-apiserver, the healthcheck fails as it's using SSL and the Controlplane is considered out-of-service by the Loadbalancer. 
If we change the healthcheck protocol manually to TCP, it works.
Today, Kops only uses SSL as a healthcheck protocol for CLB.

-> Is it possible to add the choice of healthcheck protocol used on the loadbalancer generated by Kops ?

**2. Feel free to provide a design supporting your feature request.**
Example of configuration on the kops cluster :
```
   api:
      loadBalancer:
        class: Classic
        type: Internal
 +      healthcheck: (TCP|SSL|..)
```
