### ISSUE TITLE
k8s upgrade to 1.27 fails when "ExpandPersistentVolumes" feature flag is enabled

### ISSUE THREAD

**Issue by marek-obuchowicz** [kubernetes/kops#17252]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops-1.30.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.27.16

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops upgrade cluster (1.26.x -> 1.27.16)

**5. What happened after the commands executed?**

master nodes don't come up after rolling update. Kubelet reports following error:

```
Feb 04 20:07:50 i-... kubelet[3571]: E0204 20:07:50.696548    3571 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: unrecognized feature gate: ExpandPersistentVolumes"
```

**6. What did you expect to happen?**

`kops edit cluster` should not accept cluster spec with deprecated kubelet feature flag

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
spec:
# [...]
  channel: stable
  cloudProvider: aws
  containerRuntime: containerd
  kubeAPIServer:
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - PersistentVolumeClaimResize
    - ResourceQuota
    featureGates:
      ExpandPersistentVolumes: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
# [...]
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cgroupDriver: systemd
    featureGates:
      ExpandPersistentVolumes: "true"
    imageGCHighThresholdPercent: 75
    imageGCLowThresholdPercent: 60
# [...]
  kubernetesVersion: 1.27.16
# [...]

```
