### ISSUE TITLE
Ability to specify custom arguments to Kubernetes binaries like kube-scheduler

### ISSUE THREAD

**Issue by bartpeeters** [kubernetes/kops#17253]
/kind feature

We would like to use the `-vmodule` argument of the kube-scheduler, so we can set the log level for the `schedule_one.go` module to 10, so that it will log scores when scheduling pods in our Kubernetes cluster.

Currently, you can only specify `logLevel` in the cluster spec for kubeScheduler:

```
kind: Cluster
spec:
  kubeScheduler:
    logLevel: 10
```

This `logLevel` is then transformed to the `--v 10` argument in the kube-scheduler pod manifest.

But this is the log level of all components within kube-scheduler, so setting this to 10, results in a lot of logs, most of which we are not interested in.

It would be nice if you could specify extra arguments to the kube-scheduler and maybe other components like kube-controller-manager, kubelet, ...
Which would allow us to set the `--vmodule` argument, example:

```
kind: Cluster
spec:
  kubeScheduler:
    args:
    - "--vmodule schedule_one*=10,scheduler*=3"

```
