### ISSUE TITLE
taints without value are not propagated to AWS ASG tags

### ISSUE THREAD

**Issue by jzhn** [kubernetes/kops#17308]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.30.3, but based on kops code, the issue should be reproduciable from master branch. 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.30.10

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops create -f` with an `InstanceGroup` that has taints defined in the format of `foo:NoSchedule` (with `=<value>` omitted)

**5. What happened after the commands executed?**

kops upserts AWS AutoScaling group. But `k8s.io/cluster-autoscaler/node-template/taint/foo` tag is missing from the ASG. And this might cause Cluster Autoscaler to incorrectly scale up InstanceGroups that actually cannot accomonodate the pending workloads.

**6. What did you expect to happen?**

ASG is tagged with `k8s.io/cluster-autoscaler/node-template/taint/<key>`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  generation: 1
  labels:
    kops.k8s.io/cluster: <redacted>
  name: foo
spec:
  additionalSecurityGroups:
  - <redacted>
  iam:
    profile: <redacted>
  image: <redacted>
  instanceMetadata:
    httpTokens: optional
  machineType: m7i.4xlarge
  maxSize: 20
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: foo
    node.k8s.foo.com/instance-group: foo
    node.k8s.foo.com/network-tier: tier-2
  role: Node
  rootVolumeEncryption: true
  rootVolumeOptimization: true
  rootVolumeSize: 100
  subnets:
  - <redacted>
  taints:
  - foo:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

- At https://agithub.com/kubernetes/kops/blob/v1.31.0/pkg/model/context.go#L188, kops expects the `taints` to always have `=`, otherwise it skips the tag injection. however per [kubernetes doc](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_taint/), omitting `=` when value is empty is valid.
- The instance group, despite not having its taints populated in AWS ASG, is functional with Cluster Autoscaler. So both kops and CAS can handle the `<key>:<effect>` format. So it seems like only the linked code above needs to be fixed.
