### ISSUE TITLE
Update cluster says theres modifications but i havent changed anything

### ISSUE THREAD

**Issue by jacobRichardIndio** [kubernetes/kops#17316]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kubectl version --kubeconfig tempparam
Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client version: 1.28.7 (git-v1.28.7)
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update clustername  --state s3-state-store --config tempparam
**5. What happened after the commands executed?**

It said the following resources will be modified but i havent made any changes to these resources.

  AutoscalingGroup/autoscalinggroup1name
  	MaxInstanceLifetime 	 0 -> 86400
  	WarmPool            	 <nil> -> error marshaling: json: unsupported value: encountered a cycle via *awstasks.WarmPool
  AutoscalingGroup/autoscalinggroup2name
  	WarmPool            	 <nil> -> error marshaling: json: unsupported value: encountered a cycle via *awstasks.WarmPool

**6. What did you expect to happen?**

No modifications since i havent the instancegroups havent changed.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Here is just the instancegroups, let me know if you need more info.
```
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-03-12T15:09:04Z"
  generation: 11
  labels:
    kops.k8s.io/cluster: clustername.com
  name: autoscalinggroup1name
spec:
  image: imagename
  machineType: m6a.2xlarge
  maxInstanceLifetime: 24h0m0s
  maxSize: 10
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: autoscalinggroup1name
    role: autoscalinggroup1name
  packages:
  - xfsprogs
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 200
  rootVolumeType: gp3
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  taints:
  - role=gitlab:NoSchedule
  warmPool:
    maxSize: 3
    minSize: 3

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-11-10T14:19:51Z"
  generation: 18
  labels:
    kops.k8s.io/cluster: clustername.com
  name: autoscalinggroup2name
spec:
  image: imagename
  machineType: r6a.xlarge
  maxInstanceLifetime: 72h0m0s
  maxSize: 30
  minSize: 10
  nodeLabels:
    kops.k8s.io/instancegroup: autoscalinggroup2name
  packages:
  - xfsprogs
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 200
  rootVolumeType: gp3
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  warmPool:
    maxSize: 3
    minSize: 3
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
