### ISSUE TITLE
ARM machine type specified is invalid

### ISSUE THREAD

**Issue by baka126** [kubernetes/kops#17353]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Client version: 1.31.0 
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: v1.32.3
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
 kops update cluster --name example --yes
**5. What happened after the commands executed?**
command failed during cluster creation
**6. What did you expect to happen?**
expected to create a new cluster
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: control-plane-ap-south-1a
spec:
  image: ami-02797b01b0035d52b
  machineType: t4g.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  rootVolumeType: gp3
  rootVolumeEncryption: true
  rootVolumeOptimization: true
  subnets:
  - ap-south-1a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
Calling DescribeImages to resolve name "ami-02797b01b0035d52b"
 aws_cloud.go:2018] Resolved image "ami-02797b01b0035d52b"
 logger.go:36] AWS request: request failed with unretryable error https response error StatusCode: 400, RequestID: f90c6808-9535-4aae-a3db-34bdae322f74, api error InvalidInstanceType: The following supplied instance types do not exist: []
Error: spec.machineType: Invalid value: "": machine type specified is invalid: ""
```
**9. Anything else do we need to know?**
I am trying to run master and worker nodes on ARM with flatcar.
