### ISSUE TITLE
csi-storage-plugin not working in Openstack cloud with private CA

### ISSUE THREAD

**Issue by elehcim** [kubernetes/kops#17359]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Client version: 1.31.0 (git-v1.31.0)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.31.0

**3. What cloud provider are you using?**
openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops replace -f mycluster.yaml --force
```
```
kops update cluster --name mycluster.k8s.local --yes
```
```
kops validate cluster --wait 10m
```

**5. What happened after the commands executed?**
The cluster is not validated 

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2025-04-16T11:29:33Z"
  name: mycluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v3
        clusterName: mycluster.k8s.local
        ignore-volume-az: true
      loadbalancer:
        floatingNetwork: ...
        floatingNetworkID: ...
        method: ROUND_ROBIN
        provider: amphora
        useOctavia: true
      monitor:
        delay: 15s
        maxRetries: 3
        timeout: 10s
      router:
        externalNetwork: ...
  cloudControllerManager:
    clusterName: mycluster.k8s.local
  cloudProvider: openstack
  configBase: do://kops/mycluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-nova-1
      name: etcd-1
      volumeSize: 10
      volumeType: __DEFAULT__
    - instanceGroup: control-plane-nova-2
      name: etcd-2
      volumeSize: 10
      volumeType: __DEFAULT__
    - instanceGroup: control-plane-nova-3
      name: etcd-3
      volumeSize: 10
      volumeType: __DEFAULT__
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-nova-1
      name: etcd-1
      volumeSize: 10
      volumeType: __DEFAULT__
    - instanceGroup: control-plane-nova-2
      name: etcd-2
      volumeSize: 10
      volumeType: __DEFAULT__
    - instanceGroup: control-plane-nova-3
      name: etcd-3
      volumeSize: 10
      volumeType: __DEFAULT__
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.31.7
  networkCIDR: 10.33.0.0/24
  networkID: ...
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.33.0.128/25
    id: ...
    name: nova
    type: Private
    zone: nova
  - cidr: 10.33.0.0/28
    id: ...
    name: utility-nova
    type: Utility
    zone: nova
  topology:
    dns:
      type: None
  useHostCertificates: true

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-16T11:29:35Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: bastions
spec:
  associatePublicIp: true
  image: Ubuntu Server 24.04 LTS (Noble Numbat)
  machineType: fl1
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-16T11:29:34Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: control-plane-nova-1
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      curl -kL http://path/to/cert.crt > \
      /usr/local/share/ca-certificates/cert.crt
      update-ca-certificates
    name: cacert.sh
    type: text/x-shellscript
  associatePublicIp: true
  image: Ubuntu Server 24.04 LTS (Noble Numbat)
  machineType: fl1
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-16T11:29:34Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: control-plane-nova-2
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      curl -kL http://path/to/cert.crt > \
      /usr/local/share/ca-certificates/cert.crt
      update-ca-certificates
    name: cacert.sh
    type: text/x-shellscript
  associatePublicIp: true
  image: Ubuntu Server 24.04 LTS (Noble Numbat)
  machineType: fl1
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-16T11:29:34Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: control-plane-nova-3
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      curl -kL http://path/to/cert.crt > \
      /usr/local/share/ca-certificates/cert.crt
      update-ca-certificates
    name: cacert.sh
    type: text/x-shellscript
  associatePublicIp: true
  image: Ubuntu Server 24.04 LTS (Noble Numbat)
  machineType: fl1
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  subnets:
  - nova

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-04-16T11:29:34Z"
  labels:
    kops.k8s.io/cluster: mycluster.k8s.local
  name: nodes-nova
spec:
  associatePublicIp: true
  image: Ubuntu Server 24.04 LTS (Noble Numbat)
  machineType: fl1
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - nova

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
$ kops validate cluster --wait 10m
...
NODE STATUS
NAME                            ROLE            READY
control-plane-nova-1-yo5z5q     control-plane   True
control-plane-nova-2-i3fd1v     control-plane   True
control-plane-nova-3-fgskj1     control-plane   True
nodes-nova-u4qdd7               node            True

VALIDATION ERRORS
KIND    NAME                                                    MESSAGE
Pod     kube-system/csi-cinder-controllerplugin-7b7fb6997-dnrw7 system-cluster-critical pod "csi-cinder-controllerplugin-7b7fb6997-dnrw7" is not ready (cinder-csi-plugin,csi-attacher,csi-provisioner,csi-resizer)
Pod     kube-system/csi-cinder-nodeplugin-68h2v                 system-node-critical pod "csi-cinder-nodeplugin-68h2v" is not ready (cinder-csi-plugin,node-driver-registrar)
Pod     kube-system/csi-cinder-nodeplugin-6k5nk                 system-node-critical pod "csi-cinder-nodeplugin-6k5nk" is not ready (cinder-csi-plugin,node-driver-registrar)
Pod     kube-system/csi-cinder-nodeplugin-cztjn                 system-node-critical pod "csi-cinder-nodeplugin-cztjn" is not ready (cinder-csi-plugin,node-driver-registrar)
Pod     kube-system/csi-cinder-nodeplugin-fshbr                 system-node-critical pod "csi-cinder-nodeplugin-fshbr" is not ready (cinder-csi-plugin)

Validation Failed
W0416 13:43:53.848267  582569 validate_cluster.go:230] (will retry): cluster not yet healthy
Error: validation failed: wait time exceeded during validation
```

**9. Anything else do we need to know?**
when exploring the logs of one `csi-cinder-nodeplugin` pod in the `cinder-csi-plugin` container I get

```
ubuntu@control-plane-nova-1-yo5z5q:~$ kubectl logs csi-cinder-nodeplugin-6k5nk -n kube-system -c cinder-csi-plugin
2025/04/16 13:29:13 Running command:
Command env: (log-file=, also-stdout=false, redirect-stderr=true)
Run from directory: 
Executable path: /bin/cinder-csi-plugin
Args (comma-delimited): /bin/cinder-csi-plugin,--endpoint=unix://csi/csi.sock,--cloud-config=/etc/kubernetes/cloud.config,--cluster=cloudsvc.k8s.local
2025/04/16 13:29:13 Now listening for interrupts
I0416 13:29:13.712132      10 driver.go:85] Driver: cinder.csi.openstack.org
I0416 13:29:13.712161      10 driver.go:86] Driver version: 2.0.0@v1.31.0
I0416 13:29:13.712164      10 driver.go:87] CSI Spec version: 1.8.0
I0416 13:29:13.712168      10 driver.go:124] Enabling controller service capability: LIST_VOLUMES
I0416 13:29:13.712172      10 driver.go:124] Enabling controller service capability: CREATE_DELETE_VOLUME
I0416 13:29:13.712272      10 driver.go:124] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0416 13:29:13.712280      10 driver.go:124] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0416 13:29:13.712282      10 driver.go:124] Enabling controller service capability: LIST_SNAPSHOTS
I0416 13:29:13.712284      10 driver.go:124] Enabling controller service capability: EXPAND_VOLUME
I0416 13:29:13.712286      10 driver.go:124] Enabling controller service capability: CLONE_VOLUME
I0416 13:29:13.712288      10 driver.go:124] Enabling controller service capability: LIST_VOLUMES_PUBLISHED_NODES
I0416 13:29:13.712290      10 driver.go:124] Enabling controller service capability: GET_VOLUME
I0416 13:29:13.712352      10 driver.go:135] Enabling volume access mode: SINGLE_NODE_WRITER
I0416 13:29:13.712355      10 driver.go:148] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0416 13:29:13.712358      10 driver.go:148] Enabling node service capability: EXPAND_VOLUME
I0416 13:29:13.712398      10 driver.go:148] Enabling node service capability: GET_VOLUME_STATS
I0416 13:29:13.712833      10 openstack.go:100] Global: ""
I0416 13:29:13.712860      10 openstack.go:103] Block storage opts: {0 false true false}
W0416 13:29:13.733217      10 main.go:95] Failed to GetOpenStackProvider : Get "https://my_cloud_url:5000/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

I think the private `cacert.crt` is not passed to the `csi-storage-plugin` container. As you see by using `additionalUserData` like in issue #11528, the cacert is on the control-plane nodes and it is used by the cluster by setting `useHostCertificates: true`.

[Here](https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml) the `/etc/cacert` mount point is commented out and [here](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#using-the-manifests) it is written to uncomment it when you have a privately signed cacert. I don't know how to manage this situation in kops.

I imagine I'd need to add the `cacert.crt` path in the `/etc/kubernetes/cloud.config` file using the `ca-file` option but also mount a folder containing it in the `csi-storage-plugin` container. How can I accomplish that?
Thanks
