### ISSUE TITLE
Kops upgrade command doesnt upgrade kubernetes to 1.31

### ISSUE THREAD

**Issue by atze234** [kubernetes/kops#17381]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Client version: 1.31.0 (git-v1.31.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`Server Version: v1.30.11`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops upgrade cluster --name=xxx --state=xxx

No upgrade required

```

**5. What happened after the commands executed?**
Nothing

**6. What did you expect to happen?**
Should upgrade Kubernetes to 1.31.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-05-14T11:49:49Z"
  generation: 61
  name: x
spec:
  api:
    loadBalancer:
      class: Network
      idleTimeoutSeconds: 3600
      type: Internal
  authentication:
    aws:
      backendMode: EKSConfigMap
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Bill_To: "x"
    Product: x
  cloudProvider: aws
  configBase: s3://x/x
  dnsZone: x
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    manager:
      backupRetentionDays: 90
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    manager:
      backupRetentionDays: 90
    name: events
  fileAssets:
  - content: "cutted"
    name: audit-config
    path: /srv/kubernetes/kube-apiserver/audit.conf
    roles:
    - ControlPlane
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit.conf
    logLevel: 1
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.30.11
  masterPublicName: api.x
  networkCIDR: x
  networkID: vpc-x
  networking:
    calico:
      ipv4AutoDetectionMethod: can-reach=x
  nodeTerminationHandler:
    enabled: false
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - x
  - x
  subnets:
  - cidr: x/23
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: x/23
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: x/24
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: x/24
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  topology:
    dns:
      type: Private
  updatePolicy: external

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-08-31T13:01:29Z"
  generation: 14
  labels:
    kops.k8s.io/cluster: x
  name: master-eu-central-1a
spec:
  cloudLabels:
    maxSize: "1"
    minSize: "1"
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250305
  machineType: c5.large
  maxPrice: "0.23"
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c5.large
    - m5.large
    - c4.large
    - m4.large
    onDemandAboveBase: 0
    onDemandBase: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
    lifecycle: Ec2Spot
    node-role.kubernetes.io/spot-worker: "true"
  role: Master
  subnets:
  - eu-central-1a


```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
kops upgrade cluster --name=x --state=s3://x -v 10
I0502 10:25:56.866905    4445 factory.go:98] state store s3://x
I0502 10:25:56.867004    4445 s3context.go:359] product_uuid is "4c4c4544-0048-3110-8030-c7c04f524733", assuming not running on EC2
I0502 10:25:56.867012    4445 s3context.go:192] defaulting region to "us-east-1"
I0502 10:25:57.875711    4445 s3context.go:228] found bucket in region "eu-central-1"
I0502 10:25:57.876185    4445 s3fs.go:405] Reading file "s3://x/x/config"
I0502 10:25:58.559580    4445 s3fs.go:443] Listing objects in S3 bucket "x" with prefix "x/instancegroup/"
I0502 10:25:58.593029    4445 s3fs.go:472] Listed files in s3://x/x/instancegroup: [s3://x/x/instancegroup/master-eu-central-1a s3://x/x/instancegroup/nodes s3://x/x/instancegroup/nodes-b s3://x/x/instancegroup/nodes-fallback]
I0502 10:25:58.593048    4445 s3fs.go:405] Reading file "s3://x/x/instancegroup/master-eu-central-1a"
I0502 10:25:58.665651    4445 s3fs.go:405] Reading file "s3://x/x/instancegroup/nodes"
I0502 10:25:58.745677    4445 s3fs.go:405] Reading file "s3://x/x/instancegroup/nodes-b"
I0502 10:25:58.787963    4445 s3fs.go:405] Reading file "s3://x/x/instancegroup/nodes-fallback"
I0502 10:25:58.826047    4445 channel.go:123] resolving "stable" against default channel location "https://raw.githubusercontent.com/kubernetes/kops/master/channels/"
I0502 10:25:58.826062    4445 channel.go:143] Loading channel from "https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable"
I0502 10:25:58.826070    4445 context.go:245] Performing HTTP request: GET https://raw.githubusercontent.com/kubernetes/kops/master/channels/stable
I0502 10:25:58.916727    4445 channel.go:152] Channel contents: spec:
  images:
    # We put the "legacy" version first, for kops versions that don't support versions ( < 1.5.0 )
    - name: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-07-28
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.4.0 <1.5.0"
    - name: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.5.0 <1.6.0"
    - name: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.6.0 <1.7.0"
    - name: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.7.0 <1.8.0"
    - name: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.8.0 <1.9.0"
    - name: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.9.0 <1.10.0"
    - name: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.10.0 <1.11.0"
    # Stretch is the default for 1.11 (for nvme)
    - name: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.11.0 <1.12.0"
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.12.0 <1.13.0"
    - name: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.13.0 <1.14.0"
    - name: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.14.0 <1.15.0"
    - name: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.15.0 <1.16.0"
    - name: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.16.0 <1.17.0"
    - name: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2021-02-05
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.17.0 <1.18.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20250312
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.18.0 <1.27.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20250312
      providerID: aws
      architectureID: arm64
      kubernetesVersion: ">=1.20.0 <1.27.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250305
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.27.0 <1.32.0"
    - name: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20250305
      providerID: aws
      architectureID: arm64
      kubernetesVersion: ">=1.27.0 <1.32.0"
    - name: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250305
      providerID: aws
      architectureID: amd64
      kubernetesVersion: ">=1.32.0"
    - name: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-20250305
      providerID: aws
      architectureID: arm64
      kubernetesVersion: ">=1.32.0"
    - name: cos-cloud/cos-stable-65-10323-99-0
      providerID: gce
      architectureID: amd64
      kubernetesVersion: "<1.16.0-alpha.1"
    - name: "cos-cloud/cos-stable-77-12371-114-0"
      providerID: gce
      architectureID: amd64
      kubernetesVersion: ">=1.16.0 <1.18.0"
    - name: ubuntu-os-cloud/ubuntu-2004-focal-v20240607
      providerID: gce
      architectureID: amd64
      kubernetesVersion: ">=1.18.0 <1.27.0"
    - name: ubuntu-os-cloud/ubuntu-2204-jammy-v20240607
      providerID: gce
      architectureID: amd64
      kubernetesVersion: ">=1.27.0 <1.32.0"
    - name: ubuntu-os-cloud/ubuntu-2404-noble-amd64-v20240701a
      providerID: gce
      architectureID: amd64
      kubernetesVersion: ">=1.32.0"
    - name: Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202406060
      providerID: azure
      architectureID: amd64
      kubernetesVersion: ">=1.20.0 <1.27.0"
    - name: Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:22.04.202405140
      providerID: azure
      architectureID: amd64
      kubernetesVersion: ">=1.27.0 <1.32.0"
    - name: Canonical:ubuntu-24_04-lts:server-gen1:24.04.202407011
      providerID: azure
      architectureID: amd64
      kubernetesVersion: ">=1.32.0"
  cluster:
    kubernetesVersion: v1.5.8
    networking:
      kubenet: {}
  kubernetesVersions:
  - range: ">=1.32.0"
    recommendedVersion: 1.32.3
    requiredVersion: 1.30.0
  - range: ">=1.31.0"
    recommendedVersion: 1.31.7
    requiredVersion: 1.30.0
  - range: ">=1.30.0"
    recommendedVersion: 1.30.11
    requiredVersion: 1.30.0
  - range: ">=1.29.0"
    recommendedVersion: 1.29.15
    requiredVersion: 1.29.0
  - range: ">=1.28.0"
    recommendedVersion: 1.28.15
    requiredVersion: 1.28.0
  - range: ">=1.27.0"
    recommendedVersion: 1.27.16
    requiredVersion: 1.27.0
  - range: ">=1.26.0"
    recommendedVersion: 1.26.15
    requiredVersion: 1.26.0
  - range: ">=1.25.0"
    recommendedVersion: 1.25.16
    requiredVersion: 1.25.0
  - range: ">=1.24.0"
    recommendedVersion: 1.24.17
    requiredVersion: 1.24.0
  - range: ">=1.23.0"
    recommendedVersion: 1.23.17
    requiredVersion: 1.23.0
  - range: ">=1.22.0"
    recommendedVersion: 1.22.17
    requiredVersion: 1.22.0
  - range: ">=1.21.0"
    recommendedVersion: 1.21.14
    requiredVersion: 1.21.0
  - range: ">=1.20.0"
    recommendedVersion: 1.20.15
    requiredVersion: 1.20.0
  - range: ">=1.19.0"
    recommendedVersion: 1.19.16
    requiredVersion: 1.19.0
  - range: ">=1.18.0"
    recommendedVersion: 1.18.20
    requiredVersion: 1.18.0
  - range: ">=1.17.0"
    recommendedVersion: 1.17.17
    requiredVersion: 1.17.0
  - range: ">=1.16.0"
    recommendedVersion: 1.16.15
    requiredVersion: 1.16.0
  - range: ">=1.15.0"
    recommendedVersion: 1.15.12
    requiredVersion: 1.15.0
  - range: ">=1.14.0"
    recommendedVersion: 1.14.10
    requiredVersion: 1.14.0
  - range: ">=1.13.0"
    recommendedVersion: 1.13.12
    requiredVersion: 1.13.0
  - range: ">=1.12.0"
    recommendedVersion: 1.12.10
    requiredVersion: 1.12.0
  - range: ">=1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.0
  - range: "<1.11.0"
    recommendedVersion: 1.11.10
    requiredVersion: 1.11.10
  kopsVersions:
  - range: ">=1.32.0-alpha.1"
    recommendedVersion: "1.31.0-beta.1"
    #requiredVersion: 1.32.0
    kubernetesVersion: 1.32.3
  - range: ">=1.31.0-alpha.1"
    recommendedVersion: "1.31.0-beta.1"
    #requiredVersion: 1.31.0
    kubernetesVersion: 1.31.7
  - range: ">=1.30.0-alpha.1"
    recommendedVersion: "1.30.3"
    #requiredVersion: 1.30.0
    kubernetesVersion: 1.30.11
  - range: ">=1.29.0-alpha.1"
    recommendedVersion: "1.30.3"
    #requiredVersion: 1.29.0
    kubernetesVersion: 1.29.15
  - range: ">=1.28.0-alpha.1"
    recommendedVersion: "1.30.3"
    #requiredVersion: 1.28.0
    kubernetesVersion: 1.28.15
  - range: ">=1.27.0-alpha.1"
    recommendedVersion: "1.30.3"
    #requiredVersion: 1.27.0
    kubernetesVersion: 1.27.16
  - range: ">=1.26.0-alpha.1"
    recommendedVersion: "1.30.3"
    #requiredVersion: 1.26.0
    kubernetesVersion: 1.26.15
  - range: ">=1.25.0-alpha.1"
    recommendedVersion: "1.30.3"
    #requiredVersion: 1.25.0
    kubernetesVersion: 1.25.16
  - range: ">=1.24.0-alpha.1"
    recommendedVersion: "1.29.2"
    #requiredVersion: 1.24.0
    kubernetesVersion: 1.24.17
  - range: ">=1.23.0-alpha.1"
    recommendedVersion: "1.28.7"
    #requiredVersion: 1.23.0
    kubernetesVersion: 1.23.17
  - range: ">=1.22.0-alpha.1"
    recommendedVersion: "1.27.0"
    #requiredVersion: 1.22.0
    kubernetesVersion: 1.22.17
  - range: ">=1.21.0-alpha.1"
    recommendedVersion: "1.26.5"
    #requiredVersion: 1.21.0
    kubernetesVersion: 1.21.14
  - range: ">=1.20.0-alpha.1"
    recommendedVersion: "1.25.4"
    #requiredVersion: 1.20.0
    kubernetesVersion: 1.20.15
  - range: ">=1.19.0-alpha.1"
    recommendedVersion: "1.24.5"
    #requiredVersion: 1.19.0
    kubernetesVersion: 1.19.16
  - range: ">=1.18.0-alpha.1"
    recommendedVersion: "1.23.4"
    #requiredVersion: 1.18.0
    kubernetesVersion: 1.18.20
  - range: ">=1.17.0-alpha.1"
    recommendedVersion: "1.22.3"
    #requiredVersion: 1.17.0
    kubernetesVersion: 1.17.17
  - range: ">=1.16.0-alpha.1"
    recommendedVersion: "1.21.4"
    #requiredVersion: 1.16.0
    kubernetesVersion: 1.16.15
  - range: ">=1.15.0-alpha.1"
    recommendedVersion: "1.21.4"
    #requiredVersion: 1.15.0
    kubernetesVersion: 1.15.12
  - range: ">=1.14.0-alpha.1"
    #recommendedVersion: "1.14.0"
    #requiredVersion: 1.14.0
    kubernetesVersion: 1.14.10
  - range: ">=1.13.0-alpha.1"
    #recommendedVersion: "1.13.0"
    #requiredVersion: 1.13.0
    kubernetesVersion: 1.13.12
  - range: ">=1.12.0-alpha.1"
    recommendedVersion: "1.12.1"
    #requiredVersion: 1.12.0
    kubernetesVersion: 1.12.10
  - range: ">=1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.11.0
    kubernetesVersion: 1.11.10
  - range: "<1.11.0-alpha.1"
    recommendedVersion: "1.11.1"
    #requiredVersion: 1.10.0
    kubernetesVersion: 1.11.10
I0502 10:25:58.916785    4445 channel.go:255] version range ">=1.32.0" does not apply to version "1.30.11"; skipping
I0502 10:25:58.916793    4445 channel.go:255] version range ">=1.31.0" does not apply to version "1.30.11"; skipping
I0502 10:25:58.916817    4445 aws_utils.go:52] Querying EC2 for all valid regions
I0502 10:25:59.927907    4445 aws_cloud.go:2023] Querying EC2 for all valid zones in region "eu-central-1"
I0502 10:26:00.739787    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.4.0 <1.5.0
I0502 10:26:00.739810    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.5.0 <1.6.0
I0502 10:26:00.739817    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.6.0 <1.7.0
I0502 10:26:00.739823    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.7.0 <1.8.0
I0502 10:26:00.739828    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.8.0 <1.9.0
I0502 10:26:00.739834    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.9.0 <1.10.0
I0502 10:26:00.739839    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.10.0 <1.11.0
I0502 10:26:00.739844    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.11.0 <1.12.0
I0502 10:26:00.739849    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.12.0 <1.13.0
I0502 10:26:00.739854    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.13.0 <1.14.0
I0502 10:26:00.739859    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.14.0 <1.15.0
I0502 10:26:00.739864    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.15.0 <1.16.0
I0502 10:26:00.739869    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.16.0 <1.17.0
I0502 10:26:00.739874    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.17.0 <1.18.0
I0502 10:26:00.739879    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.18.0 <1.27.0
I0502 10:26:00.739886    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.32.0
I0502 10:26:00.780322    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.4.0 <1.5.0
I0502 10:26:00.780335    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.5.0 <1.6.0
I0502 10:26:00.780338    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.6.0 <1.7.0
I0502 10:26:00.780341    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.7.0 <1.8.0
I0502 10:26:00.780343    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.8.0 <1.9.0
I0502 10:26:00.780347    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.9.0 <1.10.0
I0502 10:26:00.780351    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.10.0 <1.11.0
I0502 10:26:00.780360    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.11.0 <1.12.0
I0502 10:26:00.780363    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.12.0 <1.13.0
I0502 10:26:00.780366    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.13.0 <1.14.0
I0502 10:26:00.780369    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.14.0 <1.15.0
I0502 10:26:00.780371    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.15.0 <1.16.0
I0502 10:26:00.780392    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.16.0 <1.17.0
I0502 10:26:00.780395    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.17.0 <1.18.0
I0502 10:26:00.780397    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.18.0 <1.27.0
I0502 10:26:00.780401    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.32.0
I0502 10:26:00.780416    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.4.0 <1.5.0
I0502 10:26:00.780419    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.5.0 <1.6.0
I0502 10:26:00.780422    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.6.0 <1.7.0
I0502 10:26:00.780425    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.7.0 <1.8.0
I0502 10:26:00.780428    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.8.0 <1.9.0
I0502 10:26:00.780431    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.9.0 <1.10.0
I0502 10:26:00.780434    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.10.0 <1.11.0
I0502 10:26:00.780437    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.11.0 <1.12.0
I0502 10:26:00.780440    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.12.0 <1.13.0
I0502 10:26:00.780443    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.13.0 <1.14.0
I0502 10:26:00.780446    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.14.0 <1.15.0
I0502 10:26:00.780449    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.15.0 <1.16.0
I0502 10:26:00.780454    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.16.0 <1.17.0
I0502 10:26:00.780457    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.17.0 <1.18.0
I0502 10:26:00.780460    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.18.0 <1.27.0
I0502 10:26:00.780463    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.32.0
I0502 10:26:00.780466    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.4.0 <1.5.0
I0502 10:26:00.780470    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.5.0 <1.6.0
I0502 10:26:00.780473    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.6.0 <1.7.0
I0502 10:26:00.780476    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.7.0 <1.8.0
I0502 10:26:00.780479    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.8.0 <1.9.0
I0502 10:26:00.780481    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.9.0 <1.10.0
I0502 10:26:00.780484    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.10.0 <1.11.0
I0502 10:26:00.780487    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.11.0 <1.12.0
I0502 10:26:00.780490    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.12.0 <1.13.0
I0502 10:26:00.780494    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.13.0 <1.14.0
I0502 10:26:00.780497    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.14.0 <1.15.0
I0502 10:26:00.780500    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.15.0 <1.16.0
I0502 10:26:00.780512    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.16.0 <1.17.0
I0502 10:26:00.780515    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.17.0 <1.18.0
I0502 10:26:00.780518    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.18.0 <1.27.0
I0502 10:26:00.780522    4445 channel.go:325] Kubernetes version "1.30.11" does not match range: >=1.32.0

No upgrade required

```

**9. Anything else do we need to know?**

Since kops 1.5 or so i've updated clusters just like above. The kops version always matched the main kubernetes version. Is there a change in documentation about how to upgrade k8s major version that i've missed? The new `reconcile` command is for update/rolling-update cluster after upgrade - so not related here nor mandatory at all?
