### ISSUE TITLE
Hetzner taint - invalid input in field 'labels'

### ISSUE THREAD

**Issue by lsimeonov** [kubernetes/kops#17425]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.32.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.31.8

**3. What cloud provider are you using?**
Hetzner

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create an ig and add a simple taint
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster
  name: connection-service-node
spec:
  image: debian-12
  nodeLabels:
    kops.k8s.io/instancegroup: connection-service-node
    test.io/type: connection-service
  machineType: ccx23
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
    - nbg1
  taints:
    - dedicated=special:NoSchedule

```

**5. What happened after the commands executed?**
error running task "ServerGroup/connection-service-node" (9m48s remaining to succeed): invalid input in field 'labels' (invalid_input, 6407a1669d0e334b)

**6. What did you expect to happen?**
The node to be provisioned with tain

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  generation: 1
  name: cluster
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: hetzner
  configBase: do://secrter
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: control-plane-nbg1
      name: etcd-1
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: control-plane-nbg1
      name: etcd-1
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    cloudProvider: external
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
    cloudProvider: external
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.31.8
  networkCIDR: 10.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - name: nbg1
    type: Public
    zone: nbg1
  topology:
    dns:
      type: None

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-05T08:00:07Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: cluster
  name: connection-service-node
spec:
  image: debian-12
  machineType: ccx23
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: connection-service-node
    test.io/type: connection-service
  role: Node
  subnets:
  - nbg1
  taints:
  - dedicated=special:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-03T17:51:24Z"
  labels:
    kops.k8s.io/cluster: cluster
  name: control-plane-nbg1
spec:
  image: debian-12
  machineType: cx32
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - nbg1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-05-17T11:11:46Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster
  name: nodes-nbg1
spec:
  image: debian-12
  machineType: cpx31
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - nbg1

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-04T12:20:45Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cluster
  name: nodes-nbg1-dedicated-medium
spec:
  image: debian-12
  machineType: ccx33
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-nbg1-dedicated-medium
  role: Node
  subnets:
  - nbg1
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```bash
Executing task "ServerGroup/connection-service-node": *hetznertasks.ServerGroup {"Name":"connection-service-node","Lifecycle":"Sync","SSHKeys":[{"Name":"k8s.pricemind.io-7f:5a:2a:d6:51:9f:13:42:b1:88:29:ae:0c:63:9c:a3","Lifecycle":"Sync","ID":29058901,"PublicKey":"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFYxG2yc+X0JLdPAhhOwInFRIDYsOK8jAAX2xQjaNZvO","Labels":{"kops.k8s.io/cluster":"k8s.pricemind.io"}}],"Network":{"Name":"k8s.pricemind.io","Lifecycle":"Sync","ID":"11025805","Region":"eu-central","IPRange":"10.20.0.0/16","Subnets":["10.20.0.0/16"],"Labels":{"kops.k8s.io/cluster":"k8s.pricemind.io"}},"Count":1,"NeedUpdate":null,"Location":"nbg1","Size":"ccx23","Image":"debian-12","EnableIPv4":true,"EnableIPv6":false,"UserData":{"resource":{},"task":{"Name":"connection-service-node","Lifecycle":"Sync"}},"Labels":{"k8s.io/cluster-autoscaler/node-template/taint/dedicated":"special:NoSchedule","kops.k8s.io/cluster":"k8s.pricemind.io","kops.k8s.io/instance-group":"connection-service-node","kops.k8s.io/instance-role":"Node","kops.k8s.io/instance-userdata":"sha256.HwgzCchYC5n_BAZU8jQR_3ttoYv8U5L4Sp09zZ4AvG8","node-label.kops.k8s.io.kops.k8s.io/instancegroup":"connection-service-node","node-label.kops.k8s.io.node-role.kubernetes.io/node":"","node-label.kops.k8s.io.pricemind.io/type":"connection-service"}}
W0605 11:09:27.676716   76563 executor.go:141] error running task "ServerGroup/connection-service-node" (9m28s remaining to succeed): invalid input in field 'labels' (invalid_input, feced32e3ede4377)
```

**9. Anything else do we need to know?**
