### ISSUE TITLE
missing permissions on calico version 3.29.2

### ISSUE THREAD

**Issue by shugotek** [kubernetes/kops#17424]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Client version: 1.32.0 (git-v1.32.0)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: v1.32.5
Kustomize Version: v5.5.0
Server Version: v1.32.5
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`cat kube-apiserver-audit.log`

**5. What happened after the commands executed?**
warning log 
```
kubecontrollersconfigurations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot list resource "kubecontrollersconfigurations" in API group "crd.projectcalico.org" at the cluster scope
```

**6. What did you expect to happen?**
Access allowed and no error in logs

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: REMOVED
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeLaunchTemplateVersions"
          ],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      class: Network
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudControllerManager:
    cloudProvider: aws
  cloudProvider: aws
  configBase: REMOVED
  containerRuntime: containerd
  containerd:
    registryMirrors:
      '*':
      - REMOVED
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: REMOVED
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: REMOVED
      name: a
    memoryRequest: 100Mi
    name: events
  externalPolicies:
    master:
    - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    node:
    - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    - arn:aws:iam::aws:policy/AmazonElasticFileSystemReadOnlyAccess
  fileAssets:
  - content: |
      apiVersion: audit.k8s.io/v1 # This is required.
      kind: Policy
      # Don't generate audit events for all requests in RequestReceived stage.
      omitStages:
        - "RequestReceived"
      rules:
        # Log pod changes at RequestResponse level
        - level: RequestResponse
          resources:
          - group: ""
            # Resource "pods" doesn't match requests to any subresource of pods,
            # which is consistent with the RBAC policy.
            resources: ["pods"]
        # Log "pods/log", "pods/status" at Metadata level
        - level: Metadata
          resources:
          - group: ""
            resources: ["pods/log", "pods/status"]

        # Don't log requests to a configmap called "controller-leader"
        - level: None
          resources:
          - group: ""
            resources: ["configmaps"]
            resourceNames: ["controller-leader"]

        # Don't log watch requests by the "system:kube-proxy" on endpoints or services
        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
          - group: "" # core API group
            resources: ["endpoints", "services"]

        # Don't log authenticated requests to certain non-resource URL paths.
        - level: None
          userGroups: ["system:authenticated"]
          nonResourceURLs:
          - "/api*" # Wildcard matching.
          - "/version"

        # Log the request body of configmap changes in kube-system.
        - level: Request
          resources:
          - group: "" # core API group
            resources: ["configmaps"]
          # This rule only applies to resources in the "kube-system" namespace.
          # The empty string "" can be used to select non-namespaced resources.
          namespaces: ["kube-system"]

        # Log configmap and secret changes in all other namespaces at the Metadata level.
        - level: Metadata
          resources:
          - group: "" # core API group
            resources: ["secrets", "configmaps"]

        # Log all other resources in core and extensions at the Request level.
        - level: Request
          resources:
          - group: "" # core API group
          - group: "extensions" # Version of group should NOT be included.

        # A catch-all rule to log all other requests at the Metadata level.
        - level: Metadata
          # Long-running requests like watches that fall under this rule will not
          # generate an audit event in RequestReceived.
          omitStages:
            - "RequestReceived"
    name: apiserver-audit-policy
    path: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    roles:
    - ControlPlane
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/kube-apiserver/audit-policy-config.yaml
    cloudProvider: external
    eventTTL: 23h59m59s
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    cloudProvider: external
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.32.5
  masterPublicName: REMOVED
  networkCIDR: REMOVED
  networkID: REMOVED
  networking:
    calico:
      awsSrcDstCheck: Disable
      encapsulationMode: ipip
      mtu: 8981
      typhaReplicas: 3
      wireguardEnabled: true
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: REMOVED
    enableAWSOIDCProvider: true
  subnets:
  - cidr: REMOVED
    id: REMOVED
    name: REMOVED
    type: Private
    zone: REMOVED
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:29Z"
  labels:
    kops.k8s.io/cluster: REMOVED
  name: REMOVED
spec:
  associatePublicIp: false
  cloudLabels:
    arch: amd64
    env: REMOVED
    environment: REMOVED
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/name/REMOVED: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/REMOVED: ""
    k8s.io/cluster/REMOVED: owned
    managed-by: kops
    owner: REMOVED
  image: REMOVED
  machineType: c5.xlarge
  maxSize: 20
  minSize: 0
  nodeLabels:
    env: REMOVED
    kops.k8s.io/instancegroup: REMOVED
  role: Node
  rootVolumeEncryption: true
  rootVolumeSize: 50
  subnets:
  - REMOVED
  taints:
  - dedicated=REMOVED:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:29Z"
  labels:
    kops.k8s.io/cluster: REMOVED
  name: REMOVED
spec:
  associatePublicIp: false
  cloudLabels:
    arch: amd64
    env: REMOVED
    environment: REMOVED
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/name/REMOVED: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/REMOVED: ""
    k8s.io/cluster/REMOVED: owned
    managed-by: kops
    owner: REMOVED
  image: REMOVED
  machineType: t3.small
  maxSize: 10
  minSize: 0
  nodeLabels:
    env: REMOVED
    kops.k8s.io/instancegroup: REMOVED
  role: Node
  rootVolumeEncryption: true
  rootVolumeSize: 50
  subnets:
  - REMOVED
  taints:
  - dedicated=REMOVED:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:29Z"
  labels:
    kops.k8s.io/cluster: REMOVED
  name: REMOVED
spec:
  associatePublicIp: false
  cloudLabels:
    arch: amd64
    env: REMOVED
    environment: REMOVED
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/name/REMOVED: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/REMOVED: ""
    k8s.io/cluster/REMOVED: owned
    managed-by: kops
    owner: REMOVED
  image: REMOVED
  instanceMetadata:
    httpPutResponseHopLimit: 2
  machineType: c6i.xlarge
  maxPrice: "0.10"
  maxSize: 3
  minSize: 0
  mixedInstancesPolicy:
    instances:
    - c6i.xlarge
    - m5.xlarge
    - m6i.xlarge
    - c6in.xlarge
    - c5d.xlarge
    - c5.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: lowest-price
    spotInstancePools: 2
  nodeLabels:
    env: REMOVED
    kops.k8s.io/instancegroup: REMOVED
  role: Node
  rootVolumeEncryption: true
  rootVolumeSize: 50
  subnets:
  - REMOVED
  taints:
  - dedicated=REMOVED:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:29Z"
  labels:
    kops.k8s.io/cluster: REMOVED
  name: REMOVED
spec:
  associatePublicIp: false
  cloudLabels:
    arch: arm64
    env: REMOVED
    environment: REMOVED
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/name/REMOVED: ""
    k8s.io/cluster-autoscaler/node-template/label: REMOVED
    k8s.io/cluster-autoscaler/REMOVED: ""
    k8s.io/cluster/REMOVED: owned
    managed-by: kops
    owner: REMOVED
    usage: k8s
    version: v2
  externalLoadBalancers:
  - targetGroupArn: REMOVED
  image: REMOVED
  machineType: t4g.small
  maxSize: 4
  minSize: 2
  nodeLabels:
    env: REMOVED
    kops.k8s.io/instancegroup: REMOVED
  role: Node
  rootVolumeEncryption: true
  rootVolumeSize: 15
  subnets:
  - REMOVED
  taints:
  - dedicated=REMOVED:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:29Z"
  labels:
    kops.k8s.io/cluster: REMOVED
  name: master-REMOVED
spec:
  associatePublicIp: false
  cloudLabels:
    arch: arm64
    env: REMOVED
    environment: REMOVED
    managed-by: kops
    owner: REMOVED
    usage: k8s
    version: v2
  image: REMOVED
  machineType: t4g.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-REMOVED
  role: Master
  rootVolumeEncryption: true
  rootVolumeSize: 20
  subnets:
  - REMOVED

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:29Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: REMOVED
  name: nodes
spec:
  associatePublicIp: false
  cloudLabels:
    arch: amd64
    env: REMOVED
    environment: REMOVED
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/name/consumer: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/REMOVED: ""
    k8s.io/cluster/REMOVED: owned
    managed-by: kops
    usage: k8s
    version: v2
  image: REMOVED
  instanceMetadata:
    httpPutResponseHopLimit: 2
  machineType: t3.medium
  maxSize: 4
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeEncryption: true
  rootVolumeSize: 20
  subnets:
  - REMOVED

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-02T16:03:30Z"
  labels:
    kops.k8s.io/cluster: REMOVED
  name: REMOVED
spec:
  associatePublicIp: false
  cloudLabels:
    arch: amd64
    env: REMOVED
    environment: REMOVED
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/name/REMOVED: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/REMOVED: ""
    k8s.io/cluster/REMOVED: owned
    managed-by: kops
    owner: REMOVED
    usage: k8s
    version: v2
  image: REMOVED
  machineType: t3.medium
  maxSize: 2
  minSize: 1
  nodeLabels:
    env: REMOVED
    kops.k8s.io/instancegroup: REMOVED
  role: Node
  rootVolumeEncryption: true
  rootVolumeSize: 20
  subnets:
  - REMOVED
  taints:
  - dedicated=REMOVED:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Bug is related to calico version 3.29.2 and is corrected in version 3.29.3.
There is just a missing `list` permission for clusterRole `calico-kube-controllers` on resource `kubecontrollersconfigurations` for apiGroup `crd.projectcalico.org`
[https://github.com/projectcalico/calico/issues/10073](url)
[https://github.com/projectcalico/calico/commit/d6dbb99da274cc1253fa979008e266ff0dbf407b](url)

For those who want to fix, you can just add this missing permission manually on the cluster role.
