### ISSUE TITLE
Invalid default master node image for ap-northeast-1

### ISSUE THREAD

**Issue by 23navi** [kubernetes/kops#17440]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Client version: 1.32.0 (git-v1.32.0)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.32.4

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops create cluster \
    --name=${NAME} \
    --cloud=aws \
    --zones=ap-northeast-1a,ap-northeast-1c,ap-northeast-1d

**5. What happened after the commands executed?**

I get an error:

```
Error: control-plane-ap-northeast-1a.spec.image: Invalid value: "099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250502.1": specified image "099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250502.1" is invalid: could not find Image for "099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20250502.1"
```

**6. What did you expect to happen?**

I expect for configuration to be created without any error

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
W0616 17:28:42.087988  963499 get.go:78] `kops get [CLUSTER]` is deprecated: use `kops get all [CLUSTER]`
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2025-06-16T17:10:25Z"
  name: myfirstcluster.k8s.local
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://23navi-kops-bootstrap-configuration-bucket/myfirstcluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-northeast-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.32.4
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.0.0/18
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 172.20.64.0/18
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 172.20.128.0/18
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: None

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-16T17:10:25Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: myfirstcluster.k8s.local
  name: control-plane-ap-northeast-1a
spec:
  image: ami-054400ced365b82a0
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-16T17:10:25Z"
  labels:
    kops.k8s.io/cluster: myfirstcluster.k8s.local
  name: nodes-ap-northeast-1a
spec:
  image: ami-054400ced365b82a0
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-16T17:10:25Z"
  labels:
    kops.k8s.io/cluster: myfirstcluster.k8s.local
  name: nodes-ap-northeast-1c
spec:
  image: ami-054400ced365b82a0
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2025-06-16T17:10:25Z"
  labels:
    kops.k8s.io/cluster: myfirstcluster.k8s.local
  name: nodes-ap-northeast-1d
spec:
  image: ami-054400ced365b82a0
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - ap-northeast-1d
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
NO
