### ISSUE TITLE
Can't update API version in 1.5.1

### ISSUE THREAD

**Issue by zfy0701** [kubernetes/kops#1834]
upgraded from 1.4.4
follow the instruction here to update API setting:

```
 kubeAPIServer:
    runtimeConfig:
      apps/v1alpha1: "true"
      batch/v2alpha1: "true"
```
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#runtimeconfig

doing kops update cluster, it doesn't show any change related to API server
doing kops edit cluster, it doesn't show any changes I made before
 and after a rolling update, API server seems not picked up the new changes
