### ISSUE TITLE
Add option to increase the ELB idle timeout for apiserver 

### ISSUE THREAD

**Issue by zacblazic** [kubernetes/kops#1883]
When using `kubectl` to perform an `exec` or `logs -f`, you may have noticed that if you aren't interacting with the terminal, or logs are just silent for extended periods, that the connection will just drop. 

This is due to the short ELB idle timeout of the apiserver that is set to 60 seconds by default.

It would be great if we could have an option in the cluster spec to increase the value of the timeout, in addition to bumping the default up to 300 seconds.

Below is the proposed `cluster.spec` change:
```yaml
spec:
  api:
    loadBalancer:
      type: Public
      idleTimeoutSeconds: 600 # I'd like it a bit longer than the default
```
