### ISSUE TITLE
kops update for subnet with existing nat gateway fails

### ISSUE THREAD

**Issue by smelchior** [kubernetes/kops#1890]
I was trying to create a terraform output for our existing AWS VPC / Subnet / Natgateway setup with Kops 1.5.1. As stated in the documentation i created a section in the config with:
```
  networkCIDR: 10.220.0.0/16
  networkID: vpc-BLABLABLA
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - cidr: 10.220.32.0/19
    name: eu-central-1a
    egress: nat-BLABLABLA
    type: Private
    zone: eu-central-1a
  - cidr: 10.220.64.0/19
    name: eu-central-1b
    egress: nat-BLABLABLA
    type: Private
    zone: eu-central-1b
  - cidr: 10.220.254.0/24
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 10.220.255.0/24
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
```
when running:
`kops update cluster   --name=mycluster.xyz   --out=out   --target=terraform`
i get:
`executor.go:109] error running task "NatGateway/eu-central-1a.i-cluster.etrusted.io" (9m59s remaining to succeed): Field is required: ElasticIp`

Am i missing something in my conf?
