### ISSUE TITLE
additionalPolicies broken?

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1920]
kops version: 1.5.1
k8s version: 1.5.2
This policy looks correct according to: https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md

```yaml  
additionalPolicies:
    node: |
      [
        {
          "Action": [ "sts:AssumeRole" ],
          "Resource": "*",
          "Effect": "Allow"
        }
      ]
```

But I get this error during update:
`error creating/updating IAMRolePolicy: MalformedPolicyDocument: Syntax errors in policy.`

It changes `node: |` to `node: |+` when edit saves the spec, I'm not sure if that's related.
