### ISSUE TITLE
Should --cluster-dns be used for resolver on master nodes?

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1954]
We ran into an issue where we specified an in-cluster name for one of our apiserver startup options:

```yaml
spec:
  kubeAPIServer:
    oidcCAFile: /srv/kubernetes/ca.crt
    oidcClientID: kubernetes
    oidcIssuerURL: https://dex.security.svc.stage.us-west-2.aws.k8s:5556
```

Auth was failing mysteriously but not when talking to Dex.  Turned out all the pods on the master nodes have the default DHCP provided resolver from AWS instead of the `--cluster-dns` specified one.  I'm not certain if this is a bug or should be considered a feature request.  If there's no downside to using the kube-dns resolver, that would be ideal so that all pods in the cluster can use the same names.
