### ISSUE TITLE
Adding cluster kubelet settings changes actual config

### ISSUE THREAD

**Issue by alex88** [kubernetes/kops#1956]
I wanted to set the `terminatedPodGCThreshold`, after looking at https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/cluster.go and https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go I thought I had to add

```
kubelet:
  terminatedPodGCThreshold: 1500
```

which instead was refusing to save the config with error `Kubelet NonMasqueradeCIDR did not match cluster NonMasqueradeCIDR
So I tried to copy that value from `kops get cluster -o yaml --full`, adding `nonMasqueradeCIDR: 100.64.0.0/10` to the config, after saving the config became:

```
kubelet:
  evictionPressureTransitionPeriod: 0s
  networkPluginMTU: null
  nonMasqueradeCIDR: 100.64.0.0/10
  terminatedPodGCThreshold: 1500
```

while in the original version those values were:

```
kubelet:
  evictionPressureTransitionPeriod: 0s
  networkPluginMTU: 9001
  nonMasqueradeCIDR: 100.64.0.0/10
  terminatedPodGCThreshold: 1500
```

So I think there are 2 issues,

1) I should be able to set only `terminatedPodGCThreshold`
2) if it adds values to the config, they should be what the actual cluster state is
