### ISSUE TITLE
kops cluster with RBAC enabled is failing

### ISSUE THREAD

**Issue by kumudt** [kubernetes/kops#1960]
I created a kubernetes cluster (v1.5.3) with a master and 3 nodes using kops v1.5.1 on AWS.
I added the following additional config to support RBAC (Before doing kops update cluster --yes).

`kubeAPIServer:
    authorizationMode: RBAC,AlwaysAllow
    authorizationRbacSuperUser: admin
    runtimeConfig:
      rbac.authorization.k8s.io/v1alpha1: "true"`

Cluster was working fine. I added necessary serviceaccounts, clusterroles, clusterrolebindings etc..
Now, I removed "AlwaysAllow" string from the authorizationMode in the kops config file and tried to do update / rolling-update. Nothing happened (I think kops hasn't added that feature to detect these changes). So, I tried doing the force rolling update (using --force) and then all the master / nodes were recreated and the serviceaccounts are working as expected (I guess). But the nodes are not bound to the cluster anymore. (When I did `kubectl get nodes -o wide` only the master was getting displayed. But I can see all 3 nodes in the nodes autoscaling group). I thought this force rolling update broke the cluster networking so I tried creating a fresh cluster, this time directly with RBAC (with out AlwaysAllow) and I faced the same issue with the nodes. Only master was accessible using 'kubectl'.

I also tried editing the instance groups for increasing / decreasing the node count and the issue still remained. Autoscaling group is adding / removing the instances but none of them were accessible using kubectl.

I just want to know whether this behavior is expected (is this going to be fixed in the future versions?). If not (If I am doing something wrong), what is the best way to enable RBAC on a cluster installed with kops.

**Comment by chrislovecnm** [comment]
@sethpollack any ideas?

**Comment by sethpollack** [comment]
What do the clusterroles/clusterrolebindings look like?

**Comment by kumudt** [comment]
I created a new client 'admin' in system:masters group and used these client certificates for accessing the cluster after re-creating all the master & node instances (via kops --force).
Along with that I also added the following cluster role and role binding so that the kubernetes dashboard won't break (which anyway didn't work as the nodes themselves are not bound to the cluster).

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: na-ca-role
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- attributeRestrictions: null
  nonResourceURLs:
  - '*'
  verbs:
  - '*'

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: na-ca-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: na-ca-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: User
  name: admin
- kind: Group
  name: admin

```

**Comment by sethpollack** [comment]
In kubernetes 1.6 RBAC is moving to beta, will have [default roles/bindings](http://kubernetes-io-vnext-staging.netlify.com/docs/admin/authorization/rbac/#default-clusterroles-and-clusterrolebindings), and will start each controller with a distinct service account.

For 1.5, the equivalent would be granting cluster-admin to the `kube-controller-manager` user.

I am waiting for 1.6 to fix up my roles, and just added `name: system:authenticated` to cluster-admin for now.

```
- apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: cluster-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: Group
    name: system:masters
  - kind: Group
    name: system:authenticated
```

**Comment by kumudt** [comment]
@sethpollack thanks for the suggestion. But, adding `name: system:authenticated` would give root level access to any client of the cluster right? So, do I have to add `name: system:authenticated` to cluster-admin role even after granting `cluster-admin to the kube-controller-manager user`. (I mean is adding `name: system:authenticated` to cluster-admin compulsory in 1.5 to make RBAC work?)
If not, I am guessing that the nodes are failing because this `kube-controller-manager user` doesn't have `cluster-admin` privileges. Am I right?

**Comment by sethpollack** [comment]
No you don't need to add `name: system:authenticated`, It's probably a bad idea, I just used it as a shortcut for now.

All you should need is the `kube-controller-manager` user.

**Comment by kumudt** [comment]
oh..great thanks. Please don't mind clarifying a small query about this `kube-controller-manager` and some other user called `kubelet` (both in `kube-system` namespace if I am not wrong). What exactly are the roles of these users in the cluster? And, I believe they will be retained in 1.6 as well (Correct me If I am wrong)

**Comment by sethpollack** [comment]
I am not sure.

**Comment by kumudt** [comment]
@sethpollack I gave cluster-admin privilege to `kube-controller-manager` user. Now the nodes are accessible in the cluster. But, I got a couple of issues with my previous deployments `kube-dns` & `kubernetes-dashboard`
```
Kumuds-MacBook-Pro:Kubernetes RBAC kumud$ kubectl get deployments --all-namespaces -o wide
NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   dns-controller            1         1         1            1           5d
kube-system   heapster                  1         1         1            1           5d
kube-system   kube-dns                  2         2         2            0           5d
kube-system   kube-dns-autoscaler       1         1         1            1           5d
kube-system   kubernetes-dashboard      1         1         1            0           5d
```
```
Kumuds-MacBook-Pro:Kubernetes RBAC kumud$ kubectl describe deployment kubernetes-dashboard --namespace=kube-system
Name:			kubernetes-dashboard
Namespace:		kube-system
CreationTimestamp:	Tue, 21 Feb 2017 14:42:42 +0530
Labels:			k8s-addon=kubernetes-dashboard.addons.k8s.io
			k8s-app=kubernetes-dashboard
			kubernetes.io/cluster-service=true
			version=v1.5.0
Selector:		k8s-app=kubernetes-dashboard
Replicas:		1 updated | 1 total | 0 available | 1 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	<none>
NewReplicaSet:	kubernetes-dashboard-2465510325 (1/1 replicas created)
No events.

```
```
Kumuds-MacBook-Pro:Kubernetes RBAC kumud$ kubectl describe deployment kube-dns --namespace=kube-system
Name:			kube-dns
Namespace:		kube-system
CreationTimestamp:	Tue, 21 Feb 2017 14:40:23 +0530
Labels:			k8s-addon=kube-dns.addons.k8s.io
			k8s-app=kube-dns
			kubernetes.io/cluster-service=true
Selector:		k8s-app=kube-dns
Replicas:		2 updated | 2 total | 0 available | 2 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	0 max unavailable, 10% max surge
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	False	MinimumReplicasUnavailable
OldReplicaSets:	<none>
NewReplicaSet:	kube-dns-782804071 (2/2 replicas created)
No events.
```
What could have gone wrong with these deployments now?

**Comment by sethpollack** [comment]
Not sure.

I usually just kill my master nodes to restart the kubernetes API server.

**Comment by kumudt** [comment]
Could you please refer someone who can help me with this `kube-dns` issue ?

**Comment by sethpollack** [comment]
If its auth related, maybe @liggitt can help?

**Comment by sethpollack** [comment]
thanks!

**Comment by kumudt** [comment]
@liggitt Thanks a lot for the clarification.

But, the service account of `kube-dns` pods has already got `cluster-admin` role. Please check the cluster role binding applied before.
```
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: na-ca-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
```
So, I don't think the issue is because of the permissions. Please let me know if you need any further details. Thanks.

**Comment by kumudt** [comment]
@liggitt @sethpollack @chrislovecnm Thank you all

Adding this fixed all my issues

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: na-ca-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: system:serviceaccounts:kube-system
```

**Comment by liggitt** [comment]
I'd recommend targeting the specific service accounts you want to escalate

**Comment by kumudt** [comment]
@liggitt currently there is only one serviceaccount `default` in the `kube-system` namespace. I escalated that as mentioned in my penultimate comment. But, that didn't fix the `kube-dns` issue.

**Comment by kumudt** [comment]
@liggitt @sethpollack @chrislovecnm 

I modified my ClusterRoleBinding to this and kube-dns is working with this as well. Is this better than my previous version ??

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: na-ca-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: system:serviceaccount:kube-system:default
- kind: User
  name: kubelet
- kind: User
  name: kube-apiserver
- kind: User
  name: kube-controller-manager
- kind: User
  name: kube-proxy
- kind: User
  name: kube-scheduler
```
