### ISSUE TITLE
Choose which subnets are attached to the API ELB. 

### ISSUE THREAD

**Issue by podon** [kubernetes/kops#2149]
We follow a VPC model where all of our servers are private and endpoints are exposed via an ELB in separate subnets. We'd love the ability to attach _**only**_ the utility subnets to the API ELB, while the masters are located in the private subnet. 

Our cluster configuration is as follow. 

```
spec:
  api:
    loadBalancer:
      type: Internal
...
...
 subnets:
  - cidr:xxx.xxx.xxx.xxx/xx
    egress: nat-yyyyyyyyyy
    id: subnet-xxxxxxxxxx
    name: ap-southeast-2a
    type: Private
    zone: ap-southeast-2a
  - cidr: xxx.xxx.xxx.xxx/xx
    egress: nat-zzzzzzzzzzz
    id: subnet-xxxxxxxxxx
    name: ap-southeast-2b
    type: Private
    zone: ap-southeast-2b
  - cidr: xxx.xxx.xxx.xxx/xx
    id: subnet-xxxxxxxxxx
    name: utility-ap-southeast-2a
    type: Utility
    zone: ap-southeast-2a
  - cidr: xxx.xxx.xxx.xxx/xx
    id: subnet-xxxxxxxxxx
    name: utility-ap-southeast-2b
    type: Utility
    zone: ap-southeast-2b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

Cheers!
