### ISSUE TITLE
rootVolumeSize and rootVolumeType when target is terraform

### ISSUE THREAD

**Issue by shamil** [kubernetes/kops#2185]
Hi,

I've tried to increase volume size on the nodes IG, but nothing happens when targeting Terraform. 
Am I doing something wrong? kops `1.5.3`, kubernetes `1.5.4`

Here is my IG manifest

```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2017-03-08T13:59:10Z"
  labels:
    kops.k8s.io/cluster: qa.k8s.test.com
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a
```
