### ISSUE TITLE
One EC2 tag to differentiate roles

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kops#2209]
We use DataDog to monitor our Kubernetes clusters. DataDog (like many other systems) automatically tags data with EC2 tags. This makes it easy to facet telemetry data from masters and workers. Unfortunately this does not work as smoothly as it could because `kops` uses unique tags for all roles (`k8s.io/role/master`, `k8s.io/role/worker`, `k8s.io/role/bastion`). I propose that `kops` adds a new tag `k8s.io/role` (name is irrelevant) and sets the value accordingly. The old tags should be kept for backwards compat. The end result would be:

* masters nodes are tagged with: `k8s.io/role/master=1` and `k8s.io/role=master`
* workers nodes are tagged with `k8s.io/role/worker=1` and `k8s.io/role=worker`
* bastion instances are tagged with `k8s.io/role/bastion=1` and `k8s.io/role=bastion`

This way a metric such as "cpu load" can be easily faceted across masters and workers (which have much different workloads in the real world).

**Comment by tiadobatima** [comment]
Unless I'm misunderstanding the use-case, I think you should be able to add any extra tags you want to a specific instance group by using "CloudLabels" in your yaml file (not sure if you can do that with the CLI).

Something like:
```
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
  labels:
    kops.k8s.io/cluster: my.k8s.com
spec:
  associatePublicIp: true
  cloudLabels:
    k8s.io/role: node
    mytag: blabla
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - subnet-us-west-2a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: master-us-west-2a
  labels:
    kops.k8s.io/cluster: my.k8s.com
spec:
  cloudLabels:
    k8s.io/role: master
    mytag: blabla
  associatePublicIp: true
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - subnet-us-west-2a
```
