### ISSUE TITLE
`kops replace -f` doesnt affect the entire specified config

### ISSUE THREAD

**Issue by captainkerk** [kubernetes/kops#2243]
using: Kops Version 1.5.3

Hello! I think I found a bug with the replace command.

I have a yaml file containing a cluster definition as well as a few instance group definitions. I was able to use this file in the create operation successfully, but the `replace` command seems to only care about the first document in the yaml file. Here's an example of my config (i removed a few pieces for brevity):

```
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: a-valid-value
spec:
  [...]
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
# Master Instance Group
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: a-valid-value
  name: master-us-east-1a
spec:
  [...]
  subnets:
  - us-east-1a
---
# Node instance group
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: a-valid-value
  name: nodes
spec:
  [...]
  subnets:
  - us-east-1a
```

In my case, `kops replace -f filename.yaml` only updates the first document specified (in this case the cluster). I removed the cluster document from the file (making the master instance group the first document in the file) and reran the replace operation. It then replaced the master instance group's config, but still did not touch the node document. 

It seems like the replace command only cares about the first document in the yaml file. 

Am I wrong in concatenating these documents together? Should they live in separate yaml files? If not, this behavior I'm experiencing seems like a bug.
