### ISSUE TITLE
featuresGates in cluster spec do not show up on kubelets  

### ISSUE THREAD

**Issue by anurag** [kubernetes/kops#2293]
This is related to commit 184896aae149cbec5a831080b84056ed5e850b68. After building `kops` from `master`, I added the following to the cluster spec:
```
  kubernetesVersion: 1.6.1
  masterKubelet:
    featureGates:
      Accelerators: "true"
  kubelet:
    featureGates:
      Accelerators: "true"
```
Created the cluster with `update cluster --yes`. Logged into the node and the master to inspect `kubelet` runtime arguments with `ps aux` and expected to see '--feature-flags' as one of the args but didn't.

cc @chrislovecnm

**Comment by chrislovecnm** [comment]
looking at this now

**Comment by chrislovecnm** [comment]
Just spun up a cluster and it seems to be happy.

```
/usr/local/bin/kubelet --allow-privileged=true --babysit-daemons=true --cgroup-root=/ --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --feature-gates=Accelerators=true,ExperimentalCriticalPodAnnotation=true --hostname-override=ip-172-20-89-193.eu-west-1.compute.internal --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --node-labels=kubernetes.io/role=master,node-role.kubernetes.io/master= --non-masquerade-cidr=100.64.0.0/10 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=true --register-with-taints=node-role.kubernetes.io/master=:NoSchedule --require-kubeconfig=true --v=2 --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/
```

Let me just try one, but it should not matter.

**Comment by anurag** [comment]
Interesting. Mind sharing your cluster and ig specs?

**Comment by chrislovecnm** [comment]
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-06T19:38:15Z
  name: some.cluster
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: alpha
  cloudProvider: aws
  configBase: s3://bucket/some.cluster
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  kubelet:
    featureGates:
      ExperimentalCriticalPodAnnotation: "true"
      Accelerators: "true"
  masterKubelet:
    featureGates:
      ExperimentalCriticalPodAnnotation: "true"
      Accelerators: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
   kubernetesVersion: 1.6.0
  masterPublicName: some.cluster
  networkCIDR: 172.20.0.0/16
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
# missing subnets and ig
```

Using kops create -f command but that "should" not matter.

```
kops create -f some.cluster.yaml
```
