### ISSUE TITLE
Proposal: Default nodeLabel/cloudLabel for instancegroup name

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#2301]
In order to allow the external world to interact with the same structures that kops uses, it would be helpful if there was a way to identify members of those structures.

Specifically, there should be a default nodeLabel and cloudLabel for instance groups that have the name of the instancegroup in there.  I propose the following convention (which is open for debate):

```
nodeLabels:
  kops.kubernetes.io/instancegroup: nodes
cloudLabels:
  kops.kubernetes.io/instancegroup: nodes
```

Similar for HA masters:

```
nodeLabels:
  kops.kubernetes.io/instancegroup: master-us-west-1a-2
cloudLabels:
  kops.kubernetes.io/instancegroup: master-us-west-1a-2
```

This would facilitate kops customers writing tools that need to work with specific instance groups, whether within kubernetes or within AWS.
