### ISSUE TITLE
Exposing Services in Private Topology

### ISSUE THREAD

**Issue by alexanderbez** [kubernetes/kops#2351]
Perhaps this is solely due to my misunderstanding, but with a cluster setup in a single master private topology (with `flannel` as the CNI plugin), a `Service` with `type: NodePort` should be exposed via the API URL, correct?

e.g.
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: k8s
```

Shouldn't I be able to reach my service at `https://api.<cluster-name>.com:9090`? Is there a way I can expose this service via the API behind the ELB? Or do I need to use a `LoadBalancer` type or even an `Ingress` controller? Is there a more preferred method in the way kops sets up the cluster?

Thanks!
