### ISSUE TITLE
kops replace -f only replace the first item in the file

### ISSUE THREAD

**Issue by kenden** [kubernetes/kops#2430]
If we have several elements in the kops config file, separated by lines:
```
---
```
, then only the first element is replaced when running `kops replace -f`

## Repro steps

- Create a cluster configuration with:
```
kops create cluster \
	  --cloud aws \
	  --master-zones eu-west-1a,eu-west-1b,eu-west-1c \
	  --zones eu-west-1a,eu-west-1b,eu-west-1c \
	  --name "k8s.prod.redacted.com" \
	  --master-size t2.medium \
	  --node-size t2.medium \
	  --cloud-labels "Stack=K8s-prod" \
	  --networking calico \
	  --target cloudformation \
	  --state s3://k8s/kops/ \
	  --dns-zone=redacted.net \
	  --topology private
```
(This steps is to create certificates and keys, there is currently no way to create them with kops otherwise, except for the admin user ssh key)

- Replace the cluster config created with your own pre-made config 
(which has a policy, using existing VPC,  Subnets...)
  * Create file `config.yaml` with the content:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2017-04-05T20:51:06Z"
  name: k8s.prod.redacted.com
spec:
  additionalPolicies:
    node: |+
      [
              {
                  "Effect": "Allow",
                  "Action": [
                      "autoscaling:DescribeAutoScalingGroups",
                      "autoscaling:DescribeAutoScalingInstances",
                      "autoscaling:SetDesiredCapacity",
                      "autoscaling:TerminateInstanceInAutoScalingGroup"
                  ],
                  "Resource": "*"
              }
          ]
  api:
    loadBalancer:
      type: Public
  channel: stable
  cloudLabels:
    Stack: K8s-prod
  cloudProvider: aws
  configBase: s3://k8s/kops//k8s.prod.redacted.com
  dnsZone: redacted.net
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.5.2
  masterPublicName: api.k8s.prod.redacted.com
  networkCIDR: 172.20.0.0/16
  networkID: vpc-ef75138a
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 172.16.0.0/16
  - 172.19.0.128/32
  - 172.20.0.0/16
  subnets:
  - id: subnet-fb03f59c
    name: private.prod.eu-west-1a
    type: Private
    zone: eu-west-1a
  - id: subnet-35e5167c
    name: private.prod.eu-west-1b
    type: Private
    zone: eu-west-1b
  - id: subnet-7303312b
    name: private.prod.eu-west-1c
    type: Private
    zone: eu-west-1c
  - id: subnet-6200f605
    name: public.prod.eu-west-1a
    type: Public
    zone: eu-west-1a
  - id: subnet-13eb185a
    name: public.prod.eu-west-1b
    type: Public
    zone: eu-west-1b
  - id: subnet-e30032bb
    name: public.prod.eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2017-04-05T20:51:06Z"
  labels:
    kops.k8s.io/cluster: k8s.prod.redacted.com
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private.prod.eu-west-1a


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2017-04-05T20:51:06Z"
  labels:
    kops.k8s.io/cluster: k8s.prod.redacted.com
  name: master-eu-west-1b
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private.prod.eu-west-1b


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2017-04-05T20:51:06Z"
  labels:
    kops.k8s.io/cluster: k8s.prod.redacted.com
  name: master-eu-west-1c
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - private.prod.eu-west-1c


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2017-04-05T20:51:06Z"
  labels:
    kops.k8s.io/cluster: k8s.prod.redacted.com
  name: nodes
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - private.prod.eu-west-1a
  - private.prod.eu-west-1b
  - private.prod.eu-west-1c
```
  * Run command to replace cluster and InstanceGroups config files

```
$ kops replace -f config.yaml --state s3://k8s/kops/ --name "k8s.prod.redacted.com" -v 10
I0425 18:42:16.757418   42209 s3context.go:114] Found bucket "k8s" in region "eu-west-1"
I0425 18:42:16.757477   42209 s3fs.go:162] Reading file "s3://k8s/kops/k8s.prod.redacted.com/config"
I0425 18:42:17.076579   42209 s3fs.go:110] Writing file "s3://k8s/kops/k8s.prod.redacted.com/config"
```
---> See the files in `s3://k8s/kops/k8s.prod.redacted.com/instancegroup/`, which define the instance groups, didn't get updated. Only the first element in the file got updated

**Comment by kenden** [comment]
## Workaround

Split config.yaml into several files, one per object
```
$ tree kops_conf
kops_conf
├── cluster.yaml
└── instancegroups
    ├── ig-master-a.yaml
    ├── ig-master-b.yaml
    ├── ig-master-c.yaml
    └── ig-nodes.yaml
```
Then process those files one by one, starting with the cluster conf.
```
# Update the cluster config with our config file
$ kops replace -f kops_conf/cluster.yaml  -v 10
# Update the instancegroups config files with our config
for ig in kops_conf/instancegroups/*.y*ml; do
  kops replace -f "${ig}" -v 10
done
```

Thanks @blakebarnett, I read this tip from you on the #kops slack channel.

**Comment by kenden** [comment]
instancegroups/*.yaml files depend on specific subnets existing, and those are created from the file cluster.yaml.
That means the kops objects (Cluster, InstanceGroup) have to be created in order.

When kubectl (not kops) creates objects in the wrong order (a Service before a pod, for ex), Kubernetes retries until it works or a healthcheck fails.
But Kops cannot retry, it's not a deamon, it just runs and stops.

## Idea:
- Load all the kops objects from a single yaml file (like the config.yaml example in the description)
- If a Cluster config is present (`kind: Cluster`), try to apply it first.

**Comment by olalonde** [comment]
"kops replace -f only replace the first item in the file " <- wasn't able to reproduce with:

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-17T21:04:16Z
  name: staging.domain.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Environment: staging
  cloudProvider: aws
  configBase: s3://domain-state-store/staging.domain.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: 'true'
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.5.2
  masterPublicName: api.staging.domain.com
  networkID: "vpc-dd775bba" # hardcoded
  networkCIDR: "172.20.0.0/16" # hardcoded
  networking:
    kubenet: {}
    # weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-west-2a
    type: Public
    zone: us-west-2a
    id: "subnet-ee94ec89"
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-17T21:04:16Z
  labels:
    kops.k8s.io/cluster: staging.domain.com
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-17T21:04:17Z
  labels:
    kops.k8s.io/cluster: staging.domain.com
  name: nodes
spec:
  additionalSecurityGroups:
  - "sg-36822b4d"
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-west-2a
```
