### ISSUE TITLE
Changing network topology from private to public

### ISSUE THREAD

**Issue by sanjitsaluja** [kubernetes/kops#2432]
Is it possible to change the network topology from private to public using kops? I'm using AWS as the provider.

**Comment by kenden** [comment]
If you edit the cluster config:
```
$ kops edit cluster --name your.clustername.net  --state s3://k8s/kops/
```
And change the topology:
```
topology:
    dns:
      type: Public
```
Then
`$ kops update  cluster --name your.clustername.net  --state s3://k8s/kops/`
Does it work?

**Comment by sanjitsaluja** [comment]
No. It complains and rejects the update saying it was an invalid update.

**Comment by geojaz** [comment]
To just move from what we consider "base private topology" to "base public toplogy", I think you need to edit 

```
 topology:
    dns:
      type: (could be either Public or Private, I think)
    masters: private
    nodes: private
```

to 
```
 topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

You may still end up with a load balancer pointed at the APIserver, but I'm not sure. I've done more work going the other way, from public=>private :)
