### ISSUE TITLE
Master doesn't list nodes after rolling update

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2446]
Here's what I did... I tried to enable `batch/v2alpha1` so added it here:

```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-17T21:04:16Z
  labels:
    kops.k8s.io/cluster: staging.mydomain.com
  name: master-us-west-2a
spec:
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a
```

```bash
kops replace -f file.yaml --name mycluster
kops update cluster --name mycluster --yes
kops rolling-update cluster --name mycluster  --yes
```

After the rolling update, I am no longer able to use `kubectl` because the `api.mydomain.com` entry hasn't been updated to point to the new master's IP. Additionally, when I ssh to the new master and do `kubectl get nodes`, it is only listing the master.

```
$ kubectl get nodes
NAME                                          STATUS         AGE
ip-172-20-56-211.us-west-2.compute.internal   Ready,master   25m
```

Here are my state files for reference:

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-17T21:04:16Z
  name: staging.mydomain.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Environment: staging
  cloudProvider: aws
  configBase: s3://mydomain-state-store/staging.mydomain.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.5.2
  masterPublicName: api.staging.mydomain.com
  networkID: ${NETWORK_ID} # hardcoded
  networkCIDR: ${NETWORK_CIDR} # hardcoded
  networking:
    weave: {}
  # networking:
    # kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-west-2a
    type: Public
    zone: us-west-2a
    id: ${SUBNET_ID_1}
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-17T21:04:16Z
  labels:
    kops.k8s.io/cluster: staging.mydomain.com
  name: master-us-west-2a
spec:
  #additionalSecurityGroups:
  #- ${MASTER_SGIDS}
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-17T21:04:17Z
  labels:
    kops.k8s.io/cluster: staging.mydomain.com
  name: nodes
spec:
  additionalSecurityGroups:
  - ${NODES_SGID}
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-west-2a
```
