### ISSUE TITLE
Kops 1.6.0-alpha2 creates an unhealthy AWS ELB

### ISSUE THREAD

**Issue by xrl** [kubernetes/kops#2453]
I am running Kops 1.6.0-alpha2 in eu-central-1 with a hack-y 3 AZ configuration (eu-central-1 only has 2 AZs but I could either use 1 or 3). I am translating over my working us-west-2 kube YAMLs and I am creating this service:

```
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-13T23:06:30Z
  name: mykube.mydomain.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-kops/kops/mykube.mydomain.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.6.1
  masterInternalName: api.internal.mykube.mydomain.com
  masterPublicName: api.mykube.mydomain.com
  networkCIDR: 172.20.0.0/16
  networkID: vpc-89ef61e1
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-13T22:31:36Z
  labels:
    kops.k8s.io/cluster: mykube.mydomain.com
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m4.large
  maxSize: 2
  minSize: 2
  role: Master
  subnets:
  - eu-central-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-13T22:31:36Z
  labels:
    kops.k8s.io/cluster: mykube.mydomain.com
  name: master-eu-central-1b
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m4.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-central-1b
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-13T22:31:36Z
  labels:
    kops.k8s.io/cluster: mykube.mydomain.com
  name: nodes
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: m4.2xlarge
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
```

and then my service configuration:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  selector:
    name: nginx-ingress-controller
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
```

and the ingress controller daemonset it'll use:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  template:
    metadata:
      labels:
        name: nginx-ingress-controller
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:0.8.1
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
```

then when I look at the ELB:

```
$ aws elb describe-load-balancers
{
    "LoadBalancerDescriptions": [
        {
            "Subnets": [
                "subnet-480c4420",
                "subnet-d9a137a3"
            ],
            "CanonicalHostedZoneNameID": "CANONICAL_ID",
            "CanonicalHostedZoneName": "a-uuid.eu-central-1.elb.amazonaws.com",
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 30968,
                        "LoadBalancerPort": 80,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                },
                {
                    "Listener": {
                        "InstancePort": 31998,
                        "LoadBalancerPort": 443,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                }
            ],
            "HealthCheck": {
                "HealthyThreshold": 2,
                "Interval": 10,
                "Target": "TCP:30968",
                "Timeout": 5,
                "UnhealthyThreshold": 6
            },
            "VPCId": "vpc-89ef61e1",
            "BackendServerDescriptions": [],
            "Instances": [
                {
                    "InstanceId": "i-080fde4d6f5108b8d"
                },
                {
                    "InstanceId": "i-088545372ce0519c4"
                },
                {
                    "InstanceId": "i-0edd75d76b4721dd0"
                }
            ],
            "DNSName": "a-uuid.eu-central-1.elb.amazonaws.com",
            "SecurityGroups": [
                "sg-a8e55cc3"
            ],
            "Policies": {
                "LBCookieStickinessPolicies": [],
                "AppCookieStickinessPolicies": [],
                "OtherPolicies": []
            },
            "LoadBalancerName": "ae95429632ae111e7b74d02ef2c64855",
            "CreatedTime": "2017-04-27T00:39:03.760Z",
            "AvailabilityZones": [
                "eu-central-1a",
                "eu-central-1b"
            ],
            "Scheme": "internet-facing",
            "SourceSecurityGroup": {
                "OwnerAlias": "554546661178",
                "GroupName": "k8s-elb-ae95429632ae111e7b74d02ef2c64855"
            }
        }
    ]
}
```

and in the UI all those endpoints are marked as "out of service".
