### ISSUE TITLE
Route53 records not updating after upgrading to 1.6

### ISSUE THREAD

**Issue by sethpollack** [kubernetes/kops#2496]
I had an issue upgrading from 1.5 to 1.6 and had to rebuild my cluster. When the new cluster came up route53 records stopped upgrading and it seems like the old records were still there. I tried deleting the old records but it still wont update them anymore.

Here is an example of how I am setting the records:

```
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    dns.alpha.kubernetes.io/internal: app.example.com
spec:
  type: LoadBalancer
```
