### ISSUE TITLE
Adding authorizationMode to cluster spec doesn't trigger a rolling-update

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#2510]
kops version: 1.6.0-beta.1
k8s version: 1.6.2

relevant change in the spec: 
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  kubeAPIServer:
    authorizationMode: RBAC,AlwaysAllow
```
