### ISSUE TITLE
Incorrect configBase

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2541]
```bash
$ echo $KOPS_STATE_STORE
s3://mydomain-state-store/staging/kops
$ kops create --name staging.mydoma1n.com
$ kops edit cluster --name staging.mydoma1n.com # removed some flags
```

Shows the following file:

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-17T21:04:16Z
  name: staging.mydoma1n.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Environment: staging
  cloudProvider: aws
  configBase: s3://mydoma1n-state-store/staging.mydoma1n.com
# etc.
```

Why is `configBase` pointing to `s3://mydoma1n-state-store/staging.mydoma1n.com` instead of `s3://mydomain-state-store/staging/kops/staging.mydoma1n.com` ?

```
Version 1.6.0-beta.1 (git-77f222d)
```
