### ISSUE TITLE
Allow DNS controller to exclude ingress hosts selectively

### ISSUE THREAD

**Issue by mikelorant** [kubernetes/kops#2548]
**Component**
This issue relates to the use of the kops dns-controller with ingress resources.

**Problem**
When adding a CDN in front of an ingress, there is a need for the ingress component to route the traffic to appropriate service, however the DNS record will be associated with the ingress controller service endpoint instead of the CDN endpoint.

The current implementation of the DNS controller when enabling ingress watching (--watch-ingress=true), assumes all host rules will also require a DNS record and creates the record automatically. When implementing an origin that respects the host header, there will be a conflict for the DNS entry as both the CDN and the ingress will be fighting for the same name.

**Solution**
Some form of exclusion is necessary to allow ingress rules to not create a DNS record. The default case should always be to create the DNS record, but for those that need this solution an annotation could be used to define which hosts should be excluded.

Proposed annotation could be something like **dns.alpha.kubernetes.io/exclude** which would be a string that allows for comma separated host names.

**Example**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: nginx
    dns.alpha.kubernetes.io/exclude: exclude-dns.example.org
spec:
  rules:
  - host: include-dns.example.org
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: 80
  - host: exclude-dns.example.org
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: 80
```
