### ISSUE TITLE
Feature proposal: Move kops assets definitions in EC2 user_data to S3 state

### ISSUE THREAD

**Issue by andreychernih** [kubernetes/kops#2554]
I am trying to create a reusable Terraform module for creating AWS infrastructure for Kubernetes clusters. It is based on Terraform files created by kops. The goal is to use the same module for creating multiple clusters with different names. It works quite well, but Kubernetes version upgrades are slightly complicated - all kops asset versions and SHA hashes are hardcoded in this module which means that I have to update it every time I upgrade Kubernetes version (and I should version my module in the same way kops is versioned). I would like to avoid that because the purpose of Terraform module is to create cloud infrastructure, it should not care about kops/kubernetes version.

My proposal is to move the following assets definitions from EC2 user_data script to S3 bucket where state is located:

```
Assets:
- 57afca200aa6cec74fcc3072cae12385014f59c0@https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubelet
- 984095cd0fe8a8172ab92e2ee0add49dfc46e0c2@https://storage.googleapis.com/kubernetes-release/release/v1.6.2/bin/linux/amd64/kubectl
- 19d49f7b2b99cd2493d5ae0ace896c64e289ccbb@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz
- 93de3635b66b23bb2c838aa699054acd4c578447@https://kubeupv2.s3.amazonaws.com/kops/1.6.0-beta.1/linux/amd64/utils.tar.gz

protokubeImage:
  hash: b444d7d7a6f80540b01a15ca63d22aea6f0edc34
  name: protokube:1.6.0-beta.1
  source: https://kubeupv2.s3.amazonaws.com/kops/1.6.0-beta.1/images/protokube.tar.gz
```

This will make EC2 bootstrap script completely independent from kops / Kubernetes version. Probably, we don't even need to store all these asset definitions on S3, they can be auto-generated by `nodeup` based on the version from cluster spec. The only parameters which should be passed to bootstrap script would be NODEUP_URL, cluster name and S3 bucket where state is stored. Cluster name and S3 bucket will be Terraform module input params, NODEUP_URL can be auto-generated in user_data script by extracting version from cluster spec using `aws-cli` and `grep`.

Please let me know what are your thoughts on this proposal.
