### ISSUE TITLE
Can't create ELB with private subnet cluster

### ISSUE THREAD

**Issue by ashic** [kubernetes/kops#2608]
I created a k8s cluster with kops in an existing VPC with a private topology. kops edit cluster shows:

https://gist.github.com/ashic/e2536d0774ea5fde7e8b7afa98ef7f42

I've created a basic web deployment, and added two services - both LoadBalancers, with one having an annotation to force an internal load balancer. The internal service runs fine, but the public one is failing to start with the following message (which I get by running kubectl describe svc hellopub):

```
CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/hellopub: could not find any suitable subnets for creating the ELB
```

The VPC does have public subnets, but I've not added them to the cluster. Should I run kops edit cluster, and simply add the public subnets? Is it safe to do so? Would the topology: private bit (link above) cause an issue?

The definition of the deployment + svcs are:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-app
        image: carinamarina/hello-world-app
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: hello
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: hellopub
spec:
  selector:
    app: hello-world
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
```
