### ISSUE TITLE
api.internal dns record not updated on rolling-update

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#2634]
After my new masters were up the dns entry for api.internal was left to the 3 old masters, making all nodes break.  This was kops 1.6.0 and kubernetes 1.6.4.

**Comment by apenney** [comment]
I think this is related to #2633. Rumor is that the masters are responsible for updating this record, and mine are broken on start due to no flannel configuration.

**Comment by mtanski** [comment]
I was also affected by this issue.

The workaround is change the api.internal.* Route53 DNS entry to point to the internal ELB created by kops. This way the next rolling update / or ASG action (like recovering a failed master instance) does not leave you broken cluster where nodes cannot connect.

**Comment by chrislovecnm** [comment]
@apenny can I get more details?

1. Cluster setups
2. Exact steps taken

I assume this is kops 1.6.0

Would like to recreate ;)

**Comment by mtanski** [comment]
Steps:
1. Create a private cluster on AWS (no bastion needed)
2. Observer internal.api.${DOMAIN} Route53 A entry
3. Do a rolling update (force to make sure master also gets re-done)
4. Check the internal.api.${DOMAIN} entry still points to the old instance
5. Wait for nodes to stop being able to communicate with master

I'm not sure this happens first time (or every time) but eventually I'm able to make this happen.

Cluster info:
provider: aws 1 zone
type: private
CNI: weave
masters: 1
nodes: two IG with cluster-autoscaler for ASG

**Comment by chrislovecnm** [comment]
> Create a private cluster on AWS (no bastion needed)

k8s version?

> Observer internal.api.${DOMAIN} Route53 A entry

ELI5 please

> Do a rolling update (force to make sure master also gets re-done)

What version to what version of k8s?  Why force?  Any feature flags?  What is the command you are doing?

> type: private

topology or DNS?

**Comment by apenney** [comment]
I was going from 1.6.2 to 1.6.4.  When I did the rolling-update my master's came back up but did not update the DNS record for internal.api, leaving it pointed at the 3 ip's of my old masters.

Initially I thought the problem was missing 10-flannel.conf, but I think that would have generated if they could have reached internal.api.

Here's the cluster conf, with some domain hiding :)

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-03-24T01:40:17Z
  name: prod.domain
spec:
  additionalPolicies:
    node: |
      [
        {
          "Action": ["sts:AssumeRole"],
          "Effect": "Allow",
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: alpha
  cloudProvider: aws
  configBase: s3://xxx/prod.domain
  dnsZone: xxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    name: events
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.6.2
  masterInternalName: api.internal.prod.domain
  masterPublicName: api.prod.domain
  networkCIDR: 10.10.0.0/16
  networkID: vpc-37917a50
  networking:
    flannel: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.10.64.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.10.96.0/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.10.128.0/19
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.10.160.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.10.164.0/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 10.10.168.0/22
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    bastion:
      bastionPublicName: bastion.prod.domain
    dns:
      type: Public
    masters: private
    nodes: private
```
