### ISSUE TITLE
Node Taints specified on an instance group do not get registered on the apiserver properly

### ISSUE THREAD

**Issue by ottoyiu** [kubernetes/kops#2664]
I'm using kops1.6 and Kubernetes 1.6.2, and specifying taints on an instance group does not register the node in the apiserver with the respective taints. The apiserver does not show the node as tainted.

The instance group manifest:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-31T17:16:55Z
  labels:
    kops.k8s.io/cluster: internal.testing.com
  name: ltt
spec:
  cloudLabels:
    team: ltt
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: c4.4xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    team: ltt
  role: Node
  rootVolumeSize: 120
  rootVolumeType: gp2
  subnets:
  - us-west-2a
  taints:
  - team=ltt:PreferNoSchedule
```

One of the nodes that got spun up by the IG (output from kubectl describe nodes):
```
Name:                   ip-10-63-161-33.us-west-2.compute.internal
Role:                   node
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/instance-type=c4.4xlarge
                        beta.kubernetes.io/os=linux
                        failure-domain.beta.kubernetes.io/region=us-west-2
                        failure-domain.beta.kubernetes.io/zone=us-west-2a
                        kubernetes.io/hostname=ip-10-63-161-33.us-west-2.compute.internal
                        kubernetes.io/role=node
                        node-role.kubernetes.io/node=
                        team=ltt
Annotations:            kubernetes-ec2-srcdst-controller.ottoyiu.com/srcdst-check-disabled=true
                        node.alpha.kubernetes.io/ttl=0
                        volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:                 <none>
CreationTimestamp:      Wed, 31 May 2017 11:06:00 -0700
```

However, nodeup does set the proper daemon flags for kubelet:
https://github.com/kubernetes/kops/blob/ed840d2a6287d2f9fbc326a1def9e40a6b24f926/nodeup/pkg/model/kubelet.go#L296

```bash
admin@ip-10-63-161-33:~$ cat /etc/sysconfig/kubelet
DAEMON_ARGS="--allow-privileged=true --babysit-daemons=true --cgroup-root=/ --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --hostname-override=ip-10-63-161-33.us-west-2.compute.internal --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --node-labels=kubernetes.io/role=node,node-role.kubernetes.io/node=,team=ltt --non-masquerade-cidr=100.64.0.0/10 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=true --register-with-taints=team=ltt:PreferNoSchedule --require-kubeconfig=true --v=2 --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/"
admin@ip-10-63-161-33:~$ ps aux | grep kubelet | grep -v grep
root       1854  2.0  0.2 1135496 87464 ?       Ssl  18:05   0:23 /usr/local/bin/kubelet --allow-privileged=true --babysit-daemons=true --cgroup-root=/ --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --hostname-override=ip-10-63-161-33.us-west-2.compute.internal --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --node-labels=kubernetes.io/role=node,node-role.kubernetes.io/node=,team=ltt --non-masquerade-cidr=100.64.0.0/10 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=true --register-with-taints=team=ltt:PreferNoSchedule --require-kubeconfig=true --v=2 --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/
```

It says in the [kubelet documentation](https://kubernetes.io/docs/admin/kubelet/) that `--register-with-taints` is a no-op unless `--register-node` is true. `--register-schedulable` set to true should cover that? I tried setting `--register-node=true` and restarting kubelet to no avail.

Seeing that nodeup sets the flag properly, this may be a Kubernetes bug instead? Has anyone run into the same issue?
