### ISSUE TITLE
Configuration file instead of command line switches

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#267]
Any thoughts on driving this off of a yaml file, rather than switches?

**Comment by justinsb** [comment]
We do, I think!

Just like with k8s, there is an underlying spec for the cluster and for instance groups.  e.g. https://github.com/kubernetes/kops/blob/master/upup/pkg/api/cluster.go

When you `kops edit cluster` or `kops edit ig` you are editing the actual spec.

The CLI switches act as shortcuts to make it easier to create your seed config.

Or are you saying we should allow you to just specify a yaml file, like `kops create -f <clusterspec>`  That would also be good - and not terribly hard - if so!

**Comment by chrislovecnm** [comment]
The second case, `kops create -f my_cluster.yaml`

**Comment by justinsb** [comment]
Also, would be good to support something like `kubectl replace` or `kubectl apply`.  A use case that came up in sig-aws was changing the default subnet CIDRs.

**Comment by chrislovecnm** [comment]
We need this documented!!!

**Comment by kris-nova** [comment]
I'm still confused what we want/need here... Assigning to you @chrislovecnm - please send a PR with docs/use cases

**Comment by Eyjafjallajokull** [comment]
Hi, just wanted to note this issue is very important for me. I need to automate cluster creation with custom options which are not editable by command line switches (spot price, cidrs). Is there currently any way to script whole process of cluster creation?

**Comment by kris-nova** [comment]
So this feature is already coded into kops https://github.com/kubernetes/kops/blob/master/cmd/kops/create.go#L44

I think we have a little more effort in documenting it, and providing an example YAML file with all possible configurations..

I can try to get one out soon, if nobody else wants to take it.

**Comment by blakebarnett** [comment]
Just reiterating what I said in the channel, I use this currently, my main wish is that I could follow the same pattern with `kops update cluster -f`, currently it's required to duplicate the changes in the yaml files we store in git, and in `kops edit cluster|ig`

**Comment by vlerenc** [comment]
Any update on this? Creation by file/spec would be highly appreciated for headless/automated deployment of Kubernetes clusters through kops. It was written above that the code is already present, but it's not yet released?

**Comment by kris-nova** [comment]
Hey @vlerenc 

So as it stands today on [1.5.3](https://github.com/kubernetes/kops/releases/tag/1.5.3) a user can certainly use `kops create -f $CONFIG`.

A baseline config can be found by using a basic `kops edit cluster` command as in:

```bash
kops edit cluster $NAME
```

My example for **private topology** looks like:

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,                                                                                                                     
# and an empty file will abort the edit. If an error occurs while saving this file will be                                                                                                      
# reopened with the relevant failures.                                                                                                                                                          
#                                                                                                                                                                                               
apiVersion: kops/v1alpha2                                                                                                                                                                       
kind: Cluster                                                                                                                                                                                   
metadata:                                                                                                                                                                                       
  creationTimestamp: "2017-03-19T13:34:45Z"                                                                                                                                                     
  name: demo.nivenly.com                                                                                                                                                                        
spec:                                                                                                                                                                                           
  api:                                                                                                                                                                                          
    loadBalancer:                                                                                                                                                                               
      type: Public                                                                                                                                                                              
  channel: stable                                                                                                                                                                               
  cloudProvider: aws                                                                                                                                                                            
  configBase: s3://nivenly-state-store/demo.nivenly.com                                                                                                                                         
  etcdClusters:                                                                                                                                                                                 
  - etcdMembers:                                                                                                                                                                                
    - instanceGroup: master-us-west-1a                                                                                                                                                          
      name: a                                                                                                                                                                                   
    name: main                                                                                                                                                                                  
  - etcdMembers:                                                                                                                                                                                
    - instanceGroup: master-us-west-1a                                                                                                                                                          
      name: a                                                                                                                                                                                   
    name: events                                                                                                                                                                                
  kubernetesApiAccess:                                                                                                                                                                          
  - 0.0.0.0/0                                                                                                                                                                                   
  kubernetesVersion: 1.5.2                                                                                                                                                                      
  masterInternalName: api.internal.demo.nivenly.com                                                                                                                                             
  masterPublicName: api.demo.nivenly.com                                                                                                                                                        
  networkCIDR: 172.20.0.0/16                                                                                                                                                                    
  networking:                                                                                                                                                                                   
    weave: {}                                                                                                                                                                                   
  nonMasqueradeCIDR: 100.64.0.0/10                                                                                                                                                              
  sshAccess:                                                                                                                                                                                    
  - 0.0.0.0/0                                                                                                                                                                                   
  subnets:                                                                                                                                                                                      
  - cidr: 172.20.32.0/19                                                                                                                                                                        
    name: us-west-1a                                                                                                                                                                            
    type: Private                                                                                                                                                                               
    zone: us-west-1a                                                                                                                                                                            
  - cidr: 172.20.0.0/22                                                                                                                                                                         
    name: utility-us-west-1a                                                                                                                                                                    
    type: Utility                                                                                                                                                                               
    zone: us-west-1a                                                                                                                                                                            
  topology:
    bastion:                                                                                                                                                                                    
      bastionPublicName: bastion.demo.nivenly.com                                                                                                                                               
    dns:                                                                                                                                                                                        
      type: Public                                                                                                                                                                              
    masters: private                                                                                                                                                                            
    nodes: private             
```


##### kops update -f

Now this frankly is a great idea. I can't believe we don't have this yet. I will push for this in the next release(s) and see if I can't find a volunteer to help code it. I know @geojaz is working on `kops create -f` in general, so maybe he would be interested in `kops update -f` as well? 😉 

It will be tricky managing the deltas but thanks to the way `kops` handles it's internal models this feature should fit in nicely.

@justinsb what are your thoughts on this as far as implementation goes? This seems like low hanging fruit but want to bounce it off you before I get too carried away here.

I think we should close this issue as `kops create -f` is now in place, and open up an issue in favor of `kops update -f`.
