### ISSUE TITLE
DNS for api.internal not updated after doing a rolling update when a LoadBalancer service has a Route 53 entry

### ISSUE THREAD

**Issue by jordanjennings** [kubernetes/kops#2671]
Cluster was created using kops 1.6 and k8s 1.6.4, and has a couple services `type: LoadBalancer` using `dns.alpha.kubernetes.io/internal` to create Route 53 entries via dns controller.

When I do a rolling update on the master, the cluster never comes back up and I notice that the `api.internal.k8s.mydomain.com` Route 53 doesn't get updated (still has the old master IP). Looking at the logs from the dns controller I see:

```
W0602 00:56:42.356882       1 dnscontroller.go:119] Unexpected error in DNS controller, will retry: 
error applying DNS changeset for zone mydomain.com.::Z123456ABCDEFG: InvalidChangeBatch: 
Tried to create resource record set [name='\052.k8s.mydomain.com.', type='CNAME'] but it already 
exists
```

Note: `\052.k8s.mydomain.com` is the escaped version of `*.k8s.mydomain.com` (these DNS entries are pointing to ingress controllers which then route based on the host name)

It appears to be getting stuck on updating Route 53 because it's trying to create a Route 53 entry that already exists for the LoadBalancer service, but then the api.internal DNS entry doesn't get updated either.

Workaround: delete the Route 53 entries for the services manually and then the dns controller recreates them and updates the api.internal entry properly, and the cluster comes back up.

I know there are several other DNS issues related to rolling updates and upgrades, etc but I don't think I have seen anyone report this one. Let me know if I can provide any other helpful details on this issue, or if there's an existing issue tracking this.

**Comment by mikesplain** [comment]
@jordanjennings this just happened to me as well when upgrading from kops 1.6.0 to 1.6.1.  We have an annotation on a svc for ingress with `dns.alpha.kubernetes.io/internal=*.dev3.example.com` and saw the same issue:

```
I0614 20:07:58.535149       1 dnscontroller.go:566] Adding DNS changes to batch {A api.internal.dev3.example.com.} [10.24.109.135 10.24.40.252 10.24.66.85]
I0614 20:07:58.535167       1 dnscontroller.go:256] Using default TTL of 1m0s
I0614 20:07:58.535203       1 dnscontroller.go:566] Adding DNS changes to batch {CNAME *.dev3.example.com.} [internal-XXXXXXXXXX-XXXXXXXXXX.us-east-1.elb.amazonaws.com]
I0614 20:07:58.535218       1 dnscontroller.go:301] applying DNS changeset for zone example.com.::XXXXXXXXXX
W0614 20:07:58.583562       1 dnscontroller.go:303] error applying DNS changeset for zone example.com.::XXXXXXXXXX: InvalidChangeBatch: Tried to create resource record set [name='\052.dev3.example.com.', type='CNAME'] but it already exists
        status code: 400, request id: 2944f777-513d-11e7-b6e4-3b33dc166b2c
W0614 20:07:58.583594       1 dnscontroller.go:119] Unexpected error in DNS controller, will retry: error applying DNS changeset for zone example.com.::XXXXXXXXXX: InvalidChangeBatch: Tried to create resource record set [name='\052.dev3.example.com.', type='CNAME'] but it already exists
        status code: 400, request id: 2944f777-513d-11e7-b6e4-3b33dc166b2c```

I deleted the entry and the cluster came up as expected.  Maybe we should add some error handling here or something

**Comment by jordanjennings** [comment]
For anyone finding this, I migrated to external DNS and no more issues. As an added bonus, external DNS supports mapping Route 53 entries to the ingress ELB automatically, so you don't have to do the wildcard approach like with dns controller.

**Comment by mikesplain** [comment]
@jordanjennings which external dns did you switch to?

**Comment by jordanjennings** [comment]
@mikesplain it's actually just called "External DNS": https://github.com/kubernetes-incubator/external-dns

Kops supports external DNS via a flag, but what is currently baked in doesn't allow custom parameters. Here's what I ended up using:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    k8s-addon: external-dns.addons.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    k8s-addon: external-dns.addons.k8s.io
  name: kops:external-dns
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-addon: external-dns.addons.k8s.io
  name: kops:external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kops:external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    k8s-addon: external-dns.addons.k8s.io
    k8s-app: external-dns
    version: v0.3.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: external-dns
  template:
    metadata:
      labels:
        k8s-addon: external-dns.addons.k8s.io
        k8s-app: external-dns
        version: v0.3.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        # For 1.6, we keep the old tolerations in case of a downgrade to 1.5
        scheduler.alpha.kubernetes.io/tolerations: '[{"key": "dedicated", "value": "master"}]'
    spec:
      serviceAccount: external-dns
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      dnsPolicy: Default  # Don't use cluster DNS (we are likely running before kube-dns)
      hostNetwork: true
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.3.0
        args:
        - --source=ingress
        - --source=service
        - --domain-filter={{ .hostedZoneDomain }}
        - --provider=aws
        - --registry=txt
        - --txt-owner-id={{ .clusterName }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
```
