### ISSUE TITLE
Route53 mapper: pod can't be scheduled

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2677]
I bumped into this:

```
No nodes are available that match all of the following predicates:: MatchNodeSelector (2), PodToleratesNodeTaints (1).
```

I'm trying to deploy the Route53 mapper 1.3.0 using `kubectl apply -f <url/to/github/master>`. Any ideas on how I could debug this?

I've been staring at my `master` node config and at my deployments and their differences, but I don't see anything unusual about them.

**Comment by johnwchadwick** [comment]
It sounds like your master is not schedulable. I believe this is the default for `kube-up` clusters but probably not Kops clusters (I say probably not because Kops marked my master node schedulable when upgrading from a `kube-up` cluster.)

The route53 pods will explicitly ask for a Master node:

```yaml
    spec:
      nodeSelector:
        kubernetes.io/role: master
```

But many Kubernetes masters will have a taint:
```
node.alpha.kubernetes.io/role=master:NoSchedule
```

There's two possible solutions here.

1. You could make a custom Route53 mapper that has a toleration to match. Please keep in mind that it will need to match the actual taint on your master node, so use the `describe node` feature to find it.

```yaml
tolerations: 
  - key: "node.alpha.kubernetes.io/role"
    operator: "Equal"
    value: "master"
    effect: "NoSchedule"
```

2. You could mark your master as schedulable. I do not know how dangerous this is, but as best as I can tell kops is doing it whether purposefully or not, and it hasn't caused any anomalies that I've noticed in production.

    To do this, just remove the taint. Again, it's gotta match whatever taint you actually have, my example may not match your master node(s.)
```
kubectl taint nodes [master node] node.alpha.kubernetes.io/role:NoSchedule-
```

**Comment by ketzacoatl** [comment]
I'm running into this as well. I've only ever used `kops` to manage this cluster (which is currently 1.6.4), and I see a taint like: `node-role.kubernetes.io/master=<no value>:NoSchedule`.

If, by default, `kops` enabled scheduling on the master nodes, why would I have this taint?

**Comment by johnwchadwick** [comment]
I'm actually not sure what the `<no value>` is about, I'm sure a Kubernetes expert could explain this.

As to whether or not the taint is applied by default, I am pretty darn sure it is. There's probably a lot of reasons, esp. ensuring master reliability and capacity, but there is one that is possibly AWS specific: IAM roles.

When you create a cluster via Kops, it applies a separate IAM role to masters vs other nodes. This separate IAM role needs extra permissions in some cases, like this one where it needs *write access to Route53*. You can see why you'd not want ordinary applications to have access to this, because they could effectively take over all domains that you grant Route53 mapper access to. Maybe your code wouldn't take advantage of this, but keep in mind if anyone manages to gain RCE on any app running in the cluster, they would get this if the IAM role for nodes had access to Route53.

For this reason I think it would be unwise to remove the `NoSchedule` taint from the master node, you definitely want to limit what's running on the master.

Anyways, I'm again no Kubernetes expert, but here's my understanding:

```node-role.kubernetes.io/master=<no value>:NoSchedule```

This taint has three parts:

  * Key: `node-role.kubernetes.io/master`
  * Value: `<no value>` (oddly enough...)
  * Effect: `NoSchedule`

The first two (key and value) seem to largely be inconsequential and are probably designed to make it so that your deployments can be very specific about the type of taints they can tolerate. 

I'm not sure how you'd specify that it should match no value, but maybe specifying an empty string would do the trick.

The error message actually tells you everything you need to know about why things aren't working. Yours will probably differ at least a little, but let's look at the one in the OP.
```
No nodes are available that match all of the following predicates:: MatchNodeSelector (2), PodToleratesNodeTaints (1).
```

  * `MatchNodeSelector (2)` tells us that the node selector in the deployment does not match 2 nodes.
  * `PodToleratesNodeTaints (1)` tells us that the tolerations in the deployment does not match 1 node.

What's happening here is, Kubernetes is deciding what nodes the deployment can be scheduled on and is determining that, based on parameters, none of the nodes match the criteria.

That's because this criteria will refuse non-master nodes:
```yaml
      nodeSelector:
        kubernetes.io/role: master
```

We know that this criteria is working because presumably the OP has 3 nodes and the `MatchNodeSelector` is only rejecting 2 nodes, so it probably is matching the master only. But the problem is that the master has a taint preventing normal applications from being scheduled, and ultimately the deployment is not tolerating those taints.

----

OK, I hope my explanation of what's going on here is adequate. But you're probably wondering what to do next. I think what you want to do is download the Route53-mapper deployment and add a toleration matching your master node's taint.

As an example, I just tried to take the v1.3.0 yaml and adjust it. It might not work, now would be a good final time to emphasize that I'm no expert.

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: route53-mapper
  namespace: kube-system
  labels:
    app: route53-mapper
    k8s-addon: route53-mapper.addons.k8s.io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route53-mapper
  template:
    metadata:
      labels:
        app: route53-mapper
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"node-role.kubernetes.io", "effect":"NoSchedule"}]'
    spec:
      nodeSelector:
        kubernetes.io/role: master
      containers:
        - image: quay.io/molecule/route53-kubernetes:v1.3.0
          name: route53-mapper
```

I believe there's a more 'first class' way of specifying tolerations in the yaml, but I don't know where in the podspec it belongs. More information in the documentation here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by ketzacoatl** [comment]
Thanks @johnwchadwick, for taking the time to cover the details. They fill in and confirm what I understand about the issue.

When reviewing the docs for `route53-mapper`, one assumes we will be deploying it to a master node, so it doesn't seem to make sense that the spec (or docs..) would not attempt to address this issue with scheduling on the masters. Does the upstream spec need an update, or should the docs address this?

Putting that aside and focusing on updating a spec to run route53-mapper on my cluster, when inspecting the master nodes with `describe node`, I can see:

```
Taints:                 node-role.kubernetes.io/master:NoSchedule
```

Thus, I added `{"key":"node-role.kubernetes.io/master", "effect":"NoSchedule"}` to https://github.com/kubernetes/kops/blob/66a9e0dfc1ee619bcd0539c771cbb5aedd249bf7/addons/route53-mapper/v1.3.0.yml, which looked like:

```
  template:
    metadata:
      labels:
        app: route53-mapper
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated", "value":"master"}, {"key":"node-role.kubernetes.io/master", "effect":"NoSchedule"}]'
```

The pod is in `Pending` state, and with `describe pod` I can see:

```
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"route53-mapper-...","uid":"...
                scheduler.alpha.kubernetes.io/tolerations=[{"key":"dedicated", "value":"master"}, {"key":"node-role.kubernetes.io/master", "effect":"NoSchedule"}]
Status:         Pending
...
  19s           4s              6       default-scheduler                       Warning         FailedScheduling        No nodes are available that match all of the following predicates:: MatchNodeSelector (4), PodToleratesNodeTaints (3).
```

I also put `{"key":"node-role.kubernetes.io", "effect":"NoSchedule"}` into the spec, but that didn't work out this conflict either.

**Comment by johnwchadwick** [comment]
Honestly, I'm not sure at this point. The documentation for Kubernetes has a different syntax for adding tolerations into the PodSpec, but it's not very well documented yet. Maybe using annotations to do tolerations does not work in Kubernetes 1.6 - I'm on 1.5 and it seems to still work. It's possible that this file may need to be updated for 1.6.

**Comment by WillemMali** [comment]
What version of K8s are you two on? I'm on 1.6 and I'm trying to use the new toleration syntax right now, I'm hoping that will solve my problem and I'll update when I know more.

**Comment by WillemMali** [comment]
Adding this to my deployment's pod specification fixed it for me:

```
      tolerations: [{"key":"dedicated", "value":"master"}, {"key":"node-role.kubernetes.io/master", "effect": "NoSchedule"}]
```

**Comment by ketzacoatl** [comment]
ahah, I had `scheduler.alpha.kubernetes.io/tolerations` and used the `annotations` when I should have updated that to `tolerations` and moved to the pod spec. I also had some spurious `'` mixed in to make the list object a string (from the annotation).

I can confirm, on 1.6.x, with a cluster deployed by `kops`, this is working for me.. and either form:

`tolerations: [{"key":"dedicated", "value":"master"}, {"key":"node-role.kubernetes.io/master", "effect":"NoSchedule"}]`

or:

```
spec:
  ...
  template:
    ...
    spec:
      ...
      tolerations:
        - key: dedicated
          value: master
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
```

**Comment by andyp1per** [comment]
I too am running into this. The current addon yaml for kops 1.6 is clearly broken, but I'm not sure what the correct fix is. The second form in the comment above gets the service scheduled for me, but then I run into this problem:

W0613 09:50:09.869434       1 service_listener.go:145] Couldn't get zone ID: Could not describe load balancer: AccessDenied: User: arn:aws:sts::071824717951:assumed-role/nodes.diffusion.kube.reappt.ninja/i-0f064bebc4af06c2b is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers

This looks very similar to the cluster autoscaler issues I had when the security wasn't set up properly.

**Comment by andyp1per** [comment]
To add to my comment, this gets the pod scheduled but *not* on the master, which I think is why it doesn't work.

**Comment by andyp1per** [comment]
Adding this, correctly scheduled it on the master node for me:

```
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
```

I pilfered this from the cluster autoscaler addon

**Comment by joshuatalb** [comment]
I bumped into this issue just now after upgrading to the latest k8s version (1.6.2). The solution above this comment works, so thank you @andyp1per - much appreciated!

**Comment by andyp1per** [comment]
You're welcome, although to be honest I have abandoned this approach because 
```
  annotations:
    dns.alpha.kubernetes.io/external: "xxx.example.com"
```
is a lot easier to use and requires no set-up

**Comment by sellers** [comment]
@andyp1per  thanks for the above comment about the annotations for the Service annotations to have the dns.alpha.kubernetes.io/external: "external DNS namehere" is great.   It worked for adding a DNS entry for my load balancer for the Ingress controller.   FTW.    If you set your annotations to also say     service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0 then the internal/external does not matter so much for the dns.alpha.kubernetes.io/ annotation.

**Comment by jonathan-kosgei** [comment]
@andyp1per can you similarly specify an ACM certificate for SSL?

**Comment by andyp1per** [comment]
@jonathan-kosgei did not try. Obviously SSL termination in the load balancer is an interesting problem. I think when I looked at this I needed to setup an nginx ingress controller and did not have the time to experiment.

**Comment by jonathan-kosgei** [comment]
Thanks, I guess I'll stick with the addon to allow SSL termination

**Comment by jchv** [comment]
SSL termination works for me in Kubernetes since at least 1.5 without any cluster addons. SSL certificate annotations have no impact on the DNS settings and visa versa.

```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:xxxxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    dns.alpha.kubernetes.io/external: "domain.name"
```
