### ISSUE TITLE
Kube-dns pods shouldn't all be on one node

### ISSUE THREAD

**Issue by weaseal** [kubernetes/kops#2693]
We are experiencing failures due to all kube-dns pods landing on a single node (2 of 2 pods in our case), and that node eventually suffers any issue (network outage, physical host issue) and then all DNS services stop which causes all of our applications to fail.

It would be a great improvement if kops supported some method to ensure that this doesn't happen, perhaps via daemonsets or affinities.

This is on kubernetes 1.5.3 and kops 1.5.3

**Comment by chrislovecnm** [comment]
We probably should have anti-affinity rules spread the pods around.  Here is an example of k8s 1.6 anti-affinity rules:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: [“nginx-deployment"]
```

We would need to tweak for the kube-dns deployment.  We alway appreciate new contributors, the changes are pretty easy to make if you have a chance.
