### ISSUE TITLE
Kubernetes external ELBs can't be deployed

### ISSUE THREAD

**Issue by bdshibly** [kubernetes/kops#2714]
Hi,

I wanted to configure kubernetes cluster on private network and external ELBs public network. Here is the kops command which I used

`kops create cluster --cloud=aws --name=pr1kubernetes1.shibly.com --state=s3://pr1kubernetes1 --zones=us-west-2c,us-west-2b,us-west-2a --node-count=3 --node-size=m3.xlarge --master-size=m3.large --dns-zone=pr1kubernetes1.shibly.com --master-zones=us-west-2a,us-west-2b,us-west-2c --vpc=<vpc_id> --network-cidr=<cidr> --networking=weave --dns=private --channel=stable --associate-public-ip=false --topology=private --admin-access=<cidr> `

Here is my subnets configuration: 

```
subnets:
  - cidr: 10.10.0.0/24
    name: us-west-2c  
    egress: nat-abcd
    type: Private
    zone: us-west-2c
    id: subnet-abcd
  - cidr: 10.20.0.0/24
    name: utility-us-west-2c  
    type: Utility
    zone: us-west-2c
    id: subnet-efgh
```

 It created the cluster on Private subnets but when I am trying to create external ELBs it is giving me the following error. 

`Error creating load balancer (will retry): Failed to create load balancer for service kube-system/monitoring-grafana: could not find any suitable subnets for creating the ELB 
`
```
apiVersion: v1
kind: Service
metadata:
  labels:
    # kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: LoadBalance
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: grafana

```
How can I create the cluster on private subnet and ELBs on public subnets?

Thanks
Shibly
