### ISSUE TITLE
route53-mapper pod creation fails with RBAC cluster

### ISSUE THREAD

**Issue by depohmel** [kubernetes/kops#2751]
Hello, I have kops deployed  cluster with --authorization=RBAC. 
With route53-mapper deployed with default https://github.com/kubernetes/kops/blob/master/addons/route53-mapper/v1.3.0.yml
pod gets restarted with following:

` Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "route53-mapper" with CrashLoopBackOff: "Back-off 10s restarting failed container=route53-mapper pod=route53-mapper-116802119-78bwj_kube-system"
`

route53-mapper requires access into all namespaces in cluster and 'default' service account from kube_system doesn't have them.

I was trying to find what exactly permissions route53-mapper is required, but did find it in the docs.

As workaround I've granted cluster-admin access to kube_system default sa.

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-system-default-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
```
 Could you please update docs with kubernetes permissions required for route53-mapper ?
