### ISSUE TITLE
Additional Flags for kubelet, apiserver, etc

### ISSUE THREAD

**Issue by cheddarwhizzy** [kubernetes/kops#2828]
Sorry if this is documented somewhere and I just didn't see it.

I need to add --experimental-allowed-unsafe-sysctls to kubelet so I can increase the net.core.somaxconn value, but I'm not quite sure how to with Kops. This would be good to know for other services too such as proxy, apiserver, etc.. in the event I needed to add additional flags to any of the required components of the cluster.

Is there a way to do this today?

**Comment by bporter2387** [comment]
I suppose I could overwrite /etc/sysconfig/kubelet. I also don't see the mapping here: https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go

I would be more than happy to create a PR if this flag is desired :)

**Comment by chrislovecnm** [comment]
Please add in a pr, there are instructions in the developer folder under docs.

**Comment by kenden** [comment]
It's possible to pass some flags to apiserver:https://github.com/kubernetes/kops/blob/4edc267fb8da63449fa681a9723c010610cab815/docs/cluster_spec.md#runtimeconfig

For this Kubelet flag, not sure this would work but it's worth a try:
https://github.com/kubernetes/kops/blob/4edc267fb8da63449fa681a9723c010610cab815/docs/cluster_spec.md#kubelet
Replace `resolvConf` by `experimental-allowed-unsafe-sysctls` and you get:
```
spec:
  kubelet:
    experimental-allowed-unsafe-sysctls: "kernel.msg*,net.ipv4.route.min_pmtu"
```

Does it work?

**Comment by aledbf** [comment]
@cheddarwhizzy please check https://github.com/kubernetes/kubernetes/pull/54896

**Comment by smcquay** [comment]
I just ran into this issue to enable similar `sysctl`s:

/remove-lifecycle stale

**Comment by smcquay** [comment]
@cheddarwhizzy I've got a fix for `kops` to enable this, but I'm stuck in testing as everything I do to submit a pod with that annotation continues to give me the `SysctlForbidden` error.

I've added the following to a `Deployment` spec:

```yaml
      annotations:
        security.alpha.kubernetes.io/sysctls: net.ipv4.tcp_keepalive_time=5,net.ipv4.tcp_keepalive_intvl=1,net.ipv4.tcp_keepalive_probes=5,net.core.somaxconn=4096,net.ipv4.tcp_abort_on_overflow=1,net.ipv4.tcp_slow_start_after_idle=0
```

And I've tried adding a `PodSecurityPolicy` as well:

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sysctl-psp
  annotations:
    security.alpha.kubernetes.io/sysctls: 'net.ipv4.tcp_keepalive_time,net.ipv4.tcp_keepalive_intvl,net.ipv4.tcp_keepalive_probes,net.core.somaxconn,net.ipv4.tcp_abort_on_overflow,net.ipv4.tcp_slow_start_after_idle'
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
```

but that doesn't seem to help. I'm going to continue to dig deeper into the docs, but if you've got a light to shine on where I'm stuck I'd appreciate it.
