### ISSUE TITLE
aws: private cluster must create private ELB

### ISSUE THREAD

**Issue by trung** [kubernetes/kops#2845]
```
kops create cluster ${NAME} --dns private --topology private --cloud aws
```
This creates a **public** ELB for master instances.

**Comment by chrislovecnm** [comment]
@trung this is as designed see https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#spec, for information on how to move to an internal elb.

```yaml
spec:
  api:
    loadBalancer:
      type: Private
      idleTimeoutSeconds: 300
```
