### ISSUE TITLE
Automatically label nodes as ready for Fluentd?

### ISSUE THREAD

**Issue by aknuds1** [kubernetes/kops#2870]
I'm wondering if kops should automatically label nodes with `beta.kubernetes.io/fluentd-ds-ready=true`, as otherwise Fluentd DaemonSet won't schedule pods on them (see the [1.6 release notes](https://github.com/kubernetes/features/blob/master/release-1.6/release-notes-draft.md) for background)? Otherwise, if this is not desirable, is there a way to configure this node label via `kops create`? 

See my [StackOverflow question](https://stackoverflow.com/questions/44943834/how-do-i-configure-kubernetes-node-labels-when-creating-a-cluster-with-kops) for reference.

**Comment by georgebuckerfield** [comment]
I'm doing this using `nodeLabels` on the InstanceGroup e.g.

```
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: m3.medium
  maxSize: 3
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
```
