### ISSUE TITLE
kops API deprecate or remove kubeDNS

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2909]
We have:

```YAML
 kubeDNS:
    domain: us-east-1-cluster.local
    image: quay.io/vorstella/kubedns-amd64:1.3
    replicas: 2
    serverIP: 100.64.0.10
```
In the `clusterSpec`.  Admittedly this is doing nothing since kube-dns is an addon.
