### ISSUE TITLE
Cannot use terraform and gossip-based cluster at the same time

### ISSUE THREAD

**Issue by simnalamburt** [kubernetes/kops#2990]
If you create a cluster with both terraform and gossip options enabled, __all `kubectl` commands shall fail__.

<br>

## How to reproduce the error
My environment
```console
$ uname -a
Darwin *****.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

$ kops version
Version 1.6.2

$ terraform version
Terraform v0.9.11

$ aws --version
aws-cli/1.11.117 Python/2.7.10 Darwin/16.6.0 botocore/1.5.80
```

Setting up the cluster
```bash
# Create RSA key
ssh-keygen -f shared_rsa -N ""

# Create S3 bucket
aws s3api create-bucket \
  --bucket=kops-temp \
  --region=ap-northeast-1 \
  --create-bucket-configuration LocationConstraint=ap-northeast-1

# Create terraform codes and some resources
# including *certificates* will be stored to S3
kops create cluster \
  --name=kops-temp.k8s.local \
  --state=s3://kops-temp \
  --zones=ap-northeast-1a,ap-northeast-1c \
  --ssh-public-key=./shared_rsa.pub \
  --out=. \
  --target=terraform

# Create cluster
terraform init
terraform plan -out ./create-cluster.plan
terraform show ./create-cluster.plan | less -R # final review
terraform apply ./create-cluster.plan # fire

# Done
```

**Spoiler Alert**: Creating the self-signed certificate before creating actual Kubernetes cluster is the root cause of this issue. Please continue to see why.

### Scenario 1. Looking up non-existent domain
```console
$ kubectl get nodes
Unable to connect to the server: dial tcp: lookup api.kops-temp.k8s.local on 8.8.8.8:53: no such host
```

This is basically because of erroneous `~/.kube/config` file. If you run the `kops create cluster` with both terraform and gossip options enabled, you'll get wrong `~/.kube/config` file.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ABCABCABCABC...
    server: https://api.kops-temp.k8s.local
            # !!!! There's no such domain named "api.kops-temp.k8s.local"
  name: kops-temp.k8s.local
# ...
```

Let's manually correct that file. Or, you'll get good config file if you explicitly export the configuration once again.

```bash
kops export kubecfg kops-temp.k8s.local --state s3://kops-temp
```

Then the non-existent domain will be replaced with the ELB of master nodes' DNS name.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ABCABCABCABC...
    server: https://api-kops-temp-k8s-local-nrvnqsr-666666.ap-northeast-1.elb.amazonaws.com
  name: kops-temp.k8s.local
# ...
```

And you'll be ended up to the scenario 2 when you retry.

### Scenario 2. Invalid certificate
```console
$ kubectl get nodes
Unable to connect to the server: x509: certificate is valid for api.internal.kops-temp.k8s.local, api.kops-temp.k8s.local, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not api-kops-temp-k8s-local-nrvnqsr-666666.ap-northeast-1.elb.amazonaws.com
```

This is simply because the DNS name of ELB is not included in the certificate. This scenario occurs only when you create the cluster with terraform option being enabled. If you try to create the cluster only with gossip option not using the terraform target, the self-signed certificate will properly contain the DNS name of ELB.

<img width="277" alt="2017-07-19 12 01 32" src="https://user-images.githubusercontent.com/4435445/28324048-761a65fe-6c15-11e7-9876-2b2b79493719.png">

*(Sorry for the Korean, this is the list of DNS alternative names of certificate)*

The only way to workaround this problem is forcing "kops-temp.k8s.local" to point proper IP address via manually editing `/etc/hosts`, which is undesired for many people.

```bash
# Recover ~/.kube/config
perl -i -pe \
    's|api-kops-temp-k8s-local-rnvnqsr-666666\.ap-northeast-1\.elb\.amazonaws\.com|api.kops-temp.k8s.local|g' \
    ~/.kube/config

# Hack /etc/hosts
host api-kops-temp-k8s-local-nrvnqsr-666666.ap-northeast-1.elb.amazonaws.com |
    perl -pe 's|^.* address (.*)$|\1\tapi.kops-temp.k8s.local|g' |
    sudo tee -a /etc/hosts

# This will succeed
kubectl get nodes
```

<br>

I'm not very familiar with Kops internal, but I expect a huge change to properly fix this issue. Maybe using AWS Certificate Manager can be a solution. (#834) Any ideas?
