### ISSUE TITLE
docker options not used under CoreOS

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes/kops#3057]
docker options seem to be ignored when running on top of CoreOS.

cluster.yaml:
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  docker:
    bridgeIP: 192.168.5.1/24
```

ig.yaml:
```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
spec:
  image: coreos.com/CoreOS-stable-1409.7.0-hvm
```

```bash
$ ifconfig docker0
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:33:17:6f:f9  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
