### ISSUE TITLE
upgrade from 1.6 to 1.7 failed due to kube-proxy being passed extra arguments

### ISSUE THREAD

**Issue by erickt** [kubernetes/kops#3060]
We tried upgrading a kubernetes from 1.6.7 to 1.7.0, and this ended up breaking my cluster. The problem seems to be stemming from kube-proxy in 1.7 no longer taking arguments (see https://github.com/kubernetes/kubernetes/pull/34727). However, my cluster's kube-proxy is trying to run:

```
    - /bin/sh
    - -c
    - echo -998 > /proc/$$$/oom_score_adj && kube-proxy --kubeconfig=/var/lib/kube-proxy/kubeconfig
      --conntrack-max-per-core=131072 --resource-container="" --cluster-cidr=100.96.0.0/11
      --hostname-override=XXXX
      --master=https://127.0.0.1 --v=2 2>&1 | /usr/bin/tee /var/log/kube-proxy.log
```

This errors out with:

```
Flag --resource-container has been deprecated, This feature will be removed in a later release.
W0727 03:47:00.558965       5 server.go:188] WARNING: all flags other than --config, --write-config-to, and --cleanup-iptables are deprecated. Please begin using a config file ASAP.
F0727 03:47:00.559061       5 helpers.go:120] error: no arguments are supported
```

@chrislovecnm asked me to provide the `/etc/kubernetes/manifests/kube-proxy.manifest`:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    k8s-app: kube-proxy
    tier: node
  name: kube-proxy
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo -998 > /proc/$$$/oom_score_adj && kube-proxy --kubeconfig=/var/lib/kube-proxy/kubeconfig
      --conntrack-max-per-core=131072 --resource-container="" --cluster-cidr=100.96.0.0/11
      --hostname-override=XXXX YYYY
      --master=https://api.internal.ZZZZ --v=2 2>&1 | /usr/bin/tee
      /var/log/kube-proxy.log
    image: gcr.io/google_containers/kube-proxy:v1.7.0
    imagePullPolicy: IfNotPresent
    name: kube-proxy
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/kube-proxy/kubeconfig
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-hosts
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/log
    name: varlog
  - hostPath:
      path: /var/lib/kube-proxy/kubeconfig
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-hosts
status: {}
```
