### ISSUE TITLE
Cannot add manually created subnet to cluster using subnet id

### ISSUE THREAD

**Issue by Shemeikka** [kubernetes/kops#3096]
Problem:
I have created a cluster using the HA-guide and after that I created new subnet & route table manually using AWS console. I try to add this new subnet to the cluster spec but I get an error after kops edit cluster:

    cannot mix subnets with specified ID and unspecified ID

Cluster subnet spec:

```
subnets:
   - cidr: 172.20.32.0/19
     name: eu-west-1a
     type: Private
     zone: eu-west-1a
   - cidr: 172.20.64.0/19
     name: eu-west-1b
     type: Private
     zone: eu-west-1b
   - cidr: 172.20.96.0/19
     name: eu-west-1c
     type: Private
     zone: eu-west-1c
   - cidr: 172.20.0.0/22
     name: utility-eu-west-1a
     type: Utility
     zone: eu-west-1a
   - cidr: 172.20.4.0/22
     name: utility-eu-west-1b
     type: Utility
     zone: eu-west-1b
   - cidr: 172.20.8.0/22
     name: utility-eu-west-1c
     type: Utility
     zone: eu-west-1c
   - id: <subnet_id>
     name: <subnet_name>
     type: Private
     zone: eu-west-1a
```
What I try to achieve:

I have my kubernetes cluster with a new instance group called clerks. This instance group has to have custom route in the route table. I think this requires that I manually create new subnet and route table and then somehow attach that subnet to that instance group. This requires that the subnet is added to the cluster spec? But the cluster spec doesn't allow mixed subnets (with/without id).

Kops version 1.6.2 (git-98ae12a)
