### ISSUE TITLE
kops not working with multiple domains set in dhcp options on aws

### ISSUE THREAD

**Issue by zachaller** [kubernetes/kops#3164]
I ran into this running on the official release of kops 1.7 while upgrading to 1.7 this completely broke our cluster but because it was a test cluster just trashed it and tried to create a new cluster which also did not work. Digging into it pretty sure we ran across this issue #3060 so I ended up building kops from master so that i could get that pull into my kops version Version 1.7.0 (git-38608bd)

What I have noticed its my kube-proxy manifest still has all the domains listed from the dhcp option set so its like the pull request did not actually fix it. I should note this is running in an existing vpc and we need these set for the old infrastructure.

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    k8s-app: kube-proxy
    tier: node
  name: kube-proxy
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo -998 > /proc/$$$/oom_score_adj && kube-proxy --kubeconfig=/var/lib/kube-proxy/kubeconfig
      --conntrack-max-per-core=131072 --resource-container="" --cluster-cidr=100.96.0.0/11
      --hostname-override=ip-10-120-50-37.yyyyyyy.com xxxxxxx.com
      ec2.internal --master=https://api.internal.zaller-00.k8-prod.zzzzzz.com --v=2
      2>&1 | /usr/bin/tee /var/log/kube-proxy.log
    image: gcr.io/google_containers/kube-proxy:v1.7.0
    imagePullPolicy: IfNotPresent
    name: kube-proxy
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/kube-proxy/kubeconfig
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-hosts
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/log
    name: varlog
  - hostPath:
      path: /var/lib/kube-proxy/kubeconfig
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-hosts
status: {}
```
