### ISSUE TITLE
in a private topology the utility subnet is too small and changing it's size causes weirdness with elbs

### ISSUE THREAD

**Issue by KITSTomVN** [kubernetes/kops#3172]
Heya

Not sure if this is an issue with kops or the kubernetes AWS integration but I thought I'd start here seeing as the kops cluster yaml doesn't match up with what I'm trying to do.

The tl;dr is that if I modify the utility subnets to be a bit bigger and create a Service resource of spec.type Loadbalancer then the ELB that gets created ends up with 2/3 legs on the Utility subnets and 1/3 legs on the Private subnet, doesn't work properly, and I can't understand why.

Long version is I run `kops create cluster --topology private --networking weave --network-cidr 172.16.16.0/22 --authorization RBAC --node-count 6 --zones eu-west-1a,eu-west-1b,eu-west-1c --master-zones eu-west-1a,eu-west-1b,eu-west-1c --master-size m4.large --node-size m4.large --kubernetes-version 1.7.2 non-prod.k8s.local`, I then `kops edit cluster non-prod.k8s.local`and change the default Utility network size of /28 to a /25 (because /28 is far to small to hold a meaningful number of ELBs and the nat gateways) and shuffle the address up to accomodate.
BTW due to interconnectivity requirements I can only use 172.16.16.0/22 as my cidr is why that's there, but that should still be plenty of space for a modest k8s cluster.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-08-09T16:12:51Z
  name: non-prod.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://gapinp-kops/non-prod.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  kubeAPIServer:
    authorizationRbacSuperUser: admin
    runtimeConfig:
      batch/v2alpha1: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.2
  masterInternalName: api.internal.non-prod.k8s.local
  masterPublicName: api.non-prod.k8s.local
  networkCIDR: 172.16.16.0/22
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.16.17.128/25
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.16.18.0/25
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.16.18.128/25
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.16.16.0/25
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.16.16.128/25
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.16.17.0/25
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

And any ELBs created by Service resources end up with the utility-eu-west-1a and utility-eu-west-1b subnets attached and the eu-west-1c attached instead of utility-eu-west-1c, and 1/3 of my requests fail :(
I've managed to get this working with a /26 but without understanding why it's breaking I'm still a little nervous about it breaking again on a /26.
