### ISSUE TITLE
Swap memory on nodes

### ISSUE THREAD

**Issue by gauravarora** [kubernetes/kops#3251]
We're running a kops created cluster for our dev environment. The cluster obviously does not need to be extremely performant. Unfortunately our service still require loads of memory to start up. Is it possible to ask nodes to configure swap space also on bootup?

**Comment by chrislovecnm** [comment]
Running swap with docker can be super problematic. Can you use spot instances instead to save $$?

**Comment by chrislovecnm** [comment]
To answer your question you can probably use a hook container to set swap, but u need another Ebs volume as well ;(

**Comment by gauravarora** [comment]
@chrislovecnm we're already using spot instance but 8-10 spot instances can add up quickly. This is a dev environment used maybe for 8 hours a day so spot was a no brainer.

Would you happen to have an example of how swap can be used via a hook container?

**Comment by thuandt** [comment]
@gauravarora use cloudinit

```
  additionalUserData:
  - name: swap.txt
    type: text/cloud-config
    content: |
      #cloud-config
      swap:
        filename: /swapfile
        size: 8589934592
```
