### ISSUE TITLE
volumetype == io1 is broken with the error "Iops is required for a provisioned IOPS volume"

### ISSUE THREAD

**Issue by navinkbe7** [kubernetes/kops#3278]
When we try to make the root volume of the nodes as io1 volume type , i get an error message ,
```
W0825 17:39:46.585143   87752 executor.go:109] error running task "LaunchConfiguration/nodes.xxxxxxxxxxxxxx" (7m16s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: Iops is required for a provisioned IOPS volume.
```

*How to reproduce :*
I followed `Changing the root volume size or type` section in the below link.
https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md

*Here is what we found,*
Changes I made to the instance-group is not persisting in the s3 state store. 
For example, 
1) Do a `kops edit ig --name $NAME nodes ` and then edit the volume type.

Here is my instancegroups/nodes.yaml 
```
piVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-08-25T22:34:03Z
  labels:
    kops.k8s.io/cluster: xxxxxxxxxxxxxxxxxxxxxxxxxx
  name: nodes
spec:
  associatePublicIp: false
  image: coreos.com/CoreOS-stable-1409.9.0-hvm
  machineType: m4.2xlarge
  maxSize: 3
  minSize: 3
  role: Node
  rootVolumeIops: 200
  rootProvisionedIops: 200
  rootVolumeSize: 200
  rootVolumeType: io1
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  tenancy: default
```
2) now do a `kops get ig --name $NAME nodes -o yaml` , changes you made is gone .

```
rootVolumeIops: 200
rootProvisionedIops: 200
```
are missing .

Think kops doesn't like `rootProvisionedIops` & `rootVolumeIops` even though the docs claim the other way .

*Kops version I am on,*
```
$ kops version
Version 1.7.0
```
