### ISSUE TITLE
cloudConfig ElbSecurityGroup gets overritten on each service deployment

### ISSUE THREAD

**Issue by Deshke** [kubernetes/kops#3309]
from https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#warning-this-works-only-for-kubernetes-version-above-170

if a service A is deployed with 

```yaml
apiVersion: v1
kind: Service
metadata:
....
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
```
the SG will be updated with the 80/tcp and a ICMP rule 

![bildschirmfoto vom 2017-08-29 15-51-31](https://user-images.githubusercontent.com/1473225/29824477-f3407906-8cd1-11e7-9f98-1e45cac9462a.png)

but if service B is also deployed 

```yaml
apiVersion: v1
kind: Service
metadata:
.....
spec:
  ports:
  - name: websocket
    port: 443
    targetPort: 4712
  - name: tcp
    port: 4713
    targetPort: 4713
```

the SG will be updated/replaced with 443/tcp and 4713/tcp and the 80/tcp from service A is missing from the SG making service A unreachable 

```bash
kops version
Version 1.7.0 (git-e04c29d)
```

```yaml
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2alpha1: "true"
      batch/v2alpha1: "true"
      cloudProvider: aws
  kubernetesVersion: 1.7.2
  cloudConfig:
    elbSecurityGroup: sg-123456789
```
