### ISSUE TITLE
hooks: not work "Found fields that are not recognized"

### ISSUE THREAD

**Issue by zioalex** [kubernetes/kops#3357]
I using the follow SW version :
```
bash-4.3# kops version
Version 1.7.0 (git-e04c29d)
```
and I tried to use the hooks as described in https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks .
Using the basic example:
```
  # or disable a systemd unit
  hooks:
  - name: update-engine.service
    disable: true
```
When I try to update the cluster config using the command:
kops --state s3://STATE_FILE edit cluster MY_SCLUSTER

I got
```
# Found fields that are not recognized
# ...
#       name: events
#     hooks:
# +   - disable: true
# +     name: update-engine.service
# -   - {}
#     kubernetesApiAccess:
#     - 0.0.0.0/0
# ...
#
#
```

no way to make it working.
