### ISSUE TITLE
Trouble creating custom ami with pre-pulled docker images

### ISSUE THREAD

**Issue by opensean** [kubernetes/kops#3378]
Hello,

```
kops version
Version 1.7.0 (git-e04c29d)
```

I attempted to create a custom ami to use with kops that has some pre-pulled docker images but ran into some issues.  
I took the following steps:
1.  Created an ec2 instance using the ```kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28``` ami and 20Gb ebs volume attached.  
2.  Pulled some docker images to the machine.  
3.  Stopped the instance and created a snapshot then registered it as an ami.  
4.  Created a new ec2 instance specifying the newly registered ami to confirm my docker images were present.  
5.  After confirmation I then edited my node ig spec to included the new image id and root volume information:

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-08-28T14:54:51Z
  labels:
    kops.k8s.io/cluster: scpdcluster.k8s.local
  name: nodes-t2-small-frontend
spec:
  image: REDACTED/k8s-1.7-debian-jessie-amd64-hvm-ebs-cst-01 # my new ami
  machineType: t2.small
  maxSize: 2
  minSize: 1
  nodeLabels:
    dedicated: frontend
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - us-east-1a

```
6.  run ```kops update cluster --yes```
7.  run ```kops rolling-update cluster --yes```

The nodes are started in the cluster using my ami and correct root volume size and type.  However,  when I ssh to the node and run ```sudo docker images``` my images are not longer present, I only see the usual kubernetes images:
```
REPOSITORY                                                       TAG                 IMAGE ID            CREATED             SIZE
quay.io/external_storage/efs-provisioner                         latest              b4da30527798        13 days ago         49.53 MB
gcr.io/google_containers/cluster-autoscaler                      v0.6.1              71a3e8b29e06        4 weeks ago         145 MB
protokube                                                        1.7.0               f1aefdb5580c        7 weeks ago         363.4 MB
gcr.io/google_containers/kube-proxy                              v1.7.2              13a7af96c7e8        7 weeks ago         114.7 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64                   1.14.4              38bac66034a6        11 weeks ago        41.81 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64                  1.14.4              a8e00546bcf3        11 weeks ago        49.38 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64             1.14.4              f7f45b9cb733        11 weeks ago        41.41 MB
gcr.io/google_containers/cluster-proportional-autoscaler-amd64   1.1.2-r2            7d892ca550df        3 months ago        49.64 MB
gcr.io/google_containers/pause-amd64                             3.0                 99e59f495ffa        16 months ago       746.9 kB
```

When a node is created in the cluster does something happen during provisioning that would cause my images to be removed?  

Thank you
