### ISSUE TITLE
Log rotation for containers running on master nodes

### ISSUE THREAD

**Issue by markine** [kubernetes/kops#3410]
We have kops 1.7 + Kuberenetes 1.7.2 running on AWS. I've configured the cluster ('kops edit cluster') with a docker stanza to enable log rotation on minions:

```
  docker:
    logDriver: json-file
    logOpt:
    - max-size=10m
    - max-file=5
```

Unfortunately this does not seem to have any effect on master nodes. E.g. I just spotted a 700M+ log file from a verbose app-under-test at /var/lib/docker/containers/XXXXXXXXX/XXXXXXXXX-json.log on a master node.

What's the best way to set up log rotation for containers on master nodes?
