### ISSUE TITLE
Error with "default machine type" while migrating from single to multi-master 

### ISSUE THREAD

**Issue by azman0101** [kubernetes/kops#3427]
While trying to [Migrating from single to multi-master](https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md)

I've this error at the step [Create new master instance group](https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md#a---create-new-master-instance-group)

```
kops create instancegroup --name=cluster.k8s.xxxx.host master-eu-central-1b --subnet eu-central-1b --role Master                                

error assigning default machine type for masters: error finding default machine type: subnet "eu-central-1b" is not defined in cluster
```

This "mix" of error messages is a bit confusing for me

Before that, the cluster was created like that:

`kops create cluster --cloud=aws --zones=eu-central-1a cluster.k8s.xxxxx.host --yes`

Then, I've convert the master to a spot instance

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-21T13:40:57Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.xxxxx.host
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: r4.large
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-central-1a
```
