### ISSUE TITLE
document alpha etcd3 support

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3475]
/assign @gambol99 
@gambol99 provided a correct example

**Comment by gambol99** [comment]
Hi @chrislovecnm ... near enough :-) I've taken the following snippets from our prod cluster.yaml. Both events and main must have version and tls enabled and yes the kube apiserver storage is handled for the user. I'll raise a PR this weekend with proper docs 

```YAML
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master0-az0
      name: a-1 
    - encryptedVolume: true
      instanceGroup: master1-az0
      name: a-2 
    - encryptedVolume: true
      instanceGroup: master2-az0
      name: a-3 
    - encryptedVolume: true
      instanceGroup: master0-az1
      name: b-1 
    - encryptedVolume: true
      instanceGroup: master1-az1
      name: b-2 
    enableEtcdTLS: true
    name: main
    version: 3.0.17
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master0-az0
      name: a-1 
    - encryptedVolume: true
      instanceGroup: master1-az0
      name: a-2 
    - encryptedVolume: true
      instanceGroup: master2-az0
      name: a-3 
    - encryptedVolume: true
      instanceGroup: master0-az1
      name: b-1 
    - encryptedVolume: true
      instanceGroup: master1-az1
      name: b-2 
    enableEtcdTLS: true
    name: events
    version: 3.0.17
```
