### ISSUE TITLE
rolling-update cluster always detects changes

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3516]
The cluster I was testing on was k8s 1.7.5 built with kops 1.7.0, upgraded to k8s 1.8.0 with kops 1.8.0-alpha.1

Every time I run `update cluster --yes` and `rolling-update cluster --yes` it restarts all instance groups (except bastions).

**Comment by blakebarnett** [comment]
I noticed this doesn't happen until I update the k8s version and do a rolling-update, after that it does it every time.

**Comment by chrislovecnm** [comment]
/assign @KashifSaadat 

Do you mind taking a look?

**Comment by KashifSaadat** [comment]
Hi @blakebarnett, I've tried testing this:
- kops, nodeup and protokube at v1.8.0-alpha.1 (official release)
- Build cluster on k8s v1.7.5, perform spec edit and then rolling-update to k8s v1.8.0

After the upgrade to k8s v1.8.0, the nodes rebuild as expected and come up clean. There are no additional changes detected on a following `kops update cluster` / `kops rolling-update cluster`.

Can you provide me with the cluster spec you are using, along with images (+region/description), any custom hooks etc.

**Comment by blakebarnett** [comment]
Here's the spec for the testing cluster I was seeing this on:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: e2e.us-east-1.aws.k8s
spec:
  api:
    loadBalancer:
      type: Public
  additionalPolicies:
    # kops 1.5.3+ requires adding this for zones not matching the cluster domain
    master: |
      [
        {
            "Effect": "Allow",
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:GetHostedZone"
            ],
            "Resource": [
                "arn:aws:route53:::hostedzone/XXXXXXXXXXX"
            ]
        },
        {
            "Action": [
                "firehose:Put*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:firehose:us-west-2:XXXXXXXXXXX:*"
        }
      ]
    node: |
      [
        {
            "Action": [
                "firehose:Put*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:firehose:us-west-2:XXXXXXXXXXX:*"
        }
      ]
  channel: alpha
  cloudProvider: aws
  clusterDNSDomain: e2e.us-east-1.aws.k8s
  configBase: s3://state-store/e2e.us-east-1.aws.k8s
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: master-us-east-1a
    - instanceGroup: master-us-east-1b
      name: master-us-east-1b
    - instanceGroup: master-us-east-1c
      name: master-us-east-1c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: master-us-east-1a
    - instanceGroup: master-us-east-1b
      name: master-us-east-1b
    - instanceGroup: master-us-east-1c
      name: master-us-east-1c
    name: events
  authorization:
    rbac: {}
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
    oidcCAFile: /srv/kubernetes/ca.crt
    oidcClientID: kubernetes
    oidcIssuerURL: https://dex.security.svc.e2e.us-east-1.aws.k8s:5556
    oidcGroupsClaim: groups
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.9
  masterInternalName: api.internal.e2e.us-east-1.aws.k8s
  masterPublicName: api.e2e.us-east-1.aws.k8s
  networkCIDR: 10.88.0.0/16
  networkID: vpc-xxxxxxxxxx
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.68.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  # 10.88.30.0/24 and 10.88.31.0/24 are allocated to VPN
  - name: master-us-east-1a
    type: Private
    zone: us-east-1a
    id: subnet-ae8989f4
    egress: nat-0befef9d43c2146d5
  - name: master-us-east-1b
    type: Private
    zone: us-east-1b
    id: subnet-edfd4b89
    egress: nat-0529214237644b5cb
  - name: master-us-east-1c
    type: Private
    zone: us-east-1c
    id: subnet-baa9a696
    egress: nat-02a60c47547d310db
  - name: utility-us-east-1a
    zone: us-east-1a
    type: Utility
    id: subnet-2c979876
  - name: utility-us-east-1b
    zone: us-east-1b
    type: Utility
    id: subnet-2a73c04e
  - name: utility-us-east-1c
    zone: us-east-1c
    type: Utility
    id: subnet-20b1bb0c
  - name: node-us-east-1a
    zone: us-east-1a
    type: Private
    id: subnet-6f898935
    egress: nat-0befef9d43c2146d5
  - name: node-us-east-1b
    zone: us-east-1b
    type: Private
    id: subnet-f4f74190
    egress: nat-0529214237644b5cb
  - name: node-us-east-1c
    zone: us-east-1c
    type: Private
    id: subnet-30aaa51c
    egress: nat-02a60c47547d310db
  topology:
    bastion:
      bastionPublicName: bastion.e2e.us-east-1.aws.k8s
    dns:
      type: Private
    masters: private
    nodes: private
  hooks:
    - execContainer:
        image: quay.io/postmates/alpine:3.5-iptables
        command: [ "iptables", "-t", "nat", "-A", "POSTROUTING", "-s", "172.16.0.0/12", "!", "-o", "br-+", "-j", "MASQUERADE" ]
```

Here's an example of the master/node instance groups:

```
# vim: set ft=yaml:
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: e2e.us-east-1.aws.k8s
  name: node-us-east-1a
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: m4.2xlarge
  maxSize: 6
  minSize: 1
  nodeLabels:
    environment: e2e
    cluster: e2e.us-east-1.aws.k8s
  role: Node
  rootVolumeSize: 80
  rootVolumeType: gp2
  subnets:
  - node-us-east-1a
```

```# vim: set ft=yaml:
apiVersion: kops/v1alpha1
kind: InstanceGroup
metadata:
  name: master-us-east-1a
  labels:
    kops.k8s.io/cluster: e2e.us-east-1.aws.k8s
spec:
  nodeLabels:
    environment: e2e
    cluster: e2e.us-east-1.aws.k8s
  associatePublicIp: false
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: m4.large
  maxSize: 1
  minSize: 1
  role: Master
  zones:
  - master-us-east-1a
```
