### ISSUE TITLE
kops edit cluster shows empty file (doesn't match what's in s3)

### ISSUE THREAD

**Issue by AnthonyWC** [kubernetes/kops#3526]
I created a new cluster on AWS where kops get cluster & kops get cluster -o=yaml works

```
kops get cluster -o=yaml

apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-10-02T20:54:04Z
  name: beta.example.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://K8-example/cluster/beta.example.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.2
  masterPublicName: api.beta.example.com
  networkCIDR: 172.17.0.0/16
  networkID: vpc-########
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.17.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

But 
```
kops edit cluster beta.example.com --state=s3://K8-example/cluster
Edit cancelled, no changes made.
```
Shows me an empty file despite that I have config files in S3.
