### ISSUE TITLE
Unable to use kubelet reserved resources

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3576]
`kops version`
- my dev branch, have not validated on the master, but I have not changed this code
- k8s version 1.8
- on ec2

I am getting the error from kubelet: `failed to run Kubelet: cannot reserve "storage" resource`
Here is the relevant cluster spec section that I am having problems with:

```yaml
  kubelet:
    kubeReserved:
        cpu: "100m"
        memory: "100Mi"
        storage: "1Gi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "100m"
        memory: "100Mi"
        storage: "1Gi"
    systemReservedCgroup: "/system-reserved"
    enforceNodeAllocatable: "pods,system-reserved,kube-reserved"
```

cluster is being created using kops create -f mycluster.yaml

Expected behavior is that the kubectl start using reserved resources.

**Comment by chrislovecnm** [comment]
may be a duplicate of https://github.com/kubernetes/kops/issues/3223

**Comment by chrislovecnm** [comment]
@itskingori @blakebarnett ideas?  #3223 recommends removing: ` enforceNodeAllocatable: "pods,system-reserved,kube-reserved"`

**Comment by jjo** [comment]
* Trying a `v1.7.7` ->  `v1.8.3` upgrade (alpha channel atm) with below kubelet stanza[0] fails on kubelet crashing with e.g.:
```
kubelet[2510]: error: failed to run Kubelet: cannot reserve "storage" resource
```
* Removing `storage` lines (harmless for us as we're only handling cpu and memory resources lets `kubelet` run ok [1](for completeness)

* [0] FAIL
```
  kubelet:
    kubeReserved:
        cpu: "100m"
        memory: "192Mi"
        storage: "1Gi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "100m"
        memory: "256Mi"
        storage: "1Gi"
    systemReservedCgroup: "/system-reserved"
    enforceNodeAllocatable: "pods"
```
* [1] OK
```
  kubelet:
    kubeReserved:
        cpu: "100m"
        memory: "192Mi"
    kubeReservedCgroup: "/kube-reserved"
    systemReserved:
        cpu: "100m"
        memory: "256Mi"
    systemReservedCgroup: "/system-reserved"
    enforceNodeAllocatable: "pods"
```

**Comment by itskingori** [comment]
@chrislovecnm @jjo [quoting myself](https://github.com/kubernetes/kops/issues/3223#issuecomment-346753054) here ... these flags were mapped so that anyone who wants to use them can use them but Kops does not apply any defaults that don't work. You need the cgroups already present though (maybe I should have added that caveat in the Kops docs - they are in the Kubernetes docs though). See https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/.

@jjo when you set `enforceNodeAllocatable: "pods"` ... that is going back to Kops default behaviour ... which means allocatable is only looking at pods and none of the other two. Setting `enforceNodeAllocatable: "pods,system-reserved,kube-reserved"` tells Kubernetes to factor in all three in the allocatable resources calculation. I think the issue here is we need to have the cgroups created (as linked in my other comment, kubelet does not create them).

**Comment by blakebarnett** [comment]
We should follow the best-practices for cgroups in the base image and have the docs be able to work by default: https://github.com/kubernetes/kops/issues/3762

**Comment by rlees85** [comment]
I think @jjo has found a bug, maybe not in Kops but Kubernetes at least.

Similar thing happened to me, I upgraded from `1.7.11` -> `1.8.4` and now the kubelets fail to start.

Error:
```
Dec 04 10:49:11 ip-10-0-11-39 kubelet[15316]: error: failed to run Kubelet: cannot reserve "storage" resource
```

Kops config:
```
  kubelet:
    evictionHard: memory.available<256Mi,nodefs.available<5%,nodefs.inodesFree<5%,imagefs.available<5%,imagefs.inodesFree<5%
    kubeReserved:
        cpu: "100m"
        memory: "512Mi"
        storage: "1Gi"
    systemReserved:
        cpu: "100m"
        memory: "768Mi"
        storage: "1Gi"
    enforceNodeAllocatable: "pods"
```

Notice: No CGROUPS so this is not related to the appropriate cgroups not being present.

**Comment by blakebarnett** [comment]
According to https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#example-scenario it's `ephemeral-storage` not `storage`, maybe the key is wrong in kops?  I'll take a look when I get a chance.

**Comment by itskingori** [comment]
@blakebarnett seems like that's a K8s 1.7 vs 1.8 change. In the [1.7 docs][1] it's `storage`. Haven't looked at the code though to verify if it was just the docs that were changed or the code as well.

<img width="700" alt="screen shot 2017-12-05 at 06 20 13" src="https://user-images.githubusercontent.com/703786/33606792-6732aa2e-d984-11e7-888d-97a7a83488ba.png">

[1]: https://v1-7.docs.kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#example-scenario

**Comment by rlees85** [comment]
No, not filed upstream as of yet. I am bit new to Kubernetes & Kops and felt I better make sure more qualified people were sure it wasn't a Kops bug before doing so.

Looks like Kubernetes have changed the storage key name hence the problems

**Comment by rlees85** [comment]
@blakebarnett did you get chance to check the keys in Kops as it does seem like the keys could have changed for k8s 1.8

**Comment by blakebarnett** [comment]
kubeReserved is working fine for me, but there are some issues with systemReserved, I think it's with the build of systemd in the kops image we use by default.  Possibly updating to stretch will solve it but I haven't had a chance to test it thoroughly.

**Comment by snoby** [comment]
There are lots of different issues that attempt to show a user of kops how to set this up:
* https://github.com/kubernetes/kops/issues/3762
* https://github.com/kubernetes/kops/issues/3223
* https://github.com/kubernetes/kops/issues/1869

Main document section:
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#compute-resources-reservation

I think it's clear that this is not very well documented nor understood.  Can we get a verified working unit test at least?

**Comment by chrislovecnm** [comment]
@blakebarnett can you share your setup from at least the kops side, and I am not certain what you have done to create the needed cgroups.

**Comment by blakebarnett** [comment]
This is essentially it: https://github.com/kubernetes/kops/issues/3762#issuecomment-356478668

**Comment by snoby** [comment]
I agree however I don't think it's that simple.  I've taken the comments in #3762 as below and my kubelet doesn't start. Hence my request for a unit test that has this implemented.
```
Failed to start Kubernetes systemd probe.
Mar 16 19:43:05 ip-10-231-118-66 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Mar 16 19:43:05 ip-10-231-118-66 systemd[1]: Unit kubelet.service entered failed state.
Mar 16 19:43:07 ip-10-231-118-66 systemd[1]: kubelet.service holdoff time over, scheduling restart.
```

Here is what part of the cluster spec looks like that causes above:
```
  fileAssets:
  - content: |
      {
          "kind": "Config",
          "apiVersion": "v1",
          "preferences": {},
          "clusters": [
              {
                  "name": "github-authn",
                  "cluster": {
                      "server": "http://localhost:3000/authenticate"
                  }
              }
          ],
          "users": [
              {
                  "name": "authn-apiserver",
                  "user": {
                      "token": "secret"
                  }
              }
          ],
          "contexts": [
              {
                  "name": "webhook",
                  "context": {
                      "cluster": "github-authn",
                      "user": "authn-apiserver"
                  }
              }
          ],
          "current-context": "webhook"
      }
    name: github-authn
    path: /srv/kubernetes/webhook-authn
    roles:
    - Master
    - Node
  - content: |
      [Unit]
      Description=Limited resources slice for Kubernetes services
      Documentation=man:systemd.special(7)
      DefaultDependencies=no
      Before=slices.target
      Requires=-.slice
      After=-.slice
    name: podruntime-slice
    path: /usr/lib/systemd/system/podruntime.slice
  - content: |
      [Unit]
      Description=Limited resources slice for system services
      Documentation=man:systemd.special(7)
      DefaultDependencies=no
      Before=slices.target
      Requires=-.slice
      After=-.slice
    name: system-slice
    path: /usr/lib/systemd/system/system.slice
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authenticationTokenWebhookCacheTtl: 5m0s
    authenticationTokenWebhookConfigFile: /srv/kubernetes/webhook-authn
    runtimeConfig:
      batch/v2alpha1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerDownscaleDelay: 5m0s
    horizontalPodAutoscalerSyncPeriod: 15s
    horizontalPodAutoscalerUpscaleDelay: 3m0s
  kubelet:
    enforceNodeAllocatable: pods,kube-reserved,system-reserved
    evictionHard: memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    kubeReserved:
      cpu: 750m
      memory: 1.3Gi
    kubeReservedCgroup: /podruntime.slice
    kubeletCgroups: /podruntime.slice
    runtimeCgroups: /podruntime.slice
    systemReserved:
      cpu: 500m
      memory: 750Mi
    systemReservedCgroup: /system.slice
  kubernetesApiAccess:
  - 10.0.0.0/8
  kubernetesVersion: 1.9.4
  masterInternalName: api.internal.east-prod.k8s.tropo.com
  masterKubelet:
    kubeletCgroups: /podruntime.slice
    runtimeCgroups: /podruntime.slice
  masterPublicName: api.east-prod.k8s.tropo.com
  networkCIDR: 10.231.0.0/16
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
```

**Comment by rlees85** [comment]
Strange... even setting `storage` on just `kubeReserved` stops kubelet from starting for me...


Snippet:
```
  kubelet:
    evictionHard: memory.available<256Mi,nodefs.available<5%,nodefs.inodesFree<5%,imagefs.available<5%,imagefs.inodesFree<5%
    kubeReserved:
        cpu: "100m"
        memory: "256Mi"
        storage: "1Gi"
    systemReserved:
        cpu: "100m"
        memory: "768Mi"
#       storage: "1Gi"     - Commented out due to K8S v1.8 issue https://github.com/kubernetes/kops/issues/3576
    enforceNodeAllocatable: "pods"
```

Using the debian stretch image. Not sure how it could be systemd related as I am not using any of the cgroup stuff at all as of yet

**Comment by blakebarnett** [comment]
To be clear, I don't use `systemReserved` and I don't specify `storage` for the reasons mentioned.

**Comment by rlees85** [comment]
OK so I just realised KOPS passes the map key/values directly through, so the fix for my and @jjo problem is very simple

```
    kubeReserved:
        cpu: "100m"
        memory: "256Mi"
        ephemeral-storage: "1Gi"
    systemReserved:
        cpu: "100m"
        memory: "768Mi"
        ephemeral-storage: "1Gi"
    enforceNodeAllocatable: "pods"
```

No idea where I got `storage:` from originally or why it worked for K8S 1.7. Either way, I apologise for re-opening this issue and I think it is completely separate to the cgroup stuff in other discussions. I'm out :) I hope this helps anyone who finds themselves with the same problem as me or @jjo.
