### ISSUE TITLE
error building tasks: unhandled LoadBalancer type "Private"

### ISSUE THREAD

**Issue by airstand** [kubernetes/kops#3613]
Hey guys,

I faced an issue while creating cluster with private api loadbalancer.

kops Version 1.8.0-alpha.1 (git-991cd8c)

```
spec:
  api:
    loadBalancer:
      type: Private
....
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

```
kops update cluster

error building tasks: unhandled LoadBalancer type "Private"
```

//cc @justinsb @chrislovecnm
