### ISSUE TITLE
Terraform is missing bastion elb route 53 entry

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3618]
I may be wrong, but I think we should have a bastion elb dns entry with a kops cluster like:

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2016-12-12T04:13:14Z"
  name: privateweave.example.com
spec:
  kubernetesApiAccess:
  - 0.0.0.0/0
  channel: stable
  cloudProvider: aws
  configBase: memfs://clusters.example.com/privateweave.example.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-test-1a
      name: us-test-1a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-test-1a
      name: us-test-1a
    name: events
  kubernetesVersion: v1.4.12
  masterInternalName: api.internal.privateweave.example.com
  masterPublicName: api.privateweave.example.com
  networkCIDR: 172.20.0.0/16
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  topology:
    masters: private
    nodes: private
  subnets:
  - cidr: 172.20.32.0/19
    name: us-test-1a
    type: Private
    zone: us-test-1a
  - cidr: 172.20.4.0/22
    name: utility-us-test-1a
    type: Utility
    zone: us-test-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2016-12-12T04:13:15Z"
  name: master-us-test-1a
  labels:
    kops.k8s.io/cluster: privateweave.example.com
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-test-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2016-12-12T04:13:15Z"
  name: nodes
  labels:
    kops.k8s.io/cluster: privateweave.example.com
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-test-1a


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2016-12-14T15:32:41Z"
  name: bastion
  labels:
    kops.k8s.io/cluster: privateweave.example.com
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-us-test-1a

```

2. What kops version are you running? use `kops version`

master

3. What Kubernetes version are you running? use `kubectl version`

n/a

4. What cloud provider are you using?

AWS

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?

running update cluster with output of tf and phase cluster (should be elb phase)

6. What you expected to happen:

a TF record like 

```
resource "aws_route53_record" "api-privateweave-example-com" {
  name = "api.privateweave.example.com"
  type = "A"

  alias = {
    name                   = "${aws_elb.api-privateweave-example-com.dns_name}"
    zone_id                = "${aws_elb.api-privateweave-example-com.zone_id}"
    evaluate_target_health = false
  }

  zone_id = "/hostedzone/Z1AFAKE1ZON3YO"
}
```
is outputted for the bastion elb as well
