### ISSUE TITLE
fileAssets do not work for me

### ISSUE THREAD

**Issue by carldanley** [kubernetes/kops#3645]
What kops version are you running? `1.7.0`
What Kubernetes version are you running? `1.8.0-alpha.1`
What cloud provider are you using? `AWS`

I am trying to create a cluster that uses webhook authentication. I have specified the following:

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: {{DATE}}
  labels:
    kops.k8s.io/cluster: {{DOMAIN}}
  name: master-us-east-1a
spec:
  image: {{EC2_IMAGE}}
  machineType: {{MASTER_INSTANCE_TYPE}}
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: {{MASTER_DISK_SIZE}}
  subnets:
  - {{SUBNET_PRIVATE_US_EAST_1A_NAME}}
  fileAssets:
  - name: authentication.yaml
    path: /mnt/webhook-authentication.yaml
    roles: [Master]
    content: |
      clusters:
      - name: authentication-server
        cluster:
          server: "http://127.0.0.1:30089"
      users:
      - name: kube-apiserver
      current-context: webhook
      contexts:
      - context:
          cluster: authentication-server
          user: kube-apiserver
        name: webhook
```

The yaml above is used to generate a working kops configuration. My scripts run and the cluster comes up but it will not write the file. Keep in mind that everything else I tweak in the spec's works correctly. Initially, I thought this was an issue with the pathing not having the subdirectories necessary to write the file; upon further investigation, I found out that it's not writing regardless of the path I use. I'm going to keep experimenting with this until I get it working correctly.

**Comment by carldanley** [comment]
cc: @chrislovecnm @KashifSaadat

**Comment by chrislovecnm** [comment]
Btw you can just rerun nodeup in order to test this.  kops update will change the manifest in the state store.  I would run nodeup with -v=10 as well

**Comment by carldanley** [comment]
Sorry not familiar with where to run `nodeup`. Do you have an example of this?

**Comment by chrislovecnm** [comment]
```
sudo SKIP_PACKAGE_UPDATE=1 /var/lib/toolbox/kubernetes-install/nodeup --conf=/var/lib/toolbox/kubernetes-install/kube_env.yaml --v=8
```

Run on the node ... if the file location of nodeup is not correct grep the logs.  You may want to check to see if `/var/lib/toolbox/kubernetes-install/kube_env.yaml` is being updated.   

If that does not work.  `kops replace -f mycluster.yaml` then `kops update cluster --yes` then delete a node in the asg in aws.  That way you do not have to kill the entire cluster.

**Comment by carldanley** [comment]
@chrislovecnm My `/var/lib` folder contains:

```
apt	   dockershim	    insserv		     kube-proxy      nfs     systemd
cloud	   dpkg		    kops		     kube-scheduler  ntp     ucf
container  git		    kube-controller-manager  logrotate	     pam     update-rc.d
dhcp	   initramfs-tools  kubectl		     man-db	     python  urandom
docker	   initscripts	    kubelet		     misc	     sudo    vim
```

I grepped logs for:
1. `/var/log/kube-apiserver.log`
1. `/var/log/kube-controller-manager.log`
1. `/var/log/kube-proxy.log`
1. `/var/log/kube-scheduler.log`

Could not find anything mentioning `nodeup` - what am I missing?

**Comment by chrislovecnm** [comment]
/var/log/daemon.log :)  There is a service that creates it ... let me see if I can find the code

**Comment by carldanley** [comment]
Ah, found it at `/var/cache/kubernetes-install` - debugging now

**Comment by carldanley** [comment]
My `/var/cache/kubernetes-install/kube_env.yaml` looks like this:

```
Assets:
- a9c8695a66a6479b64eb024b654fe7b0d49806e6@https://storage.googleapis.com/kubernetes-release/release/v1.8.0-alpha.1/bin/linux/amd64/kubelet
- a2250d7feba3ab7819f42d4a465ea2faf8e43914@https://storage.googleapis.com/kubernetes-release/release/v1.8.0-alpha.1/bin/linux/amd64/kubectl
- 1d9788b0f5420e1a219aad2cb8681823fc515e7c@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
- 5d95d64d7134f202ba60b1fa14adaff138905d15@https://kubeupv2.s3.amazonaws.com/kops/1.7.0/linux/amd64/utils.tar.gz
ClusterName: [redacted]
ConfigBase: s3://[redacted]
InstanceGroupName: master-us-east-1c
Tags:
- _automatic_upgrades
- _aws
- _kubernetes_master
- _networking_cni
channels:
- s3://[redacted]/addons/bootstrap-channel.yaml
protokubeImage:
  hash: 5bd97a02f0793d1906e9f446c548ececf1444737
  name: protokube:1.7.0
  source: https://kubeupv2.s3.amazonaws.com/kops/1.7.0/images/protokube.tar.gz
```

Would I just update the file in the s3 bucket and then manually run that command to test or?
