### ISSUE TITLE
Advanced Audit Log Configuration

### ISSUE THREAD

**Issue by brosander** [kubernetes/kops#3672]
I'm a new kops user and am really enjoying it so far!

One area I'm not sure how to address currently within kops directly is audit logging.

I think I've configured it as much as I can currently within kops based on [the cluster spec doc](https://github.com/kubernetes/kops/blob/1.7.0/docs/cluster_spec.md#audit-logging):
```
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
```

[Kubernetes provides advanced audit configuration options.](https://v1-7.docs.kubernetes.io/docs/tasks/debug-application-cluster/audit/#advanced-audit)

It would be nice to be able to define an audit policy through kops to specify different levels of audit logging based on how sensitive the operation is.

It could be inline or a separate secret or file.

As far as I can tell I should be able to patch the container command for the api server to add my own flag to a host mount or config map but I would expect to have to redo that every time I update the cluster.

Sorry in advance for any newbishness or if I've missed a better way to accomplish this. :smile:
