### ISSUE TITLE
FeatureGates support in all the components

### ISSUE THREAD

**Issue by diegows** [kubernetes/kops#3773]
-------------FEATURE REQUEST --------------------

featureGates are supported in KubeletConfigSpec and KubeProxyConfig only. It should be supported in KubeAPIServerConfig, KubeControllerManagerConfig and KubeSchedulerConfig.

**Comment by diegows** [comment]
Tried with this but no luck after building it.

https://github.com/flugel-it/kops/commit/550924748837c65d2dabcf6a39b12a63b97a54f9

**Comment by chrislovecnm** [comment]
Take a look at this documentation https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md

You need to update two more files and generate API machinery.

**Comment by diegows** [comment]
Still no luck :(

https://github.com/flugel-it/kops/commit/eff369bb7104e51fc3564649cc6778cb48c22c96

**Comment by chrislovecnm** [comment]
Need more details

**Comment by diegows** [comment]
Sorry. After that last commit, I can build kops without issues, "kops edit cluster..." works and saves the changes, but "kops update cluster..." doesn't add --feature-gates to api, scheduler and controller manager. I'm able to create the cluster, but it's not enabling the feature gates.

**Comment by chrislovecnm** [comment]
Does kops get cluster -o yaml show the updates after you edit?

**Comment by diegows** [comment]
Yes.

```
diegows@diegows-laptop:~/kops/bin$ ./kops get cluster -o yaml | grep -A 1 -B 1 featureGates
  kubeAPIServer:
    featureGates:
      PersistentLocalVolumes: "true"
  kubeControllerManager:
    featureGates:
      PersistentLocalVolumes: "true"
  kubeScheduler:
    featureGates:
      PersistentLocalVolumes: "true"
  kubelet:
    featureGates:
      PersistentLocalVolumes: "true"
```
