### ISSUE TITLE
etcd version and enableEtcdTLS being ignored in cluster spec

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3812]
Kops: `Version 1.8.0-beta.1 (git-2c0e5be87)`
K8s version: 1.8.2
Provider: AWS

My etcdClusters spec:
```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: master-us-east-1a
    - instanceGroup: master-us-east-1b
      name: master-us-east-1b
    - instanceGroup: master-us-east-1c
      name: master-us-east-1c
    name: main
    enableEtcdTLS: false
    version: 3.0.17
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: master-us-east-1a
    - instanceGroup: master-us-east-1b
      name: master-us-east-1b
    - instanceGroup: master-us-east-1c
      name: master-us-east-1c
    name: events
    enableEtcdTLS: false
    version: 3.0.17
```

If I check the `cluster.spec` in S3 after updating with this configuration the fields `version` and `enableEtcdTLS` are missing.  The cluster creation silently just uses etcd v2.

**Comment by chrislovecnm** [comment]
This is working fine for me
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-29T01:53:32Z
  name: us-west-2.aws.example.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: alpha
  cloudProvider: aws
  clusterDNSDomain: us-west-2-cluster.local
  configBase: s3://aws.example.com/us-west-2.aws.example.com
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-west-2c
      name: d
    name: main
    version: 3.0.17
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-west-2c
      name: d
    name: events
    version: 3.0.17
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.2
  masterPublicName: api.us-west-2.aws.example.com
  networkCIDR: 172.60.0.0/16
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.60.0.0/24
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**Comment by chrislovecnm** [comment]
@KashifSaadat so the one thing that I can recreate is that when you set `enableEtcdTLS` to false it is dropped from the manifest.

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-29T01:53:32Z
  name: us-west-2.aws.example.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: alpha
  cloudProvider: aws
  clusterDNSDomain: us-west-2-cluster.local
  configBase: s3://aws.k8spro.com/us-west-2.aws.example.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2c
      name: d
    name: main
    version: 3.0.17
  - etcdMembers:
    - instanceGroup: master-us-west-2c
      name: d
    name: events
    version: 3.0.17
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.2
  masterPublicName: api.us-west-2.aws.example.com
  networkCIDR: 172.60.0.0/16
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.60.0.0/24
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
