### ISSUE TITLE
Support kube-router in kubernetes 1.8

### ISSUE THREAD

**Issue by igorcalabria** [kubernetes/kops#3821]
2. What kops version are you running? use `kops version`
`Version 1.8.0-alpha.1 (git-991cd8c)`

3. What Kubernetes version are you running? use `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

4. What cloud provider are you using?
AWS

Kubernetes 1.8 removed the `pod.beta.kubernetes.io/init-containers` annotation. The effect on kube-router daemonset is that the config file is not dropped in `/etc/cni/net.d`, kubelet fails to init the network and node is never marked as ready. The solution is pretty simple, just move the annotation to the new `initContainers` spec. 

```
    spec:
      initContainers:
        - name: install-cni
          image: busybox
          command: [ "/bin/sh", "-c", "set -e -x; if [ ! -f /etc/cni/net.d/10-kuberouter.conf ]; then TMP=/etc/cni/net.d/.tmp-kuberouter-cfg; cp /etc/kube-router/cni-conf.json ${TMP}; mv ${TMP} /etc/cni/net.d/10-kuberouter.conf; fi" ]
          volumeMounts:
          - mountPath: /etc/cni/net.d
            name: cni
          - mountPath: /etc/kube-router
            name: kube-router-cfg
```
