### ISSUE TITLE
Example incorrect for AdditionalUserData in IGs

### ISSUE THREAD

**Issue by dgem** [kubernetes/kops#3853]
Hi,

I was testing out the support for additional user data in cloud-init for instance groups when I found that using the example given didn't appear to work.

The [example given in the docs](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#additional-user-data-for-cloud-init) appears to have an incorrect field name: `ExtraUserData`

The correct field name according to the [go docs](https://godoc.org/k8s.io/kops/pkg/apis/kops#InstanceGroupSpec) is `AdditionalUserData`.

An amended version of the example reads:
```yaml
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "Hello World.  The time is now $(date -R)!" | tee /root/output.txt
  - name: local_repo.txt
    type: text/cloud-config
    content: |
      #cloud-config
      apt:
        primary:
          - arches: [default]
            uri: http://local-mirror.mydomain
            search:
              - http://local-mirror.mydomain
              - http://archive.ubuntu.com
```
