### ISSUE TITLE
Need to be able to use --target with -f

### ISSUE THREAD

**Issue by iMartyn** [kubernetes/kops#3900]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
kops 1.7.0 and kops 1.7.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
1.7.8 or 1.7.10

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
`kops create -f kops.yaml --target terraform --out terrraform_out`

5. What happened after the commands executed?
Error: unknown flag: --target

6. What did you expect to happen?
Create the terraform from the yaml.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-11-01T12:02:57Z
  name: preprod.redacted
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Environment: Preprod
    Group: Kubernetes
    Squad: Staging
    Tribe: Platform
  cloudProvider: aws
  configBase: s3://bucket/folder
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.8
  masterInternalName: <<redacted>>
  masterPublicName: <<redacted>>
  networkCIDR: 172.22.0.0/16
  networking:
    flannel: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.22.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.22.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.22.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.22.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.22.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.22.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    bastion:
      bastionPublicName: bastion.<<redacted>>
    dns:
      type: Public
    masters: private
    nodes: private
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
To create a cluster that has lifecycle hooks (e.g. for sssd installation and configuration) we have to add to the yaml that is created, and that can only be done when passing a yaml.  We output to terraform as we need to augment to enable peering etc on our legacy infrastructure and we use terraform for our legacy infrastructure.
