### ISSUE TITLE
Attach additional security group rules shouldn't required and terminate instances

### ISSUE THREAD

**Issue by pandeybk** [kubernetes/kops#3909]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
 kops version
Version 1.7.1 (git-c69b811)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops edit ig and add following 

```
spec:
  additionalSecurityGroups:
  - sg-group-id
```

`kops update cluster <cluster-name> --yes
`
Above command says it required rolling-update

`kops rolling-update cluster <cluster-name> --yes
`
5. What happened after the commands executed?
Rolling update actually terminate the instances to add new SG. 

6. What did you expect to happen?
Adding SG shouldn't required instances to terminate. 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-06T20:31:20Z
  labels:
    kops.k8s.io/cluster: dev-k8s.dev-domain.net
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-sasasa
  - sg-sas212a
  image: ami-ddasdas
  machineType: m4.4xlarge
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
```
