### ISSUE TITLE
Upgrade K8s 1.7.10 to 1.8.2 w/ RBAC and working Calico 2.6.2

### ISSUE THREAD

**Issue by bgeesaman** [kubernetes/kops#3910]
0. What were you trying to do?
Get 1.8.x K8s running with RBAC and native egress NetworkPolicy with Calico to be able to block access to the Kubelet API, Dashboard, Various metrics endpoints, and EC2 Metadata API to prevent certain attacks.

1. What `kops` version are you running? kops-1.8.0-beta.1

2. What Kubernetes version are you running? 1.7.10 -> 1.8.2

3. What cloud provider are you using? AWS
 
4. What commands did you run?

   1. Create the cluster
    ```
    $ ./kops create cluster --name mydnsname --state s3://mybucket --zones us-east-1d --networking calico
    ```

   2.  Edit the cluster spec: (manually change k8s version from ```1.7.10``` -> ```1.8.2``` and authorizationMode from ```alwaysallow: {}``` to ```rbac: {}```)
    ```
     $ ./kops edit cluster --state s3://mybucket/
    ```

What changed during the ```edit```
```
Using cluster from kubectl context: kube.lonimbus.com

W1126 07:33:53.621184   45558 firewall.go:221] Opening etcd port on masters for access from the nodes, for calico.  This is unsafe in untrusted environments.
I1126 07:33:53.622607   45558 executor.go:91] Tasks: 0 done / 75 total; 33 can run
I1126 07:33:54.826644   45558 executor.go:91] Tasks: 33 done / 75 total; 24 can run
I1126 07:33:55.546785   45558 executor.go:91] Tasks: 57 done / 75 total; 16 can run
I1126 07:33:55.926735   45558 executor.go:91] Tasks: 73 done / 75 total; 2 can run
I1126 07:33:55.991321   45558 executor.go:91] Tasks: 75 done / 75 total; 0 can run
Will modify resources:
  LaunchConfiguration/master-us-east-1d.masters.kube.lonimbus.com
  	UserData            
  	                    	...
  	                    	    - max-file=5
  	                    	    storage: overlay,aufs
  	                    	+   version: 1.13.1
  	                    	-   version: 1.12.6
  	                    	  kubeAPIServer:
  	                    	    address: 127.0.0.1
  	                    	...
  	                    	    - DefaultTolerationSeconds
  	                    	    - NodeRestriction
  	                    	+   - Priority
  	                    	    - ResourceQuota
  	                    	    allowPrivileged: true
  	                    	    anonymousAuth: false
  	                    	    apiServerCount: 1
  	                    	+   authorizationMode: RBAC
  	                    	-   authorizationMode: AlwaysAllow
  	                    	    cloudProvider: aws
  	                    	    etcdServers:
  	                    	...
  	                    	    etcdServersOverrides:
  	                    	    - /events#http://127.0.0.1:4002
  	                    	+   image: gcr.io/google_containers/kube-apiserver:v1.8.2
  	                    	-   image: gcr.io/google_containers/kube-apiserver:v1.7.10
  	                    	    insecurePort: 8080
  	                    	    kubeletPreferredAddressTypes:
  	                    	...
  	                    	    clusterName: kube.lonimbus.com
  	                    	    configureCloudRoutes: false
  	                    	+   image: gcr.io/google_containers/kube-controller-manager:v1.8.2
  	                    	-   image: gcr.io/google_containers/kube-controller-manager:v1.7.10
  	                    	    leaderElection:
  	                    	      leaderElect: true
  	                    	...
  	                    	    featureGates: null
  	                    	    hostnameOverride: '@aws'
  	                    	+   image: gcr.io/google_containers/kube-proxy:v1.8.2
  	                    	-   image: gcr.io/google_containers/kube-proxy:v1.7.10
  	                    	    logLevel: 2
  	                    	  kubeScheduler:
  	                    	+   image: gcr.io/google_containers/kube-scheduler:v1.8.2
  	                    	-   image: gcr.io/google_containers/kube-scheduler:v1.7.10
  	                    	    leaderElection:
  	                    	      leaderElect: true
  	                    	...
  	                    	  cat > kube_env.yaml << '__EOF_KUBE_ENV'
  	                    	  Assets:
  	                    	+ - 2f6ec469e61125a837ad447cab012600ef08f0b2@https://storage.googleapis.com/kubernetes-release/release/v1.8.2/bin/linux/amd64/kubelet
  	                    	- - 4d38bdc8e850c05103348cee2cbffbddce62bcf8@https://storage.googleapis.com/kubernetes-release/release/v1.7.10/bin/linux/amd64/kubelet
  	                    	+ - 20f145a084a7afc80569f5852cc1bcd377e0e562@https://storage.googleapis.com/kubernetes-release/release/v1.8.2/bin/linux/amd64/kubectl
  	                    	- - 4c174128ad3657bb09c5b3bd4a05565956b44744@https://storage.googleapis.com/kubernetes-release/release/v1.7.10/bin/linux/amd64/kubectl
  	                    	  - 1d9788b0f5420e1a219aad2cb8681823fc515e7c@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
  	                    	  - 0b35723531ae917ec593a82753ea6e244ece354e@https://kubeupv2.s3.amazonaws.com/kops/1.8.0-beta.1/linux/amd64/utils.tar.gz
  	                    	...
  	                    	

  LaunchConfiguration/nodes.kube.lonimbus.com
  	UserData            
  	                    	...
  	                    	    - max-file=5
  	                    	    storage: overlay,aufs
  	                    	+   version: 1.13.1
  	                    	-   version: 1.12.6
  	                    	  kubeProxy:
  	                    	    clusterCIDR: 100.96.0.0/11
  	                    	...
  	                    	    featureGates: null
  	                    	    hostnameOverride: '@aws'
  	                    	+   image: gcr.io/google_containers/kube-proxy:v1.8.2
  	                    	-   image: gcr.io/google_containers/kube-proxy:v1.7.10
  	                    	    logLevel: 2
  	                    	  kubelet:
  	                    	...
  	                    	  cat > kube_env.yaml << '__EOF_KUBE_ENV'
  	                    	  Assets:
  	                    	+ - 2f6ec469e61125a837ad447cab012600ef08f0b2@https://storage.googleapis.com/kubernetes-release/release/v1.8.2/bin/linux/amd64/kubelet
  	                    	- - 4d38bdc8e850c05103348cee2cbffbddce62bcf8@https://storage.googleapis.com/kubernetes-release/release/v1.7.10/bin/linux/amd64/kubelet
  	                    	+ - 20f145a084a7afc80569f5852cc1bcd377e0e562@https://storage.googleapis.com/kubernetes-release/release/v1.8.2/bin/linux/amd64/kubectl
  	                    	- - 4c174128ad3657bb09c5b3bd4a05565956b44744@https://storage.googleapis.com/kubernetes-release/release/v1.7.10/bin/linux/amd64/kubectl
  	                    	  - 1d9788b0f5420e1a219aad2cb8681823fc515e7c@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
  	                    	  - 0b35723531ae917ec593a82753ea6e244ece354e@https://kubeupv2.s3.amazonaws.com/kops/1.8.0-beta.1/linux/amd64/utils.tar.gz
  	                    	...                    	
```

   5.  Apply the changes
     ```
     $ ./kops update cluster --state s3://mybucket/ --yes
     $ ./kops rolling-update cluster --state s3://mybucket/ --yes
     ```

   6.  Hand edit calico policy deployment: (manually change ```v0.7.0``` -> ```v1.0.0-rc4```)
    ```
    $ kubectl edit deployment calico-policy-controller -n kube-system
    ```

   7.  Hand edit calico node daemonset: (manually change ```v2.4.1``` -> ```v2.6.2```)
    ```
    $ kubectl edit daemonset calico-node -n kube-system
    ```

   8.  Install RBAC as per their docs
    ```
    $ kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/rbac.yaml
    ```

5. What happened after the commands executed?
The cluster was upgraded to ```1.8.2```, then calico was upgraded to ```1.0/2.6.2```.  Then applying a ```networkpolicy``` like this works to block egress traffic except DNS lookups:

```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: default
spec:
  podSelector: {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
  - ports:
    - protocol: UDP
      port: 53
  policyTypes:
  - Ingress
  - Egress
```

/cc @chrislovecnm

**Comment by chrislovecnm** [comment]
So does this work?

**Comment by bgeesaman** [comment]
It works, yes, but my definition of “works” is probably not as far reaching as you’d like.  Pods launch, they can see each other, I can kubectl exec/logs, I can add/remove network policies and the Calico logs seem clean during that process.

That said, what test harness can I run to be a bit more thorough in my definition of “it works”?

**Comment by chrislovecnm** [comment]
So I usually test with the go guestbook under examples. If you want to get serious about it, you need to run the e2e test suite.

These instructions may be dated https://github.com/kubernetes/kops/blob/master/docs/development/testing.md

Also, please test 1.8.2, and not 1.9.x.

**Comment by chrislovecnm** [comment]
./hack/ginkgo-e2e.sh --ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort --report-dir=/workspace/_artifacts --disable-log-dump=true

This command I think is in the Kubernetes/Kubernetes project - been awhile since I ran e2e

Is the magic command to run e2e, but I am probably missing some env variables. I am digging the commands out of https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/3920/pull-kops-e2e-kubernetes-aws/4193/build-log.txt

This is a build log for one of our e2e runs.

**Comment by bgeesaman** [comment]
1. Performed the above again installation/in-place-upgrade successfully.
2. Installed the guestbook-go from [here](https://github.com/kubernetes/examples/tree/master/guestbook-go)
3. Hit via ELB-hostname:3000, added entries

4. Applied network policy:
default-deny.yml
```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: default
spec:
  podSelector: {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
  - ports:
    - protocol: UDP
      port: 53
  policyTypes:
  - Ingress
  - Egress
```

guestbook-front.yml
```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: guestbook-front
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: guestbook
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 100.64.0.0/10
  - ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
          role: master
  - ports:
    - protocol: TCP
      port: 6379
  policyTypes:
  - Ingress
  - Egress
```

guestbook-back.yml
```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: guestbook-back
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: guestbook
  - ports:
    - protocol: TCP
      port: 6379
  policyTypes:
  - Ingress
  - Egress
```

5. Validated ELB-hostname:3000 still operates correctly
6. Validated via kubectl exec that a test pod could not reach redis pods directly

I'll figure out how to run the e2e tests next
