### ISSUE TITLE
kops update cluster ignores kubernetesVersion

### ISSUE THREAD

**Issue by maust** [kubernetes/kops#3916]
1. What `kops` version are you running? Version 1.7.1 (mac)

2. What Kubernetes version are you running? 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:40Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using? AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
* `kops edit ig nodes`
* Increased maxSize from 6 to 12
* `kops update cluster $NAME`
* Output see https://gist.github.com/maust/579a44f7cc1a02977643416130f16a99

5. What happened after the commands executed?
Shows that kops wants to update k8s from 1.6.2 to 1.7.1

6. What did you expect to happen?
Only the update of the ASG, but no update of k8s.

7. Please provide your cluster manifest.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-05-10T07:01:27Z
  name: $NAME
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Project: $PROJECT
    System: k8s
  cloudProvider: aws
  configBase: s3://$S3BUCKET/$NAME
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.6.2
  masterInternalName: api.internal.$NAME
  masterPublicName: api.$NAME
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: 172.20.96.0/19
    name: eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-10T07:01:27Z
  labels:
    kops.k8s.io/cluster: $NAME
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-10T07:01:27Z
  labels:
    kops.k8s.io/cluster: $NAME
  name: nodes
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: t2.medium
  maxSize: 12
  minSize: 6
  role: Node
  subnets:
  - eu-west-1a
```
