### ISSUE TITLE
fileAssets fails when using /srv/kubernetes/assets

### ISSUE THREAD

**Issue by twang-rs** [kubernetes/kops#3921]
kops: 1.8.0-beta.1 (git-9b71713)
kubernetes: 1.7.10

Maybe related to #3645.

I tried to add a fileAsset in /srv/kubernetes/assets via the following snippet:

```
fileAssets:
- name: github-webhook
  roles: [Master]
  content: |
    kind: Config
    apiVersion: v1
    preferences: {}
    clusters:
    - name: authenticator
      cluster:
        server: http://localhost:3000/authenticate
    users:
    - name: api-server
    contexts:
    - name: webhook
      context:
        cluster: authenticator
        user: api-server
    current-context: webhook
```

After performing `kop replace -f cluster-spec.yml`, `kops update cluster $NAME --yes`, and `kops rolling-update cluster --yes`, the masters do not come up.

SSH into the box and rerunning node up:

```
$ sudo SKIP_PACKAGE_UPDATE=1 /var/cache/kubernetes-install/nodeup --conf=/var/cache/kubernetes-install/kube_env.yaml --v=10
```

Generates the following error:

```
[Install]
WantedBy=multi-user.target
F1124 19:12:26.323970     840 task.go:57] found duplicate tasks with name "File//srv/kubernetes/assets": File: "/srv/kubernetes/assets" and File: "/srv/kubernetes/assets"
```
From my limited knowledge of kops:

* The error comes from [AddTask](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/task.go#L57)
* I assume that [FileAssetsBuilder.buildFileAssets](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/file_assets.go#L92) is what is adding tasks for my file asset
* I can see here that it is adding a task to create the directory of my asset, following by a task to create my file.

I assume that what is happening is that since a FileType_Directory task for`/srv/kubernetes/assets` is being added by default (see [FileAssetsBuilder.Build](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/file_assets.go#L43)), and since [File tasks use its Path as its name](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/nodeup/nodetasks/file.go#L111) -- we are creating tasks with the same name.

Browsing source, I see that we have a [EnsureTask](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/task.go#L66), it may make more sense to use this instead of AddTask for creating directories.

I tried setting the `fileAssets` both with `path` set to `/srv/kubernetes/assets/github-webhook.yaml` and without specifying `path` at all -- both produce this error.  I then tried changing the `path` to `/opt/github-webhook.yaml` and that appeared to work.
