### ISSUE TITLE
Enable PodTolerationRestrictions and PodNodeSelector Admission Controllers on cluster

### ISSUE THREAD

**Issue by mikn** [kubernetes/kops#3927]
This is up to the maintainers whether you want to enable just these two, or create a feature that allows users to enumerate which admission controllers they want to add.
These specific admission controllers just adds a couple of features to Kubernetes which allows you to specify as annotations on the namespace itself, which tolerations and nodeSelectors are automatically attached to pods created in that namespace and which are not allowed.
The PodTolerationRestrictions is rather hard to figure out how it works however as it is to be specified in a JSON string; and PodNodeSelector allows you to use the label selector syntax.

**Comment by justinsb** [comment]
Marking for 1.9, as AFAICT neither of these are enabled in 1.8.  It looks like they aren't even going to be enabled in 1.9!

We do allow override of admission controllers today by specifying the flag in the kubeApiServer field, but we should promote it to a dedicated field if admissions controllers are going to be more configurable going forward, because specifying the flag directly doesn't do well with k8s version updates (because the list is then "locked", whereas you want to say "the default + PodNodeSelector".

**Comment by mikn** [comment]
Oh. What do you mean with that neither of them are going to be enabled in 1.9? As far as I understand, they just give you a recommended "enabled" admission controller list in the documentation per version? :)
I can give it a try to provide some code for making the admission controller list configurable, assuming your suggestion is something like what you want (defaultAdmissionControllers: true/false + additionalAdmissionControllers: [list of admission controllers])

**Comment by justinsb** [comment]
So the primary tested configurations are defined here, I believe: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L296-L304

So it's true that the docs could say something different, but they really shouldn't deviate from the tested configuration.

Figuring out how to configure this would be great - I'm not sure if we should try to adopt dynamic initialization controllers though instead (my guess is no, but I'm not sure).  It looks like we'll likely allow per-admission-controller configuration in future, so I suggest that we always have the default list, but then we define an array of objects, and we can force controllers on or off, or (in future) add configuration.

i.e.

```
admissionControllers:
- name: PodNodeSelector
  disable: false # optional, false should be the default
  config: {} # for the future
- name: DefaultThing
  disable: true
```

How does that sound?  cc @mtaufen for componentconfig implications and @krousey and @pipejakob for machine API implications

**Comment by mikn** [comment]
Sounds good! Only nitpick I'd have is that I would change `disable` to `enable` and default that to true instead. I'll start digging into what this could look like as right now we're building our own version of kops, and I really dislike doing so. :)

**Comment by jordanjennings** [comment]
The ability to define additional admission controllers on top of the default would be great. With cluster updates I always have to remember to compare my custom list with the defaults to manually build the defaults + extras list.  (Coincidentally we are also using `PodNodeSelector` and `PodTolerationRestriction`, which is why I noticed this issue).

**Comment by bradenwright** [comment]
Any updates on this, 1.9 is out and I would really like to use this feature but haven't been able how to configure in kops

**Comment by jordanjennings** [comment]
@bradenwright You can pretty easily enable this feature by adding some configuration to your kops manifest:

```
  kubeAPIServer:
    # need to verify the admission controllers on version updates
    # should be in sync with kops defaults plus additional custom ones
    # https://github.com/kubernetes/kops/blob/master/pkg/model/components/apiserver.go
    admissionControl:
    # defaults from apiserver.go for k8s 1.9
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota

    ###################### add custom ones here ###########################
    # https://kubernetes.io/docs/admin/admission-controllers/#podnodeselector
    - PodNodeSelector
    # https://kubernetes.io/docs/admin/admission-controllers/#podtolerationrestriction
    - PodTolerationRestriction
```

**Comment by bradenwright** [comment]
@jordanjennings thanks for the reply, I should have been a little more clear.  I'm not sure how to setup the config.  So I was trying to set:
```
    PodNodeSelector:
      configuration:
        podNodeSelectorPluginConfig: 
          clusterDefaultNodeSelector: "kops.k8s.io/instancegroup=nodes"
```

but have not been able to get `kops edit cluster` to save, it doesn't like what I've tried.

**Comment by jordanjennings** [comment]
@bradenwright I wasn't aware that kops directly supported this at all, so I'm not sure about that syntax you're using.

In my case I was looking to set up dedicated nodes for a particular namespace, so I set up taints on an instance groups using kops, and then I set up the toleration restriction and node selector using annotations on the namespace. So if a namespace doesn't have any annotations it will schedule to all untainted instance groups. The dedicated namespace looks like:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "{{ .dedicatedKey }}", "Operator": "Equal", "Value": "{{ .dedicatedValue }}", "Effect": "NoSchedule"}]'
    scheduler.alpha.kubernetes.io/node-selector: {{ .dedicatedKey }}={{ .dedicatedValue }}
```

**Comment by bradenwright** [comment]
@jordanjennings thans for replying, I may just have to go with that for now.  My worry is that if a new namespace is created we have to then remember to add above to a namespace, I was hoping to set a default for the cluster.

I've found some documentation: https://kubernetes.io/docs/admin/admission-controllers/#podnodeselector (anchor isn't working may want to search for PodNodeSelector) and https://embano1.github.io/post/podnodesel/ which is an indepth tutorial.

I'm not sure if this is currently supported by kops, but it would be super useful

**Comment by deyceg** [comment]
@justinsb do you have anyone working on this? I don't really want to have a custom kops build or some hacky workaround (haven't found one yet mind). For billing purposes I need to ensure _team_ namespaces are run on the correct nodes and not make it a development concern to remember to place `nodeSelector` on the manifests

**Comment by pajel** [comment]
In k8s 1.10 the field has changed from `admissionControl` to `enableAdmissionPlugins`.
Your kops manifest should look like this:
```
spec:
  kubeAPIServer:
    enableAdmissionPlugins:
    # default admission controllers
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    # custom admission controllers
    - PodNodeSelector
    - PodTolerationRestriction
```
