### ISSUE TITLE
Etcd Upgrade (v2.3.7)  /bin/tee: not found

### ISSUE THREAD

**Issue by edulop91** [kubernetes/kops#3938]
1. What `kops` version : `Version 1.8.0-beta.1 (git-9b71713)`

2. What Kubernetes version are you running?
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using? `aws`

4. What commands did you run?  What is the simplest way to reproduce this issue?
creating a new cluster with etcd version `2.3.7`

5. What happened after the commands executed?
Master etcd logs:
```
cat containers/etcd-server-ip-xxxxx.ec2.internal_kube-system_etcd-container-xxxxx.log 
{"log":"/bin/sh: /bin/tee: not found\n","stream":"stderr"}
```
Locally:
```
docker run -it  gcr.io/google_containers/etcd:2.3.7 sh     
/ # which tee
/usr/bin/tee
/ # /bin/tee
sh: /bin/tee: not found
```
6. What did you expect to happen?
Etcd's run command to be compatible with the etcd image hosted on default gcr. 

7. Please provide your cluster manifest. 
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  annotations:
  creationTimestamp: xxxxx
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: us-east-1a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: us-east-1b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: us-east-1c
    name: main
    version: 2.3.7
...
```

9. Anything else do we need to know?
Attempting to upgrade a kops cluster running etcd 2.2.x to one running 3.x.x. Seems like I need the intermediate 2.3.x etcd version to accomplish this. Is there perhaps an alternate suggested path to perform this upgrade? Is there a mechanism to point the etcd manifest to an alternate etcd image registry?

Thanks!
