### ISSUE TITLE
api and api.internal DNS doesn't replace placeholder

### ISSUE THREAD

**Issue by erstaples** [kubernetes/kops#4001]
As @geojaz mentioned in [this](https://github.com/kubernetes/kops/issues/2189) issue, I am still experiencing this problem with kops version 1.7.1, so I'm opening up a new issue.

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.7.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kops create cluster --zones=us-west-2b --name test2.k8s.example.io --networking canal --yes
```

5. What happened after the commands executed?

Cluster create kicks off, finishes with `Cluster is starting.  It should be ready in a few minutes.` One log worth mentioning is this: 
```
I1203 10:21:05.283368   35767 utils.go:152] Found matching hosted zone ".example.io", but it was "Private" and we require "Public"
```
But despite this kops still creates the DNS records in the correct hosted zone, which is in fact public. After some time the etcd DNS placeholders are replaced with the real DNS, but the api and api.internal remain placeholder values despite letting it run all night. 

6. What did you expect to happen?

I expected all four DNS placeholders to have been replaced with the real DNS.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-03T18:21:03Z
  name: test.k8s.example.io
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.k8s.example.io/test.k8s.example.io
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.10
  masterPublicName: api.test.k8s.example.io
  networkCIDR: 172.20.0.0/16
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-03T18:21:03Z
  labels:
    kops.k8s.io/cluster: test.k8s.example.io
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-03T18:21:03Z
  labels:
    kops.k8s.io/cluster: test.k8s.example.io
  name: nodes
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-west-2b
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

https://gist.github.com/erstaples/a59541be24aef9e3393a1b24c5e0b670

9. Anything else do we need to know?
