### ISSUE TITLE
field oidcUsernamePrefix is not recognized in cluster configuration file

### ISSUE THREAD

**Issue by polasekr** [kubernetes/kops#4007]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? 
Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops edit cluster --state s3://hu-s3b-kops --name=k8s-dev.hubub.com

5. What happened after the commands executed?
When I added a oidcUsernamePrefix  parameter in kubeAPIServer section, I couldn't save the configuration. This is the config with the message at the top.
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
# ...
#       oidcIssuerURL: https://gluu.hubub.com
#       oidcUsernameClaim: uid
# +     oidcUsernamePrefix: user
#       runtimeConfig:
#         batch/v2alpha1: "true"
# ...
# 
...
...
...
  kubeAPIServer:
    oidcClientID: kubernetes
    oidcIssuerURL: https://gluu.hubub.com
    oidcUsernameClaim: uid
    oidcUsernamePrefix: user
    runtimeConfig:
      batch/v2alpha1: "true"
...
...
...
```
6. What did you expect to happen?
Since --oidc-username-prefix switch is defined in kubernetes 1.8, parameter oidcUsernamePrefix should be accepted and configuration saved.
