### ISSUE TITLE
Canal on K8s v1.8 with chain append mode no longer respects networkpolicies

### ISSUE THREAD

**Issue by KashifSaadat** [kubernetes/kops#4037]
The information around this issue is documented here: https://github.com/projectcalico/canal/issues/115

Depending on the outcome from the above issue, we will likely need updates to the following files:
- [k8s-1.8.yaml.template](https://github.com/kubernetes/kops/blob/1.8.0/upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.8.yaml.template)
- [k8s-1.6.yaml.template](https://github.com/kubernetes/kops/blob/1.8.0/upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/k8s-1.6.yaml.template)
- [pre-k8s-1.6.yaml.template](https://github.com/kubernetes/kops/blob/1.8.0/upup/models/cloudup/resources/addons/networking.projectcalico.org.canal/pre-k8s-1.6.yaml.template)

---

### Versions
* Calico version: v2.6.2
* Flannel version: v0.9.1 (the issue was introduced in this version, v0.9.0 works fine)
* Kops version: v1.8.0
* Operating System and version: CoreOS stable v1520.8.0

### Cluster Spec (networking block)
```yaml
  networking:
    canal:
      chainInsertMode: append
      defaultEndpointToHostAction: RETURN
      prometheusMetricsEnabled: true
```

CC @chrislovecnm
