### ISSUE TITLE
AutoscalingLaunchConfiguration error (unsupported instance type p2.xlarge)

### ISSUE THREAD

**Issue by blancsys** [kubernetes/kops#4054]
Hi, I'm trying to deploy a Kubernetes cluster using GPU instance types (p2.xlarge) as described at https://github.com/kubernetes/kops/blob/master/docs/gpu.md.

However, after edit the ig to use p2.xlarge and execute the "kops update cluster <cluster-name> --yes" command, I get the following error:

```
W1213 09:29:49.065541    7649 executor.go:109] error running task "LaunchConfiguration/nodes.k8s.domain.com" (9m57s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: The specified instance type p2.xlarge is not valid
```

This problem occurs even if I configure minNodes=1 and maxNodes=1. It seems like AWS Autoscaling Groups doesn't support p2.xlarge right? But, there is any workaround to this problem? Because it's working somehow on https://github.com/kubernetes/kops/blob/master/docs/gpu.md

Thank you very much in advance!

1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.8.4

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

1) kops create cluster --zones=us-west-1b <cluster-name>
2) kops edit ig --name=<cluster-name> nodes    (and configure machineType: p2.xlarge)
3) kops update cluster <cluster-name> --yes

5. What happened after the commands executed?

The following error is shown many times and the cluster is not created (no new EC2 instances):
```
W1213 09:29:49.065541    7649 executor.go:109] error running task "LaunchConfiguration/nodes.k8s.domain.com" (9m57s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: The specified instance type p2.xlarge is not valid
```

6. What did you expect to happen?

Cluster is created. I should see new p2.xlarge EC2 instances

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-13T13:11:35Z
  name: k8s.domain.com
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://bucket-name/k8s.domain.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-1b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-1b
      name: b
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.k8s.domain.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-1b
    type: Public
    zone: us-west-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-13T13:11:36Z
  labels:
    kops.k8s.io/cluster: k8s.domain.com
  name: master-us-west-1b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-1b
  role: Master
  subnets:
  - us-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-13T13:11:36Z
  labels:
    kops.k8s.io/cluster: k8s.domain.com
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: p2.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-1b
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

I have executed "kops update cluster k8s.domain.com -v 10 --yes" and there is a lot of new output, but nothing more related to this error. 

9. Anything else do we need to know?

Creation of cluster works like a charm when I use other instance types. However, I need instances with GPU support. So, this problem is related to the use of p2.xlarge instances. There is any workarounds? Thank you very much
