### ISSUE TITLE
Spot instances fail to register on 1.8 with calico CNI

### ISSUE THREAD

**Issue by david92rl** [kubernetes/kops#4112]
**What `kops` version are you running?**
`Version 1.8.0 (git-5099bc5)`

**What Kubernetes version are you running?**
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:11:02Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What cloud provider are you using?**
AWS

**What commands did you run?  What is the simplest way to reproduce this issue?**
First, created the cluster spec with
```
kops create cluster \
--state s3://XXXXXX \
--name XXXXXX \
--authorization AlwaysAllow \
--cloud aws \
--cloud-labels XXXXXX=XXXXXX,XXXXXX=XXXXXX \
--encrypt-etcd-storage \
--master-size m3.medium \
--ssh-public-key XXXXXX \
--zones eu-west-1a,eu-west-1b,eu-west-1c \
--networking calico \
--dry-run \
--output yaml \
--vpc XXXXXX
```
Then modified the following in the cluster spec:
```
spec.kubeAPIServer.runtimeConfig.autoscaling/v2beta1 \"true\"
spec.kubeAPIServer.runtimeConfig.batch/v1beta1 \"true\"
spec.kubelet.enableCustomMetrics true
spec.kubeControllerManager.horizontalPodAutoscalerSyncPeriod "15s"
spec.kubeControllerManager.horizontalPodAutoscalerDownscaleDelay "5m0s"
spec.kubeControllerManager.horizontalPodAutoscalerUpscaleDelay "2m0s"
spec.kubeControllerManager.HorizontalPodAutoscalerUseRestClients true
```
Then created the cluster and the following instance groups
On Demand:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: on-demand
  labels:
    kops.k8s.io/cluster: XXXXXX
spec:
  rootVolumeSize: 100
  rootVolumeType: gp2
  machineType: c4.2xlarge
  maxSize: 50
  minSize: 0
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

Spot:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: spot
  labels:
    kops.k8s.io/cluster: XXXXXX
spec:
  rootVolumeSize: 100
  rootVolumeType: gp2
  machineType: m3.2xlarge
  maxPrice: "0.5"
  maxSize: 50
  minSize: 0
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**What happened after the commands executed?**

The cluster started as usual but after setting the desired count to X in the AWS Autoscaling Groups the on-demand nodes are successfully registered but the spot ones fail

**What did you expect to happen?**
All nodes registering successfully

**Please provide your cluster manifest.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-19T15:32:27Z
  name: XXXXXX
spec:
  additionalPolicies:
    master: |-
      XXXXXX
    node: |-
      XXXXXX
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    XXX: XXX
    XXX: XXX
  cloudProvider: aws
  configBase: s3://XXXXXX
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
      batch/v1beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerDownscaleDelay: 5m0s
    horizontalPodAutoscalerSyncPeriod: 15s
    horizontalPodAutoscalerUpscaleDelay: 2m0s
    horizontalPodAutoscalerUseRestClients: true
  kubelet:
    enableCustomMetrics: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.XXXXXX
  networkCIDR: 10.0.0.0/16
  networkID: XXXXXX
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 10.0.64.0/19
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: 10.0.96.0/19
    name: eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-19T15:32:28Z
  labels:
    kops.k8s.io/cluster: XXXXXX
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-19T15:32:29Z
  labels:
    kops.k8s.io/cluster: XXXXXX
  name: on-demand
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: c4.2xlarge
  maxSize: 50
  minSize: 0
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-19T15:32:30Z
  labels:
    kops.k8s.io/cluster: XXXXXX
  name: spot
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m3.2xlarge
  maxPrice: "0.5"
  maxSize: 50
  minSize: 0
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**Anything else do we need to know?**
Looking at the kubelet logs on the failing nodes I see these errors: 
```
Unable to update cni config: No networks found in /etc/cni/net.d/
Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
I can see the `/etc/cni/net.d/` directory is empty, which is the cause of this.

I've also tried with different instance types but it still fails to register the spot nodes. 

I'm not 100% sure but both spot and on-demand should use the same Launch Configurations so I don't really get what could be causing this.
