### ISSUE TITLE
Segfault when kops create -f with a SSHCredential

### ISSUE THREAD

**Issue by plombardi89** [kubernetes/kops#4115]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.8.0 (git-5099bc5)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Trying to setup a 1.8 cluster

3. What cloud provider are you using? AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

Create a file with this:

```
---
apiVersion: kops/v1alpha2
kind: SSHCredential
metadata:
  labels:
    kops.k8s.io/cluster: plombardi.k736.net
spec:
  publicKey: |
    ANY VALUE DOES NOT MATTER
```

Then run `kops create -f <path>`

5. What happened after the commands executed?

```
I1219 15:33:23.764631   12899 s3context.go:163] Found bucket "<REDACTED" in region "us-east-1"
I1219 15:33:23.764702   12899 s3fs.go:176] Reading file "s3://<REDACTED>/plombardi.k736.net/config"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0xf5839c]

goroutine 1 [running]:
k8s.io/kops/pkg/apis/kops/registry.ConfigBase(0x0, 0xc42077af80, 0x12, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/apis/kops/registry/registry.go:34 +0x2c
k8s.io/kops/pkg/client/simple/vfsclientset.(*VFSClientset).KeyStore(0xc420251f30, 0x0, 0x12, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/client/simple/vfsclientset/clientset.go:105 +0x32
main.RunCreate(0xc4206e6980, 0x4a706e0, 0xc42000c018, 0xc4206e6aa0, 0x1, 0xc42013a238)
	/go/src/k8s.io/kops/cmd/kops/create.go:212 +0x5c0
main.NewCmdCreate.func1(0xc420287440, 0xc420997e90, 0x0, 0x3)
	/go/src/k8s.io/kops/cmd/kops/create.go:91 +0x66
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420287440, 0xc420997e00, 0x3, 0x3, 0xc420287440, 0xc420997e00)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4c60000, 0x29fc900, 0x0, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4c60000, 0x4c90710, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/go/src/k8s.io/kops/cmd/kops/root.go:95 +0x9b
main.main()
	/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```
kubern
6. What did you expect to happen?

SSHCredential created just fine :)

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```yaml
---
apiVersion: kops/v1alpha2
kind: SSHCredential
metadata:
  labels:
    kops.k8s.io/cluster: plombardi.k736.net
spec:
  publicKey: |
    REDACTED
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: plombardi.k736.net
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: us-east-1a
    - instanceGroup: master-us-east-1b
      name: us-east-1b
    - instanceGroup: master-us-east-1c
      name: us-east-1c
    name: main
    version: 3.0.17
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: us-east-1a
    - instanceGroup: master-us-east-1b
      name: us-east-1b
    - instanceGroup: master-us-east-1c
      name: us-east-1c
    name: events
    version: 3.0.17
  kubernetesVersion: 1.8.0
  networkCIDR: 10.10.0.0/16
  networking:
    calico:
      crossSubnet: true
  sshKeyName: foo
  subnets:
  - name: us-east-1a
    type: Public
    zone: us-east-1a
  - name: us-east-1b
    type: Public
    zone: us-east-1b
  - name: us-east-1c
    type: Public
    zone: us-east-1c
  - name: us-east-1d
    type: Public
    zone: us-east-1d
  - name: us-east-1e
    type: Public
    zone: us-east-1e
  - name: us-east-1f
    type: Public
    zone: us-east-1f
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: plombardi.k736.net
  name: master-us-east-1a
spec:
  associatePublicIp: true
  image: coreos/CoreOS-stable-1576.4.0-hvm
  machineType: m4.large
  maxPrice: "0.1"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: plombardi.k736.net
  name: master-us-east-1b
spec:
  associatePublicIp: true
  image: coreos/CoreOS-stable-1576.4.0-hvm
  machineType: m4.large
  maxPrice: "0.1"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: plombardi.k736.net
  name: master-us-east-1c
spec:
  associatePublicIp: true
  image: coreos/CoreOS-stable-1576.4.0-hvm
  machineType: m4.large
  maxPrice: "0.1"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: plombardi.k736.net
  name: workers-standard
spec:
  associatePublicIp: true
  image: coreos/CoreOS-stable-1576.4.0-hvm
  machineType: r4.large
  maxPrice: "0.14"
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1f
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

```
I1219 15:38:51.646447   13000 s3context.go:163] Found bucket "<REDACTED>" in region "us-east-1"
I1219 15:38:51.646536   13000 s3fs.go:176] Reading file "s3://<REDACTED>/plombardi.k736.net/config"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0xf5839c]

goroutine 1 [running]:
k8s.io/kops/pkg/apis/kops/registry.ConfigBase(0x0, 0xc420a74080, 0x12, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/apis/kops/registry/registry.go:34 +0x2c
k8s.io/kops/pkg/client/simple/vfsclientset.(*VFSClientset).KeyStore(0xc4203f0000, 0x0, 0x12, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kops/pkg/client/simple/vfsclientset/clientset.go:105 +0x32
main.RunCreate(0xc4207a1a80, 0x4a706e0, 0xc420080008, 0xc4207a1ba0, 0x1, 0xc42000c4a0)
	/go/src/k8s.io/kops/cmd/kops/create.go:212 +0x5c0
main.NewCmdCreate.func1(0xc4202f18c0, 0xc420a016e0, 0x0, 0x3)
	/go/src/k8s.io/kops/cmd/kops/create.go:91 +0x66
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202f18c0, 0xc420a01650, 0x3, 0x3, 0xc4202f18c0, 0xc420a01650)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4c60000, 0x29fc900, 0x0, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x4c60000, 0x4c90710, 0x0)
	/go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/go/src/k8s.io/kops/cmd/kops/root.go:95 +0x9b
main.main()
	/go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.
