### ISSUE TITLE
ASG Health Check Grace Period default too low

### ISSUE THREAD

**Issue by neverfox** [kubernetes/kops#4147]
I was asked to submit this issue by @geojaz after a debugging session on Slack. Thanks to Slack user bradgeesaman for coming up with the solution to the problem. Essentially, I had a three master HA setup across three AZs and last night all of the masters went into a restart loops, i.e. they were shutting-down and being restarted by their ASGs only to get shutdown again. I was unable to get control through kops or kubectl and the window of time to check logs was too slim. bradgeesaman suggested I increase the ASG health check grace period to a higher number and that worked to allow them to start up and pass. The masters were taking too long from AWS's perspective to successfully initialize so giving them more time stopped the cycle. It turns out the reason was a runaway cronjob that was stacking up pending pods and, I suspect, bogging things down just long enough to fail the health checks.

As it turns out, the default ASG health check grace period set by kops was 0. Since that's the time to wait before *starting* the health checks, my suspicion is that, under normal operating conditions, the masters can get going before the health checks fail, even when they start immediately. However, under troublesome conditions, it might need more time. So the issue is that it might be helpful or necessary to have a higher default grace period (300 worked in my case) for those times when you have sluggish instances (that might well cause restarts).

1. What `kops` version are you running? 1.8.0

2. What Kubernetes version are you running? 1.8.4

3. What cloud provider are you using? AWS

4. What commands did you run?  What is the simplest way to reproduce this issue? It's not simple but overload your cluster and then try to roll it.

5. What happened after the commands executed? N/A

6. What did you expect to happen? Masters to restart and stabilize.

7. Please provide your cluster manifest.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-09-18T19:49:31Z
  name: REDACTED
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: REDACTED
  dnsZone: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    - instanceGroup: master-us-east-1f
      name: f
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    - instanceGroup: master-us-east-1f
      name: f
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.REDACTED
  networkCIDR: 172.20.0.0/16
  networking:
    kopeio: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 172.20.64.0/19
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 172.20.96.0/19
    name: us-east-1f
    type: Private
    zone: us-east-1f
  - cidr: 172.20.0.0/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 172.20.4.0/22
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  - cidr: 172.20.8.0/22
    name: utility-us-east-1f
    type: Utility
    zone: us-east-1f
  topology:
    bastion:
      bastionPublicName: bastion.REDACTED
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-18T19:49:32Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-us-east-1d
  - utility-us-east-1e
  - utility-us-east-1f

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-18T19:49:31Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1d
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-18T19:49:32Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1e
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1e

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-18T19:49:32Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1f
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1f

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-18T19:49:32Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: r4.xlarge
  maxSize: 9
  minSize: 9
  role: Node
  subnets:
  - us-east-1d
  - us-east-1e
  - us-east-1f
```
