### ISSUE TITLE
kops incorrectly detects overlapping CIDR ranges, but still creates the subnets

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4150]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?

aws

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops create cluster --cloud aws --name {cluster name} --state s3://k8sstate --node-count 1 --zones eu-west-1a,eu-west-1b --node-size t2.micro --master-size t2.micro --master-zones eu-west-1a --ssh-public-key ~/.ssh/id_rsa.pub --topology=private --networking=weave --associate-public-ip=false --master-volume-size 50 --node-volume-size 50 --vpc {existing vpc}`

then edited the CIDR blocks via `kops edit cluster `

```
  - cidr: 10.32.34.0/23
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.32.36.0/23
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.32.34.0/23
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.32.36.0/23
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
```

5. What happened after the commands executed?

```
W1227 12:33:18.339131   11257 executor.go:109] error running task "Subnet/utility-eu-west-1b.{cluster name}" (9m58s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CIDR '10.32.36.0/23' conflicts with another subnet
	status code: 400, request id: 75add824-d203-4c34-8c28-b0fa14d7c21a
W1227 12:33:18.339208   11257 executor.go:109] error running task "Subnet/eu-west-1a.{cluster name}" (9m58s remaining to succeed): error creating subnet: InvalidSubnet.Conflict: The CIDR '10.32.34.0/23' conflicts with another subnet
	status code: 400, request id: af8d90af-6eaa-4331-8273-60c7576705d3
```
It then keeps retrying -- but the **subnets were created** -- so presumably, it created the subnets, but doesn't know they were created successfully so when it retries it thinks there's a conflict because there's already a subnet there (the one it just created)

6. What did you expect to happen?

No errors

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-27T12:36:14Z
  name: {CLUSTER_NAME}
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8sstate/{CLUSTER_NAME}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterInternalName: api.internal.{CLUSTER_NAME}
  masterPublicName: api.{CLUSTER_NAME}
  networkCIDR: 10.32.0.0/16
  networkID: {EXISTING_VPC}
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.32.34.0/23
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.32.36.0/23
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.32.34.0/23
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.32.36.0/23
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-27T12:36:14Z
  labels:
    kops.k8s.io/cluster: {CLUSTER_NAME}
  name: master-eu-west-1a
spec:
  additionalSecurityGroups:
  - {EXTRA_SECURITY_GROUP}
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  rootVolumeSize: 50
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-27T12:36:14Z
  labels:
    kops.k8s.io/cluster: {CLUSTER_NAME}
  name: nodes
spec:
  additionalSecurityGroups:
  - {EXTRA_SECURITY_GROUP}
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 50
  subnets:
  - eu-west-1a
  - eu-west-1b
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

N/A

9. Anything else do we need to know?

I also tried using existing, pre-created subnets and using the IDs, there were no errors this time (as I guess it identified it didn't need to create any new subnets.
