### ISSUE TITLE
kops validate will fail if `associate-public-ip` is false

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4158]
I am attempting to plug in a new k8s cluster into existing subnets and VPC and want to avoid giving anything public IPs if possible.

So I used this:

`kops create cluster --cloud aws --name {CLUSTER_NAME} --state s3://k8sstate --node-count 1 --zones eu-west-1a,eu-west-1b --node-size r3.large --master-size r3.large --master-zones eu-west-1a --ssh-public-key ~/.ssh/id_rsa.pub --associate-public-ip=false --vpc {EXISTING_VPC}`

Then updated the CIDR ranges to reflect the existing (pre-created) subnets. These subnets are behind NATs (in case that makes a difference)

```
  subnets:
  - cidr: {RANGE A}
    id: {SUBNET A}
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: {RANGE B}
    id: {SUBNET B}
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
```
The DNS entries are created successfully with placeholders. The etcd-a, etcd-events, api.internal all update off their placeholder IPs successfully. However, the api entry never updates off the placeholder.

I assumed the `--associate-public-ip` might be a contributing factor and after turning it off, the api DNS entry does indeed update to the public IP. Since `kops validate` looks up the api entry (the non-internal one), using `associate-public-ip=false` will cause `kops validate` to never be successful.

This also affects `rolling-update` and may affects some deployments.

Is there a switch on kops/kops validate where I can say "use the api.internal entry" ?
