### ISSUE TITLE
[AWS] Feature Request: Encrypted volume support in storage-aws.addons.k8s.io

### ISSUE THREAD

**Issue by steveruckdashel** [kubernetes/kops#4225]
I would like the ability to have the default EBS storage class provision encrypted volumes. I image configuring this through the cluster_spec:
```
spec:
  cloudConfig:
    awsStorageEnrypted: true
```

Resulting in storage-aws.addons.k8s.io/v1.7.0.yaml having the `encrypted: true` flag:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  labels:
    k8s-addon: storage-aws.addons.k8s.io
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    k8s-addon: storage-aws.addons.k8s.io
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: true
```
