### ISSUE TITLE
LoadBalancer always reports instances as OutOfService

### ISSUE THREAD

**Issue by grimborg** [kubernetes/kops#4295]
I expose a deployment using a service of type LoadBalancer. That creates an ELB, but the EC2 instances it has never pass the health checks, so they are marked as OutOfService and I can't access my deployment from outside.

Am I doing something wrong? Or is this a kops bug?

cloud: aws
kops version: 1.8.0
kubectl version: 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mmacfadden** [comment]
Do you think this is the same issue as #4301? I know this was reported first, but I think that issue has more info in it.

**Comment by mmacfadden** [comment]
Ultimately the actual issue is probably #4156.

**Comment by chrislovecnm** [comment]
@grimborg are you using master or a released kops version?

**Comment by darrenhaken** [comment]
I am also facing this problem using Kops 1.8.1

**Comment by dasgoll** [comment]
Same issue with Kops 1.8.1

**Comment by snoby** [comment]
Same issue with Kops 1.9.0-alpha.1

**Comment by mmacfadden** [comment]
For me this was fixed in master. Seems odd that 1.9.0-alpha.1 would still have the issue. i should be standing up another cluster shortly. I can report on what i find.

**Comment by snoby** [comment]
@mmacfadden  - let me save you some time, I had to use master to get my already running cluster back from this mess-up.  Only master ( built on Linux) works.

**Comment by mmacfadden** [comment]
@snoby I built on mac os using homebrew from master, and that also worked.

**Comment by dggc** [comment]
I also came across this bug, using Kops 1.8.1 and K8s 1.10.1.

Then I tried reducing the number of master nodes from 3 to 1, recreated the cluster, and it worked. Far from ideal, but a good enough workaround for me while this bug gets resolved.

**Comment by borsboom** [comment]
Has anyone checked whether kops 1.9.0 fixes this?

**Comment by awbacker** [comment]
I'm using `kops 1.9` and having this issue as well (with kube_version 1.9.7). 

It was able to create the cluster fine, and master was reachable (yay!).  However, I after I updated the nodes configuration and did a `kops update cluster --yes && kops rolliing-update cluster --yes` the master was *OutOfService* again.

Really scary to use kops, and no _idea_ how to reach it again

**Comment by MichaelCal** [comment]
Running into this same issue. Kops 1.9.0, Kubernetes 1.10.2.

**Comment by Antiarchitect** [comment]
My issue was this: https://github.com/kubernetes/kops/issues/4844, so solved by moving to m4 for master

**Comment by tomtjose** [comment]
I am also facing this issue; while trying to create the cluster with a specific CentOS image for the instance group. ELB is reporting the master instances as out-of-service, even though the master EC2 instances are running healthy.

Cluster creation is successful if I switch to the default ami (Debian); rest of the kops create flags/configurations being same.

Do you have any helpful pointers or things to try out?
Kops version : 1.9.0
kubectl client : 1.10.1

**Comment by angegar** [comment]
Hi all, i see this issue is pretty old but i am encountering the same one. My nodes and master nodes are up as per my aws console but the api ELB does flag the master as out of service. How did you sort it out ?

Please find my configuration below :

**Cluster configuration**
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: mycluster
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect" : "Allow",
          "Action" : ["sts:AssumeRole"],
          "Resource" : ["*"]
        }
      ]
    node: |
      [
        {
          "Effect" : "Allow",
          "Action" : ["sts:AssumeRole",
                       "route53:ChangeResourceRecordSets",
                       "route53:GetChange",
                       "route53:ListHostedZones",
                        "ec2:DescribeSpotInstanceRequests",
                        "ec2:CancelSpotInstanceRequests",
                        "ec2:GetConsoleOutput",
                        "ec2:RequestSpotInstances",
                        "ec2:RunInstances",
                        "ec2:StartInstances",
                        "ec2:StopInstances",
                        "ec2:TerminateInstances",
                        "ec2:CreateTags",
                        "ec2:DeleteTags",
                        "ec2:DescribeInstances",
                        "ec2:DescribeKeyPairs",
                        "ec2:DescribeRegions",
                        "ec2:DescribeImages",
                        "ec2:DescribeAvailabilityZones",
                        "ec2:DescribeSecurityGroups",
                        "ec2:DescribeSubnets",
                        "iam:ListInstanceProfilesForRole",
                        "iam:PassRole"],
          "Resource" : ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mys3bucket/mycluster
  docker:
    logDriver: ""
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer: {}
  kubelet:
    enableCustomMetrics: true
    featureGates:
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.8
  masterInternalName: api.internal.mycluster
  masterPublicName: api.mycluster
  networkCIDR: 10.165.14.0/24
  networkID: vpc-id
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.165.14.96/27
    egress: nat-id
    id: subnet-id
    name: wkpr1
    type: Private
    zone: us-east-1a
  - cidr: 10.165.14.32/27
    egress: nat-id
    id: subnet-id
    name: wkpr2
    type: Private
    zone: us-east-1b
  - cidr: 10.165.14.64/27
    egress: nat-id
    id: subnet-id
    name: wkpr3
    type: Private
    zone: us-east-1c
  - cidr: 10.165.14.192/27
    id: subnet-id
    name: wkpu4
    type: Utility
    zone: us-east-1a
  - cidr: 10.165.14.128/27
    id: subnet-id
    name: wkpu2
    type: Utility
    zone: us-east-1b
  - cidr: 10.165.14.160/27
    id: subnet-id
    name: wkpu3
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**Master IG configuration**
```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-14T22:10:42Z
  labels:
    Application: Kubernetes cluster
    Environment: Production
    kops.k8s.io/cluster: mycluster
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t3.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - wkpr1
```

**kops version** : Version 1.11.1 (git-0f2aa8d30)
**kubectl version**:   Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: EOF
