### ISSUE TITLE
NodePort services in AWS deploy not working

### ISSUE THREAD

**Issue by neilhwatson** [kubernetes/kops#4328]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Default kops install into two AWS Zones. Also added helm, then nginx-ingress and external-dns via helm.

5. What happened after the commands executed?

Install was successful.

Then deployed a basic helloworld helm chart:

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: RELEASE-NAME-helloworld
      labels:
        app: helloworld
        chart: helloworld-0.1.0
        release: RELEASE-NAME
        heritage: Tiller
    spec:
      type: NodePort
      ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          name: helloworld
      selector:
        app: helloworld
        release: RELEASE-NAME

    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: RELEASE-NAME-helloworld
      labels:
        app: helloworld
        chart: helloworld-0.1.0
        release: RELEASE-NAME
        heritage: Tiller
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: helloworld
            release: RELEASE-NAME
        spec:
          containers:
            - name: helloworld
              image: "neilhwatson/web-docker:1.0"
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 80
              livenessProbe:
                httpGet:
                  path: /
                  port: 80
              readinessProbe:
                httpGet:
                  path: /
                  port: 80
              resources:
                {}
                

    ---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: RELEASE-NAME-helloworld
      labels:
        app: helloworld
        chart: helloworld-0.1.0
        release: RELEASE-NAME
        heritage: Tiller
      annotations:
          kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: helloworld.k8s.example.net
          http:
            paths:
              - path: /
                backend:
                  serviceName: RELEASE-NAME-helloworld
                  servicePort: 80

6. What did you expect to happen?

    curl helloworld.k8s.example.net

Should returna a web page. Instead it timedout.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
    apiVersion: kops/v1alpha2
    kind: Cluster
    metadata:
      creationTimestamp: 2018-01-22T16:52:38Z
      name: k01.k8s.example.net
    spec:
      additionalPolicies:
        node: |
          [
            {
              "Effect": "Allow",
              "Action": [
                "route53:ChangeResourceRecordSets"
              ],
              "Resource": [
                "arn:aws:route53:::hostedzone/Z3DTR6HOCGKBEK"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "route53:ListHostedZones",
                "route53:ListResourceRecordSets"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
      api:
        dns: {}
      authorization:
        alwaysAllow: {}
      channel: stable
      cloudLabels:
        OWNER: Neil Watson neil.watson@example.com
      cloudProvider: aws
      configBase: s3://k01.k8s.example.net.example.net/k01.k8s.example.net
      etcdClusters:
      - etcdMembers:
        - instanceGroup: master-ca-central-1a
          name: a
        name: main
      - etcdMembers:
        - instanceGroup: master-ca-central-1a
          name: a
        name: events
      iam:
        allowContainerRegistry: true
        legacy: false
      kubernetesApiAccess:
      - 0.0.0.0/0
      kubernetesVersion: 1.8.6
      masterPublicName: api.k01.k8s.example.net
      networkCIDR: 172.20.0.0/16
      networking:
        kubenet: {}
      nonMasqueradeCIDR: 100.64.0.0/10
      sshAccess:
      - 0.0.0.0/0
      subnets:
      - cidr: 172.20.32.0/19
        name: ca-central-1a
        type: Public
        zone: ca-central-1a
      - cidr: 172.20.64.0/19
        name: ca-central-1b
        type: Public
        zone: ca-central-1b
      topology:
        dns:
          type: Public
        masters: public
        nodes: public

    ---

    apiVersion: kops/v1alpha2
    kind: InstanceGroup
    metadata:
      creationTimestamp: 2018-01-22T16:52:39Z
      labels:
        kops.k8s.io/cluster: k01.k8s.example.net
      name: master-ca-central-1a
    spec:
      image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
      machineType: c4.large
      maxSize: 1
      minSize: 1
      nodeLabels:
        kops.k8s.io/instancegroup: master-ca-central-1a
      role: Master
      subnets:
      - ca-central-1a

    ---

    apiVersion: kops/v1alpha2
    kind: InstanceGroup
    metadata:
      creationTimestamp: 2018-01-22T16:52:39Z
      labels:
        kops.k8s.io/cluster: k01.k8s.example.net
      name: nodes
    spec:
      image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
      machineType: t2.medium
      maxSize: 2
      minSize: 2
      nodeLabels:
        kops.k8s.io/instancegroup: nodes
      role: Node
      subnets:
      - ca-central-1a
      - ca-central-1b
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

My guess is that the default setup does not permit NodePort services to work. Only LoadBalancer services appear to work.
