### ISSUE TITLE
Worker nodes will *randomly* not register with cluster, requiring a reboot

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4362]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.8.0 (git-5099bc5)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
`kubectl edit ig nodes` and then increased max/min to a higher number

5. What happened after the commands executed?
The nodes spun up in AWS, but some did not register.

6. What did you expect to happen?

If I increase the count from max/min of 0/0 to max/min of 5/5 they will start up in AWS, but anything from none to all of them may or may not show up in the cluster, even after 30 minutes of waiting. It isn't consistent so the first might not register, but the last might, or vice versa. It seems like a race condition of some sort.

Mentioned in #4314 

This is fixed by doing a reboot of an instance (not a terminate) within the AWS console.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-01-04T10:25:26Z
  name: [CLUSTERNAME]
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["route53:*"],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["route53:*"],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://[STATEBUCKET]/[CLUSTERNAME]
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterInternalName: api.internal.[CLUSTERNAME]
  masterPublicName: api.[CLUSTERNAME]
  networkCIDR: 10.32.0.0/16
  networkID: vpc-7d274919
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.32.12.0/23
    id: [SUBNET]
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.32.22.0/23
    id: [SUBNET]
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.32.32.0/23
    id: [SUBNET]
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 10.32.12.0/23
    id: [SUBNET]
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.32.22.0/23
    id: [SUBNET]
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 10.32.32.0/23
    id: [SUBNET]
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-23T10:13:18Z
  labels:
    instance-type: m4.2xlarge
    kops.k8s.io/cluster: [CLUSTERNAME]
  name: m42xlargenodes
spec:
  additionalSecurityGroups:
  - [SECURITYGROUP]
  - [SECURITYGROUP]
  associatePublicIp: false
  cloudLabels:
    Billing: finance
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m4.2xlarge
  maxPrice: "1.50"
  maxSize: 15
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: m42xlargenodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-04T10:25:26Z
  labels:
    kops.k8s.io/cluster: [CLUSTERNAME]
  name: master-eu-west-1a
spec:
  additionalSecurityGroups:
  - [SECURITYGROUP]
  associatePublicIp: false
  cloudLabels:
    Billing: finance
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxPrice: "1.00"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-04T10:25:26Z
  labels:
    kops.k8s.io/cluster: [CLUSTERNAME]
  name: master-eu-west-1b
spec:
  additionalSecurityGroups:
  - [SECURITYGROUP]
  associatePublicIp: false
  cloudLabels:
    Billing: finance
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxPrice: "1.00"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-04T10:25:26Z
  labels:
    kops.k8s.io/cluster: [CLUSTERNAME]
  name: master-eu-west-1c
spec:
  additionalSecurityGroups:
  - [SECURITYGROUP]
  associatePublicIp: false
  cloudLabels:
    Billing: finance
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxPrice: "1.00"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
  - eu-west-1c
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

N/A this happens during an instance spin up

9. Anything else do we need to know?
