### ISSUE TITLE
"kops create secret sshpublickey" using the same public key

### ISSUE THREAD

**Issue by manhongcc** [kubernetes/kops#4373]
I am not sure if this is a bug.
1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.0 (git-5099bc5)`
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?
AWS
4. What commands did you run?  What is the simplest way to reproduce this issue?
`kops create secret --name cluster.name sshpublickey admin -i ~/.ssh/mykey.pub`
The public key file is actually the same public key I used to create the cluster with option
`--ssh-public-key` in `kops create cluster`

5. What happened after the commands executed?
The certificate-authority-data, client-certificate-data, client-key-data in  ~/.kube/config is being modified. But the new config file is not able to access the cluster right away.
Therefore I switch back to the original config file(The one before the modification by `kops create secret --name cluster.name sshpublickey admin -i ~/.ssh/mykey.pub`) which worked fine at that moment. I can use kubectl as perfectly normal.

The real problem is after a week, 
I have to use the new kubeconfig to access the cluster. The old kubeconfig does not work anymore with error 
`Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

2 different kube-dns pods kubedns container show logs like below respectively
```
I0203 09:56:04.859131       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0203 09:56:05.359155       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0203 09:56:05.465167       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Unauthorized
E0203 09:56:05.465201       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Unauthorized
```

```
E0203 09:58:29.178130       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://100.64.0.1:443/api/v1/endpoints?resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
E0203 09:58:29.180491       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://100.64.0.1:443/api/v1/services?resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

kubectl -nkube-system log kube-apiserver-ip-172-20-60-234.eu-west-1.compute.internal
```
E0203 12:21:09.557873       6 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]
I0203 12:21:09.557990       6 wrap.go:42] GET /api/v1/endpoints?resourceVersion=0: (326.534µs) 401 [[kube-dns/v0.0.0 (linux/amd64) kubernetes/$Format] 172.20.85.161:52138]
E0203 12:21:09.557888       6 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]
I0203 12:21:09.558227       6 wrap.go:42] GET /api/v1/services?resourceVersion=0: (518.841µs) 401 [[kube-dns/v0.0.0 (linux/amd64) kubernetes/$Format] 172.20.85.161:52138]
```

6. What did you expect to happen?
I expect the command should not change everything because the public key file is actually the same one. 
It should not affect any configuration.(If I didn't make any mistakes)
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: REDACTED
  name: REDACTED
spec:
  additionalPolicies:
    node: |
      [
        { "Effect": "Allow", "Action": ["acm:DescribeCertificate", "acm:ListCertificates"], "Resource": "*"},
        { "Effect": "Allow", "Action": ["s3:*"], "Resource": ["*"] },
        { "Effect": "Allow", "Action": ["ec2:*Snapshot", "ec2:CreateTags", "ec2:Describe*"], "Resource": ["*"] },
        { "Effect": "Allow", "Action": ["route53:ChangeResourceRecordSets"], "Resource": ["arn:aws:route53:::hostedzone/*"] },
        { "Effect": "Allow", "Action": ["route53:*", "route53:ListResourceRecordSets"], "Resource": ["*"] }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://REDACTED
  dnsZone: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: true
  kubeAPIServer:
    authorizationRbacSuperUser: admin
  kubernetesApiAccess:
  - REDACTED
  kubernetesVersion: v1.8.6
  masterInternalName: api.internal.REDACTED
  masterPublicName: api.REDACTED
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - REDACTED
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: 172.20.96.0/19
    name: eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: REDACTED
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-eu-west-1a
spec:
  image: ami-32d1474b
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: REDACTED
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  image: ami-32d1474b
  machineType: t2.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
I suspect the api-server has used the new certificate for authentication,
but other pods failed to authenticate with the old key.
