### ISSUE TITLE
configuration for docker version

### ISSUE THREAD

**Issue by Caskia** [kubernetes/kops#4392]
Hi guys,
     I want to upgrade my docker version to 17.06+, so changed the cluster config file. But it doesn't have any effect! So I want to know how to update docker version?

kops version: 1.8.0
cloud provider: aws
code command: 
```
kops edit cluster ${NAME}
kops update cluster ${NAME} --yes
```
manifest
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-02-06T13:33:00Z
  name: hicoincluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://hicoin-bucket/hicoincluster.k8s.local
  dnsZone: Z302W97P4XUUSE
  docker:
    bridge: ""
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay,aufs
    version: 17.06.0-ce
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterInternalName: api.internal.hicoincluster.k8s.local
  masterPublicName: api.hicoincluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 172.20.64.0/19
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-06T13:33:00Z
  labels:
    kops.k8s.io/cluster: hicoincluster.k8s.local
  name: master-ap-northeast-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1a
  role: Master
  rootVolumeSize: 20
  subnets:
  - ap-northeast-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-06T13:33:00Z
  labels:
    kops.k8s.io/cluster: hicoincluster.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 20
  subnets:
  - ap-northeast-1a
  - ap-northeast-1c

```
