### ISSUE TITLE
Updating secrets / locking down access with `kubectl` doesn't appear to be working

### ISSUE THREAD

**Issue by aaboyd** [kubernetes/kops#4403]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-5099bc5)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Changed the secrets for admin and kube on S3 directly, as mentioned https://github.com/kubernetes/kops/blob/master/docs/secrets.md#workaround-for-changing-secrets-with-type-secret .
Then did a rolling update
`kops rolling-update cluster --yes --force`

5. What happened after the commands executed?
Commands executed successfully, access with kubectl was still functioning with old `KUBECONFIG`

6. What did you expect to happen?
Was expecting an old `KUBECONFIG` to not work properly anymore since the credentials had been changed. 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-09-08T17:04:01Z
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2b
      name: b
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  networkCIDR: 121.193.0.0/16
  networkID: vpc-*******
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 121.193.32.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-08T17:04:02Z
  name: master-us-east-2b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-08T17:04:02Z
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m4.xlarge
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  - us-east-2b
```

I am looking for a way to lock down a cluster and prevent users who previously had access from actually changing anything.  I have already put the proper permissions on the state stores buckets, but anyone who had previously exported using `kops export kubecfg` still has access to the cluster.
