### ISSUE TITLE
Auto Scaling Group failed to maintain the desired number of nodes. [AWS]

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/kops#4418]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.0 (git-5099bc5)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?
Somehow crash a node in the cluster

5. What happened after the commands executed?
Auto Scaling Group failed to maintain the desired number of nodes when 2 of my cluster nodes died.

6. What did you expect to happen?
When 2 of my cluster nodes died, the Auto Scaling Group should have terminated these nodes and created 2 new nodes for my cluster.  

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by gauravarora** [comment]
Did your node terminate or did the kubelet crash? ASG will only bring up a new node if your old nodes terminate.

**Comment by huang-jy** [comment]
If the nodes "die", but still report healthy back to AWS, regardless of reason, then they will not be replaced by the ASG.

**Comment by chrisseto** [comment]
I ran in a similar issue recently, does this look related? (There's a temporary solution included)

https://github.com/kubernetes/kubernetes/issues/60644

**Comment by huang-jy** [comment]
@chrisseto are your instances spots?

**Comment by chrisseto** [comment]
Yep, spot `c4.xlarge` instances in `us-east-1`

**Comment by huang-jy** [comment]
Then you might need the hooks fix:

Add to cluster definition under spec:

```
  hooks:
  - manifest: "Type=oneshot                    \nExecStart=/usr/bin/docker run --net
      host quay.io/sergioballesteros/check-aws-tags\nExecStartPost=/bin/systemctl
      restart kubelet.service\n"
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Node
  - manifest: "Type=oneshot                    \nExecStart=/usr/bin/docker run --net
      host quay.io/sergioballesteros/check-aws-tags\nExecStartPost=/bin/systemctl
      restart kubelet.service\n"
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Master
```
