### ISSUE TITLE
Bastions role additionalUserData not available?

### ISSUE THREAD

**Issue by abednarik** [kubernetes/kops#4444]
Hi

 Thanks for this tools, works great :)

1. I'm currently using additionalUserData for nodes and masters to install SaltStack and setup users and a few minor things we apply to all instances. I'm trying to do the same for bastions groups, but even when I edit bastions IG nothing changes and kops doesn't detect any change.

Here is what I do

```
kops edit instancegroup bastions
```

I add the example present in Instance Group for this feature

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-13T15:43:08Z
  labels:
    kops.k8s.io/cluster: mycluster.company.com
  name: bastions
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "Hello World.  The time is now $(date -R)!" | tee /root/output.txt
  image: ami-965e6bf3
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-2a
  - utility-us-east-2b
  - utility-us-east-2c
```

I don't get a message like **kops edit does not update the cloud resources, to apply the changes use "kops update cluster"** like I get when editing nodes IG.

Running update/rolling-update cluster doesn't change anything. I also checked Launch Configuration for this group and user-data is empty.

2. Feel free to provide a design supporting your feature request.

The same approach used for all other instances, like nodes and master?

Thanks.
