### ISSUE TITLE
Unable to create cluster with .k8s.local (gossip): DNS Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by smcquay** [kubernetes/kops#4448]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

I'm trying to test out recently merged `amazon-vpc-routed-eni` functionality, so I'm running off of master:

```bash
 $ kops version                                                                                                                                                                                     
Version 1.8.0 (git-5825c41f8)
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

My `kubectl` version:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: EOF
```

and I've not specified any flags for `kops` for kubernetes version, so I've requested the default. 

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```bash
$  kops create cluster --zones us-west-2a k8s-kops-poc-04.k8s.local
$  kops update cluster k8s-kops-poc-04.k8s.local --yes
```

5. What happened after the commands executed?

All kubernetes commands return with `Unable to connect to the server: EOF`, e.g.:

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: EOF
$ kubectl get nodes
Unable to connect to the server: EOF
```

6. What did you expect to happen?

As I was following the [tutorial guide](https://github.com/kubernetes/kops/blob/master/docs/aws.md#configure-dns) which states:

> Note: If you are using Kops 1.6.2 or later, then DNS configuration is optional. Instead, a gossip-based cluster can be easily created. The only requirement to trigger this is to have the cluster name end with .k8s.local. If a gossip-based cluster is created then you can skip this section.

I skipped the DNS section by specifying a cluster name of `k8s-kops-poc-04.k8s.local`, which was noted in the output of `kops create cluster`:

```
I0215 12:50:31.369743   85779 apply_cluster.go:437] Gossip DNS: skipping DNS validation
```

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-02-15T20:49:48Z
  name: k8s-kops-poc-04.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://sm-k8s-kops-state-store/k8s-kops-poc-04.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterPublicName: api.k8s-kops-poc-04.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-15T20:49:48Z
  labels:
    kops.k8s.io/cluster: k8s-kops-poc-04.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-15T20:49:48Z
  labels:
    kops.k8s.io/cluster: k8s-kops-poc-04.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a

```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

[create.stderr.txt](https://github.com/kubernetes/kops/files/1729378/create.stderr.txt)
[create.stdout.txt](https://github.com/kubernetes/kops/files/1729379/create.stdout.txt)
[update.stderr.txt](https://github.com/kubernetes/kops/files/1729380/update.stderr.txt)
[update.stdout.txt](https://github.com/kubernetes/kops/files/1729381/update.stdout.txt)

9. Anything else do we need to know?

I've tried this in the region that I want it to be in (us-west-1a), and the one from the docs (us-west-2a). I've tried it with a complex set of flags:

```bash
kops create cluster \
    --cloud=aws \
    --zones us-west-1a \
    --name=k8s-kops-poc-00.k8s.local \
    --vpc $KOPS_TEST \
    --networking amazon-vpc-routed-eni \
    --master-size c4.xlarge \
    --kubernetes-version 1.9.2 \
    --node-count 4 \
    --node-size m4.2xlarge \
    --state s3://sm-k8s-kops-state-store 
```

and as simple as they come on the tutorial. I've reached out to folks in #kops-users in slack, and got reports such as:

> nwatson [10:20 AM] I couldn't make that work either, 2 months ago, and went with using a hosted subdomain instead.
> hubt [10:29 AM] gossip dns is much less tested, but should work. i would fo with route53 if at all possible.

Does this feature work?

**Comment by chrislovecnm** [comment]
Are instances being created?  Any errors on the ASG's?  What does `kops validate` say?  You may be running into a problem with a 'feature' of nodeup that we have currently.  Are you getting nodeup errors?  Can you rebase and try again, please?  I fixed something in the Makefile which might help.  How are you building kops?

**Comment by smcquay** [comment]
Alright I did a rebase and redeploy and I'm seeing what I want to see:

```bash
$ kubectl get nodes                                                                                                                   
NAME                                          STATUS    ROLES     AGE       VERSION
ip-172-20-49-209.us-west-1.compute.internal   Ready     master    29m       v1.8.6
ip-172-20-51-53.us-west-1.compute.internal    Ready     node      28m       v1.8.6
ip-172-20-61-17.us-west-1.compute.internal    Ready     node      28m       v1.8.6
```

It's likely a dupe of the `nodeup` failures! Thanks for the suggestion!

Getting back to your earlier suggestion @chrislovecnm would you like me to update docs somehow? A simple `git pull && make` fixed it for me, but I'm happy to dig into building generally and help flesh out docs (I couldn't see any in the docs). If there's already an issue I'm happy to take it (I searched for a few mins and couldn't find one); should I make one?

**Comment by smcquay** [comment]
This is interesting; the next step for me is running a cluster with the `amazon-vpc-routed-eni`, when I Also when I try to run this:

```bash
$ kops create cluster -v 10 --cloud=aws --zones us-west-1a --name=k8s-kops-poc-08.k8s.local --networking amazon-vpc-routed-eni --master-size c4.xlarge --kubernetes-version 1.9.2 --node-count 4 --node-size m4.2xlarge --state s3://sm-k8s-kops-state-store > ~/create.stdout.txt 2> ~/create.stderr.txt
$  kops update cluster -v 10 k8s-kops-poc-08.k8s.local --yes > ~/update.stdout.txt 2> ~/update.stderr.txt
```

[update.stdout.txt](https://github.com/kubernetes/kops/files/1732534/update.stdout.txt)
[update.stderr.txt](https://github.com/kubernetes/kops/files/1732535/update.stderr.txt)
[create.stdout.txt](https://github.com/kubernetes/kops/files/1732536/create.stdout.txt)
[create.stderr.txt](https://github.com/kubernetes/kops/files/1732537/create.stderr.txt)

The cluster gets in a similar situation where all `kubectl` commands return: 

```bash
$ kubectl get nodes                                                                                                                                                                                              
Unable to connect to the server: EOF
```

```bash
$ admin@ip-172-20-63-168:~$ ps aux | grep -i nodeup
root       756  0.0  0.0 345872 22968 ?        Sl   19:03   0:00 ./nodeup --install-systemd-unit --conf=/var/cache/kubernetes-install/kube_env.yaml --v=8
root       781  1.4  0.0 621752 31204 ?        Ssl  19:03   0:07 /var/cache/kubernetes-install/nodeup --conf=/var/cache/kubernetes-install/kube_env.yaml --v=8
```
So that's running, and I've poked around using `lsof` and in `/var/log/` and don't see any `nodeup`
-specific logs; should I attach `/var/log/cloud-init*`? Any other ideas or suggestions?

**Comment by apjneeraj** [comment]
I got this couple of times but because cluster was still in creations and I could see that my nodes we're just getting initialized. Api Load balancer was waiting for master to come up so kops validate as well as kubeclt get nodes can show something. I waited for few minutes and it works as expected.

**Comment by smcquay** [comment]
@apjneeraj Yes I've gotten the same message as I'm waiting for nodes to come up (just reproduced this morning with the "vanilla" cluster, created with `kops -v10 create cluster --zones us-west-1a k8s-kops-poc-10.k8s.local`), but this seems to be a permanent failure to stand up a cluster. I replicated my attempt to get `amazon-vpc-routed-eni` just before lunch and `nodeup` still seems wedged:

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-02-20T20:31:12Z
  name: k8s-kops-poc-11.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://sm-k8s-kops-state-store/k8s-kops-poc-11.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterPublicName: api.k8s-kops-poc-11.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-1a
    type: Public
    zone: us-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

```bash
$ kops validate cluster
Using cluster from kubectl context: k8s-kops-poc-11.k8s.local

Validating cluster k8s-kops-poc-11.k8s.local


cannot get nodes for "k8s-kops-poc-11.k8s.local": Get https://api-k8s-kops-poc-11-k8s-l-2qnhlb-1784246008.us-west-1.elb.amazonaws.com/api/v1/nodes: EOF
$  kubectl get nodes                  
Unable to connect to the server: EOF
```


[update.stdout.txt](https://github.com/kubernetes/kops/files/1741985/update.stdout.txt)
[update.stderr.txt](https://github.com/kubernetes/kops/files/1741986/update.stderr.txt)
[create.stdout.txt](https://github.com/kubernetes/kops/files/1741987/create.stdout.txt)
[create.stderr.txt](https://github.com/kubernetes/kops/files/1741988/create.stderr.txt)

I'm going to dig around now in my running instance to see if I can identify root cause for `nodeup` failure
