### ISSUE TITLE
ELB created via a Kubernetes Service shows the nodes as OutOfService

### ISSUE THREAD

**Issue by darrenhaken** [kubernetes/kops#4486]
I have created a service using the following:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    name: nginx-example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
spec:
  selector:
    app: nginx-example
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http-web
```

The ELB launches but the nodes are seen as unavailable. It also looks like security groups are not set properly on the ELB to allow it access on the port set by K8 (in this case `30892`). I had not modified any SG's as part of creating the cluster.

I used Kops 1.8.1 for K8 1.9.3 - anyone got any ideas what's going on?

**Comment by huang-jy** [comment]
Do you have a pod running that matches the selector?

**Comment by darrenhaken** [comment]
Here is the deployment manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

**Comment by huang-jy** [comment]
Couple of errors:

```
Error from server (BadRequest): error when creating "nginx.yaml": Deployment in version "v1" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1"
```

you are also using a selector in your service definition of "app: nginx-example", but your pods have "app: nginx"

I've tweaked your definition:

```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    name: nginx-example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http-web
```

**Comment by darrenhaken** [comment]
Was the error on the `apiVersion` then?

**Comment by huang-jy** [comment]
There were two things I changed.

First was the apiVersion as I got this error:

```
Error from server (BadRequest): error when creating "nginx.yaml": Deployment in version "v1" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1"
```

The second was your selector in your service. Here's how I debugged it

Created from your config (with the apiVersion changed)
```
$ kubectl create -f nginx.yaml
deployment "nginx-example" created
service "nginx-example" created
```
Check the pods are running
```
$ kubectl get pods | grep nginx
nginx-example-569477d6d8-gfksb   1/1       Running   0          39s
nginx-example-569477d6d8-p92k9   1/1       Running   0          39s
```
Check your selector
```
$ kubectl describe service nginx-example | grep -i selector | awk '{print $2}'
app=nginx-example
```
Find pods matching your label
```
$ get pods -l $(kubectl describe service nginx-example | grep -i selector | awk '{print $2}')
No resources found.
```
No pods found, so the service won't pass anything to the pods, even though they are running....

So let's delete and recreate

```
$ kubectl delete -f nginx.yaml
deployment "nginx-example" deleted
service "nginx-example" deleted
```
```
$ kubectl create -f nginx-patched.yaml
deployment "nginx-example" created
service "nginx-example" created
```
Check the pods are running
```
$ kubectl get pods | grep nginx
nginx-example-569477d6d8-vxc5s   1/1       Running   0          5s
nginx-example-569477d6d8-zqhbv   1/1       Running   0          5s
```
Check the selector now
```
$ kubectl describe service nginx-example | grep -i selector | awk '{print $2}'
app=nginx
```
Search for pods matching the label
```
$ kubectl get pods -l $(kubectl describe service nginx-example | grep -i selector | awk '{print $2}')
NAME                             READY     STATUS    RESTARTS   AGE
nginx-example-569477d6d8-vxc5s   1/1       Running   0          37s
nginx-example-569477d6d8-zqhbv   1/1       Running   0          37s
```

So now the service should be passing the requests onto the pods. You can verify this using the kubernetes dashboard (if you have installed on your cluster)

https://[cluster api host]/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/service/default/nginx-example?namespace=default

**Comment by amalucelli** [comment]
Your internal ELB has subnets configured in the same availability zone as your node?

Are you tagging the privates nodes with the annotation `kubernetes.io/role/internal-elb` as described in [aws.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L88)

```go
// TagNameSubnetInternalELB is the tag name used on a subnet to designate that
// it should be used for internal ELBs
const TagNameSubnetInternalELB = "kubernetes.io/role/internal-elb"
```

**Comment by darrenhaken** [comment]
@amalucelli what should be annotated with kubernetes.io/role/internal-elb? 
The K8 nodes?

**Comment by huang-jy** [comment]
For internal ELBs, you tag with the annotation 

`service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"`

When I tested your yaml earlier, it did correctly create an internal-only ELB, so that is fine.

**Comment by darrenhaken** [comment]
@huang-jy did it connect to the nodes as well?

**Comment by huang-jy** [comment]
@darrenhaken yes, it picked up the pods as per your config. I use a similar method for my corporate test cluster.

The only catch you have to remember is that the ELB will resolve to a private IP and not a public IP if you use that annotation.

**Comment by darrenhaken** [comment]
@huang-jy did you have any issues with the Security Groups it creates? 

At the moment the instance nodes seem to have a default `node-xx` security group attached which restricts incoming traffic to the master. I'm wondering if the issue I have is about SG's blocking connectivity.

**Comment by huang-jy** [comment]
@darrenhaken your yaml does not create any new security groups -- or do you mean the security groups kops creates at the cluster creation?

**Comment by darrenhaken** [comment]
I mean the security groups Kops creates.

**Comment by huang-jy** [comment]
No, I had no issues. I added additional groups to it as part of the creation though, to allow the cluster to talk to other parts of my AWS estate though.

**Comment by darrenhaken** [comment]
How did you add additional groups?

**Comment by huang-jy** [comment]
Assuming the groups are already created:

```
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-01-04T10:25:26Z
  labels:
    kops.k8s.io/cluster: [clustername]
  name: master-eu-west-1a
spec:
  additionalSecurityGroups:
  - sg-xxxxxxxx
  - sg-yyyyyyyy
  - sg-zzzzzzzz
....
....
```

**Comment by darrenhaken** [comment]
And can you add any additional security groups to the ELB that K8 creates for a `Service`?

**Comment by huang-jy** [comment]
I haven't tried myself, but additionalSecurityGroups doesn't work in a service definition

```
error: error validating "test.yaml": error validating data: ValidationError(Service.spec): unknown field "additionalSecurityGroups" in io.k8s.api.core.v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by darrenhaken** [comment]
Do you have anything set on `cloudConfig` for your Kops manifest?

I noticed i had this set:

```
cloudConfig:
  disableSecurityGroupIngress: true
  elbSecurityGroup: sg-xxxxxxx
```

I wondered if that's causing the problem, I'm redeploying the cluster to see.

**Comment by darrenhaken** [comment]
@huang-jy So I did `curl {IP_OF_NODE}:{NODEPORT}` where nodeport is the one the ELB is trying to connect to. I get a connection refused. 

I have added an SG to the node to allow **all inbound/outbound** traffic but I still get the same problem. Is there any kubectl commands to verify that the ports are open?

**Comment by huang-jy** [comment]
@darrenhaken you don't normally have to hit the node directly. You have created a loadbalancer as part of the service, you should be using that.

Since you have created an internal loadbalancer, which therefore resolves to internal IPs, you can only access that if you are DirectConnected into the VPC, or you are going through a bastion. Please confirm you are doing one of those. If not, take off that internal annotation to make the ELB public.

Assuming you are able to access it using the internal IP, I found another error.

Your service definition describes how to port map the requests. You described this:

```
  ports:
  - name: http
    port: 80
    targetPort: http-web
```

But have not declared http-web anywhere.

This leads to this message showing when trying to curl the elb:
```
curl: (52) Empty reply from server
```

Change that to:

```
  ports:
  - name: http
    port: 80
    targetPort: 80
```

And it should work

```
$ curl -IL [elb-host-name]
HTTP/1.1 200 OK
Server: nginx/1.7.9
Date: Thu, 22 Feb 2018 17:43:06 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 23 Dec 2014 16:25:09 GMT
Connection: keep-alive
ETag: "54999765-264"
Accept-Ranges: bytes
```

For summary, here's the full config I used
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    name: nginx-example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
```

**Comment by darrenhaken** [comment]
I tried to connect directly to the node rather than through the ELB to verify if I could at least connect directly to the node.

I do have a VPN to the VPC and can access other resources in the account.

Below are **all** the files I have used to create the cluster

### kops manifest:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-02-21T11:51:01Z
  name: k8.dev.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://bucket/k8.dev.k8s.local
  dnsZone: dns.fake.zone.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.k8.dev.k8s.local
  networkCIDR: 10.90.0.0/16
  networkID: vpc-4c4dca2b
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.xx.x.x/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.xxx.0.0/22
    id: subnet-id1
    name: subnet-x1
    type: Private
    zone: eu-west-1a
  - cidr: 10.xxx.16.0/22
    id: subnet-id2
    name: private-b
    type: Private
    zone: eu-west-1b
  - cidr: 10.xxx.32.0/22
    id: subnet-id3
    name: private-c
    type: Private
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-21T11:51:01Z
  labels:
    kops.k8s.io/cluster: k8.dev.k8s.local
  name: master-eu-west-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - private-a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-21T11:51:01Z
  labels:
    kops.k8s.io/cluster: k8.dev.k8s.local
  name: nodes
spec:
  associatePublicIp: false
  additionalSecurityGroups:
  - sg-xxxxx
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 6
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - sg-xx1
  - sg-xx2
  - sg-xx3

```

### Deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
spec:
  selector:
    matchLabels:
      app: nginx-example
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx-example
        image: nginx:1.7.9
        ports:
        - name: http-port
          containerPort: 80
        
```

### Service:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
spec:
  selector:
    app: nginx-example
  type: LoadBalancer
  ports:
  - name: nginx-example
    port: 80
    targetPort: 80
```
