### ISSUE TITLE
Update causing protokube downgrade?

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kops#4543]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.0`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
`1.9.1`

3. What cloud provider are you using?
`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
$ KOPS_STATE_STORE=s3://my-test.my-domain.com kops edit ig --name my.cluster.k8s.local nodes
<Modified the AMI id>

$ KOPS_STATE_STORE=s3://my-test.my-domain.com kops update cluster --name my.cluster.k8s.local
I0228 23:28:31.172089   33902 apply_cluster.go:450] Gossip DNS: skipping DNS validation
...
```

5. What happened after the commands executed?

The output of the commands above showed that protokube was being downgraded from v1.8.1 to 1.8.0
```
Will modify resources:
  LaunchConfiguration/master-us-west-2a.masters.my.cluster.k8s.local
  	UserData
  	                    	...
  	                    	  set -o pipefail

  	                    	+ NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.8.0/linux/amd64/nodeup
  	                    	- NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.8.1/linux/amd64/nodeup
  	                    	  NODEUP_HASH=
...
  	                    	+   name: protokube:1.8.0
  	                    	-   name: protokube:1.8.1
```

6. What did you expect to happen?
Protokube version should've remained unchanged.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-02-28T22:48:26Z
  name: my.cluster.k8s.local
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["ec2:DescribeVpcs"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["elasticloadbalancing:*"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-bucket/my.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.1
  masterPublicName: api.my.cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: 172.20.0.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 172.20.4.0/22
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 172.20.8.0/22
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
