### ISSUE TITLE
Please document etcdCluster volumeType setting

### ISSUE THREAD

**Issue by vainu-arto** [kubernetes/kops#4557]
Currently it's possible to set the volume type for etcd EBS volumes, but one needs to use the source to find out how. As an example:

```
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
      volumeType: io1
    - instanceGroup: master-eu-west-1b
      name: b
      volumeType: io1
    - instanceGroup: master-eu-west-1c
      name: c
      volumeType: io1
    name: main
```

It seems that volume size is also configurable, and should be documented. It seems to me that the configured amount of IOPS isn't configurable, should it be? It's not a massive amount of work to configure manually, mainly since kops update cluster doesn't overwrite it (like it does the volume type).
