### ISSUE TITLE
Cluster update fails to detect additional VPC CIDRs

### ISSUE THREAD

**Issue by Mikulas** [kubernetes/kops#4578]
Reproduced with both 1.7.1 and 1.9.0-alpha.1 (git-034bad8).
Cloud: AWS
/kind bug

### What is the simplest way to reproduce this issue?

1. Assume an existing VPC `vpc-a` with CIDR (for example `172.20.0.0/16`)
2. Attach new CIDR the the same VPC `vpc-a`, for example `172.22.0.0/16`
3. Create a new kops cluster in the same vpc `vpc-a` within the `172.22.0.0/16` CIDR.
4. Invoking `kops update cluster $NAME` will fail with
>  error running task "VPC/$NAME" (9m59s remaining to succeed): Field cannot be changed: CIDR

<details>
<summary>Relevant v10 logs</summary>

```
I0305 12:14:51.968876   42804 executor.go:157] Executing task "VPC/$NAME": *awstasks.VPC {"Name":"$NAME","Lifecycle":"Sync","ID":"vpc-a","CIDR":"172.22.0.0/16","EnableDNSHostnames":null,"EnableDNSSupport":true,"Shared":true,"Tags":{"KubernetesCluster":"$NAME","Name":"$NAME","kubernetes.io/cluster/$NAME":"shared"}}
I0305 12:14:51.969091   42804 request_logger.go:45] AWS request: ec2/DescribeVpcs
I0305 12:14:52.028683   42804 vpc.go:84] found matching VPC *awstasks.VPC {"Name":"eu-central-1.k8s.mangoweb.org","Lifecycle":null,"ID":"vpc-a","CIDR":"172.20.0.0/16","EnableDNSHostnames":null,"EnableDNSSupport":null,"Shared":null,"Tags":{"KubernetesCluster":"eu-central-1.k8s.mangoweb.org","Name":"eu-central-1.k8s.mangoweb.org"}}
I0305 12:14:52.028899   42804 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I0305 12:14:52.092799   42804 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I0305 12:14:52.160730   42804 changes.go:80] Field changed "Name" actual="eu-central-1.k8s.mangoweb.org" expected="$NAME"
I0305 12:14:52.160789   42804 changes.go:80] Field changed "CIDR" actual="172.20.0.0/16" expected="172.22.0.0/16"
I0305 12:14:52.160828   42804 changes.go:80] Field changed "Tags" actual="map[Name:eu-central-1.k8s.mangoweb.org KubernetesCluster:eu-central-1.k8s.mangoweb.org]" expected="map[KubernetesCluster:$NAME Name:$NAME kubernetes.io/cluster/$NAME:shared]"
W0305 12:14:52.160942   42804 executor.go:109] error running task "VPC/$NAME" (9m58s remaining to succeed): Field cannot be changed: CIDR
```
</details>

<details>
<summary>Redacted spec</summary>

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: $NAME
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://$STATE/$NAME
  dnsZone: Z2YWA7XRM6G2RG
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - Priority
    runtimeConfig:
      scheduling.k8s.io/v1alpha1: "true"
  kubelet:
    featureGates:
      PodPriority: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.$NAME
  networkCIDR: 172.19.0.0/16
  networkID: vpc-05e1616d
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 193.86.64.162/32
  subnets:
  - cidr: 172.19.32.0/19
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.19.64.0/19
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.19.96.0/19
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.19.0.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.19.4.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.19.8.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: master-eu-central-1a
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: master-eu-central-1b
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: master-eu-central-1c
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-4fcc1622
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 50
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```
</details>

### What did you expect to happen?

Kops should have detected the second CIDR instead of attempting to update the first one.

### Related issue

Same error as in https://github.com/kubernetes/kops/issues/2830, but that one is about changing the CIDR. This issue does not require changing the CIDR as it's already properly defined.

**Comment by krogon** [comment]
Can you check removing `spec.networkCIDR` and add your second CIDR as `spec.AdditionalNetworkCIDRs` ?

**Comment by Mikulas** [comment]
Yeah that one does work with the `1.9.0-alpha.1 (git-034bad8)`. It fails with 1.7.1 as that version does not have the additional CIDRs implemented. Thank you.

```diff
@ kops edit cluster @
- networkCIDR: 172.22.0.0/16
+ additionalNetworkCIDRs:
+   - 172.22.0.0/16
```

<details>
<summary>This is the spec I've used</summary>

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: v2.eu-central-1.k8s.mangoweb.org
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s.mangoweb.org/v2.eu-central-1.k8s.mangoweb.org
  dnsZone: Z2YWA7XRM6G2RG
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.v2.eu-central-1.k8s.mangoweb.org
  additionalNetworkCIDRs:
  - 172.22.0.0/16
  networkID: vpc-05e1616d
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 193.86.64.162/32
  subnets:
  - cidr: 172.22.32.0/19
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.22.64.0/19
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.22.96.0/19
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.22.0.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.22.4.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.22.8.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: v2.eu-central-1.k8s.mangoweb.org
  name: master-eu-central-1a
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: v2.eu-central-1.k8s.mangoweb.org
  name: master-eu-central-1b
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: v2.eu-central-1.k8s.mangoweb.org
  name: master-eu-central-1c
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: v2.eu-central-1.k8s.mangoweb.org
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-4fcc1622
  associatePublicIp: true
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 50
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```

</details>

Is this still a bug? Why does kops make the distinction between CIDR and an AdditionalCIDR at all?
