### ISSUE TITLE
Bug in normalizing container images' location

### ISSUE THREAD

**Issue by ihac** [kubernetes/kops#4579]
There (might) be a bug in function [RemapImage](https://github.com/kubernetes/kops/blob/master/pkg/assets/builder.go#L124) when using user-defined dns-controller location. The function should return after overriding location by env `DNSCONTROLLER_IMAGE`([line 146](https://github.com/kubernetes/kops/blob/master/pkg/assets/builder.go#L146)), otherwise the location of dns-controller would be normalized again with `a.AssetsLocation.ContainerRegistry`.

FYI, the k8s components and dns-controller image cannot be pulled in CN due to network issue. So to deploy k8s in CN, I added a few code in `cmd/kops/create_cluster.go` and initialized the `cluster.Spec.Assets` with a new container registry. However, it turned out that the registry mirror  of dns-controller was duplicated as below:
``` yaml
    spec:
      containers:
      - command:
        - /usr/bin/dns-controller
        - --watch-ingress=false
        - --dns=gossip
        - --gossip-seed=127.0.0.1:3999
        - --zone=*/*
        - -v=2
        image: <my_registry>/<my_registry>-dns-controller:1.8.0
        name: dns-controller
```
What I really expected is `<my_registry>/dns-controller:1.8.0`.
