### ISSUE TITLE
Deep merge values for toolbox template

### ISSUE THREAD

**Issue by gwkunze** [kubernetes/kops#4662]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

We've been using the `kops toolbox template` command to generate our kops configuration. But noticed that it does a simple key-based merge if you specify multiple values files. This is unlike the templating behavior of Helm which does a deep merge of values. For example if I have the following two files:

default.yaml
```yaml
masters:
  machineType: m4.xlarge
  additionalSecurityGroups:
    - sg-12345678
```

overrides.yaml
```yaml
masters:
  machineType: t2.medium 
```

And run kops toolbox template with `--values default.yaml --values overrides.yaml` the effective values become:
```yaml
masters:
  machineType: t2.medium 
```

instead of:
```yaml
masters:
  machineType: t2.medium
  additionalSecurityGroups:
    - sg-12345678
```

Since the masters key in override.yaml overrides anything above it.

2. Feel free to provide a design supporting your feature request.

This would change existing templating behavior, but implementation should be simple, I already got it to work by copying the [mergeValues](https://github.com/kubernetes/helm/blob/master/cmd/helm/install.go#L292) function from Helm and swapping the for loop in [newTemplateContext](https://github.com/kubernetes/kops/blob/master/cmd/kops/toolbox_template.go#L226) with a call the the `mergeValues` function.
I'm looking into getting my company signed for contributing so I can make a PR.
