### ISSUE TITLE
kube-proxy flag (--cluster-cidr) is wrong when using amazon-vpc-routed-eni CNI plugin

### ISSUE THREAD

**Issue by liwenwu-amazon** [kubernetes/kops#4674]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
kops version
Version dev (git-2db1d17)
```
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
1.9.3
```

3. What cloud provider are you using?
 
```
AWS
```
4. What commands did you run?  What is the simplest way to reproduce this issue?
```
1. create a cluster using amazon-vpc-routed-eni CNI
2. create a kubernet services, 
# Run the Pods.
kubectl run --namespace=policy-demo nginx --replicas=2 --image=nginx

# Create the Service.
kubectl expose --namespace=policy-demo deployment nginx --port=80
3. create a pod
# Run a Pod and try to access the `nginx` Service.
$ kubectl run --namespace=policy-demo access --rm -ti --image busybox /bin/sh
Waiting for pod policy-demo/access-472357175-y0m47 to be running, status is Pending, pod ready: false

If you don't see a command prompt, try pressing enter.

/ # wget -q nginx -O -
```

5. What happened after the commands executed?
```
all Pod to Service (such as nginx) traffic are "source-nat"
```
6. What did you expect to happen?
```
Pod to Service (nginx) traffic should NOT be "source-nat"
```

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
kops get cluster --name cni-mar8-1.k8s.local -oyaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-08T19:49:04Z
  name: cni-mar8-1.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-test-com-state-store/cni-mar8-1.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.cni-mar8-1.k8s.local
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0066bd79
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 10.0.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.0.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: public
    nodes: public
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
```
kube-proxy are started with wrong --cluster-cidr

In my case,  the Pod's IP are allocated from subnet 10.0.96.0/19, but I am seeing following flags
 /usr/local/bin/kube-proxy --cluster-cidr=10.0.128.0/17 --conntrack-max-per-core=131072
```
10. I am seeing wrong iptable entries added
```
#the following will trigger Pod to service traffic "source-nat"
-A KUBE-SERVICES ! -s 10.0.128.0/17 -d 10.0.16.203/32 -p tcp -m comment --comment "policy-demo/nginx: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
``

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.
