### ISSUE TITLE
Cannot add node-monitor-grace-period parameter

### ISSUE THREAD

**Issue by namloc2001** [kubernetes/kops#4678]
------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
Version 1.8.0
```
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

The following to create cluster configuration:
```
kops create cluster --zones=eu-west-2a,eu-west-2b --name=name.k8s.local --cloud aws
```
Then to edit the cluster configuration in vi:
```
kops edit cluster --name=name.k8s.local
```
Add these settings to the cluster yaml:
```
kubeControllerManager:
  nodeMonitorGracePeriod: 20s
```
(have also tried: "20s", "0m20s", "20", "20" etc etc)

Then to save and exit:
```
:wq
```

5. What happened after the commands executed?
Kops states error, with message:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
# ...
#       legacy: false
#     kubeControllerManager:
# +     nodeMonitorGracePeriod: 20s
#       terminatedPodGCThreshold: 10
#     kubelet:
# ...
```

6. What did you expect to happen?
Kops to accept parameter and save file successfully for build.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-14T16:41:12Z
  name: name.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://name.k8s.com/name.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    terminatedPodGCThreshold: 10
  kubelet:
    allowPrivileged: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.7
  masterInternalName: api.internal.name.k8s.local
  masterPublicName: api.name.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-2a
    type: Public
    zone: eu-west-2a
  - cidr: 172.20.64.0/19
    name: eu-west-2b
    type: Public
    zone: eu-west-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
N/A

9. Anything else do we need to know?
N/A
