### ISSUE TITLE
route53 entry not deleted on cluster deletion

### ISSUE THREAD

**Issue by smartpierre** [kubernetes/kops#4689]
Hello, here is a report of my experience :)

1. What `kops` version are you running? The command `kops version`, will display
 this information.

> 1.8.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

> Client 1.9.3
> Server 1.8.6

3. What cloud provider are you using?

> AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

> created a simple cluster
> added a loadbalancer service with dns
>deleted the cluster

5. What happened after the commands executed?

> cluster was created
> loadbalancer was created
> dns entry in route53 was created
> cluster was deleted
> load balancer was deleted
> dns entry in route53 was NOT deleted

6. What did you expect to happen?

> dns entry in route53 should have been deleted

9. Anything else do we need to know?

> occured multiple times (did a workshop with my team, everyone created a cluster, at the end, everyones delete his cluster, dns entries are still here)
> this problem does not occur when we keep the cluster alive, and just delete the load balancer

**Comment by justinsb** [comment]
How are you creating the loadbalancer DNS entry (dns-controller or external-dns or something else?)  Do you have a link to the workshop?

**Comment by smartpierre** [comment]
Here is a snippet of my LB : 
```
apiVersion: v1
kind: Service
metadata:
  name: frontend-test-lb
  annotations:
    dns.alpha.kubernetes.io/external: "test.mydomain.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: |-
      arn:aws:acm:eu-west-2:xxxxxxxxxxx:certificate/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: frontend-test
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 80
    protocol: TCP
```

**Comment by smartpierre** [comment]
Here is the procedure we followed : 

## Step 2 : create a deployment

Get file : https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/run-application/deployment.yaml

Ask politely kubectl to create the deployment : `kubectl apply -f deployment.yaml`

Ask politely kubectl what's the state of the deployment : `kubectl describe deployment nginx-deployment`

List the pods created by the deployment : `kubectl get pods -l app=nginx`

Display information about a pod : `kubectl describe pod <pod-name>`

## Step 3 : update a deployment

Get file : https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/run-application/deployment-update.yaml

Apply the changes : `kubectl apply -f deployment-update.yaml`

Watch kubernetes do its magic : `kubectl get pods -l app=nginx`

## Step 4 : expose the pods

Put this in a file :

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    dns.alpha.kubernetes.io/external: "nginx.MYSUBDOMAIN"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
```

Create the service : `kubectl apply -f nginx-service.yaml`

Check the state of the service : `kubectl get svc`

More info : `kubectl describe svc nginx-service`

Wait a bit, and you should be able to see the nginx welcome page on `nginx.MYSUBDOMAIN`

## Step 7 : cleanup

Delete the deployment : `kubectl delete deployment nginx-deployment`

Delete the cluster : `kops delete cluster --name ${NAME} --yes`
