### ISSUE TITLE
Unable to create a cluster through an YAML file - Routing table is not updated duo to missing tag.

### ISSUE THREAD

**Issue by waldman** [kubernetes/kops#4691]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0-alpha.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
AWS_PROFILE=$aws_profile kops create \
    --state=${kops_state_bucket} \
    --filename k8s-manifests/kops/create-cluster.yaml

AWS_PROFILE=$aws_profile kops create secret \
    --state=${kops_state_bucket} \
    --name ${cluster_name}.${platform_domain} sshpublickey admin -i <pub_key_path>

AWS_PROFILE=$aws_profile kops update cluster \
     --state=${kops_state_bucket} \
     ${cluster_name}.${platform_domain} \
     --yes
```
Here is the yaml file that I'm using to create the cluster: 
```
---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: cluster-test-2.[...redacted...]
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    disableSecurityGroupIngress: true
    elbSecurityGroup: [...redacted...]
    kubeScheduler:
      usePolicyConfigMap: true
  cloudProvider: aws
  configBase: s3://[...redacted...]/cluster-test-2.[...redacted...]
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.cluster-test-2.[...redacted...]
  masterPublicName: api.cluster-test-2.[...redacted...]
  networkCIDR: 10.250.0.0/16
  networkID: [...redacted...]
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.250.12.0/23
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 10.250.14.0/23
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.250.16.0/23
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: public
    nodes: public

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster-test-2.[...redacted...]
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 100
  minSize: 3
  rootVolumeSize: 500
  rootVolumeType: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster-test-2.[...redacted...]
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster-test-2.[...redacted...]
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster-test-2.[...redacted...]
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c
```

5. What happened after the commands executed?
The cluster is created but duo to a missing tag on the routing table the cluster doesn't get to a ready state. 

The DNS pods fails to get up duo to the masters being unable to update the AWS routing table duo to the missing `KubernetesCluster` tag, The missing tag causes a permission issue. 

Adding the tag manually causes the cluster to get up.

Two side notes:
- The routing table is marked as `shared` when it should be `owned` (It is created together with the subnets that I'm passing manually and are being created by kops it self).
- The route table is not deleted by the `kops delete cluster <cluster_name> --yes`

6. What did you expect to happen?
The cluster should be up and running after a couple of minutes without the need of any manual intervention. 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
Unfortunately the cluster was already deleted but it was created through the yaml file above.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
When doing a `describe node` on a single master node:
```
  Warning  FailedToCreateRoute  4m (x36057 over 20h)  route_controller  (combined from similar events): Could not create route 1ecb7328-28a4-11e8-8c8b-025304dab174 100.96.0.0/24 for node ip-10-250-7-150.ec2.internal after 625.015462ms: error creating AWS route (100.96.0.0/24): "UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: HVr5azsEkQ0ISGwzGZCBbaNFaQ1R0ZiBHFN17U5BNtBu5l9L3sDi254CxetlTiUtnq5RGQtRQsMIGo3IdaVIbxYgRpps348muefOpCw6NTGQH98EphPK-Xmwsnz9yracvs0ZsHjI_xtnWMJ2RYwnOdYwzY4CXXdhL4ppK9m6LXs6KrDu0uQo_oxzevi4mbTQyvip4vAPobYYJz0qor2Uc9UhT8I8XSuAOt8w6nG-4AUD5BwgKbtyMwW3jv1qAHSCHOIYflnv2niR_4fL1WLL034j5zjWgFQ_madJVthQRxxwJmbiCMfpI1nIQE8_-bH22Sf435nbIjW3RpzXXcZRyeMu35hXM6NZ7IhWLc6SiJR32_8aWOe-eo8edvr76KTl_zEIChnse9CrairSp67xc15QjX8t32xf7Hcn-kZXaWR1hhnD-9qyjR05zTR3UkhPfujePWTlp4uKs3YGoTJQeuuvn8qVRti6BG3Yw3fpFuswftN2Ad9feKFaZn4c-dqXFityVxGZjekX6iIG4UkNYPXFbKnSP9Z5bAAmNRGSDUGs2MOiYMnfhgQ58wT-fKeKAndV8GbeYB-PUO7BEqz9TYiwe5JgX-QEEu-sF7Q_80hy9Ndwajws3jmzhSbtXeMQevGdDB5dQ4eVJE6XdnbTGfNZ9Q\n\tstatus code: 403, request id: 31da3d04-ed78-4fee-876d-581bc9496e90"
```

When checking the events on the dns-controller pod:
```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  44s (x4057 over 19h)  default-scheduler  0/3 nodes are available: 3 NodeNetworkUnavailable.
```

When checking the cluster events:
```
root@ip-10-250-7-150:~# kubectl -n kube-system get events
LAST SEEN   FIRST SEEN   COUNT     NAME                                                    KIND      SUBOBJECT   TYPE      REASON             SOURCE              MESSAGE
3m          19h          4057      dns-controller-77b5fd476-7wlhj.151c3a14066db47f         Pod                   Warning   FailedScheduling   default-scheduler   0/3 nodes are available: 3 NodeNetworkUnavailable.
3m          19h          4057      kube-dns-autoscaler-787d59df8f-5sl5n.151c3a13cb7de079   Pod                   Warning   FailedScheduling   default-scheduler   0/3 nodes are available: 3 NodeNetworkUnavailable, 3 PodToleratesNodeTaints.
3m          19h          4057      kube-dns-c58977f6c-hn42v.151c3a13c606f3e2               Pod                   Warning   FailedScheduling   default-scheduler   0/3 nodes are available: 3 NodeNetworkUnavailable, 3 PodToleratesNodeTaints.
```

9. Anything else do we need to know?
The subnets are being created by kops and didn't existed prior to running the `kops cluster update` (the same for the route table).... Aaaand you guys rocks! \o/
