### ISSUE TITLE
Add support for custom configs passed to --runtime-config

### ISSUE THREAD

**Issue by ls-jftheroux** [kubernetes/kops#474]
I need to enable NetworkPolicy right now. My understanding is that I need to pass some options to --runtime-config for kube-apiserver to do so.

It's currently not possible with kops right now.

Having the ability to pass custom configs to k8s components would be great. As right now, although kops is awesome, it's a bit limiting in some cases.

An example of what I'm looking for:

```
--runtime-config=extensions/v1beta1/networkpolicies=true
```

**Comment by pacuna** [comment]
also interested in this. I'm trying to test the new ScheduleJob type and I need to pass options via runtime-config to the api-server

**Comment by pacuna** [comment]
@justinsb thanks! So, this options should be passed when running the create cluster command?

**Comment by justinsb** [comment]
For now you need to edit the cluster spec post-creation.  We can probably make this better, but this is "step one".

So you would do

`kops create cluster`; `kops edit cluster`; `kops update cluster`

In the edit, you will add a section under the main spec that looks like

```
  kubelet:
    kubeAPIServer:
      runtimeConfig:
        "extensions/v1beta1/networkpolicies": "true"
```

But... you may want to let me test this properly first!  It's implemented so I automatically closed the ticket, but it isn't fully tested.

**Comment by pacuna** [comment]
@justinsb thanks. I actually tried that and I wasn't able to turn the config I needed. One thing I notice is that the kubeApiServer should be outside the kubelet section right? Or else it gets deleted

**Comment by Shrugs** [comment]
Just to confirm to any other people that stumble into this via google, the config does need to be at the root of the spec like so:

```yml
spec:
  kubeAPIServer:
    runtimeConfig:
      "group/api/resource": "true"
```

**Comment by chrislovecnm** [comment]
@Shrugs if you are able to help to update the docs, that would be amazing

**Comment by Shrugs** [comment]
@chrislovecnm Good idea, I'll plan on it.

**Comment by alex88** [comment]
I've added

```
spec:
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
```

ran `kops update cluster --yes` but nothing changed, `kops rolling-update cluster` and `kops upgrade cluster` doesn't show any pending changes
