### ISSUE TITLE
Failed to get system container stats for "/system.slice/kubelet.service" / docker.service kubelet issue

### ISSUE THREAD

**Issue by kaspernissen** [kubernetes/kops#4798]
**_1. What `kops` version are you running? The command `kops version`, will display
 this information._**
Kops version 1.8.1

**_2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag._**
Kubernetes version 1.8.6

**_3. What cloud provider are you using?_**
AWS

**_4. What commands did you run?  What is the simplest way to reproduce this issue?_**

After noticing some increasing load on some of our nodes, we started to investigate a bit. I'm not sure whether the following is exactly the casue for this increase, but this what we found in the logs. 
![increased_consumption](https://user-images.githubusercontent.com/4429108/37902753-bb1a664a-30f5-11e8-807a-d40a3cb81e4b.png)

To reproduce, I tried spinning up a new cluster with a similar configuration as our production cluster and found the same error in the log. 

```
export KOPS_NAME="Cluster"
export KOPS_STATE_STORE="s3://STORE"
export PRIVATE_HOSTED_ZONE_ID="ID"

kops create cluster \
  --name $KOPS_NAME \
  --state $KOPS_STATE_STORE \
  --node-count 3 \
  --zones eu-west-1a \
  --master-zones eu-west-1a \
  --dns-zone=${PRIVATE_HOSTED_ZONE_ID} \
  --dns private \
  --node-size t2.medium \
  --master-size t2.small \
  --topology private \
  --networking weave \
  --image kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14 \
  --kubernetes-version=1.8.6 \
  --bastion \
  --yes
```

after spinning up the cluster, SSH into one of the worker nodes and grep the kubelet logs
```
tail -f /var/log/syslog | grep kubelet
```

_**5. What happened after the commands executed?**_
kubelet produces the following 2 error messages every 10 seconds

```
Mar 26 10:54:33 ip-172-20-60-18 kubelet[1221]: E0326 10:54:33.720576    1221 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Mar 26 10:54:33 ip-172-20-60-18 kubelet[1221]: E0326 10:54:33.720602    1221 summary.go:92] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
```

**_6. What did you expect to happen?_**
No errors in the log

_**7. Please provide your cluster manifest. Execute**_
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-26T10:44:45Z
  name: k8s.test.example.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://example-test-k8s-state-store/k8s.test.example.com
  dnsZone: ZF3HEQO28R8JR
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterPublicName: api.k8s.test.example.com
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.20.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  topology:
    bastion:
      bastionPublicName: bastion.k8s.test.example.com
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-26T10:44:45Z
  labels:
    kops.k8s.io/cluster: k8s.test.example.com
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-26T10:44:45Z
  labels:
    kops.k8s.io/cluster: k8s.test.example.com
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-26T10:44:45Z
  labels:
    kops.k8s.io/cluster: k8s.test.example.com
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
```

**_8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here._**

_**9. Anything else do we need to know?**_

Possible fix: 
After searching the internet for similar issues, I stumbled upon the following issue: https://stackoverflow.com/questions/46726216/kubelet-fails-to-get-cgroup-stats-for-docker-and-kubelet-services

The solution seems to be the following:

```
sudo vim /etc/sysconfig/kubelet

```
add at the end of DAEMON_ARGS string:
```
 --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice
```
and finally restart the kubelet
```
sudo systemctl restart kubelet
```
This removes the error. However, this is rather cumbersome to do when having X number of nodes that all outputs this error. I tried looking into the code, and found the following place (link: https://github.com/kubernetes/kops/blob/e634143c434b060a0ca0819f169f55fca2d1f1d7/nodeup/pkg/model/kubelet.go), where this might need to be added. I don't have enough knowledge of whether this is something that should be in Kops or whether it might be a Kubernetes issue.
