### ISSUE TITLE
kops 1.8.1 default configuration creates unnecessary logspam

### ISSUE THREAD

**Issue by number101010** [kubernetes/kops#4814]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.8.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.8.6

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops create cluster`

5. What happened after the commands executed?

A cluster was created with the api-server being passed a long list of parameters under  `--admission-control` including `Priority` which seems to be causing the below log messages.  These messages are logged every second by every kube-apiserver

```
I0328 00:36:50.862614 6 wrap.go:42] GET /apis/scheduling.k8s.io/v1alpha1/priorityclasses?resourceVersion=0: (185.903µs) 404 [[kube-apiserver/v1.8.6 (linux/amd64) kubernetes/6260bb0] 127.0.0.1:44026]
E0328 00:36:50.862862 6 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *scheduling.PriorityClass: the server could not find the requested resource (get priorityclasses.scheduling.k8s.io)
```

6. What did you expect to happen?

The `Priority` parameter should not be passed because it causes insane logspam or perhaps some other configuration piece is missing?

9. Anything else do we need to know?
I was able to mitigate the issue by adding the following to my clusterspec:
```
spec:
  kubeAPIServer:
    admissionControl: 
      - NamespaceLifecycle
      - LimitRanger
      - ServiceAccount
      - PersistentVolumeLabel
      - DefaultStorageClass
      - DefaultTolerationSeconds
      - NodeRestriction
      - ResourceQuota
```
This is the standard list of admission plugins selected by kops minus `Initializers` and `Priority`.  I removed `Initializers` because it's alpha and I did not pass the appropriate feature flag to turn it on.

Does this seem correct?  Is there some other misconfiguration perhaps that's causing the logspam?
