### ISSUE TITLE
 1.9.0-beta.1， gossip-based  cluster, nodes can not connect to master

### ISSUE THREAD

**Issue by eisig** [kubernetes/kops#4889]
1. What `kops` version are you running?

Version 1.9.0-beta.1 (git-210a7bfe9)

2. What Kubernetes version are you running? 
1.9.7-beta.0

3. What cloud provider are you using?

aws (cn-northwest-1)

4. What commands did you run?  What is the simplest way to reproduce this issue?
export NAME=test-nx2.k8s.local
kops create cluster \
    --master-zones ${AWS_REGION}a --master-count 1 \
    --zones ${AWS_REGION}a,${AWS_REGION}b --node-count 1 \
    --network-cidr ${VPC_NETWORK_CIDR} \
    --vpc ${VPC_ID} \
    --image ${AMI} \
    --networking weave \
    --kubernetes-version=$KUBERNETES_VERSION_URL \
     --name=$NAME \
     --authorization=rbac \
     --associate-public-ip=true \
     --topology public \
      --out=. \
    --target=terraform \
    -v 8

5. What happened after the commands executed?

   the nodes instance fail to start.  It can not look up host    api.internal.test-nx2.k8s.local
  I found  kops did not add api.internal.test-nx2.k8s.local to /etc/hosts

```
# Begin host entries managed by kops - do not edit
10.1.32.67 etcd-a.internal.test-nx2.k8s.local etcd-events-a.internal.test-nx2.k8s.local
# End host entries managed by kops
```
6. What did you expect to happen?
  when I use previous version build from release-1.9 
Version 1.9.0-alpha.3 (git-c707c82f6). 
The cluster  is OK. 
```
# Begin host entries managed by kops - do not edit
10.1.10.24 api.internal.test-nx2.k8s.local etcd-a.internal.test-nx.k8s.local etcd-events-a.internal.test-nx.k8s.local
# End host entries managed by kops
```

7. Please provide your cluster manifest. Execute

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-03T10:41:10Z
  name: test-nx2.k8s.local
spec:
  additionalPolicies:
    master: "[\n  {\n    \"Effect\": \"Allow\",\n    \"Action\": [\"autoscaling:DescribeAutoScalingInstances\",\"autoscaling:DescribeTags\"],\n
      \   \"Resource\": [\"*\"]\n  }\n  \n]\n"
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-xxxxx/test-nx2.k8s.local
  docker:
    logDriver: ""
    logOpt:
    - max-size=20m
    registryMirrors:
    - https://registry.docker-cn.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: https://s3.cn-north-1.amazonaws.com.cn/xxxx/kubernetes/release/v1.9.7-beta.0
  masterInternalName: api.internal.test-nx2.k8s.local
  masterPublicName: api.test-nx2.k8s.local
  networkCIDR: 10.1.0.0/16
  networkID: vpc-fxxxxx
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.1.32.0/24
    name: cn-northwest-1a
    type: Public
    zone: cn-northwest-1a
  - cidr: 10.1.64.0/24
    name: cn-northwest-1b
    type: Public
    zone: cn-northwest-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

9. Anything else do we need to know?

OS version:  Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)
