### ISSUE TITLE
Unable to access API server after restarting the cluster

### ISSUE THREAD

**Issue by sanketjpatel** [kubernetes/kops#4967]
Hi,
I noticed a weird behavior with kops on aws.
I had setup the cluster, created a few deployments, running fine, all good.

I then terminated the nodes, master, and bastion. Updated the autoscaling groups for them to desired, min, max of 0. Went to sleep. Woke up in the morning and updated the autoscaling groups back to their original configuration…
Nodes - 2 (desired, min and max)
Master - 1
Bastion - 1

New instances were running, showing healthy. However, the api-loadbalancer showed up as unhealthy (0 out of 1 instances OutOfService). I waited for about 30 mins and still it was showing unhealthy. So, I SSH’ed into the master via my bastion and ran the following command `bash <(curl -s http://169.254.169.254/latest/user-data)`

It still took about 1 hour for the api-loadbalancer to become healthy and accept traffic. The original deployments were still there (that’s great!)

I want to understand why it took so long and if there’s a way to speed up this process. Initializing the cluster from scratch only took about 5-10 mins. I have copied over the `/var/log/syslog` from the master and going through it, but wondering if I should be looking at something else. Thanks!

---------------------------------------
1. What `kops` version are you running? The command `kops version`, will display
 this information.
`1.8.1`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?
Terminate the instances on a running cluster, update autoscaling groups to 0 for nodes, master, bastion. Once all instances have been terminated, update autoscaling groups back to their original configuration.

5. What happened after the commands executed?
The API server's Loadbalancer showed instances as `OutOfService`, although the master and node instances were in a `Healthy` status.

6. What did you expect to happen?
The CNI config gets initialized sooner. 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-10T13:53:05Z
  name: *****
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://*****
  dnsZone: *****
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.7
  masterPublicName: api.*****
  networkCIDR: 172.20.0.0/16
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  topology:
    bastion:
      bastionPublicName: bastion.*****
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-10T13:53:06Z
  labels:
    kops.k8s.io/cluster: *****
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-10T13:53:05Z
  labels:
    kops.k8s.io/cluster: *****
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-10T13:53:05Z
  labels:
    kops.k8s.io/cluster: *****
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.
