### ISSUE TITLE
Maximum worker node disk size?

### ISSUE THREAD

**Issue by cablespaghetti** [kubernetes/kops#4979]
1. What `kops` version are you running? 1.9.0

2. What Kubernetes version are you running? 1.9.1

3. What cloud provider are you using? AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops create cluster --node-size r4.xlarge mydomain.com --master-size m3.medium --ssh-public-key ~/.ssh/id_rsa.pub --ssh-access my-ip/32 --admin-access my-ip/32 --cloud aws --zones eu-west-1a,eu-west-1b,eu-west-1c --master-zones eu-west-1a,eu-west-1b,eu-west-1c --node-count 3 --node-volume-size 4096

5. What happened after the commands executed? The masters all come up as expected but the worker nodes which have the large volume size configured just repeatedly start and immediately stop during initialization.

6. What did you expect to happen? A working cluster with 3 worker nodes with 4TB volumes to come up.

Is there some kind of maximum disk size with kops? I looked up the gp2 volume disk size and it's 16TB.

**Comment by huang-jy** [comment]
Does it still happen if you don't explicitly specify the node volume size?

**Comment by huang-jy** [comment]
Can you pastebin (or using a method of your choice) the logs from one of the nodes? I'm not sure what's going on here but maybe it'll help one of the team debug it. 

Also, pasting the cluster definition may be of help.

**Comment by cablespaghetti** [comment]
I unfortunately haven't been able to get on any of the nodes to get the logs off, because it seems to get terminated before SSH comes up.

I'll see if I can get the cluster definition shortly.

**Comment by cablespaghetti** [comment]
Command:

```
kops create cluster --node-size r4.xlarge --master-count 3 --master-size m3.medium --ssh-public-key ~/.ssh/id_rsa.pub --ssh-access 1.2.3.4/32 --admin-access 1.2.3.4/32 --node-count 3 --vpc vpc-0882e56c --subnets subnet-064a3062,subnet-dcc4b5aa --cloud aws --zones eu-west-1a,eu-west-1b --master-zones eu-west-1a,eu-west-1b --utility-subnets subnet-064a3062,subnet-dcc4b5aa bigdisk.k8s.mydomain.com --node-volume-size 4096
```

Cluster YAML:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-12T16:36:17Z
  name: bigdisk.k8s.mydomain.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.k8s.mydomain.com/bigdisk.k8s.mydomain.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a-1
      name: a-1
    - instanceGroup: master-eu-west-1b-1
      name: b-1
    - instanceGroup: master-eu-west-1a-2
      name: a-2
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a-1
      name: a-1
    - instanceGroup: master-eu-west-1b-1
      name: b-1
    - instanceGroup: master-eu-west-1a-2
      name: a-2
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 1.2.3.4/32
  kubernetesVersion: 1.9.3
  masterPublicName: api.bigdisk.k8s.mydomain.com
  networkCIDR: 10.25.0.0/16
  networkID: vpc-0882e56c
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 1.2.3.4/32
  subnets:
  - cidr: 10.25.0.0/17
    id: subnet-064a3062
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 10.25.128.0/17
    id: subnet-dcc4b5aa
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-12T16:36:17Z
  labels:
    kops.k8s.io/cluster: bigdisk.k8s.mydomain.com
  name: master-eu-west-1a-1
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a-1
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-12T16:36:17Z
  labels:
    kops.k8s.io/cluster: bigdisk.k8s.mydomain.com
  name: master-eu-west-1a-2
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a-2
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-12T16:36:17Z
  labels:
    kops.k8s.io/cluster: bigdisk.k8s.mydomain.com
  name: master-eu-west-1b-1
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b-1
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-12T16:36:17Z
  labels:
    kops.k8s.io/cluster: bigdisk.k8s.mydomain.com
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: r4.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 4096
  subnets:
  - eu-west-1a
  - eu-west-1b
```

The result (I've left this for multiple hours previously):
![screenshot from 2018-04-12 17-45-49](https://user-images.githubusercontent.com/11150054/38691692-83c0813e-3e79-11e8-881c-8130b25a0b4d.png)
