### ISSUE TITLE
Problem upgrading from 1.8.7 to 1.9.3 using kops 1.9.0

### ISSUE THREAD

**Issue by stormmore** [kubernetes/kops#5002]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
$ kops version
Version 1.9.0 (git-cccd71e67)
```
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

I am using the the documented automatic procedure for upgrading a cluster from `1.8.7` to `1.9.3`, in other words running the following commands:
```
kops upgrade cluster
kops upgrade cluster --yes
kops update cluster
kops update cluster --yes
kops rolling-upgrade cluster
kops rolling-upgrade cluster --yes
```
5. What happened after the commands executed?

Having run this procedure 3 times, I have determined that during the `kops update cluster --yes` command, `kops` updates my `.kube/config` server URL to point to the underlying ELB that is supporting the `api-server`. This causes the `kops rolling-update cluster` command to fail for a certificate validation error since the CNAME for the ELB is not in the `1.8.7` master certificate (worth noting that it is in the new master certificate for `1.9.3`.

The workaround is to manual revert the change to the `.kube/config` file to point at the original location for the `api-server`.

6. What did you expect to happen?

Didn't expect to have to manually update my `.kube/config`.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-18T00:08:26Z
  name: us-west-2.domain.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3:/k8s/us-west-2.domain.com
  dnsZone: Z1GJ01WC184I8O
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.us-west-2.domain.com
  networkCIDR: 10.2.0.0/17
  networkID: vpc-2e106357
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.2.16.0/20
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.2.32.0/20
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.2.48.0/20
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: 10.2.0.0/23
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.2.2.0/23
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 10.2.4.0/23
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T00:08:26Z
  labels:
    kops.k8s.io/cluster: us-west-2.domain.com
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T00:08:26Z
  labels:
    kops.k8s.io/cluster: us-west-2.domain.com
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T00:08:26Z
  labels:
    kops.k8s.io/cluster: us-west-2.domain.com
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T00:08:26Z
  labels:
    kops.k8s.io/cluster: us-west-2.domain.com
  name: nodes
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    kubernetes.io/cluster/us-west-2.domain.com: owned
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.small
  maxSize: 30
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
```
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

It might be worth knowing that the Route53 hosted zone used for the cluster is private and that we manually added the api.us-west-2.domain.com ALIAS entries for the public side. Longer term, the public side wont be necessary, but in the interim I need those entries.
