### ISSUE TITLE
Changes to spec.api.loadBalancer.additionalSecurityGroups are not properly executed

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#5003]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops edit cluster
add
```
spec:
  api:
    loadBalancer:
      type: Public
      additionalSecurityGroups:
      - sg-xxxxxxxx
```
kops update cluster
kops update cluster --yes

5. What happened after the commands executed?
```kops update cluster``` prints:
```
...
Will modify resources:
  LoadBalancer/api.mycluster.com
  	SecurityGroups      	 [id:sg-de9574a3] -> [name:api-elb.mycluster.com id:sg-de9574a3, name:sg-xxxxxxxx id:sg-xxxxxxxx]
```
```kops update cluster --yes``` returns without errors.

6. What did you expect to happen?
Security group sg-xxxxxxxx should be added to API ELB after running ```kops update cluster --yes```. But that doesn't happen.
Running ```kops update cluster``` multiple times gives the same message about adding the additional security group. 

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-13T21:00:26Z
  name: mycluster.com
spec:
  api:
    loadBalancer:
      additionalSecurityGroups:
      - sg-xxxxxxxx
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mybucket/mycluster.com
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-myregion-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-myregion-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-myregion-1c
      name: c
    name: main
    version: 3.0.17
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-myregion-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-myregion-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-myregion-1c
      name: c
    name: events
    version: 3.0.17
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.9.6
  masterInternalName: api.internal.mycluster.com
  masterPublicName: api.mycluster.com
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 127.0.0.1/32
  subnets:
  - cidr: 172.20.64.0/18
    name: myregion-1a
    type: Private
    zone: myregion-1a
  - cidr: 172.20.128.0/18
    name: myregion-1b
    type: Private
    zone: myregion-1b
  - cidr: 172.20.192.0/18
    name: myregion-1c
    type: Private
    zone: myregion-1c
  - cidr: 172.20.0.0/24
    name: utility-myregion-1a
    type: Utility
    zone: myregion-1a
  - cidr: 172.20.1.0/24
    name: utility-myregion-1b
    type: Utility
    zone: myregion-1b
  - cidr: 172.20.2.0/24
    name: utility-myregion-1c
    type: Utility
    zone: myregion-1c
  topology:
    bastion:
      bastionPublicName: bastion.mycluster.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-13T21:00:26Z
  labels:
    kops.k8s.io/cluster: mycluster.com
  name: bastions
spec:
  image: ami-1234567
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  rootVolumeSize: 12
  subnets:
  - utility-myregion-1a
  - utility-myregion-1b
  - utility-myregion-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-13T21:00:26Z
  labels:
    kops.k8s.io/cluster: mycluster.com
  name: master-myregion-1a
spec:
  image: ami-1234567
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-myregion-1a
  role: Master
  rootVolumeSize: 60
  subnets:
  - myregion-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-13T21:00:26Z
  labels:
    kops.k8s.io/cluster: mycluster.com
  name: master-myregion-1b
spec:
  image: ami-1234567
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-myregion-1b
  role: Master
  rootVolumeSize: 60
  subnets:
  - myregion-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-13T21:00:26Z
  labels:
    kops.k8s.io/cluster: mycluster.com
  name: master-myregion-1c
spec:
  image: ami-1234567
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-myregion-1c
  role: Master
  rootVolumeSize: 60
  subnets:
  - myregion-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-13T21:00:26Z
  labels:
    kops.k8s.io/cluster: mycluster.com
  name: nodes
spec:
  image: ami-1234567
  machineType: t2.medium
  maxSize: 10
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 60
  subnets:
  - myregion-1a
  - myregion-1b
  - myregion-1c
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
