### ISSUE TITLE
Feature Proposal: Additional CloudFormation resources

### ISSUE THREAD

**Issue by gwkunze** [kubernetes/kops#5013]
We're currently using the CloudFormation target to generate our clusters but we want our cluster to come with some extra resources not contained within the stack. 

For example, we use [kube2iam](https://github.com/jtblin/kube2iam) and we need at least two IAM roles for any cluster, these roles need to be assumable by the instance role of our nodes. To make these roles assumable we need a reference to the arn of an instancegroup's instance role.

This requirement is only really valid to the CloudFormation target as far as I can tell as with the terraform target you can use its [module](https://www.terraform.io/docs/modules/usage.html) feature to add resources to your stack. The CloudFormation target, having no outputs/exports doesn't really integrate with other parts of your cloud infrastructure.

I'm proposing adding the option to add "raw" Cloudformation resources in the cluster spec. Essentially a field containing a `map[string]interface{}` that is copied verbatim to the `kubernetes.json` output.

I'm willing to create a PR to add this functionality, but since it's very target specific, I want to be certain this is a feature that would actually be acceptable within Kops or that we should implement this externally (modifying the generated `kubernetes.json` after Kops has generated it).

**Comment by gwkunze** [comment]
To give an example, a cluster spec would look something like this:
```
Kind: Cluster
spec:
    ...
    cloudformation:
        additionalResources:
            MyResource:
                Type: "AWS::IAM::Role"
                Properties:
                    ...
                    
```

Another potential addition would be the ability to specify CF outputs, allowing you to create an exported value that's usable in other stacks.
