### ISSUE TITLE
AWS Storage Gateway (S3) with K8S NFS-Provisioner

### ISSUE THREAD

**Issue by styk-tv** [kubernetes/kops#5040]
K8S NFS-Provisioner: https://github.com/kubernetes-incubator/external-storage/tree/master/nfs

AWS Storage Gateway: https://aws.amazon.com/blogs/aws/file-interface-to-aws-storage-gateway/

It would be such a cool addition if we had ability to provision nfs volumes from pods directly onto s3. It seems with few terraform scripts automating storage gateway and already existing and proven component in k8s incubator it would be possible to reuse kops storage bucket and enable volumes that would survive infra rebuild.

```
  volumeMounts:
    - name: export-volume
      mountPath: /export
volumes:
  - name: export-volume
    hostPath:
      path: /my-s3-sg-mapping/nfs-provisioner
```
