### ISSUE TITLE
VPC additional CIDRs not allowed

### ISSUE THREAD

**Issue by montyz** [kubernetes/kops#5045]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.9.0 (git-cccd71e67)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

No server version because cluster isn't coming up.

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

AWS allows you to add CIDRs to VPCs. So I took my existing VPC with 10.0.0.0/16 and added in 10.1.0.0/16. Then I used that VPC id & the flag `--network-cidr=10.1.0.0/16`
e.g.:
```
kops create cluster \
  --cloud=aws \
  --master-zones=$ZONES \
  --name=$NAME \
  --network-cidr=$NETWORK_CIDR \
  --networking=weave \
  --node-count=$NODE_COUNT \
  --node-security-groups=$NODE_SECURITY_GROUPS \
  --node-size=$NODE_SIZE \
  --ssh-access=$WHITELIST \
  --ssh-public-key=$SSH_PUB_KEY \
  --state=$KOPS_STATE_STORE \
  --topology=private \
  --vpc=$VPC \
  --zones=$ZONES
```
5. What happened after the commands executed?

```
W0419 19:03:09.747014     126 executor.go:118] error running task "VPC/k8s-dev8.lark.com" (9m54s remaining to succeed): CIDR: Invalid value: "10.1.0.0/16": field is immutable: old="10.0.0.0/16" new="10.1.0.0/16"
```
6. What did you expect to happen?

I expected it to create the cluster with all the subnets in 10.1.0.0

7. Please provide your cluster manifest. Execute

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-19T19:02:51Z
  name: cluster.name
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cluster.name/cluster.name
  egressProxy:
    excludes: .local,127.0.0.1,localhost,api.cluster.name,cluster.name,100.64.0.1,100.64.0.0/10,169.254.169.254,10.1.0.0/16
    httpProxy:
      host: squid-dev5-int.lark.com
      port: 3128
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - x.x.x.x/32
  - x.x.x.x/32
  kubernetesVersion: 1.9.3
  masterPublicName: api.cluster.name
  networkCIDR: 10.1.0.0/16
  networkID: vpc-8106e1e4
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - x.x.x.x/32
  - x.x.x.x/32
  subnets:
  - cidr: 10.1.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.1.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.1.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.1.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.1.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.1.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-19T19:02:52Z
  labels:
    kops.k8s.io/cluster: cluster.name
  name: master-us-east-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-19T19:02:53Z
  labels:
    kops.k8s.io/cluster: cluster.name
  name: master-us-east-1b
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-19T19:02:54Z
  labels:
    kops.k8s.io/cluster: cluster.name
  name: master-us-east-1c
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-19T19:02:54Z
  labels:
    kops.k8s.io/cluster: cluster.name
  name: nodes
spec:
  additionalSecurityGroups:
  - sg-0dcc837d
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: r4.large
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
```
I0419 19:19:01.596597     280 executor.go:91] Tasks: 55 done / 116 total; 1 can run
I0419 19:19:01.596701     280 executor.go:166] Executing task "VPC/k8s-dev8.lark.com": *awstasks.VPC {"Name":"k8s-dev8.lark.com","Lifecycle":"Sync","ID":"vpc-8106e1e4","CIDR":"10.1.0.0/16","AdditionalCIDR":null,"EnableDNSHostnames":null,"EnableDNSSupport":true,"Shared":true,"Tags":null}
I0419 19:19:01.597017     280 request_logger.go:45] AWS request: ec2/DescribeVpcs
I0419 19:19:01.759054     280 vpc.go:92] found matching VPC *awstasks.VPC {"Name":"Dev4","Lifecycle":null,"ID":"vpc-8106e1e4","CIDR":"10.0.0.0/16","AdditionalCIDR":["10.1.0.0/16"],"EnableDNSHostnames":null,"EnableDNSSupport":null,"Shared":null,"Tags":null}
I0419 19:19:01.759617     280 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I0419 19:19:01.901070     280 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I0419 19:19:02.075166     280 changes.go:81] Field changed "CIDR" actual="10.0.0.0/16" expected="10.1.0.0/16"
I0419 19:19:02.075250     280 changes.go:81] Field changed "AdditionalCIDR" actual="[10.1.0.0/16]" expected="[]"
W0419 19:19:02.075398     280 executor.go:118] error running task "VPC/k8s-dev8.lark.com" (9m39s remaining to succeed): CIDR: Invalid value: "10.1.0.0/16": field is immutable: old="10.0.0.0/16" new="10.1.0.0/16"
```
9. Anything else do we need to know?

Not that I can think of.
