### ISSUE TITLE
Support docker ce 18.03

### ISSUE THREAD

**Issue by chotiwat** [kubernetes/kops#5047]
------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

    My team wanted to use docker's multi-stage build which is available on docker >= 17.05. We had tried docker 17.09 by specifying it in the kops cluster config but after the switch we started seeing pods stuck in terminating state because their container could not be killed. The behavior is similar to https://github.com/docker/for-linux/issues/1. The only solution was to restart the docker service on the node that is having the problem. It got worse after we created a kubernetes CronJob resource that runs every 5 minutes.

    We have been testing docker 18.03, by using our modified nodeup executable based on kops 1.9.0, and also testing another cluster with docker 17.03. So far, we haven't seen the problem reappearing in any of the clusters but we will continue to monitor them. We understand that the validated docker version for k8s 1.9 is 17.03.x but we still want to support multi-stage build on our cluster. We'd be happy to open a pr with our nodeup change.

    Versions:
    * Kops: 1.9.0
    * Kubernetes: 1.9.6
    * Kubectl: 1.9.5
    * Master/node OS: Ubuntu 16.04 xenial

2. Feel free to provide a design supporting your feature request.

    This is the cronjob spec that we use to reproduce the problem.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: default
spec:
  startingDeadlineSeconds: 30
  concurrencyPolicy: Forbid
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 1
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: hello
            image: hello-world
          restartPolicy: Never
```
