### ISSUE TITLE
Kops should deploy kube-dns 1.14.10, since 1.14.9 is broken for externalName services

### ISSUE THREAD

**Issue by guilhermeblanco** [kubernetes/kops#5063]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

```
Version 1.9.0
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

```
AWS
```

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
curl -XGET http://service.name
> curl: bad address
```

5. What happened after the commands executed?

```
Nothing
```

6. What did you expect to happen?

```
HTTP response
```

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```yaml
kubedns:
    Image:         gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.9
  dnsmasq:
    Image:         gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.9
  sidecar:
    Image:         gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.9
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

```
N/A
```

9. Anything else do we need to know?

```
Kops should be pointing to (considering amd64):
* kubedns: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/k8s-dns-kube-dns-amd64@sha256:b99fc3eee2a9f052f7eb4cc00f15eb12fc405fa41019baa2d6b79847ae7284a8/details/info
* dnsmasq: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/k8s-dns-dnsmasq-amd64@sha256:0850b339c6b763486f2738cee8fb47dc3db3f6f6feff4928125d89bf4a6f749b/details/info
* sidecar: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/k8s-dns-sidecar-amd64@sha256:4f1ab957f87b94a5ec1edc26fae50da2175461f00afecf68940c4aa079bd08a4/details/info
```
