### ISSUE TITLE
etcd-backup to support clusters with `enableEtcdTLS` configured

### ISSUE THREAD

**Issue by KashifSaadat** [kubernetes/kops#5064]
Using the following etcdClusterSpec (shortened):
```
  etcdClusters:
  - backups:
      backupStore: s3://<bucket>/kops-backups/etcd/main/
    enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: az1-master1
      name: a-1
    - encryptedVolume: true
      instanceGroup: az2-master1
      name: b-1
    - encryptedVolume: true
      instanceGroup: az3-master1
      name: c-1
    image: gcr.io/etcd-development/etcd:v3.3.3
    name: main
    version: 3.3.3
```

The `etcd-backup` container produces the following logs:
```
controller.go:57] unexpected error running backup controller loop: unable to find server version of etcd on [http://127.0.0.1:4001]: client: etcd cluster is unavailable or misconfigured; error #0: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Changes would need to be made both to kops and the [etcd-manager project](https://github.com/kopeio/etcd-manager) to support clusters that have etcd TLS enabled, such as:
- kops pass the CA Cert path as an arg to etcd-backup (or the full list of arguments that etcd is run with)
- etcd-backup parses the above and updates calls to etcd based on the arguments provided
