### ISSUE TITLE
Private topologies on AWS - ELB never sees masters as healthy

### ISSUE THREAD

**Issue by jmcclell** [kubernetes/kops#5076]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

`1.9.0`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: EOF
```

3. What cloud provider are you using?

`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?

Any permutation of private topology (public ELB, however) seems to fail. I'll paste details from one permutation throughout this report. It doesn't seem to be related to which networking provider is used, as each one I've tried fails similarly.

```
jason@mbp15r:~ >  kops create cluster east.kube.REDACTED \
--node-count 3 \
--zones "us-east-1a,us-east-1b,us-east-1c" \
--master-zones "us-east-1a,us-east-1b,us-east-1c" \
--dns-zone kube.REDACTED \
--master-size m5.xlarge \
--node-size m5.xlarge \
--topology private \
--networking kube-router \
--ssh-public-key ~/.ssh/t.dsc.tv.pub \
--bastion \
-v 10 \
--yes
```

5. What happened after the commands executed?

The cluster configuration is created. The AWS resources are created. However, the cluster does not validate as the API cannot be reached. The API cannot be reached because (on the surface, at least) the public ELB sees all master nodes as unhealthy and thus out of service.

```
jason@mbp15r:~ > kops validate cluster --name east.REDACTED
Validating cluster east.REDACTED


unexpected error during validation: error listing nodes: Get https://api.east.REDACTED/api/v1/nodes: EOF
```

6. What did you expect to happen?

I expect the cluster to validate and for the ELB to see the master nodes as healthy and put them in service.

```
jason@mbp15r:~ > aws elb describe-instance-health --load-balancer-name api-east-kube-REDACTED
{
    "InstanceStates": [
        {
            "InstanceId": "i-REDACTED",
            "State": "OutOfService",
            "ReasonCode": "Instance",
            "Description": "Instance has failed at least the UnhealthyThreshold number of health checks consecutively."
        },
        {
            "InstanceId": "i-REDACTED",
            "State": "OutOfService",
            "ReasonCode": "Instance",
            "Description": "Instance has failed at least the UnhealthyThreshold number of health checks consecutively."
        },
        {
            "InstanceId": "i-REDACTED",
            "State": "OutOfService",
            "ReasonCode": "Instance",
            "Description": "Instance has failed at least the UnhealthyThreshold number of health checks consecutively."
        }
    ]
}
```

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-28T11:57:12Z
  name: east.kube.REDACTED
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://REDACTED-kops/east.kube.REDACTED
  dnsZone: kube.REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterPublicName: api.east.kube.REDACTED
  networkCIDR: 172.20.0.0/16
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.20.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.east.kube.REDACTED
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-28T11:57:12Z
  labels:
    kops.k8s.io/cluster: east.kube.REDACTED
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-28T11:57:12Z
  labels:
    kops.k8s.io/cluster: east.kube.REDACTED
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-28T11:57:12Z
  labels:
    kops.k8s.io/cluster: east.kube.REDACTED
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-28T11:57:12Z
  labels:
    kops.k8s.io/cluster: east.kube.REDACTED
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-28T11:57:12Z
  labels:
    kops.k8s.io/cluster: east.kube.REDACTED
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

https://gist.github.com/jmcclell/9c6261cf8ad8ac0592c09253196954eb

9. Anything else do we need to know?

Viewing the logs from protokube on one of the masters reveals this repeating over and over:

```
I0428 15:35:29.694344    2871 aws_volume.go:320] nvme path not found "/rootfs/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol0750ac3feaffc8842"
I0428 15:35:29.694365    2871 volume_mounter.go:107] Waiting for volume "vol-0750ac3feaffc8842" to be attached
```

The Kops [documentation](https://github.com/kubernetes/kops/blob/master/docs/networking.md#kube-router-example-for-cni-ipvs-based-service-proxy-and-network-policy-enforcer) states:
```
No additional configurations are required to be done by user. Kube-router automatically disables source-destination check on all AWS EC2 instances. For the traffic within a subnet there is no overlay or tunneling used. For cross-subnet pod traffic ip-ip tunneling is used implicitly and no configuration is required.
```

However, source/dest checking has not been disabled. I disabled it manually on the master + node instances just in case there was an issue with networking at the kube-router level, but this did not fix it. Though now I realize this should not impact api elb -> master communication, anyway. Either way, this seems to indicate that the bootstrapping is not complete.
