### ISSUE TITLE
Removing availability zones from cluster?

### ISSUE THREAD

**Issue by nicolas-goudry** [kubernetes/kops#5082]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

`Version 1.9.0`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```sh
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

**AWS**

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops edit ig nodes` to remove 2 availability zones from `spec.subnets`
`kops edit cluster` to remove 2 availability zones from `spec.subnets`

5. What happened after the commands executed?

I'm afraid to use the command `kops update cluster --yes` and blow up my deployments.

6. What did you expect to happen?

Not being afraid of blowing things up? There is no doc about such operation after hours of research :man_shrugging:

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-11-24T13:52:47Z
  name: xxx.fr
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx-state-store/xxx.fr
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.xxx.fr
  masterPublicName: api.xxx.fr
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-24T13:52:47Z
  labels:
    kops.k8s.io/cluster: xxx.fr
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-24T13:52:47Z
  labels:
    kops.k8s.io/cluster: xxx.fr
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.large
  maxSize: 8
  minSize: 8
  role: Node
  subnets:
  - eu-west-1a
```

Can I update my cluster without blowing everything up?

Thanks for your help!
