### ISSUE TITLE
AWS LoadBalancer marking instances OutOfService

### ISSUE THREAD

**Issue by smartpierre** [kubernetes/kops#5105]
Hello, 
I'm trying to setup a proper cluster for our infrastructure, but I have problems with the AWS LoadBalancer, here is a replicate with a really simple cluster configuration : 

**a single nginx pod and a single loadbalancer on a standard AWS cluster**

The LoadBalancer always shows the nodes as "OutOfService"
I've been trying to fix it for a while now and I don't understand what's wrong, could you help me please ?
When I worked with the previous version of kops, everything was fine :/

1. What `kops` version are you running? The command `kops version`, will display
 this information.

>Version 1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

>Client 1.10.0
>Server 1.9.3

3. What cloud provider are you using?

>AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

>kops create cluster
>kops update cluster --yes
>kubectl apply -f pod.yml
>kubectl apply -f service.yml

pod.yml : 
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```

service.yml : 
```
kind: Service
apiVersion: v1
metadata:
  name: my-nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
```

5. What happened after the commands executed?

>Pod is OK
>Service is OK
>LoadBalancer is created, but shows nodes "OutOfService" at all time

6. What did you expect to happen?

>LoadBalancer should be able to health check nodes

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-04T08:56:25Z
  name: test.me.co
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-andromeda/test.me.co
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1b
      name: b
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.test.me.co
  masterPublicName: launchpad.test.me.co
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-04T08:56:25Z
  labels:
    kops.k8s.io/cluster: test.me.co
  name: master-eu-central-1b
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-04T08:56:25Z
  labels:
    kops.k8s.io/cluster: test.me.co
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1b
```

9. Anything else do we need to know?

>My previous attempt were all fine in eu-west-1, first time I'm trying eu-central-1

Thank you :)

**Comment by smartpierre** [comment]
I've just created another cluster on eu-west-1, default configuration, added the pod and the service, ELB still marks instances as OutOfService :(

**Comment by mliyanagamage** [comment]
I spent the last two hours downgrading the cluster to see if it was a version issue... turns out I had mixed up `port` and `targetPort`.

**Comment by smartpierre** [comment]
Hi, thank you for your help.
Sorry for the delay, I was on holidays.

Here is what I've done @vendrov 

1. nginx pod is running perfectly, I made a `kubectl port-forward` on it and was able to get the nginx welcome and logs
2. here is the output of the desribe : 
```
> kubectl describe svc my-nginx-service
Name:                     my-nginx-service
Namespace:                default
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"my-nginx-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol...
Selector:                 app=nginx
Type:                     LoadBalancer
IP:                       100.68.45.229
LoadBalancer Ingress:     aa7890a85575411e88a86024dc0c289f-1841960892.eu-central-1.elb.amazonaws.com
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31592/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  24m   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   23m   service-controller  Ensured load balancer
```

3. here is the security group for my nodes : 
```
Group name: nodes.test.me 
Group description: Security group for nodes
Group ID: sg-94153af9
VPC ID: vpc-5694e03d

Type | Protocol | Port Range | Source

All traffic | All | All | sg-66123d0b (k8s-elb-aa7890a85575411e88a86024dc0c289f)
All traffic | All | All | sg-94153af9 (nodes.test.me)
All traffic | All | All | sg-f0153a9d (masters.test.me)
```
security group for the LB : 
```
Group name: k8s-elb-aa7890a85575411e88a86024dc0c289f 
Group description: Security group for Kubernetes ELB aa7890a85575411e88a86024dc0c289f (default/my-nginx-service)
Group ID: sg-66123d0b 
VPC ID: vpc-5694e03d

Type | Protocol | Port Range | Source | Description

HTTP | TCP | 80 | 0.0.0.0/0
Custom ICMP Rule - IPv4 | Destination Unreachable | fragmentation required, and DF flag set | 0.0.0.0/0
```

4. ELB health check : 
```
Ping Target | TCP:31592
Timeout | 5 seconds
Interval | 10 seconds
Unhealthy threshold | 6
Healthy threshold | 2
```

I don't see anything weird :(

**Comment by smartpierre** [comment]
I have found the answer !
I've read this : https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/
I checked the endpoints : `kubectl get endpoints my-nginx-service`
And the service didn't have one !
The pod.yml was missing a label : 

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```

Now I have to find why it's not working on my real cluster. I'll dig more and see what I can do.
