### ISSUE TITLE
must configure at least one InstanceGroup being reported when trying to update cluster

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kops#5115]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

```
kops version
Version 1.9.0 (git-cccd71e67)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

AWS

`kops -v 10 update cluster  --yes prod-1.k8s.nuclearpistachio.com`

Shows an error of:
`must configure at least one InstanceGroup`

But an instance group is defined, in fact more than one.

manifest
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-08T14:09:29Z
  name: prod-1.k8s.nuclearpistachio.com
spec:
  api:
    dns: {}
    loadBalancer:
      idleTimeoutSeconds: 300
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.nucl
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 10.0.0.0/8
  kubernetesVersion: 1.8.4
  masterPublicName: api.prod-1.k8s.nuclearpistachio.com.com
  networkCIDR: 10.151.0.0/16
  networkID: vpc-xxxx
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.0.0.0/8
  subnets:
  - cidr: 10.151.0.0/24
    name: us-east-1a-utility
    type: Utility
    zone: us-east-1a
  - cidr: 10.151.1.0/24
    name: us-east-1b-utility
    type: Utility
    zone: us-east-1b
  - cidr: 10.151.2.0/24
    name: us-east-1c-utility
    type: Utility
    zone: us-east-1c
  - cidr: 10.151.3.0/24
    name: us-east-1d-utility
    type: Utility
    zone: us-east-1d
  - cidr: 10.151.4.0/24
    name: us-east-1e-utility
    type: Utility
    zone: us-east-1e
  - cidr: 10.151.5.0/24
    name: us-east-1f-utility
    type: Utility
    zone: us-east-1f
  - cidr: 10.151.15.0/24
    name: kube-master-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.151.16.0/24
    name: kube-master-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.151.17.0/24
    name: kube-master-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.151.21.0/24
    name: worker-zone-a
    type: Private
    zone: us-east-1a
  - cidr: 10.151.22.0/24
    name: worker-zone-b
    type: Private
    zone: us-east-1b
  - cidr: 10.151.23.0/24
    name: worker-zone-c
    type: Private
    zone: us-east-1c
  - cidr: 10.151.24.0/24
    name: worker-zone-d
    type: Private
    zone: us-east-1d
  - cidr: 10.151.25.0/24
    name: worker-zone-e
    type: Private
    zone: us-east-1e
  - cidr: 10.151.26.0/24
    name: worker-zone-f
    type: Private
    zone: us-east-1f
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**Comment by chrissound** [comment]
So it seems to not be importing the actual yaml file I've previously exported which is:

```
#
# Kops cli: 1.8.0
#
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: prod-1.k8s.nuclearpistachio.com
spec:
  sshKeyName: kube_managed_saas_kops
  networkID: vpc-xxxx
  kubernetesApiAccess:
  # Internal routes
  - 10.0.0.0/8
  api:
    dns: {}
    loadBalancer:
      type: Public
      idleTimeoutSeconds: 300
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://clusters.nucl
  etcdClusters:
  # https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#etcdclusters-v3--tls
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
    version: 3.0.17
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
    version: 3.0.17
  iam:
    # https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#iam-roles
    allowContainerRegistry: false
    legacy: false
  kubeAPIServer:
    # auditLogPath: /var/log/kube-apiserver-audit.log
    # auditLogMaxAge: 10
    # auditLogMaxBackups: 1
    # auditLogMaxSize: 100
    # auditPolicyFile: /srv/kubernetes/audit.conf
    # https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#runtimeconfig
    # runtimeConfig:
    #   batch/v2alpha1: "true"
    #   apps/v1alpha1: "true"
  kubelet:
    # https://github.com/kubernetes/kops/blob/master/docs/security.md#kubelet-api
    # anonymousAuth: false
    # kubeReserved:
    #     cpu: "100m"
    #     memory: "100Mi"
    #     storage: "1Gi"
    # kubeReservedCgroup: "/kube-reserved"
    # systemReserved:
    #     cpu: "100m"
    #     memory: "100Mi"
    #     storage: "1Gi"
    # systemReservedCgroup: "/system-reserved"
    # enforceNodeAllocatable: "pods,system-reserved,kube-reserved"
  kubernetesVersion: 1.8.4
  masterPublicName: api.prod-1.k8s.nuclearpistachio.com.com
  networkCIDR: 10.151.0.0/16
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.0.0.0/8
  subnets:
  # utility subnets
  - cidr: 10.151.0.0/24
    name: us-east-1a-utility
    type: Utility
    zone: us-east-1a
  - cidr: 10.151.1.0/24
    name: us-east-1b-utility
    type: Utility
    zone: us-east-1b
  - cidr: 10.151.2.0/24
    name: us-east-1c-utility
    type: Utility
    zone: us-east-1c
  - cidr: 10.151.3.0/24
    name: us-east-1d-utility
    type: Utility
    zone: us-east-1d
  - cidr: 10.151.4.0/24
    name: us-east-1e-utility
    type: Utility
    zone: us-east-1e
  - cidr: 10.151.5.0/24
    name: us-east-1f-utility
    type: Utility
    zone: us-east-1f
  # public subnets
  # - cidr: 10.151.15.0/24
  #   name: us-east-1a
  #   type: Public
  #   zone: us-east-1a
  # - cidr: 10.151.16.0/24
  #   name: us-east-1b
  #   type: Public
  #   zone: us-east-1b
  # - cidr: 10.151.17.0/24
  #   name: us-east-1c
  #   type: Public
  #   zone: us-east-1c
  # Kube masters subnets
  - cidr: 10.151.15.0/24
    name: kube-master-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.151.16.0/24
    name: kube-master-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.151.17.0/24
    name: kube-master-1c
    type: Private
    zone: us-east-1c
  # worker subnets
  - cidr: 10.151.21.0/24
    name: worker-zone-a
    type: Private
    zone: us-east-1a
    # egress: nat-0b280bf309e7fd7e7
    # id: subnet-c9a6f2ad
  - cidr: 10.151.22.0/24
    name: worker-zone-b
    type: Private
    zone: us-east-1b
    # egress: nat-0b280bf309e7fd7e7
    # id: subnet-aa1e7c95
  - cidr: 10.151.23.0/24
    name: worker-zone-c
    type: Private
    zone: us-east-1c
  - cidr: 10.151.24.0/24
    name: worker-zone-d
    type: Private
    zone: us-east-1d
  - cidr: 10.151.25.0/24
    name: worker-zone-e
    type: Private
    zone: us-east-1e
  - cidr: 10.151.26.0/24
    name: worker-zone-f
    type: Private
    zone: us-east-1f
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: master-us-east-1a
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-master
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - kube-master-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: master-us-east-1b
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-master
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - kube-master-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: master-us-east-1c
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-master
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - kube-master-1c

######################
## Spot instances
## type: m4.large
######################
---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-a-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxPrice: "0.06"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-a
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-b-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # zone b still seems to work.  Leaving it alone for now
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxPrice: "0.06"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-b
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-c-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxPrice: "0.06"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-c
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-d-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxPrice: "0.06"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-d
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-e-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxPrice: "0.06"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-e
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-e

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-f-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxPrice: "0.06"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-f
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-f

######################
## Spot instances
## type: m4.xlarge
######################
---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-a-m4-xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxPrice: "0.09"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-a
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.xlarge
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-b-m4-xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.xlarge
  maxPrice: "0.09"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-b
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.xlarge
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-c-m4-xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxPrice: "0.09"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-c
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.xlarge
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-d-m4-xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxPrice: "0.09"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-d
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.xlarge
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-e-m4-xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxPrice: "0.09"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-e
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.xlarge
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-e

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: spot-zone-f-m4-xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-spot-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxPrice: "0.09"
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: spot-zone-f
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "true"
    k8s.info/instanceType: m4.xlarge
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-f

#########################
## On Damand instances
#########################
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: ondemand-zone-a-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-ondemand-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxSize: 5
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: ondemand-zone-a
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "false"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: ondemand-zone-b-m4-large
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-ondemand-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: m4.large
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: ondemand-zone-b
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "false"
    k8s.info/instanceType: m4.large
    k8s.info/hasPublicIP: "false"
  role: Node
  subnets:
  - worker-zone-b

## On Demand instance - high memory

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: prod-1.k8s.nuclearpistachio.com.com
  name: ondemand-zone-c-r4.xlarge
spec:
  cloudLabels:
    CostCenter: kubernetes-saas
    Owner: kubernetes
    Project: cloud
    Purpose: kubernetes-ondemand-node
    # https://github.com/kubernetes/autoscaler/issues/511#issuecomment-354616866
    k8s.io/cluster-autoscaler/node-template/label/prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
  # current meltdown/spectre updated image: https://github.com/kubernetes/kops/blob/master/channels/alpha#L16
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-05
  machineType: r4.xlarge
  maxSize: 5
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: ondemand-zone-c
    prod-1.k8s.nuclearpistachio.com.com/role: scale-zero
    k8s.info/isSpot: "false"
    k8s.info/instanceType: r4.xlarge
    k8s.info/hasPublicIP: "false"
    k8s.info/memory-max: "30GB"
  role: Node
  subnets:
  - worker-zone-c
```

How can I import / create from such a file?
