### ISSUE TITLE
High DNS latency after upgrading to kubernetes 1.9.7

### ISSUE THREAD

**Issue by igorvpcleao** [kubernetes/kops#5116]
> 1. What `kops` version are you running? The command `kops version`, will display
>  this information.

Version 1.9.0

> 2. What Kubernetes version are you running? `kubectl version` will print the
>  version if a cluster is running or provide the Kubernetes version specified as
>  a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

> 3. What cloud provider are you using?

AWS

> 4. What commands did you run?  What is the simplest way to reproduce this issue?

kops edit cluster; # updated k8s version, only
kops update cluster;
kops rolling update;

> 5. What happened after the commands executed?

Cluster got updated;
DNS latency increased;

> 6. What did you expect to happen?

DNS latency not to increase;

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2016-08-06T01:33:08Z
  name: fool
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: alpha
  cloudProvider: aws
  configBase: s3://kubernetes/fool
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1b
      name: us-east-1b
    - instanceGroup: master-us-east-1c
      name: us-east-1c
    - instanceGroup: master-us-east-1d
      name: us-east-1d
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1b
      name: us-east-1b
    - instanceGroup: master-us-east-1c
      name: us-east-1c
    - instanceGroup: master-us-east-1d
      name: us-east-1d
    name: events
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/sbin/sysctl net.ipv4.neigh.default.gc_thresh3=8192 ; /sbin/sysctl net.ipv4.neigh.default.gc_thresh2=4096 ; /sbin/sysctl -p
    name: increase-neigh-gc-thresh.service
  iam:
    legacy: true
  kubeAPIServer:
    authorizationMode: RBAC
    authorizationRbacSuperUser: admin
    oidcClientID: idddddd
    oidcGroupsClaim: groups
    oidcIssuerURL: https://accounts.google.com
    oidcUsernameClaim: email
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.7
  masterInternalName: api.internal.fool
  masterPublicName: api.fool
  networkCIDR: 10.20.0.0/16
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.20.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 10.20.128.0/19
    name: us-east-1d
    type: Public
    zone: us-east-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-16T19:35:17Z
  labels:
    kops.k8s.io/cluster: fool
  name: foo-us-east-1d
spec:
  additionalSecurityGroups:
  - sg-popopop
  associatePublicIp: true
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/fool: "true"
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c4.2xlarge
  maxSize: 25
  minSize: 5
  nodeLabels:
    elasticIpPool: xalalala
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  - us-east-1d
  taints:
  - dedicated=xalalala:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-27T15:00:20Z
  labels:
    kops.k8s.io/cluster: fool
  name: app-x
spec:
  additionalSecurityGroups:
  - sg-popopo
  associatePublicIp: true
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/fool: "true"
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c4.2xlarge
  maxSize: 40
  minSize: 8
  nodeLabels:
    xulululu-dedicated: "true"
  role: Node
  rootVolumeSize: 25
  rootVolumeType: gp2
  subnets:
  - us-east-1c
  - us-east-1d
  taints:
  - dedicated=xulululu:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-14T21:00:43Z
  labels:
    kops.k8s.io/cluster: fool
  name: dddddd
spec:
  additionalSecurityGroups:
  - sg-fffff
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/fool: "true"
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c4.2xlarge
  maxSize: 25
  minSize: 2
  nodeLabels:
    maestro-dedicated: "true"
  role: Node
  rootVolumeSize: 50
  rootVolumeType: gp2
  subnets:
  - us-east-1d
  - us-east-1c
  taints:
  - dedicated=xalalala:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2016-08-06T01:33:08Z
  labels:
    kops.k8s.io/cluster: fool
  name: master-us-east-1b
spec:
  associatePublicIp: true
  cloudLabels:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-02T00:41:03Z
  labels:
    kops.k8s.io/cluster: fool
  name: master-us-east-1c
spec:
  associatePublicIp: true
  cloudLabels:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-02T00:42:39Z
  labels:
    kops.k8s.io/cluster: fool
  name: master-us-east-1d
spec:
  cloudLabels:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-1d
  role: Master
  subnets:
  - us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-28T13:16:19Z
  labels:
    kops.k8s.io/cluster: fool
  name: nodes-v2-us-east-1b
spec:
  associatePublicIp: true
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/fool: "true"
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c4.2xlarge
  maxSize: 30
  minSize: 10
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-v2-us-east-1b
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-28T13:16:19Z
  labels:
    kops.k8s.io/cluster: fool
  name: nodes-v2-1c
spec:
  associatePublicIp: true
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/fool: "true"
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c4.2xlarge
  maxSize: 30
  minSize: 10
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-v2-1c
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-28T13:16:19Z
  labels:
    kops.k8s.io/cluster: fool
  name: nodes-v2
spec:
  associatePublicIp: true
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kubernetes.io/cluster/fool: "true"
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c4.2xlarge
  maxSize: 30
  minSize: 10
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-v2
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1d
```

I also tried to upgrade kube-dns from 1.14.9 to 1.14.10 without success. Latency only reduced after rolling back kube-dns to my previous version: 1.14.6.
