### ISSUE TITLE
Kops creates large no of protokube: 1.8.1 containers causing docker pull to fail

### ISSUE THREAD

**Issue by cloudbow** [kubernetes/kops#5145]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
Version 1.8.0 (git-5099bc5)
```
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?
```
aws
```
4. What commands did you run?  What is the simplest way to reproduce this issue?
```
kops create cluster \
    --zones us-east-2a,us-east-2b \
    --node-size 'm4.xlarge' \
    --master-size 'c4.large' \
    --kubernetes-version=1.8.4 \
    --node-count=3 \
    sc-cloud.k8s.local
```
5. What happened after the commands executed?
Immediately after executing nothing happened. But after around 3 months of time one of the aws nodes gave ImagePullBackOff for certain containers. And docker pull failed with error
tcp dial i/o timeout
6. What did you expect to happen?
The pods should have initialised correctly
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-12-06T11:17:21Z
  name: sc-cloud.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kubernetes-slingtv-state-store/sc-cloud.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.4
  masterPublicName: api.sc-cloud.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.20.64.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-06T11:17:22Z
  labels:
    kops.k8s.io/cluster: sc-cloud.k8s.local
  name: master-us-east-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  subnets:
  - us-east-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-12-06T11:17:22Z
  labels:
    kops.k8s.io/cluster: sc-cloud.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.xlarge
  maxSize: 9
  minSize: 9
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-2a
  - us-east-2b
```
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
```
o        Created                                         gallant_lichterman
e0234c8a48dc        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         sad_roentgen
197724f86489        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         condescending_lamarr
4c4021bc99eb        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         practical_ritchie4
b9bbfaccd778        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         competent_spence
929e7757f7f9        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         friendly_colden
3b34afab8b1f        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         adoring_swanson
bf592cec84d3        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         clever_euclid
26eff12d318f        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         pensive_dubinsky9
c67a3312b0f9        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         peaceful_noether
2521e37d4ceb        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         happy_stonebraker
71f44b5c69d7        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         awesome_colden
626cbd5c833d        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         sad_noether
6086fc0b80a7        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         objective_stonebraker
bc9104c43604        protokube:1.8.0                                                                                                           "/usr/bin/protokub..."   2 months ago        Created                                         youthful_kilby
```
9. Anything else do we need to know?

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.
