### ISSUE TITLE
Can I specify ELB port instead of default 443?

### ISSUE THREAD

**Issue by tongda** [kubernetes/kops#5157]
443 in China is forbidden if one do not get license from government. Is there a way to specify a customized port for ELB to connect to master:443?

I expect it to be like this:

```
spec:
  api:
    loadBalancer:
      type: Public
      port: 8888
```
