### ISSUE TITLE
docker pull hanging

### ISSUE THREAD

**Issue by sheldonkwok** [kubernetes/kops#5169]
1. What `kops` version are you running? 
`Version 1.9.0 (git-cccd71e67)`

2. What Kubernetes version are you running?
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
AWS 

4. What commands did you run?  What is the simplest way to reproduce this issue?
`k apply -f k8.yml`
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  progressDeadlineSeconds: 10

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.13
          ports:
            - containerPort: 80


---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: prod
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
```
5. What happened after the commands executed?
Deployment pod hangs on Reason `Pulling`. I attempted to pull the nginx image as root on the node and it was also hanging.

```
root@ip-10-10-33-157:~# docker pull nginx:1.10                                            
1.10: Pulling from library/nginx             
6d827a3ef358: Waiting                        
1e3e18a64ea9: Waiting                        
556c62bb43ac: Waiting  
```

6. What did you expect to happen?
I expected kops nodes to pull image. I've read about issues with overlayfs but am having trouble debugging. I want to switch to aufs but related issue: https://github.com/kubernetes/kops/issues/3196
