### ISSUE TITLE
Instances not using all space from the root volume

### ISSUE THREAD

**Issue by david92rl** [kubernetes/kops#5175]
**Kops version**: 1.9.0
**Kubernetes version**: v1.9.3
**Cloud provider**: AWS

Having this instance group template:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: spot
spec:
  rootVolumeSize: 100
  rootVolumeType: gp2
  machineType: c5.2xlarge
  maxPrice: "0.39"
  maxSize: 60
  minSize: 0
  role: Node
```
I created the instance group with:
`kops replace -f instancegroup.yaml --force`

The instance group was created as expected, but the instances started running out of space very quicky so I checked the disk with:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs           3.1G  1.3M  3.1G   1% /run
/dev/nvme0n1p1  7.4G  6.1G  911M  88% /
tmpfs           7.6G     0  7.6G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
```
And 
```
$ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0  100G  0 disk
`-nvme0n1p1 259:1    0    8G  0 part /
```
Doing this in an instance created with kops 1.8 in a `c4` instance:
```
$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0  100G  0 disk
`-xvda1 202:1    0  100G  0 part /
```

I'm not sure if this is just happening to the new family of `c5` instances

**Comment by steve-horan** [comment]
This is due to the Jessie image not supporting NVMe. If you wish to use the new generation instance types, use the stretch image.

```
$ kops get ig nodes -oyaml
Using cluster from kubectl context: 

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-16T17:50:06Z
  labels:
    kops.k8s.io/cluster:
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-02-08
  machineType: c5.4xlarge
  maxPrice: "0.40"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-2c

```

```
admin@ip-172-20-63-154:~$ df -hT /dev/nvme0n1p2
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/nvme0n1p2 ext4  120G  2.1G  113G   2% /
```

**Comment by steve-horan** [comment]
I am wondering what everyone else things in regards to this, either have kops notify you on update of the ig or even have kops correct the image automatically if you are using those instance types.

**Comment by endorama** [comment]
We had the same problem but using kops `1.8.x`. Could we use the new image with kops version 1.8?

If not, this would mean that we need to upgrade kubernetes and kops version to `1.9.x` in order to use `c5` type instances, am I correct?

**Comment by kty1965** [comment]
I have same issue.


I am using c5.large instance type, EBS allocated 128GB but just available `7.4G`.
below is instance group information
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-02T20:57:39Z
  labels:
    kops.k8s.io/cluster: k8s.wi.com
  name: c-nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: c5.large
  maxSize: 4
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: c-nodes
  role: Node
  subnets:
  - ap-northeast-2a
  - ap-northeast-2c
```

`df -h`
```
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs           744M  1.1M  743M   1% /run
/dev/nvme0n1p1  7.4G  5.1G  1.9G  73% /
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
```
