### ISSUE TITLE
cluster-autoscaler requires batch.jobs and batch.cronjobs access

### ISSUE THREAD

**Issue by DaveTaddei-CR** [kubernetes/kops#5190]
kops version 1.9.0

kubernetes verson 1.9.4

Cloud Provider: AWS

To reproduce: run kubectl from cluster-autoscaler pod and attempt to get job and cronjob resources

A forbidden access error occurs when the cluster autoscaler attempts to remove nodes:
```Error from server (Forbidden): jobs.batch is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list jobs.batch in the namespace "kube-system"```

Default template needs to include the following:
```
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - watch
  - list
  - get
```
