### ISSUE TITLE
Rolling-update causes outage when all nodes are removed from ELB

### ISSUE THREAD

**Issue by u2mejc** [kubernetes/kops#5211]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
$ kops version
Version 1.9.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as**
 a `kops` flag.

> Issue occurred when upgrading from K8 version 1.8.1.
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T19:38:53Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
AWS / Classic ELB

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
# Upgrade kubernetes 
kops update cluster
kops update cluster --yes
kops rolling-update cluster
kops rolling-update cluster --yes
```

**5. What happened after the commands executed?**
All EC2 nodes disappeared from ELB simultaneously and did not come back until new nodes started up. (To clarify: that they were removed, not marked unhealthy).

**6. What did you expect to happen?**
Doing so, I'd expect a rolling update to:
- add a node (ec2 instance)
- Wait for it to come healthy / Ready (inside the ELB & K8)
- taint a old node and wait for all pods on the old node to complete rescheduling
- Terminate old drained node and it from ELB

**7. Please provide your cluster manifest. Execute**
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information. ✅ 
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: misc-east-k8s.internal
spec:
  additionalPolicies:
    master: |
      [ { "Effect": "Allow", "Action": [ "s3:GetObject", "s3:ListBucket" ], "Resource": [ "arn:aws:s3:::builds.example.com", "arn:aws:s3:::builds.example.com/*", "arn:aws:s3:::builds2.example.com" ] } ]
    node: |
      [ { "Effect": "Allow", "Action": [ "s3:GetObject", "s3:ListBucket" ], "Resource": [ "arn:aws:s3:::builds.example.com", "arn:aws:s3:::builds.example.com/*" ] } ]
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://misc-east-k8s-kops/misc-east-k8s.internal
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2b
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2b
      name: a
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.8
  masterInternalName: api.internal.misc-east-k8s.internal
  masterPublicName: api.misc-east-k8s.internal
  networkCIDR: 10.13.0.0/16
  networkID: vpc-7f8c2f18
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.13.32.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.13.64.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 10.13.160.0/19
    name: us-east-1f
    type: Public
    zone: us-east-1f
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-25T20:29:32Z
  labels:
    kops.k8s.io/cluster: misc-east-k8s.internal
  name: master-us-east-2b
spec:
  image: coreos.com/CoreOS-stable-1745.3.1-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-25T21:42:35Z
  labels:
    kops.k8s.io/cluster: misc-east-k8s.internal
  name: nodes
spec:
  image: coreos.com/CoreOS-stable-1745.3.1-hvm
  machineType: m5.xlarge
  maxSize: 6
  minSize: 6
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1b
  - us-east-1c
  - us-east-1f
```
