### ISSUE TITLE
'Timeout expired waiting for volumes to attach/mount for pod'

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#5238]
------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.9.0 (git-cccd71e67)
`
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
kubectl create -f {pv.yaml, deploy.yaml}

I am using a previously created ebs volume (since we can't dynamically provision disks within k8s from ec2 snapshots yet)

pv:
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: tempdisk
  namespace: testing
spec:
  capacity:
    storage: 3000G
  awsElasticBlockStore:
    volumeID: aws://eu-west-1a/vol-xxxxxxxxx
    fsType: ext4
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: testing
  name: tempdisk-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3000G
  storageClassName: gp2

```

deploy:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: testing
  labels:
    app: testing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      labels:
        app: testing-app
    spec:
      securityContext:
        runAsUser: 9999
        fsGroup: 999
      containers:
      - name: main
        image: docker-host/image:latest
        command: [ "bash","-c","sleep 24h"]
        ports:
        - containerPort: 80
        - containerPort: 8080

      volumes:
      - name: temp-disk
        persistentVolumeClaim:
          claimName: tempdisk-claim
```

5. What happened after the commands executed?
Returned successful, but trouble mounting into the pod.
The volume mounted onto the node successfully and I can cd into the folder and see the contents (i.e. fsck isn't necessary) but I get error in syslog specifically the timeout message.

6. What did you expect to happen?
Deployment to succeed, and pod to have the specified volumes mounted

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
(available if needed)

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
(N/A -- not an issue with the command itself)

9. Anything else do we need to know?
N/A
