### ISSUE TITLE
Unable to launch IGs with taints while using certain network CNIs

### ISSUE THREAD

**Issue by natefox** [kubernetes/kops#5246]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
Version 1.9.1
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
```

3. What cloud provider are you using?
`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?
```
$ kops create cluster --yes \
  --name nfox.k8s.local \
  --master-count 3 \
  --zones us-west-2a,us-west-2b,us-west-2c \
  --networking amazon-vpc-routed-eni
```
This creates a cluster and it validates just fine.

```
$ kops create instancegroup --edit --role Node --subnet us-west-2a,us-west-2b,us-west-2c --name=nfox.k8s.local tainttest

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  name: tainttest
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: tainttest
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  taints:
  - mytaint=test:NoExecute
```
I create an IG with my editor, adding the taint in the last 2 lines. Then run `kops update cluster --yes` which runs fine. But it never validates.

5. What happened after the commands executed?
Cluster never validates.
```
$ kops validate cluster nfox.k8s.local
Validating cluster nfox.k8s.local

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-us-west-2a	Master	m3.medium	1	1	us-west-2a
master-us-west-2b	Master	m3.medium	1	1	us-west-2b
master-us-west-2c	Master	m3.medium	1	1	us-west-2c
nodes			Node	t2.medium	2	2	us-west-2a,us-west-2b,us-west-2c
tainttest		Node	t2.medium	2	2	us-west-2a,us-west-2b,us-west-2c

NODE STATUS
NAME						ROLE	READY
ip-172-20-104-1.us-west-2.compute.internal	master	True
ip-172-20-112-85.us-west-2.compute.internal	node	True
ip-172-20-42-164.us-west-2.compute.internal	node	False
ip-172-20-57-252.us-west-2.compute.internal	master	True
ip-172-20-73-10.us-west-2.compute.internal	master	True
ip-172-20-73-147.us-west-2.compute.internal	node	True
ip-172-20-95-204.us-west-2.compute.internal	node	False

VALIDATION ERRORS
KIND	NAME						MESSAGE
Node	ip-172-20-42-164.us-west-2.compute.internal	node "ip-172-20-42-164.us-west-2.compute.internal" is not ready
Node	ip-172-20-95-204.us-west-2.compute.internal	node "ip-172-20-95-204.us-west-2.compute.internal" is not ready

Validation Failed
```

6. What did you expect to happen?
Cluster to validate

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-01T20:07:04Z
  name: nfox.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://nfox-k8s-state-store/nfox.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.6
  masterPublicName: api.nfox.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-01T20:07:05Z
  labels:
    kops.k8s.io/cluster: nfox.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-01T20:07:05Z
  labels:
    kops.k8s.io/cluster: nfox.k8s.local
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-01T20:07:05Z
  labels:
    kops.k8s.io/cluster: nfox.k8s.local
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-01T20:07:05Z
  labels:
    kops.k8s.io/cluster: nfox.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-01T20:12:47Z
  labels:
    kops.k8s.io/cluster: nfox.k8s.local
  name: tainttest
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: tainttest
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  taints:
  - tainted=test:NoExecute
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
https://gist.github.com/natefox/6977509ca16c3a39b6c023710d9a8df4

9. Anything else do we need to know?
Launching a cluster with weave and amazon-vpc-routed-eni networking flags fail when trying to launch an IG with taints. kubenet (no `--networking` specified), flannel and calico are ok (havent tested others).

Fairly certain this has to do with the `tolerations` in each of the networking addons. Eg: [flannel](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.flannel/k8s-1.6.yaml.template#L98) has
```
      tolerations:
      - operator: Exists
```
Whereas all the others have variations of tolerating master and other taints (k8s' recommended 'CriticalAddonsOnly'.

[Calico](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.7.yaml.template#L140) has something different as well, but it works:
```
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
```

Maybe there should be a set standard tolerations across all CNI plugins?
