### ISSUE TITLE
Rename The Instance Group

### ISSUE THREAD

**Issue by krisanalfa** [kubernetes/kops#5298]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

```
$ kops version
Version 1.9.1
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

```
AWS
```

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
kops edit ig foo
```

Rename my instance from `foo` to `bar`

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-07T08:04:20Z
  labels:
    kops.k8s.io/cluster: k8s.travlr.com
  name: bar
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: r4.xlarge
  maxSize: 6
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: bar
  role: Node
  subnets:
  - ap-southeast-2a
  - ap-southeast-2b
  - ap-southeast-2c
```

5. What happened after the commands executed?

```
error writing InstanceGroup: cannot update configuration file s3://<STORE>/<NAME>/instancegroup/bar: does not exist
```

6. What did you expect to happen?

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

`kops` should rename the instance group.

9. Anything else do we need to know?

Also when I run:

```
$ kops update cluster
```

The output is:

```
No changes need to be applied
```
