### ISSUE TITLE
Support real ssl certs for api server 

### ISSUE THREAD

**Issue by feniix** [kubernetes/kops#530]
It would be nice to be able to provide real certificates for the api server.

Another option would be to support letsencrypt.

**Comment by chrislovecnm** [comment]
@feniix we are discussing the additions of various plugins within kops.  Will let you know

**Comment by justinsb** [comment]
I mentioned this on slack, but reposting here:

The way that kube-up and kops has set up k8s to date has been with a single CA certificate, which then signs everything, including the API server certificate used for https.  So it's not trivial trivial to just swap out a single keypair.

But....
I was able to run with ingress in front of the API server, using a kube-lego (letsencrypt) certificate - so any certificate would work. The trick was that ingress re-encrypts the traffic - i.e. it talks https to the API


This does _not_ work with client certificate authentication.  But it will work with token auth or basic auth.  We do actually enable basic auth today (you can delete the client cert from your kubeconfig and it'll still work).  And external auth systems tend to use token auth or JWT I believe, both of which should also work

Here's the ingress I used:

```
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/tls-acme: "true"
  name: kubernetes
  namespace: default
spec:
  rules:
  - host: api.cluster.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes
          servicePort: 443
        path: /
  tls:
  - hosts:
    - api.cluster.example.com
    secretName: tls-cluster.example.com
```
