### ISSUE TITLE
Allow users to disable kube-proxy replacement from kube-router (and other config?)

### ISSUE THREAD

**Issue by mikn** [kubernetes/kops#5310]
Currently, there are no configuration options at all exposed for the kube-router installation (so metrics are not enabled, nor can you pick which features of kube-router you want).
We recently hit this issue: https://github.com/cloudnativelabs/kube-router/issues/455 where it turns out that kube-router's service proxy implementation does not implement the specific health check feature required to run `externalTrafficPolicy: Local` on services.
I would like to propose the ability to at least run kube-router with the standard kube-proxy, for these cases - but greater configuration in general for kube-router would be great.
If there are any pointers or design suggestions of such a feature, I'd gladly try to take these and submit a PR (our secondary target is also exposing metrics and annotate the pods for Prometheus scraping).

**Comment by roffe** [comment]
hi @mikn we have supported running kube-router alongside kube-proxy since early releases
also metrics, policy controller, service proxy etc is all toggleable via cli flags you must explicitly specify

All of the cli options can be seen here:
https://www.kube-router.io/docs/user-guide/

Kube proxy must be started with `--run-service-proxy` to handle the creation of services etc, if it's omnited it's the cluster operators responsibility to make sure kube-proxy is running and properly configured ( out of scope of kube-routers responsibilitys )

**Comment by roffe** [comment]
Regarding prometheus scraping, there is not a unified way to do this at the moment, some use prometheus-operator and specific monitor manifests. others use the annotations.

I've documented the annotation scenario here:
https://www.kube-router.io/docs/user-guide/

Also, the reasoning to why I disabled metrics by default is to prevent kube-router from exposing the internal metrics to the net by misstake since kube-router runs at host networking level

**Comment by roffe** [comment]
It's very unfortunate that we oversaw the healthcheck implemetation for `externalTrafficPolicy: Local` but we are looking into that to have it fixed asap

**Comment by mikn** [comment]
Thank you for your answers! I was unclear that I was referring to that you cannot change any settings for kube-router within the kops installation manifests, meaning I need to self-host the manifests with the tweaks.

Good information about why you disabled the metrics per default, I'm pretty sure the SGs set up by kops specifically prevents this even with a public topology, otherwise it would be trivial to fix. :)

**Comment by roffe** [comment]
Ah sorry, well yes. that is very static and you don't have much options to modify it at cluster creation.

I provision the cluster then immediately replace the DS with my own custom one

For reference here is the DS i replace the kops deployed one with for my Kops 1.9 cluster:
( note that i'm using a debug image i built, so you not copy my manifest straight off)
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "20245"      
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kube-router
        image: roffe/kube-router-git:health-5
        # image: cloudnativelabs/kube-router:v0.2.0-beta.6
        args:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --metrics-port=20245
        - --iptables-sync-period=2m
        - --routes-sync-period=2m
        - --ipvs-sync-period=2m
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --bgp-graceful-restart
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 25
          periodSeconds: 3
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_TIME
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: kubeconfig
          mountPath: /var/lib/kube-router/kubeconfig
          readOnly: true
      initContainers:
      - name: install-cni
        image: busybox
        command:
        - /bin/sh
        - -c
        - set -e -x;
          if [ ! -f /etc/cni/net.d/10-kuberouter.conf ]; then
            TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
            cp /etc/kube-router/cni-conf.json ${TMP};
            mv ${TMP} /etc/cni/net.d/10-kuberouter.conf;
          fi
        volumeMounts:
        - name: cni-conf-dir
          mountPath: /etc/cni/net.d
        - name: kube-router-cfg
          mountPath: /etc/kube-router
      hostNetwork: true
      serviceAccountName: kube-router
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
        name: lib-modules
      - hostPath:
          path: /etc/cni/net.d
        name: cni-conf-dir
      - name: kubeconfig
        hostPath:
          path: /var/lib/kube-router/kubeconfig
      - name: kube-router-cfg
        configMap:
          name: kube-router-cfg
```
