### ISSUE TITLE
New masters not able to join cluster

### ISSUE THREAD

**Issue by sourabhmodi** [kubernetes/kops#5327]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
```
kops version = Version 1.9.1 (git-ba77c9ca2)
```
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Kubernetes and Kubectl version
Client Version: v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335
Server Version: v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1
```
3. What cloud provider are you using?
```
Cloud Provider: AWS
```
4. What commands did you run?  What is the simplest way to reproduce this issue?
```
Changed the minSize, maxSize of master IG from one to three.
after that update the cluster  and "kops rolling-update cluster" command.
```

5. What happened after the commands executed?

New Instances was launched(Could see in AWS console) but they didn't join the cluster.
"kops validate cluster"  command gave the following error after some time
```
VALIDATION ERRORS
KIND    NAME                    MESSAGE
Machine i-xxxxxxxxxxxxxxxxx     machine "i-xxxxxxxxxxxxxxxxx" has not yet joined cluster
Machine i-xxxxxxxxxxxxxxxxy     machine "i-xxxxxxxxxxxxxxxxy" has not yet joined cluster
```
6. What did you expect to happen?
```
New launched Instances should have joined the cluster. 
```
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-02T03:21:51Z
  name: clustername
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://pathto/bucket
  dnsZone: clustername
  docker:
    insecureRegistry: IP.add.res.ss
    logDriver: ""
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.6
  masterInternalName: api.internal.clustername
  masterPublicName: api.clustername
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2c
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-02T03:21:52Z
  labels:
    kops.k8s.io/cluster: clustername
  name: master-us-east-2c
spec:
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/usr/bin/docker run --net host quay.io/sergioballesteros/check-aws-tags
      ExecStartPost=/bin/systemctl restart kubelet.service
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Master
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.large
  maxPrice: "price_set"
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2c  
  role: Master
  subnets:
  - us-east-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-02T03:21:52Z
  labels:
    kops.k8s.io/cluster: clustername
  name: nodes
spec:
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/usr/bin/docker run --net host quay.io/sergioballesteros/check-aws-tags
      ExecStartPost=/bin/systemctl restart kubelet.service
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Node
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.xlarge
  maxPrice: "price_set"
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-02T03:21:52Z
  labels:
    kops.k8s.io/cluster: clustername
  name: testnodes
spec:
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/usr/bin/docker run --net host quay.io/sergioballesteros/check-aws-tags
      ExecStartPost=/bin/systemctl restart kubelet.service
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Node
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.micro
  maxPrice: "price_set"
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: notestnodes
  role: Node
  subnets:
  - us-east-2c

```
8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
```
No special command were executed to achieve this.
```
9. Anything else do we need to know?
```
1.We have added a hook in the IG after moving to spot instances, as the new instance were not able to join the cluster, but this hooked helped.
2. Earlier when we accidently changed the minSize and maxSize of master's IG to 2, kops gave error and didn't allowed use to save. as we can only have odd number of masters for leader selection. 
But after this issue arise, we were able to set the vale to 2 and a new instance was launched but also that single instance was not able to join the cluster. 
3. This a single AZ cluster, so none of the steps here are required to follow "https://github.com/kubernetes/kops/blob/master/docs/single-to-multi-master.md"
PS : Any kind of help will be appreciated. 
```
