### ISSUE TITLE
docker bridgeIP

### ISSUE THREAD

**Issue by milan-dasek** [kubernetes/kops#5336]
Hello,

I am not able to change docker BIP on running cluster.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.9.1

2. What Kubernetes version are you running?
1.5.8

3. What cloud provider are you using?
aws

4. What commands did you run?  What is the simplest way to reproduce this issue?
kops edit cluster %NAME%

5. What happened after the commands executed?
# Found fields that are not recognized
# ...
#     docker:
#       bridgeIP: 172.18.0.1/16
# -     logDriver: ""
#     etcdClusters:
#     - etcdMembers:
# ...

6. What did you expect to happen?
I expect kops will change IP range for

```
{
        "Name": "bridge",
        "Id": "109b684195c13a0a94a65554f2329673b5a1c95f2718a9f3806491c341e2e811",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
```

7. Please provide your cluster manifest. Execute
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-01-30T08:00:00Z
  name: %NAME%
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://%CONFIGBASE%
  dnsZone: %DNSZONE%
  docker:
    bridgeIP: 172.18.0.1/16
  etcdClusters:
  ....
```
