### ISSUE TITLE
rolling-update wants to replace spot instances created by Autospotting

### ISSUE THREAD

**Issue by kaazoo** [kubernetes/kops#5346]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

```Version 1.9.0```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
# kops rolling-update cluster --name CLUSTERNAME --state s3://S3_BUCKET
NAME			STATUS		NEEDUPDATE	READY	MIN	MAX	NODES
bastions		NeedsUpdate	1		0	1	1	0
master-eu-west-1a	Ready		0		1	1	1	1
master-eu-west-1b	Ready		0		1	1	1	1
master-eu-west-1c	Ready		0		1	1	1	1
nodes			NeedsUpdate	3		0	3	6	3

Must specify --yes to rolling-update.
```

5. What happened after the commands executed?

'kops rolling-update' wants to replace spot instances, allthough they have the same tags and config as specified in the launchconfig.

6. What did you expect to happen?

'kops rolling-update' should show NEEDUPDATE column with value '0'.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
kops get --name CLUSTERNAME --state s3://S3_BUCKET -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-19T11:22:54Z
  name: CLUSTERNAME
spec:
  additionalPolicies:
    bastion: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:*", "ec2:Describe*", "cloudwatch:*"],
          "Resource": ["*"]
        }
      ]
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:*", "ec2:Describe*", "cloudwatch:*"],
          "Resource": ["*"]
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:*", "ec2:Describe*", "cloudwatch:*", "sts:AssumeRole"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    foo: bar
  cloudProvider: aws
  configBase: s3://S3_BUCKET/CLUSTERNAME
  dnsZone: ABCDEFGH
  docker:
    bridge: ""
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay2
    version: 17.03.2
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-1c
      name: c
    name: main
    version: 3.1.12
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-west-1c
      name: c
    name: events
    version: 3.1.12
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubelet:
    enableCustomMetrics: true
  kubernetesApiAccess:
  - xxx.xxx.xxx.xxx/yyy
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.CLUSTERNAME
  masterPublicName: api.CLUSTERNAME
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - xxx.xxx.xxx.xxx/yyy
  subnets:
  - cidr: 172.20.64.0/18
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.20.128.0/18
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.20.192.0/18
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.20.0.0/24
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.20.1.0/24
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.20.2.0/24
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    bastion:
      bastionPublicName: bastion.CLUSTERNAME
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T11:22:54Z
  labels:
    kops.k8s.io/cluster: CLUSTERNAME
  name: bastions
spec:
  cloudLabels:
    spot-enabled: "true"
  image: ami-baa19ac3
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  rootVolumeSize: 30
  subnets:
  - utility-eu-west-1a
  - utility-eu-west-1b
  - utility-eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T11:22:54Z
  labels:
    kops.k8s.io/cluster: CLUSTERNAME
  name: master-eu-west-1a
spec:
  cloudLabels:
    spot-enabled: "false"
  image: ami-003838ea
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  rootVolumeSize: 60
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T11:22:54Z
  labels:
    kops.k8s.io/cluster: CLUSTERNAME
  name: master-eu-west-1b
spec:
  cloudLabels:
    spot-enabled: "false"
  image: ami-003838ea
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  rootVolumeSize: 60
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T11:22:54Z
  labels:
    kops.k8s.io/cluster: CLUSTERNAME
  name: master-eu-west-1c
spec:
  cloudLabels:
    spot-enabled: "false"
  image: ami-003838ea
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  rootVolumeSize: 60
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T11:22:54Z
  labels:
    kops.k8s.io/cluster: CLUSTERNAME
  name: nodes
spec:
  cloudLabels:
    autospotting_allowed_instance_types: current
    spot-enabled: "true"
  image: ami-003838ea
  machineType: m5.large
  maxSize: 6
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 60
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

```
...
I0619 14:49:45.009897   82893 aws_utils.go:39] Querying EC2 for all valid regions
I0619 14:49:45.643529   82893 aws_cloud.go:981] Querying EC2 for all valid zones in region "eu-west-1"
I0619 14:49:45.643686   82893 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I0619 14:49:45.958178   82893 aws_cloud.go:423] Listing all Autoscaling groups matching cluster tags
I0619 14:49:45.960381   82893 request_logger.go:45] AWS request: autoscaling/DescribeTags
I0619 14:49:46.266176   82893 request_logger.go:45] AWS request: autoscaling/DescribeAutoScalingGroups
NAME			STATUS		NEEDUPDATE	READY	MIN	MAX	NODES
bastions		NeedsUpdate	1		0	1	1	0
master-eu-west-1a	Ready		0		1	1	1	1
master-eu-west-1b	Ready		0		1	1	1	1
master-eu-west-1c	Ready		0		1	1	1	1
nodes			NeedsUpdate	3		0	3	6	3

Must specify --yes to rolling-update.
```

9. Anything else do we need to know?

I use https://github.com/cristim/autospotting to automatically replace on-demand instances with spot instances. The spot instances have the same configuration as the on-demand instances and they are attached to the same ASG (bastion & nodes).
Whenever a new on-demand instance comes up (for example by cluster autoscaling), Autospotting will replace it with a spot-instance.
