### ISSUE TITLE
Logrotate fails to rotate twice in a day making maxsize setting ineffective

### ISSUE THREAD

**Issue by trinitronx** [kubernetes/kops#5378]
Opening new issue given current `logstash` configuration problem.

### Details

Looks like this is still an issue in `kops Version 1.9.0 (git-cccd71e67)`, and with latest stable CoreOS `1745.6.0`.  It's probably still an issue in other distros too, as I'm not aware of a distro or logrotate version that has different behavior.

There are probably a couple cases where logrotate will fail, but at least one that I've seen is this:

```
rotating pattern: /var/log/kube-apiserver.log after 1 days (5 rotations)
empty log files are not rotated, log files >= 104857600 are rotated earlier, old logs are removed
considering log /var/log/kube-apiserver.log
  log needs rotating
rotating log /var/log/kube-apiserver.log, log->rotateCount is 5
dateext suffix '-20180612'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
glob finding logs to compress failed
destination /var/log/kube-apiserver.log-20180612 already exists, skipping rotation
```

Unfortunately, `logrotate` silently skips rotation with the current configuration used in `kops` and default configs in many other distros!  This is probably due to very unintuitive configuration & expected behavior with `maxsize` in `logrotate`.

### Problem

The default `/usr/share/logrotate/logrotate.conf` has `dateext` option enabled.  With this option, all rotated log files will get suffix including the current date with day granularity.

Usually, this works fine if log rotation with minimum granularity of 1 day keeps log file size below max size & all combined logs + rotated files under disk full threshold.  However, when logs grow faster than the threshold _within 1 day_, then `logrotate` refuses to do a subsequent (second, third, etc...) rotation in that day!  Eventually if logs continue to grow at this higher rate, you end up with disk full, and a server in very bad state when `/var/log` is on an important partition.

Q: Why does this happen?
A: `logrotate` with `dateext` by default will [_**skip rotation**_ when a file with `dateext` suffix already exists](https://unix.stackexchange.com/a/29590/7688) for that day!

This can be a problem when services generate a lot of logs.  You might set `maxsize` in a logrotate config, and set up hourly rotation expecting that this will prevent logs from growing over `maxsize`, and rotate multiple times per day on the hour.  Unfortunately, `logrotate` does not behave this way by default when a previous rotated log for that day already exists.  You can see by the verbose output above from `logrotate -v` that it tells you why it's skipping in this case.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running?

`Version 1.9.0 (git-cccd71e67)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

`kops create cluster`
Cluster with default logrotate config comes up with logrotate behavior affected by this issue.

5. What happened after the commands executed?

Cluster is healthy until log line creation rate on a node exceeds that required to fill disk after first rotation & `maxsize` is exceeded in a single day.  Logrotate fails to rotate a subsequent time, and disk fills up!

6. What did you expect to happen?

Logrotate should rotate _again_ and any time `maxsize` for the log files are exceeded.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-19T20:30:16Z
  name: foo.dev.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    app: kubernetes
    component: infrastructure
    created_by: kops
    support_level: dev
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: s3://foo.dev.local/foo.dev.local
  configStore: s3://foo.dev.local/foo.dev.local
  dnsZone: Z3BHGNMGZ2EV0G
  docker:
    bridge: ""
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay,aufs
    version: 17.03.2
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: us-east-1b-1
    name: main
    version: 3.0.17
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1b-1
      name: us-east-1b-1
    name: events
    version: 3.0.17
  hooks:
  - before:
    - network-pre.target
    - kubelet.service
    manifest: |
      Type=oneshot
      ExecStart=/usr/sbin/modprobe br_netfilter
      [Unit]
      Wants=network-pre.target
      [Install]
      WantedBy=multi-user.target
    name: fix-dns.service
    roles:
    - Node
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  keyStore: s3://foo.dev.local/foo.dev.local/pki
  kubeAPIServer:
    address: 127.0.0.1
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: 1
    authorizationMode: RBAC
    cloudProvider: aws
    etcdQuorumRead: false
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    image: gcr.io/google_containers/kube-apiserver:v1.9.3
    insecurePort: 8080
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    oidcCAFile: /srv/kubernetes/ca.crt
    oidcClientID: foo.dev.local
    oidcGroupsClaim: user_roles
    oidcGroupsPrefix: 'oidc:'
    oidcIssuerURL: https://dex.kube-system.svc.cluster.local
    oidcUsernameClaim: sub
    oidcUsernamePrefix: 'oidc:'
    requestheaderAllowedNames:
    - aggregator
    requestheaderExtraHeaderPrefixes:
    - X-Remote-Extra-
    requestheaderGroupHeaders:
    - X-Remote-Group
    requestheaderUsernameHeaders:
    - X-Remote-User
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd3
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: foo.dev.local
    configureCloudRoutes: false
    image: gcr.io/google_containers/kube-controller-manager:v1.9.3
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    domain: cluster.local
    replicas: 2
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    hostnameOverride: '@aws'
    image: gcr.io/google_containers/kube-proxy:v1.9.3
    logLevel: 2
  kubeScheduler:
    image: gcr.io/google_containers/kube-scheduler:v1.9.3
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      ExperimentalCriticalPodAnnotation: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: gcr.io/google_containers/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    requireKubeconfig: true
  kubernetesApiAccess:
  - 10.97.3.0/24
  kubernetesVersion: v1.9.3
  masterInternalName: api.internal.foo.dev.local
  masterKubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: cluster.local
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    featureGates:
      ExperimentalCriticalPodAnnotation: "true"
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: gcr.io/google_containers/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
    requireKubeconfig: true
  masterPublicName: api.foo.dev.local
  networkCIDR: 10.97.3.0/24
  networkID: vpc-12345678
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://foo.dev.local/foo.dev.local/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
  - 10.97.3.0/24
  subnets:
  - cidr: 10.97.3.32/27
    egress: nat-c0fefe1234567890a
    id: subnet-543210fe
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.97.3.96/27
    egress: nat-c0fefe1234567890a
    id: subnet-badc0de1
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.97.3.160/27
    id: subnet-feedc0de
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.97.3.224/27
    id: subnet-feedbeef
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T20:30:17Z
  labels:
    kops.k8s.io/cluster: foo.dev.local
  name: master-us-east-1b-1
spec:
  image: ami-3f061b45
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b-1
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T20:30:17Z
  labels:
    kops.k8s.io/cluster: foo.dev.local
  name: nodes
spec:
  associatePublicIp: false
  image: ami-3f061b45
  machineType: c4.large
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: node
  role: Node
  subnets:
  - us-east-1b
  - us-east-1e
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

This probably wouldn't assist with solving this issue... it's in logrotate configuration

9. Anything else do we need to know?

Looks like this issue was duplicated & attempted fixes made in different ways:

#2710
#2816
#3055
