### ISSUE TITLE
Misleading error when `logDriver` is omitted from the `spec.docker` cluster config section

### ISSUE THREAD

**Issue by geekofalltrades** [kubernetes/kops#5384]
------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

   1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

    ```
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
    ```

3. What cloud provider are you using?

   AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

   Run `kops edit cluster` and attempt to set a configuration value in the `spec.docker` config section. In my case, I am trying to set `storage: overlay2`. By default, the `docker` section is missing, and I have to add it.

5. What happened after the commands executed?

   The cluster is not edited successfully. This error is displayed:

    ```
    # Found fields that are not recognized
    # ...
    #     configBase: [omitted]
    #     docker:
    # -     logDriver: ""
    #       storage: overlay2
    #     encryptionConfig: true
    # ...
    ```

6. What did you expect to happen?

   The cluster to be edited successfully.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

    ```
    apiVersion: kops/v1alpha2
    kind: Cluster
    metadata:
      creationTimestamp: 2018-06-25T22:08:28Z
      name: [omitted]
    spec:
      additionalPolicies:
        bastion: '[{"Effect":"Allow","Action":["logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents","logs:DescribeLogStreams"],"Resource":["arn:aws:logs:*:*:*"]},{"Effect":"Allow","Action":["kms:GenerateRandom"],"Resource":["*"]}]'
        master: '[{"Effect":"Allow","Action":["logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents","logs:DescribeLogStreams"],"Resource":["arn:aws:logs:*:*:*"]},{"Effect":"Allow","Action":["kms:GenerateRandom"],"Resource":["*"]},{"Effect":"Allow","Action":["ec2:ModifyVolume","ec2:DescribeVolumesModifications"],"Resource":["*"]}]'
        node: '[{"Effect":"Allow","Action":["logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents","logs:DescribeLogStreams"],"Resource":["arn:aws:logs:*:*:*"]},{"Effect":"Allow","Action":["kms:GenerateRandom"],"Resource":["*"]}]'
      api:
        loadBalancer:
          type: Public
      authorization:
        rbac: {}
      channel: stable
      cloudLabels:
        [omitted]
      cloudProvider: aws
      configBase: [omitted]
      encryptionConfig: true
      etcdClusters:
      - enableEtcdTLS: true
        etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-us-west-2a-1
          kmsKeyId: [omitted]
          name: [omitted]
        - encryptedVolume: true
          instanceGroup: master-us-west-2a-2
          kmsKeyId: [omitted]
          name: [omitted]
        - encryptedVolume: true
          instanceGroup: master-us-west-2a-3
          kmsKeyId: [omitted]
          name: [omitted]
        name: main
        version: 3.1.11
      - enableEtcdTLS: true
        etcdMembers:
        - encryptedVolume: true
          instanceGroup: master-us-west-2a-1
          kmsKeyId: [omitted]
          name: [omitted]
        - encryptedVolume: true
          instanceGroup: master-us-west-2a-2
          kmsKeyId: [omitted]
          name: [omitted]
        - encryptedVolume: true
          instanceGroup: master-us-west-2a-3
          kmsKeyId: [omitted]
          name: [omitted]
        name: events
        version: 3.1.11
      iam:
        allowContainerRegistry: true
        legacy: false
      kubeAPIServer:
        admissionControl:
        - Initializers
        - NamespaceLifecycle
        - LimitRanger
        - ServiceAccount
        - PersistentVolumeLabel
        - DefaultStorageClass
        - DefaultTolerationSeconds
        - MutatingAdmissionWebhook
        - ValidatingAdmissionWebhook
        - NodeRestriction
        - PersistentVolumeClaimResize
        - ResourceQuota
        featureGates:
          ExpandPersistentVolumes: "true"
        logLevel: 1
      kubeControllerManager:
        featureGates:
          ExpandPersistentVolumes: "true"
      kubernetesApiAccess:
        [omitted]
      kubernetesVersion: 1.9.6
      masterInternalName: [omitted]
      masterPublicName: [omitted]
      networkCIDR: 172.20.0.0/16
      networking:
        calico: {}
      nonMasqueradeCIDR: 100.64.0.0/10
      sshAccess:
        [omitted]
      subnets:
      - cidr: 172.20.32.0/19
        name: us-west-2a
        type: Private
        zone: us-west-2a
      - cidr: 172.20.64.0/19
        name: us-west-2b
        type: Private
        zone: us-west-2b
      - cidr: 172.20.0.0/22
        name: utility-us-west-2a
        type: Utility
        zone: us-west-2a
      - cidr: 172.20.4.0/22
        name: utility-us-west-2b
        type: Utility
        zone: us-west-2b
      topology:
        bastion:
          bastionPublicName: [omitted]
        dns:
          type: Public
        masters: private
        nodes: private
      updatePolicy: external
    ```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

   (Nothing interesting.)

9. Anything else do we need to know?

   The edit appears to be removing a `logDriver` config value that defaults to an empty string, but it definitely wasn't displayed in the spec -- I had to add the `spec.docker` section.

   When I add the `logDriver` option and set it to an empty string, the edit is successful.

   So, (1) there's some problem around this `logDriver` option and the way its default value is set; and (2) when it's omitted, the resulting error message is misleading, because `storage` is a valid field, not one that is not recognized.
