### ISSUE TITLE
Default Calico Networking Config in 1.8/1.9 makes APIServer unreachable

### ISSUE THREAD

**Issue by shivshav** [kubernetes/kops#5391]
Hey guys! We've been using `kops` to manage our cluster in AWS for quite a while and have had an awesome experience with it. Ran into an issue when upgrading our staging cluster from `1.7.8` to `1.8.13` (and from `1.8.13` to `1.9.8`) with an improper config when using calico as our networking plugin where the apiserver would become unreachable by multiple different services.

# Cluster/Issue Details

1. What `kops` version are you running? 
`Version 1.9.1 (git-ba77c9ca2)`

2. What Kubernetes version are you running? 
Upgrading from `v1.7.8` --> `v1.8.13` --> `v1.9.8`

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Followed [this](https://github.com/kubernetes/kops/blob/master/docs/upgrade.md#manual-update) to upgrade first from `1.7.8` to `1.8.13`. When we experienced the issue and were unable to find an answer, we decided to move from `1.8.13` to `1.9.8` as that was our ultimate goal to land at anyways for dealing with unrelated DNS issues.

5. What happened after the commands executed?
Cluster came up, but APIServer was unreachable by things like `kube-proxy`,`dns-controller`, and horizontal pod autoscaler trying to access `metrics-server` and/or `heapster` through APIServer

6. What did you expect to happen?
No change in behavior from previous kubernetes version regarding things like autoscaling.

7. Please provide your cluster manifest.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-05-31T07:09:20Z
  name: <CLUSTER_NAME>
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://<s3-bucket>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    legacy: true
  kubeAPIServer:
    featureGates:
      CustomPodDNS: "true"
    runtimeConfig:
      batch/v2alpha1: "true"
  kubelet:
    featureGates:
      CustomPodDNS: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.8
  masterInternalName: api.internal.<CLUSTER_NAME>
  masterPublicName: api.<CLUSTER_NAME>
  networkCIDR: 10.40.0.0/16
  networkID: <VPC-ID>
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - x.x.x.x/24
  - x.x.x.x/24
  subnets:
  - cidr: 10.40.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.40.64.0/19
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.40.96.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.40.100.0/22
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-31T07:09:20Z
  labels:
    kops.k8s.io/cluster: <CLUSTER_NAME>
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-31T07:09:21Z
  labels:
    kops.k8s.io/cluster: <CLUSTER_NAME>
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m4.large
  maxSize: 6
  minSize: 1
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-2a
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-16T02:51:53Z
  labels:
    kops.k8s.io/cluster: <CLUSTER_NAME>
  name: util-node
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: r4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    leafly/node-util: "true"
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-2a
  - us-west-2b
```

8. Some samples of logs
`kube-controller-manager`
```
kube-controller-manager-ip-x-x-x-x.us-west-2.compute.internal kube-controller-manager 2018-06-25T22:49:02.446604264Z I0625 22:49:02.446371       1 event.go:218] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"integration", Name:"integration-data-api", UID:"1e6f6714-1cf2-11e8-98ce-069c1008689c", APIVersion:"autoscaling/v2beta1", ResourceVersion:"71325290", FieldPath:""}): type: 'Warning' reason: 'FailedComputeMetricsReplicas' failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```
From HPA events
```
Warning FailedComputeMetricsReplicas 51m (x411 over 4h) horizontal-pod-autoscaler failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://X.X.X.X:****/apis/metrics/v2beta1/namespaces/default/pods?labelSelector=app%3Dcnum'") has prevented the request from succeeding (get pods.metrics.k8s.io)
```

9. Anything else do we need to know?
Calico Versions:
`quay.io/calico/node:v2.6.7`
`quay.io/calico/cni:v1.11.2`

We managed to fix the issue by adding 
```
          - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
            value: ACCEPT
```
to the calico DaemonSet configuration as it turns out the default configuration regarding packets going from an endpoint back to the host was changed from `ACCEPT` to `DROP`. Was wondering if this could become a default in the calico yaml template maintained in the repo for 1.8+ (happy to submit as a PR) or at least configurable option through the NetworkingSpec so that all our cluster state can continue to be maintained through the state store. If this is not expected behavior when upgrading, then I'd be curious to hear thoughts on why we happened to run into this issue as there is nothing special about our calico networking configuration. Please let me know if I can provide any more information
