### ISSUE TITLE
DNS-controller problem with public IP

### ISSUE THREAD

**Issue by kaliha** [kubernetes/kops#5406]
1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.9.1 (git-ba77c9ca2)

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
v1.9.6

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?
Create cluster with 
`  topology:
    dns:
      type: Public
    masters: private
    nodes: public`
Create new service and ingress. Try to assign annotation to service:
`dns.alpha.kubernetes.io/external: sub.domain.com`

5. What happened after the commands executed?
Service and ingress created without public IP.

6. What did you expect to happen?
DNS record with public node public ip.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: kube-system
  labels:
    k8s-app: app
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Dex"
    dns.alpha.kubernetes.io/external: sub.domain.com
spec:
  ports:
  - port: 5556
    protocol: TCP
    targetPort: 5556
    name: https
  selector:
    app: app

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: app
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - sub.domain.com
    secretName: tls-secret
  rules:
  - host: sub.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 5556
```
