### ISSUE TITLE
ipvs proxier doesn't work with pod->service->pod on the same node

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kops#5408]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.9.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.9.6

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

I followed the aws doc. The only change is I enabled the ipvs proxier.
```
kubeProxy:
  proxyMode: ipvs
  featureGates:
    SupportIPVSProxyMode: "true"
```

5. What happened after the commands executed?

Starts up fine. However, I am unable to access pods on the same node via the service IP. Something seems broken with the hairpin nat setup.

6. What did you expect to happen?

Should be able to access pods via service IP regardless of where they are.

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

Sorry, I deleted my cluster.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

Apologies, I deleted my cluster due to using a personal account. So I'm listing the steps here from memory. iptables mode worked fine. So something seems screwy with the ipvs mode setup.

**Comment by igorvpcleao** [comment]
Hi @jsravn,

I'm considering modifying my cluster to use IPVS and I found your issue. So, I tried to reproduce what happened.
I created an `API` (a deployment) and a `requester` (a daemonset) for consulting this API.
```
k get pods -n requester-poc -o wide
NAME              READY     STATUS    RESTARTS   AGE       IP              NODE
requester-bhj9b   1/1       Running   0          25m       172.20.49.143   ip-172-20-33-52.ec2.internal
requester-lkcg2   1/1       Running   0          13m       172.20.33.22    ip-172-20-56-17.ec2.internal
requester-ntmjm   1/1       Running   0          19m       172.20.37.182   ip-172-20-48-43.ec2.internal
```
```
k get pods -n hey-iam-alive-poc -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP              NODE
hey-iam-alive-7969ffdcd4-77h5b   1/1       Running   0          13m       172.20.48.146   ip-172-20-33-52.ec2.internal
hey-iam-alive-7969ffdcd4-z22ch   1/1       Running   0          13m       172.20.32.175   ip-172-20-48-43.ec2.internal
```
```
k get svc -n hey-iam-alive-poc
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
http      ClusterIP   100.71.196.35   <none>        80/TCP    6d
```
As we can see, we have both `API` and `requester` pods on node `ip-172-20-33-52.ec2.internal`. Therefore, I scaled down `hey-iam-alive-poc` to just the pod running on that node. 
```
k get pods -n hey-iam-alive-poc -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP              NODE
hey-iam-alive-7969ffdcd4-77h5b   1/1       Running   0          13m       172.20.48.146   ip-172-20-33-52.ec2.internal
```
After that, I could see some failures for a short period of time, but after that everything seems to be ok.

<img width="1608" alt="screen shot 2018-07-11 at 17 06 48" src="https://user-images.githubusercontent.com/3065657/42597246-906aa95e-852e-11e8-9ed8-ad10d5042700.png">

Prometheus metric used for plotting:
```increase(poc_requester_success[1m])``` and ```increase(poc_requester_failures[1m])```

Also, within `hey-iam-alive-7969ffdcd4-77h5b` I tried to curl the service, and everything worked fine.

```
root@hey-iam-alive-7969ffdcd4-77h5b:/app# curl http.hey-iam-alive-poc.svc.cluster.local.:80
Hey. Look, I'm alive!
```

Am I missing something?

Thanks!

**Comment by jsravn** [comment]
@igorvpcleao What k8s version did you use? Are you sure it was using ipvs mode? I will attempt to try again later today.

**Comment by igorvpcleao** [comment]
`1.9.6` and `amazon-vpc` as CNI

**Comment by igorvpcleao** [comment]
Sorry, I noticed I did not answer your last question.
```
$ ps aux | grep kube-proxy
root      3012  0.2  1.0  57224 42704 ?        Ssl  Jul11   6:03 /usr/local/bin/kube-proxy --cluster-cidr=100.96.0.0/11 --conntrack-max-per-core=131072 --feature-gates=SupportIPVSProxyMode=true --hostname-override=ip-172-20-56-17.ec2.internal --kubeconfig=/var/lib/kube-proxy/kubeconfig --master=https://api.internal.kube-xalala --oom-score-adj=-998 --proxy-mode=ipvs --resource-container= --v=2
root      3023  0.0  0.0   4204   692 ?        S    Jul11   0:00 tee -a /var/log/kube-proxy.log
admin    19943  0.0  0.0   3016   248 pts/0    R+   13:27   0:00 grep kube-proxy
```
```
$ ps aux | grep kube-proxy
root      3042  0.2  1.0  57224 42020 ?        Ssl  Jul11   5:38 /usr/local/bin/kube-proxy --cluster-cidr=100.96.0.0/11 --conntrack-max-per-core=131072 --feature-gates=SupportIPVSProxyMode=true --hostname-override=ip-172-20-48-43.ec2.internal --kubeconfig=/var/lib/kube-proxy/kubeconfig --master=https://api.internal.kube-test.xalala --oom-score-adj=-998 --proxy-mode=ipvs --resource-container= --v=2
```
```
$ ps aux | grep kube-proxy
root      2923  0.2  1.0  56968 42192 ?        Ssl  Jul11   5:57 /usr/local/bin/kube-proxy --cluster-cidr=100.96.0.0/11 --conntrack-max-per-core=131072 --feature-gates=SupportIPVSProxyMode=true --hostname-override=ip-172-20-33-52.ec2.internal --kubeconfig=/var/lib/kube-proxy/kubeconfig --master=https://api.internal.kube-test.xalala --oom-score-adj=-998 --proxy-mode=ipvs --resource-container= --v=2
```
```
$ ps aux | grep kube-proxy
root      3463  0.3  1.0  56968 42060 ?        Ssl  Jul11   8:32 /usr/local/bin/kube-proxy --cluster-cidr=100.96.0.0/11 --conntrack-max-per-core=131072 --feature-gates=SupportIPVSProxyMode=true --hostname-override=ip-172-20-56-162.ec2.internal --kubeconfig=/var/lib/kube-proxy/kubeconfig --master=https://127.0.0.1 --oom-score-adj=-998 --proxy-mode=ipvs --resource-container= --v=2
```

**Comment by jsravn** [comment]
@igorvpcleao I just used whatever the default is. Not sure what it uses out of the box.

Here's my config
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-07-19T15:54:10Z
  name: ravncluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://super-secret-bucket/ravncluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    featureGates:
      SupportIPVSProxyMode: "true"
    proxyMode: ipvs
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.6
  masterInternalName: api.internal.ravncluster.k8s.local
  masterPublicName: api.ravncluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
