### ISSUE TITLE
ClusterAutoscaler autodiscovery

### ISSUE THREAD

**Issue by thomasjungblut** [kubernetes/kops#5415]
------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

I just wanted to wire up CA's autodiscovery feature (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup). 

But I figured out that Kops does not add the required tags to the ASG:
> k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<YOUR CLUSTER NAME>

2. Feel free to provide a design supporting your feature request.

Simply adding the tags to the instance group cloud context:
https://github.com/kubernetes/kops/blob/9b803261297adbd75be98e4182adb8dfca8965e8/pkg/model/context.go#L170

Happy to create a PR if that sounds sane to you guys?

EDIT: 

also figured out that we can add this to instance groups directly:

```
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/cluster-name: "smth"
    k8s.io/cluster-autoscaler/enabled: "true"
```

so maybe it's better to have it as a feature flag? also don't know how it fits with the existing kops CA addon. 

Cheers,
Thomas
