### ISSUE TITLE
Downgrade does not affect instance group image versions

### ISSUE THREAD

**Issue by renewooller** [kubernetes/kops#5436]
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.

1.9.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

1.11.0 (client version - master server is unreachable, was 1.9.x)

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

kops edit cluster
-> changed kubernetesVersion from 1.9.1 to 1.7.0 (downgrade)

kops update cluster --yes

kops rolling-update cluster --yes

5. What happened after the commands executed?

During the update, it terminated master, then attempted to validate the cluster. The validation failed, it tried again every 30s until timing out after 5 minutes. The problem was that the volume for etc was not attached to the new instance of master. 

One thing I noticed that could be behind this behaviour is that the 'kops edit cluster' and 'kops update cluster --yes' did not actually change the image used by the master node. That is, it remained:

  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11

Despite the version shifting to 1.7

6. What did you expect to happen?

I expected the image to be

  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2018-03-11

7. Please provide your cluster manifest. Execute

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-06-08T00:53:45Z
  name: dev.xxx.com
spec:
  additionalPolicies:
    node: "[\n  {\n    \"Effect\": \"Allow\",\n    \"Action\": [\"s3:*\"],\n    \"Resource\":
      [\"*\"]\n  }\n] \n"
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://dev-xxx-com-state-store/dev.xxx.com
  dnsZone: dev.xxx.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    name: events
  iam:
    legacy: true
  kubeAPIServer:
    allowPrivileged: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.0
  masterInternalName: api.internal.dev.xxx.com
  masterPublicName: api.dev.xxx.com
  networkCIDR: 10.20.0.0/16
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.20.32.0/19
    name: us-west-1a
    type: Private
    zone: us-west-1a
  - cidr: 10.20.0.0/22
    name: utility-us-west-1a
    type: Utility
    zone: us-west-1a
  topology:
    bastion:
      bastionPublicName: bastion.dev.xxx.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-08T01:13:10Z
  labels:
    kops.k8s.io/cluster: dev.xxx.com
  name: apps
spec:
  additionalSecurityGroups:
  - sg-6e505009
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    type: apps
  role: Node
  subnets:
  - us-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-08T00:53:46Z
  labels:
    kops.k8s.io/cluster: dev.xxx.com
  name: bastions
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - utility-us-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-08T00:53:46Z
  labels:
    kops.k8s.io/cluster: dev.xxx.com
  name: master-us-west-1a
spec:
  additionalSecurityGroups:
  - sg-6e505009
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-08T01:23:01Z
  labels:
    kops.k8s.io/cluster: dev.xxx.com
  name: services
spec:
  additionalSecurityGroups:
  - sg-6e505009
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.small
  maxSize: 2
  minSize: 2
  nodeLabels:
    type: services
  role: Node
  subnets:
  - us-west-1a
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?

I noticed that none of the images on the instance groups were updated

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

the update, if the version is different, should update the instance groups. 

2. Feel free to provide a design supporting your feature request.
