### ISSUE TITLE
NVMe drives are not being automatically mounted on CoreOS nodes in AWS

### ISSUE THREAD

**Issue by chrissnell** [kubernetes/kops#5468]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

`1.10.0-alpha.1`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

`1.10.4`

3. What cloud provider are you using?

AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

Built a new cluster in **us-east-1** using **i3.xlarge** instance types and `595879546273/CoreOS-stable-1745.7.0-hvm` as the image  for my nodes.

NVMe drive is not mounted:

```
$ df -h
Filesystem       Size  Used Avail Use% Mounted on
devtmpfs          15G     0   15G   0% /dev
tmpfs             15G     0   15G   0% /dev/shm
tmpfs             15G  1.4M   15G   1% /run
tmpfs             15G     0   15G   0% /sys/fs/cgroup
/dev/xvda9       122G   22G   96G  19% /
/dev/mapper/usr  985M  713M  221M  77% /usr
none              15G  184M   15G   2% /run/torcx/unpack
/dev/xvda1       128M   49M   80M  38% /boot
tmpfs             15G     0   15G   0% /tmp
tmpfs             15G     0   15G   0% /media
/dev/xvda6       108M  112K   99M   1% /usr/share/oem
tmpfs            3.0G     0  3.0G   0% /run/user/500
```

It's definitely available, just not mounted:

```
$ lsblk
NAME    MAJ:MIN   RM   SIZE RO TYPE  MOUNTPOINT
xvda    202:0      0   128G  0 disk  
|-xvda1 202:1      0   128M  0 part  /boot
|-xvda2 202:2      0     2M  0 part  
|-xvda3 202:3      0     1G  0 part  
| `-usr 254:0      0  1016M  1 crypt /usr
|-xvda4 202:4      0     1G  0 part  
|-xvda6 202:6      0   128M  0 part  /usr/share/oem
|-xvda7 202:7      0    64M  0 part  
`-xvda9 202:9      0 125.7G  0 part  /
nvme0n1 259:0      0 884.8G  0 disk  
xvdbt   202:18176  0    10G  0 disk  /var/lib/kubelet/pods/1/REDACTED
```

6. What did you expect to happen?

NVMe drive would be mounted and available for use in `emptyDir` volumes.

7. Please provide your cluster manifest.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-07-16T18:11:50Z
  name: us-east-1-ci.kube.redacted.domain
spec:
  api:
    dns: {}
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://redacted-kops-store/us-east-1-ci.kube.redacted.domain
  dnsZone: kube.redacted.domain
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUpscaleDelay: 1m0s
    horizontalPodAutoscalerUseRestClients: true
  kubelet:
    enableCustomMetrics: true
    enforceNodeAllocatable: pods
    kubeReserved:
      cpu: 150m
      ephemeral-storage: 1Gi
      memory: 100Mi
    kubeReservedCgroup: /kube-reserved
    systemReserved:
      cpu: 100m
      ephemeral-storage: 1Gi
      memory: 100Mi
    systemReservedCgroup: /system-reserved
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.5
  masterPublicName: api.us-east-1-ci.kube.redacted.domain
  networkCIDR: 10.27.0.0/16
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.27.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.27.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.27.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.27.128.0/19
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.27.160.0/19
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.27.192.0/19
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-16T18:11:50Z
  labels:
    kops.k8s.io/cluster: us-east-1-ci.kube.redacted.domain
  name: master-us-east-1a
spec:
  image: 595879546273/CoreOS-stable-1745.7.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-16T18:11:51Z
  labels:
    kops.k8s.io/cluster: us-east-1-ci.kube.redacted.domain
  name: master-us-east-1b
spec:
  image: 595879546273/CoreOS-stable-1745.7.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-16T18:11:51Z
  labels:
    kops.k8s.io/cluster: us-east-1-ci.kube.redacted.domain
  name: master-us-east-1c
spec:
  image: 595879546273/CoreOS-stable-1745.7.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-16T18:11:51Z
  labels:
    kops.k8s.io/cluster: us-east-1-ci.kube.redacted.domain
  name: nodes
spec:
  image: 595879546273/CoreOS-stable-1745.7.0-hvm
  machineType: i3.xlarge
  maxSize: 30
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c

```
