### ISSUE TITLE
Weird kube-proxy-ip Break Down When Running a Flask Application

### ISSUE THREAD

**Issue by berniechiu** [kubernetes/kops#5473]
1. What `kops` version are you running? The command `kops version`, will display
 this information.

Version 1.9.1

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?

`AWS`

4. What commands did you run?  What is the simplest way to reproduce this issue?

I have a cluster base on this image `https://github.com/puckel/docker-airflow`
I have 3 Celery worker setup in K8S cluster, when I sending jobs and `kube-proxy-ip` service starts to break down.

5. What happened after the commands executed?

Since `kube-proxy-ip` breaks down, most of the DNS in K8S cluster can't be resolved.

6. What did you expect to happen?

My application works as usual

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

```yaml
kops get --name airflow -o yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-07-20T03:27:17Z
  name: airflow
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://airflow-kops-state-store/airflow
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-northeast-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-northeast-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    cpuRequest: 150m
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.9
  masterInternalName: api.internal.airflow
  masterPublicName: api.airflow
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-northeast-2a
    type: Public
    zone: ap-northeast-2a
  - cidr: 172.20.64.0/19
    name: ap-northeast-2c
    type: Public
    zone: ap-northeast-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-20T03:27:17Z
  labels:
    kops.k8s.io/cluster: airflow
  name: master-ap-northeast-2a
spec:
  image: 595879546273/CoreOS-stable-1745.7.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-2a
  role: Master
  subnets:
  - ap-northeast-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-20T03:27:17Z
  labels:
    kops.k8s.io/cluster: airflow
  name: nodes
spec:
  image: 595879546273/CoreOS-stable-1745.7.0-hvm
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-northeast-2a
  - ap-northeast-2c
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

`TLS handshake timeout` on `kube-proxy-id` log

After remove the Airflow app, I can see other messages like

`Stale udp service kube-system kube-dns` might be the problem?

Maybe there's another way I can see more precise failing log?

9. Anything else do we need to know?

I've followed this link on DNS problem but seems no luck
https://medium.com/tailor-tech/production-grade-kubernetes-on-aws-3-lessons-learned-scaling-a-cluster-a421dfe786dd

I also directly scale the CPU resource on kube-proxy-id and also no luck

Thanks for the help!
