### ISSUE TITLE
Running multiple clusters in 1 GCE project causes networking issues

### ISSUE THREAD

**Issue by RobertDiebels** [kubernetes/kops#5495]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.9.1
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.8.7
**3. What cloud provider are you using?**
GCE
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I created and deployed 2 clusters with `kops create` and `kops update cluster`
**5. What happened after the commands executed?**
Commands execute correctly, clusters are deployed. Networking resolution fails in kubernetes internally.
**6. What did you expect to happen?**
My expectation was that I would be able to setup networking if each cluster had it's own instances. 
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

In the yaml below I replaced my project-name with `...`.

**Cluster 1**
_Cluster.yaml_
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: leaf-1.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://.../leaf-1.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: b
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.7
  masterPublicName: api.leaf-1.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: ...
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: europe-west1
    region: europe-west1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
_nodes.yaml_
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: leaf-1.k8s.local
  name: nodes
spec:
  image: cos-cloud/cos-stable-60-9592-90-0
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  rootVolumeType: pd-standard
  rootVolumeSize: 60
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
```
_masters.yaml_
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: leaf-1.k8s.local
  name: master-europe-west1-b
spec:
  image: cos-cloud/cos-stable-60-9592-90-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  rootVolumeType: pd-standard
  rootVolumeSize: 60
  nodeLabels:
    kops.k8s.io/instancegroup: master-europe-west1-b
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
```

**Cluster 2**
_cluster.yaml_
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: root.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://.../root.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: b
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.7
  masterPublicName: api.root.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: ...
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: europe-west1
    region: europe-west1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
_masters.yaml_
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: root.k8s.local
  name: master-europe-west1-b
spec:
  image: cos-cloud/cos-stable-60-9592-90-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  rootVolumeType: pd-standard
  rootVolumeSize: 60
  nodeLabels:
    kops.k8s.io/instancegroup: master-europe-west1-b
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
```
_nodes.yaml_
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: root.k8s.local
  name: nodes
spec:
  image: cos-cloud/cos-stable-60-9592-90-0
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  rootVolumeType: pd-standard
  rootVolumeSize: 60
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A
**9. Anything else do we need to know?**
The problem is with networking within the clusters.
I've launched both clusters separately and they work fine. However when deploying them both at the same time, to the same project, the networking gets wonky.

I don't have a use-case but it seems to be related to a DNS issue [https://github.com/kubernetes/kops/issues/4391] because I can reach IP's just fine.
