### ISSUE TITLE
Upgrading to 1.10.3 does not respect custom image value for instance group

### ISSUE THREAD

**Issue by merlineus** [kubernetes/kops#5505]
I have a cluster provisioned with kops v1.9.1 on AWS and a custom instance group with image "k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11". Master nodes have default images "k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11". After updating kops to 1.10.0-beta.1 I've tried to upgrade cluster to Kubernetes version 1.10.3, but upgrade procedure ignore image specified in manifest file.

Kops version: Version 1.10.0-beta.1

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.1-dirty", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"dirty", BuildDate:"2018-07-21T09:59:23Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Manifest for instance group:

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-24T12:57:13Z
  labels:
    kops.k8s.io/cluster: frankfurt.k8s.local
  name: nodes-db-test
spec:
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: i3.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    app: stolon
    kops.k8s.io/instancegroup: nodes-db-test
  role: Node
  subnets:
  - eu-central-1a
```

Kops upgrade output:
```
ITEM					PROPERTY		OLD							NEW
Cluster					KubernetesVersion	1.9.6							1.10.3
InstanceGroup/master-eu-central-1a	Image			kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08	kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
InstanceGroup/master-eu-central-1b	Image			kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08	kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
InstanceGroup/master-eu-central-1c	Image			kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08	kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
InstanceGroup/nodes			Image			kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08	kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
InstanceGroup/nodes-db-test		Image			kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11	kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
```
