### ISSUE TITLE
kops 1.10.1 beta and k8s 1.10.3

### ISSUE THREAD

**Issue by cdenneen** [kubernetes/kops#5545]
Just updated from 1.9.0 and k8s 1.9.6 to latest kops.

Master nodes upgraded to 1.10.3 fine but none of the workers registered.
In inspecting they all complained they had no networking configuration in /etc/cni
Cluster was configured for calico.
If I checked the master nodes they all had the calico configurations and binaries in /opt/cni/bin. It's just the worker nodes.

I have reverted kops to 1.9.2 and when I went to apply the cluster update here was the difference which showed something interesting (_networking_cni) wasn't in the 1.10 config. Guessing this is a bug that I wanted to bring to someone's attention:

```
~ » kops update cluster
Using cluster from kubectl context: k8s.example.com

W0727 21:29:04.172846   38764 firewall.go:249] Opening etcd port on masters for access from the nodes, for calico.  This is unsafe in untrusted environments.
I0727 21:29:04.177338   38764 executor.go:91] Tasks: 0 done / 97 total; 37 can run
I0727 21:29:04.413667   38764 executor.go:91] Tasks: 37 done / 97 total; 32 can run
I0727 21:29:04.569304   38764 executor.go:91] Tasks: 69 done / 97 total; 20 can run
I0727 21:29:06.045993   38764 executor.go:91] Tasks: 89 done / 97 total; 5 can run
I0727 21:29:06.152860   38764 dnsname.go:111] AliasTarget for "api.k8s.example.com." is "internal-api-k8s-example-com-j0nvj9-372528243.us-east-1.elb.amazonaws.com."
I0727 21:29:06.363534   38764 executor.go:91] Tasks: 94 done / 97 total; 3 can run
I0727 21:29:06.567058   38764 executor.go:91] Tasks: 97 done / 97 total; 0 can run
Will modify resources:
  IAMRolePolicy/additional.masters.k8s.example.com
  	PolicyDocument
  	                    	...
  	                    	    "Statement": [
  	                    	      {
  	                    	+       "Sid": "",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...


  IAMRolePolicy/additional.nodes.k8s.example.com
  	PolicyDocument
  	                    	...
  	                    	    "Statement": [
  	                    	      {
  	                    	+       "Sid": "",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...


  IAMRolePolicy/masters.k8s.example.com
  	PolicyDocument
  	                    	...
  	                    	    "Statement": [
  	                    	      {
  	                    	+       "Sid": "kopsK8sEC2MasterPermsFullAccess",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sASMasterPerms",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sELBMasterPermsFullAccess",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsMasterCertIAMPerms",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sS3GetListBucket",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sS3BucketFullAccess",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sRoute53Change",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sRoute53GetChanges",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sRoute53ListZones",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sECR",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...


  IAMRolePolicy/nodes.k8s.example.com
  	PolicyDocument
  	                    	...
  	                    	    "Statement": [
  	                    	      {
  	                    	+       "Sid": "kopsK8sEC2NodePerms",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sS3GetListBucket",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sS3BucketFullAccess",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sRoute53Change",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sRoute53GetChanges",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sRoute53ListZones",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...
  	                    	      },
  	                    	      {
  	                    	+       "Sid": "kopsK8sECR",
  	                    	        "Effect": "Allow",
  	                    	        "Action": [
  	                    	...


  LaunchConfiguration/master-us-east-1a.masters.k8s.example.com
  	UserData
  	                    	...
  	                    	  set -o pipefail

  	                    	+ NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/nodeup
  	                    	- NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/nodeup
  	                    	- NODEUP_HASH=cf090a0bcae814feca2893678e3379c89673b370
  	                    	-
  	                    	+ NODEUP_HASH=bdbcc902bd22995ac3c8b4a0636bcd93070849a0
  	                    	+
  	                    	+
  	                    	+
  	                    	- export AWS_REGION=us-east-1


  	                    	...
  	                    	  cloudConfig: null
  	                    	  docker:
  	                    	+   bridge: ""
  	                    	    insecureRegistry: artifactory.example.com:6555
  	                    	    ipMasq: false
  	                    	    ipTables: false
  	                    	+   logDriver: json-file
  	                    	-   logDriver: ""
  	                    	    logLevel: warn
  	                    	+   logOpt:
  	                    	+   - max-size=10m
  	                    	+   - max-file=5
  	                    	    storage: overlay,aufs
  	                    	    version: 17.03.2
  	                    	...
  	                    	      version: 2.2.1
  	                    	  kubeAPIServer:
  	                    	-   allowPrivileged: true
  	                    	-   anonymousAuth: false
  	                    	-   apiServerCount: 3
  	                    	-   authorizationMode: AlwaysAllow
  	                    	+   address: 127.0.0.1
  	                    	-   bindAddress: 0.0.0.0
  	                    	-   cloudProvider: aws
  	                    	+   admissionControl:
  	                    	-   enableAdmissionPlugins:
  	                    	    - Initializers
  	                    	    - NamespaceLifecycle
  	                    	...
  	                    	    - NodeRestriction
  	                    	    - ResourceQuota
  	                    	+   allowPrivileged: true
  	                    	+   anonymousAuth: false
  	                    	+   apiServerCount: 3
  	                    	+   authorizationMode: AlwaysAllow
  	                    	+   cloudProvider: aws
  	                    	    etcdQuorumRead: false
  	                    	    etcdServers:
  	                    	...
  	                    	    - /events#http://127.0.0.1:4002
  	                    	    image: k8s.gcr.io/kube-apiserver:v1.10.3
  	                    	-   insecureBindAddress: 127.0.0.1
  	                    	    insecurePort: 8080
  	                    	    kubeletPreferredAddressTypes:
  	                    	...
  	                    	  - 94f996d645e74634a4be67bbb5417f892774230b@https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
  	                    	  - d595d3ded6499a64e8dac02466e2f5f2ce257c9f@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-amd64-v0.6.0.tgz
  	                    	+ - 72fac6679084d1f929d0abbd8a9ff9337273504b@https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/utils.tar.gz
  	                    	- - 1029269ea06e790e1daa50932269cc9aa983c137@https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/utils.tar.gz
  	                    	  ClusterName: k8s.example.com
  	                    	  ConfigBase: s3://k8s-example-com-state-store/k8s.example.com
  	                    	...
  	                    	  - _aws
  	                    	  - _kubernetes_master
  	                    	+ - _networking_cni
  	                    	  channels:
  	                    	  - s3://k8s-example-com-state-store/k8s.example.com/addons/bootstrap-channel.yaml
  	                    	  protokubeImage:
  	                    	+   hash: 527db0b5fd4b635e6cb2ca22bfec813a048855a7
  	                    	-   hash: 638f47cdd905cf2801ee97f7b6306bc786139777
  	                    	+   name: protokube:1.9.2
  	                    	-   name: protokube:1.10.0-beta.1
  	                    	+   source: https://kubeupv2.s3.amazonaws.com/kops/1.9.2/images/protokube.tar.gz
  	                    	-   source: https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/images/protokube.tar.gz

  	                    	  __EOF_KUBE_ENV
  	                    	...


  LaunchConfiguration/master-us-east-1b.masters.k8s.example.com
  	UserData
  	                    	...
  	                    	  set -o pipefail

  	                    	+ NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/nodeup
  	                    	- NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/nodeup
  	                    	- NODEUP_HASH=cf090a0bcae814feca2893678e3379c89673b370
  	                    	-
  	                    	+ NODEUP_HASH=bdbcc902bd22995ac3c8b4a0636bcd93070849a0
  	                    	+
  	                    	+
  	                    	+
  	                    	- export AWS_REGION=us-east-1


  	                    	...
  	                    	  cloudConfig: null
  	                    	  docker:
  	                    	+   bridge: ""
  	                    	    insecureRegistry: artifactory.example.com:6555
  	                    	    ipMasq: false
  	                    	    ipTables: false
  	                    	+   logDriver: json-file
  	                    	-   logDriver: ""
  	                    	    logLevel: warn
  	                    	+   logOpt:
  	                    	+   - max-size=10m
  	                    	+   - max-file=5
  	                    	    storage: overlay,aufs
  	                    	    version: 17.03.2
  	                    	...
  	                    	      version: 2.2.1
  	                    	  kubeAPIServer:
  	                    	-   allowPrivileged: true
  	                    	-   anonymousAuth: false
  	                    	-   apiServerCount: 3
  	                    	-   authorizationMode: AlwaysAllow
  	                    	+   address: 127.0.0.1
  	                    	-   bindAddress: 0.0.0.0
  	                    	-   cloudProvider: aws
  	                    	+   admissionControl:
  	                    	-   enableAdmissionPlugins:
  	                    	    - Initializers
  	                    	    - NamespaceLifecycle
  	                    	...
  	                    	    - NodeRestriction
  	                    	    - ResourceQuota
  	                    	+   allowPrivileged: true
  	                    	+   anonymousAuth: false
  	                    	+   apiServerCount: 3
  	                    	+   authorizationMode: AlwaysAllow
  	                    	+   cloudProvider: aws
  	                    	    etcdQuorumRead: false
  	                    	    etcdServers:
  	                    	...
  	                    	    - /events#http://127.0.0.1:4002
  	                    	    image: k8s.gcr.io/kube-apiserver:v1.10.3
  	                    	-   insecureBindAddress: 127.0.0.1
  	                    	    insecurePort: 8080
  	                    	    kubeletPreferredAddressTypes:
  	                    	...
  	                    	  - 94f996d645e74634a4be67bbb5417f892774230b@https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
  	                    	  - d595d3ded6499a64e8dac02466e2f5f2ce257c9f@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-amd64-v0.6.0.tgz
  	                    	+ - 72fac6679084d1f929d0abbd8a9ff9337273504b@https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/utils.tar.gz
  	                    	- - 1029269ea06e790e1daa50932269cc9aa983c137@https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/utils.tar.gz
  	                    	  ClusterName: k8s.example.com
  	                    	  ConfigBase: s3://k8s-example-com-state-store/k8s.example.com
  	                    	...
  	                    	  - _aws
  	                    	  - _kubernetes_master
  	                    	+ - _networking_cni
  	                    	  channels:
  	                    	  - s3://k8s-example-com-state-store/k8s.example.com/addons/bootstrap-channel.yaml
  	                    	  protokubeImage:
  	                    	+   hash: 527db0b5fd4b635e6cb2ca22bfec813a048855a7
  	                    	-   hash: 638f47cdd905cf2801ee97f7b6306bc786139777
  	                    	+   name: protokube:1.9.2
  	                    	-   name: protokube:1.10.0-beta.1
  	                    	+   source: https://kubeupv2.s3.amazonaws.com/kops/1.9.2/images/protokube.tar.gz
  	                    	-   source: https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/images/protokube.tar.gz

  	                    	  __EOF_KUBE_ENV
  	                    	...


  LaunchConfiguration/master-us-east-1c.masters.k8s.example.com
  	UserData
  	                    	...
  	                    	  set -o pipefail

  	                    	+ NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/nodeup
  	                    	- NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/nodeup
  	                    	- NODEUP_HASH=cf090a0bcae814feca2893678e3379c89673b370
  	                    	-
  	                    	+ NODEUP_HASH=bdbcc902bd22995ac3c8b4a0636bcd93070849a0
  	                    	+
  	                    	+
  	                    	+
  	                    	- export AWS_REGION=us-east-1


  	                    	...
  	                    	  cloudConfig: null
  	                    	  docker:
  	                    	+   bridge: ""
  	                    	    insecureRegistry: artifactory.example.com:6555
  	                    	    ipMasq: false
  	                    	    ipTables: false
  	                    	+   logDriver: json-file
  	                    	-   logDriver: ""
  	                    	    logLevel: warn
  	                    	+   logOpt:
  	                    	+   - max-size=10m
  	                    	+   - max-file=5
  	                    	    storage: overlay,aufs
  	                    	    version: 17.03.2
  	                    	...
  	                    	      version: 2.2.1
  	                    	  kubeAPIServer:
  	                    	-   allowPrivileged: true
  	                    	-   anonymousAuth: false
  	                    	-   apiServerCount: 3
  	                    	-   authorizationMode: AlwaysAllow
  	                    	+   address: 127.0.0.1
  	                    	-   bindAddress: 0.0.0.0
  	                    	-   cloudProvider: aws
  	                    	+   admissionControl:
  	                    	-   enableAdmissionPlugins:
  	                    	    - Initializers
  	                    	    - NamespaceLifecycle
  	                    	...
  	                    	    - NodeRestriction
  	                    	    - ResourceQuota
  	                    	+   allowPrivileged: true
  	                    	+   anonymousAuth: false
  	                    	+   apiServerCount: 3
  	                    	+   authorizationMode: AlwaysAllow
  	                    	+   cloudProvider: aws
  	                    	    etcdQuorumRead: false
  	                    	    etcdServers:
  	                    	...
  	                    	    - /events#http://127.0.0.1:4002
  	                    	    image: k8s.gcr.io/kube-apiserver:v1.10.3
  	                    	-   insecureBindAddress: 127.0.0.1
  	                    	    insecurePort: 8080
  	                    	    kubeletPreferredAddressTypes:
  	                    	...
  	                    	  - 94f996d645e74634a4be67bbb5417f892774230b@https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
  	                    	  - d595d3ded6499a64e8dac02466e2f5f2ce257c9f@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-amd64-v0.6.0.tgz
  	                    	+ - 72fac6679084d1f929d0abbd8a9ff9337273504b@https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/utils.tar.gz
  	                    	- - 1029269ea06e790e1daa50932269cc9aa983c137@https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/utils.tar.gz
  	                    	  ClusterName: k8s.example.com
  	                    	  ConfigBase: s3://k8s-example-com-state-store/k8s.example.com
  	                    	...
  	                    	  - _aws
  	                    	  - _kubernetes_master
  	                    	+ - _networking_cni
  	                    	  channels:
  	                    	  - s3://k8s-example-com-state-store/k8s.example.com/addons/bootstrap-channel.yaml
  	                    	  protokubeImage:
  	                    	+   hash: 527db0b5fd4b635e6cb2ca22bfec813a048855a7
  	                    	-   hash: 638f47cdd905cf2801ee97f7b6306bc786139777
  	                    	+   name: protokube:1.9.2
  	                    	-   name: protokube:1.10.0-beta.1
  	                    	+   source: https://kubeupv2.s3.amazonaws.com/kops/1.9.2/images/protokube.tar.gz
  	                    	-   source: https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/images/protokube.tar.gz

  	                    	  __EOF_KUBE_ENV
  	                    	...


  LaunchConfiguration/nodes1.k8s.example.com
  	UserData
  	                    	...
  	                    	  set -o pipefail

  	                    	+ NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/nodeup
  	                    	- NODEUP_URL=https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/nodeup
  	                    	- NODEUP_HASH=cf090a0bcae814feca2893678e3379c89673b370
  	                    	-
  	                    	+ NODEUP_HASH=bdbcc902bd22995ac3c8b4a0636bcd93070849a0
  	                    	+
  	                    	+
  	                    	+
  	                    	- export AWS_REGION=us-east-1


  	                    	...
  	                    	  cloudConfig: null
  	                    	  docker:
  	                    	+   bridge: ""
  	                    	    insecureRegistry: artifactory.example.com:6555
  	                    	    ipMasq: false
  	                    	    ipTables: false
  	                    	+   logDriver: json-file
  	                    	-   logDriver: ""
  	                    	    logLevel: warn
  	                    	+   logOpt:
  	                    	+   - max-size=10m
  	                    	+   - max-file=5
  	                    	    storage: overlay,aufs
  	                    	    version: 17.03.2
  	                    	...
  	                    	  - 94f996d645e74634a4be67bbb5417f892774230b@https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
  	                    	  - d595d3ded6499a64e8dac02466e2f5f2ce257c9f@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-amd64-v0.6.0.tgz
  	                    	+ - 72fac6679084d1f929d0abbd8a9ff9337273504b@https://kubeupv2.s3.amazonaws.com/kops/1.9.2/linux/amd64/utils.tar.gz
  	                    	- - 1029269ea06e790e1daa50932269cc9aa983c137@https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/linux/amd64/utils.tar.gz
  	                    	  ClusterName: k8s.example.com
  	                    	  ConfigBase: s3://k8s-example-com-state-store/k8s.example.com
  	                    	...
  	                    	  - _automatic_upgrades
  	                    	  - _aws
  	                    	+ - _networking_cni
  	                    	  channels:
  	                    	  - s3://k8s-example-com-state-store/k8s.example.com/addons/bootstrap-channel.yaml
  	                    	  protokubeImage:
  	                    	+   hash: 527db0b5fd4b635e6cb2ca22bfec813a048855a7
  	                    	-   hash: 638f47cdd905cf2801ee97f7b6306bc786139777
  	                    	+   name: protokube:1.9.2
  	                    	-   name: protokube:1.10.0-beta.1
  	                    	+   source: https://kubeupv2.s3.amazonaws.com/kops/1.9.2/images/protokube.tar.gz
  	                    	-   source: https://kubeupv2.s3.amazonaws.com/kops/1.10.0-beta.1/images/protokube.tar.gz

  	                    	  __EOF_KUBE_ENV
  	                    	...


  ManagedFile/k8s.example.com-addons-bootstrap
  	Contents
  	                    	...
  	                    	      selector:
  	                    	        k8s-addon: dns-controller.addons.k8s.io
  	                    	+     version: 1.9.1
  	                    	-     version: 1.10.0-beta.1
  	                    	    - id: k8s-1.6
  	                    	      kubernetesVersion: '>=1.6.0'
  	                    	...
  	                    	      selector:
  	                    	        k8s-addon: dns-controller.addons.k8s.io
  	                    	+     version: 1.9.1
  	                    	-     version: 1.10.0-beta.1
  	                    	    - id: v1.7.0
  	                    	      kubernetesVersion: '>=1.7.0'
  	                    	...


  ManagedFile/k8s.example.com-addons-dns-controller.addons.k8s.io-k8s-1.6
  	Contents
  	                    	...
  	                    	      k8s-addon: dns-controller.addons.k8s.io
  	                    	      k8s-app: dns-controller
  	                    	+     version: v1.9.1
  	                    	-     version: v1.10.0-beta.1
  	                    	    name: dns-controller
  	                    	    namespace: kube-system
  	                    	...
  	                    	          k8s-addon: dns-controller.addons.k8s.io
  	                    	          k8s-app: dns-controller
  	                    	+         version: v1.9.1
  	                    	-         version: v1.10.0-beta.1
  	                    	      spec:
  	                    	        containers:
  	                    	...
  	                    	          - --zone=*/*
  	                    	          - -v=2
  	                    	+         image: kope/dns-controller:1.9.1
  	                    	-         image: kope/dns-controller:1.10.0-beta.1
  	                    	          name: dns-controller
  	                    	          resources:
  	                    	...


  ManagedFile/k8s.example.com-addons-dns-controller.addons.k8s.io-pre-k8s-1.6
  	Contents
  	                    	...
  	                    	      k8s-addon: dns-controller.addons.k8s.io
  	                    	      k8s-app: dns-controller
  	                    	+     version: v1.9.1
  	                    	-     version: v1.10.0-beta.1
  	                    	    name: dns-controller
  	                    	    namespace: kube-system
  	                    	...
  	                    	          k8s-addon: dns-controller.addons.k8s.io
  	                    	          k8s-app: dns-controller
  	                    	+         version: v1.9.1
  	                    	-         version: v1.10.0-beta.1
  	                    	      spec:
  	                    	        containers:
  	                    	...
  	                    	          - --zone=*/*
  	                    	          - -v=2
  	                    	+         image: kope/dns-controller:1.9.1
  	                    	-         image: kope/dns-controller:1.10.0-beta.1
  	                    	          name: dns-controller
  	                    	          resources:
  	                    	...


  ManagedFile/k8s.example.com-addons-kube-dns.addons.k8s.io-k8s-1.6
  	Contents
  	                    	- null
  	                    	-
  	                    	- ---
  	                    	-
  	                    	  apiVersion: extensions/v1beta1
  	                    	  kind: Deployment
  	                    	...
  	                    	      metadata:
  	                    	        annotations:
  	                    	-         prometheus.io/port: "10055"
  	                    	-         prometheus.io/scrape: "true"
  	                    	          scheduler.alpha.kubernetes.io/critical-pod: ""
  	                    	          scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly",
  	                    	...
  	                    	        containers:
  	                    	        - args:
  	                    	+         - --domain=cluster.local.
  	                    	-         - --config-dir=/kube-dns-config
  	                    	          - --dns-port=10053
  	                    	+         - --config-dir=/kube-dns-config
  	                    	-         - --domain=cluster.local.
  	                    	          - --v=2
  	                    	          env:
  	                    	...

```

**Comment by mikesplain** [comment]
@cdenneen Can you provide your cluster spec and instance groups in full for kops 1.9.0 (with parts redacted).  Most likely we'll need more details for this but we should certainly look into this before GA.  Thanks for the report!

/assign

**Comment by cdenneen** [comment]
@mikesplain 

Here is the configuration:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-10-27T17:33:47Z
  name: k8s.example.com
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Owner: Chris Denneen
    Service: Kubernetes
    Support Team: Cloud Services
  cloudProvider: aws
  configBase: s3://k8s-example-com-state-store/k8s.example.com
  dnsZone: example.com
  docker:
    insecureRegistry: artifactory.example.com:6555
    logDriver: ""
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    legacy: true
  kubernetesApiAccess:
  - 10.0.0.0/8
  kubernetesVersion: 1.10.3
  masterInternalName: api.internal.k8s.example.com
  masterPublicName: api.k8s.example.com
  networkCIDR: 10.11.0.0/16
  networkID: vpc-XXXXXXX
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.0.0.0/8
  subnets:
  - cidr: 10.11.31.0/24
    id: subnet-XXXXXXX
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.11.41.0/24
    id: subnet-XXXXXXX
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.11.51.0/24
    id: subnet-XXXXXXX
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.11.61.0/24
    id: subnet-XXXXXXX
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.11.71.0/24
    id: subnet-XXXXXXX
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.11.32.0/24
    id: subnet-XXXXXXX
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.11.42.0/24
    id: subnet-XXXXXXX
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.11.52.0/24
    id: subnet-XXXXXXX
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.11.62.0/24
    id: subnet-XXXXXXX
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 10.11.72.0/24
    id: subnet-XXXXXXX
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-27T17:33:47Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-us-east-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxPrice: "0.04"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-27T17:33:47Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-us-east-1b
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxPrice: "0.04"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-27T17:33:47Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-us-east-1c
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.large
  maxPrice: "0.04"
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-27T17:33:47Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m4.xlarge
  maxPrice: "0.10"
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
```

I ended up having to delete the s3 configurations for the cluster and recreate from old 1.8 backup I had exported, updated to 1.10 and then recreated with. I believe there was a known issue for calico not upgrading between 1.7 -> 1.8 or 1.8 -> 1.9 properly but it worked for me... think I used the versions just before and just after the affected issues. However during this upgrade the cni configs for calico not being created on workers leads me to believe there was something leftover in the s3 bucket causing the issue. I even created brand new instanceGroup and it still had same issue. Removing config and recreating worked. 

I've also noticed worth mentioning I changed my cluster from kubenet -> calico -> flannel -> canal -> calico over the course of testing 1.6, 1.7, 1.8, 1.9 and I believe back in 1.8 it never properly went back to calico (STATE_STORE must of still had calico configuration set so when switching back to calico it didn't see a config change). Guessing when changing CNI the configs don't get updated and old parts cleaned up properly and if you go back to a previously used CNI it causes some bad inconsistency state.
