### ISSUE TITLE
CNI plugin fails with kube-router when ipv6 is disabled

### ISSUE THREAD

**Issue by roffe** [kubernetes/kops#5558]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.9.1`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Start k8s cluster with kube-router as CNI and nodes with kernel param `ipvs6.disabled=1`

**5. What happened after the commands executed?**
The CNI plugins go into some fail mode where it fills up /var/lib/cni/network/kubernets with ip leases until it runs out of ip's and the kubelet starts alerting that it cannot alocate any ip in the range for the node. deployments etc will have their pods stuck in Container Creating and they would fail with a error setting up pod sandbox

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-10T08:48:37Z
  name: staging.redacted
spec:
  api:
    loadBalancer:
      idleTimeoutSeconds: 600
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://redacted-kops-state-staging/staging.redacted
  dnsZone: redacted
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Unit]
      Description=Download Heptio AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/heptio-authenticator-aws
      ExecStart=/bin/bash -c "/usr/local/bin/aws s3 \
       cp --recursive s3://redacted-kops-state-staging/staging.redacted/addons/authenticator \
       /srv/kubernetes/heptio-authenticator-aws/ && \
       /bin/chmod a+w /srv/kubernetes/heptio-authenticator-aws/kubeconfig.yaml"
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /srv/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
    featureGates:
      ExpandPersistentVolumes: "true"
    runtimeConfig:
      admissionregistration.k8s.io/v1alpha1: "true"
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
    horizontalPodAutoscalerUseRestClients: true
  kubelet:
    anonymousAuth: false
    enableCustomMetrics: true
    featureGates:
      ExpandPersistentVolumes: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.8
  masterInternalName: api.internal.staging.redacted
  masterPublicName: api.staging.redacted
  networkCIDR: 10.0.0.0/16
  networkID: redacted
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.0.8.0/24
  subnets:
  - cidr: 10.0.118.0/24
    id: subnet-redacted
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.0.117.0/24
    id: subnet-redacted
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.0.116.0/24
    id: subnet-redacted
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 10.0.115.0/24
    id: subnet-redacted
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.0.114.0/24
    id: subnet-redacted
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 10.0.113.0/24
    id: subnet-redacted
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-13T11:18:01Z
  labels:
    kops.k8s.io/cluster: staging.redacted
  name: highcpu
spec:
  image: ami-6117f08c
  machineType: c4.xlarge
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: highcpu
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - req=highcpu:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-10T08:48:37Z
  labels:
    kops.k8s.io/cluster: staging.redacted
  name: master-eu-west-1a
spec:
  image: ami-6117f08c
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-16T08:48:12Z
  labels:
    kops.k8s.io/cluster: staging.redacted
  name: morenodes
spec:
  image: ami-6117f08c
  machineType: m4.large
  maxSize: 3
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: morenodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-10T08:48:38Z
  labels:
    kops.k8s.io/cluster: staging.redacted
  name: nodes
spec:
  cloudLabels:
    kubernetes.io/cluster/staging.redacted: owned
    tag-key: k8s.io/role/node
  image: ami-6117f08c
  machineType: m4.xlarge
  maxSize: 8
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```
ami-6117f08c is my custom build kops ami from imagebuilder with grub kernel opt `ipvs6.disabled=1`

**9. Anything else do we need to know?**

Upgrading the CNI plugins to 0.7.1 with:
```
export CNI_VERSION_URL=https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
export CNI_ASSET_HASH_STRING=6ecc5c7dbb8e4296b0d0d017e5440618e19605b9aa3b146a2c29af492f299dc7
kops update cluster....
```
solves the problem.

I'm guessing the same problem would occur on any solution that depends on the default CNI plugins if ipv6 is disabled on the nodes
