### ISSUE TITLE
API ELB AdditionalSecurityGroup - Stuck Updates

### ISSUE THREAD

**Issue by joshphp** [kubernetes/kops#5574]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 
1.9.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.9.9

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- kops edit cluster
- Add to the spec 
```spec:
  api:
    loadBalancer:
      type: Public
      additionalSecurityGroups:
      - sg-xxxxxxxx
```
- `kops update cluster` shows pending SG changes
- `kops update cluster --yes`
- pending changes still exist and always show up with `kops update cluster`

**5. What happened after the commands executed?**
- The change did not take affect, so I removed that spec from the cluster config

**6. What did you expect to happen?**
- The SG to be added, but then when it did not, I did not expect it to be stuck trying to apply. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: STRIPPED
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": ["arn:aws:iam::STRIPPED:role/kube2iam/*"]
        }
      ]
  additionalSans:
  - STRIPPED
  api:
    loadBalancer:
      idleTimeoutSeconds: 1800
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://STRIPPED
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1e
      name: e
      volumeSize: 100
    name: main
    version: 3.2.18
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: a
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: c
      volumeSize: 100
    - encryptedVolume: true
      instanceGroup: master-us-east-1e
      name: e
      volumeSize: 100
    name: events
    version: 3.2.18
  hooks:
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authorizationRbacSuperUser: admin
    oidcClientID: STRIPPED
    oidcIssuerURL: STRIPPED
    oidcUsernameClaim: email
  kubernetesApiAccess:
  - 172.27.4.117/32
  - 172.27.0.43/32
  - 172.27.4.146/32
  - 172.27.4.101/32
  kubernetesVersion: 1.9.9
  masterInternalName: STRIPPED
  masterPublicName: STRIPPED
  networkCIDR: 10.129.0.0/16
  networkID: STRIPPED
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - STRIPPED
  subnets:
  - cidr: 10.129.0.0/24
    id: subnet-47d13069
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.129.16.0/24
    id: subnet-edda71a7
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.129.32.0/24
    id: subnet-809572dc
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.129.48.0/24
    id: subnet-adf606ca
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.129.64.0/24
    id: subnet-5c858663
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.129.4.0/24
    id: subnet-41c8296f
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.129.20.0/24
    id: subnet-fda902b7
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.129.36.0/24
    id: subnet-0b917657
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.129.52.0/24
    id: subnet-d4f808b3
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 10.129.68.0/24
    id: subnet-f59794ca
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
- Cloudtrail shows this alert constantly now:

`Requested configuration change for LoadBalancer \"LOADBALANCER\" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.`
