### ISSUE TITLE
Trying to turn off pod preemption but maintain priority in a kops provisioned k8s 1.11 cluster

### ISSUE THREAD

**Issue by byndcivilization** [kubernetes/kops#5576]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.9.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops update cluster --name [redacted] --state s3://[redacted] --yes
kubectl apply -f schedulertest.yaml
```
the  schedulertest.yaml looks like:
```
apiVersion: componentconfig/v1alpha1
kind: KubeSchedulerConfiguration
algorithmSource:
    provider: DefaultProvider
disablePreemption: true
```
This follows the kubernetes documentation for turning off preemption but leaving on priority in k8s 1.11. 

**5. What happened after the commands executed?**
Recieved the following error:
```
error: unable to recognize "schedulertest.yaml": no matches for kind "KubeSchedulerConfiguration" in version "componentconfig/v1alpha1"
```

**6. What did you expect to happen?**
the manifest should run and disable preemption

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: [redacted]
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://[redacted]
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: [redacted]
      name: a
    - encryptedVolume: true
      instanceGroup: [redacted]
      name: b
    - encryptedVolume: true
      instanceGroup: [redacted]
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: [redacted]
      name: a
    - encryptedVolume: true
      instanceGroup: [redacted]
      name: b
    - encryptedVolume: true
      instanceGroup: [redacted]
      name: c
    name: events
  hooks:
  - manifest: |
      [Unit]
      Description=pull images
      After=docker.service
      [Service]
      Environment="PULL_IMAGES=[redacted]"
      ExecStart=/bin/bash -c "for i in `echo $PULL_IMAGES`; do docker pull $i; done"
      [Install]
      WantedBy=multi-user.target
    name: pullimages.service
  - manifest: |
      [Unit]
      Description=Add SSH Pubkeys for user: %i
      After=network.target systemd-user-sessions.service network-online.target
      [Service]
      User=%i
      Environment=H=/home/%i
      Environment=K=authorized_keys
      Environment=URL=https://s3.amazonaws.com/[redacted]
      Type=oneshot
      ExecStart=/bin/mkdir -p ${H}/.ssh
      ExecStart=/usr/bin/wget ${URL} -q -O ${H}/.ssh/${K}
      ExecStart=/bin/chmod 0400 ${H}/.ssh/${K}
      [Install]
      WantedBy=multi-user.target
    name: ssh-pubkeys@admin.service
  - before:
    - kubelet.service
    manifest: |
      [Unit]
      Description=Download Heptio AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/heptio-authenticator-aws
      ExecStart=/usr/local/bin/aws s3 cp --recursive s3://[redacted] /srv/kubernetes/heptio-authenticator-aws/
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    legacy: true
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /srv/kubernetes/heptio-authenticator-aws/heptio-authenticator-aws.kubeconfig
    authorizationMode: RBAC
    runtimeConfig:
      batch/v2alpha1: "true"
      componentconfig/v1alpha1: "true"
      scheduling.k8s.io/v1alpha1: "true"
  kubelet:
    featureGates:
      DevicePlugins: "true"
      ExperimentalCriticalPodAnnotation: "true"
  kubernetesApiAccess:
  - [redacted]
  - [redacted]
  - [redacted]
  kubernetesVersion: v1.11.0
  masterInternalName: api.internal.[redacted]
  masterPublicName: api.[redacted]
  networkCIDR: [redacted]
  networkID: vpc-961154ee
  networking:
    canal: {}
  nonMasqueradeCIDR: [redacted]
  sshAccess:
  - [redacted]
  subnets:
  - cidr: [redacted]
    id: [redacted]
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: [redacted]
    id: [redacted]
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: [redacted]
    id: [redacted]
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: [redacted]
    id: [redacted]
    name: priv-us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: [redacted]
    id: [redacted]
    name: util-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: [redacted]
    id: [redacted]
    name: priv-us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: [redacted]
    id: [redacted]
    name: util-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: [redacted]
    id: [redacted]
    name: priv-us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: [redacted]
    id: [redacted]
    name: util-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:22Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: admin-nodes
spec:
  cloudLabels:
    InstanceType: t2.large
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    gpu: absent
    nodePool: admin
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:19Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: master-us-east-1a
spec:
  cloudLabels:
    InstanceType: t2.large
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    nodePool: master
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:20Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: master-us-east-1b
spec:
  cloudLabels:
    InstanceType: t2.large
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    nodePool: master
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1b
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:21Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: master-us-east-1c
spec:
  cloudLabels:
    InstanceType: t2.large
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    nodePool: master
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1c
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:27Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nat-nodes-application-gpu-medium
spec:
  cloudLabels:
    InstanceType: p2.xlarge
    IpAddress: nat
  hooks:
  - manifest: |
      [Unit]
      Description=Install nvidia docker
      [Service]
      Type=oneshot
      ExecStartPre=/bin/chmod 550 /home/admin/nvidia-docker-installation.sh
      ExecStart=/bin/bash -c /home/admin/nvidia-docker-installation.sh
      ExecStartPost=/bin/rm /home/admin/nvidia-docker-installation.sh
      [Install]
      WantedBy=nvidia-init.target
    name: nvidia-docker-install.service
  image: [redacted]/encrypted-root-k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-05-27
  machineType: p2.xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: present
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - priv-us-east-1a
  - priv-us-east-1b
  - priv-us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:26Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nat-nodes-application-large
spec:
  cloudLabels:
    InstanceType: m4.2xlarge
    IpAddress: nat
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: m4.2xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: absent
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - priv-us-east-1a
  - priv-us-east-1b
  - priv-us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:25Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nat-nodes-application-medium
spec:
  cloudLabels:
    InstanceType: m4.xlarge
    IpAddress: nat
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: m4.xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: absent
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - priv-us-east-1a
  - priv-us-east-1b
  - priv-us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:24Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nat-nodes-application-small
spec:
  cloudLabels:
    InstanceType: t2.large
    IpAddress: nat
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: absent
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - priv-us-east-1a
  - priv-us-east-1b
  - priv-us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:26Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nodes-application-gpu-medium
spec:
  cloudLabels:
    InstanceType: p2.xlarge
    IpAddress: random
  hooks:
  - manifest: |
      [Unit]
      Description=Install nvidia docker
      [Service]
      Type=oneshot
      ExecStartPre=/bin/chmod 550 /home/admin/nvidia-docker-installation.sh
      ExecStart=/bin/bash -c /home/admin/nvidia-docker-installation.sh
      ExecStartPost=/bin/rm /home/admin/nvidia-docker-installation.sh
      [Install]
      WantedBy=nvidia-init.target
    name: nvidia-docker-install.service
  image: [redacted]/encrypted-root-k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-05-27
  machineType: p2.xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: present
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:25Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nodes-application-large
spec:
  cloudLabels:
    InstanceType: m4.2xlarge
    IpAddress: random
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: m4.2xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: absent
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:24Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nodes-application-medium
spec:
  cloudLabels:
    InstanceType: m4.xlarge
    IpAddress: random
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: m4.xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: absent
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:23Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nodes-application-small
spec:
  cloudLabels:
    InstanceType: t2.large
    IpAddress: random
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 0
  minSize: 0
  nodeLabels:
    gpu: absent
    nodePool: application
  role: Node
  rootVolumeSize: 250
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  suspendProcesses:
  - AZRebalance
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-01T17:10:22Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: workflows-nodes-v2
spec:
  cloudLabels:
    InstanceType: t2.large
  image: [redacted]/encrypted-root-k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-17
  machineType: t2.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    gpu: absent
    nodePool: workflows-v2
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  suspendProcesses:
  - AZRebalance
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I suspect this might have something to do with the kops bootstrapping process for 1.9 not taking into account some new features in k8s 1.11. I may totally be wrong here. I cant seem to get the componentconfig api to turn on through kops. I also can seem to find a kube-scheduler config file anywhere in our kops state bucket so im assuming that gets set in bootstrapping.
