### ISSUE TITLE
externalTrafficPolicy: Local services are unreachable

### ISSUE THREAD

**Issue by jaredallard** [kubernetes/kops#5650]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.9.2 (git-cb54c6a52)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```go
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"archive", BuildDate:"2018-07-21T18:59:36Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?** aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?** 

Modified a service to `externalTrafficPolicy: Local`

**5. What happened after the commands executed?** All services became unreachable

**6. What did you expect to happen?** All nodes w/ a pod should've been healthy, while ones w/o a pod should've been not healthy

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-07T23:32:47Z
  name: <name>
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://<name>/<name>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authorizationRbacSuperUser: admin
    oidcClientID: [redacted]
    oidcIssuerURL: https://accounts.google.com
    oidcUsernameClaim: email
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.8
  masterInternalName: api.internal.<name>.k8s.local
  masterPublicName: api.<name>.k8s.local
  networkCIDR: 172.0.0.0/16
  networkID: vpc-<vpc>
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.0.48.64/26
    id: subnet-<id>
    name: uix-a
    type: Private
    zone: us-west-2a
  - cidr: 172.0.48.128/26
    id: subnet-<id>
    name: uix-b
    type: Private
    zone: us-west-2b
  - cidr: 172.0.104.0/23
    id: subnet-<id>
    name: tinder
    type: Private
    zone: us-west-2b
  - cidr: 172.0.52.0/22
    id: subnet-<id>
    name: eng-a
    type: Private
    zone: us-west-2a
  - cidr: 172.0.156.0/22
    id: subnet-<id>
    name: eng-b
    type: Private
    zone: us-west-2b
  - cidr: 172.0.128.0/20
    id: subnet-<id>
    name: apps-a
    type: Private
    zone: us-west-2a
  - cidr: 172.0.0.0/20
    id: subnet-<id>
    name: apps-b
    type: Private
    zone: us-west-2b
  - cidr: 172.0.100.0/24
    id: subnet-<id>
    name: infra-a
    type: Private
    zone: us-west-2a
  - cidr: 172.0.101.0/24
    id: subnet-<id>
    name: infra-b
    type: Private
    zone: us-west-2b
  - cidr: 172.0.56.0/21
    id: subnet-<id>
    name: fe-a
    type: Utility
    zone: us-west-2a
  - cidr: 172.0.24.0/21
    id: subnet-<id>
    name: fe-b
    type: Utility
    zone: us-west-2b
  - cidr: 172.0.100.0/24
    id: subnet-<id>
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.0.101.0/24
    id: subnet-<id>
    name: us-west-2b
    type: Private
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  updatePolicy: external
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.** n/a

**9. Anything else do we need to know?**

The problem appears to be caused by `kube-proxy` being invoked with the wrong, non-resolvable hostname-override:

```
     mkfifo /tmp/pipe; ... --conntrack-max-per-core=131072 --hostname-override=ip-172-0-129-238.ec2.internal ...
```

which should've, if I'm correct, been:

```
--hostname-override=ip-172-0-129-238.us-west-2.compute.internal
```

to match the node's resolvable, and current name, hostname: `ip-172-0-129-238.us-west-2.compute.internal`

**EDIT** The VPC we put kops into has two dhcp option sets.
