### ISSUE TITLE
`Unable to connect to the server: EOF ` when using a shared VPC and subnets

### ISSUE THREAD

**Issue by ilyasotkov** [kubernetes/kops#5667]
**kops version**: any (1.9 / 1.10)
**kubernetes version**: any (1.9 / 1.10)

I've noticed that it's not possible to use a shared VPC and subnet when they have the longer format of AWS IDs.

The cluster gets created just fine, but fails validation, because (from looking in the console) instances (masters / nodes) are not launched into any VPC.

<img width="296" alt="screen shot 2018-08-19 at 7 19 02" src="https://user-images.githubusercontent.com/16720268/44305469-45fab600-a380-11e8-9f29-8e20a7657fe0.png">

**How to reproduce:** Use this guide https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md. If your VPC / subnet has format `vpc-1234abc0` / `subnet-1234abc0`, it will work, but if it's `vpc-1234567890abcdef0` / `subnet-1234567890abcdef0`, instances get created without any network interface. 

Cluster validation (`kubectl get nodes`) will fail with:

```
unexpected error during validation: error listing nodes: Get https://api.<CLUSTER_NAME>/api/v1/nodes: EOF
```

This a ❗️MAJOR bug❗️ since all new VPC are assigned the longer format starting from July 2018.

**Comment by geojaz** [comment]
Thanks for this detailed report @ilyasotkov . 

I'll try to repro this now and see what's going on. I'm almost sure that I've built a cluster into a VPC with a new-style ID (but I'm not sure). For sake of completeness, would you plesae send over a copy of your cluster/instance specs (`kops get cluster -oyaml > cluster.yml; kops get ig nodes master-west-west2a > nodes.yml`) and could you turn on debug logging and attach those too. If you can't post something here, feel free to DM me on k8s slack.

**Comment by ilyasotkov** [comment]
Sure thing, here are the kops configs (cluster name, state store s3 bucket, and IDs changed)):

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: cluster.example.com
spec:
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubelet:
    enableCustomMetrics: true
  cloudProvider: aws
  kubernetesVersion: v1.9.9
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  configBase: s3://cluster-example-state-store/cluster.example.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  sshAccess:
  - 0.0.0.0/0
  masterPublicName: api.cluster.example.com
  networkCIDR: 172.20.0.0/16
  networkID: vpc-1234567890abcdef0
  subnets:
  - cidr: 172.20.32.0/19
    id: subnet-1234567890abcdef0
    egress: nat-1234567890abcdef0
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.20.0.0/22
    name: utility-eu-west-1c
    id: subnet-1234567890abcdef0
    type: Utility
    zone: eu-west-1c
  externalDns:
    watchIngress: true
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  topology:
    bastion:
      bastionPublicName: bastion.cluster.example.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1c
  labels:
    kops.k8s.io/cluster: cluster.example.com
spec:
  role: Master
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-05-27
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
  labels:
    kops.k8s.io/cluster: cluster.example.com
spec:
  role: Node
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-05-27
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  subnets:
  - eu-west-1c

```
Network spec (CloudFormation):

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template declares networking resources for a kops Kubernetes cluster.
  The main reason for not using kops to create these resources is described
  in this GitHub issue: https://github.com/kubernetes/kops/issues/3182

Parameters:
  Env:
    Type: String
    Description: The environment where the CloudFormation stack will be deployed

  ClusterName:
    Type: String
    Description: Name of your cluster, this value is used to tag subnets for kops

Resources:
  ClusterVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.20.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref ClusterVpc

  SubnetPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1c
      CidrBlock: 172.20.32.0/19
      VpcId: !Ref ClusterVpc
      Tags:
        - Key: !Sub kubernetes.io/cluster/${ClusterName}
          Value: shared
        - Key: kubernetes.io/role/elb
          Value: "1"
        - Key: SubnetType
          Value: Private

  RouteTablePrivate:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ClusterVpc

  RouteTablePrivateAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetPrivate

  SubnetUtility:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1c
      CidrBlock: 172.20.0.0/22
      VpcId: !Ref ClusterVpc
      Tags:
        - Key: !Sub kubernetes.io/cluster/${ClusterName}
          Value: shared
        - Key: kubernetes.io/role/elb
          Value: "1"
        - Key: SubnetType
          Value: Utility

  RouteTableUtility:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ClusterVpc

  RouteTableUtilityAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableUtility
      SubnetId: !Ref SubnetUtility

  NatGatewayEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEip.AllocationId
      SubnetId: !Ref SubnetPrivate

  RouteToNatGateway:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
      RouteTableId: !Ref RouteTablePrivate

  RouteToInternetGateway:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTableUtility
```
