### ISSUE TITLE
conntrack util not installed

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes/kops#5671]
kubernetes uses the `conntrack` binary to perform some UDP related cleanup operations like https://github.com/kubernetes/kubernetes/pull/59286 or https://github.com/kubernetes/kubernetes/pull/22573

It seems that kops is not explicitly installing the `conntrack` tool, causing those cleanup tasks to never be performed. 

Examples of others installing it 
https://github.com/kubernetes/kubernetes/pull/26839, https://github.com/kubernetes/kubernetes/pull/64640

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.10.0 (git-8b52ea6d1)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS / CoreOS nodes

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`conntrack`

**5. What happened after the commands executed?**

`conntrack: command not found`

**6. What did you expect to happen?**

`conntrack` to be installed

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-06-22T07:08:46Z
  labels:
    kops.k8s.io/cluster: xxx
  name: master-a
spec:
  image: coreos.com/CoreOS-stable-*-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
  role: Master
  subnets:
  - a
```
