### ISSUE TITLE
How to make my node loadbalance internal

### ISSUE THREAD

**Issue by dozer47528** [kubernetes/kops#5707]
I want to create a kubernetes cluster for internal using.

`kops create cluster --zones=us-west-2a --vpc=${VPC_ID} --topology=private --networking=calico`

But this load balancer is still internet-facing ( I don't known how to call it)

![image](https://user-images.githubusercontent.com/1676951/44664495-ff731e80-aa45-11e8-8706-75333d92b5b2.png)

So how to make this load balancer internal facing?

**Comment by rekcah78** [comment]
Hi,
in your cluster spec:

```
spec:
  api:
    loadBalancer:
      type: Public -> Internal
```
