### ISSUE TITLE
Ability to add Pod Annotations to K8s Control Pane Pods

### ISSUE THREAD

**Issue by salilgupta1** [kubernetes/kops#5710]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We would like to add some custom datadog annotations to our k8s Control Pane pods (etcd, k8sapiserver, etc ...) so our datadog agent can scrape the prometheus endpoints.

It would be really useful if we could pass pod annotations via our kops configuration. However, right now, we are looking at using a kops hook to edit the manifest files and add the necessary annotations.

**2. Feel free to provide a design supporting your feature request.**

**Comment by luanguimaraesla** [comment]
We would like this feature too.

**Comment by luanguimaraesla** [comment]
@salilgupta1 did you figure out any workaround to make datadog-agent to scrape kube-apiserver pods?

**Comment by MoShitrit** [comment]
+1 on that one please! I'm looking for etcd pods as well, for the same reason of allowing datadog-agent to autodiscover etcd instances using their annotations pattern:
```
    ad.datadoghq.com/etcd-container.check_names: '["etcd"]'
    ad.datadoghq.com/etcd-container.init_configs: '[{}]'
    ad.datadoghq.com/etcd-container.instances: '[{"url": "http://%%host%%:4001"}]'
```

**Comment by valouille** [comment]
I have the same need for kube-apiserver pods, also using Datadog-agent auto-discovery feature to monitor well our clusters.

**Comment by MoShitrit** [comment]
> I have the same need for kube-apiserver pods, also using Datadog-agent auto-discovery feature to monitor well our clusters.

@valouille I ended up getting a solution from Datadog support in form of deploying a "dummy" daemon set which has a selector to run only on the masters, and which contains the annotations for auto-discovery. It uses the host network, so this way the `%%host%%` resolves to the master IP address. It works good for us and allows us to monitor `etcd` as desired.
Here's what we're using:

```
# This daemonset is a workaround for datadog's inability to "autodiscover" static pods
# (pods created by kubelet rather than the kubernetes scheduler)
# This affects pods that Kops defines in /etc/kubernetes/manifests, including etcd
# See https://github.com/kubernetes/kubernetes/issues/61717
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: datadog-etcd-dummy
  labels:
    k8s-app: datadog-etcd-dummy
spec:
  selector:
    matchLabels:
      k8s-app: datadog-etcd-dummy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/dummy.check_names: '["etcd"]'
        ad.datadoghq.com/dummy.init_configs: '[{}]'
        ad.datadoghq.com/dummy.instances: '[{"url": "http://%%host%%:4001"}]'
      labels:
        k8s-app: datadog-etcd-dummy
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: dummy
          image: gcr.io/google_containers/etcd:2.2.1
          command: ["/bin/sh"]
          args:
            - -c
            - while :; do sleep 2073600; done
          resources:
            requests:
              memory: 20Mi
              cpu: 10m
            limits:
              memory: 20Mi
              cpu: 100m
```

Hope this helps!
