### ISSUE TITLE
DNS resolution does not work on freshly build k8s.local cluster with predefined VPC and subnets

### ISSUE THREAD

**Issue by eugene-marchenko** [kubernetes/kops#5718]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
$ kops version
Version 1.10.0 (git-8b52ea6d1)
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
- `$ kops create cluster --node-count=4 --node-size=c4.xlarge --zones=us-east-1a,us-east-1b,us-east-1c,us-east-1d --subnets=subnet-2xxxxx6f,subnet-8xxxxxd7,subnet-81xxxxe6,subnet-9xxxxxb8 --vpc=vpc-exxxxxx2 --ssh-access=xxx.x.xxx.xx/23,x.x.x.x/32,10.129.0.0/20 --name=${KOPS_CLUSTER_NAME} --master-size=c4.large --ssh-public-key .ssh/xxxxx-kops-xxx.pub --image=coreos.com/CoreOS-stable-1800.7.0-hvm --node-volume-size=20 --admin-access=xx.xxx.x.0/23,xx.xxx.xx.xx/32,10.xxx.0.0/20 --node-security-groups=sg-6e0xxx18,sg-720xxxx4,sg-748xxx02`
- added section   
```
  hooks:
  - name: fix-dns.service
    roles:
    - Node
    - Master
    before:
    - network-pre.target
    - kubelet.service
    manifest: |
      Type=oneshot
      ExecStart=/usr/sbin/modprobe br_netfilter
      [Unit]
      Wants=network-pre.target
      [Install]
      WantedBy=multi-user.target
```
to cluster config like mentioned [here](https://github.com/kubernetes/kops/issues/4391#issuecomment-364321275)
- `$ update cluster --name=xxxxxx-kops-cluster-xxxxxx.k8s.local --yes`

**5. What happened after the commands executed?**
- Cluster successfully started but DNS from inside the pods does not resolve any names. No matter internal kubernetes services names or external like google.com
- I can successfully access them by IP address like 8.8.8.8
- DNS resolution works fine from cluster nodes

**6. What did you expect to happen?**
`nslookup google.com` executed successfully

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-08-29T21:23:40Z
  name: xxxxxx-kops-cluster-xxxxxx.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    disableSecurityGroupIngress: true
  cloudProvider: aws
  configBase: s3://xxxxxx-kops-cluster-xxxxxx/xxxxxx-kops-cluster-xxxxxx.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  hooks:
  - before:
    - network-pre.target
    - kubelet.service
    manifest: |
      Type=oneshot
      ExecStart=/usr/sbin/modprobe br_netfilter
      [Unit]
      Wants=network-pre.target
      [Install]
      WantedBy=multi-user.target
    name: fix-dns.service
    roles:
    - Node
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - x.x.x.x/23
  - x.x.x.x/32
  - 10.129.0.0/20
  kubernetesVersion: 1.10.3
  masterInternalName: api.internal.xxxxxx-kops-cluster-xxxxxx.k8s.local
  masterPublicName: api.xxxxxx-kops-cluster-xxxxxx.k8s.local
  networkCIDR: 10.129.0.0/20
  networkID: vpc-exxxxxx2
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - x.x.x.x/23
  - x.x.x.x/32
  - 10.129.0.0/20
  subnets:
  - cidr: 10.129.1.0/25
    id: subnet-2xxxxxxf
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 10.129.1.128/25
    id: subnet-8xxxxxx7
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.129.4.128/25
    id: subnet-8xxxxxx6
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 10.129.6.0/25
    id: subnet-9xxxxxx8
    name: us-east-1d
    type: Public
    zone: us-east-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
There are no errors or restarts on kube-dns pods from kube-system namespace
I found that if I run cluster without predefined subnets/VPC/security_groups, DNS started working fine.

Do you have any suggestions?
