### ISSUE TITLE
kops (rolling?) update does not manage kubeDNS cluster modifications

### ISSUE THREAD

**Issue by mrballcb** [kubernetes/kops#5728]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

> kops 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

> kubernetes 1.9.10

**3. What cloud provider are you using?**

> AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

> kops edit cluster --name foo
> kops update cluster --name foo --create-kube-config=false
> kops update cluster --name foo --create-kube-config=false --yes
> kops rolling-update cluster --name foo

**5. What happened after the commands executed?**

In step 1 we added the following segment to the cluster spec:
```
  kubeDNS:
    upstreamNameservers:
    - 10.1.1.2
    - 10.2.1.2
```
In step 2 it showed it would make the change:
```
Will modify resources:
  ManagedFile/gold.k8s.pgi-tools.com-addons-kube-dns.addons.k8s.io-k8s-1.6
  	Contents
  	                    	...
  	                    	  ---

  	                    	+ apiVersion: v1
  	                    	+ data:
  	                    	+   upstreamNameservers: |
  	                    	+     ["10.1.1.2","10.2.1.2"]
  	                    	+ kind: ConfigMap
  	                    	+ metadata:
  	                    	+   name: kube-dns
  	                    	+   namespace: kube-system
  	                    	+
  	                    	+ ---
  	                    	+
  	                    	  apiVersion: extensions/v1beta1
  	                    	  kind: Deployment
  	                    	...
```
In step 3 it said it changed everything.
In step 4 it said there was nothing to rolling update

**6. What did you expect to happen?**

> I expected the update command to trigger a change of some sort that would make rolling-update do something to update the kube-dns configmap.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-06-22T17:47:23Z
  name: foo
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudLabels:
    Team: SaaS Operations
  cloudProvider: aws
  configBase: s3://BUCKET/foo
  dnsZone: OBFUSCATED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    - instanceGroup: master-us-east-1e
      name: e
    name: events
  hooks:
  - before:
    - update-engine.service
    manifest: |
      Type=oneshot
      ExecStartPre=/usr/bin/systemctl mask --now update-engine.service
      ExecStartPre=/usr/bin/systemctl mask --now locksmithd.service
      ExecStart=/usr/bin/systemctl reset-failed update-engine.service
    name: disable-automatic-updates.service
  iam:
    legacy: true
  kubeDNS:
    upstreamNameservers:
    - 10.1.1.2
    - 10.2.1.2
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.10
  masterInternalName: api.internal.foo
  masterPublicName: api.foo
  networkCIDR: 10.100.0.0/16
  networkID: vpc-1310dd6a
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.100.0.0/24
    id: subnet-7e2ff752
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.100.1.0/24
    id: subnet-1bcf5853
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.100.2.0/24
    id: subnet-65547259
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.100.10.0/24
    id: subnet-c62ef6ea
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.100.11.0/24
    id: subnet-3ac35472
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 10.100.12.0/24
    id: subnet-4f507673
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    bastion:
      bastionPublicName: bastion.foo
    dns:
      type: Private
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/mrballcb/737e5a76fd863c4d1a65fbd1e950d5ba

**9. Anything else do we need to know?**

We know for sure that when deleting a pod, a new pod starting does not trigger any process to sync that configmap.  We know for sure that when terminating a master, the new master starting does not trigger that process either.

Unsure how much to value this since coredns will be replacing kube-dns shortly.
