### ISSUE TITLE
Taint not working with instance group and Cilium

### ISSUE THREAD

**Issue by DerekHeldtWerle** [kubernetes/kops#5730]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
❯ kops version
Version 1.10.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`1.10.5`
**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster --name=test.k8s.local --vpc=<vpc> --node-count=3 --ssh-public-key=key.pub --master-size=m4.large --node-size=m4.xlarge --zones=us-east-1a,us-east-1b,us-east-1c --topology private --networking cilium --dns private --override 'cluster.spec.etcdClusters[*].version=3.1.11' --kubernetes-version=1.10.5 --dns-zone=test.test --api-loadbalancer-type internal --master-volume-size 200 --node-volume-size 300 --encrypt-etcd-storage=true
```
**5. What happened after the commands executed?**
I created an instance group with a custom taint and cilium fails to be properly scheduled onto any nodes in the custom instance group.

**6. What did you expect to happen?**
I would expect the instance group with a custom taint to have a cilium pod scheduled on it.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
Instance group in question:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-07-26T21:16:44Z
  labels:
    kops.k8s.io/cluster: test.k8s.local
  name: new-service
spec:
  image: ami-xxxxx
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: new-service
  taints:
    - cluster=new-service:NoSchedule
  role: Node
  rootVolumeSize: 
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Logs from the instance with the custom taint:
```
Aug 30 21:38:31 ip-xxxxx.xxx.xxx.xxx kubelet[1329]: W0830 21:38:31.026798    1329 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d/
```
**9. Anything else do we need to know?**
I've managed to get around this by updating the daemonset after deployment to include a specific tolerations matching the taint described above, but a seemless deployment would be preferred if possible:

```
      - effect: NoSchedule
        key: cluster
        value: new-service
```
