### ISSUE TITLE
Can't launch new cluster with 1.10.0

### ISSUE THREAD

**Issue by kellycampbell** [kubernetes/kops#5733]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0 (git-91e3503f3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.3 (have also tried 1.10.5, 1.10.7)

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
 kops create cluster --name test-k8s-1.10.v2.domain.net --cloud aws --networking calico --network-cidr 172.21.0.0/16 --state s3://<state store> --node-count 1 --master-count 1 --zones us-east-2a --master-zones us-east-2a --dns-zone domain.net --node-size t2.large --master-size t2.large --ssh-public-key secure/ssh-k8s-v2.pub --admin-access X.X.X.X/32,Y.Y.Y.Y/32 --ssh-access X.X.X.X/32,Y.Y.Y.Y/32

kops update cluster test-k8s-1.10.v2.domain.net --yes
```

**5. What happened after the commands executed?**

Typical startup output, but the master node never completes launching.

Here's what `docker ps` shows on the master node:
```
root@ip-172-21-38-43:/var/log# docker ps
CONTAINER ID        IMAGE                                                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
827969a3c705        k8s.gcr.io/kube-proxy@sha256:568df575bb2e630abfd4a4754a23a8af7b13c3f4a526796af01021eda3ff7a30   "/bin/sh -c 'mkfif..."   5 minutes ago       Up 5 minutes                            k8s_kube-proxy_kube-proxy-ip-172-21-38-43.us-east-2.compute.internal_kube-system_24da070ff3d5e92dfbcfd43cc471b6cc_0
77a932acacbf        k8s.gcr.io/pause-amd64:3.0                                                                      "/pause"                 6 minutes ago       Up 6 minutes                            k8s_POD_kube-proxy-ip-172-21-38-43.us-east-2.compute.internal_kube-system_24da070ff3d5e92dfbcfd43cc471b6cc_0
root@ip-172-21-38-43:/var/log# docker ps
CONTAINER ID        IMAGE                                                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
827969a3c705        k8s.gcr.io/kube-proxy@sha256:568df575bb2e630abfd4a4754a23a8af7b13c3f4a526796af01021eda3ff7a30   "/bin/sh -c 'mkfif..."   11 minutes ago      Up 11 minutes                           k8s_kube-proxy_kube-proxy-ip-172-21-38-43.us-east-2.compute.internal_kube-system_24da070ff3d5e92dfbcfd43cc471b6cc_0
77a932acacbf        k8s.gcr.io/pause-amd64:3.0                                                                      "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_kube-proxy-ip-172-21-38-43.us-east-2.compute.internal_kube-system_24da070ff3d5e92dfbcfd43cc471b6cc_0
```

**6. What did you expect to happen?**

Expected master to complete startup and run api server.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-08-30T22:59:17Z
  name: test-k8s-1.10.v2.domain.net
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://STATE_STORE/test-k8s-1.10.v2.domain.net
  dnsZone: domain.net
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - X.X.X.X/32
  - Y.Y.Y.Y/32
  kubernetesVersion: 1.10.3
  masterPublicName: api.test-k8s-1.10.v2.domain.net
  networkCIDR: 172.21.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - X.X.X.X/32
  - Y.Y.Y.Y/32
  subnets:
  - cidr: 172.21.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-30T22:59:18Z
  labels:
    kops.k8s.io/cluster: test-k8s-1.10.v2.domain.net
  name: master-us-east-2a
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  subnets:
  - us-east-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-30T22:59:18Z
  labels:
    kops.k8s.io/cluster: test-k8s-1.10.v2.domain.net
  name: nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/kellycampbell/43f6bd664f9e2ba1d218296b2d9c5474

**9. Anything else do we need to know?**
