### ISSUE TITLE
empty "/etc/hosts" file when using gossip

### ISSUE THREAD

**Issue by joway** [kubernetes/kops#5743]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.9.1 (git-ba77c9ca2)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```json
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
- cat /etc/hosts
```
**5. What happened after the commands executed?**

```
admin@ip-172-31-79-233:~$ cat /etc/hosts
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
127.0.1.1 ip-172-31-79-233.cn-north-1.compute.internal ip-172-31-79-233
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

# Begin host entries managed by kops - do not edit
# End host entries managed by kops
```

**6. What did you expect to happen?**

```
admin@ip-172-31-74-11:~$ cat /etc/hosts
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
127.0.1.1 ip-172-31-74-11.cn-north-1.compute.internal ip-172-31-74-11
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

# Begin host entries managed by kops - do not edit
172.31.xxx.xxx	api.internal.kops-v1.k8s.local etcd-3.internal.kops-v1.k8s.local etcd-events-3.internal.kops-v1.k8s.local
172.31.xxx.xxx	api.internal.kops-v1.k8s.local etcd-1.internal.kops-v1.k8s.local etcd-events-1.internal.kops-v1.k8s.local
172.31.xxx.xxx	api.internal.kops-v1.k8s.local etcd-2.internal.kops-v1.k8s.local etcd-events-2.internal.kops-v1.k8s.local
# End host entries managed by kops
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-03T08:36:49Z
  name: kops-v1.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-store/kops-v1.k8s.local
  docker:
    logDriver: ""
    registryMirrors:
    - https://xxx.mirror.aliyuncs.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-cn-north-1b-1
      name: "1"
    - instanceGroup: master-cn-north-1b-2
      name: "2"
    - instanceGroup: master-cn-north-1b-3
      name: "3"
    name: main
  - etcdMembers:
    - instanceGroup: master-cn-north-1b-1
      name: "1"
    - instanceGroup: master-cn-north-1b-2
      name: "2"
    - instanceGroup: master-cn-north-1b-3
      name: "3"
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
  kubeProxy:
    enabled: true
    proxyMode: iptables
  kubelet:
    imageGCHighThresholdPercent: 70
    imageGCLowThresholdPercent: 50
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: https://s3.cn-north-1.amazonaws.com.cn/kops-asset/kubernetes/release/v1.9.3
  masterInternalName: api.internal.kops-v1.k8s.local
  masterKubelet:
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  masterPublicName: api.kops-v1.k8s.local
  networkCIDR: 172.31.0.0/16
  networkID: vpc-xxx
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 172.31.0.0/16
  subnets:
  - cidr: 172.31.xxx.0/20
    id: subnet-xxx
    name: cn-north-1b
    type: Public
    zone: cn-north-1b
  - cidr: 172.31.xxx.0/22
    id: subnet-xxx
    name: utility-cn-north-1b
    type: Utility
    zone: cn-north-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
