### ISSUE TITLE
Issue using locally built `kops`

### ISSUE THREAD

**Issue by amitsaha** [kubernetes/kops#5761]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Kops built from `release` branch.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Not relevant

**3. What cloud provider are you using?**

AWS and using `--networking amazon-vpc-routed-eni`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

- Clone repository
- Use official `golang` docker image to volume mount the repo
- `make kops`

Create cluster:

```
.build/local/kops create cluster --state s3://state-bucket --master-size t2.medium --node-size t2.medium --node-count 1 --zones ap-southeast-2a,ap-southeast-2b,ap-southeast-2c --networking amazon-vpc-routed-eni --name rsaus-non-production.k8s.local --topology private --subnets subnet-015ef7388cf9feb5c,subnet-006f6310e7dceee87,subnet-072a94601e3dd1ac4 --utility-subnets subnet-015ef7388cf9feb5c,subnet-006f6310e7dceee87,subnet-072a94601e3dd1ac4 --out ./kubernetes/ --vpc vpc-07bda143da5cad1fc --api-loadbalancer-type internal --target terraform
```

**5. What happened after the commands executed?**

On the master, logs in `/var/log/syslog` complain about an empty `/etc/cni/net.d`. Looking around I see that, the `addons/networking.amazon-vpc-routed-eni/k8s-1.7.yml` file is only being partially uploaded:

```
# Vendored from https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.0/config/v1.0/aws-k8s-cni.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: aws-node
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  verbs: ["list", "watch", "get"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  verbs: ["list", "watch"]

```

**6. What did you expect to happen?**

The master/nodes should be provisioned correctly as with a release binary of `kops`.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.

Build logs:

```
root@f2ecc321c1f2:/go/src/k8s.io/kops# make kops
mkdir -p /go/src/k8s.io/kops/.build/local
go build  -ldflags=all="" -o /go/src/k8s.io/kops/.build/local/go-bindata k8s.io/kops/vendor/github.com/jteeuwen/go-bindata/go-bindata
cd /go/src/k8s.io/kops; /go/src/k8s.io/kops/.build/local/go-bindata -o upup/models/bindata.go -pkg models -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix upup/models/ upup/models/...
go build  -ldflags=all="-X k8s.io/kops.Version=1.10.0 -X k8s.io/kops.GitVersion=8b52ea6d1 " -o /go/src/k8s.io/kops/.build/local/kops k8s.io/kops/cmd/kops/
```

**9. Anything else do we need to know?**

Not sure
