### ISSUE TITLE
Internal ELB (AWS) rediness failure

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#5825]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Running an HELM chart of prometheus
```
# Prometheus
prometheus:
  externalLabels:
    environment: "prod"
  image:
    tag: v2.4.0
  nodeSelector:
    role: monitor
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "monitor"
    effect: "NoSchedule"
  retention: 336h
  service:
     annotations:
       service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
       service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
       service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
       service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
     loadBalancerSourceRanges:
     - 172.20.0.0/16
     type: LoadBalancer
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 128Gi
  additionalScrapeConfigs:
  - job_name: "prometheus"
    static_configs:
    - targets:
      - "localhost:9090"
```

**5. What happened after the commands executed?**
object has been created but rediness probe fails, unable to connect to the pod.
I've checked `SG` and connectivity to `NodePort` everything works.

**6. What did you expect to happen?**
I have tested it in 3 different env. For the first two it works, for the third env (which has ~200) servers it was failing

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: prod.cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://coralogix-k8s-state/prod.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.10.5
  masterPublicName: api.prod.cluster.k8s.local
  networkCIDR: 172.30.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 101.64.0.0/10
  sshAccess:
  - 172.20.0.0/16
  subnets:
  - cidr: 172.30.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.30.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.30.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.30.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.30.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.30.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:16Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: categorization
spec:
  cloudLabels:
    Env: prod
    Role: categorization
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: categorization
    role: categorization
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=categorization:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:18Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: categorization-old
spec:
  cloudLabels:
    Env: prod
    Role: categorization-old
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 36
  minSize: 36
  nodeLabels:
    kops.k8s.io/instancegroup: categorization-old
    role: categorization-old
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=categorization-old:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:17Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: central
spec:
  cloudLabels:
    Env: prod
    Role: central
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.2xlarge
  maxSize: 12
  minSize: 12
  nodeLabels:
    kops.k8s.io/instancegroup: central
    role: nodes
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: couchbase
spec:
  cloudLabels:
    Env: prod
    Role: couchbase
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: r5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: couchbase
    role: couchbase
    service: couchbase
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=couchbase:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:27Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-002
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: m5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    cluster: "002"
    kops.k8s.io/instancegroup: es-cluster-002
    role: es-cluster
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=es-cluster-002:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:24Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-client-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: m5.xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-client-001
    role: es-cluster-client
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=es-cluster-client-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:24Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-cold-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: r5.xlarge
  maxSize: 21
  minSize: 21
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-cold-001
    role: es-cluster-cold
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=es-cluster-cold-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:23Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-hot-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: r5.2xlarge
  maxSize: 39
  minSize: 39
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-hot-001
    role: es-cluster-hot
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=es-cluster-hot-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:26Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-master-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: m5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-master-001
    role: es-cluster-master
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=es-cluster-master-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:15Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: ingress
spec:
  cloudLabels:
    Env: prod
    Role: ingress
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.2xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: ingress
    role: ingress
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=ingress:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:20Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: kafka
spec:
  cloudLabels:
    Env: prod
    Role: kafka
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.2xlarge
  maxSize: 9
  minSize: 9
  nodeLabels:
    kops.k8s.io/instancegroup: kafka
    role: kafka
    service: kafka
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=kafka:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:19Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: logsingest
spec:
  cloudLabels:
    Env: prod
    Role: logsingest
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.xlarge
  maxSize: 21
  minSize: 21
  nodeLabels:
    kops.k8s.io/instancegroup: logsingest
    role: logsingest
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=logsingest:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:12Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1a
spec:
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:13Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1b
spec:
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:13Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1c
spec:
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:14Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: monitor
spec:
  cloudLabels:
    Env: prod
    Role: monitor
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: monitor
    role: monitor
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1b
  taints:
  - role=monitor:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-09-23T07:05:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: zookeeper
spec:
  cloudLabels:
    Env: prod
    Role: zookeeper
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: zookeeper
    role: zookeeper
    service: zookeeper
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  taints:
  - role=zookeeper:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
