### ISSUE TITLE
API DNS never created using amazonvpc networking

### ISSUE THREAD

**Issue by jaymell** [kubernetes/kops#5895]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
``` kops create -f cluster.yaml ```

**5. What happened after the commands executed?**
Cluster is created, but API endpoint is never reachable.

**6. What did you expect to happen?**
I expect to be able to reach the public API endpoint after cluster is created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-08-27T19:50:24Z
  name: [redacted]
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: [redacted]
  etcdClusters:
  - etcdMembers:
    - instanceGroup: [redacted]
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: [redacted]
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess: [redacted]
  kubernetesVersion: 1.10.3
  masterInternalName: [redacted]
  masterPublicName: [redacted]
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess: [redacted]
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-27T19:50:30Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m4.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-27T19:50:30Z
  labels:
    kops.k8s.io/cluster: [redacted]
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Can provide this later if needed.

**9. Anything else do we need to know?**

It appears as though the issue I'm seeing is related entirely to the `amazonvpc` network plugin. I've created several clusters that are identical with the exception of this parameter. When I create the cluster using `kubenet`, everything works as expected -- the public DNS record is properly created by `dns-controller`. However, when I modify (or re-create from scratch) the cluster using `amazonvpc`, the 203.0.113.123 placeholder IP is never replaced for the public API DNS record.

If I inspect the nodes, I see that for kubenet, the Addresses field for the master nodes is properly populated, e.g.,:
```
Addresses:
  InternalIP:   172.20.37.140
  ExternalIP:   [public ip]
  InternalDNS:  ip-172-20-37-140.<region>.compute.internal
  ExternalDNS:  ec2-< ... >.<region>.compute.amazonaws.com
  Hostname:     ip-172-20-37-140.<region>.compute.internal
```

However, for amazonvpc, the master node description is missing ExternalIP and ExternalDNS, so I'm guessing this is why the records are never created.
