### ISSUE TITLE
r4 instances not using all space from the root volume

### ISSUE THREAD

**Issue by muenchdo** [kubernetes/kops#5933]
**1. What `kops` version are you running?**
1.9.1

**2. What Kubernetes version are you running?**
v1.9.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Create instance group: `kops create -ig supercompute`

Modify template:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: eu-1.k8s.local
  name: supercompute
spec:
  additionalUserData:
  - content: |
      #cloud-config
      runcmd:
       - dd if=/dev/zero of=/swapfile1 bs=65536 count=3814697
       - chown root:root /swapfile1
       - chmod 0600 /swapfile1
       - mkswap /swapfile1
       - swapon /swapfile1
    name: swap.txt
    type: text/cloud-config
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  kubelet:
    failSwapOn: false
  machineType: r4.16xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: supercompute
    type: supercompute
  role: Node
  rootVolumeSize: 2500
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```

Update cluster: `kops update cluster --yes`

**5. What happened after the commands executed?**
The instance group was created as expected, but the instances started running out of space very quickly so I checked the disk with:
```
admin@ip-0-0-0-0:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            97G  1.8M   97G   1% /run
/dev/xvda1      424G  278G  129G  69% /
tmpfs           241G     0  241G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           241G     0  241G   0% /sys/fs/cgroup
```
and
```
admin@ip-0-0-0-0:~$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0  2.5T  0 disk
└─xvda1 202:1    0  452G  0 part /
```
**6. What did you expect to happen?**
The instance to use all space available on the root volume.

**7. Anything else do we need to know?**
Instance type is r4, so I don't think it is related to #5175
