### ISSUE TITLE
etcd-server-events memory leak?

### ISSUE THREAD

**Issue by Jarch09** [kubernetes/kops#5941]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.10.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`v1.12.0`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster (private topology) on AWS

**5. What happened after the commands executed?**
I have a 5 node HA cluster (3 masters, 2 nodes); the cluster has been performing well, but both the memory usage and working set for `etcd-server-events` pods have been increasing linearly since the cluster was created, which is worrisome.

All the other pods seem stable.

**6. What did you expect to happen?**
I did not expect memory use to grow unbounded. I'm new to kube so probably missing a lot, but why isn't kops putting a memory usage limit on the `etcd-server-events` pods? What should standard behavior for these pods look like?

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.10.3
  masterPublicName: cluster-name
  networkCIDR: CIDR
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: CIDR
  subnets:
  - cidr: CIDR
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: CIDR
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: CIDR
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: CIDR
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: CIDR
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: CIDR
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: date
  labels:
    kops.k8s.io/cluster: some-cluster
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  rootVolumeSize: 64
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: date
  labels:
    kops.k8s.io/cluster: some-cluster
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  rootVolumeSize: 64
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: date
  labels:
    kops.k8s.io/cluster: some-cluster
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  rootVolumeSize: 64
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: date
  labels:
    kops.k8s.io/cluster: some-cluster
  name: nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 64
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
In the past week memory use by one of the `etcd-server-events` pods has approximately doubled (from ~370MiB to ~760MiB). This is on par for the other two as well.
