### ISSUE TITLE
Master send RevokeSecurityGroup for NLB traffic port when it should not be revoked

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#5952]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I've checked it via `cloudtrail` and saw that the master revokes the NLB traffic port from the security group
**5. What happened after the commands executed?**

**6. What did you expect to happen?**
It shouldn't happen
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: prod.cluster.k8s.local
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["cloudwatch:ListMetrics","cloudwatch:GetMetricStatistics"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://coralogix-k8s-state/prod.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.10.5
  masterPublicName: api.prod.cluster.k8s.local
  networkCIDR: 172.30.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 101.64.0.0/10
  sshAccess:
  - 172.20.0.0/16
  subnets:
  - cidr: 172.30.32.0/19
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.30.64.0/19
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.30.96.0/19
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.30.0.0/22
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.30.4.0/22
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.30.8.0/22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:34Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: anomaly
spec:
  cloudLabels:
    Env: prod
    Role: anomaly
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: anomaly
    role: anomaly
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=anomaly:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:36Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: archiving
spec:
  cloudLabels:
    Env: prod
    Role: archiving
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.2xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: archiving
    role: archiving
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=archiving:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:37Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: batchprocessing
spec:
  cloudLabels:
    Env: prod
    Role: batchprocessing
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: r5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: batchprocessing
    role: batchprocessing
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=batchprocessing:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:28Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: categorization
spec:
  cloudLabels:
    Env: prod
    Role: categorization
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: categorization
    role: categorization
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=categorization:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:30Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: categorization-old
spec:
  cloudLabels:
    Env: prod
    Role: categorization-old
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.xlarge
  maxSize: 45
  minSize: 45
  nodeLabels:
    kops.k8s.io/instancegroup: categorization-old
    role: categorization-old
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=categorization-old:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:30Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: central
spec:
  cloudLabels:
    Env: prod
    Role: central
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: central
    role: nodes
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:39Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: couchbase
spec:
  cloudLabels:
    Env: prod
    Role: couchbase
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: r5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: couchbase
    role: couchbase
    service: couchbase
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=couchbase:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:43Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-002
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: m5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    cluster: "002"
    kops.k8s.io/instancegroup: es-cluster-002
    role: es-cluster
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-002:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:41Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-client-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: m5.xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-client-001
    role: es-cluster-client
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-client-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:41Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-cold-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: r5.xlarge
  maxSize: 21
  minSize: 21
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-cold-001
    role: es-cluster-cold
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-cold-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:40Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-hot-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: r5.2xlarge
  maxSize: 43
  minSize: 43
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-hot-001
    role: es-cluster-hot
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-hot-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:42Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-master-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11
  machineType: m5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-master-001
    role: es-cluster-master
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-master-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:26Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: heroku
spec:
  cloudLabels:
    Env: prod
    Role: heroku
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.2xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: heroku
    role: heroku
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=heroku:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:27Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: ingress
spec:
  cloudLabels:
    Env: prod
    Role: ingress
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: ingress
    role: ingress
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  taints:
  - role=ingress:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:38Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: kafka
spec:
  cloudLabels:
    Env: prod
    Role: kafka
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.2xlarge
  maxSize: 9
  minSize: 9
  nodeLabels:
    kops.k8s.io/instancegroup: kafka
    role: kafka
    service: kafka
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=kafka:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:36Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: kafkadispatcher
spec:
  cloudLabels:
    Env: prod
    Role: kafkadispatcher
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.large
  maxSize: 9
  minSize: 9
  nodeLabels:
    kops.k8s.io/instancegroup: kafkadispatcher
    role: kafkadispatcher
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=kafkadispatcher:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:33Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: kibana
spec:
  cloudLabels:
    Env: prod
    Role: kibana
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: kibana
    role: kibana
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=kibana:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:32Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: livetail
spec:
  cloudLabels:
    Env: prod
    Role: livetail
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.2xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: livetail
    role: livetail
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=livetail:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:32Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: livetail-pub
spec:
  cloudLabels:
    Env: prod
    Role: livetail-pub
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: livetail-pub
    role: livetail-pub
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=livetail-pub:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:31Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: logsingest
spec:
  cloudLabels:
    Env: prod
    Role: logsingest
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 25
  minSize: 25
  nodeLabels:
    kops.k8s.io/instancegroup: logsingest
    role: logsingest
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=logsingest:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:28Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: logsparser
spec:
  cloudLabels:
    Env: prod
    Role: logsparser
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.2xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: logsparser
    role: logsparser
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=logsparser:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1a
spec:
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:23Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1b
spec:
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:24Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1c
spec:
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:25Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: monitor
spec:
  cloudLabels:
    Env: prod
    Role: monitor
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: monitor
    role: monitor
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=monitor:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:35Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: statsingest
spec:
  cloudLabels:
    Env: prod
    Role: statsingest
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: statsingest
    role: statsingest
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=statsingest:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:29Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: user-alerts
spec:
  cloudLabels:
    Env: prod
    Role: user-alerts
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: c5.xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: user-alerts
    role: user-alerts
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=user-alerts:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:25Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: webapi
spec:
  cloudLabels:
    Env: prod
    Role: webapi
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.xlarge
  maxSize: 9
  minSize: 9
  nodeLabels:
    kops.k8s.io/instancegroup: webapi
    role: webapi
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=webapi:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:37Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: ws
spec:
  cloudLabels:
    Env: prod
    Role: ws
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: ws
    role: ws
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=ws:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-13T13:20:38Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: zookeeper
spec:
  cloudLabels:
    Env: prod
    Role: zookeeper
  image: 595879546273/CoreOS-stable-1855.4.0-hvm
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: zookeeper
    role: zookeeper
    service: zookeeper
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=zookeeper:NoSchedule
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
