### ISSUE TITLE
calico-node running on master does not peer with the other nodes

### ISSUE THREAD

**Issue by valer-cara** [kubernetes/kops#5958]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.10.0 (git-8b52ea6d1)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I've upgraded two clusters from 1.9 to 1.10 and on both master -> overlay connection has been cut out due to calico-node booting with the wrong config. 

Is this the intended approach (having master/overlay isolation)? If so i guess calico-node shouldn't run on the master at all.

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

Have the master node peered into the mesh.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-16T15:13:18Z
  name: staging-v1.xxxxxxx
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-6re0ha/staging-v1.xxxxxxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1d
      name: d
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: staging-v1.xxxxxxx
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'oidc:'
    oidcIssuerURL: https://xxxxxxx
    oidcUsernameClaim: email
    oidcUsernamePrefix: 'oidc:'
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.6
  masterInternalName: api.internal.staging-v1.xxxxxxx
  masterPublicName: api.staging-v1.xxxxxxx
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 172.20.0.0/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  topology:
    bastion:
      bastionPublicName: bastion.staging-v1.xxxxxxx
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-16T15:13:19Z
  labels:
    kops.k8s.io/cluster: staging-v1.xxxxxxx
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-28T13:55:52Z
  labels:
    kops.k8s.io/cluster: staging-v1.xxxxxxx
  name: i3xl-nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: i3.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: i3xl-nodes
  role: Node
  subnets:
  - us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-16T15:13:18Z
  labels:
    kops.k8s.io/cluster: staging-v1.xxxxxxx
  name: master-us-east-1d
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180405
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1d
  role: Master
  subnets:
  - us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-16T15:13:18Z
  labels:
    kops.k8s.io/cluster: staging-v1.xxxxxxx
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180405
  machineType: m5.2xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1d

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Here's the output from `calicoctl node status` ran on master vs. node.

Confd renders different `/etc/calico/confd/config/bird.cfg` files on the two hosts, as seen in the status below.

```
Master node status:

IPv4 BGP status
+---------------+-------------------+-------+------------+--------------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |              INFO              |
+---------------+-------------------+-------+------------+--------------------------------+
| 172.20.36.20  | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.37.184 | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.39.224 | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.43.76  | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.46.20  | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.46.42  | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.48.165 | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.53.25  | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.56.167 | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.57.244 | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.59.111 | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.63.138 | node-to-node mesh | start | 2018-10-16 | Active Socket: Connection      |
|               |                   |       |            | reset by peer                  |
+---------------+-------------------+-------+------------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.


Worker node status:

Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+--------------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |              INFO              |
+---------------+-------------------+-------+------------+--------------------------------+
| 172.20.36.20  | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.39.224 | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.43.76  | node-to-node mesh | start | 2018-10-16 | Connect Socket: Host is        |
|               |                   |       |            | unreachable                    |
| 172.20.53.25  | node-to-node mesh | start | 2018-10-16 | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| 172.20.62.170 | node-to-node mesh | up    | 2018-10-16 | Established                    |
| 172.20.63.138 | node-to-node mesh | up    | 2018-10-16 | Established                    |
| 172.20.48.23  | node-to-node mesh | up    | 18:12:05   | Established                    |
| 172.20.36.44  | node-to-node mesh | up    | 13:19:15   | Established                    |
| 172.20.33.208 | node-to-node mesh | up    | 18:49:41   | Established                    |
+---------------+-------------------+-------+------------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.
```

These are the nodes in the cluster:

```
NAME                            STATUS    ROLES     AGE       VERSION
ip-172-20-33-208.ec2.internal   Ready     node      19h       v1.10.6
ip-172-20-36-44.ec2.internal    Ready     node      19h       v1.10.6
ip-172-20-48-23.ec2.internal    Ready     node      19h       v1.10.6
ip-172-20-53-133.ec2.internal   Ready     master    20h       v1.10.6
ip-172-20-58-136.ec2.internal   Ready     node      20h       v1.10.6
ip-172-20-62-170.ec2.internal   Ready     node      20h       v1.10.6
ip-172-20-63-138.ec2.internal   Ready     node      79d       v1.9.8
```

Thank you!
