### ISSUE TITLE
legacy IAM builder doesn't create correct node policy when using amazonvpc or romana 

### ISSUE THREAD

**Issue by wendorf** [kubernetes/kops#5959]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster --name cluster.example.com --out ./ --target terraform`

**5. What happened after the commands executed?**

Node policy document has neither:

```
    {
      "Effect": "Allow",
      "Action": [
        "ec2:*"
      ],
      "Resource": [
        "*"
      ]
    }
```

nor

```
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateNetworkInterface",
        "ec2:AttachNetworkInterface",
        "ec2:DeleteNetworkInterface",
        "ec2:DetachNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DescribeInstances",
        "ec2:ModifyNetworkInterfaceAttribute",
        "ec2:AssignPrivateIpAddresses",
        "tag:TagResources"
      ],
      "Resource": [
        "*"
      ]
    }
```

**6. What did you expect to happen?**

The node policy document has either `ec2:*` or the ENI actions.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: cluster.example.com
spec:
  cloudProvider: aws
  iam:
    legacy: true
  kubelet:
    cloudProvider: aws
  networking:
    amazonvpc:
      imageName: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:1.1.0
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I think https://github.com/kubernetes/kops/blob/258700f073cbe8883cb34ad9869a8b23029e6a91/pkg/model/iam/iam_builder.go#L790-L793 and https://github.com/kubernetes/kops/blob/258700f073cbe8883cb34ad9869a8b23029e6a91/pkg/model/iam/iam_builder.go#L790-L793 are buggy and the policies in those functions should be applied for nodes even in legacyIAM.
