### ISSUE TITLE
Route table corruption with multiple CNI-adapters

### ISSUE THREAD

**Issue by theikkila** [kubernetes/kops#6012]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. Description**
We've been running kops using various versions in AWS for a 6 months without an issue.
Mostly using `kube-router` as networking layer.
After we introduced medium workload with lot's of connections outside we started to have issues with random nodes regularly.

Issue is that randomly some nodes cannot connect external network (outside from our VPC's private network).

We have contacted AWS-support because we initially though this might be a bug in AWS-nat gateway since all other networking worked just fine. 

Finally after few days of debugging, going through lot's of tcpdumps and assitance provided by AWS we noticed that it's actually routing problem inside the cluster. 
We didn't though of this because we have changed first from **kube-router** to **calico** and from **calico** to **flannel** but the only way to resolve the problem is currently either terminating the node having these network problems or rebooting docker daemon in the node which seems to flush the routing tables and clear the issue.

**6. What did you expect to happen?**
I'm expecting to have a working connections without issues.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-25T12:48:26Z
  name: cluster.mydomain.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mycluster-state/cluster.mydomain.com
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-west-1a
      name: a
    name: events
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/bin/sh -c 'test -b /dev/nvme0n1p1 && growpart-workaround /dev/nvme0n1 1 && resize2fs /dev/nvme0n1p1 || true'
    name: resize-nvme-rootfs
    roles:
    - Node
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.6
  masterInternalName: api.internal.cluster.mydomain.com
  masterPublicName: api.cluster.mydomain.com
  networkCIDR: 10.166.153.0/24
  networkID: vpc-XXXX
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.166.153.0/26
  subnets:
  - cidr: 10.166.153.96/27
    id: subnet-05686282d8be1dccf
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.166.153.128/27
    id: subnet-04f6e476dec82f024
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.166.153.160/27
    id: subnet-056fd7a4d95979231
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 10.166.153.0/27
    id: subnet-0901c15ca2003f597
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.166.153.32/27
    id: subnet-007b099c8c5c05fcd
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 10.166.153.64/27
    id: subnet-0344716d054347ee2
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-25T12:48:26Z
  labels:
    kops.k8s.io/cluster: cluster.mydomain.com
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-05-25T12:48:26Z
  labels:
    kops.k8s.io/cluster: cluster.mydomain.com
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```
