### ISSUE TITLE
Add support for adding annotations to nodes from instance group spec

### ISSUE THREAD

**Issue by adammw** [kubernetes/kops#6026]
Equivalent to the `nodeLabels` spec for instance groups, but with annotations. For example: 

```yaml
spec:
  nodeAnnotations:
    k8s.amazonaws.com/eniConfig: my-custom-netconfig
```

Annotations are often required for various daemonsets running on the nodes for configuration, for example the eniConfig annotation in the example above is required for the AWS CNI plugin: aws/amazon-vpc-cni-k8s#165.

Previously reported as https://github.com/kubernetes/kops/issues/3344 but went stale.
