### ISSUE TITLE
Configure Bastion ELB Healthcheck

### ISSUE THREAD

**Issue by opensean** [kubernetes/kops#6072]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

It looks the configuration values for the bastion ELB healthcheck are hard coded [bastion.go](https://github.com/kubernetes/kops/blob/master/pkg/model/bastion.go).

```
HealthCheck: &awstasks.LoadBalancerHealthCheck{
				Target:             s("TCP:22"),
				Timeout:            i64(5),
				Interval:           i64(10),
				HealthyThreshold:   i64(2),
				UnhealthyThreshold: i64(2),
}

```

I have been told by some security folks at work that the 10 second interval can trigger [AWS GuardDuty SSHBruteForce alerts](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_unauthorized.html#unauthorized9).  

A useful feature would be to able to configure these values in the cluster spec similar to the [bastion ELB idle timeout](https://github.com/kubernetes/kops/blob/master/docs/bastion.md#changing-your-elb-idle-timeout), for example:

```
spec:
  topology:
    bastion:
      idleTimeoutSeconds: 1200
      target: "TCP:22"
      timeout: 5
      interval: 120
      healthyThreshold: 2
      unhealthyThreshold: 2

```

Thank you for making kops such an amazing tool,

- sean
