### ISSUE TITLE
protokube not specify the AWS_REGION in the manifest of etcd-manager

### ISSUE THREAD

**Issue by knight42** [kubernetes/kops#6098]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.9.3

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Follow the instructions in https://github.com/kubernetes/kops/blob/master/docs/etcd/manager.md.

**5. What happened after the commands executed?**
`etcd-manager` failed to start because of wrong default region `us-east-1`.

**6. What did you expect to happen?**
`etcd-manager` should locate the bucket in `cn-north-1` region.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: kops-test.k8s.local
spec:
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-store/kops-test.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-cn-north-1b-1
      name: "1"
    - instanceGroup: master-cn-north-1b-2
      name: "2"
    - instanceGroup: master-cn-north-1b-3
      name: "3"
    manager:
      image: kopeio/etcd-manager:latest
    name: main
  - etcdMembers:
    - instanceGroup: master-cn-north-1b-1
      name: "1"
    - instanceGroup: master-cn-north-1b-2
      name: "2"
    - instanceGroup: master-cn-north-1b-3
      name: "3"
    manager:
      image: kopeio/etcd-manager:latest
    name: events
  kubernetesVersion: https://s3.cn-north-1.amazonaws.com.cn/kops-asset/kubernetes/release/v1.9.3
  masterInternalName: api.internal.kops-test.k8s.local
  masterPublicName: api.kops-test.k8s.local
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
In fact, the bug is unrelated to `kops`, but related to `protokube`, so I guess I should paste the logs of `etcd-manager` here:
```
I1119 09:43:22.730080       1 s3context.go:154] unable to get bucket location from region "us-east-1"; scanning all regions: InvalidToken: The provided token is malformed or otherwise invalid.
        status code: 400, request id: <redacted>, host id: <redacted>
F1119 09:43:24.591170       1 main.go:304] error performing scan for legacy data: error marking cluster as created: error creating cluster-creation marker file s3://kops-state-store/kops-test
.k8s.local/backups/etcd/main/control/etcd-cluster-created: Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: <redacted>, host id: <redacted>
```
**9. Anything else do we need to know?**
