### ISSUE TITLE
"associatePublicIP: false" has no impact for GCE instance templates/nodes

### ISSUE THREAD

**Issue by LarsT42** [kubernetes/kops#6104]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
release-1.9, HEAD

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.9.10

**3. What cloud provider are you using?**
GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create -f...
...
```

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: xxxxx
  name: nodes
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-16
  maxSize: 3
  minSize: 3
  **associatePublicIP: false**
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
  - europe-west1-c
  - europe-west1-d
```
...
**5. What happened after the commands executed?**
Cluster runs with public ephemeral IP-Addresses for each node instead of none

**6. What did you expect to happen?**
No public access to node

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-11-20T08:20:13Z
  name: xxxx
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://xxxxxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: b
    - instanceGroup: master-europe-west1-c
      name: c
    - instanceGroup: master-europe-west1-d
      name: d
    name: main
  - etcdMembers:
    - instanceGroup: master-europe-west1-b
      name: b
    - instanceGroup: master-europe-west1-c
      name: c
    - instanceGroup: master-europe-west1-d
      name: d
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: kubernetes
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'oidc:'
    oidcIssuerURL: https://xxxx/dex
    oidcUsernameClaim: email
  kubelet: {}
  kubernetesApiAccess:
  - 217.110.227.178/32
  - 10.0.0.0/8
  kubernetesVersion: 1.9.10
  masterPublicName: api.xxxxx.gg
  networking: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: xxxx-220915
  sshAccess:
  - 217.110.227.178/32
  - 10.0.0.0/8
  subnets:
  - name: europe-west1
    region: europe-west1
    type: Private
  - name: utility-europe-west1
    type: Utility
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-20T08:20:15Z
  labels:
    kops.k8s.io/cluster: xxxx
  name: master-europe-west1-b
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-europe-west1-b
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-20T08:20:17Z
  labels:
    kops.k8s.io/cluster: xxxx
  name: master-europe-west1-c
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-europe-west1-c
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-20T08:20:18Z
  labels:
    kops.k8s.io/cluster: xxxx
  name: master-europe-west1-d
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-europe-west1-d
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-20T08:20:20Z
  labels:
    kops.k8s.io/cluster: xxxx
  name: nodes
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-16
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
  - europe-west1-c
  - europe-west1-d
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
n.a.
**9. Anything else do we need to know?**
