### ISSUE TITLE
Misconfigured etcd after upgrading to 1.10.11

### ISSUE THREAD

**Issue by xrl** [kubernetes/kops#6167]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
$ kops version
Version 1.10.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Trying to go from `1.10.7` -> `1.10.11`.

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Change `kubernetesVersion: 1.10.7` to `kubernetesVersion: 1.10.11`.

**5. What happened after the commands executed?**

The cluster update and rolling restart kick off as usual but the master never converges.

**6. What did you expect to happen?**

Converge and return clean.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-13T23:06:30Z
  name: secret.lalala.com
spec:
  additionalPolicies:
    node: |
      [{
        "Effect": "Allow",
        "Action": [
          "route53:ChangeResourceRecordSets"
        ],
        "Resource": [
          "arn:aws:route53:::hostedzone/*"
        ]
      },
      {
        "Effect": "Allow",
        "Action": [
          "route53:ListHostedZones",
          "route53:ListResourceRecordSets"
        ],
        "Resource": [
          "*"
        ]
      }]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://secret-cloudformation/kops/secret.lalala.com
  docker:
    logDriver: json-file
    logOpt:
    - max-size=50m
    - max-file=5
    storage: overlay2
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1b
      name: b
    name: events
  iam:
    legacy: true
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.7
  masterInternalName: api.internal.secret.lalala.com
  masterPublicName: api.secret.lalala.com
  networkCIDR: 172.20.0.0/16
  networkID: vpc-89ef61e1
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  - cidr: 172.20.96.0/19
    name: eu-central-1c
    type: Public
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

The error is inside the master so I'm just going to skip to the gist of logs I got.

**9. Anything else do we need to know?**

I logged on to the master and dumped the errors from the etcd and protokube: https://gist.github.com/xrl/2037013809baee4df1896ca88ca8ebe2
