### ISSUE TITLE
DNS records for api.internal not updated when upgrading to 1.10.11

### ISSUE THREAD

**Issue by edmeister** [kubernetes/kops#6168]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.9.6 to 1.10.11

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

The typical update process. `kops upgrade cluster`, `kops update cluster`, `kops rolling-update cluster`.

**5. What happened after the commands executed?**

The rolling update started fine, but the DNS records for `api.internal` were not updated. This caused the nodes to become `not ready` as soon as the last master node was cycled.

**6. What did you expect to happen?**

A working cluster. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-18T13:45:27Z
  name: k8s.******
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://******
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  externalDns:
    watchIngress: true
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubernetesApiAccess:
  - xxx.xxx.xxx.xxx
  kubernetesVersion: 1.10.11
  masterInternalName: api.internal.k8s.******
  masterPublicName: api.k8s.******
  networkCIDR: xxx.xxx.xxx.xxx/xx
  networking:
    calico:
      logSeverityScreen: error
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - xxx
  subnets:
  - cidr: 172.25.24.32/27
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.25.24.64/27
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.25.24.96/27
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 172.25.24.128/27
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.25.24.160/27
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.25.24.192/27
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T13:45:27Z
  labels:
    kops.k8s.io/cluster: k8s.******
  name: master-eu-west-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T13:45:27Z
  labels:
    kops.k8s.io/cluster: k8s.******
  name: master-eu-west-1b
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T13:45:27Z
  labels:
    kops.k8s.io/cluster: k8s.******
  name: master-eu-west-1c
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-03-18T13:45:27Z
  labels:
    kops.k8s.io/cluster: k8s.******
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.xlarge
  maxSize: 20
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I have upgraded 4 clusters so far, that were all set up using kops. The two I did last night (4/12/18) went fine, the two I did today all had the issue described at bullet 5.
