### ISSUE TITLE
Please allow creating scheduled jobs via Kops

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/kops#618]
According to http://kubernetes.io/docs/user-guide/scheduled-jobs : 

> You need a working Kubernetes cluster at version >= 1.4, with batch/v2alpha1 API turned on by passing --runtime-config=batch/v2alpha1 while bringing up the API server (see Turn on or off an API version for your cluster for more). 

Please provide a way to do that thru Kops on AWS, plzplzplz

**Comment by justinsb** [comment]
I think we’ll have to expose the runtime-config flag.  I actually thought I did but I exposed it as a map and this isn't a map option it looks like.  I'll take a look.

But is it better _also_ to allow you to specify specific functionality you want enabled.  So you could say “scheduledJobs: true".  And you would get batch/v2alpha1 enabled.  But later when scheduled jobs went GA, we would stop adding the flag?

**Comment by justinsb** [comment]
So at least on the first part, this should work if you build from master.

`kops edit cluster`, and add this to the spec:

```
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: true
```

If you `kops edit cluster` again just to check, it should look like this:

```
...
  etcdClusters:
  - etcdMembers:
    - name: us-east-1b
      zone: us-east-1b
    name: main
  - etcdMembers:
    - name: us-east-1b
      zone: us-east-1b
    name: events
  kubeAPIServer:
    runtimeConfig:
      batch/v2alpha1: "true"
  kubernetesVersion: v1.4.0
...
```

Then you'll have to force a re-read of the configuration.  Easiest way is probably to do a rolling-update of the whole cluster, but the detection is a bit wonky here.  (You actually only need to terminate the master instance if you'd prefer to do that)

```
kops rolling-update cluster --force --yes
```

When it comes back, if you want to you should can do

```
kubectl get pods --all-namespaces | grep kube-apiserver
kubectl describe --namespace=kube-system pod kube-apiserver-ip-172-20-85-46.ec2.internal | grep runtime
```

And you should see `--runtime-config=batch/v2alpha1=true`

Then I was able to do:
`kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/user-guide/sj.yaml`

Note that your `kubectl version` for the client must be 1.4 (I think)

**Comment by offlinehacker** [comment]
Thanks!

**Comment by chrislovecnm** [comment]
Moving this to documenation

**Comment by brunoalano** [comment]
Should check the issue #746 too

**Comment by Shrugs** [comment]
This is no longer an issue on master, I believe. In summary, after adding the additional properties (note the quotes around `"true"`)

```
  kubeAPIServer:
    runtimeConfig:
      "batch/v2alpha1": "true"
```

you must do a forced rolling update (`kops rolling-update cluster {cluster} --force --yes`), since kops doesn't yet have a way to determine whether or not the process on the master is running with the correct arguments.

**Comment by chrislovecnm** [comment]
Closing

**Comment by djuretic** [comment]
In my case (with AWS) after modifying the cluster I was getting this error:

```
Cluster.Spec.KubeAPIServer.CloudProvider: Invalid value: "": Did not match cluster CloudProvider
```

Solution: Add `cloudProvider: aws`, as shown below:

```
kubeAPIServer:
  cloudProvider: aws
  runtimeConfig:
    batch/v2alpha1: "true"
```
