### ISSUE TITLE
Failed to start nvidia-device-plugin

### ISSUE THREAD

**Issue by yujunz** [kubernetes/kops#6227]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Version 1.10.11

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Follow the instructions in https://github.com/kubernetes/kops/blob/master/hooks/nvidia-device-plugin/README.md Then

`kubectl logs nvidia-device-plugin-daemonset-qdqvx`

**5. What happened after the commands executed?**

```
2018/12/20 08:48:07 Loading NVML
2018/12/20 08:48:07 Failed to initialize NVML: could not load NVML library.
2018/12/20 08:48:07 If this is a GPU node, did you set the docker default runtime to `nvidia`?
...
```

**6. What did you expect to happen?**

No failure during start.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-12-20T07:58:08Z
  name: clover.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-nvaiinfracn-stage-state-store/clover.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.11
  masterPublicName: api.clover.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-20T07:58:09Z
  labels:
    kops.k8s.io/cluster: clover.k8s.local
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-20T07:58:09Z
  labels:
    kops.k8s.io/cluster: clover.k8s.local
  name: nodes
spec:
  hooks:
  - execContainer:
      image: dcwangmit01/nvidia-device-plugin:0.1.0
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: p2.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

N/A
