### ISSUE TITLE
AWS - multiple AZ cluster doesn't cooperate with PVC from different AZ

### ISSUE THREAD

**Issue by wszychta** [kubernetes/kops#6267]
Hi I have problem with kubernetes cluster created with kops
I'm using this command to create cluster on AWS:
```
kops create cluster \
--bastion="true" \
--master-count=3 \
--node-count=4 \
--master-zones eu-west-1a,eu-west-1b,eu-west-1c \
--zones eu-west-1a,eu-west-1b,eu-west-1c \
--node-size t2.medium \
--master-size t2.small \
--dns private \
--dns-zone MY_DNS_ZONE \
--vpc MY_VPC \
--topology private \
--networking kopeio-vxlan \
--target=terraform \
${NAME}
```

Everything is working fine before I try to create PVC on EBS.
My pods are in **"Pending"** state and in `kubectl get events` I see comunicate:
`0/7 nodes are available: 3 node(s) had taints that the pod didn't tolerate, 4 node(s) had no available volume zone.`

**When I change cluster from Multiple AZs to only single AZ everything is working fine.**
As I understand pods are not able to connect to PVs in different AZ than pods.

Can you help me with this case or redirect me to some who can help with that? I'm new to Kubernetes and to run my project I used **docker-compose**, **kops** and **kompose** (https://github.com/kubernetes/kompose)

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
docker-compose version:
```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
kops version:
```
Version 1.10.0 (git-8b52ea6d1)
```
kompose version:
```
1.17.0 (a74acad)
```

here are examples of my project database kubernetes files with claims:

**database deployment:**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
        image: mysql:5.7
        name: DATABASE_NAME
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: database-claim0
        - mountPath: /etc/mysql/conf.d
          name: database-claim1
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
      - name: database-claim1
        persistentVolumeClaim:
          claimName: database-claim1
status: {}
```

**database claim:**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-claim0
  name: database-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
```
