### ISSUE TITLE
kops update cluster wants to create already-existing shared subnets if KubernetesCluster tag isn't present

### ISSUE THREAD

**Issue by wilsonjackson** [kubernetes/kops#6294]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Owner cluster was last updated with 1.10.0. Shared cluster was created with 1.10.0.

The issue is present when trying to update the owner cluster with kops 1.10.0, 1.10.1, and 1.11.1.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.3 (owned) & 1.10.11 (shared)

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops update cluster owner.cluster`

**5. What happened after the commands executed?**

If `KubernetesCluster` tag is present and set to the name of the owner cluster, I see `No changes need to be applied`

If `KubernetesCluster` tag is not present (which is presently the advice [in the docs](https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md#subnet-tags)):

```
Will create resources:
  RouteTableAssociation/private-us-west-2a.owner.cluster
  	RouteTable          	name:private-us-west-2a.owner.cluster id:rtb-XXXXXXXX
  	Subnet              	name:us-west-2a.owner.cluster

  RouteTableAssociation/private-us-west-2b.owner.cluster
  	RouteTable          	name:private-us-west-2b.owner.cluster id:rtb-XXXXXXXX
  	Subnet              	name:us-west-2b.owner.cluster

  RouteTableAssociation/utility-us-west-2a.owner.cluster
  	RouteTable          	name:owner.cluster id:rtb-XXXXXXXX
  	Subnet              	name:utility-us-west-2a.owner.cluster

  RouteTableAssociation/utility-us-west-2b.owner.cluster
  	RouteTable          	name:owner.cluster id:rtb-XXXXXXXX
  	Subnet              	name:utility-us-west-2b.owner.cluster

  Subnet/us-west-2a.owner.cluster
  	ShortName           	us-west-2a
  	VPC                 	name:owner.cluster id:vpc-XXXXXXXX
  	AvailabilityZone    	us-west-2a
  	CIDR                	10.40.32.0/19
  	Shared              	false
  	Tags                	{Name: us-west-2a.owner.cluster, KubernetesCluster: owner.cluster, kubernetes.io/cluster/owner.cluster: owned, kubernetes.io/role/internal-elb: 1, SubnetType: Private}

  Subnet/us-west-2b.owner.cluster
  	ShortName           	us-west-2b
  	VPC                 	name:owner.cluster id:vpc-XXXXXXXX
  	AvailabilityZone    	us-west-2b
  	CIDR                	10.40.64.0/19
  	Shared              	false
  	Tags                	{Name: us-west-2b.owner.cluster, KubernetesCluster: owner.cluster, kubernetes.io/cluster/owner.cluster: owned, kubernetes.io/role/internal-elb: 1, SubnetType: Private}

  Subnet/utility-us-west-2a.owner.cluster
  	ShortName           	utility-us-west-2a
  	VPC                 	name:owner.cluster id:vpc-XXXXXXXX
  	AvailabilityZone    	us-west-2a
  	CIDR                	10.40.96.0/22
  	Shared              	false
  	Tags                	{Name: utility-us-west-2a.owner.cluster, KubernetesCluster: owner.cluster, kubernetes.io/cluster/owner.cluster: owned, kubernetes.io/role/elb: 1, SubnetType: Utility}

  Subnet/utility-us-west-2b.owner.cluster
  	ShortName           	utility-us-west-2b
  	VPC                 	name:owner.cluster id:vpc-XXXXXXXX
  	AvailabilityZone    	us-west-2b
  	CIDR                	10.40.100.0/22
  	Shared              	false
  	Tags                	{SubnetType: Utility, Name: utility-us-west-2b.owner.cluster, KubernetesCluster: owner.cluster, kubernetes.io/cluster/owner.cluster: owned, kubernetes.io/role/elb: 1}
```

**6. What did you expect to happen?**

In both cases no new resources should be created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-05-31T07:09:20Z
  name: owner.cluster
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://XXXXXXXX/owner.cluster
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  hooks:
  - before:
    - kubelet.service
    manifest: |
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/aws-iam-authenticator
      ExecStart=/usr/local/bin/aws s3 cp --recursive s3://XXXXXXXX/owner.cluster/addons/authenticator /srv/kubernetes/aws-iam-authenticator/
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    legacy: true
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml
    authorizationRbacSuperUser: admin
    featureGates:
      CustomPodDNS: "true"
    runtimeConfig:
      batch/v2alpha1: "true"
  kubelet:
    authenticationTokenWebhook: true
    featureGates:
      CustomPodDNS: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.3
  masterInternalName: api.internal.owner.cluster
  masterPublicName: api.owner.cluster
  networkCIDR: 10.40.0.0/16
  networkID: vpc-XXXXXXXX
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - X.X.X.X/24
  - X.X.X.X/24
  subnets:
  - cidr: 10.40.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.40.64.0/19
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.40.96.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.40.100.0/22
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-31T07:09:20Z
  labels:
    kops.k8s.io/cluster: owner.cluster
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-31T07:09:21Z
  labels:
    kops.k8s.io/cluster: owner.cluster
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 9
  minSize: 1
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-2a
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-16T02:51:53Z
  labels:
    kops.k8s.io/cluster: owner.cluster
  name: util-node
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    XXXXXXXX/node-util: "true"
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - us-west-2a
  - us-west-2b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/wilsonjackson/cff6eff32eea4bc2f0a55dbf8d50898a

**9. Anything else do we need to know?**

`kubernetes.io/cluster/owner.cluster: owned` and `kubernetes.io/cluster/shared.cluster: shared` tags are present on the subnets.

Both clusters were created an a preexisting VPC, which is not owned by any cluster. The subnets/route tables/etc. were created by the owner cluster.

**Comment by Nuru** [comment]
As explained in the ["run in existing VPC" docs](https://github.com/kubernetes/kops/blob/737a7a2cb81b70b558095ba1261a0898cc2bd168/docs/run_in_existing_vpc.md#shared-subnets), if you want `kops` to use existing subnets rather than create its own, you must specify the subnet ID to use as well as the CIDRs. Similarly, if you want to share gateways, you must also provide gateway IDs. So your Cluster.spec.subnets should look like:
```
  subnets:
  - cidr: 10.40.32.0/19
    egress: nat-0XXXXXXXXXXXXXXXX
    id: subnet-0XXXXXXXXXXXXXXXX
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.40.64.0/19
    egress: nat-0XXXXXXXXXXXXXXXX
    id: subnet-0XXXXXXXXXXXXXXXX
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.40.96.0/22
    id: subnet-0XXXXXXXXXXXXXXXX
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.40.100.0/22
    id: subnet-0XXXXXXXXXXXXXXXX
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
```
If you specify subnets and gateways, `kops` will not create them, and also will not create route tables.
