### ISSUE TITLE
upgrade disfunction after interrupted worker upgrade

### ISSUE THREAD

**Issue by gladiatr72** [kubernetes/kops#6315]
This has happened twice this month.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.10.0 (git-8b52ea6d1)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.10.11

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops rolling-update cluster [cluster name] --yes`

**5. What happened after the commands executed?**

The cluster has several nodes.  The amount of time it was taking exceeded the amount of time allowed (by default) by kops to do its thing.  This timeout occured after the aforementioned node was finished its termination and subsequent replacement.

Righto.  Ok.  No problem.  I re-ran the _rolling_update_ command.

Kops initializes its run, checks already-upgraded nodes, finally arriving at the node that was not finished during the last run it declares something to the effect of _node already cordoned_.

Then it stops.

It waits.

Waits some more.

Eventually it exits at the (default) timeout threshold.

**6. What did you expect to happen?**

I expected kops to see this final node in its state of already-cordoned and continue on its merry way.   

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: mud
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://puddle
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    name: main
    version: 3.0.17
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    name: events
    version: 3.0.17
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubernetesApiAccess: []
  kubernetesVersion: 1.10.12
  masterInternalName: api.internal.mud
  masterPublicName: api.mud
  networkCIDR: 10.131.0.0/19
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess: []
  subnets:
  - cidr: 10.131.4.0/22
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 10.131.8.0/22
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 10.131.12.0/22
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I achieved my goal of a cleanly upgraded cluster by destroying the worker instance--its replacement came online without problem.  Unfortunately time constraints did not allow for filing an issue before pulling out the hatchet.

**9. Anything else do we need to know?**
