### ISSUE TITLE
KubeAPIServer Webhook misconfigured when running aws authenticator

### ISSUE THREAD

**Issue by mazzy89** [kubernetes/kops#6321]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.5

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Spin up a cluster with the following cluster Spec:

```yaml
hooks:
  - name: kops-hook-authenticator-config.service
     before:
       - kubelet.service
     roles:
       - Master
     manifest: |-
       [Unit]
       Description=Download AWS Authenticator configs from S3
       [Service]
       Type=oneshot
       ExecStart=/bin/mkdir -p /srv/kubernetes/aws-iam-authenticator
       ExecStart=/usr/local/bin/aws s3 cp --recursive s3://pb-ops-kops-state-store/voyager.staging.productboard.net/addons/authenticator /srv/kubernetes/aws-iam-authenticator/
authentication:
   aws: {}
kubeAPIServer:
   authenticationTokenWebhookConfigFile: "/srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml"
```

**5. What happened after the commands executed?**

The KubeAPIServer is spin up with the following command:

```sh
  - command:
    - /bin/sh
    - -c
    - mkfifo /tmp/pipe; (tee -a /var/log/kube-apiserver.log < /tmp/pipe & ) ; exec
      /usr/local/bin/kube-apiserver --allow-privileged=true --anonymous-auth=false
      --apiserver-count=3 --authentication-token-webhook-config-file=/etc/kubernetes/authn.config
      --authorization-mode=RBAC --basic-auth-file=/srv/kubernetes/basic_auth.csv --bind-address=0.0.0.0
      --client-ca-file=/srv/kubernetes/ca.crt --cloud-provider=aws --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority
      --etcd-cafile=/srv/kubernetes/ca.crt --etcd-certfile=/srv/kubernetes/etcd-client.pem
      --etcd-keyfile=/srv/kubernetes/etcd-client-key.pem --etcd-servers-overrides=/events#https://127.0.0.1:4002
      --etcd-servers=https://127.0.0.1:4001 --insecure-bind-address=127.0.0.1 --insecure-port=8080
      --kubelet-client-certificate=/srv/kubernetes/kubelet-api.pem --kubelet-client-key=/srv/kubernetes/kubelet-api-key.pem
      --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP --proxy-client-cert-file=/srv/kubernetes/apiserver-aggregator.cert
      --proxy-client-key-file=/srv/kubernetes/apiserver-aggregator.key --requestheader-allowed-names=aggregator
      --requestheader-client-ca-file=/srv/kubernetes/apiserver-aggregator-ca.cert
      --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group
      --requestheader-username-headers=X-Remote-User --secure-port=443 --service-cluster-ip-range=100.64.0.0/13
      --storage-backend=etcd3 --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key
      --token-auth-file=/srv/kubernetes/known_tokens.csv --v=2 > /tmp/pipe 2>&1
```

**6. What did you expect to happen?**

It should be  `--authentication-token-webhook-config-file=/srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml`.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

AWS IAM Authenticator version 0.3.0

Log

```txt
aws-iam-authenticator-5hzbd aws-iam-authenticator time="2019-01-10T15:40:05Z" level=info msg="mapping IAM role" groups="[system:masters]" role="arn:aws:iam::xxxxxxxxxxxxxxx:role/kubernetes-admin" username="kubernetes-admin:{{AccountID}}:{{SessionName}}"
aws-iam-authenticator-5hzbd aws-iam-authenticator time="2019-01-10T15:40:05Z" level=info msg="loaded existing keypair" certPath=/var/aws-iam-authenticator/cert.pem keyPath=/var/aws-iam-authenticator/key.pem
aws-iam-authenticator-5hzbd aws-iam-authenticator time="2019-01-10T15:40:05Z" level=info msg="listening on https://127.0.0.1:21362/authenticate"
aws-iam-authenticator-5hzbd aws-iam-authenticator time="2019-01-10T15:40:05Z" level=info msg="reconfigure your apiserver with `--authentication-token-webhook-config-file=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml` to enable (assuming default hostPath mounts)"
```
