### ISSUE TITLE
internal route53 record did not get created when running `kubectl apply -f service.yaml`

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/kops#6322]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops v1.9.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

k8s version for server, v1.9.10
kubectl, v1.13.1 (whatever the latest version)

**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kubectl apply -f service.yml

**5. What happened after the commands executed?**

The reoute53 DNS pointing to the ingress LB not getting created.

**6. What did you expect to happen?**

I thought a managed route53 DNS would be created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: v1
kind: Service
metadata:
  name: x-service
  namespace: x
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ CERTIFICATE_ARN }}
    dns.alpha.kubernetes.io/internal: "xx.internal.dns"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 9000
  selector:
    name: x-service
    app: x
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
