### ISSUE TITLE
kops not recreating ELB

### ISSUE THREAD

**Issue by thedarkfalcon** [kubernetes/kops#6332]
Hi,

I had a cluster which was created with public topology, I tried shifting it to a private as per [the docs](https://github.com/kubernetes/kops/blob/master/docs/topology.md) but the update left the cluster broken (as per below). I changed the cluster config back to public and ran the update process again, but the cluster is still broken.

When I run a force rolling update command kops terminates and recreates the nodes, but the masters or the ELB aren't being created. I can see in the aws console that the master autoscaling groups are failing to create their masters because the masters are trying to be added to the deleted ELB.

`Failed: Launching a new EC2 instance
 Status Reason: There is no ACTIVE Load Balancer named '_[redacted load balancer name]_'. Validating load balancer configuration failed.`

Why isn't a new ELB being created? Do I need to manually delete the autoscaling master groups referencing the previous ELB?

**1. What `kops` version are you running?**
Version 1.9.0

**2. What Kubernetes version are you running?**
1.10.3

**3. What cloud provider are you using?**
aws

**7. Please provide your cluster manifest.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-11-21T02:53:18Z
  name: [REDACTED]
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Product: [REDACTED]
  cloudProvider: aws
  configBase: [REDACTED]
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ca-central-1a-1
      name: a-1
    - instanceGroup: master-ca-central-1b-1
      name: b-1
    - instanceGroup: master-ca-central-1a-2
      name: a-2
    name: main
  - etcdMembers:
    - instanceGroup: master-ca-central-1a-1
      name: a-1
    - instanceGroup: master-ca-central-1b-1
      name: b-1
    - instanceGroup: master-ca-central-1a-2
      name: a-2
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - Initializers
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - ResourceQuota
    - PodSecurityPolicy
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - AlwaysPullImages
    - DenyEscalatingExe
  kubernetesApiAccess:
  - [REDACTED]
  kubernetesVersion: 1.10.11
  masterInternalName: api.internal.[REDACTED]
  masterPublicName: api.[REDACTED]
  networkCIDR: 192.168.64.0/21
  networking:
    cni: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - [REDACTED]
  subnets:
  - cidr: 192.168.65.0/24
    name: ca-central-1a
    type: Public
    zone: ca-central-1a
  - cidr: 192.168.66.0/24
    name: ca-central-1b
    type: Public
    zone: ca-central-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-21T02:53:19Z
  labels:
    kops.k8s.io/cluster: [REDACTED].k8s.local
  name: master-ca-central-1a-1
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1a-1
  role: Master
  subnets:
  - ca-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-21T02:53:19Z
  labels:
    kops.k8s.io/cluster: [REDACTED].k8s.local
  name: master-ca-central-1a-2
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1a-2
  role: Master
  subnets:
  - ca-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-21T02:53:19Z
  labels:
    kops.k8s.io/cluster: [REDACTED].k8s.local
  name: master-ca-central-1b-1
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1b-1
  role: Master
  subnets:
  - ca-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-11-21T02:53:20Z
  labels:
    kops.k8s.io/cluster: [REDACTED].k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ca-central-1a
  - ca-central-1b
```
