### ISSUE TITLE
ipvsScheduler isn't being passed to terraform userdata

### ISSUE THREAD

**Issue by angelichorsey** [kubernetes/kops#6337]
1. 
```
$ kops version
Version 1.11.0 (git-2c2042465)
```
2. kubernetes 1.10.11

3. aws cloud provider

4. Provide cluster spec with the following and then run `kops update cluster --target=terraform`
```  
spec:
  kubeProxy:
    proxyMode: ipvs
    ipvsScheduler: lc
```

5. After execution the files wrote to disk, but the aws_launch_configuration* files used for userdata did not have the `ipvsScheduler: lc` line under `kubeProxy`

6. I expected this value to exist in the userdata.

7.
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: k8s.<redacted>
spec:
  additionalPolicies:
    master: |
      <redacted>
    node: |
      <redacted>
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://<redacted>/k8s.<redacted>
  dnsZone: k8s.<redacted>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: dev-master-ue1b-1
      name: dev-b-1
    - instanceGroup: dev-master-ue1c-1
      name: dev-c-1
    - instanceGroup: dev-master-ue1b-2
      name: dev-b-2
    name: main
  - etcdMembers:
    - instanceGroup: dev-master-ue1b-1
      name: dev-b-1
    - instanceGroup: dev-master-ue1c-1
      name: dev-c-1
    - instanceGroup: dev-master-ue1b-2
      name: dev-b-2
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - ResourceQuota
    - DefaultTolerationSeconds
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubernetesApiAccess:
  - <redacted>
  kubernetesVersion: 1.10.11
  kubeProxy:
    proxyMode: ipvs
    ipvsScheduler: lc
  masterInternalName: api.internal.k8s.<redacted>
  masterPublicName: api.k8s.<redacted>
  networkCIDR: <redacted>
  networkID: vpc-<redacted>
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - <redacted>
  sshKeyName: <redacted>
  subnets:
  - cidr: <redacted>
    id: subnet-<redacted>
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: <redacted>
    id: subnet-<redacted>
    name: us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

8. I'll wait until this sort of thing is the only other option to resolve this. A lot of work to review and clean information from `-v 10`. I can see very early on
```
I0114 12:12:43.857381   25836 options_loader.go:130] executing builder *components.KubeProxyOptionsBuilder
I0114 12:12:43.859543   25836 spec_builder.go:49] options: {
```
and in the options it outputs there is no `ipvsScheduler` under `kubeProxy`.

9. The only extra information I can think of is that I see this flag should be available from
https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go
line 215:
```
IPVSScheduler *string `json:"ipvsScheduler,omitempty" flag:"ipvs-scheduler"`
```

**Comment by angelichorsey** [comment]
I've also manually added `ipvsScheduler: lc` to the launch configuration userdata and after a rolling update the cluster has `--proxy-mode=ipvs` but lacks the scheduler flag.

**Comment by clee231** [comment]
This may be related.
For Kubernetes before 1.11, the ipvs feature is behind a feature flag:
```
kubeProxy:
  proxyMode: ipvs
  ipvsScheduler: lc
  featureGates:
    SupportIPVSProxyMode: "true"
```
