### ISSUE TITLE
Docker systemd unit being overwritten by unattended-upgrade

### ISSUE THREAD

**Issue by dtshepherd** [kubernetes/kops#6339]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.10.11

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Deploy a simple cluster using the `kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17` AMI and running docker `18.06.1`.  The cluster will come up fine and you can deploy kubernetes resources to it.

Force the `systemd` package to be re-installed (or upgrade it).  Note, the AMI does this automatically when `systemd` changes and in my case, that's what happened:
```
Start-Date: 2019-01-14  06:12:06
Commandline: /usr/bin/unattended-upgrade
Upgrade: libsystemd0:amd64 (232-25+deb9u4, 232-25+deb9u7)
End-Date: 2019-01-14  06:12:15
```

`/etc/systemd/system/docker.service` is reverted to its original installed state, not the overwritten version deployed by `kops`.

Run `sudo systemctl restart docker` and watch docker fail to start, since it can't find its config `/etc/sysconfig/docker`.

**5. What happened after the commands executed?**

Docker fails to start-up or restart.  Note, docker may restart if a node OOMs, not just when SSH'd in restarting it.

**6. What did you expect to happen?**

Docker should restart as expected and configs maintained.  The `stretch` image should either disable `unattended-upgrade` (bad idea) or use `systemd` [drop-ins](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) (probably the right way).

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: mycluster.mydomain.com
spec:
  additionalNetworkCIDRs:
  - 172.27.1.0/26
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mystate/mycluster.mydomain.com
  dnsZone: mydomain.com
  docker:
    version: 18.06.1
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  fileAssets:
  - content: |
      {
          "name": "cbr0",
          "plugins": [
              {
                  "type": "flannel",
                  "delegate": {
                      "hairpinMode": true,
                      "isDefaultGateway": true
                  }
              },
              {
                  "type": "portmap",
                  "capabilities": {
                      "portMappings": true
                  }
                }
          ]
      }
    name: flannel.conflist
    path: /etc/cni/net.d/00-flannel.conflist
    roles:
    - Master
    - Node
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    cloudProvider: aws
    runtimeConfig:
      batch/v2alpha1: "true"
  kubelet:
    featureGates:
      ReadOnlyAPIDataVolumes: "false"
  kubernetesApiAccess:
  - X.X.X.X
  kubernetesVersion: 1.10.11
  masterInternalName: api.internal.mycluster.mydomain.com
  masterPublicName: api.mycluster.mydomain.com
  networkCIDR: 172.21.0.0/16
  networkID: vpc-be342cc5
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - X.X.X.X
  subnets:
  - cidr: 172.21.10.0/24
    id: subnet-43aa746d
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 172.27.1.0/26
    id: subnet-003278753c78d0a0b
    name: us-east-1c-external
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T16:32:01Z
  labels:
    kops.k8s.io/cluster: mycluster.mydomain.com
  name: fixed-ip-node
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    efk-node: "true"
    fixed-ip-node: "true"
    generic-node: "true"
  role: Node
  rootVolumeSize: 300
  rootVolumeType: gp2
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T16:32:01Z
  labels:
    kops.k8s.io/cluster: mycluster.mydomain.com
  name: kafka
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kafka-node: "true"
  role: Node
  rootVolumeSize: 1000
  rootVolumeType: gp2
  subnets:
  - us-east-1c
  taints:
  - kafka-node=true:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T16:31:59Z
  labels:
    kops.k8s.io/cluster: mycluster.mydomain.com
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    master-node: "true"
  role: Master
  rootVolumeSize: 300
  rootVolumeType: gp2
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-19T16:32:00Z
  labels:
    kops.k8s.io/cluster: mycluster.mydomain.com
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.2xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    efk-node: "true"
    generic-node: "true"
  role: Node
  rootVolumeSize: 300
  rootVolumeType: gp2
  subnets:
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

If you reboot the node, the `kops-configuration` re-installs the systemd override for `docker`.  However, if a node OOMs or has some other failure, docker may restart without a node restart.  It seems like systemd drop-ins should be used for any overrides of the system installed systemd units.
