### ISSUE TITLE
Amazon Linux 2 default cluster has inter-pod connectivity issue

### ISSUE THREAD

**Issue by pahud** [kubernetes/kops#6341]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

$ kops version
Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I created my cluster in `us-west-2` like this:

```
kops create cluster --cloud=aws \
--name=cluster.uw2.k8s.local \
--image=ami-03c652d3a09856345 \
--zones=us-west-2a,us-west-2b,us-west-2c \
--master-count=3 \
--master-size=m5.large \
--node-count=3 \
--node-size=m5.large \
--vpc=vpc-09905ff2c172b6cd7 \
--networking=amazon-vpc-routed-eni \
--ssh-public-key=~/.ssh/id_rsa.pub
```

**5. What happened after the commands executed?**

everything looks fine when cluster is created. However, after a few minutes, `kube-dns` keeps crashing.

![image](https://user-images.githubusercontent.com/278432/51154143-d563b100-18ad-11e9-8883-eb3111ed1a53.png)

```
$ kubectl -n kube-system describe po/kube-dns-6b4f4b544c-2s2z9
Name:               kube-dns-6b4f4b544c-2s2z9
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-108-4.us-west-2.compute.internal/10.0.108.4
Start Time:         Tue, 15 Jan 2019 01:38:48 +0000
Labels:             k8s-app=kube-dns
                    pod-template-hash=2609061007
Annotations:        prometheus.io/port=10055
                    prometheus.io/scrape=true
                    scheduler.alpha.kubernetes.io/critical-pod=
                    scheduler.alpha.kubernetes.io/tolerations=[{"key":"CriticalAddonsOnly", "operator":"Exists"}]
Status:             Running
IP:                 10.0.108.70
Controlled By:      ReplicaSet/kube-dns-6b4f4b544c
Containers:
  kubedns:
    Container ID:  docker://538a2274a1681e437f96769baa4e926c4e1298c6c69f9e0757a0cdd3a259b359
    Image:         k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.10
    Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-kube-dns-amd64@sha256:b99fc3eee2a9f052f7eb4cc00f15eb12fc405fa41019baa2d6b79847ae7284a8
    Ports:         10053/UDP, 10053/TCP, 10055/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      --config-dir=/kube-dns-config
      --dns-port=10053
      --domain=cluster.local.
      --v=2
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 15 Jan 2019 02:09:13 +0000
      Finished:     Tue, 15 Jan 2019 02:10:13 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      memory:  170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-k2ll9 (ro)
  dnsmasq:
    Container ID:  docker://aa44c3ab6b8064380248d008c37e312c9b67ea32c188e07710d4d7f8fbcfe43d
    Image:         k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10
    Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:bbb2a290a568125b3b996028958eb773f33b5b87a6b37bf38a28f8b62dddb3c8
    Ports:         53/UDP, 53/TCP
    Host Ports:    0/UDP, 0/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --dns-forward-max=150
      --no-negcache
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/in6.arpa/127.0.0.1#10053
    State:          Running
      Started:      Tue, 15 Jan 2019 02:11:09 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Tue, 15 Jan 2019 02:08:59 +0000
      Finished:     Tue, 15 Jan 2019 02:11:09 +0000
    Ready:          True
    Restart Count:  6
    Requests:
      cpu:        150m
      memory:     20Mi
    Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-k2ll9 (ro)
  sidecar:
    Container ID:  docker://b2b343c4ae40c36c738b7495b385997932cf21e213ac5746817d3aa4ee594f54
    Image:         k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.10
    Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-sidecar-amd64@sha256:4f1ab957f87b94a5ec1edc26fae50da2175461f00afecf68940c4aa079bd08a4
    Port:          10054/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 15 Jan 2019 02:09:00 +0000
      Finished:     Tue, 15 Jan 2019 02:11:10 +0000
    Ready:          False
    Restart Count:  6
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-k2ll9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-k2ll9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-k2ll9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From                                               Message
  ----     ------            ----                ----                                               -------
  Warning  FailedScheduling  34m (x5 over 34m)   default-scheduler                                  0/3 nodes are available: 3 node(s) were not ready.
  Warning  FailedScheduling  34m                 default-scheduler                                  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 node(s) were not ready.
  Warning  FailedScheduling  34m                 default-scheduler                                  0/3 nodes are available: 1 node(s) were not ready, 2 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  33m (x13 over 34m)  default-scheduler                                  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  33m (x2 over 33m)   default-scheduler                                  0/4 nodes are available: 1 node(s) were not ready, 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  33m (x2 over 33m)   default-scheduler                                  0/5 nodes are available: 2 node(s) were not ready, 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  33m                 default-scheduler                                  0/6 nodes are available: 3 node(s) had taints that the pod didn't tolerate, 3 node(s) were not ready.
  Normal   Pulling           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  pulling image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.10"
  Normal   Pulled            33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Successfully pulled image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.10"
  Normal   Created           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Created container
  Normal   Started           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Started container
  Normal   Pulling           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  pulling image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10"
  Normal   Pulling           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  pulling image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.10"
  Normal   Created           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Created container
  Normal   Started           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Started container
  Normal   Pulled            33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Successfully pulled image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10"
  Normal   Pulled            33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Successfully pulled image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.10"
  Normal   Created           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Created container
  Normal   Started           33m                 kubelet, ip-10-0-108-4.us-west-2.compute.internal  Started container
  Warning  Unhealthy         12m (x4 over 12m)   kubelet, ip-10-0-108-4.us-west-2.compute.internal  Liveness probe failed: Get http://10.0.108.70:10054/metrics: dial tcp 10.0.108.70:10054: connect: connection refused
  Warning  Unhealthy         12m (x4 over 12m)   kubelet, ip-10-0-108-4.us-west-2.compute.internal  Liveness probe failed: Get http://10.0.108.70:10054/healthcheck/kubedns: dial tcp 10.0.108.70:10054: connect: connection refused
  Warning  Unhealthy         12m (x5 over 12m)   kubelet, ip-10-0-108-4.us-west-2.compute.internal  Liveness probe failed: Get http://10.0.108.70:10054/healthcheck/dnsmasq: dial tcp 10.0.108.70:10054: connect: connection refused
  Warning  Unhealthy         8m (x25 over 12m)   kubelet, ip-10-0-108-4.us-west-2.compute.internal  Readiness probe failed: Get http://10.0.108.70:8081/readiness: dial tcp 10.0.108.70:8081: connect: connection refused
  Normal   Killing           3m (x5 over 11m)    kubelet, ip-10-0-108-4.us-west-2.compute.internal  Killing container with id docker://dnsmasq:Container failed liveness probe.. Container will be killed and recreated.
```

It looks like the liveness probe fails with conection being refused.

Trying to run `nginx` and `curl` from another pod, no response. Looks like the inter-pod connectivity is being rejected. 

```
pahud:~/environment $ kubectl delete deploy/nginx
deployment.extensions "nginx" deleted
pahud:~/environment $ kubectl run nginx --image nginx --port 80
deployment.apps "nginx" created
pahud:~/environment $ kubectl get po
NAME                     READY     STATUS    RESTARTS   AGE
nginx-6f858d4d45-7p5j5   1/1       Running   0          29s
pahud:~/environment $ kubectl get po  -l run=nginx --output=jsonpath={.items[0].status.podIP}
10.0.79.63pahud:~/environment $ kubectl run curlx --image=radial/busyboxplus:curl -ti --rm --restart=Never 
If you don't see a command prompt, try pressing enter.
[ root@curlx:/ ]$ curl http://10.0.79.63

```

**6. What did you expect to happen?**

inter-pod communication is healthy.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-01-15T01:30:46Z
  name: cluster.uw2.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://pahud-tmp-us-west-2/cluster.uw2.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterPublicName: api.cluster.uw2.k8s.local
  networkCIDR: 10.0.0.0/16
  networkID: vpc-09905ff2c172b6cd7
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 10.0.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 10.0.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-15T01:30:46Z
  labels:
    kops.k8s.io/cluster: cluster.uw2.k8s.local
  name: master-us-west-2a
spec:
  image: ami-03c652d3a09856345
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-15T01:30:46Z
  labels:
    kops.k8s.io/cluster: cluster.uw2.k8s.local
  name: master-us-west-2b
spec:
  image: ami-03c652d3a09856345
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-15T01:30:47Z
  labels:
    kops.k8s.io/cluster: cluster.uw2.k8s.local
  name: master-us-west-2c
spec:
  image: ami-03c652d3a09856345
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-15T01:30:47Z
  labels:
    kops.k8s.io/cluster: cluster.uw2.k8s.local
  name: nodes
spec:
  image: ami-03c652d3a09856345
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The output of `iptables-save` from within one of the nodes just FYR

```
# iptables-save 
# Generated by iptables-save v1.4.21 on Tue Jan 15 02:19:05 2019
*mangle
:PREROUTING ACCEPT [34675:59694978]
:INPUT ACCEPT [29338:56471944]
:FORWARD ACCEPT [5120:3208440]
:OUTPUT ACCEPT [27569:2948001]
:POSTROUTING ACCEPT [32689:6156441]
-A PREROUTING -i eth0 -m comment --comment "AWS, primary ENI" -m addrtype --dst-type LOCAL --limit-iface-in -j CONNMARK --set-xmark 0x80/0x80
-A PREROUTING -i eni+ -m comment --comment "AWS, primary ENI" -j CONNMARK --restore-mark --nfmask 0x80 --ctmask 0x80
COMMIT
# Completed on Tue Jan 15 02:19:05 2019
# Generated by iptables-save v1.4.21 on Tue Jan 15 02:19:05 2019
*nat
:PREROUTING ACCEPT [4:240]
:INPUT ACCEPT [4:240]
:OUTPUT ACCEPT [34:2344]
:POSTROUTING ACCEPT [11:964]
:AWS-SNAT-CHAIN-0 - [0:0]
:AWS-SNAT-CHAIN-1 - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-6Y6IIP6RBXEPDSBX - [0:0]
:KUBE-SEP-LDXQARC4UTRIKNBI - [0:0]
:KUBE-SEP-MGHZ2SHFN3EAO62S - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -m comment --comment "AWS SNAT CHAN" -j AWS-SNAT-CHAIN-0
-A AWS-SNAT-CHAIN-0 ! -d 10.0.0.0/16 -m comment --comment "AWS SNAT CHAN" -j AWS-SNAT-CHAIN-1
-A AWS-SNAT-CHAIN-1 -m comment --comment "AWS, SNAT" -m addrtype ! --dst-type LOCAL -j SNAT --to-source 10.0.108.4
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-6Y6IIP6RBXEPDSBX -s 10.0.91.241/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-6Y6IIP6RBXEPDSBX -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 10.0.91.241:443
-A KUBE-SEP-LDXQARC4UTRIKNBI -s 10.0.52.196/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-LDXQARC4UTRIKNBI -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 10.0.52.196:443
-A KUBE-SEP-MGHZ2SHFN3EAO62S -s 10.0.104.63/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-MGHZ2SHFN3EAO62S -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 10.0.104.63:443
-A KUBE-SERVICES -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-MGHZ2SHFN3EAO62S
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-LDXQARC4UTRIKNBI
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-6Y6IIP6RBXEPDSBX
COMMIT
# Completed on Tue Jan 15 02:19:05 2019
# Generated by iptables-save v1.4.21 on Tue Jan 15 02:19:05 2019
*filter
:INPUT ACCEPT [307:65654]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [276:36218]
:KUBE-EXTERNAL-SERVICES - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
:KUBE-SERVICES - [0:0]
-A INPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A OUTPUT -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-SERVICES -d 10.0.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Tue Jan 15 02:19:05 2019
```
