### ISSUE TITLE
kubeScheduler usePolicyConfigmap no longer working with kops 11

### ISSUE THREAD

**Issue by gwohletz** [kubernetes/kops#6353]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.6

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops replace ; kops update cluster

**5. What happened after the commands executed?**
kops upgraded cluster to 1.11.6, but the scheduler no longer runs with the required arguments to use the configmap

**6. What did you expect to happen?**
schedule continues to run with the arguments as it did with 1.10

**7. Please provide your cluster manifest. Execute
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: XXX
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["autoscaling:DescribeTags"],
          "Resource": ["*"]
        }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    environment: PROD
    kubernetes: ""
  cloudProvider: aws
  clusterDNSDomain: cluster.local
  configBase: XXX
  dnsZone: XXX
  docker:
    registryMirrors:
    - XXX
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2-a
      kmsKeyId: XXX
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2-b
      kmsKeyId: XXX
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2-c
      kmsKeyId: XXX
      name: c
    name: main
    version: 3.2.18
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2-a
      kmsKeyId: XXX
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2-b
      kmsKeyId: XXX
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2-c
      kmsKeyId: XXX
      name: c
    name: events
    version: 3.2.18
  hooks:
  - manifest: |
      [Unit]
      Description=Allow iptables forwarding

      [Service]
      Type=oneshot
      ExecStart=/sbin/iptables -P FORWARD ACCEPT

      [Install]
      WantedBy=multi-user.target
    name: iptables-forward.service
  iam:
    legacy: false
  kubeAPIServer:
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - NodeRestriction
    - Priority
    - ResourceQuota
    - PodSecurityPolicy
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    anonymousAuth: true
    oidcClientID: XXX
    oidcIssuerURL: XXX
    oidcUsernameClaim: XXX
  kubeScheduler: {}
  kubelet:
    anonymousAuth: false
    enforceNodeAllocatable: pods
    kubeReserved:
      cpu: 125m
      memory: 512Mi
    systemReserved:
      cpu: 125m
      memory: 512Mi
  kubernetesApiAccess:
  - XXX
  kubernetesVersion: 1.11.6
  networkCIDR: XXX
  networkID: XXX
  networking:
    canal: {}
  nonMasqueradeCIDR: XXX
  serviceClusterIPRange: XXX
  sshAccess:
  - XXX
  sshKeyName: XXX
  subnets:

[subnets elided]

[ instance groups elided ]

```

For reasons that are unclear dumping the cluster manifest does not output
```
  kubeScheduler:
    usePolicyConfigmap: true
```
even though this is present in the yaml file i loaded with kops replace

This had been working fine with kops 10

As a result the scheduler yaml is missing the needed arguments to tell it to load the scheduler config map, and as such the configmap is ignored and the default scheduler policy is used instead

to be clear the yaml l load with kops replace looks like this

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: XXX
spec: 
  api:    
    dns: {}
  docker: 
    registryMirrors:
    - XXX
  kubernetesApiAccess:
    - XXX
  kubeScheduler:
    usePolicyConfigmap: true
  kubeAPIServer:
[rest of yaml elided]
```
but when i run "kops get" while i see most of my yaml i dont see the kubeScheduler section

also, not surprisingly, the kubeScheduler section is missing from cluster.spec on the s3 bucket as well.
