### ISSUE TITLE
error listing DNS zones: Throttling: Rate exceeded

### ISSUE THREAD

**Issue by walkafwalka** [kubernetes/kops#6366]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops update cluster
```

**5. What happened after the commands executed?**

```
error listing DNS zones: Throttling: Rate exceeded
        status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**6. What did you expect to happen?**

Creation or update of cloud resources to match cluster desired configuration.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-12-28T08:31:06Z
  name: REDACTED
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets"
          ],
          "Resource": [
            "*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "s3:CreateBucket",
            "s3:DeleteObject",
            "s3:Put*",
            "s3:Get*",
            "s3:List*"
          ],
          "Resource": [
            "arn:aws:s3:::*"
          ]
        }
      ]
  api:
    loadBalancer:
      sslCertificate: REDACTED
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: REDACTED
  dnsZone: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterInternalName: REDACTED
  masterPublicName: REDACTED
  networkCIDR: 192.168.0.0/16
  networkID: REDACTED
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 192.168.16.0/20
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: 192.168.32.0/20
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: 192.168.48.0/20
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-28T08:31:06Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-28T08:31:06Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-28T08:31:06Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-28T08:31:06Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

```
...
I0119 13:29:09.998860   17032 s3fs.go:220] Reading file "s3://REDACTED"
I0119 13:29:10.013119   17032 route53.go:53] AWS request: route53 ListHostedZones
I0119 13:29:11.052885   17032 route53.go:53] AWS request: route53 ListHostedZones
I0119 13:29:13.039037   17032 route53.go:53] AWS request: route53 ListHostedZones
I0119 13:29:16.607735   17032 route53.go:53] AWS request: route53 ListHostedZones

error listing DNS zones: Throttling: Rate exceeded
        status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**9. Anything else do we need to know?**

The error is intermittent however Route 53 API Requests are allowed up to 5 requests per second. According to the logs, it does not look like this is happening.

Possibly related: https://github.com/kubernetes/kops/issues/1376
