### ISSUE TITLE
Enabling etcd-manager breaks etcd

### ISSUE THREAD

**Issue by juris** [kubernetes/kops#6376]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.11.0
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I'm using kops since version 1.6, so I'm still on etcd2. This time I tried to enable etcd-manager as described in [the docs](https://github.com/kubernetes/kops/blob/master/docs/etcd/manager.md).

It failed initially because of #6311. So I set etcd version to 2.2.1 explicitly and then enabled etcd-manager with
`kops set cluster "cluster.spec.etcdClusters[*].manager.image=kopeio/etcd-manager:latest"`

Later on I started to restart master nodes one by one:
```
kops rolling-update cluster f3-dev.k8s.local --instance-group master-us-east-1a --yes
kops rolling-update cluster f3-dev.k8s.local --instance-group master-us-east-1b --yes
kops rolling-update cluster f3-dev.k8s.local --instance-group master-us-east-1c --yes
```

**5. What happened after the commands executed?**

Two first master restarts went fine. I was able to validate etcd health with etcdctl cluster-health.

This is how it looked after master A went up with etcd-manager:
```
etcdctl cluster-health
member 22ffec229227f838 is healthy: got healthy result from http://etcd-c.internal.f3-dev.k8s.local:4001
member 79c0787284ca5bc1 is healthy: got healthy result from http://0.0.0.0:4001
member e67333250905a5e9 is healthy: got healthy result from http://etcd-b.internal.f3-dev.k8s.local:4001
```

This is how it looked after master B went up with etcd-manager:
```
etcdctl cluster-health
member 22ffec229227f838 is healthy: got healthy result from http://etcd-c.internal.f3-dev.k8s.local:4001
member 79c0787284ca5bc1 is healthy: got healthy result from http://0.0.0.0:4001
member e67333250905a5e9 is healthy: got healthy result from http://0.0.0.0:4001
```

And after last master went down for replacement, something terrible happened:
```
etcdctl cluster-health
failed to check the health of member 22ffec229227f838 on http://etcd-c.internal.f3-dev.k8s.local:4001: Get http://etcd-c.internal.f3-dev.k8s.local:4001/health: dial tcp 10.113.107.41:4001: i/o timeout
member 22ffec229227f838 is unreachable: [http://etcd-c.internal.f3-dev.k8s.local:4001] are all unreachable
member 79c0787284ca5bc1 is unhealthy: got unhealthy result from http://0.0.0.0:4001
member e67333250905a5e9 is unhealthy: got unhealthy result from http://0.0.0.0:4001
```

Now I'm seeing this in etcd-manager logs:
```
I0122 16:58:49.207625    1744 controller.go:318] spec member_count:3 etcd_version:"2.2.1"
I0122 16:58:49.207905    1744 controller.go:432] controller loop complete
2019-01-22 16:58:49.771440 I | raft: 79c0787284ca5bc1 is starting a new election at term 925
2019-01-22 16:58:49.771475 I | raft: 79c0787284ca5bc1 became candidate at term 926
2019-01-22 16:58:49.771481 I | raft: 79c0787284ca5bc1 received vote from 79c0787284ca5bc1 at term 926
2019-01-22 16:58:49.771491 I | raft: 79c0787284ca5bc1 [logterm: 530, index: 108691385] sent vote request to 22ffec229227f838 at term 926
2019-01-22 16:58:49.771500 I | raft: 79c0787284ca5bc1 [logterm: 530, index: 108691385] sent vote request to e67333250905a5e9 at term 926
2019-01-22 16:58:50.284602 E | etcdhttp: got unexpected response error (etcdserver: request timed out)
2019-01-22 16:58:50.287406 E | etcdhttp: got unexpected response error (etcdserver: request timed out)
2019-01-22 16:58:50.971567 I | raft: 79c0787284ca5bc1 is starting a new election at term 926
2019-01-22 16:58:50.971638 I | raft: 79c0787284ca5bc1 became candidate at term 927
2019-01-22 16:58:50.971656 I | raft: 79c0787284ca5bc1 received vote from 79c0787284ca5bc1 at term 927
2019-01-22 16:58:50.971685 I | raft: 79c0787284ca5bc1 [logterm: 530, index: 108691385] sent vote request to 22ffec229227f838 at term 927
2019-01-22 16:58:50.971713 I | raft: 79c0787284ca5bc1 [logterm: 530, index: 108691385] sent vote request to e67333250905a5e9 at term 927
2019-01-22 16:58:51.167942 E | etcdhttp: got unexpected response error (etcdserver: request timed out)
```

Moreover, `/etc/hosts` file got duplicate records for etcd-[a,b,c] hosts:
```
# Begin host entries managed by kops - do not edit
10.113.76.226	etcd-b.internal.f3-dev.k8s.local etcd-events-b.internal.f3-dev.k8s.local
10.113.62.225	etcd-a.internal.f3-dev.k8s.local etcd-events-a.internal.f3-dev.k8s.local
10.113.107.41	api.internal.f3-dev.k8s.local etcd-c.internal.f3-dev.k8s.local etcd-events-c.internal.f3-dev.k8s.local
10.113.45.139	api.internal.f3-dev.k8s.local
10.113.94.237	api.internal.f3-dev.k8s.local
# End host entries managed by kops

# Begin host entries managed by etcd-manager[etcd-events] - do not edit
10.113.100.181	etcd-events-c.internal.f3-dev.k8s.local
10.113.45.139	etcd-events-a.internal.f3-dev.k8s.local
10.113.94.237	etcd-events-b.internal.f3-dev.k8s.local
# End host entries managed by etcd-manager[etcd-events]

# Begin host entries managed by etcd-manager[etcd] - do not edit
10.113.100.181	etcd-c.internal.f3-dev.k8s.local
10.113.45.139	etcd-a.internal.f3-dev.k8s.local
10.113.94.237	etcd-b.internal.f3-dev.k8s.local
# End host entries managed by etcd-manager[etcd]
```

For example `etcd-a.internal.f3-dev.k8s.local` has both, old and the new addresses listed:
```
grep etcd-a.internal.f3-dev.k8s.local /etc/hosts
10.113.62.225	etcd-a.internal.f3-dev.k8s.local etcd-events-a.internal.f3-dev.k8s.local
10.113.45.139	etcd-a.internal.f3-dev.k8s.local
```

The same applies to other masters.

**6. What did you expect to happen?**
I expected etcd-manager to be up and running and managing my etcd v2.2.1.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-04-05T12:11:29Z
  name: f3-dev.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    env: dev
    project: f3
  cloudProvider: aws
  configBase: s3://___/____
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    manager:
      image: kopeio/etcd-manager:latest
    name: main
    version: 2.2.1
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    manager:
      image: kopeio/etcd-manager:latest
    name: events
    version: 2.2.1
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 10.113.0.0/16
  - 10.0.0.10/32
  - 10.0.16.10/32
  kubernetesVersion: 1.11.6
  masterInternalName: api.internal.f3-dev.k8s.local
  masterPublicName: api.f3-dev.k8s.local
  networkCIDR: 10.113.0.0/16
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.113.0.0/16
  - 10.0.0.10/32
  - 10.0.16.10/32
  subnets:
  - cidr: 10.113.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.113.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.113.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.113.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.113.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.113.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-05T12:11:29Z
  labels:
    kops.k8s.io/cluster: f3-dev.k8s.local
  name: master-us-east-1a
spec:
  image: ami-0ce9569c6a8b20bb0
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-05T12:11:29Z
  labels:
    kops.k8s.io/cluster: f3-dev.k8s.local
  name: master-us-east-1b
spec:
  image: ami-0ce9569c6a8b20bb0
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-05T12:11:30Z
  labels:
    kops.k8s.io/cluster: f3-dev.k8s.local
  name: master-us-east-1c
spec:
  image: ami-0ce9569c6a8b20bb0
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-05T12:11:30Z
  labels:
    kops.k8s.io/cluster: f3-dev.k8s.local
  name: nodes
spec:
  image: ami-0ce9569c6a8b20bb0
  machineType: r5.xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-05T15:14:39Z
  labels:
    kops.k8s.io/cluster: f3-dev.k8s.local
  name: nodes-util-1a
spec:
  image: ami-0ce9569c6a8b20bb0
  machineType: r5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-util-1a
  role: Node
  subnets:
  - us-east-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
