### ISSUE TITLE
kops toolbox template: Incorrect interpolation of arrays from values yaml

### ISSUE THREAD

**Issue by cheeseandcereal** [kubernetes/kops#6377]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

    Version 1.11.0

**2. What commands did you run?  What is the simplest way to reproduce this issue?**

    kops toolbox template --values values.yaml --template def.yaml

def.yaml:
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  kubernetesApiAccess: {{.allowedIPs}}
```
values.yaml:
```yaml
allowedIPs:
- 1.2.3.4/32
- 4.3.2.1/32
```

**3. What happened after the commands executed?**

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
spec:
  kubernetesApiAccess: [1.2.3.4/32 4.3.2.1/32]
```

**4. What did you expect to happen?**

The interpolated array in the resulting yaml should contain commas to make it a proper yaml array. The way that it's outputting the array in the interpolated outputted yaml is incorrect.

**5. Any other information?**

This also happens when using the --set or --set-string flag with an array as documented in [HERE](https://github.com/kubernetes/kops/blob/master/docs/operations/cluster_template.md), making the documentation incorrect due to this bug.
