### ISSUE TITLE
fileAssets usage for offline cluster creation

### ISSUE THREAD

**Issue by Treyone** [kubernetes/kops#6391]
kops version : 1.10.0 (current release)
k8s version : 1.10
cloud provider : AWS

I've seen a number of issues and PRs related to `fileAssets` for offline cluster creation in air-gapped, security intensive environments : https://github.com/kubernetes/kops/issues/3246, https://github.com/kubernetes/kops/issues/3645, https://github.com/kubernetes/kops/pull/2573, https://github.com/kubernetes/kops/pull/2899, https://github.com/kubernetes/kops/pull/2917, https://github.com/kubernetes/kops/issues/3246, but I can't find any documentation on how to do this. It's also mentioned in the [AWS China](https://github.com/kubernetes/kops/issues/3246) docs page as the "official way" to achieve offline mode.

I could write such guide, however, I'll need some help to make it work before I can explain how to do it. I'm going through the above PRs but is there any other resource I could use ? Does anybody know how that feature works ? @chrislovecnm maybe, who seems to ave been has been involved in this topic a lot ?

**Comment by Treyone** [comment]
Just in case someone wonders:
`fileAssets` can be used to create files on the nodes. The syntax is the following 👍 
```yaml
fileAssets:
  - content: |
    file
    content
    goes
    here      
    name: cloud-config
    path: /my/file
    roles:
    - Master
    - Node
```

`assets` can be used to set a location to get the k8s files and containers:
```yaml
  assets:
    containerRegistry: my.internal.registry
    fileRepository: http://where-to-get-files.internal
```

The registry has to have the containers that kubernetes usually pulls from `k8s.gcr.io` and the file repository must contain all files generated when building kubernetes, with sha1s (generated using `sha1sum`). Such a configuration allows an offline kubernetes installation.
