### ISSUE TITLE
out-of-tree cloudprovider support?

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#6439]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

in-tree cloudproviders are deprecated https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider That is why I am asking to add support for out-of-tree cloudproviders for kops.

**2. Feel free to provide a design supporting your feature request.**
I tried to do this already as addon. However, this cannot be implemented as addon because then it is loaded too late. This out-of-tree resource should be added as similar way like kube-apiserver or controller-manager in `nodeup/pkg/model`. Openstack do have working out-of-tree provider https://github.com/kubernetes/cloud-provider-openstack which have more features than in-tree one.

I have used out-of-tree controller as deployed to each master like currently (kube-apiserver and controller-manager) manifests are deployed. 

Example:
```
apiVersion: v1
kind: Pod
metadata:
  name: openstack-cloud-controller-manager
  namespace: kube-system
spec:
  securityContext:
    runAsUser: 1001
  hostNetwork: true
  containers:
  - name: openstack-cloud-controller-manager
    image: jesseh/occm:latest
    args:
      - /bin/openstack-cloud-controller-manager
      - --v=2
      - --cloud-config=/etc/kubernetes/cloud.config
      - --cloud-provider=openstack
      - --master=http://127.0.0.1:8080
    volumeMounts:
    - mountPath: /etc/kubernetes/cloud.config
      name: cloudconfig
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/cloud.config
    name: cloudconfig
```
