### ISSUE TITLE
Kops upgrade to 1.11 - There were unauthenticated packages

### ISSUE THREAD

**Issue by nisan270390** [kubernetes/kops#6443]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
kops 1.11.0 upgrade from 1.10.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops upgrade cluster $NAME --yes
kops update cluster $NAME --yes
kops rolling-update cluster $NAME --yes

**5. What happened after the commands executed?**
```
Feb 04 10:19:29 ip-10-0-33-213 nodeup[2528]: I0204 10:19:29.530988    2528 package.go:260] Installing package "conntrack"
Feb 04 10:19:29 ip-10-0-33-213 nodeup[2528]: I0204 10:19:29.531016    2528 package.go:309] running command [apt-get install --yes conntrack]
Feb 04 10:19:29 ip-10-0-33-213 nodeup[2528]: I0204 10:19:29.812955    2528 package.go:260] Installing package "ebtables"
Feb 04 10:19:29 ip-10-0-33-213 nodeup[2528]: I0204 10:19:29.812994    2528 package.go:309] running command [apt-get install --yes ebtables]
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: W0204 10:19:30.050192    2528 executor.go:130] error running task "Package/ebtables" (7m10s remaining to succeed): error i
nstalling package "ebtables": exit status 100: Reading package lists...
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: Building dependency tree...
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: Reading state information...
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: The following NEW packages will be installed:
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]:   ebtables
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: 0 upgraded, 1 newly installed, 0 to remove and 53 not upgraded.
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: Need to get 85.5 kB of archives.
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: After this operation, 359 kB of additional disk space will be used.
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: WARNING: The following packages cannot be authenticated!
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]:   ebtables
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: W0204 10:19:30.050236    2528 executor.go:130] error running task "Package/conntrack" (7m10s remaining to succeed): error
installing package "conntrack": exit status 100: Reading package lists...
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: Building dependency tree...
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: Reading state information...
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: The following NEW packages will be installed:
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]:   conntrack
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: 0 upgraded, 1 newly installed, 0 to remove and 53 not upgraded.
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: Need to get 32.9 kB of archives.
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: After this operation, 104 kB of additional disk space will be used.
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: WARNING: The following packages cannot be authenticated!
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]:   conntrack
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Feb 04 10:19:30 ip-10-0-33-213 nodeup[2528]: I0204 10:19:30.050251    2528 executor.go:145] No progress made, sleeping before retrying 2 failed task(s)
```

**6. What did you expect to happen?**
clean upgrade to 1.11

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-12-24T14:42:00Z
  name: staging1.k8s.XXXXX.com
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Environment: staging
    ManagedBy: kops
    k8s.io/cluster-autoscaler/enabled: ""
    kubernetes.io/cluster/staging1.k8s.XXXXX.com: owned
  cloudProvider: aws
  configBase: s3://clusters.k8s.XXXXX.com/staging1.k8s.XXXXX.com
  dnsZone: k8s.XXXXX.com
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
    version: 3.3.10
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
    version: 3.3.10
  fileAssets:
  - content: |
      [Service]
      CPUAccounting=true
      MemoryAccounting=true
      Slice=kube-reserved.slice
    name: kubelet-cgroup
    path: /etc/systemd/system/kubelet.service.d/11-cgroups.conf
    roles:
    - Master
    - Node
  - content: |
      [Service]
      CPUAccounting=true
      MemoryAccounting=true
      Slice=kube-reserved.slice
    name: docker-cgroup
    path: /etc/systemd/system/docker.service.d/11-cgroups.conf
    roles:
    - Master
    - Node
  - content: |
      [Unit]
      Description=Limited resources slice for Kubernetes services
      Documentation=man:systemd.special(7)
      DefaultDependencies=no
      Before=slices.target
      Requires=-.slice
      After=-.slice
    name: podruntime-slice
    path: /usr/lib/systemd/system/kube-reserved.slice
    roles:
    - Master
    - Node
  - content: |
      apiVersion: audit.k8s.io/v1alpha1
      kind: Policy
      rules:
        # The following requests were manually identified as high-volume and low-risk,
        # so drop them.
        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
            - group: "" # core
              resources: ["endpoints", "services"]
        - level: None
          # Ingress controller reads `configmaps/ingress-uid` through the unsecured port.
          # TODO(#46983): Change this to the ingress controller service account.
          users: ["system:unsecured"]
          namespaces: ["kube-system"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["configmaps"]
        - level: None
          users: ["kubelet"] # legacy kubelet identity
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["nodes"]
        - level: None
          userGroups: ["system:nodes"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["nodes"]
        - level: None
          users:
            - system:kube-controller-manager
            - system:kube-scheduler
            - system:serviceaccount:kube-system:endpoint-controller
          verbs: ["get", "update"]
          namespaces: ["kube-system"]
          resources:
            - group: "" # core
              resources: ["endpoints"]
        - level: None
          users: ["system:apiserver"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["namespaces"]

        # Don't log these read-only URLs.
        - level: None
          nonResourceURLs:
            - /healthz*
            - /version
            - /swagger*

        # Don't log events requests.
        - level: None
          resources:
            - group: "" # core
              resources: ["events"]

        # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
        # so only log at the Metadata level.
        - level: Metadata
          resources:
            - group: "" # core
              resources: ["secrets", "configmaps"]
            - group: authentication.k8s.io
              resources: ["tokenreviews"]

        # Get repsonses can be large; skip them.
        - level: Metadata
          verbs: ["get", "list", "watch"]
          resources:
            - group: "" # core
            - group: "admissionregistration.k8s.io"
            - group: "apps"
            - group: "authentication.k8s.io"
            - group: "authorization.k8s.io"
            - group: "autoscaling"
            - group: "batch"
            - group: "certificates.k8s.io"
            - group: "extensions"
            - group: "networking.k8s.io"
            - group: "policy"
            - group: "rbac.authorization.k8s.io"
            - group: "settings.k8s.io"
            - group: "storage.k8s.io"

        # Default level for known APIs
        - level: Metadata
          resources:
            - group: "" # core
            - group: "admissionregistration.k8s.io"
            - group: "apps"
            - group: "authentication.k8s.io"
            - group: "authorization.k8s.io"
            - group: "autoscaling"
            - group: "batch"
            - group: "certificates.k8s.io"
            - group: "extensions"
            - group: "networking.k8s.io"
            - group: "policy"
            - group: "rbac.authorization.k8s.io"
            - group: "settings.k8s.io"
            - group: "storage.k8s.io"

        # Default level for all other requests.
        - level: Metadata
    name: apiserver-audit-policy
    path: /srv/kubernetes/audit.yaml
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    oidcClientID: XXXXXXX
    oidcGroupsClaim: groups
    oidcGroupsPrefix: 'okta:'
    oidcIssuerURL: XXXXXXXX
    oidcUsernameClaim: preferred_username
    oidcUsernamePrefix: 'okta:'
    runtimeConfig:
      admissionregistration.k8s.io/v1alpha1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerDownscaleDelay: 5m0s
    horizontalPodAutoscalerSyncPeriod: 15s
    horizontalPodAutoscalerUpscaleDelay: 3m0s
  kubeDNS:
    provider: CoreDNS
  kubelet:
    cloudProvider: aws
    enableCustomMetrics: true
    kubeReserved:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 2Gi
    kubeReservedCgroup: /kube-reserved.slice
    systemReserved:
      cpu: 300m
      ephemeral-storage: 1Gi
      memory: 1Gi
    systemReservedCgroup: /system.slice
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterPublicName: api.staging1.k8s.XXXXX.com
  networkCIDR: 10.0.0.0/18
  networkID: XXXXXX
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/18
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: riskified
  subnets:
  - cidr: 10.0.32.0/22
    id: XXXXXXX
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.0.36.0/22
    id: XXXXXXX
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.0.40.0/22
    id: XXXXXXX
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.0.44.0/22
    id: XXXXXXX
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 10.0.48.0/22
    id: XXXXXXX
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 10.0.0.0/24
    id: XXXXXXX
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.0.1.0/24
    id: XXXXXXX
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.0.2.0/24
    id: XXXXXXX
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.0.3.0/24
    id: XXXXXXX
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 10.0.4.0/24
    id: XXXXXXX
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-24T14:42:01Z
  labels:
    kops.k8s.io/cluster: staging1.k8s.XXXXX.com
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-24T14:42:01Z
  labels:
    kops.k8s.io/cluster: staging1.k8s.XXXXX.com
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-24T14:42:01Z
  labels:
    kops.k8s.io/cluster: staging1.k8s.XXXXX.com
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-24T14:42:02Z
  labels:
    kops.k8s.io/cluster: staging1.k8s.XXXXX.com
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.4xlarge
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

**9. Anything else do we need to know?**
