### ISSUE TITLE
[INFO] DataStore has no available IP addresses 

### ISSUE THREAD

**Issue by pulpbill** [kubernetes/kops#6452]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`kops version -Version 1.10.0 (git-8b52ea6d1)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Trying to deploy more pods

**5. What happened after the commands executed?**
Pod can't start

**6. What did you expect to happen?**
Pods get ready status

**7. Please provide your cluster manifest. Execute
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-01-07T19:46:52Z
  name: asdasd
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://asdasd/asdasd
  dnsZone: asdasd
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.12
  masterPublicName: api.asdasd
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  topology:
    bastion:
      bastionPublicName: bastion.asdasd
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-07T19:46:53Z
  labels:
    kops.k8s.io/cluster: asdasd
  name: bastions
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.micro
  maxPrice: "0.005"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
    spot: "true"
  role: Bastion
  subnets:
  - utility-us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-07T19:46:52Z
  labels:
    kops.k8s.io/cluster: asdasd
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.large
  maxPrice: "0.04"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
    spot: "true"
  role: Master
  rootVolumeSize: 40
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-01-07T19:46:52Z
  labels:
    kops.k8s.io/cluster: asdasd
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.xlarge
  maxPrice: "0.19"
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    spot: "true"
  role: Node
  rootVolumeSize: 100
  subnets:
  - us-east-1a
```

**9. Anything else do we need to know?**

I'm debugging why a pod can't start. And I'm seeing this at nodes:

`2019-02-05T18:41:41Z [INFO] Send AddNetworkReply: IPv4Addr , DeviceNumber: 0, err: datastore: no available IP addresses 2019-02-05T18:41:44Z [INFO] Received AddNetwork for NS /proc/31240/ns/net, Pod some-pod-1-8f7b94b59-kvlwr, NameSpace my-ns, Container 73141b0590192774dcb0c030ef91751d0ee8763410a1c40444c4280244f17c2e, ifname eth0 2019-02-05T18:41:44Z [DEBUG] AssignIPv4Address: IP address pool stats: total:42, assigned 42 2019-02-05T18:41:44Z [DEBUG] AssignPodIPv4Address, skip ENI eni-02f3ee3be7e41030b that does not have available addresses 2019-02-05T18:41:44Z [DEBUG] AssignPodIPv4Address, skip ENI eni-09dfa333f2ccf438a that does not have available addresses 2019-02-05T18:41:44Z [DEBUG] AssignPodIPv4Address, skip ENI eni-0a1e8a193399b1e5d that does not have available addresses 2019-02-05T18:41:44Z [INFO] DataStore has no available IP addresses 2019-02-05T18:41:44Z [INFO] Send AddNetworkReply: IPv4Addr , DeviceNumber: 0, err: datastore: no available IP addresses 2019-02-05T18:41:45Z [DEBUG] IP pool stats: total = 42, used = 42, c.currentMaxAddrsPerENI = 15, c.maxAddrsPerENI = 15 2019-02-05T18:41:45Z [DEBUG] Start increasing IP Pool size 2019-02-05T18:41:45Z [DEBUG] Skipping increase IPPOOL due to max ENI already attached to the instance : 3`

It's a new cluster I'm testing on AWS deployed via kops and using helm charts. I have 2x t2.2xlarge, master is t2.large and bastion t2.micro. The instances are in a VPC. I can see that one of the instances has 3 ENI attached and the other just 2.

Nodes has :
PodCIDR: 172.20.141.0/24
PodCIDR: 172.20.140.0/24
Master:
PodCIDR: 172.20.129.0/24

Any thoughts? Thank you!
