### ISSUE TITLE
Can't enable ETCD TLS auth

### ISSUE THREAD

**Issue by abhyuditjain** [kubernetes/kops#6455]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.13.3

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster $NAME \
--api-loadbalancer-type public \
--topology private \
--encrypt-etcd-storage=true \
--api-ssl-certificate "<ARN>" \
--zones "ap-south-1b,ap-south-1a" \
--ssh-public-key ~/.ssh/cluster.pub \
--master-count 1 \
--master-size t2.medium \
--master-volume-size 30 \
--node-count 2 \
--node-size t2.small \
--authorization "RBAC" \
--kubernetes-version "1.13.3" \
--node-volume-size 30 \
--yes \
--image ami-092e1fd695ed0e93c \
--networking calico 
```

```
kops edit cluster
```

Then added `enableEtcdTLS: true` and `version: 3.2.26` to ETCD cluster.

Then ran:
```
kops update cluster
```

**5. What happened after the commands executed?**
This error was shown:
```
Using cluster from kubectl context: cluster.k8s.local

I0208 19:12:44.623415   27508 apply_cluster.go:542] Gossip DNS: skipping DNS validation

error building tasks: TLS not supported for etcd-manager
```

**6. What did you expect to happen?**
Successful update

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-08T13:35:44Z
  name: cluster.k8s.local
spec:
  api:
    loadBalancer:
      sslCertificate: <ARN>
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cluster-state-store/cluster.k8s.local
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1b
      name: b
    name: main
    version: 3.2.26
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1b
      name: b
    name: events
    version: 3.2.26
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.3
  masterInternalName: api.internal.cluster.k8s.local
  masterPublicName: api.cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      crossSubnet: true
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Private
    zone: ap-south-1a
  - cidr: 172.20.64.0/19
    name: ap-south-1b
    type: Private
    zone: ap-south-1b
  - cidr: 172.20.0.0/22
    name: utility-ap-south-1a
    type: Utility
    zone: ap-south-1a
  - cidr: 172.20.4.0/22
    name: utility-ap-south-1b
    type: Utility
    zone: ap-south-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-08T13:35:44Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-ap-south-1b
spec:
  image: ami-092e1fd695ed0e93c
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1b
  role: Master
  rootVolumeSize: 30
  subnets:
  - ap-south-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-08T13:35:44Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: nodes
spec:
  image: ami-092e1fd695ed0e93c
  machineType: t2.small
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 30
  subnets:
  - ap-south-1a
  - ap-south-1b
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by mapdegree** [comment]
You can enable TLS encryption for Kops only at cluster creation, not later. You can achieve this by exporting the kops cluster yaml first, changing it and recreate the cluster.

Please try to stick with the same versions of KOPS and kubectl.

**Comment by abhyuditjain** [comment]
@mapdegree I tried with the yaml using `kops create -f cluster.yml` but I get the same error message. Here's the yaml:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-06T05:04:34Z
  name: cluster.k8s.local
spec:
  api:
    loadBalancer:
      sslCertificate: <ARN>
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cluster-state-store/cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1b
      name: b
    name: main
    enableEtcdTLS: true
    version: 3.2.26
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1b
      name: b
    name: events
    enableEtcdTLS: true
    version: 3.2.26
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.3
  masterPublicName: api.cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Private
    zone: ap-south-1a
  - cidr: 172.20.64.0/19
    name: ap-south-1b
    type: Private
    zone: ap-south-1b
  - cidr: 172.20.0.0/22
    name: utility-ap-south-1a
    type: Utility
    zone: ap-south-1a
  - cidr: 172.20.4.0/22
    name: utility-ap-south-1b
    type: Utility
    zone: ap-south-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-06T05:04:34Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-ap-south-1b
spec:
  image: ami-092e1fd695ed0e93c
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1b
  role: Master
  rootVolumeSize: 30
  subnets:
  - ap-south-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-06T05:04:34Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: nodes
spec:
  image: ami-092e1fd695ed0e93c
  machineType: t2.small
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 30
  subnets:
  - ap-south-1a
  - ap-south-1b
```

The error I get:

```
I0211 11:11:13.841852    7276 apply_cluster.go:542] Gossip DNS: skipping DNS validation

error building tasks: TLS not supported for etcd-manager
```
