### ISSUE TITLE
Docker Vulnerability CVE-2019-5736

### ISSUE THREAD

**Issue by jjo** [kubernetes/kops#6459]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops-1.11

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

N/A

**5. What happened after the commands executed?**

N/A

**6. What did you expect to happen?**

kops should default to non-vulnerable docker-ce versions

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

[docker.go](https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/docker.go) `dockerVersions` array contains urls for vulnerable docker-ce packages,
unfortunately as of 2019-02-11 the only `docker-ce` fixed package for CVE-2019-5736 is
`docker-ce_18.09.2~3-0~debian-stretch_amd64` [1][2] (17.x and other 18.x
packages fixed only for `docker-ee` releases) -- this is particularly problematic
as current `docker.go` has no `18.09.x` entry.

[1] https://docs.docker.com/engine/release-notes/#18062
[2] https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/

**Comment by jjo** [comment]
A 18.06.2 update seems to have appeared at [1][2] a few minutes ago,
now there are updated packages dated 2019-02-11 ~18:11 from download.docker.com:

* Centos: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.2.ce-3.el7.x86_64.rpm
* Debian Stretch: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.06.2~ce~3-0~debian_amd64.deb
* Ubuntu Bionic: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.06.2~ce~3-0~debian_amd64.deb

**Comment by mikesplainsonos** [comment]
Thanks for diving into this @jjo

**Comment by mikesplain** [comment]
Thanks for diving into this @jjo

**Comment by eyalzek** [comment]
The fix has also been back ported to `17.06.2-ee-19` and `18.03.1-ee-6`. Can we add supports for these versions as well? I don't necessarily want to perform a major upgrade just for this fix. On another note, is it possible to do this ATM without kops "officially" supporting a version? From what I can see in the source code, it's impossible - but there might be ways around it?

**Comment by mikesplain** [comment]
As mentioned in the PR just now, I don't think we can support those since they're enterprise versions. I don't think they've patched older community editions, unless anyone else has been able to find them?

**Comment by 3h4x** [comment]
I've just tested using patched binary from `rancher` -> https://github.com/rancher/runc-cve
Is replacing `docker-runc` binary something that `kops` could do during bootstrapping?

**Comment by 3h4x** [comment]
PR related https://github.com/kubernetes/kops/pull/6460

**Comment by gaganapplatix** [comment]
is the new rancher binary for older versions of docker (specifically 17.03.2-ce) going to be supported (https://github.com/kubernetes/kops/issues/6459#issuecomment-462773115) or should we start testing with 18.06.2-ce for our clusters (considering we were still on the supported 17.03 versions before)?

**Comment by captainkerk** [comment]
@3h4x I'm also interested in just patching the docker-runc binary.

I'm using a kops hook to update the docker-runc binary at boot: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks

Kops hooks can take systemd unit file, the hook (in the cluster spec file) looks like:
```
  hooks:
  - name: patch-runc.service
    manifest: |
      [Unit]
      Description=install rancher docker-runc
      Before=docker.service
      DefaultDependencies=no
      [Service]
      ExecStart=/bin/bash -c "wget https://github.com/rancher/runc-cve/releases/download/CVE-2019-5736-build2/runc-v17.03.2-amd64 && mv runc-v17.03.2-amd64 /usr/bin/docker-runc && chmod +x /usr/bin/docker-runc && docker-runc --version && echo done"
      [Install]
      WantedBy=basic.target
```

I haven't quite flushed out the details, but I think the main thing is just to set that hook to run before the docker service. Hope that helps!

**Comment by HagaiBarel** [comment]
@captainkerk I'm doing something similar, and can confirm it works as expected. My hook looks like this - 

```yaml
  hooks:
  #temp fix for CVE-2019-5736 until kops add support for it
  #ref: https://github.com/rancher/runc-cve
  #we run busybox at the last step as sanity test
  - name: patch-runc
    roles:
    - Node
    - Master
    before:
    - docker.service
    manifest: |
      Type=oneshot
      ExecStart=mv /usr/bin/docker-runc /usr/bin/docker-runc.orig
      ExecStart=curl -Lo /usr/bin/docker-runc https://github.com/rancher/runc-cve/releases/download/CVE-2019-5736-build2/runc-v17.03.1-amd64
      ExecStart=chmod +x /usr/bin/docker-runc
      ExecStart=docker run --rm busybox echo ok
```

Comparing `sha256` after the hook runs, verifies that the patched `runc` version is indeed the one present. Tested on `ubuntu 18.04` AMI on AWS, kops 1.11
