### ISSUE TITLE
Can't create cluster in existing AWS VPC with multiple CIDRs

### ISSUE THREAD

**Issue by idanya** [kubernetes/kops#6462]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Created a cluster.yaml and ig.yaml 
`kops create -f cluster.yaml`
`kops create -f ig.yaml`

Then, update the cluster with
`kops update cluster`

**5. What happened after the commands executed?**

Getting an error: 
`error running task "VPC/<cluster name>" (9m46s remaining to succeed): CIDR: Invalid value: "10.44.0.0/16": field is immutable: old="10.42.0.0/16" new="10.44.0.0/16"`

**6. What did you expect to happen?**
Update to succeed

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-01-23T07:46:54Z
  name: <cluster name>
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Business Unit: <unit>
    Service Role: k8s
  cloudProvider: aws
  configBase: s3://path/<cluster name>
  docker:
    storage: overlay2,overlay,aufs
    version: 18.06.1
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    clusterCIDR: 10.44.0.0/16
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    clusterCIDR: 10.44.0.0/16
  kubelet:
    anonymousAuth: true
    cloudProvider: aws
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterInternalName: api.internal.<cluster name>
  masterPublicName: api.<cluster name>
  networkCIDR: 10.44.0.0/16
  additionalNetworkCIDRs:
  - 10.42.0.0/16 --> This is the default CIDR of the VPC
  - 10.43.0.0/16
  networkID: <existing VPC id with 3 CIDRS>
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.44.0.0/16
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: mc-key
  subnets:
  - cidr: 10.44.32.0/19
    id: <subnet id>
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.44.64.0/19
    id: <subnet id>
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.44.96.0/19
    id: <subnet id>
    name: us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
I0213 11:34:52.367294   12648 request_logger.go:45] AWS request: ec2/DescribeVpcs
I0213 11:34:52.554382   12648 vpc.go:85] found matching VPC *awstasks.VPC {"Name":"<vpc name>","Lifecycle":null,"ID":"<vpc id>","CIDR":"10.42.0.0/16","EnableDNSHostnames":null,"EnableDNSSupport":null,"Shared":null,"Tags":null}
I0213 11:34:52.554570   12648 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I0213 11:34:52.732355   12648 request_logger.go:45] AWS request: ec2/DescribeVpcAttribute
I0213 11:34:52.919233   12648 changes.go:81] Field changed "CIDR" actual="10.42.0.0/16" expected="10.44.0.0/16"
W0213 11:34:52.919310   12648 executor.go:130] error running task "VPC/<cluster name>" (9m57s remaining to succeed): CIDR: Invalid value: "10.44.0.0/16": field is immutable: old="10.42.0.0/16" new="10.44.0.0/16"
```
**9. Anything else do we need to know?**
Trying to create a cluster in a multi CIDR VPC where the default CIDR is not the one which the cluster should run on.
Looks like kops wants to run the cluster on the main CIDR and doesn't accept the second or third CIDR as it's network range. 
I've added `additionalNetworkCIDRs` as some other issues suggested but that did not change anything, same error occurs with or without this field.
