### ISSUE TITLE
Kops tries to delete bastion IAM resources it doesn't own if their names match

### ISSUE THREAD

**Issue by geekofalltrades** [kubernetes/kops#6466]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

N/A

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops delete cluster --yes`

Repro:
1. Create a kops cluster named with private topology **without** the `--bastion` flag, so Kops should not create any bastion resources.
2. Create an IAM role and instance profile called `bastions.<cluster-name>` in the same account as the Kops cluster.
3. Delete the Kops cluster.

**5. What happened after the commands executed?**

Kops attempts to delete the IAM role and instance profile, even though it didn't create them.

**6. What did you expect to happen?**

Kops should not attempt to delete resources that aren't associated with the cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-13T21:12:13Z
  name: <cluster-name>
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: <state>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a-1
      name: "1"
    - instanceGroup: master-us-west-2a-2
      name: "2"
    - instanceGroup: master-us-west-2a-3
      name: "3"
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-us-west-2a-1
      name: "1"
    - instanceGroup: master-us-west-2a-2
      name: "2"
    - instanceGroup: master-us-west-2a-3
      name: "3"
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - <our-ip>
  kubernetesVersion: 1.11.7
  masterPublicName: api.<cluster-name>
  networkCIDR: 10.230.0.0/16
  networkID: vpc-00f9acb44629207b8
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - <our-ip>
  subnets:
  - cidr: 10.230.32.0/19
    id: subnet-09217e48294daf497
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.230.0.0/22
    id: subnet-0d19f0c95defc126b
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

When the cluster is created, but not applied with --yes, and I try to delete it, I get this (the bastion resources already exist separately):
```
$ kops delete cluster <cluster-name> --yes
TYPE			NAME				ID
iam-instance-profile	bastions.<cluster-name>	bastions.<cluster-name>
iam-role		bastions.<cluster-name>	bastions.<cluster-name>
```

**9. Anything else do we need to know?**

I've been working on moving our clusters to shared VPC and shared subnets, because it makes more sense for our infrastructure. As part of that change, it made sense to also remove the bastion from Kops management. That way, if we had to recreate the cluster at any point, we wouldn't lose bastion access to the rest of the shared VPC. To minimize the diff of this move, I tried to reuse the same names on the bastion resources as Kops would have - but then, when I deleted a cluster, Kops tried to delete some of the bastion resources.

It looks like Kops does not tag the bastion iam role or instance profile it creates in any way; it just tries to match them on name only to decide if they belong to it.

I'll work around this issue by using different names for our non-Kops bastion resources.
