### ISSUE TITLE
kube-state-metrics addon uses wrong API version for CronJobs

### ISSUE THREAD

**Issue by imsky** [kubernetes/kops#6474]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 1.9.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** 1.9.10

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?** Created a kops cluster with kube-state-metrics addon.

**5. What happened after the commands executed?** kube-state-metrics logged the following:

> E0215 17:16:06.850345       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/cronjob.go:93: Failed to list *v2alpha1.CronJob: the server could not find the requested resource

**6. What did you expect to happen?** kube-state-metrics to properly inspect CronJobs, which have API version of "batch/v1beta1" - kube-state-metrics 1.4 should support this (addon deploys with 1.1)

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-14T19:54:28Z
  name: foo.example
spec:
  additionalPolicies:
    node: '[{"Action": ["sts:AssumeRole"], "Effect": "Allow", "Resource": ["*"]}]'
  addons:
  - manifest: kube-state-metrics
  - manifest: monitoring-standalone
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://bucket/foo.example
  docker:
    logDriver: json-file
    storage: overlay2
    version: 17.03.2
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: us-east-1a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: us-east-1b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: us-east-1c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: us-east-1a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: us-east-1b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: us-east-1c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 7
    auditLogMaxBackups: 4
    auditLogMaxSize: 256
    auditLogPath: /var/log/kube-apiserver-audit.log
    authorizationRbacSuperUser: admin
    cloudProvider: aws
  kubelet:
    featureGates:
      AdvancedAuditing: "true"
      ExperimentalCriticalPodAnnotation: "true"
      MountContainers: "true"
      MountPropagation: "true"
      PodPriority: "true"
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.10
  masterKubelet:
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  masterPublicName: api.foo.example
  networkCIDR: 172.1.0.0/16
  networkID: vpc-123
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.1.0.0/24
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.1.1.0/24
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.1.2.0/24
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.1.3.0/24
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.1.4.0/24
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.1.5.0/24
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.foo.example
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
