### ISSUE TITLE
Kops patch including new Docker version for CVE-2019-5736

### ISSUE THREAD

**Issue by giovadifiore** [kubernetes/kops#6476]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Are you considerding to cherry-pick [#6460](https://github.com/kubernetes/kops/pull/6460) to have a patch version of Kops for at least 1.10 and 1.11 releases?

**Comment by jeyglk** [comment]
Is it safe to use a version of docker that has not be verified on Kubernetes 1.10 / 1.11 ? This is a big risk that has been left unanswered in the PR.

**Comment by philwhln** [comment]
From @captainkerk in https://github.com/kubernetes/kops/pull/6460#issuecomment-463730763 ...

> Honestly, I think using rancher's patched docker-runc is the best way to patch for this CVE, at least until kops supports kubernetes v1.12. The solution proposed in this PR is to use a version of docker that hasnt been verified with **any** version of kubernetes that kops supports. v1.12 is the first version to support docker 18.06.
> 
> It would be nice if kops could just use rancher's patched version of docker-runc (or maybe build your own) without us having to use a hook. To me, that seems like an interesting patch vector that should be considered?

**Comment by justinsb** [comment]
We definitely need to cherry-pick something for 1.11 at least.  Our options seem to be to install an updated runc or to use a newer version of docker.  Neither is formally tested with k8s 1.11, the patched runc is probably harder but safer.

Not sure if anyone knows of a third way...

**Comment by akhmadfld** [comment]
Just share my hooks based on https://github.com/kubernetes/kops/issues/6459#issuecomment-463558952 with sha256sum check. Use it on `cluster.yml` or `kops edit cluster` under [spec](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks)

```
  hooks:
  #temp fix for CVE-2019-5736 until kops add support for it
  #ref: https://github.com/rancher/runc-cve
  #we run busybox at the last step as sanity test
  - name: patch-runc
    roles:
    - Node
    - Master
    before:
    - docker.service
    manifest: |
      Type=oneshot
      ExecStart=/bin/bash -c 'mv /usr/bin/docker-runc /usr/bin/docker-runc.orig && wget -P /tmp  https://github.com/rancher/runc-cve/releases/download/CVE-2019-5736-build3/runc-v17.03.2-amd64 && echo "25d2965a74d33e7bc7e16f6b6fef6a8c93a115d0c1027bdb792b2a57c03f2a74  /tmp/runc-v17.03.2-amd64" | sha256sum -c && chmod +x /tmp/runc-v17.03.2-amd64 && mv /tmp/runc-v17.03.2-amd64 /usr/bin/docker-runc'
```
