### ISSUE TITLE
NAT Gateways not recreated after deleted

### ISSUE THREAD

**Issue by ivnilv** [kubernetes/kops#6518]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.0 (git-2c2042465)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Deleted NAT gateways created (and tagged) by KOPS in 3 AZ, from the AWS console.

Then ran the `kops update cluster` command, in hopes that it will see the difference and recreate the NAT gateways.

**5. What happened after the commands executed?**

It didnt see any differences...

**6. What did you expect to happen?**

Expected KOPS to recreate the NAT gateways as they were provisioned by the tool itself.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-08T11:13:49Z
  name: REDACTED.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://REDACTED/REDACTED.k8s.local
  docker:
    version: 18.03.1
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterInternalName: api.internal.REDACTED.k8s.local
  masterPublicName: api.REDACTED.k8s.local
  networkCIDR: 172.20.0.0/16
  networkID: vpc-0df2d9d87afd2fd4b
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.20.96.0/19
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.20.0.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.20.4.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.20.8.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-08T11:13:49Z
  labels:
    kops.k8s.io/cluster: REDACTED.k8s.local
  name: master-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190122
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-08T11:13:49Z
  labels:
    kops.k8s.io/cluster: REDACTED.k8s.local
  name: master-eu-central-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190122
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-08T11:13:49Z
  labels:
    kops.k8s.io/cluster: REDACTED.k8s.local
  name: master-eu-central-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190122
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-08T11:13:49Z
  labels:
    kops.k8s.io/cluster: REDACTED.k8s.local
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190210
  machineType: t3.small
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```
