### ISSUE TITLE
LoadBalancer service targets removed when performing rolling-update on master

### ISSUE THREAD

**Issue by saidmasoud** [kubernetes/kops#6537]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** 

```sh
$ kops version
Version 1.10.0 (git-8b52ea6d1)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```sh
kubectl create -f <see below files>
kops edit cluster <cluster name>
# added the following:
authentication:
     aws: {}
kubeAPIServer:
               authenticationTokenWebhookConfigFile: /etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml

:wq

kops update cluster <cluster name> –-yes
kops rolling-update cluster <cluster name> –-instance-group-roles=Master –-force –-yes
```

auth-cm.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-iam-authenticator
  labels:
    k8s-app: aws-iam-authenticator
data:
  config.yaml: |
    clusterID: k8s.preprod.remine.com
    server:
      mapRoles: 
      - rolearn: <role-arn>
        username: admin-user
        groups:
        - cluster-admin
      - rolearn: <role-arn>
        username: developer-user
        groups:
        - developer

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: aws-iam-authenticator
  labels:
    k8s-app: aws-iam-authenticator
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: aws-iam-authenticator
    spec:
      # run on the host network (don't depend on CNI)
      hostNetwork: true

      # run on each master node
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists

      # run `aws-iam-authenticator server` with three volumes
      # - config (mounted from the ConfigMap at /etc/aws-iam-authenticator/config.yaml)
      # - state (persisted TLS certificate and keys, mounted from the host)
      # - output (output kubeconfig to plug into your apiserver configuration, mounted from the host)
      containers:
      - name: aws-iam-authenticator
        image: gcr.io/heptio-images/authenticator:v0.3.0
        args:
        - server
        - --config=/etc/aws-iam-authenticator/config.yaml
        - --state-dir=/var/aws-iam-authenticator
#        - --generate-kubeconfig=/etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
        - --kubeconfig-pregenerated

        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 100m

        volumeMounts:
        - name: config
          mountPath: /etc/aws-iam-authenticator/
        - name: state
          mountPath: /var/aws-iam-authenticator/
        - name: output
          mountPath: /etc/kubernetes/heptio-authenticator-aws/

      volumes:
      - name: config
        configMap:
          name: aws-iam-authenticator
      - name: output
        hostPath:
          path: /srv/kubernetes/aws-iam-authenticator/
      - name: state
        hostPath:
          path: /srv/kubernetes/aws-iam-authenticator/
```

clusterrolebinding.yaml:

```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
subjects:
- kind: User
  name: admin-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer
subjects:
- kind: User
  name: developer-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io

```

clusterrole.yml:

```yml
kind: ClusterRole

apiVersion: rbac.authorization.k8s.io/v1

metadata:

  name: developer

rules:

- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: [""]
  resources: ["pods/status", "namespaces", "namespaces/status", "pods/log"]
  verbs: ["get", "list", "watch"]

```

serviceaccounts.yml:

```yml
# Service account for admin users
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
# Service account for developer users
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-user
  namespace: kube-system
```

**5. What happened after the commands executed?**

The master was re-created, but three of our LoadBalancer services (out of about 20 or so) had all of their targets removed and their security group IDs were removed from the nodes security group ingress rule list.

**6. What did you expect to happen?**

The master should have been re-created with no changes to any of the other kubernetes resources.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-10-10T02:50:49Z
  name: <name>
spec:
  additionalPolicies:
    node: |
      [ # redacted additional IAM actions
      ]
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    environment: development,staging
    poc: cloud-eng
    role: k8s
  cloudProvider: aws
  configBase: <s3 bucket>/<name>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1f
      name: f
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1f
      name: f
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.11
  masterInternalName: api.internal.<name>
  masterPublicName: api.<name>
  networkCIDR: 172.20.0.0/23
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.30.0.0/24
  subnets:
  - cidr: 172.20.0.0/24
    name: us-east-1e
    type: Public
    zone: us-east-1e
  - cidr: 172.20.1.0/24
    name: us-east-1f
    type: Public
    zone: us-east-1f
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-10T02:50:55Z
  labels:
    kops.k8s.io/cluster: <name>
  name: master-us-east-1f
spec:
  image: ami-67e43818
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1f
  role: Master
  subnets:
  - us-east-1f

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-10T02:50:55Z
  labels:
    kops.k8s.io/cluster: <name>
  name: nodes
spec:
  image: ami-67e43818
  machineType: m5.2xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1e
  - us-east-1f
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
