### ISSUE TITLE
"error finding the launch configuration or template for instance"

### ISSUE THREAD

**Issue by tsuna** [kubernetes/kops#6558]
**1. What `kops` version are you running?**

`Version 1.12.0-alpha.1 (git-02165dbd6)` — this is master as of commit 8cea9af6e63fdbeabd1ced5eaf2177d270353a46 plus the code in #6347

**2. What Kubernetes version are you running?**

Server v1.11.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops rolling-update cluster`

**5. What happened after the commands executed?**

```
error getting cloud instance group "master-us-west-2a": error finding the launch configuration or template for instance: i-0c0ecf68f087c3cc5
```
(the instance ID in question was that of the master, see the AWS cli output at the very bottom)

**6. What did you expect to happen?**

The `rolling-update` command (without `--yes`) should've printed the IGs and what, if anything, needs to be updated.

**7. Please provide your cluster manifest.**

This is a small test cluster that I am the only one using:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-06-22T23:09:49Z
  name: k8s.example.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://example-com-k8s-state-store/k8s.example.com
  docker:
    logLevel: debug
    logOpt:
    - max-size=64m
    - max-file=8
    version: 18.09.3
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 30
    auditLogMaxBackups: 5
    auditLogMaxSize: 128
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    maxRequestsInflight: 100
  kubelet:
    anonymousAuth: false
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.7
  masterInternalName: api.internal.k8s.example.com
  masterKubelet:
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  masterPublicName: api.k8s.example.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.20.0.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  topology:
    bastion:
      bastionPublicName: bastion.k8s.example.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-20T23:17:50Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: bastions
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t3.micro
  maxPrice: "0.01"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
    spot: "true"
  role: Bastion
  rootVolumeSize: 16
  rootVolumeType: standard
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-22T23:09:49Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-us-west-2a
spec:
  fileAssets:
  - content: |
      apiVersion: audit.k8s.io/v1beta1
      kind: Policy
      # Don't generate audit events for all requests in RequestReceived stage.
      omitStages:
        - "RequestReceived"
      rules:
        # Log pod changes at RequestResponse level.
        - level: RequestResponse
          resources:
          - group: ""
            # Resource "pods" doesn't match requests to any subresource of pods,
            # which is consistent with the RBAC policy.
            resources: ["pods"]
        # Log "pods/log", "pods/status" at Metadata level.
        - level: Metadata
          resources:
          - group: ""
            resources: ["pods/log", "pods/status"]
        # Don't log requests to a ConfigMap called "controller-leader"
        - level: None
          resources:
          - group: ""
            resources: ["configmaps"]
            resourceNames: ["controller-leader"]
        # Don't log watch requests by the "system:kube-proxy" on endpoints or services
        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
          - group: "" # core API group
            resources: ["endpoints", "services", "services/status"]
        - level: None
          verbs: ["list"]
          resources:
          - group: "admissionregistration.k8s.io"
        # Don't log these read-only URLs.
        - level: None
          nonResourceURLs:
          - /healthz*
          - /version
          - /swagger
        # Log the request body of ConfigMap changes in kube-system.
        - level: Request
          resources:
          - group: "" # core API group
            resources: ["configmaps"]
          # This rule only applies to resources in the "kube-system" namespace.
          # The empty string "" can be used to select non-namespaced resources.
          namespaces: ["kube-system"]
        # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
        # so only log at the Metadata level.
        - level: Metadata
          resources:
          - group: "" # core API group
            resources: ["secrets", "configmaps"]
          - group: authentication.k8s.io
            resources: ["tokenreviews"]
        # Log all other resources in core and extensions at the Request level.
        - level: Request
          resources:
          - group: "" # core API group
          - group: "extensions" # Version of group should NOT be included.
        # A catch-all rule to log all other requests at the Metadata level.
        - level: Metadata
          # Long-running requests like watches that fall under this rule will not
          # generate an audit event in RequestReceived.
          omitStages:
            - "RequestReceived"
    name: apiserver-audit-policy
    path: /srv/kubernetes/audit.yaml
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m3.medium
  maxPrice: "0.05"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-06-22T23:09:49Z
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.small
  maxPrice: "0.01"
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 32
  rootVolumeType: standard
  subnets:
  - us-west-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.**

Sorry I didn't think about capturing this at the time and I've completed a `rolling-update` in the meantime and I can't reproduce anymore as now the ASG lists a `LaunchConfigurationName` in the output of the AWS cli below.

**9. Anything else do we need to know?**

I regularly update my local kops from upstream and this issue started happening right after #6277 merged.  I unmerged it manually with `git revert -m 1 1564a6746134935ca0de7ec3815d18f4bb271fb3` and was able to run the `rolling-update` command normally.

Here is the output of `aws autoscaling describe-auto-scaling-groups` at the time (note the lack of `LaunchConfigurationName` inside of the `Instances` list):
```
{
    "AutoScalingGroups": [
        {
            "AutoScalingGroupName": "bastions.k8s.example.com",
            "AutoScalingGroupARN": "arn:aws:autoscaling:us-west-2:XXX:autoScalingGroup:XXX:autoScalingGroupName/bastions.k8s.example.com",
            "LaunchConfigurationName": "bastions.k8s.example.com-20190228193453",
            "MinSize": 1,
            "MaxSize": 1,
            "DesiredCapacity": 1,
            "DefaultCooldown": 300,
            "AvailabilityZones": [
                "us-west-2a"
            ],
            "LoadBalancerNames": [
                "bastion-k8s-example-com-rt7a6a"
            ],
            "TargetGroupARNs": [],
            "HealthCheckType": "EC2",
            "HealthCheckGracePeriod": 0,
            "Instances": [
                {
                    "InstanceId": "i-08d7ac97e8e8c5b5e",
                    "AvailabilityZone": "us-west-2a",
                    "LifecycleState": "InService",
                    "HealthStatus": "Healthy",
                    "LaunchConfigurationName": "bastions.k8s.example.com-20190227003355",
                    "ProtectedFromScaleIn": false
                }
            ],
            "CreatedTime": "2019-02-21T07:42:29.246Z",
            "SuspendedProcesses": [],
            "VPCZoneIdentifier": "subnet-08f793e682402951b",
            "EnabledMetrics": [
                {
                    "Metric": "GroupPendingInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupInServiceInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupTerminatingInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupStandbyInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupDesiredCapacity",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupMaxSize",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupMinSize",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupTotalInstances",
                    "Granularity": "1Minute"
                }
            ],
            "Tags": [
                {
                    "ResourceId": "bastions.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "KubernetesCluster",
                    "Value": "k8s.example.com",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "bastions.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "Name",
                    "Value": "bastions.k8s.example.com",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "bastions.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/cluster-autoscaler/node-template/label/kops.k8s.io/instancegroup",
                    "Value": "bastions",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "bastions.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/cluster-autoscaler/node-template/label/spot",
                    "Value": "true",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "bastions.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/role/bastion",
                    "Value": "1",
                    "PropagateAtLaunch": true
                }
            ],
            "TerminationPolicies": [
                "Default"
            ],
            "NewInstancesProtectedFromScaleIn": false,
            "ServiceLinkedRoleARN": "arn:aws:iam::XXX:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
        },
        {
            "AutoScalingGroupName": "master-us-west-2a.masters.k8s.example.com",
            "AutoScalingGroupARN": "arn:aws:autoscaling:us-west-2:XXX:autoScalingGroup:XXX:autoScalingGroupName/master-us-west-2a.masters.k8s.example.com",
            "LaunchConfigurationName": "master-us-west-2a.masters.k8s.example.com-20190228193453",
            "MinSize": 1,
            "MaxSize": 1,
            "DesiredCapacity": 1,
            "DefaultCooldown": 300,
            "AvailabilityZones": [
                "us-west-2a"
            ],
            "LoadBalancerNames": [
                "api-k8s-example-com-3murt0"
            ],
            "TargetGroupARNs": [],
            "HealthCheckType": "EC2",
            "HealthCheckGracePeriod": 0,
            "Instances": [
                {
                    "InstanceId": "i-0c0ecf68f087c3cc5",
                    "AvailabilityZone": "us-west-2a",
                    "LifecycleState": "InService",
                    "HealthStatus": "Healthy",
                    "ProtectedFromScaleIn": false
                }
            ],
            "CreatedTime": "2018-06-23T01:29:14.920Z",
            "SuspendedProcesses": [],
            "VPCZoneIdentifier": "subnet-08f793e682402951b",
            "EnabledMetrics": [
                {
                    "Metric": "GroupPendingInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupInServiceInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupStandbyInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupDesiredCapacity",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupTotalInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupMinSize",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupMaxSize",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupTerminatingInstances",
                    "Granularity": "1Minute"
                }
            ],
            "Tags": [
                {
                    "ResourceId": "master-us-west-2a.masters.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "KubernetesCluster",
                    "Value": "k8s.example.com",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "master-us-west-2a.masters.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "Name",
                    "Value": "master-us-west-2a.masters.k8s.example.com",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "master-us-west-2a.masters.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/cluster-autoscaler/node-template/label/kops.k8s.io/instancegroup",
                    "Value": "master-us-west-2a",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "master-us-west-2a.masters.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/role/master",
                    "Value": "1",
                    "PropagateAtLaunch": true
                }
            ],
            "TerminationPolicies": [
                "Default"
            ],
            "NewInstancesProtectedFromScaleIn": false,
            "ServiceLinkedRoleARN": "arn:aws:iam::XXX:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
        },
        {
            "AutoScalingGroupName": "nodes.k8s.example.com",
            "AutoScalingGroupARN": "arn:aws:autoscaling:us-west-2:XXX:autoScalingGroup:XXX:autoScalingGroupName/nodes.k8s.example.com",
            "LaunchConfigurationName": "nodes.k8s.example.com-20190228193453",
            "MinSize": 3,
            "MaxSize": 3,
            "DesiredCapacity": 3,
            "DefaultCooldown": 300,
            "AvailabilityZones": [
                "us-west-2a"
            ],
            "LoadBalancerNames": [],
            "TargetGroupARNs": [],
            "HealthCheckType": "EC2",
            "HealthCheckGracePeriod": 0,
            "Instances": [
                {
                    "InstanceId": "i-01804d0974b8ebfa4",
                    "AvailabilityZone": "us-west-2a",
                    "LifecycleState": "InService",
                    "HealthStatus": "Healthy",
                    "ProtectedFromScaleIn": false
                },
                {
                    "InstanceId": "i-028877739ab2b39e0",
                    "AvailabilityZone": "us-west-2a",
                    "LifecycleState": "InService",
                    "HealthStatus": "Healthy",
                    "ProtectedFromScaleIn": false
                },
                {
                    "InstanceId": "i-098567ad6c1eba06b",
                    "AvailabilityZone": "us-west-2a",
                    "LifecycleState": "InService",
                    "HealthStatus": "Healthy",
                    "ProtectedFromScaleIn": false
                }
            ],
            "CreatedTime": "2018-06-23T01:29:14.987Z",
            "SuspendedProcesses": [],
            "VPCZoneIdentifier": "subnet-08f793e682402951b",
            "EnabledMetrics": [
                {
                    "Metric": "GroupMinSize",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupStandbyInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupMaxSize",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupTerminatingInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupInServiceInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupPendingInstances",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupDesiredCapacity",
                    "Granularity": "1Minute"
                },
                {
                    "Metric": "GroupTotalInstances",
                    "Granularity": "1Minute"
                }
            ],
            "Tags": [
                {
                    "ResourceId": "nodes.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "KubernetesCluster",
                    "Value": "k8s.example.com",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "nodes.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "Name",
                    "Value": "nodes.k8s.example.com",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "nodes.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/cluster-autoscaler/node-template/label/kops.k8s.io/instancegroup",
                    "Value": "nodes",
                    "PropagateAtLaunch": true
                },
                {
                    "ResourceId": "nodes.k8s.example.com",
                    "ResourceType": "auto-scaling-group",
                    "Key": "k8s.io/role/node",
                    "Value": "1",
                    "PropagateAtLaunch": true
                }
            ],
            "TerminationPolicies": [
                "Default"
            ],
            "NewInstancesProtectedFromScaleIn": false,
            "ServiceLinkedRoleARN": "arn:aws:iam::XXX:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
        }
    ]
}
```
