### ISSUE TITLE
Unable to enable kube-scheduler.usePolicyConfigMap due to RBAC

### ISSUE THREAD

**Issue by reverson** [kubernetes/kops#6579]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.11.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit cluster
# Enable kubeScheduler.usePolicyConfigMap

**5. What happened after the commands executed?**
kops could not validate cluster, 1 kube-scheduler is in a constant restart cycle with the following error presented at the end of the run ```couldn't get policy config map kube-system/scheduler-policy: configmaps "scheduler-policy" is forbidden: User "system:kube-scheduler" cannot get configmaps in the namespace "kube-system"
```

**6. What did you expect to happen?**
kube-scheduler pod would start up and read policy from scheduler-policy configmap.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-27T19:25:35Z
  name: CLUSTER
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://CLUSTER/CLUSTER
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    - instanceGroup: master-us-east-2b
      name: b
    - instanceGroup: master-us-east-2c
      name: c
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeScheduler:
    usePolicyConfigMap: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterInternalName: api.internal.CLUSTER
 masterPublicName: api.CLUSTER
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  - cidr: 172.20.64.0/19
    name: us-east-2b
    type: Public
    zone: us-east-2b
  - cidr: 172.20.96.0/19
    name: us-east-2c
    type: Public
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I've attempted to add scheduler-policy to the ` system::leader-locking-kube-scheduler` role, but that didn't seem to help.
