### ISSUE TITLE
Controller Manager removes instance group's ingress rule of service Load Balancer sg-id even when other load balancers have attached that same sg-id.

### ISSUE THREAD

**Issue by makknife** [kubernetes/kops#6583]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client - 1.11.1
Server - 1.11.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops edit cluster
```
spec:
  cloudConfig:
    elbSecurityGroup: sg-XXXXXXX
```

now `kubectl apply` a kubernetes service with a load balancer
now `kubectl apply` a second kubernetes service with a load balancer
now `kubectl delete` one of those services

**5. What happened after the commands executed?**

The load balancers get deployed with the elb security group attached (as expected)
The nodes instance group's ec2 security group gets an ingress rule with the elb security group.

When one of the services with a load balancer is removed from the cluster,
the other services with load balancers all lose connection to the cluster because kubernetes removes the ingress rule of the shared security group. ec2 doesn't allow duplicate ingress rules.

**6. What did you expect to happen?**
I expect kubernetes to know that I still have other services deployed with load balancers using the same security group, that is kops spec.cloudConfig.elbSecurityGroup. 

If there are, don't remove the ingress rule.
If there aren't, it's okay to remove the ingress rule.

A workaround we are using is to add the security group id as an ingress rule to an additional security group attached to the nodes, but this is kind of a hack. i would like an option in the kops cluster spec.

`kops edit ig nodes`

```
kind: InstanceGroup
....
spec:
  additionalSecurityGroups:
  - sg-YYYYYY
```

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-08-23T19:54:18Z
  name: REDACTED
spec:
  api:
    loadBalancer:
      type: Internal
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    elbSecurityGroup: REDACTED
  cloudProvider: aws
  configBase: REDACTED
  dnsZone: REDACTED
  docker:
    insecureRegistry: REDACTED
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1a
      name: a
    manager:
      image: kopeio/etcd-manager:1.0.20180729
    name: main
    version: 3.2.18
  - etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1a
      name: a
    manager:
      image: kopeio/etcd-manager:1.0.20180729
    name: events
    version: 3.2.18
  externalDns:
    disable: true
  iam:
    legacy: false
  kubernetesApiAccess:
  - REDACTED
  kubernetesVersion: 1.11.6
  masterInternalName: REDACTED
  masterPublicName: REDACTED
  networkCIDR: REDACTED
  networkID: REDACTED
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: REDACTED
  sshAccess:
  - REDACTED
  subnets:
  - cidr: REDACTED
    id: REDACTED
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: REDACTED
    id: REDACTED
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: REDACTED
    id: REDACTED
    name: us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-23T19:54:18Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1a
spec:
  cloudLabels: REDACTED
  iam:
    profile: REDACTED
  image: REDACTED
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a
  taints:
  - node-role.kubernetes.io/master=:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-23T19:54:18Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1b
spec:
  cloudLabels: REDACTED
  iam:
    profile: REDACTED
  image: REDACTED
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b
  taints:
  - node-role.kubernetes.io/master=:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-23T19:54:18Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: master-us-east-1c
spec:
  cloudLabels: REDACTED
  iam:
    profile: REDACTED
  image: REDACTED
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c
  taints:
  - node-role.kubernetes.io/master=:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-23T19:54:18Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: nodes
spec:
  additionalSecurityGroups:
  - REDACTED
  cloudLabels: REDACTED
  iam:
    profile: REDACTED
  image: REDACTED
  kubelet:
    evictionHard: memory.available<2Gi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionMinimumReclaim: memory.available=2Gi,nodefs.available=10%,imagefs.available=10%
    maxPods: 30
  machineType: r4.xlarge
  maxSize: 30
  minSize: 15
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-08-23T19:54:18Z
  labels:
    kops.k8s.io/cluster: REDACTED
  name: persistent
spec:
  additionalSecurityGroups:
  - REDACTED
  cloudLabels: REDACTED
  iam:
    profile: REDACTED
  image: REDACTED
  kubelet:
    evictionHard: memory.available<2Gi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    evictionMinimumReclaim: memory.available=1Gi,nodefs.available=10%,imagefs.available=10%
    maxPods: 16
  machineType: r4.xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    dedicated: persistent
    kops.k8s.io/instancegroup: persistent
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  taints:
  - dedicated=persistent:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

snipet of controller-manager.log
```
I0222 13:40:44.744632       1 service_controller.go:729] Service has been deleted REDACTED. Attempting to cleanup load balancer resources
I0222 13:40:44.745590       1 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"REDACTED", Name:"REDACTED", UID:"REDACTED", APIVersion:"v1", ResourceVersion:"1517940", FieldPath:""}): type: 'Normal' reason: 'DeletingLoadBalancer' Deleting load balancer
I0222 13:40:44.959721       1 aws.go:3828] Removing rule for traffic from the load balancer (REDACTED) to instance (REDACTED)
I0222 13:40:45.012568       1 aws.go:2667] Comparing sg-XXX to sg-AAA
I0222 13:40:45.012599       1 aws.go:2667] Comparing sg-XXX to sg-ZZZ
I0222 13:40:45.012607       1 aws.go:2667] Comparing sg-XXX to sg-YYY
 ```

controller manager thinks it's exclusively for that service
when a new service is deployed the load balancer will use the default sg-id and apply an ingress rule of that load balancers sg-id to the ec2 sg ingress rules.
however, since multiple load balancers have the same default sg it ends up applying on the same/single ingress rule.
the aws api will not put duplicate rules on the ec2 sg.

**9. Anything else do we need to know?**
not really
