### ISSUE TITLE
Volume creation does not work

### ISSUE THREAD

**Issue by mazzy89** [kubernetes/kops#6659]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.5

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
AWS_SDK_LOAD_CONFIG=1 KOPS_STATE_S3_ACL=bucket-owner-full-control kops update cluster my-cluster --state s3://my-cluster-kops-state-store --lifecycle-overrides IAMRole=ExistsAndWarnIfChanges,IAMRolePolicy=ExistsAndWarnIfChanges,IAMInstanceProfileRole=ExistsAndWarnIfChanges --out=config/my-cluster/terraform --target=terraform
```

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

Terraform configuration should change and include the new volume but unfortunately, this does not happen.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my-cluster
  name: nodes
spec:
  detailedInstanceMonitoring: false
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.xlarge
  maxSize: 4
  minSize: 4
  role: Node
  volumeMounts:
  - device: /dev/nvme2n1
    filesystem: ext4
    path: /var/lib/docker
  volumes:
  - device: /dev/nvme2n1
    encrypted: true
    size: 100
    type: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  iam:
    profile: ""
  subnets:
  - private-us-east-1a
  - private-us-east-1b
  - private-us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by rdrgmnzs** [comment]
@mazzy89 to help us debug this would you be able to provide us a full cluster manifest as well as the generated terraform config file?

**Comment by mazzy89** [comment]
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: k8s.mydomain.net
spec:
  additionalPolicies: {}
  api:
    loadBalancer:
      type: Public
      idleTimeoutSeconds: 600
  fileAssets:
  - name: kube-apiserver-audit-policy
    path: /srv/kubernetes/audit.yaml
    roles:
      - Master
    content: |
      apiVersion: audit.k8s.io/v1beta1
      kind: Policy
      rules:
        # The following requests were manually identified as high-volume and low-risk,
        # so drop them.
        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
            - group: "" # core
              resources: ["endpoints", "services", "services/status"]
        - level: None
          # Ingress controller reads 'configmaps/ingress-uid' through the unsecured port.
          # TODO(#46983): Change this to the ingress controller service account.
          users: ["system:unsecured"]
          namespaces: ["kube-system"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["configmaps"]
        - level: None
          users: ["kubelet"] # legacy kubelet identity
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["nodes", "nodes/status"]
        - level: None
          userGroups: ["system:nodes"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["nodes", "nodes/status"]
        - level: None
          users:
            - system:kube-controller-manager
            - system:kube-scheduler
            - system:serviceaccount:kube-system:endpoint-controller
          verbs: ["get", "update"]
          namespaces: ["kube-system"]
          resources:
            - group: "" # core
              resources: ["endpoints"]
        - level: None
          users: ["system:apiserver"]
          verbs: ["get"]
          resources:
            - group: "" # core
              resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
        - level: None
          users: ["cluster-autoscaler"]
          verbs: ["get", "update"]
          namespaces: ["kube-system"]
          resources:
            - group: "" # core
              resources: ["configmaps", "endpoints"]
        # Don't log HPA fetching metrics.
        - level: None
          users:
            - system:kube-controller-manager
          verbs: ["get", "list"]
          resources:
            - group: "metrics.k8s.io"
        # Don't log these read-only URLs.
        - level: None
          nonResourceURLs:
            - /healthz*
            - /version
            - /swagger*
        # Don't log events requests.
        - level: None
          resources:
            - group: "" # core
              resources: ["events"]
        # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
        - level: Request
          users: ["kubelet", "system:node-problem-detector", "system:serviceaccount:kube-system:node-problem-detector"]
          verbs: ["update","patch"]
          resources:
            - group: "" # core
              resources: ["nodes/status", "pods/status"]
          omitStages:
            - "RequestReceived"
        - level: Request
          userGroups: ["system:nodes"]
          verbs: ["update","patch"]
          resources:
            - group: "" # core
              resources: ["nodes/status", "pods/status"]
          omitStages:
            - "RequestReceived"
        # deletecollection calls can be large, don't log responses for expected namespace deletions
        - level: Request
          users: ["system:serviceaccount:kube-system:namespace-controller"]
          verbs: ["deletecollection"]
          omitStages:
            - "RequestReceived"
        # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
        # so only log at the Metadata level.
        - level: Metadata
          resources:
            - group: "" # core
              resources: ["secrets", "configmaps"]
            - group: authentication.k8s.io
              resources: ["tokenreviews"]
          omitStages:
            - "RequestReceived"
        # Get repsonses can be large; skip them.
        - level: Request
          verbs: ["get", "list", "watch"]
          resources:
            - group: "" # core
            - group: "admissionregistration.k8s.io"
            - group: "apiextensions.k8s.io"
            - group: "apiregistration.k8s.io"
            - group: "apps"
            - group: "authentication.k8s.io"
            - group: "authorization.k8s.io"
            - group: "autoscaling"
            - group: "batch"
            - group: "certificates.k8s.io"
            - group: "extensions"
            - group: "metrics.k8s.io"
            - group: "networking.k8s.io"
            - group: "node.k8s.io"
            - group: "policy"
            - group: "rbac.authorization.k8s.io"
            - group: "scheduling.k8s.io"
            - group: "settings.k8s.io"
            - group: "storage.k8s.io"
          omitStages:
            - "RequestReceived"
        # Default level for known APIs
        - level: RequestResponse
          resources:
            - group: "" # core
            - group: "admissionregistration.k8s.io"
            - group: "apiextensions.k8s.io"
            - group: "apiregistration.k8s.io"
            - group: "apps"
            - group: "authentication.k8s.io"
            - group: "authorization.k8s.io"
            - group: "autoscaling"
            - group: "batch"
            - group: "certificates.k8s.io"
            - group: "extensions"
            - group: "metrics.k8s.io"
            - group: "networking.k8s.io"
            - group: "node.k8s.io"
            - group: "policy"
            - group: "rbac.authorization.k8s.io"
            - group: "scheduling.k8s.io"
            - group: "settings.k8s.io"
            - group: "storage.k8s.io"
          omitStages:
            - "RequestReceived"
        # Default level for all other requests.
        - level: Metadata
          omitStages:
            - "RequestReceived"
  hooks:
    - name: kops-hook-tag-ebs-volumes.service
      roles:
        - Master
        - Node
      manifest: |-
        [Unit]
        Description=Tag EBS Volumes without tags with AutoScaling Group tags
        [Service]
        Type=oneshot
        ExecStartPre=/bin/bash -c "/usr/bin/curl -s https://stedolan.github.io/jq/download/linux64/jq > /usr/local/bin/jq && chmod +x /usr/local/bin/jq"
        ExecStart=/bin/bash \
          -c 'AWS_REGION=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//'); \
              INSTANCE_ID=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id); \
              VOLUMES=$(/usr/local/bin/aws ec2 describe-volumes --region $AWS_REGION --filters Name=attachment.instance-id,Values=$INSTANCE_ID | /usr/local/bin/jq -r '"'"'.Volumes[] | select(.Tags == null) | .Attachments[].VolumeId'"'"'); \
              AUTOSCALING_GROUP=$(/usr/local/bin/aws autoscaling describe-auto-scaling-instances --region $AWS_REGION --instance-ids $INSTANCE_ID | /usr/local/bin/jq -r .AutoScalingInstances[].AutoScalingGroupName); \
              TAGS=$(/usr/local/bin/aws autoscaling describe-tags --region $AWS_REGION --filters Name=auto-scaling-group,Values=$AUTOSCALING_GROUP --query '"'"'Tags[*].{Key:Key,Value:Value}'"'"'); \
              /usr/local/bin/aws ec2 create-tags --region "$AWS_REGION" --resources "$VOLUMES" --tags "$TAGS";'
  kubeAPIServer:
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditLogMaxAge: 30
    auditLogMaxBackups: 2
    auditLogMaxSize: 100
    auditPolicyFile: /srv/kubernetes/audit.yaml
    authorizationMode: RBAC
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
  kubelet:
    anonymousAuth: false
    authorizationMode: Webhook
    authenticationTokenWebhook: true
  authorization:
    rbac: {}
  authentication:
    aws: {}
  channel: stable
  cloudLabels:
    Cluster: k8s.mydomain.net
    Environment: staging
  cloudProvider: aws
  configBase: s3://k8s-mydomain-net
  dnsZone: mydomain.net
  kubeDNS:
    provider: CoreDNS
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: member-a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: member-b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: member-c
    enableEtcdTLS: true
    name: main
    version: 3.3.10
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-east-1a
      name: member-a
    - encryptedVolume: true
      instanceGroup: master-us-east-1b
      name: member-b
    - encryptedVolume: true
      instanceGroup: master-us-east-1c
      name: member-c
    enableEtcdTLS: true
    name: events
    version: 3.3.10
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.5
  masterPublicName: api.k8s.mydomain.net
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: private-us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: private-us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: private-us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.20.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.k8s.mydomain.net
    dns:
      type: Public
    masters: private
    nodes: private
  addons: {}

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.mydomain.net
  name: bastions
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Bastion
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  iam:
    profile: arn:aws:iam::xxxxxxxxxx:instance-profile/kops-bastion-role-7077ada4-d8bf-47b7-8541-8779aff94709
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c
  additionalUserData:
    - name: instanceup.sh
      type: text/x-shellscript
      content: |
        #!/bin/bash

        set -o errexit
        set -o nounset
        set -o pipefail

        echo "Install jq..."
        curl -s https://stedolan.github.io/jq/download/linux64/jq > /usr/local/bin/jq && chmod +x /usr/local/bin/jq

        echo "Tag EBS Volumes without tags with AutoScaling Group tags..."
        AWS_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
        INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
        VOLUMES=$(aws ec2 describe-volumes --region "$AWS_REGION" --filters Name=attachment.instance-id,Values="$INSTANCE_ID" | jq -r '.Volumes[] | select(.Tags == null) | .Attachments[].VolumeId')
        AUTOSCALING_GROUP=$(aws autoscaling describe-auto-scaling-instances --region "$AWS_REGION" --instance-ids "$INSTANCE_ID" | jq -r .AutoScalingInstances[].AutoScalingGroupName)
        TAGS=$(aws autoscaling describe-tags --region "$AWS_REGION" --filters Name=auto-scaling-group,Values=$AUTOSCALING_GROUP --query 'Tags[*].{Key:Key,Value:Value}')

        aws ec2 create-tags --region "$AWS_REGION" --resources "$VOLUMES" --tags "$TAGS"



---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.mydomain.net
  name: master-us-east-1a
spec:
  detailedInstanceMonitoring: false
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  role: Master
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  iam:
    profile: arn:aws:iam::xxxxxxxxxxxx:instance-profile/kops-master-role-49d5ee4c-a109-46ea-bef4-0d554370b02f
  subnets:
  - private-us-east-1a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.mydomain.net
  name: master-us-east-1b
spec:
  detailedInstanceMonitoring: false
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  role: Master
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  iam:
    profile: arn:aws:iam::xxxxxxxxxx:instance-profile/kops-master-role-49d5ee4c-a109-46ea-bef4-0d554370b02f
  subnets:
  - private-us-east-1b

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.mydomain.net
  name: master-us-east-1c
spec:
  detailedInstanceMonitoring: false
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  role: Master
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  iam:
    profile: arn:aws:iam::xxxxxxxxx:instance-profile/kops-master-role-49d5ee4c-a109-46ea-bef4-0d554370b02f
  subnets:
  - private-us-east-1c

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.mydomain.net
  name: nodes
spec:
  detailedInstanceMonitoring: false
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.xlarge
  maxSize: 4
  minSize: 4
  role: Node
  volumeMounts:
  - device: /dev/nvme2n1
    filesystem: ext4
    path: /var/lib/docker
  volumes:
  - device: /dev/nvme2n1
    encrypted: true
    size: 100
    type: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  iam:
    profile: arn:aws:iam::xxxxxxxxxx:instance-profile/kops-worker-role-7a231603-22bf-4f4f-b36f-29207b757d1f
  subnets:
  - private-us-east-1a
  - private-us-east-1b
  - private-us-east-1c

---
apiVersion: kops/v1alpha2
kind: SSHCredential
metadata:
  labels:
    kops.k8s.io/cluster: k8s.mydomain.net
spec:
  publicKey: ssh-rsa xxxxxxxxxx
```
