### ISSUE TITLE
KOPS 1.12.aplaha mixed instances types bug with terraform output 

### ISSUE THREAD

**Issue by granular-ryanbonham** [kubernetes/kops#6688]
Version 1.12.0-alpha.2 (git-c3b99b857)

Creating an instance group, using mixed instance policy using the following IG template
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-27T14:13:14Z
  labels:
    customer_facing: "yes"
    kops.k8s.io/cluster: cluster.XXXX.XXX
  name: nodes-us-east-1c
spec:
  additionalSecurityGroups:
  - sg-XXXXXXX
  image: ami-06e8172ba84b291f8
  machineType: m5.xlarge
  maxSize: 100
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - m5.xlarge
    - m4.xlarge
    onDemandAboveBase: 40
    spotInstancePools: 2
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 256
  rootVolumeType: gp2
  subnets:
  - us-east-1c
```

Generates a terraform output for the aws_autoscaling_group with the following mied_instance_policy
```
mixed_instances_policy = {
    launch_template = {
      launch_template_specification = {
        launch_template_name = "${aws_launch_template.nodes-us-east-1b-cluster.XXXX.XXXX}"
      }

      overrides = {
        instance_type = "m5.xlarge"
      }

      overrides = {
        instance_type = "m4.xlarge"
      }
    }
````
Running terraform plan, show the following error.

Error: aws_autoscaling_group.nodes-us-east-1b-cluster.XXXX.XXX: mixed_instances_policy.0.launch_template.0: invalid or unknown key: overrides

According the the terraform docs, the key should be "override" not "overrides"

https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#mixed_instances_policy
