### ISSUE TITLE
kops 1.12 etcd3 migration with current etcd3 cluster

### ISSUE THREAD

**Issue by Deshke** [kubernetes/kops#6690]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.12.0-alpha.2 (git-c3b99b857)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.9 -> 1.12.7

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

https://github.com/kubernetes/kops/blob/master/docs/etcd3-migration.md

```
kops edit cluster -> kube 1.12.7/ etcd 3.2.24
kops rolling-update cluster --cloudonly --instance-group-roles master --master-interval=1s --yes
kops rolling-update cluster --yes
``` 

**5. What happened after the commands executed?**

dead cluster

**6. What did you expect to happen?**

healthy cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-03-27T14:17:30Z
  name: testing.k8s.some.tld
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://some.s3/testing.k8s.some.tld
  dnsZone: testing.k8s.some.tld
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
    version: 3.2.24
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    hairpinMode: hairpin-veth
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.7
  masterInternalName: api.internal.testing.k8s.some.tld
  masterPublicName: api.testing.k8s.some.tld
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc:
      imageName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - some.fancy.ipv4.subnet
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  - cidr: 172.20.96.0/19
    name: eu-central-1c
    type: Public
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
  updatePolicy: external
``` 

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
....

**9. Anything else do we need to know?**

trying to update a kube 1.11.9 with etcd 3 and tls to kube 1.121.7 with  kops 1.12-alpha2, changes to the kops configuration from step 7.

```
-   version: 3.2.18
+  version: 3.2.24
-   kubernetesVersion: 1.11.9
+  kubernetesVersion: 1.12.7
```
