### ISSUE TITLE
Cluster created with calico networking fails: nodes not joining the cluster

### ISSUE THREAD

**Issue by oekarlsson** [kubernetes/kops#6694]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.0-alpha.2 (git-c3b99b857)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.12.7

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud aws --authorization RBAC --node-count 3 --master-count 3 --zones eu-north-1a,eu-north-1b,eu-north-1c --master-zones eu-north-1a,eu-north-1b,eu-north-1c --node-size t3.large --master-size t3.medium --networking calico --name $NAME && kops update cluster --yes

**5. What happened after the commands executed?**
masters seem to be running ok. This is the output from kubectl get all -n kube-system
```
NAME                                                                        READY   STATUS    RESTARTS   AGE
pod/coredns-549c9d5c4f-9qckf                                                0/1     Pending   0          36m
pod/coredns-549c9d5c4f-ndxbr                                                0/1     Pending   0          36m
pod/dns-controller-7659f8d54b-n9z95                                         0/1     Pending   0          37m
pod/etcd-manager-events-ip-172-20-122-238.eu-north-1.compute.internal       1/1     Running   0          35m
pod/etcd-manager-events-ip-172-20-56-224.eu-north-1.compute.internal        1/1     Running   0          36m
pod/etcd-manager-events-ip-172-20-87-38.eu-north-1.compute.internal         1/1     Running   0          36m
pod/etcd-manager-main-ip-172-20-122-238.eu-north-1.compute.internal         1/1     Running   0          35m
pod/etcd-manager-main-ip-172-20-56-224.eu-north-1.compute.internal          1/1     Running   0          36m
pod/etcd-manager-main-ip-172-20-87-38.eu-north-1.compute.internal           1/1     Running   0          36m
pod/kube-apiserver-ip-172-20-122-238.eu-north-1.compute.internal            1/1     Running   3          36m
pod/kube-apiserver-ip-172-20-56-224.eu-north-1.compute.internal             1/1     Running   3          35m
pod/kube-apiserver-ip-172-20-87-38.eu-north-1.compute.internal              1/1     Running   3          36m
pod/kube-controller-manager-ip-172-20-122-238.eu-north-1.compute.internal   1/1     Running   0          36m
pod/kube-controller-manager-ip-172-20-56-224.eu-north-1.compute.internal    1/1     Running   0          36m
pod/kube-controller-manager-ip-172-20-87-38.eu-north-1.compute.internal     1/1     Running   0          36m
pod/kube-proxy-ip-172-20-122-238.eu-north-1.compute.internal                1/1     Running   0          36m
pod/kube-proxy-ip-172-20-56-224.eu-north-1.compute.internal                 1/1     Running   0          36m
pod/kube-proxy-ip-172-20-87-38.eu-north-1.compute.internal                  1/1     Running   0          36m
pod/kube-scheduler-ip-172-20-122-238.eu-north-1.compute.internal            1/1     Running   0          36m
pod/kube-scheduler-ip-172-20-56-224.eu-north-1.compute.internal             1/1     Running   0          36m
pod/kube-scheduler-ip-172-20-87-38.eu-north-1.compute.internal              1/1     Running   0          35m

NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                  AGE
service/kube-dns   ClusterIP   100.64.0.10   <none>        53/UDP,53/TCP,9153/TCP   36m

NAME                             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/coredns          2         2         2            0           36m
deployment.apps/dns-controller   1         1         1            0           38m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/coredns-549c9d5c4f          2         2         0       36m
replicaset.apps/dns-controller-7659f8d54b   1         1         0       37m
admin@ip-172-20-122-238:~$ kubectl get all -n kube-system
```

The reason for dns-controller and coredns not starting is that no nodes is available to schedule the pods on. dns-controller is not allowed to run on master.

kube-apiserver.log has a lot of these lines:
```
E0328 09:03:38.185665       1 establishing_controller.go:106] felixconfigurations.crd.projectcalico.org failed with: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "felixconfigurations.crd.projectcalico.org": the object has been modified; please apply your changes to the latest version and try again
```

**6. What did you expect to happen?**
a working cluster with calico

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-03-28T08:54:14Z
  name: [deleted]
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://[deleted]
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-north-1a
      name: a
    - instanceGroup: master-eu-north-1b
      name: b
    - instanceGroup: master-eu-north-1c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-north-1a
      name: a
    - instanceGroup: master-eu-north-1b
      name: b
    - instanceGroup: master-eu-north-1c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.7
  masterInternalName: [deleted]
  masterPublicName: [deleted]
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-north-1a
    type: Public
    zone: eu-north-1a
  - cidr: 172.20.64.0/19
    name: eu-north-1b
    type: Public
    zone: eu-north-1b
  - cidr: 172.20.96.0/19
    name: eu-north-1c
    type: Public
    zone: eu-north-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-28T08:54:15Z
  labels:
    kops.k8s.io/cluster: [deleted]
  name: master-eu-north-1a
spec:
  image: ami-8a23aaf4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1a
  role: Master
  subnets:
  - eu-north-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-28T08:54:15Z
  labels:
    kops.k8s.io/cluster: [deleted]
  name: master-eu-north-1b
spec:
  image: ami-8a23aaf4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1b
  role: Master
  subnets:
  - eu-north-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-28T08:54:15Z
  labels:
    kops.k8s.io/cluster: [deleted]
  name: master-eu-north-1c
spec:
  image: ami-8a23aaf4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1c
  role: Master
  subnets:
  - eu-north-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-03-28T08:54:15Z
  labels:
    kops.k8s.io/cluster: [deleted]
  name: nodes
spec:
  additionalUserData:
  - content: [deleted script to install objectivefs]
  image: ami-8a23aaf4
  machineType: t3.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-north-1a
  - eu-north-1b
  - eu-north-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I have tried both kubeDns and coreDns. I have tried different versions of Kubernetes, same result. This is in the eu-north-1 region, so I need to use kops 1.12 to make it work. The default AMI is not available here, so I use a newer one: k8s-1.11-debian-stretch-amd64-hvm-ebs-2019-03-27. I have tried a few other versions. I have earlier created clusters in eu-north-1 successfully, but not with calico.
