### ISSUE TITLE
Selecting addon manifest based on Cloud

### ISSUE THREAD

**Issue by christus02** [kubernetes/kops#6725]
**Cloud Specific Addons Support**

When adding a new addon in Kops, we may need to have different manifest files for different clouds. Need an option in the addon.yaml to choose cloud. So that Kops can select the respective manifest file based on cloud.

**Proposal**

```
kind: Addons
metadata:
  name: ingress-citrix
spec:
  addons:
  - version: 1.1.1
    selector:
      k8s-addon: ingress-citrix.addons.k8s.io
    cloud: GCE
    manifest: v1.1.1-gce.yaml
  - version: 1.1.1
    selector:
      k8s-addon: ingress-citrix.addons.k8s.io
    cloud: AWS
    manifest: v1.1.1-aws.yaml
```
