### ISSUE TITLE
Custom etcd CAs? Generating new etcd client certs?

### ISSUE THREAD

**Issue by den-is** [kubernetes/kops#6760]
AWS
kops 1.12.0-beta.1
k8s 1.12.7

So now etcd-manager generates 33 different CAs. All communication are secure TLS only communications. Cool.

What is the best way to provide own probably single CA for all etcd purposes ?

What is the best way to generate custom etcd-client certificates for some external certificates?

Current recipe/howto:
For example for `prometheus-operator` helm chart, to enable KubeEtcd monitor.
I had to grab etcd CA cert and key from S3 state dir.
And generate client cert for prometheus operator on my own
(or grab kube-apiservers key-pair)
```
kubeEtcd:
  enabled: true

  service:
    port: 4001
    targetPort: 4001
    selector:
      k8s-app: etcd-manager-main

  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    serverName: 127.0.0.1
    caFile: /etc/prometheus/secrets/etcd-client-cert/etcd-ca
    certFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client
    keyFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
```
(if I provide my own CA to etcd, i will be able to generate additional client certs too)
