### ISSUE TITLE
API server high error rate

### ISSUE THREAD

**Issue by oded-dd** [kubernetes/kops#6785]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I am getting an alert from my monitoring system indicating API server has an high error rate

The ERROR log I see: `status.go:64] apiserver received an error that is not an metav1.Status: u0026client.ClusterError{Errors:[]error{(*errors.errorString)(0xc4391e6840)}}` 

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: prod.cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://coralogix-k8s-state/prod.cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.8
  masterInternalName: api.internal.prod.cluster.k8s.local
  masterPublicName: api.prod.cluster.k8s.local
  networkCIDR: 172.30.0.0/16
  networkID: vpc-04bb5fe47c6bfa343
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 101.64.0.0/10
  sshAccess:
  - 172.20.0.0/16
  subnets:
  - cidr: 172.30.0.0/22
    id: subnet-0b55e6039dc043857
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 172.30.4.0/22
    id: subnet-01cbf2291c78285ef
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 172.30.8.0/22
    id: subnet-01eb4d95c4218c759
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  - cidr: 172.30.32.0/19
    egress: nat-046e5721ed321a03d
    id: subnet-07cd547e01ec46fea
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 172.30.64.0/19
    egress: nat-0e7be1c87b527cac6
    id: subnet-023cd60a19df31a0d
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 172.30.96.0/19
    egress: nat-0aa9c62342ceb7dfc
    id: subnet-0ebc3e55f4e588355
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  updatePolicy: external

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-04T18:19:38Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: backend
spec:
  cloudLabels:
    Env: prod
    Role: backend
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: c5.2xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: backend
    role: backend
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:20Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: batchprocessing
spec:
  cloudLabels:
    Env: prod
    Role: batchprocessing
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: r5.xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: batchprocessing
    role: batchprocessing
    service: batchprocessing
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=batchprocessing:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: couchbase
spec:
  cloudLabels:
    Env: prod
    Role: couchbase
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: r5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: couchbase
    role: couchbase
    service: couchbase
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=couchbase:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-002
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    cluster: "002"
    kops.k8s.io/instancegroup: es-cluster-002
    role: es-cluster
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-002:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-client-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.xlarge
  maxSize: 6
  minSize: 6
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-client-001
    role: es-cluster-client
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-client-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-hot-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r5.2xlarge
  maxSize: 43
  minSize: 43
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-hot-001
    role: es-cluster-hot
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-hot-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-master-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-master-001
    role: es-cluster-master
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-master-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: es-cluster-warm-001
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      sudo su -
      echo "DefaultLimitMEMLOCK=infinity" >> /etc/systemd/system.conf
      systemctl daemon-reexec
    name: limit_memlock.sh
    type: text/x-shellscript
  cloudLabels:
    Env: prod
    Role: elasticsearch
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r5.xlarge
  maxSize: 40
  minSize: 40
  nodeLabels:
    cluster: "001"
    kops.k8s.io/instancegroup: es-cluster-warm-001
    role: es-cluster-warm
    service: elasticsearch
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=es-cluster-warm-001:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: fluentd
spec:
  cloudLabels:
    Env: prod
    Role: fluentd
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: fluentd
    role: fluentd
    service: fluentd
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=fluentd:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-12-04T18:19:38Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: frontend
spec:
  cloudLabels:
    Env: prod
    Role: frontend
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: c5.xlarge
  maxSize: 12
  minSize: 12
  nodeLabels:
    kops.k8s.io/instancegroup: frontend
    role: frontend
  role: Node
  rootVolumeSize: 64
  subnets:
  - eu-west-1a
  taints:
  - role=frontend:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: kafka
spec:
  cloudLabels:
    Env: prod
    Role: kafka
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.2xlarge
  maxSize: 10
  minSize: 10
  nodeLabels:
    kops.k8s.io/instancegroup: kafka
    role: kafka
    service: kafka
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=kafka:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: kafka-connect
spec:
  cloudLabels:
    Env: prod
    Role: kafka-connect
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: kafka-connect
    role: kafka-connect
    service: kafka-connect
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=kafka-connect:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1a
spec:
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1b
spec:
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: master-eu-west-1c
spec:
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  rootVolumeSize: 64
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: monitor
spec:
  cloudLabels:
    Env: prod
    Role: monitor
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: monitor
    role: monitor
    service: monitor
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=monitor:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:21Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: timeseries
spec:
  cloudLabels:
    Env: prod
    Role: timeseries
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: timeseries
    role: timeseries
    service: timeseries
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=timeseries:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:20Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: user-alerts
spec:
  cloudLabels:
    Env: prod
    Role: user-alerts
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: c5.2xlarge
  maxSize: 20
  minSize: 20
  nodeLabels:
    kops.k8s.io/instancegroup: user-alerts
    role: user-alerts
    service: user-alerts
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=user-alerts:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-10T11:21:22Z
  labels:
    kops.k8s.io/cluster: prod.cluster.k8s.local
  name: zookeeper
spec:
  cloudLabels:
    Env: prod
    Role: zookeeper
  image: 595879546273/CoreOS-stable-2023.5.0-hvm
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: zookeeper
    role: zookeeper
    service: zookeeper
  role: Node
  rootVolumeOptimization: true
  rootVolumeSize: 20
  subnets:
  - eu-west-1a
  taints:
  - role=zookeeper:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
