### ISSUE TITLE
Nodes of mixedinstancegroups are in "NeedsUpdate" state even after rolling-update.

### ISSUE THREAD

**Issue by vivekgarg20** [kubernetes/kops#6796]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.0-beta.2 (git-d1453d22a)
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a"
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Applied mixed instance policy to one of instance group as introduced
Sample spec
```
  mixedInstancesPolicy:
    instances:
    - m5.2xlarge
    - c5.2xlarge
    - r5.2xlarge
    onDemandAboveBase: 0
    spotInstancePools: 3
```
did rolling-update --yes for instance groupl
**5. What happened after the commands executed?**
Kops nodes remained in "NeedsUpdate" state.
**6. What did you expect to happen?**
Nodes to go into "Ready" state.

**7. Please provide your cluster manifest. Execute
specs provided above.
