### ISSUE TITLE
 dns apiserver Validation Failed

### ISSUE THREAD

**Issue by KOSSOKO** [kubernetes/kops#6800]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0 (git-8b52ea6d1)
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --name mgs-test.com --dns private --zones eu-west-3a,eu-west-3b,eu-west-3c --yes
**5. What happened after the commands executed?**
I0420 21:55:11.162307   14209 create_cluster.go:480] Inferred --cloud=aws from zone "eu-west-3a"
I0420 21:55:11.203915   14209 subnets.go:184] Assigned CIDR 172.20.32.0/19 to subnet eu-west-3a
I0420 21:55:11.203938   14209 subnets.go:184] Assigned CIDR 172.20.64.0/19 to subnet eu-west-3b
I0420 21:55:11.203945   14209 subnets.go:184] Assigned CIDR 172.20.96.0/19 to subnet eu-west-3c
I0420 21:55:12.318889   14209 create_cluster.go:1351] Using SSH public key: /home/ec2-user/.ssh/id_rsa.pub
I0420 21:55:13.354856   14209 dns.go:92] Private DNS: skipping DNS validation
I0420 21:55:13.479172   14209 executor.go:103] Tasks: 0 done / 77 total; 30 can run
I0420 21:55:13.755955   14209 vfs_castore.go:735] Issuing new certificate: "apiserver-aggregator-ca"
I0420 21:55:14.098308   14209 vfs_castore.go:735] Issuing new certificate: "ca"
I0420 21:55:14.297198   14209 executor.go:103] Tasks: 30 done / 77 total; 25 can run
I0420 21:55:15.509304   14209 vfs_castore.go:735] Issuing new certificate: "apiserver-aggregator"
I0420 21:55:15.970994   14209 vfs_castore.go:735] Issuing new certificate: "kubelet-api"
I0420 21:55:16.262446   14209 vfs_castore.go:735] Issuing new certificate: "kube-proxy"
I0420 21:55:16.354328   14209 vfs_castore.go:735] Issuing new certificate: "kube-controller-manager"
I0420 21:55:16.814825   14209 vfs_castore.go:735] Issuing new certificate: "master"
I0420 21:55:17.360231   14209 vfs_castore.go:735] Issuing new certificate: "apiserver-proxy-client"
I0420 21:55:18.070871   14209 vfs_castore.go:735] Issuing new certificate: "kubecfg"
I0420 21:55:18.185154   14209 vfs_castore.go:735] Issuing new certificate: "kubelet"
I0420 21:55:18.208210   14209 vfs_castore.go:735] Issuing new certificate: "kops"
I0420 21:55:18.230868   14209 vfs_castore.go:735] Issuing new certificate: "kube-scheduler"
I0420 21:55:18.354074   14209 executor.go:103] Tasks: 55 done / 77 total; 20 can run
I0420 21:55:18.542239   14209 launchconfiguration.go:380] waiting for IAM instance profile "nodes.mgs-test.com" to be ready
I0420 21:55:18.543034   14209 launchconfiguration.go:380] waiting for IAM instance profile "masters.mgs-test.com" to be ready
I0420 21:55:28.863086   14209 executor.go:103] Tasks: 75 done / 77 total; 2 can run
I0420 21:55:29.357900   14209 executor.go:103] Tasks: 77 done / 77 total; 0 can run
I0420 21:55:29.357932   14209 dns.go:153] Pre-creating DNS records
I0420 21:55:29.987128   14209 update_cluster.go:290] Exporting kubecfg for cluster
W0420 21:55:30.043234   14209 create_kubecfg.go:75] Did not find API endpoint for gossip hostname; may not be able to reach cluster
kops has set your kubectl context to mgs-test.com

Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.mgs-test.com
 * the admin user is specific to Debian. If not using Debian please use the appropriate user based on your OS.
 * read about installing addons at: https://github.com/kubernetes/kops/blob/master/docs/addons.md.

**6. What did you expect to happen?**
To create a master and two nodes
In my aws console I have just two nodes.

When I run kops validate, I got 
Using cluster from kubectl context: mgs-test.com

```
Validating cluster mgs-test.com

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-eu-west-3a       Master  c4.large        1       1       eu-west-3a
nodes                   Node    t2.medium       2       2       eu-west-3a,eu-west-3b,eu-west-3c

NODE STATUS
NAME    ROLE    READY

VALIDATION ERRORS
KIND    NAME            MESSAGE
dns     apiserver       Validation Failed

The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.


Validation Failed

```
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-04-20T21:55:12Z
  name: mgs-test.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mgs-test.net/mgs-test.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-3a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-3a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.10.13
  masterPublicName: api.mgs-test.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-3a
    type: Public
    zone: eu-west-3a
  - cidr: 172.20.64.0/19
    name: eu-west-3b
    type: Public
    zone: eu-west-3b
  - cidr: 172.20.96.0/19
    name: eu-west-3c
    type: Public
    zone: eu-west-3c
  topology:
    dns:
      type: Private
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-04-20T21:55:12Z
  labels:
    kops.k8s.io/cluster: mgs-test.com
  name: master-eu-west-3a
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-3a
  role: Master
  subnets:
  - eu-west-3a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-04-20T21:55:12Z
  labels:
    kops.k8s.io/cluster: mgs-test.com
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-3a
  - eu-west-3b
  - eu-west-3c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I created a private Route53, and when I run kops create cluster kops created 4 entries : 
api.mgs-test.com
api.internal.mgs-test.com
etcd-a.internal.mgs-test.com
etcd-events-a.internal.mgs-test.com
