### ISSUE TITLE
What is the correct way to update cluster from 1.11 to 1.12 

### ISSUE THREAD

**Issue by hustshawn** [kubernetes/kops#7043]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.12.1`
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.9
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops edit cluster` modify the `kubernetesVersion` from `1.11.9` to `1.12.7`
and then
`kops rolling-update cluster --cloudonly --instance-group-roles master --master-interval=1s --yes`
**5. What happened after the commands executed?**
`Unable to connect to the server: EOF`, cannot connect to API server. Found the nodes in the API ELB are in `OutOfService ` status.
**6. What did you expect to happen?**
Update successfully.
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: my-cluster-name
spec:
  kubelet:
    anonymousAuth: false
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-state-store
  dnsZone: xxxxxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.9
  masterInternalName: xxxxxx
  masterPublicName: xxxxxx
  networkCIDR: 10.8.0.0/16
  networkID: vpc-xxxxxx
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.8.1.0/24
    id: subnet-xxxxxx
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: 10.8.3.0/24
    id: subnet-xxxxxx
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  - cidr: 10.8.5.0/24
    id: subnet-xxxxxx
    name: ap-southeast-1c
    type: Private
    zone: ap-southeast-1c
  - cidr: 10.8.2.0/24
    id: subnet-xxxxxx
    name: utility-ap-southeast-1a
    type: Utility
    zone: ap-southeast-1a
  - cidr: 10.8.4.0/24
    id: subnet-xxxxxx
    name: utility-ap-southeast-1b
    type: Utility
    zone: ap-southeast-1b
  - cidr: 10.8.6.0/24
    id: subnet-xxxxxx
    name: utility-ap-southeast-1c
    type: Utility
    zone: ap-southeast-1c
  topology:
    bastion:
      bastionPublicName: xxxxxx
    dns:
      type: Private
    masters: private
    nodes: private
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
After tried the above rolling update and fails update. I tried to modify the `etcd` related part of y cluster definition, and moved back one subversion (1.12.7 -> 12.6), in order to trigger rolling update , and it fails again.
```
 etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    name: main
    version: 3.2.24
  - enableEtcdTLS: true
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    name: events
    version: 3.2.24
```
