### ISSUE TITLE
kops will not update AWS IAM Authenticator image in the daemonset

### ISSUE THREAD

**Issue by bhutkovskyysos** [kubernetes/kops#7055]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.12.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.12.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Initially I created a new cluster with kops and used:
```
  authentication:
    aws: {}
```
for IAM authentication as described here:
https://github.com/kubernetes/kops/blob/master/docs/authentication.md#aws-iam-authenticator

This created an aws-iam-authenticator daemonset, running `gcr.io/heptio-images/authenticator:v0.3.0`. Then I found this enhancement: https://github.com/kubernetes/kops/pull/6730

so I updated the image for aws authentication:

```
authentication:
    aws:
      image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.4.0-alpine
```
I updated my template and ran `kops update cluster --name $NAME --yes`. This gave me a diff (to reproduce again I updated v0.4.0 to v0.4.0-alpine)

```
Will modify resources:
 ManagedFile/kops-cluster.com-addons-authentication.aws-k8s-1.10
     Contents
                             ...
                                       - --state-dir=/var/aws-iam-authenticator
                                       - --kubeconfig-pregenerated=true
                             +         image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.4.0
                             -         image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.4.0-alpine
                                       name: aws-iam-authenticator
                                       resources:
                             ...


 ManagedFile/kops-cluster.com-addons-authentication.aws-k8s-1.12
     Contents
                             ...
                                       - --state-dir=/var/aws-iam-authenticator
                                       - --kubeconfig-pregenerated=true
                             +         image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.4.0
                             -         image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.4.0-alpine
                                       name: aws-iam-authenticator
                                       resources:
```

When I look at the kops cluster state I do see a new image.

**5. What happened after the commands executed?**

Nothing happened.  aws-iam-authenticator daemonset was not updated.

**6. What did you expect to happen?**

I was expecting daemonset to get updated with new image. Also  I assume this would trigger pods restart. 

**9. Anything else do we need to know?**

I also looked at protokube logs and found that it is looking at /addons/bootstrap-channel.yaml, which doesn't have my new image:
```
  - id: k8s-1.10
    kubernetesVersion: '>=1.10.0 <1.12.0'
    manifest: authentication.aws/k8s-1.10.yaml
    name: authentication.aws
    selector:
      role.kubernetes.io/authentication: "1"
    version: 0.3.0-kops.1
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: authentication.aws/k8s-1.12.yaml
    name: authentication.aws
    selector:
      role.kubernetes.io/authentication: "1"
    version: 0.3.0-kops.1
```

but the one in:
addons/authentication.aws/k8s-1.12.yaml

has the new version. I think protokube is not reading it?

I also tried forcing a rolling-update, which rotated all nodes and masters but that didn't help.
