### ISSUE TITLE
Is there a way to allocate hugepages on a kops-provisioned node?

### ISSUE THREAD

**Issue by richstokes** [kubernetes/kops#7058]
K8s supports pods consuming huge pages (https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/)

Problem is, to get the huge pages you have to log into each node and create a "hugetlbfs" file system. This is very clunky and error-prone to do by hand.

Can kops support this? Maybe as part of editing a given node group you could specify an amount of memory to reserve for hugepage?

**Comment by richstokes** [comment]
FYI on a Debian node it looks like running this works:

```
echo 256 > /proc/sys/vm/nr_hugepages
systemctl restart kubelet.service
```

But it can also be set via Kernel parameters which may be better due to less chance of memory fragmentation - not sure how I can set this via kops

**Comment by richstokes** [comment]
As a workaround, I have set it in the additionalUserData section of the node spec, e.g:

```
spec:
  additionalUserData:
  - content: |
      #!/bin/bash
      echo 1024 > /proc/sys/vm/nr_hugepages && systemctl restart kubelet.service
    name: setHP.sh
    type: text/x-shellscript
```
