### ISSUE TITLE
Cannot set MTU with kops 1.11 and calico v3

### ISSUE THREAD

**Issue by gjacquet** [kubernetes/kops#7086]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.12.4

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops edit cluster`

We then set the MTU for calico to 9001

**5. What happened after the commands executed?**
Everything seemed to work, no error displayed.

**6. What did you expect to happen?**
I was expecting the generated configmap to contain the MTU but instead I got something like this:

```yaml
apiVersion: v1
data:
  calico_backend: bird
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "etcd_ca_cert_file": "/srv/kubernetes/calico/ca.pem",
          "etcd_cert_file": "/srv/kubernetes/calico/calico-client.pem",
          "etcd_key_file": "/srv/kubernetes/calico/calico-client-key.pem",
          "etcd_scheme": "https",
          "log_level": "info",
          "ipam": {
            "type": "calico-ipam"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
  etcd_endpoints: ***
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system

---
```

MTU is not set.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Relevant part is:
```yaml
  networking:
    calico:
      majorVersion: v3
      mtu: 9001
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
This looks like #6407 except in my case the MTU was not even set in the manifest in the S3 bucket

It looks like when #5380 was done, only the template for calico v2 was updated, the template for calico v2 was not changed in that PR. I believe calico v3 for kube 1.12 with kops 1.12 should work, the template looks right.

I believe something like this would fix it: https://github.com/gjacquet/kops/commit/c80ff3e0ed90f88314f6c6320aa797146975df06

I can open a PR if you would like.
