### ISSUE TITLE
Gathering metrics from etcd-manager

### ISSUE THREAD

**Issue by tomaszkiewicz** [kubernetes/kops#7135]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Before updating I used the following setup to get metrics from etcd:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-service-proxier
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["http:etcd-server-prometheus-discovery:etcd"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-service-proxier
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-service-proxier
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-server-prometheus-discovery
  namespace: kube-system
  labels:
    k8s-app: etcd-server
spec:
  selector:
    k8s-app: etcd-server
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: etcd
    port: 4001
    targetPort: 4001
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd-server
  name: etcd-server
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    path: /api/v1/namespaces/kube-system/services/http:etcd-server-prometheus-discovery:etcd/proxy/metrics
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd-server
```

It's a little hacky, but much more secure than opening firewall ports for etcd and simpler than deploying another prometheus on masters just to monitor etcd (like suggested in https://github.com/kubernetes/kops/issues/4975 and links in that thread).

After upgrading to 1.12 however, I tried to adapt the above solution to work with etcd-manager:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-service-proxier
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames:
  - "https:etcd-manager-main-prometheus-discovery:etcd"
  - "https:etcd-manager-events-prometheus-discovery:etcd"
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-service-proxier
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-service-proxier
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-manager-events-prometheus-discovery
  namespace: kube-system
  labels:
    k8s-app: etcd-manager-events
spec:
  selector:
    k8s-app: etcd-manager-events
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: etcd
    port: 4001
    targetPort: 4001
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd-manager-events
  name: etcd-manager-events
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    path: /api/v1/namespaces/kube-system/services/https:etcd-manager-events-prometheus-discovery:etcd/proxy/metrics
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd-manager-events
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-manager-main-prometheus-discovery
  namespace: kube-system
  labels:
    k8s-app: etcd-manager-main
spec:
  selector:
    k8s-app: etcd-manager-main
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: etcd
    port: 4001
    targetPort: 4001
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd-manager-main
  name: etcd-manager-main
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    path: /api/v1/namespaces/kube-system/services/https:etcd-manager-main-prometheus-discovery:etcd/proxy/metrics
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd-manager-main
```

Unfortunately this doesn't work:

```
$ kubectl get --raw /api/v1/namespaces/kube-system/services/https:etcd-manager-main-prometheus-discovery:etcd/proxy/metrics
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

But, the cluster has valid endpoints for that service:
```
$ kubectl describe service -n kube-system etcd-manager-main-prometheus-discovery                                                            
Name:              etcd-manager-main-prometheus-discovery
Namespace:         kube-system
Labels:            k8s-app=etcd-manager-main
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"etcd-manager-main"},"name":"etcd-manager-main-promet...
Selector:          k8s-app=etcd-manager-main
Type:              ClusterIP
IP:                None
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:         10.120.128.108:443,10.120.129.224:443,10.120.130.81:443
Port:              etcd  4001/TCP
TargetPort:        4001/TCP
Endpoints:         10.120.128.108:4001,10.120.129.224:4001,10.120.130.81:4001
Session Affinity:  None
Events:            <none>
```

And ssh to the host and executing curl:

```
root@ip-10-120-129-224 ~# curl https://localhost:4001/metrics -k --cert /etc/kubernetes/pki/etcd-manager-main/etcd-clients-ca.crt --key /etc/kubernetes/pki/etcd-manager-main/etcd-clients-ca.key
```

Provides valid metrics for etcd.

Do you have any suggestions on what I'm doing wrong? Or maybe do you know a better way to gather etcd-manager metrics?

Best regards

Łukasz Tomaszkiewicz
