### ISSUE TITLE
Running `kops update cluster` makes changes without the yes flag

### ISSUE THREAD

**Issue by bbck** [kubernetes/kops#7194]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.12.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.11.8 upgrading to 1.12.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops update cluster --out . --target terraform`

**5. What happened after the commands executed?**
Calico was upgraded on the cluster. Since when going from k8s 1.11 -> 1.12 this is a breaking change we lost networking on the cluster.

**6. What did you expect to happen?**
No changes are made to the running cluster.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: REDACTED
spec:
  additionalPolicies:
    node: |
      REDACTED
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    REDACTED
  cloudProvider: aws
  configBase: s3://REDACTED
  docker:
    bridgeIP: 172.31.0.1/16
    logDriver: json-file
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1e
      name: e
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1e
      name: e
    name: events
  hooks:
  - execContainer:
      command:
      - sh
      - -c
      - chroot /rootfs curl -o /tmp/install https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install
        && chroot /rootfs bash /tmp/install
      image: busybox
  - execContainer:
      command:
      - sh
      - -c
      - chroot /rootfs sysctl -w net.ipv4.neigh.default.gc_thresh1=0 && chroot /rootfs
        sysctl -w net.ipv4.neigh.default.gc_thresh2=32767 && chroot /rootfs sysctl
        -w net.ipv4.neigh.default.gc_thresh3=65535
      image: busybox
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    anonymousAuth: false
    oidcClientID: REDACTED
    oidcIssuerURL: REDACTED
    oidcUsernameClaim: REDACTED
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    resolvConf: /run/systemd/resolve/resolv.conf
  kubernetesApiAccess:
  - REDACTED
  kubernetesVersion: 1.12.8
  masterInternalName: api.internal.REDACTED
  masterPublicName: api.REDACTED
  networkCIDR: REDACTED
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - REDACTED
  subnets:
  - REDACTED
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Difficult to do since the cluster if already upgraded. If needed I can create a new one and follow the same upgrade process.

**9. Anything else do we need to know?**
This is probably a dupe of #2319. Because of the potential for this to cause breaking changes at the very least it should be documented that executing the command will make changes, especially for terraform users.
