### ISSUE TITLE
metrics-server: enable authenticationTokenWebhook

### ISSUE THREAD

**Issue by sdarwin** [kubernetes/kops#7200]
Per https://github.com/kubernetes-incubator/metrics-server/issues/133 , the metrics-server will not function on kops without these fixes.

1. --kubelet-insecure-tls added to metrics-server
2. authenticationTokenWebhook set on the kubelet  

kops edit cluster

```
kubelet:
     anonymousAuth: false
     authenticationTokenWebhook: true
     authorizationMode: Webhook
```
Although, minimalistically this is sufficient:
```
kubelet:
     anonymousAuth: false
     authenticationTokenWebhook: true
```

Since running a metrics server is pretty common, eliminating the extra steps would be convenient. 

Could the settings of "authenticationTokenWebhook: true" and "authorizationMode: Webhook" be configured by default on kops, so the end-user doesn't encounter unexpected errors when deploying metrics?

**Comment by sdarwin** [comment]
Investigating the issue a bit more, a question could be "Do other k8s installers also have this same problem? How do they solve it?"

1. Kubespray

Kubespray enables both Webhook authentication and authorization for the kubelet. Here's the kubelet-config.


root@node1:~# cat /etc/kubernetes/kubelet-config.yaml
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
nodeStatusUpdateFrequency: "10s"
failSwapOn: True
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: True
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.crt
authorization:
  mode: Webhook
staticPodPath: /etc/kubernetes/manifests
cgroupDriver: cgroupfs
maxPods: 110
address: 172.31.6.69
readOnlyPort: 0
kubeletCgroups: /systemd/system.slice
clusterDomain: cluster.local
clusterDNS:
- 169.254.25.10
kubeReserved:
  cpu: 200m
  memory: 512M
```

2. eksctl

eksctl also enables Webhook authentication and authorization for the kubelet. Here's the kubelet-config.

root@node1:~# cat /etc/eksctl/kubelet.yaml
```
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/eksctl/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
clusterDNS:
- 10.100.0.10
clusterDomain: cluster.local
featureGates:
  RotateKubeletServerCertificate: true
kind: KubeletConfiguration
serverTLSBootstrap: true
```
---

It might be kops is aiming for a generic kubernetes installation, which means keeping standard kubernetes default setting. That's potentially a reason to not enable Webhook. However, if --anonymous-auth=false is set, it's indicating "You can't connect anonymously, you must supply authentication credentials".  And how will that be done? Most often with service tokens. So, tokens should be allowed. Otherwise, an alternative could be to setting --anonymous-auth back to the default of "true".
