### ISSUE TITLE
kops create cluster with --authorization RBAC: kops validate cluster is failing

### ISSUE THREAD

**Issue by sagarpatkeatl** [kubernetes/kops#7242]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.12.2 (git-3fc9bc486)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
$ kops get cluster -o yaml | grep kubernetesVersion
  kubernetesVersion: 1.12.8
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. `kops create cluster -v 10 c2.*.* --zones ap-south-1a --master-size t2.medium --master-count 1 --node-size t2.medium --node-count 1 --authorization "RBAC"`
1. `kops edit cluster c2.k8s.local`, and added the following in spec:
```
  kubeAPIServer:
    authorizationRbacSuperUser: admin
```
1. `kops -v 10 update cluster c2.*.* --yes`

**5. What happened after the commands executed?**
After 90 mins, validation was failing with message: `The dns-controller Kubernetes deployment has not updated the Kubernetes cluster's API DNS entry to the correct IP address.  The API DNS IP address is the placeholder address that kops creates: 203.0.113.123.  Please wait about 5-10 minutes for a master to start, dns-controller to launch, and DNS to propagate.  The protokube container and dns-controller deployment logs may contain more diagnostic information.  Etcd and the API DNS entries must be updated for a kops Kubernetes cluster to start.`

**6. What did you expect to happen?**

Validation to pass

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-07-12T11:37:03Z
  name: c2
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-c2/c2
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authorizationRbacSuperUser: admin
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.8
  masterPublicName: api.c2
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/sagarpatkeatl/d9424f5611c117600d50641fce480f23

**9. Anything else do we need to know?**
Following Instructions from https://pracucci.com/kubernetes-rbac-with-kops.html
