### ISSUE TITLE
Metrics server unable to scrape nodes

### ISSUE THREAD

**Issue by jwsomis** [kubernetes/kops#7254]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`1.12.2`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
`AWS`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Using https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/v1.8.x.yaml for the metrics server with the below command
```
        command:
            - /metrics-server
            - --kubelet-preferred-address-types=InternalIP #,Hostname,ExternalIP
            - --kubelet-insecure-tls
            - --logtostderr
            - --v=10
```

**5. What happened after the commands executed?**
Metrics server logs these errors:
```
I0716 19:27:32.806587       1 round_trippers.go:405] POST https://100.64.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews 201 Created in 1 milliseconds
I0716 19:27:32.806603       1 round_trippers.go:411] Response Headers:
I0716 19:27:32.806609       1 round_trippers.go:414]     Content-Type: application/json
I0716 19:27:32.806613       1 round_trippers.go:414]     Content-Length: 294
I0716 19:27:32.806618       1 round_trippers.go:414]     Date: Tue, 16 Jul 2019 19:27:32 GMT
I0716 19:27:32.806659       1 request.go:897] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/","verb":"get"},"user":"system:anonymous","group":["system:unauthenticated"]},"status":{"allowed":false,"reason":"no RBAC policy matched"}}
I0716 19:27:32.806731       1 authorization.go:73] Forbidden: "/", Reason: "no RBAC policy matched"
I0716 19:27:32.806793       1 wrap.go:42] GET /: (2.364998ms) 403 [[Go-http-client/2.0] 10.91.5.210:14286]
I0716 19:27:32.836516       1 logs.go:49] http: TLS handshake error from 10.91.4.39:55630: EOF
```
and HPAs are unable to collect cpu metrics.

Additionally, if I set enableCustomMetrics to true, DNS is never able to resolve the api server even though the DNS record exists with the correct value.

**6. What did you expect to happen?**
Metrics server could collect metrics on nodes and HPAs would be able to get CPU metrics.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
Kops config file:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: k8s.dev.example.com
spec:
  additionalPolicies:
    node: | #Removed
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-bucket/k8s.dev.example.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    #enableCustomMetrics: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubeDNS:
    provider: CoreDNS
  kubernetesVersion: 1.12.8
  masterPublicName: api.k8s.dev.example.com
  networkCIDR: 10.0.0.0/16
  networkID: vpc-#############
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: eturi_vew_dev_2019
  subnets:
  - cidr: 10.0.3.0/24
    id: subnet-#############
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.0.4.0/24
    id: subnet-#############
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 10.0.5.0/24
    id: subnet-#############
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: 10.0.0.0/24
    id: subnet-#############
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 10.0.1.0/24
    id: subnet-#############
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 10.0.2.0/24
    id: subnet-#############
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
  name: master-us-west-2b
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b
  role: Master
  subnets:
  - us-west-2b

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.dev.example.com
  name: nodes
spec:
  additionalUserData:
  - name: get_vew_config.sh
    type: text/x-shellscript
    content: |
      #!/bin/bash
      exec > >(tee -a "/root/cloud-init.log") 2>&1'
      apt install -y chrony
      echo "server 169.254.169.123 prefer iburst" >> /etc/chrony/chrony.conf
      /etc/init.d/chrony restart
      mkdir /data
  cloudLabels:
    env: dev
    service: test
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.small
  maxSize: 7
  minSize: 2
#  mixedInstancePolicy:
#    onDemandBase: 2
#    onDemandAboveBase: 10 # the percentage of instances above base that should be On-Demand
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
