### ISSUE TITLE
Cannot add networking option for weave

### ISSUE THREAD

**Issue by denmaddog** [kubernetes/kops#7328]
When I try editing cluster I get this:

```
# Found fields that are not recognized
# ...
#     networking:
#       weave:
# +       NoMasqLocal: 1
#         mtu: 8912
```
The option  NoMasqLocal: 1 is the one I am trying to add.

KOPS version is:
Version 1.12.2 (git-3fc9bc486)

apiVersion: kops/v1alpha2

What am I missing here?

**Comment by denmaddog** [comment]
I managed to edit cluster with noMasqLocal: 1.
But even after forcing rolling-update this option is not in weave-net pods spec, as it is the case with MTU.
Any idea?

**Comment by denmaddog** [comment]
I've tried changing other options like MTU with kops edit cluster(updating cluster, deleting pod to be recreated), but the value stays the same:

```
  containers:
  - command:
    - /home/weave/launch.sh
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: IPALLOC_RANGE
      value: 100.96.0.0/11
    - name: WEAVE_MTU
      value: "8912"
    image: weaveworks/weave-kube:2.5.1
```
And in kops edit:

```
  networking:
    weave:
      mtu: 8913
      noMasqLocal: 1
  nonMasqueradeCIDR: 100.64.0.0/10
```
It looks like none of the options given to weave within kops are being considered when pod created.
