### ISSUE TITLE
dockerConfig: ipTables and IpMasq are ignored

### ISSUE THREAD

**Issue by maxbrunet** [kubernetes/kops#7367]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.12.1`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`1.11.10`

**3. What cloud provider are you using?**

`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```yaml
# config.yaml
apiVersion: kops/v1alpha2
 kind: Cluster
 metadata:
   ...
 spec:
   ...
   docker:
     ipMasq: true
     ipTables: true
```

```shell
kops replace -f config.yaml
kops update cluster
terraform apply
kops rolling-update cluster
```

**5. What happened after the commands executed?**

Rolling-update happens smoothly, but the Docker options are not set in `/etc/sysconfig/docker`:

```shell
DOCKER_OPTS=--ip-masq=false --iptables=false --log-driver=json-file --log-level=warn --log-opt=max-file=5 --log-opt=max-size=10m --storage-driver=overlay2
DOCKER_NOFILE=1000000
```

```shell
ps -fC dockerd
UID        PID  PPID  C STIME TTY          TIME CMD
root       957     1  3 17:06 ?        00:02:01 /run/torcx/bin/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock --selinux-enabled=true --ip-masq=false --iptables=false --log-driver=json-file --log-level=warn --log-opt=max-file=5 --log-opt=max-size=10m --storage-driver=overlay2
```

**6. What did you expect to happen?**

`--ip-masq` and `--iptables` are set to `true`.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

<details>

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-10-12T19:53:39Z
  name: k8s-cluster
spec:
  additionalPolicies: {} # REDACTED
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    ENV: k8s
  cloudProvider: aws
  configBase: s3://k8s-state/k8s-cluster
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a-1
      name: a-1
    - instanceGroup: master-us-west-2b-1
      name: b-1
    - instanceGroup: master-us-west-2c-1
      name: c-1
    name: main
    provider: Legacy
    version: 2.2.1
  - etcdMembers:
    - instanceGroup: master-us-west-2a-1
      name: a-1
    - instanceGroup: master-us-west-2b-1
      name: b-1
    - instanceGroup: master-us-west-2c-1
      name: c-1
    name: events
    provider: Legacy
    version: 2.2.1
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: # REDACTED
    oidcIssuerURL: # REDACTED
    oidcUsernameClaim: # REDACTED
  kubeDNS:
    provider: CoreDNS
  kubelet:
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  kubernetesApiAccess: [] # REDACTED
  kubernetesVersion: 1.11.10
  masterKubelet:
    kubeletCgroups: /systemd/system.slice
    runtimeCgroups: /systemd/system.slice
  masterPublicName: api.k8s-cluster
  networkCIDR: # REDACTED
  networking:
    calico:
      crossSubnet: true
  nonMasqueradeCIDR: # REDACTED
  sshAccess: # REDACTED
  subnets: {} # REDACTED
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-12T19:53:39Z
  labels:
    kops.k8s.io/cluster: k8s-cluster
  name: master-us-west-2a-1
spec:
  cloudLabels:
    Creator: kops-terraform
    Stack: k8s
  image: ami-0b2bce213b890b477
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a-1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-12T19:53:39Z
  labels:
    kops.k8s.io/cluster: k8s-cluster
  name: master-us-west-2b-1
spec:
  cloudLabels:
    Creator: kops-terraform
    Stack: k8s
  image: ami-0b2bce213b890b477
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2b-1
  role: Master
  subnets:
  - us-west-2b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-12T19:53:39Z
  labels:
    kops.k8s.io/cluster: k8s-cluster
  name: master-us-west-2c-1
spec:
  cloudLabels:
    Creator: kops-terraform
    Stack: k8s
  image: ami-0b2bce213b890b477
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c-1
  role: Master
  subnets:
  - us-west-2c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-10-12T19:53:39Z
  labels:
    kops.k8s.io/cluster: k8s-cluster
  name: nodes
spec:
  cloudLabels:
    Creator: kops-terraform
    Stack: k8s
  image: ami-0b2bce213b890b477
  machineType: m4.2xlarge
  maxSize: 9
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
  - us-west-2b
  - us-west-2c
```

</details>

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Unfortunately this is way too much details that I cannot share, we will see after discussion if any particular part is relevant to add to the issue.

**9. Anything else do we need to know?**

I'm trying to re-add the following docker iptables rule:

```shell
iptables -t nat -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
```

It is present in our other Kubernetes cluster deployed with kops 1.11.1 without these setting (default are `false`).
I have tried to set them to `true` manually in `/etc/sysconfig/docker` and restart the Docker daemon, and it works.
