### ISSUE TITLE
authorizationWebhookConfigFile field not recognized

### ISSUE THREAD

**Issue by driusha** [kubernetes/kops#7386]
**1. What `kops` version are you running?**
Version 1.14.0-alpha.3 (git-cd430998f)

**2. What Kubernetes version are you running?**
1.15.1

**3. What cloud provider are you using?**
gce

**7. Please provide your cluster manifest.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-07-20T19:47:06Z
  generation: 1
  name: polovov-sandbox-13.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://polovov-sandbox/polovov-sandbox-13.local
  docker:
    logDriver: ""
    version: 17.03.2
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-europe-west4-a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-europe-west4-a
      name: a
    name: events
  fileAssets:
  - content: |
      ...
    name: authorization-webhook
    path: /srv/kubernetes/assets/authorization-webhook.yaml
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authorizationMode: Webhook,RBAC
    authorizationWebhookConfigFile: /srv/kubernetes/assets/authorization-webhook.yaml
    featureGates:
      PodShareProcessNamespace: "true"
    runtimeConfig:
      batch/v2alpha1: "true"
  kubeControllerManager:
    featureGates:
      PodShareProcessNamespace: "true"
  kubeScheduler:
    featureGates:
      PodShareProcessNamespace: "true"
  kubelet:
    anonymousAuth: false
    featureGates:
      PodShareProcessNamespace: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.1
  masterInternalName: api.polovov-sandbox-13.k8s.local
  masterPublicName: api.polovov-sandbox-13.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: flant-sandbox
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: europe-west4
    region: europe-west4
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

I tried to add Webhook authorization mechanism to my existing cluster by configuring `.spec.kubeAPIServer.authorizationMode` and `.spec.kubeAPIServer.authorizationWebhookConfigFile`, but only `authorizationMode` option works and `authorizationWebhookConfigFile` is not recognized.

I think this issue is related to https://github.com/kubernetes/kops/issues/7321 and https://github.com/kubernetes/kops/pull/7344.
