### ISSUE TITLE
spotAllocationStrategy cannot be used with Diversified nor LowestPrice strategies

### ISSUE THREAD

**Issue by YenTheFirst** [kubernetes/kops#7405]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.12

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11

**3. What cloud provider are you using?**

AWS

**7. Please provide your cluster manifest.**
The relevant bit of manifest is
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my-cluster
  name: my-group
spec:
  cloudLabels:
    kops.k8s.io/instancegroup: my-group
  machineType: r4.16xlarge
  maxSize: 10
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: my-group
  role: Node
  mixedInstancesPolicy:
    instances:
    - r4.8xlarge
    - r4.16xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m5.12xlarge
    onDemandAboveBase: 30
    spotAllocationStrategy: <varies>
    spotInstancePools: 5
```

[note: the mixedInstancesPolicy is not included in the output of`kops get`, but it's in the manifest passed to kops, and it clearly has an effect on validation and in AWS requests]

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
# write a kops manifest.yaml including the above instance group
kops replace -f manifest.yaml
kops update cluster clustername
```

**5. What happened after the commands executed?**

when using `spotAllocationStrategy: lowest-price`, a kops validation error:
```
error: error replacing instanceGroup: my-group.spotAllocationStrategy: Invalid value: "lowest-price": unsupported spot allocation strategy
```

when using `spotAllocationStrategy: LowestPrice`, an AWS error:

```
W0814 00:55:07.268805      14 executor.go:130] error running task "AutoscalingGroup/my-group.my-cluster" (9m59s remaining to succeed): error updating AutoscalingGroup: ValidationError: SpotAllocationStrategy is invalid. Valid options are: [lowest-price, capacity-optimized].
```

when using `diversified`, `Diversified`, the same respective errors. And, as expected, both `capacity-optimized` and `CapacityOptimized` are validation errors, as that strategy is not yet supported.

**6. What did you expect to happen?**

I expected one of those values to pass validation and successfully create.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
Skipped.

**9. Anything else do we need to know?**

Multiple places refer to support for mixed instance types as using "EC2 fleet", including
* Documentation https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#creating-a-instance-group-of-mixed-instances-types-aws-only
* Comments on API: https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/instancegroup.go#L166
* The originating PR: https://github.com/kubernetes/kops/pull/6277

However, as far as I can tell, this is not actually making direct use of the AWS "EC2 Fleet" or "Spot Fleet" APIs, but is making use of AWS's ASG support for a MixedInstancePolicy. In particular, it seems that an "EC2 Fleet" supports `lowest-price`, `diversified`, and `capacity-optimized` (https://docs.aws.amazon.com/cli/latest/reference/ec2/create-fleet.html?highlight=fleet), while an Auto Scaling Group's mixed instance policy supports `lowest-price` and `capacity-optimized` (as suggested by the error message above, and https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-allocation-strategies)

Also, the rendered terraform seems to be adding a mixedInstancesPolicy to the ASG, not creating a separate fleet. https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go#L278
