### ISSUE TITLE
Add ability to configure additional EBS volume settings

### ISSUE THREAD

**Issue by kplimack** [kubernetes/kops#7409]
I am attaching additional EBS volumes to hold my logs.  In the event that a node is terminated, I have a job that can attach to disconnected EBS volumes and slurp up any logs on disk that may not have been shipped by fluent*.  

I found that this setting is hard coded here, https://github.com/kubernetes/kops/blob/3b0af771e88e236bab51bdc7390dd2c370b95ad3/pkg/model/awsmodel/autoscalinggroup.go#L215, 

I would like to be able to configure this along with my volume/volumemounts like so
```yaml
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /var/log
  volumes:
  - device: /dev/nvme1n1
    encrypted: true
    size: 500
    type: io1
    deleteOnTermination: false
```

If possible, Id also like to be able to configure the IOPS on this volume
