### ISSUE TITLE
Cloudformation templates for private topology clusters not correctly formatted

### ISSUE THREAD

**Issue by symbiont-tj-blair** [kubernetes/kops#7452]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops v1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

kubernetes 1.11.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I created a cluster cloudformation template using the following command

```
kops create cluster \
  --cloud aws \
  --topology private \
  --networking weave \
  --master-count 1 \
  --node-count 3 \
  --zones us-east-1c \
  --ssh-public-key ./newkey.pub \
  --kubernetes-version 1.11.9 \
  --state s3://tjb-sandbox-kops \
  --target cloudformation \
  my-cluster.tjb-sandbox.symdev.us
```

Afterwards I copied the template to s3 and created it with the following command

```
aws cloudformation create-stack \
  --capabilities CAPABILITY_NAMED_IAM \
  --stack-name kubernetes-my-cluster-tjb-sandbox-symdev-us \
  --template-url https://s3.amazonaws.com/tjb-cloudformation-templates/bad.json
```

**5. What happened after the commands executed?**

The cloudformation template generated in the expected location, however the elastic IP addresses and NAT gateways contain malformed cloudformation blocks.

EIP has a `Tags` block which is not supported by AWS:
```
"AWSEC2EIPuseast1cmyclustername": {
      "Type": "AWS::EC2::EIP",
      "Properties": {
        "Domain": "vpc",
        "Tags": [
          {
            "Key": "KubernetesCluster",
            "Value": "my-cluster-name"
          },
          {
            "Key": "Name",
            "Value": "us-east-1c.my-cluster-name"
          },
          {
            "Key": "kubernetes.io/cluster/my-cluster-name",
            "Value": "owned"
          }
        ]
      }
    }
```

NAT gateways contained a improperly formatted `tags` block:

```
    "AWSEC2NatGatewayuseast1cmyclustername": {
      "Type": "AWS::EC2::NatGateway",
      "Properties": {
        "AllocationId": {
          "Fn::GetAtt": [
            "AWSEC2EIPuseast1cmyclustername",
            "AllocationId"
          ]
        },
        "SubnetId": {
          "Ref": "AWSEC2Subnetutilityuseast1cmyclustername"
        },
        "tags": {
          "KubernetesCluster": "my-cluster-name",
          "Name": "us-east-1c.my-cluster-name",
          "kubernetes.io/cluster/my-cluster-name": "owned"
        }
      }
    }
```

Attempting to install this cloudformation template failed and forced an immediate rollback.

**6. What did you expect to happen?**

I expected the command to output properly formatted cloudformation that would install as expected.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-08-22T15:15:51Z
  name: my-cluster.tjb-sandbox.symdev.us
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://tjb-sandbox-kops/my-cluster.tjb-sandbox.symdev.us
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.9
  masterPublicName: api.my-cluster.tjb-sandbox.symdev.us
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.20.0.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-08-22T15:15:51Z
  labels:
    kops.k8s.io/cluster: my-cluster.tjb-sandbox.symdev.us
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-08-22T15:15:51Z
  labels:
    kops.k8s.io/cluster: my-cluster.tjb-sandbox.symdev.us
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

https://gist.github.com/symbiont-tj-blair/5fc5a97c071bf116d01a20959c61b6dd

**9. Anything else do we need to know?**

Tested this on kops dating back to 1.11.0, this was present in all versions.
