### ISSUE TITLE
Allow configurable kube-router version

### ISSUE THREAD

**Issue by cdobbyn** [kubernetes/kops#7469]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
The version deployed by kops should be updated (currently 0.1.0) and you should be able to configure your target version as part of the cluster spec.

The workaround today is to simply update the kube-router version in the daemonset post deploy.

**2. Feel free to provide a design supporting your feature request.**
Cluster configuration would look like this:
```
spec:
  networking:
    kuberouter:
      version: 0.3.2
```
