### ISSUE TITLE
Certain configuration may result in not able to bring up cluster.

### ISSUE THREAD

**Issue by hustshawn** [kubernetes/kops#7490]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
$ kops version --short
1.13.0
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
kubectl version --short
Client Version: v1.14.3
Unable to connect to the server: EOF
```
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kubectl create -f cluster.yaml`
The `cluster.yaml` definition
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: mycluster-masked
spec:
  api:
    loadBalancer:
      type: Public
      crossZoneLoadBalancing: true
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-k8s-state-store/mycluster-masked
  dnsZone: my-dns-zone-id
  kubeDNS:
    provider: CoreDNS
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    # allowPrivileged: true
    disableBasicAuth: true
    anonymousAuth: false
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditPolicyFile: /srv/kubernetes/audit.yaml
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
    # From best practice
    - Initializers
    - AlwaysPullImages
    - DenyEscalatingExec
    - PodSecurityPolicy
  kubelet:
    anonymousAuth: false
    enableCustomMetrics: true
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterPublicName: api.mycluster-masked
  networkCIDR: 10.6.0.0/16
  networkID: vpc-xxxxxx
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  sshKeyName: ifund-devops
  subnets:
  - cidr: 10.6.11.0/24
    id: subnet-xxxxxxxxxx
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: 10.6.13.0/24
    id: subnet-xxxxxxxxxx
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  - cidr: 10.6.15.0/24
    id: subnet-xxxxxxxxxx
    name: ap-southeast-1c
    type: Private
    zone: ap-southeast-1c
  - cidr: 10.6.12.0/24
    id: subnet-xxxxxxxxxx
    name: utility-ap-southeast-1a
    type: Utility
    zone: ap-southeast-1a
  - cidr: 10.6.14.0/24
    id: subnet-xxxxxxxxxx
    name: utility-ap-southeast-1b
    type: Utility
    zone: ap-southeast-1b
  - cidr: 10.6.16.0/24
    id: subnet-xxxxxxxxxx
    name: utility-ap-southeast-1c
    type: Utility
    zone: ap-southeast-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: mycluster-masked
  name: master-ap-southeast-1a
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1a
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: mycluster-masked
  name: master-ap-southeast-1b
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1b
  role: Master
  subnets:
  - ap-southeast-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: mycluster-masked
  name: master-ap-southeast-1c
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1c
  role: Master
  subnets:
  - ap-southeast-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: mycluster-masked
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c
```
**5. What happened after the commands executed?**
Cannot access to the cluster API, and the instance status in the API ELB are `OutOfService `
**6. What did you expect to happen?**
Can access to cluster API normally
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
As above.
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Before that, I made some changes on my existing cluster, especially in the `kubeAPIServer` and `kubelet` section on the cluster manifest. Since I wanna support `PodSecurityPolicy` and wanna have some security enhancement based on the security best practice document [here](https://github.com/hustshawn/kubernetes-security-best-practice/blob/master/kops.md) and [here](https://github.com/hustshawn/kubernetes-security-best-practice/blob/master/README.md#api-settings)
