### ISSUE TITLE
Why is kube-proxy started on master nodes?

### ISSUE THREAD

**Issue by mijo-md** [kubernetes/kops#7502]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.12.3 (git-e55205471)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.12.10

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Log on to any master node and run `docker ps | grep kube-proxy`.

**5. What happened after the commands executed?**

You will find that kube-proxy is running.

**6. What did you expect to happen?**

As most Kubernetes documentation and even kops documentation says, kube-proxy is usually only deployed on the nodes and not on the masters. I would expect that, unless the masters have been tainted to also double as nodes, the default action would be to _not_ deploy kube-proxy on the masters.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-08-30T11:00:02Z
  name: xxREMOVEDxx
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxREMOVEDxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: xxREMOVEDxx-aws-1a
    - instanceGroup: master-eu-west-1b
      name: xxREMOVEDxx-aws-1b
    - instanceGroup: master-eu-west-1c
      name: xxREMOVEDxx-aws-1c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: xxREMOVEDxx-aws-1a
    - instanceGroup: master-eu-west-1b
      name: xxREMOVEDxx-aws-1b
    - instanceGroup: master-eu-west-1c
      name: xxREMOVEDxx-aws-1c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    serviceNodePortRange: 3000-33000
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.10
  masterPublicName: api.xxREMOVEDxx
  networkCIDR: 172.20.0.0/16
  networkID: xxREMOVEDxx
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.128.0/19
    id: xxREMOVEDxx
    name: xxREMOVEDxx-aws.eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 172.20.160.0/19
    id: xxREMOVEDxx
    name: xxREMOVEDxx-aws.eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: 172.20.192.0/19
    id: xxREMOVEDxx
    name: xxREMOVEDxx-aws.eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
n/a

**9. Anything else do we need to know?**
n/a
