### ISSUE TITLE
stable channel documentation is stale for AMI in 1.13

### ISSUE THREAD

**Issue by geekofalltrades** [kubernetes/kops#7522]
Dispensing with the template in this case b/c it's a pretty straightforward report.

As of the 1.13 tag, the [images doc](https://github.com/kubernetes/kops/blob/1.13.0/docs/images.md#debian) points at the stable channel manifest as documentation for the AMI to use for Kops deployments.

At time of writing, the [manifest on master](https://github.com/kubernetes/kops/blob/master/channels/stable) only goes up to Kops/K8s 1.12. This is the latest entry:

```yaml
    - name: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
      providerID: aws
      kubernetesVersion: ">=1.12.0"
```

The [version on the 1.13 tag](https://github.com/kubernetes/kops/blob/1.13.0/channels/stable) is even more out of date, only going up to the 1.11 AMI.

1.13 AMIs do exist, though; I can see them when I search AMIs in the AWS console.

* k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-06-21
* k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16

So, it looks like the docs are out of date.

In our deployment, we start with this Debian AMI as a base and then apply customizations to it, so it's useful for us for the documentation to be up-to-date with the latest official version so we're not guessing at which image to use.
