### ISSUE TITLE
[AWS] dockerconfig not present in S3 Bucket state-store although permission is granted to this Resource

### ISSUE THREAD

**Issue by dminca** [kubernetes/kops#7554]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```sh
# create bucket to store state
aws s3 mb s3://my-state-store --region us-west-1

kops create cluster \
--name="kubernetes-cluster.example.com" \
--dns-zone="<ZONEIDHERE>" \
--vpc="vpc-<SOME-SAMPLE-ID>" \
--subnets="subnet-432j43h32424,subnet-4jk3234j24" \
--utility-subnets="subnet-8g8fgd8gfd8g,subnet-8dfgfdg8g79dg" \
--state=s3://my-state-store \
--authorization="RBAC" \
--zones="us-east-1d,us-east-1b,us-east-1c" \
--master-zones="us-east-1d,us-east-1b,us-east-1c" \
--kubernetes-version="1.13.10" \
--node-count=10 \
--node-size="m4.large" \
--master-size="m4.xlarge" \
--master-count=3 \
--dns=public \
--networking="weave" \
--topology=private \
--cloud=aws \
--ssh-public-key="./id_rsa.pub" \
--api-loadbalancer-type=internal \
--associate-public-ip="false" \
--network-cidr="172.x.x.x/20"
```

**5. What happened after the commands executed?**
Created a K8s cluster with the above configuration & also granted privilege to a `Resource`

```
"Resource": [
<snipped>
                "arn:aws:s3:::my-state-store/secrets/dockerconfig"
```

**6. What did you expect to happen?**
Since that particular **Resource** was granted access it should exist in the S3 Bucket, instead `my-state-store/secrets/dockerconfig` is not present in the bucket.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

<details>
  <summary>Click for details</summary>

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-05-16T07:39:59Z
  generation: 4
  name: kubernetes-cluster.example.com
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "ecr:*",
            "route53:*"
            ],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-kubernetes-cluster.example.com/kubernetes-cluster.example.com
  dnsZone: <SAMPLE_ZONE_ID>
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    name: main
    version: 3.2.24
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    featureGates:
      TTLAfterFinished: "true"
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    volumePluginDirectory: /var/lib/kubelet/volumeplugins
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterInternalName: api.internal.kubernetes-cluster.example.com
  masterPublicName: api.kubernetes-cluster.example.com
  networkCIDR: 172.x.x.x/20
  networkID: vpc-<SAMPLE_VPC_ID>
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.x.x.x/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.x.x.x/22
    id: subnet-<SAMPLE_SUBNET_ID>
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.x.x.x/22
    id: subnet-<SAMPLE_SUBNET_ID>
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.x.x.x/22
    id: subnet-<SAMPLE_SUBNET_ID>
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.x.x.x/24
    id: subnet-<SAMPLE_SUBNET_ID>
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.x.x.x/24
    id: subnet-<SAMPLE_SUBNET_ID>
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.x.x.x/24
    id: subnet-<SAMPLE_SUBNET_ID>
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-16T07:39:59Z
  labels:
    kops.k8s.io/cluster: kubernetes-cluster.example.com
  name: master-eu-central-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-16T07:39:59Z
  labels:
    kops.k8s.io/cluster: kubernetes-cluster.example.com
  name: master-eu-central-1b
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-16T07:39:59Z
  labels:
    kops.k8s.io/cluster: kubernetes-cluster.example.com
  name: master-eu-central-1c
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-16T07:40:00Z
  labels:
    kops.k8s.io/cluster: kubernetes-cluster.example.com
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: i3.large
  maxSize: 20
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```
</details>

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Can't do that, it's too much sensitive information

**9. Anything else do we need to know?**
Without the `dockerconfig` the Kubernetes cluster is not able to pull/push any images to any ECR, including those that reside in a separate AWS Account. One can have a K8s cluster in AWS Account A and try to pull images from ECR Account B and it'll fail miserably because the `dockerconfig` doesn't have the policy attached (or the file doesn't even exist in the S3 bucket).
