### ISSUE TITLE
Cannot change networking plugin due wrong detected etcd version

### ISSUE THREAD

**Issue by alex88** [kubernetes/kops#7575]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.13.10

**3. What cloud provider are you using?**

AWS

I've upgraded my cluster from 1.11 to 1.13.10 with the classic `kops upgrade cluster > update > rolling-upgrade`, my etcd config is:

```
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
```

I've tried to change my networking config from:

```
  networking:
    calico:
      mtu: 9001
```

to:

```
  networking:
    cilium: {}
```

due a bug that doesn't let you set the MTU in calico. After trying to save the config file I get this error:

```
error populating cluster spec: Spec.EtcdClusters[0].Version: Invalid value: "2.2.1": minimal version required is 3.1.0
```

however if I go to my etcd manager I see in the logs: `spec member_count:1 etcd_version:"3.2.24"` which makes me think that I have 3.2.24 and also because https://github.com/kubernetes/kops/blob/master/docs/etcd3-migration.md#default-upgrades says:

> When upgrading to kubernetes 1.12 with kops 1.12, by default:
> - Calico will be updated to a configuration that uses CRDs
> - We will automatically start using etcd-manager
> - Using etcd-manager will default to etcd3
> - Using etcd3 will default to using TLS for all etcd communications
