### ISSUE TITLE
cant deploy kops in aws china

### ISSUE THREAD

**Issue by creeram** [kubernetes/kops#7607]
kops version = Version 1.12.3 (git-e55205471")

cloud provider = AWS CHINA "ningxia region"   --gossib based-approach

--steps  followed :

*configured aws-cli that has access to :  
AmazonEC2FullAccess
AmazonS3FullAccess
IAMFullAccess
AmazonVPCFullAccess

*There is no route53 service in china so used a gossip-based approach.o 

created a aws s3 bucket to save the state.

cluster name: cluster.k8s.local

Then,

set the following environment variables:

export NAME=cluster.k8s.local
export KOPS_STATE_STORE=s3://cluster.k8s.kops
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)

then,

kops create cluster --node-count 2  --zones cn-northwest-1a --master-zones cn-northwest-1a --node-size t3.small --master-size t3.small --networking flannel --image "kops create cluster --node-count 2  --zones cn-northwest-1a --master-zones cn-northwest-1a --node-size t3.small --master-size t3.small --networking flannel --image "837727238323/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190628" --associate-public-ip=false --api-loadbalancer-type internal  --topology private --vpc vpc-ef3a8786   --subnets subnet-3bf73f40   --name ${NAME}" --associate-public-ip=false --api-loadbalancer-type internal  --topology private --vpc "vpc-id"  --subnets "subnet-id"   --name ${NAME}

added below mirror links by editing kops configuration file

assets:
    containerProxy: gcr.azk8s.cn/google_containers
docker:
    registryMirrors:
    - https://dockerhub.azk8s.cn

The cluster configuration is:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-09-17T11:46:00Z
  name: cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  assets:
    containerProxy: gcr.azk8s.cn/google_containers
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cluster.k8s.kops/cluster.k8s.local
  docker:
    registryMirrors:
    - https://dockerhub.azk8s.cn
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-cn-northwest-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
     allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.10
  masterInternalName: api.internal.cluster.k8s.local
  masterPublicName: api.cluster.k8s.local
  networkCIDR: 172.31.0.0/16
  networkID: vpc-ef3a8786
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.32.0/19
    name: cn-northwest-1a
    type: Private
    zone: cn-northwest-1a
  - cidr: 172.31.0.0/22
    name: utility-cn-northwest-1a
    type: Utility
    zone: cn-northwest-1a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
*kops updae cluster $name --yes

When i update the configuration file it doesnot throw any error successfully created a cluster.
but when i check loggin into the instances there are no kubernetes related files were installed like kubectl, kubeadm, etc. only the docker was installed.

also tired will higher resource instance to check if it was due to low system resources.
