### ISSUE TITLE
Kops Template has issues with  {{range $i, $az := .availability_zones.value}}

### ISSUE THREAD

**Issue by BrokenFlame** [kubernetes/kops#7615]
1. Kops Version: 1.13.0, on macOS Catalina
2. Kubernetes Version 1.14
3. Cloud Provider AWS
4. The command that has an issue is Kops Toolbox Template
```terminal
kops toolbox template --name ${CLUSTER_NAME} --values <( echo ${TF_OUTPUT}) --template cluster-template.yaml --format-yaml > cluster.yaml
```

**5. What happened after the commands executed?**
Template Renders and integrates once over the range function
```yaml
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{index $az $i}}
      name: {{ index $az $i | replace $.region.value "" }} {{/* converts eu-west-1a to a */}}
  {{end}}
```

OUTPUT:
```terminal
 etcdClusters:
  - etcdMembers:
    - instanceGroup: master-[eu-west-2a eu-west-2b eu-west-2c]
      name: a
    name: main
```

**6. What did you expect to happen?**
Iterate over the three elements in the array .availability_zones.value and render 
```yaml
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{index $az $i}}
      name: {{ index $az $i | replace $.region.value "" }} {{/* converts eu-west-1a to a */}}
  {{end}}
```

OUTPUT:
```terminal
 etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-2b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-2c
      name: c
    name: main
```

7. Cluster does not exits yet, however the template is as follows:
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{.kubernetes_cluster_name.value}}
spec:
  api:
    loadBalancer:
      type: Public
      additionalSecurityGroups: ["{{.common_http_sg_id.value}}"]
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.kops_s3_bucket.value}}/{{.kubernetes_cluster_name.value}}
  # Create one etcd member per AZ
  etcdClusters:
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{index $az $i}}
      name: {{ index $az $i | replace $.region.value "" }} {{/* converts eu-west-1a to a */}}
  {{end}}
    name: main
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{index $az $i}}
      name: {{ index $az $i | replace $.region.value "" }} {{/* converts eu-west-1a to a */}}
  {{end}}
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.10.6
  masterPublicName: api.{{.kubernetes_cluster_name.value}}
  networkCIDR: {{.vpc_cidr_block.value}}
  networkID: {{.vpc_id.value}}
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  # Public (utility) subnets, one per AZ
  {{range $i, $id := .public_subnet_ids.value}}
  - id: {{index . $i}}
    name: utility-{{index $.availability_zones.value $i}}
    type: Utility
    zone: {{index $.availability_zones.value $i}}
  {{end}}
  # Private subnets, one per AZ
  {{range $i, $id := .private_subnet_ids.value}}
  - id: {{.}}
    name: {{index $.availability_zones.value $i}}
    type: Private
    zone: {{index $.availability_zones.value $i}}
    egress: {{index $.nat_gateway_ids.value $i}}
  {{end}}
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---

# Create one master per AZ
{{range .availability_zones.value}}
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{$.kubernetes_cluster_name.value}}
  name: master-{{.}}
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{.}}
---
  {{end}}

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.kubernetes_cluster_name.value}}
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.small
  maxSize: 2
  minSize: 2
  role: Node
  subnets:
  {{range .availability_zones.value}}
  - {{.}}
  {{end}}
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
No debug output.

**9. Anything else do we need to know?**
The array .availability_zones.value contains: [eu-west-2a eu-west-2b eu-west-2c]

**Comment by mikesplain** [comment]
Hi @BrokenFlame, have you tried:
```
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{ $az }}
  {{end}}
```

You shouldn't need to use index there, and in fact, since your array isn't a map, you can just use:
```
{{range $az := .availability_zones.value}}
```

Hope this helps!

**Comment by BrokenFlame** [comment]
Hi @mikesplain, 
Thanks for your quick reply. However I have tried that and unfortunately, that renders a single instance of:
```yaml
  - etcdMembers:
    - instanceGroup: master-[eu-west-2a eu-west-2b eu-west-2c]
      name: a
    name: main
```
As you can see it just rendered the entire array inline:
```terminal
    - instanceGroup: master-[eu-west-2a eu-west-2b eu-west-2c]
```
I'm trying to get the array to render multiple blocks

I've also tried a very simply test:
```yaml
  subnets:
  {{range .availability_zones.value}}
  - {{.}} {{ "\n"}}
  {{end}}
```
But this did not render as expected either:
```terminal
subnets:
  - - eu-west-2a eu-west-2b eu-west-2c
```
the strange thing here was the double dash, at the beginning.

Does this provide any insight that might help?
