### ISSUE TITLE
wrong and old image version for kube-router

### ISSUE THREAD

**Issue by PascalBourdier** [kubernetes/kops#7640]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.13.10

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
$ kops create cluster --cloud aws  --networking kube-router
$ kubectl -n kube-system get ds kube-router -o jsonpath="{.spec.template.spec.containers[*].image}"

**5. What happened after the commands executed?**
it is not the good version (cloudnativelabs/kube-router:v0.1.0)

**6. What did you expect to happen?**
cloudnativelabs/kube-router:v0.3.1
according this file https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.12.yaml.template#L44

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-09-20T14:21:08Z
  name: poc-kops-1-13.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Team: SRE
    Usage: poc
  cloudProvider: aws
  configBase: s3://.../poc-kops-1-13.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    - instanceGroup: master-eu-west-1b
      name: b
    - instanceGroup: master-eu-west-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterPublicName: api.poc-kops-1-13.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kuberouter: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 172.20.64.0/19
    name: eu-west-1b
    type: Public
    zone: eu-west-1b
  - cidr: 172.20.96.0/19
    name: eu-west-1c
    type: Public
    zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-20T14:21:08Z
  labels:
    kops.k8s.io/cluster: poc-kops-1-13.k8s.local
  name: master-eu-west-1a
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-20T14:21:08Z
  labels:
    kops.k8s.io/cluster: poc-kops-1-13.k8s.local
  name: master-eu-west-1b
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-20T14:21:08Z
  labels:
    kops.k8s.io/cluster: poc-kops-1-13.k8s.local
  name: master-eu-west-1c
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-20T14:21:08Z
  labels:
    kops.k8s.io/cluster: poc-kops-1-13.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
NA

**9. Anything else do we need to know?**
no
