### ISSUE TITLE
IG with Mixed instances not working

### ISSUE THREAD

**Issue by rafaelsilvaa10** [kubernetes/kops#7680]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.13.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops edit ig testemix
kops update cluster 
kops rolling-update cluster
```

**5. What happened after the commands executed?**
New nodes were created in aws, however they did not have a status of "READY" in the cluster.

> message: validate cluster
> machine "i-LALA" has not yet joined cluster

**6. What did you expect to happen?**
I hoped that in my cluster would appear a new ig with nodes mix types

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  generation: 5
  labels:
    kops.k8s.io/cluster: myclustername
  name: testemix
spec:
  additionalSecurityGroups:
  - sg-asdadsa21
  cloudLabels:
    Project: infra
  image: coreos.com/CoreOS-stable-2079.3.0-hvm
  machineType: r4.xlarge
  maxSize: 10
  minSize: 2
  mixedInstancesPolicy:
    instances:
    - r4.8xlarge
    - r4.16xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m5.12xlarge
    onDemandAboveBase: 30
    spotInstancePools: 5
  nodeLabels:
    kops.k8s.io/instancegroup: testemix
    node: "true"
    role: node
  role: Node
  subnets:
  - XxXXXX
  - YYYYYY
  - ZZZZZZ
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I made this configuration following the tutorial: https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md

When I remove the configuration above the ig works normally.
