### ISSUE TITLE
Ability to Set CoreDNS Replicas in Cluster Spec

### ISSUE THREAD

**Issue by daviddyball** [kubernetes/kops#7726]
I'd love to have the ability to either:
a) configure HPA on `coredns` pods so that it scales with CPU usage or,
b) Edit my cluster spec and run `N` number of replicas e.g.
  ```
  spec:
  kubeDNS:
    provider: CoreDNS
    config:
      replicas: 4
  ```

If this is already possible it doesn't appear listed in the [cluster_spec docs](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md).
