### ISSUE TITLE
Deploying 1.13.10 with Calico does not complete

### ISSUE THREAD

**Issue by nelsonjr** [kubernetes/kops#7732]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
1.11.1
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0",
GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", 
BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", 
Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**
```
Amazon
```
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kkops create cluster --name xxx.yyy.net --dns-zone yyy.net --topology private
  --state s3://xxx-k8s --networking calico --kubernetes-version 1.13.10
  --zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c
  --master-zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c
  --api-loadbalancer-type internal --master-size t2.medium 
  --node-size c5.xlarge --node-count 3 
  --vpc vpc-xxxxxxxx
  --subnets subnet-aaa,subnet-bbb,subnet-ccc
  --utility-subnets subnet-ddd,subnet-eee,subnet-fff
  --ssh-public-key zzz.pub
```
**5. What happened after the commands executed?**
Nodes never get ready:
```
$ kubectl get nodes
NAME                                  STATUS     ROLES    AGE     VERSION
xxx.ap-southeast-1.compute.internal   NotReady   master   3m19s   v1.13.10
xxx.ap-southeast-1.compute.internal   NotReady   master   3m21s   v1.13.10
xxx.ap-southeast-1.compute.internal   NotReady   master   3m20s   v1.13.10
```
System pods did not start or fail:
```
$ kubectl get pod --all-namespaces
NAMESPACE     NAME                                       READY   STATUS       RESTARTS   AGE
kube-system   calico-complete-upgrade-v331-vzxh5         0/1     Pending      0          4m9s
kube-system   calico-kube-controllers-6f576fdc84-m4xbz   0/1     Pending      0          4m9s
kube-system   calico-node-pq24z                          0/2     Init:Error   5          4m2s
kube-system   calico-node-wt9j5                          0/2     Init:0/1     5          4m3s
kube-system   calico-node-xtbcr                          0/2     Init:Error   5          4m1s
kube-system   dns-controller-7b65774bc-569g2             0/1     Pending      0          4m8s
... etcd ... Running
... kube-apiserver ... Running
... kube-controller ... Running
kube-system   kube-dns-859d8bc8bb-4g7rs                  0/3     Pending      0          4m8s
... kube-proxy-ip ... Running
... kube-scheduler ... Running
```
**6. What did you expect to happen?**
```
Master nodes to be ready eventually.
```
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-10-02T08:42:29Z
  name: xxx.yyy.net
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx-k8s/xxx.yyy.net
  dnsZone: yyy.net
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    name: main
    version: 3.2.24
  - etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    - instanceGroup: master-ap-southeast-1b
      name: b
    - instanceGroup: master-ap-southeast-1c
      name: c
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterPublicName: api.xxx.yyy.net
  networkCIDR: x.x.x.x/16
  networkID: vpc-xxx
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: y.y.y.y/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: a.a.a.a/22
    id: subnet-aaaaa
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: b.b.b.b/22
    id: subnet-bbbbb
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  - cidr: c.c.c.c/22
    id: subnet-ccccc
    name: ap-southeast-1c
    type: Private
    zone: ap-southeast-1c
  - cidr: d.d.d.d4
    id: subnet-ddddd
    name: utility-ap-southeast-1a
    type: Utility
    zone: ap-southeast-1a
  - cidr: e.e.e.e/24
    id: subnet-eeeee
    name: utility-ap-southeast-1b
    type: Utility
    zone: ap-southeast-1b
  - cidr: f.f.f.f/24
    id: subnet-fffff
    name: utility-ap-southeast-1c
    type: Utility
    zone: ap-southeast-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
N/A
```
**9. Anything else do we need to know?**
- Same script worked before to create 1.11.0 cluster.
- Changing networking from `calico` to `weave` deployment succeeds.
