### ISSUE TITLE
AutoScalingGroup Notifications - Gauging Interest

### ISSUE THREAD

**Issue by joshbranham** [kubernetes/kops#7737]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
We have a use case of setting up notifications on our AWS `AutoScalingGroups` for production clusters. Currently, we do this via an out of band process any time we recreate `InstanceGroups` or build a new cluster. I am posting this to see if others have a use case for this and if so I will look into implementing it. 

**2. Feel free to provide a design supporting your feature request.**
The solution would be to add an array of `notifications` to the `InstanceGroup` spec, where you would provide an array of notifications and a destination SNS ARN. Below is an example of how I would see it represented. Let me know if this would be useful to you :)

```
kind: InstanceGroup
spec:
  notifications:
  - arn: <sns arn>
    notifications:
    - autoscaling:TEST_NOTIFICATION
    - autoscaling:EC2_INSTANCE_LAUNCH
    - autoscaling:EC2_INSTANCE_TERMINATE
```
