### ISSUE TITLE
Wrong number of spot instances created in ig

### ISSUE THREAD

**Issue by mohammadasim** [kubernetes/kops#7817]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.12.1`
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:52:31Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`
**3. What cloud provider are you using?**
`AWS`
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops create cluster` then run the command `kops edit ig nodes` I then added the configuration for spot instances, which consisted of 2 on demand and 2 spot. I then run the command  `kops create cluster --yes`
**5. What happened after the commands executed?**
The cluster was created without any issues and I could validate the cluster.
**6. What did you expect to happen?**
I expected that 4 worker nodes to be created 2 on demand and 2 spot instances, instead 1 on demand and 3 spot instances were created.
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
    apiVersion: kops/v1alpha2
    kind: InstanceGroup
    metadata:
      creationTimestamp: 2019-10-22T11:46:02Z
      labels:
        kops.k8s.io/cluster: <my-cluster name>
      name: nodes
    spec:
      image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190406
      machineType: t2.medium
      maxSize: 4
      minSize: 2
      mixedInstancesPolicy:
        instances:
        - t2.medium
        - t3.medium
        - c5d.large
        - t3a.medium
        onDemandAboveBase: 2
        spotInstancePools: 2
      nodeLabels:
        kops.k8s.io/instancegroup: nodes
      role: Node
      subnets:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
