### ISSUE TITLE
Prevent eviction of pods weave addon with priorityClassName

### ISSUE THREAD

**Issue by jochen42** [kubernetes/kops#7873]
**1. Problem description**

Weave Pods should never be evicted because it would break the node networking and impacts the whole cluster.

**2. Solution from [weaveworks](https://github.com/weaveworks/weave/issues/3691)**

```yaml
daemonSet:
  spec:
    template:
      spec:
        priorityClassName: system-node-critical
```
