### ISSUE TITLE
Kops attempts to delete external targetGroups it does not own

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/kops#8058]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.12.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.12.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops delete cluster --yes

**5. What happened after the commands executed?**
```
I1208 10:56:02.760872     103 errors.go:32] unexpected aws error code: "ResourceInUse"

target-group:arn:aws:elasticloadbalancing:xx-yy-z:123456:targetgroup/xxx/xxxxxxxxxxxxxxxx	error deleting resources, will retry: error deleting TargetGroup "arn:aws:elasticloadbalancing:xx-yy-z:123456:targetgroup/xxx/xxxxxxxxxxxxxxxx": ResourceInUse: Target group 'arn:aws:elasticloadbalancing:xx-yy-z:123456:targetgroup/xxx/xxxxxxxxxxxxxxxx' is currently in use by a listener or a rule

	status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**6. What did you expect to happen?**
For Kops to not try to delete a target group which it did not create

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: abc.cluster.k8s.local
  name: mno
spec:
  additionalSecurityGroups:
    - sg-xxxxxxxxxxxxxxxxx
  externalLoadBalancers:
    - targetGroupArn: arn:aws:elasticloadbalancing:xx-yy-z:123456:targetgroup/xxx/xxxxxxxxxxxxxxxx
  image: 595879546273/CoreOS-stable-2303.3.0-hvm
  machineType: c5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: mno
    role: mno
    service: mno
  role: Node
  subnets:
    - xx-yy-za
  taints:
    - role=mno:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Target group was constructed in Terraform and the tags
```
KubernetesCluster: abc.cluster.k8s.local
Env: abc
kubernetes.io/cluster/abc.cluster.k8s.local: shared
```
were added in Terraform before the ARN of the target group was passed in under `externalLoadBalancers`.
