### ISSUE TITLE
Tutorial "Getting Started with kops on AWS" can't get EC2 instance running

### ISSUE THREAD

**Issue by nodje** [kubernetes/kops#8097]
`kops  1.15.0`
`kubctl v1.17.0`
Using AWS

`kops create cluster --zones us-west-1a ${NAME} -v10 > create.log 2>&1`
`kops update cluster ${NAME} --yes -v10 > update.log 2>&1`
See [gist ](https://gist.github.com/nodje/7f854d00284ced9ce031e2db8084709f) for these two files content

ASAICS most infrastructure parts got instantiated BUT the master & nodes EC2 instances

As it seems only EC2 instances were not created and as I don't see any log from what I suppose is doing the `run-instance`:
```
Executing task "LaunchConfiguration/nodes.kops.domain.com": *awstasks.LaunchConfiguration {"Name":"nodes.kops.domain.com","Lifecycle":"Sync","AssociatePublicIP":true,"BlockDeviceMappings":null,"IAMInstanceProfile":{"Name":"nodes.kops.domain.com","Lifecycle":"Sync","ID":"AIPASIGZOYE6M4L7A7DKZ","Shared":false},"ID":null,"ImageID":"kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26","InstanceMonitoring":null,"InstanceType":"t2.medium","RootVolumeIops":null,"RootVolumeOptimization":null,"RootVolumeSize":128,"RootVolumeType":"gp2","SSHKey":{"Name":"kubernetes.kops.domain.com-4a:b2:1d:c3:59:bf:d9:a9:ba:93:72:03:05:e9:f4:c2","Lifecycle":"Sync","PublicKey":{"Name":"","Resource":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1aWKcsCEQV7fEVed7D8+UQKo4gmM8EKWmFirX1iPSO3eX5cQzHhVyQ/hK4rYPLqOybB3OTUNLFjjeSlvsS+yj1+5DrNjqdX5XDCqpJTKJZJBALuPzRNgBmCPZ7eRk3sHzgU4cXqJxVlX135yQIK+ii6oGCKD6JWWHUCo3SQKtiIQHyMI8j3XXvanJhHUlbLhO/BKSkNd/3ER24IPdMmKl+3LuvsR3UhDGdB3F3m4l+Y8RWq2bOyffgTfv4zGRJFNPuBD+afICXsd07p8s5xAmZLL3x///uQr9Hmw5zwb6zVnciT+1s0hxn/MK6OWGABNOhqTYBpunxsceirSDzqRHNd3b7dG9DR+Foek/xELVXCJ+wJXEhA9wBMSO38eJTSUXfId66MbfQB5qvMwxTvoOmJA+AW/9CPawmrZgSYxkALNhkbVY9PLCMnDhl7NqLOpHp8OSLY1owsRc/bRH9l8wHpuBVR0qrZ70KP/w4j9WrQ5g+ygf3H5Q+OjA5SO6mhk= user@work.domain.com\n"},"KeyFingerprint":"7a:af:26:50:e2:e2:39:38:e2:f6:08:07:4f:b3:86:45"},"SecurityGroups":[{"Name":"nodes.kops.domain.com","Lifecycle":"Sync","ID":"sg-09a4e42acee69cf69","Description":"Security group for nodes","VPC":{"Name":"kops.domain.com","Lifecycle":"Sync","ID":"vpc-00d891ddc03f86a0d","CIDR":"172.20.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":false,"Tags":{"KubernetesCluster":"kops.domain.com","Name":"kops.domain.com","kubernetes.io/cluster/kops.domain.com":"owned"}},"RemoveExtraRules":["port=22"],"Shared":null,"Tags":{"KubernetesCluster":"kops.domain.com","Name":"nodes.kops.domain.com","kubernetes.io/cluster/kops.domain.com":"owned"}}],"SpotPrice":"","Tenancy":null,"UserData":{"Name":"","Resource":{}}}
```
I've tried to run this JSON config as `aws ec2 run-instances --cli-input-json file://ec2runinst.json` just to try to make sure I was able to create EC2 instances from awscli.
But I got a `a bytes-like object is required, not 'dict'`

Could there be a JSON syntax problem in the awstasks.LaunchConfiguration  ????

See below output for `kops get --name ${NAME} -o yaml`
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-12-12T13:18:38Z"
  name: kops.domain.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-domain-com-state-store/kops.domain.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.5
  masterPublicName: api.kops.domain.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-1a
    type: Public
    zone: us-west-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-12T13:18:38Z"
  labels:
    kops.k8s.io/cluster: kops.domain.com
  name: master-us-west-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-1a
  role: Master
  subnets:
  - us-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-12T13:18:38Z"
  labels:
    kops.k8s.io/cluster: kops.domain.com
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-1a

```
