### ISSUE TITLE
Update cluster command starts actual rollout

### ISSUE THREAD

**Issue by grem11n** [kubernetes/kops#8136]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Initial cluster is provisioned with `kops 1.14.0`:
```
kops-1.14.0 version
Version 1.14.0 (git-d5078612f)
```

Upgrade is done with `kops` version `1.15.0`:
```
kops version
Version 1.15.0 (git-9992b4055)
```

Feature flags for Spotinst are enabled (this may be an actual issue):
```
KOPS_FEATURE_FLAGS="+Spotinst,SpotinstOcean"
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Initial cluster is version `v1.14.6`:
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Upgrade version: `v1.15.6`

**3. What cloud provider are you using?**

AWS with Spotinst integration

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Different scenarios to upgrade the cluster version.

Scenario 1:

`kops upgrade cluster --yes` <== works fine
`kops update cluster --yes` <== starts an update and rolling out new nodes, which causes an issues

Scenario 2:

Modify the cluster manifests for both cluster and instance groups:
`kops edit cluster` and `kops edit ig XXX` <== works fine
`kops update cluster --yes` <== starts an update and rolling out new nodes, which causes an issues

Scenario 3:

Modify the local manifest and apply with:
`kops update cluster --config kops_cluster.test.yaml --yes` <== starts an update and rolling out new nodes, which causes an issues

**5. What happened after the commands executed?**

After `kops update cluster --yes`, new instances are provisioned. Rolling upgrade command shows that no rollout is required:

```
kops rolling-update cluster   
Using cluster from kubectl context: test.k8s.local

NAME                    STATUS  NEEDUPDATE      READY   MIN     MAX     NODES
master-eu-central-1a    Ready   0               0       1       1       0
master-eu-central-1b    Ready   0               0       1       1       0
master-eu-central-1c    Ready   0               1       1       1        0
nodes                             Ready   0               3       3       10    0

No rolling-update required.
```

Since old master nodes are still exist, new nodes cannot attach EBS volumes for `etcd`. Therefore, `etcd` cannot start. 

```
kops validate cluster
Using cluster from kubectl context: test.k8s.local

Validating cluster test.k8s.local

INSTANCE GROUPS
NAME			ROLE	MACHINETYPE					MIN	MAX	SUBNETS
master-eu-central-1a	Master	t3.medium					1	1	eu-central-1a
master-eu-central-1b	Master	t3.medium					1	1	eu-central-1b
master-eu-central-1c	Master	t3.medium					1	1	eu-central-1c
nodes			Node	m4.large,m3.large,c4.large,c3.large,t3.xlarge	3	10	eu-central-1a,eu-central-1b,eu-central-1c

NODE STATUS
NAME						ROLE	READY
ip-10-110-1-223.eu-central-1.compute.internal	node	True
ip-10-110-2-10.eu-central-1.compute.internal	node	True
ip-10-110-3-87.eu-central-1.compute.internal	node	True

VALIDATION ERRORS
KIND	NAME			MESSAGE
Machine	i-05e9b32d78c62bb22	machine "i-05e9b32d78c62bb22" has not yet joined cluster
Machine	i-09113d6b72efd92a9	machine "i-09113d6b72efd92a9" has not yet joined cluster
Machine	i-0ecfab2e866e8d8dd	machine "i-0ecfab2e866e8d8dd" has not yet joined cluster

Validation Failed
```

As a workaround, you can terminate old master nodes in AWS one by one and wait for EBS volumes to attach to the new masters

**6. What did you expect to happen?**

1. `kops update cluster --yes` just modifies config in S3 bucket
2. Actual rollout happens after `kops rolling-update cluster --yes`. Rolling upgrade terminates old nodes first, so an issue with EBS volumes doesn't occur.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
<...>
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-1a
      name: a
    - instanceGroup: master-1b
      name: b
    - instanceGroup: master-1c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.3.13
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-1a
      name: a
    - instanceGroup: master-1b
      name: b
    - instanceGroup: master-1c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.3.13
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
<...>
  kubernetesVersion: 1.14.6
  masterPublicName: api.test.k8s.local
  networkCIDR: 10.110.0.0/16
  networkID: <...>
  networking:
    cni: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.110.0.0/16
  subnets:
<...>
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: test.k8s.local
  name: master-1a
spec:
  additionalSecurityGroups:
<...>
  associatePublicIp: false
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-1a
  role: Master
  subnets:
<...>

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: test.k8s.local
  name: master-1b
spec:
  additionalSecurityGroups:
<...>
  associatePublicIp: false
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-1b
  role: Master
  subnets:
<..>

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-17T10:40:34Z"
  labels:
    kops.k8s.io/cluster: test.k8s.local
  name: master-1c
spec:
  additionalSecurityGroups:
<...>
  associatePublicIp: false
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-1c
  role: Master
  subnets:
<...>

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: test.k8s.local
    spotinst.io/ocean-default-launchspec: "true"
  name: nodes
spec:
  additionalSecurityGroups:
<...>
  associatePublicIp: false
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m4.large,m3.large,c4.large,c3.large,t3.xlarge
  maxSize: 10
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
<...>
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

As a workaround, you can terminate old master nodes one by one in AWS.
