### ISSUE TITLE
Bastions: Remove additionalUserData

### ISSUE THREAD

**Issue by nvanheuverzwijn** [kubernetes/kops#8330]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
run `kubectl edit ig bastions`
add this to the template :
```
  additionalUserData:
  - content: |
      #!/bin/sh
      echo "Hello World.  The time is now $(date -R)!" | tee /root/output.txt
    name: myscript.sh
    type: text/x-shellscript 
```
`kubectl update cluster`
`kubectl update cluster --yes`
`kubectl edit ig bastions`
remove the additionalUserData
`kubectl update cluster`

**5. What happened after the commands executed?**
additionalUserdata is not removed

**6. What did you expect to happen?**
additionalUserdata to be removed

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**
