### ISSUE TITLE
Partition "aws" is not valid for resource "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxx" in us-gov-west-1 region

### ISSUE THREAD

**Issue by lazzarello** [kubernetes/kops#8359]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.15.0 (git-9992b4055)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.14

**3. What cloud provider are you using?**

AWS Govcloud

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
export CLUSTER_NAME="mission.control"
export AMI_NAME="414987029474/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16"
kops create cluster --image=${AMI_NAME} --dns=private --zones=us-gov-west-1a --name=${CLUSTER_NAME}
```

**5. What happened after the commands executed?**

W0116 21:06:48.637367   15823 executor.go:130] error running task "IAMRolePolicy/masters.mission.control" (5m59s remaining to succeed): error creating/updating IAMRolePolicy: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxx".
	status code: 400, request id: 724f2a61-375c-49f5-952e-110372e0c12d

**6. What did you expect to happen?**

The cluster is created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-01-17T05:01:42Z"
  name: mission.control
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mission-control-state-store/mission.control
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.6
  masterPublicName: api.mission.control
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-gov-west-1a
    type: Public
    zone: us-gov-west-1a
  topology:
    dns:
      type: Private
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-17T05:01:43Z"
  labels:
    kops.k8s.io/cluster: mission.control
  name: master-us-gov-west-1a
spec:
  image: 414987029474/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-gov-west-1a
  role: Master
  subnets:
  - us-gov-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-17T05:01:43Z"
  labels:
    kops.k8s.io/cluster: mission.control
  name: nodes
spec:
  image: 414987029474/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-gov-west-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Looks like this is the relevant JSON for the policy failure

```
    {
      "Effect": "Allow",
      "Action": [
        "route53:ChangeResourceRecordSets",
        "route53:ListResourceRecordSets",
        "route53:GetHostedZone"
      ],
      "Resource": [
        "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxx"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "route53:GetChange"
      ],
      "Resource": [
        "arn:aws:route53:::change/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "route53:ListHostedZones"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ecr:GetAuthorizationToken",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        "ecr:GetRepositoryPolicy",
        "ecr:DescribeRepositories",
        "ecr:ListImages",
        "ecr:BatchGetImage"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

**9. Anything else do we need to know?**

This looks similar to #6763
