### ISSUE TITLE
Openstack - impossible to define dns servers for existing network when installing without router

### ISSUE THREAD

**Issue by shreben** [kubernetes/kops#8362]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.16.0-alpha.1 (git-ea779042c)`
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`1.15.6`
**3. What cloud provider are you using?**
`openstack`
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Install cluster without floating network and using existing networks with predefined dns servers
**5. What happened after the commands executed?**
```
[2020-01-17T12:54:12.440Z] I0117 12:54:12.311522     314 executor.go:103] Tasks: 99 done / 126 total; 1 can run
[2020-01-17T12:54:12.440Z] I0117 12:54:12.311568     314 executor.go:176] Executing task "Subnet/my_existing_subnet": *openstacktasks.Subnet {"ID":"8ba6623f-806b-4d39-9693-58d3e0ecb4a6","Name":"my_existing_subnet","Network":{"ID":"30612834-46b8-4225-8126-81161fce265b","Name":"my_existing_subnet_name","Lifecycle":"Sync","Tag":"my_cluster_name"},"CIDR":"10.99.36.0/22","DNSServers":[],"Tag":"my_cluster_name","Lifecycle":"Sync"}

[2020-01-17T12:54:13.370Z] I0117 12:54:13.061362     314 changes.go:81] Field changed "DNSServers" actual="[0xc000a2f620 0xc000a2f630 0xc000a2f640 0xc000a2f650]" expected="[]"
[2020-01-17T12:54:13.370Z] I0117 12:54:13.061415     314 changes.go:81] Field changed "Tag" actual="" expected="my_cluster_name"
[2020-01-17T12:54:13.370Z] W0117 12:54:13.062151     314 executor.go:128] error running task "Subnet/my_existing_subnet" (8s remaining to succeed): Field cannot be changed: DNSServers
```
**6. What did you expect to happen?**
cluster to be deployed.
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: my_cluster_name
spec:
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
    terminatedPodGCThreshold: 1000
    featureGates:
      TTLAfterFinished: "true"
  api:
    loadBalancer:
      type: Private
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    openstack:
      blockStorage:
        bs-version: v2
        ignore-volume-az: false
      loadbalancer:
        subnetID: 8ba6623f-806b-4d39-9693-58d3e0ecb4a6
        method: ROUND_ROBIN
        provider: octavia
        useOctavia: true
      monitor:
        delay: 1m
        maxRetries: 3
        timeout: 30s
  cloudProvider: openstack
  configBase: swift://my_cluster_name/my_cluster_name
  docker:
    logDriver: json-file
    logOpt:
    - max-size=100m
    - max-file=2
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-nova-1
      name: "1"
      volumeType: ceph
    - instanceGroup: master-nova-2
      name: "2"
      volumeType: ceph
    - instanceGroup: master-nova-3
      name: "3"
      volumeType: ceph
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-nova-1
      name: "1"
      volumeType: ceph
    - instanceGroup: master-nova-2
      name: "2"
      volumeType: ceph
    - instanceGroup: master-nova-3
      name: "3"
      volumeType: ceph
    memoryRequest: 100Mi
    name: events
  fileAssets:
...
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeScheduler:
    featureGates:
      TTLAfterFinished: "true"
  kubeProxy:
    featureGates:
      TTLAfterFinished: "true"
  kubeAPIServer:
    featureGates:
      TTLAfterFinished: "true"
    admissionControl:
    - NodeRestriction
    - AlwaysPullImages
    - NamespaceLifecycle
    - PodSecurityPolicy
    - ServiceAccount
    - DefaultTolerationSeconds
    - LimitRanger
    - DefaultStorageClass
    - PersistentVolumeLabel
    - ResourceQuota
    - DenyEscalatingExec
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditPolicyFile: /srv/kubernetes/assets/audit.yaml
    authenticationTokenWebhookConfigFile: /srv/kubernetes/webhook-guard-config
    logLevel: 1
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.6
  masterKubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    readOnlyPort: 0
    kubeletCgroups: "/podruntime.slice/podruntime-kubelet.slice"
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    readOnlyPort: 0
    kubeletCgroups: "/podruntime.slice/podruntime-kubelet.slice"
    kubeReserved:
        cpu: 125m
        memory: 1Gi
    kubeReservedCgroup: "/podruntime.slice"
    enforceNodeAllocatable: "pods,kube-reserved"
  masterPublicName: api.my_cluster_name
  networkCIDR: 10.99.36.0/22
  networkID: 30612834-46b8-4225-8126-81161fce265b
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.99.36.0/22
    id: 8ba6623f-806b-4d39-9693-58d3e0ecb4a6
    name: nova
    type: Private
    zone: nova
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Hi
I'm deploying a cluster into openstack. All the networking exists and preconfigured by network team. Setup assumes there is no floating network. Cluster config is shown above.
Eventually my deployment job failed because of mismatch between existing DNS servers assigned to existing network and kops configuration. From what I've found looks like  it's impossible to define DNS servers for existing subnet.
Subnet configuration:
https://github.com/kubernetes/kops/blob/1c37a328e1a76563f3fb2a41b9353675653650b4/pkg/model/openstackmodel/network.go#L67
DNS servers cannot be assigned here because I don't use router https://github.com/kubernetes/kops/blob/1c37a328e1a76563f3fb2a41b9353675653650b4/pkg/model/openstackmodel/network.go#L71
Even if I define router.dnsServers I cannot use this option because in that case it assumes usage of floating network without any variants https://github.com/kubernetes/kops/blob/c323819e6480d71bad8d21184516e3162eaeca8f/upup/pkg/fi/cloudup/openstack/cloud.go#L423
Please correct me if I'm wrong in my assumptions or suggest a way to deploy cluster without floating network.
