### ISSUE TITLE
Updating networking results in an empty /etc/cni/net.d/

### ISSUE THREAD

**Issue by brownds14** [kubernetes/kops#8405]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.13.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops edit cluster` -> Updated networking from canal to calico
`kops update cluster --yes`
`kops rolling-update cluster --cloudonly --force --master-interval=1s --node-interval=1s --yes`

**5. What happened after the commands executed?**
Terminated then recreated new masters and nodes. Quite a few pods are in pending, and the masters are unable to join the cluster. Inspecting the /etc/cni/net.d/ directory shows that it is empty.

**6. What did you expect to happen?**
Masters and nodes would be terminated and recreated. Masters would join the cluster, then nodes, and pods would be running. /etc/cni/net.d/ should have reference to calico and there should be a Calico DaemonSet running in the kube-system namespace.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-09-27T18:47:24Z"
  generation: 6
  name: <cluster-name>
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: <removed>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterInternalName: api.internal.<cluster-name>
  masterPublicName: api.<cluster-name>
  networkCIDR: 10.102.0.0/18
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.102.8.0/21
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.102.16.0/21
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.102.24.0/21
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.102.0.0/24
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.102.1.0/24
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.102.2.0/24
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.<cluster-name>
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-09-27T18:47:24Z"
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: bastions
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-09-27T18:47:24Z"
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-09-27T18:47:24Z"
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-09-27T18:47:24Z"
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-09-27T18:47:24Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m5.large
  maxSize: 9
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
* The Calico Daemonset is missing and the /etc/cni/net.d/ directory is empty
* Using `journalctl -u kubelet` I can see this warning and error repeated frequently.
```
ip-10-102-27-124 kubelet[2393]: W0123 15:17:24.720235    2393 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d/
ip-10-102-27-124 kubelet[2393]: E0123 15:17:24.721044    2393 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
* I've tried looking through some old issues and posts on other websites. There are some issues that appear similar, but the bug was resolved. Some posts recommended just restarting kubelet, but I've had no luck with that either.
