### ISSUE TITLE
Kops doesnt upgrade weave Version (1.15.7 - 2.5.1)

### ISSUE THREAD

**Issue by atze234** [kubernetes/kops#8437]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.0 (git-9992b4055)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops upgrade cluster --yes
kops update cluster --yes
kops rolling-update cluster --yes

**5. What happened after the commands executed?**
Weave still running Version 2.5.1
**6. What did you expect to happen?**
Weave should run Version 2.5.2 (and have prometheus scrape annotations)

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
  networking:
    weave:
      mtu: 8912
```

**9. Anything else do we need to know?**

I expect weave Version 2.5.2 with Prometheus annotations in my Cluster, not 2.5.1.
We're runniung other Clusters, where this update worked. 

Can i manually set the Weave Version anyhow? I'd rather let kops do the updates in the future automagically. 
Or will i have to overwrite the Weave Deamonset manually?

Best Regards
Joerg

**Comment by atze234** [comment]
The yaml in State Store addons/networking.weave/k8s-1.12.yaml is the right one, but its not applied in cluster.

**Comment by johngmyers** [comment]
What were you upgrading from?

**Comment by atze234** [comment]
This time from 1.15.6, but it should have upgraded weave long time earlier i think.
Dont know the version with the weave upgrade. In my other clusters the 2.5.2 was installed even with 1.15.6.

**Comment by johngmyers** [comment]
Kops stores the version of the manifest it installed in the annotations of the `kube-system` Namespace resource. It would be useful to report that.

**Comment by atze234** [comment]
Hi, sorry for late answer...
Annotations here:
```
    addons.k8s.io/core.addons.k8s.io: '{"version":"1.4.0","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","manifestHash":"3ffe9ac576f9eec72e2bdfbd2ea17d56d9b17b90"}'
    addons.k8s.io/dns-controller.addons.k8s.io: '{"version":"1.15.0","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","id":"k8s-1.12","manifestHash":"c2d7e7d9fba2375a615ad51f0b7b4ca0bdd61d25"}'
    addons.k8s.io/kube-dns.addons.k8s.io: '{"version":"1.14.13-kops.1","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","id":"k8s-1.12","manifestHash":"b4dff071aa340fd71650c96f213fdf4b4f799c71"}'
    addons.k8s.io/kubelet-api.rbac.addons.k8s.io: '{"version":"v0.0.1","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","id":"k8s-1.9","manifestHash":"e1508d77cb4e527d7a2939babe36dc350dd83745"}'
    addons.k8s.io/limit-range.addons.k8s.io: '{"version":"1.5.0","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","manifestHash":"2ea50e23f1a5aa41df3724630ac25173738cc90c"}'
    addons.k8s.io/networking.weave: '{"version":"2.5.1-kops.1","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","id":"k8s-1.8"}'
    addons.k8s.io/rbac.addons.k8s.io: '{"version":"1.8.0","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","id":"k8s-1.8","manifestHash":"5d53ce7b920cd1e8d65d2306d80a041420711914"}'
    addons.k8s.io/storage-aws.addons.k8s.io: '{"version":"1.15.0","channel":"s3://<redacted>/addons/bootstrap-channel.yaml","id":"v1.15.0","manifestHash":"23459f7be52d7c818dc060a8bcf5e3565bd87a7b"}'

```

Sounds outdated?

**Comment by johngmyers** [comment]
I suppose the next question is what the contents of `"s3://<redacted>/addons/bootstrap-channel.yaml"` are.

It's looking like it's not updating the addon at all, not updating it with the k8s-1.8.yaml.

**Comment by atze234** [comment]
Hi @johngmyers ,

i've already posted the relevant part of `bootstrap-channel.yaml` above.

Anyway, this is the whole file:

```
kind: Addons
metadata:
  creationTimestamp: null
  name: bootstrap
spec:
  addons:
  - manifest: core.addons.k8s.io/v1.4.0.yaml
    manifestHash: 3ffe9ac576f9eec72e2bdfbd2ea17d56d9b17b90
    name: core.addons.k8s.io
    selector:
      k8s-addon: core.addons.k8s.io
    version: 1.4.0
  - id: pre-k8s-1.6
    kubernetesVersion: <1.6.0
    manifest: kube-dns.addons.k8s.io/pre-k8s-1.6.yaml
    manifestHash: 895c961cb9365cbedb22edd20a7648182ae7ed3f
    name: kube-dns.addons.k8s.io
    selector:
      k8s-addon: kube-dns.addons.k8s.io
    version: 1.14.13-kops.1
  - id: k8s-1.6
    kubernetesVersion: '>=1.6.0 <1.12.0'
    manifest: kube-dns.addons.k8s.io/k8s-1.6.yaml
    manifestHash: 191685ca6fe009302e55512b0eefc5a676433f10
    name: kube-dns.addons.k8s.io
    selector:
      k8s-addon: kube-dns.addons.k8s.io
    version: 1.14.13-kops.1
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: kube-dns.addons.k8s.io/k8s-1.12.yaml
    manifestHash: b4dff071aa340fd71650c96f213fdf4b4f799c71
    name: kube-dns.addons.k8s.io
    selector:
      k8s-addon: kube-dns.addons.k8s.io
    version: 1.14.13-kops.1
  - id: k8s-1.8
    kubernetesVersion: '>=1.8.0'
    manifest: rbac.addons.k8s.io/k8s-1.8.yaml
    manifestHash: 5d53ce7b920cd1e8d65d2306d80a041420711914
    name: rbac.addons.k8s.io
    selector:
      k8s-addon: rbac.addons.k8s.io
    version: 1.8.0
  - id: k8s-1.9
    kubernetesVersion: '>=1.9.0'
    manifest: kubelet-api.rbac.addons.k8s.io/k8s-1.9.yaml
    manifestHash: e1508d77cb4e527d7a2939babe36dc350dd83745
    name: kubelet-api.rbac.addons.k8s.io
    selector:
      k8s-addon: kubelet-api.rbac.addons.k8s.io
    version: v0.0.1
  - manifest: limit-range.addons.k8s.io/v1.5.0.yaml
    manifestHash: 2ea50e23f1a5aa41df3724630ac25173738cc90c
    name: limit-range.addons.k8s.io
    selector:
      k8s-addon: limit-range.addons.k8s.io
    version: 1.5.0
  - id: pre-k8s-1.6
    kubernetesVersion: <1.6.0
    manifest: dns-controller.addons.k8s.io/pre-k8s-1.6.yaml
    manifestHash: 1144516823c61328d746e2ee6a00437b9d22d1b6
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 1.15.0
  - id: k8s-1.6
    kubernetesVersion: '>=1.6.0 <1.12.0'
    manifest: dns-controller.addons.k8s.io/k8s-1.6.yaml
    manifestHash: 5168087b30e61f8149e51a7394fccb272b5a9dd8
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 1.15.0
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: dns-controller.addons.k8s.io/k8s-1.12.yaml
    manifestHash: c2d7e7d9fba2375a615ad51f0b7b4ca0bdd61d25
    name: dns-controller.addons.k8s.io
    selector:
      k8s-addon: dns-controller.addons.k8s.io
    version: 1.15.0
  - id: v1.15.0
    kubernetesVersion: '>=1.15.0'
    manifest: storage-aws.addons.k8s.io/v1.15.0.yaml
    manifestHash: 23459f7be52d7c818dc060a8bcf5e3565bd87a7b
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.0
  - id: v1.7.0
    kubernetesVersion: '>=1.7.0 <1.15.0'
    manifest: storage-aws.addons.k8s.io/v1.7.0.yaml
    manifestHash: 62705a596142e6cc283280e8aa973e51536994c5
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.0
  - id: v1.6.0
    kubernetesVersion: <1.7.0
    manifest: storage-aws.addons.k8s.io/v1.6.0.yaml
    manifestHash: 7de4b2eb0521d669172038759c521418711d8266
    name: storage-aws.addons.k8s.io
    selector:
      k8s-addon: storage-aws.addons.k8s.io
    version: 1.15.0
  - id: pre-k8s-1.6
    kubernetesVersion: <1.6.0
    manifest: networking.weave/pre-k8s-1.6.yaml
    manifestHash: 32d430ee79854844fa084818e85aacb5f0e031d0
    name: networking.weave
    selector:
      role.kubernetes.io/networking: "1"
    version: 2.3.0-kops.3
  - id: k8s-1.6
    kubernetesVersion: '>=1.6.0 <1.7.0'
    manifest: networking.weave/k8s-1.6.yaml
    manifestHash: acb88149827e2f211235099d3f5e1f991ff2c2cc
    name: networking.weave
    selector:
      role.kubernetes.io/networking: "1"
    version: 2.3.0-kops.3
  - id: k8s-1.7
    kubernetesVersion: '>=1.7.0 <1.8.0'
    manifest: networking.weave/k8s-1.7.yaml
    manifestHash: 13eeb613fc135ad26b3959a47fa3374f323954ee
    name: networking.weave
    selector:
      role.kubernetes.io/networking: "1"
    version: 2.5.2-kops.2
  - id: k8s-1.8
    kubernetesVersion: '>=1.8.0 <1.12.0'
    manifest: networking.weave/k8s-1.8.yaml
    manifestHash: 331ac726e3ff2c1d7094223beaa8464b94fc8a70
    name: networking.weave
    selector:
      role.kubernetes.io/networking: "1"
    version: 2.5.2-kops.2
  - id: k8s-1.12
    kubernetesVersion: '>=1.12.0'
    manifest: networking.weave/k8s-1.12.yaml
    manifestHash: 21fcbac5e303ee79bb0111c0e3475a230ebaf85b
    name: networking.weave
    selector:
      role.kubernetes.io/networking: "1"
    version: 2.5.2-kops.2
```

**Comment by johngmyers** [comment]
So the version in the annotation is 2.5.1-kops.1, which appears nowhere in the current bootstrap-channel. The other addons match, so it was likely some problem applying the manifests. Perhaps it attempted to change an immutable field or something.

I would try to track down the relevant log file where `channels` applied the addon. I believe that's inside `protokube` with a prefix "error running channels:".

**Comment by atze234** [comment]
The Update should have happened weeks/months ago. Unfortunately there aint no more logs from this time at my systems. I may have a look at current systems on Monday.

The Question is now: How to to this properly so that kops can update automatically in the future? Just apply the ‘k8s-1.12.yaml‘ from state and update the annotation?

**Comment by johngmyers** [comment]
Since I don't know what went wrong in the first place, I can't say how to ensure it doesn't happen in the future.

I believe you should be able to get another log file by doing another `kops update cluster --yes`, possibly followed by another rolling update in order to get another attempt at running `channels`. Or you could try running `channels` directly.

**Comment by atze234** [comment]
Hi, this is protokubes Output:

```
I0210 11:54:50.430750   31872 channel_version.go:105] Checking existing channel: Version=1.15.0 Channel=s3://<redacted>/addons/bootstrap-channel.yaml Id=k8s-1.12 ManifestHash=c2d7e7d9fba2375a615ad51f0b7b4ca0bdd61d25 compared to new channel: Version=1.15.0 Channel=s3://<redacted>/addons/bootstrap-channel.yaml Id=k8s-1.12 ManifestHash=c2d7e7d9fba2375a615ad51f0b7b4ca0bdd61d25
I0210 11:54:50.430777   31872 channel_version.go:132] Manifest Match
NAME			CURRENT		UPDATE
networking.weave	2.5.1-kops.1	2.5.2-kops.2
I0210 11:54:50.432979   31872 channel_version.go:105] Checking existing channel: Version=2.5.1-kops.1 Channel=s3://<redacted>/addons/bootstrap-channel.yaml Id=k8s-1.8 compared to new channel: Version=2.5.2-kops.2 Channel=s3://<redacted>/addons/bootstrap-channel.yaml Id=k8s-1.12 ManifestHash=21fcbac5e303ee79bb0111c0e3475a230ebaf85b
I0210 11:54:50.435352   31872 channel_version.go:125] New Version is greater then old
I0210 11:54:50.435385   31872 addon.go:141] Applying update from "s3://<redacted>/addons/networking.weave/k8s-1.12.yaml"
I0210 11:54:50.435418   31872 s3fs.go:220] Reading file "s3://<redacted>/addons/networking.weave/k8s-1.12.yaml"
I0210 11:54:50.531323   31872 apply.go:67] Running command: kubectl apply -f /tmp/channel494428740/manifest.yaml
I0210 11:54:50.777362   31872 apply.go:70] error running kubectl apply -f /tmp/channel494428740/manifest.yaml
I0210 11:54:50.777390   31872 apply.go:71] serviceaccount/weave-net unchanged
clusterrole.rbac.authorization.k8s.io/weave-net unchanged
clusterrolebinding.rbac.authorization.k8s.io/weave-net unchanged
role.rbac.authorization.k8s.io/weave-net unchanged
rolebinding.rbac.authorization.k8s.io/weave-net unchanged
The DaemonSet "weave-net" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"name":"weave-net", "role.kubernetes.io/networking":"1"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Error: error updating "networking.weave": error applying update from "s3://<redacted>/addons/networking.weave/k8s-1.12.yaml": error running kubectl

```

**Comment by johngmyers** [comment]
Yes, you'll need to delete the `DaemonSet`.

**Comment by johngmyers** [comment]
The only change to the `labelSelector` is in 9a06ff550cf4ceffcbe5a7f28e0bd962bdc5bec2, which changed the `DaemonSet` from `extensions/v1beta1` to `apps/v1`. Presumably this started happening when you first upgraded Kubernetes across the 1.12 boundary. And presumably it is the implicit value of the field from `extensions/v1beta1` that is immutable.

**Comment by atze234** [comment]
I added with kubectl edit `role.kubernetes.io/networking: "1"` to immutable Field, which wasnt immutable then:

So before:
```
spec:
  selector:
    matchLabels:
      name: weave-net
```
after:

```
spec:
  selector:
    matchLabels:
      name: weave-net
      role.kubernetes.io/networking: "1"
```

protokube immediately updated the Deamonset to weave-2.5.2 then:

```
I0211 08:45:43.506939    6880 channel_version.go:125] New Version is greater then old
I0211 08:45:43.506958    6880 addon.go:141] Applying update from "s3://<redacted>/addons/networking.weave/k8s-1.12.yaml"
I0211 08:45:43.506989    6880 s3fs.go:220] Reading file "s3://<redacted>/addons/networking.weave/k8s-1.12.yaml"
I0211 08:45:43.606063    6880 apply.go:67] Running command: kubectl apply -f /tmp/channel852261328/manifest.yaml
I0211 08:45:43.849528    6880 channel_version.go:192] sending patch: "{\"metadata\":{\"annotations\":{\"addons.k8s.io/networking.weave\":\"{\\\"version\\\":\\\"2.5.2-kops.2\\\",\\\"channel\\\":\\\"s3://<redacted>/addons/bootstrap-channel.yaml\\\",\\\"id\\\":\\\"k8s-1.12\\\",\\\"manifestHash\\\":\\\"21fcbac5e303ee79bb0111c0e3475a230ebaf85b\\\"}\"}}}"
Updated "networking.weave" to 2.5.2-kops.2
```

Wonder why this worked back last year in my other clusters out of the box. Since it wasnt immutable after all...strange thing. 
Anyway the "Problem" now is, that the apiVersion of the Daemonset still is `extensions/v1beta1` (all  older clusters)
That would be a problem when `extensions/v1beta1` deprecates in `1.16` ?
Maybe there should be a hint/fix for 1.15 -> 1.16 upgrades in release Notes then?
