### ISSUE TITLE
Terraform output not supporting all components configs

### ISSUE THREAD

**Issue by linecolumn** [kubernetes/kops#8463]
Using: Version 1.17.0-alpha.2 (git-5db135e3b)

Just found out that not all component configs (https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go) are supported when exporting KOPS to Terraform.

Some of them are present, but some are not (for e.g. kubeControllerManagers):

```
NodeMonitorPeriod
NodeMonitorGracePeriod
NodeStatusUpdateFrequency
PodEvictionTimeout
AttachDetachReconcileSyncPeriod
[...]
```

cluster.yaml file:
``` 
kubeControllerManager:
    NodeMonitorPeriod: 4s
    NodeMonitorGracePeriod: 20s
    NodeStatusUpdateFrequency: 6s
    PodEvictionTimeout: 55s
    AttachDetachReconcileSyncPeriod: 22s
```

Unfortunately, on masters this changes are not reflected when using terraform apply.

Please make all components configs _exportable_ in Terraform output.

**Comment by carnivorelogic** [comment]
Listed keywords are case-sensitive, first letter should be lower-case, like this:

```
kubeControllerManager:
    nodeMonitorPeriod: 4s
    nodeMonitorGracePeriod: 20s
    podEvictionTimeout: 55s
    attachDetachReconcileSyncPeriod: 22s
```

Also, `nodeStatusUpdateFrequency: 6s` should be moved to Kubelet department.
