### ISSUE TITLE
Create cluster ignoring/crashing on additional network CIDRs 

### ISSUE THREAD

**Issue by db3net** [kubernetes/kops#8470]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.15.0 (git-9992b4055)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.17.0"

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create an additional CIDR range within existing VPC. In this case, our default was 10.152.0.0/16. We added 10.153.0.0/16. 

Then we created 6 new subnets for the cluster in availability zones a,b,c . 3 had public, 3 had private routing

We then ran the following "cops create cluster" command specifying subnets.

```kops create cluster --cloud aws --topology private --dns-zone Z1TIPCAZF9A2CT --ssh-public-key /home/kops/.ssh/k8sdev.pub --networking calico --vpc vpc-0MYVPCID0000  --subnets subnet-000000000000A,subnet-000000000000B,subnet-0000000000C --utility-subnets subnet-000000000000000a,subnet-000000000000000b,subnet-000000000000000c --master-size t2.medium --node-size t2.medium --zones us-east-1a,us-east-1b,us-east-1c --state s3://myco-k8s-state --node-count 3 --master-count 3 --name admin.k8s.aws.mycompany.com --api-loadbalancer-type internal --bastion=false```

Error....

`spec.Subnets[0].CIDR: Invalid value: "10.153.8.0/26": Subnet "us-east-1a" had a CIDR "10.153.8.0/26" that was not a subnet of the NetworkCIDR "10.152.0.0/16"`

We ran it again with ``` network-cidr 10.153.0.0/16 ``` with dry-run flag and it generated the YAML correctly (will paste below)

We edited the kops YAML file and added 

```
  additionalNetworkCIDRs:
  - 10.153.0.0/16
  - 10.152.0.0/16
```

**5. What happened after the commands executed?**
Received 
```error running task "VPC/admin.k8s.mycompany.com" (9m59s remaining to succeed): CIDR: Invalid value: "10.153.0.0/16": field is immutable: old="10.152.0.0/16" new="10.153.0.0/16"```

**6. What did you expect to happen?**
We expected it to just work by deriving CIDR from the specific subnets OR from the specified network-cidr . I believe it's using the first CIDR in the VPC and ignoring the others. 

**7. Please provide your cluster manifest. 
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTiredactcotamp: "2020-02-04T16:37:52Z"
  name: admin.k8s.aws.redactco.com
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://redactco-k8s-state/admin/admin.k8s.aws.redactco.com
  dnsZone: Z1TIPCAZF9A2CT
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.7
  masterPublicName: api.admin.k8s.aws.redactco.com
  networkCIDR: 10.153.0.0/16
  networkID: vpc-0975426780e4582b8
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.153.8.0/26
    id: subnet-00b4fc2cd00a7e022
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.153.8.64/26
    id: subnet-04bb41ba3a171fbfa
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.153.8.128/26
    id: subnet-0fdc9b610314c2bab
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.153.248.0/26
    id: subnet-0d492a24d62eff560
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.153.248.64/26
    id: subnet-03475c4c3cb572033
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.153.248.128/26
    id: subnet-0e1252a322e4f8a79
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTiredactcotamp: "2020-02-04T16:37:52Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.redactco.com
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTiredactcotamp: "2020-02-04T16:37:52Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.redactco.com
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTiredactcotamp: "2020-02-04T16:37:52Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.redactco.com
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTiredactcotamp: "2020-02-04T16:37:52Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.redactco.com
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-04T16:19:06Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.myco.com
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-04T16:19:06Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.myco.com
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-04T16:19:06Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.myco.com
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-04T16:19:06Z"
  labels:
    kops.k8s.io/cluster: admin.k8s.aws.myco.com
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

See - https://gist.github.com/db3net/1b5a1b1b7ce0afac5059fb053cb88892

**9. Anything else do we need to know?**
