### ISSUE TITLE
Setting Custom Kernel Runtime Parameters not working

### ISSUE THREAD

**Issue by linecolumn** [kubernetes/kops#8508]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.17.0-alpha.2 (git-5db135e3b)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.17.2

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**Case 1:**

1. `kops create cluster         --cloud aws   --zones eu-central-1a,eu-central-1b,eu-central-1c         --master-size t3.medium         --master-zones eu-central-1a,eu-central-1b,eu-central-1c         --ssh-public-key ~/.ssh/id_rsa.pub         --node-size t3.medium         --node-count 1       ${NAME}`

2. manually edit instance group and add wanted block (as per https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#setting-custom-kernel-runtime-parameters)

`# kops edit ig nodes`

insert in appropriate place:

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-07T11:49:46Z"
  labels:
    kops.k8s.io/cluster: platform.k8s.local
  name: nodes
spec:
  sysctlParameters:
    - net.ipv4.tcp_sack=0
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.medium
[..]
```
save file and exit. Immediately repeat  `# kops edit ig nodes` and notice that **there is no sysctlParameters block inside**.

**Case 2.**

1. `kops create cluster         --cloud aws   --zones eu-central-1a,eu-central-1b,eu-central-1c         --master-size t3.medium         --master-zones eu-central-1a,eu-central-1b,eu-central-1c         --ssh-public-key ~/.ssh/id_rsa.pub         --node-size t3.medium         --node-count 1       ${NAME}`

2. export kops to one big cluster.yaml with `kops get --name $NAME -o yaml > cluster.yaml`

edit cluster.yaml and insert in same block:

```
sysctlParameters:
  - net.ipv4.tcp_sack=0
```
to all instance groups and kind: Cluster group

3. deploy cluster with `kops update ... --yes`

4. all instances (master, nodes) are not having changes applied

I see that last commits were from @ripta, thus referencing him in order to check this issue.
