### ISSUE TITLE
Can't create/use multiple subnets on GCE

### ISSUE THREAD

**Issue by HagaiBarel** [kubernetes/kops#8615]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.2 (git-ad595825a)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.9

**3. What cloud provider are you using?**
`gce`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Scenario 1:
Create a cluster from command line (do not update yet) on `gce`
Edit the cluster spec
Add additional subnets
Run `kops update cluster --yes`
No new subnets are created and the VM are being created in the default GCE subnet

Scenario 2:
Create the VPC and subnets by hand/api/terrafrom
Edit the cluster spec so it will use `networkID: <value from above>`
Run `kops update cluster`
`kops` tries to change the VPC mode custom -> auto

```
Will modify resources:
  Network/kops-net
  	Mode                	 custom -> auto
```

**5. What happened after the commands executed?**
In scenario 1, all the VM are launched in the default VPC and subnet. In Scenario 2, the `kops update` action times out and fails as the network mode can't be changed.

**6. What did you expect to happen?**
Multiple subnets created in the same region with the specified cidr ranges

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

The relevant section of the manifest is:
```
networkID: "kops-net"
subnets:
- name: europe-west1b
  region: europe-west1
  type: Private
  cidr: 10.105.0.0/20
- name: europe-west1c
  region: europe-west1
  type: Private
  cidr: 10.105.16.0/20
- name: europe-west1d
  region: europe-west1
  type: Private
  cidr: 10.105.32.0/20
```
This correlates to scenario 2 as above, I've pre-created the VPC (kops-net) and the subnets with the same names and cidr blocks
