### ISSUE TITLE
Is gossip-based dns +  private topology + "DNS access to master nodes" a valid configuration?

### ISSUE THREAD

**Issue by pai911** [kubernetes/kops#8624]
Hi gurus!

I started out with a cluster with private topology +  gossip-based DNS, and everything worked just fine!

But since I don't want to pay for the extra ELB for HA, I surveyed for a little while and found that kops supports a way to [allow access to the master node with dns](https://github.com/kubernetes/kops/blob/9bf2818b858df0bcbbfba9e8d48ae856a5fd936f/docs/cluster_spec.md#api).

But the result didn't look quite what I expected. I still couldn't access the master node.

I'd like to know if gossip-based DNS +  private topology + "DNS access to master nodes" a valid configuration?

I felt like I should also configure DNS as described [here](https://github.com/kubernetes/kops/blob/master/docs/getting_started/aws.md#configure-dns), but I wasn't really sure about it.

Could anyone shed some light on this?

Thanks!

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.15.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I am just testing with 1 worker node

kops create cluster ${NAME} \
    --node-count 1 \
    --zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c \
    --node-size t3.micro \
    --master-size t3.small \
    --master-zones ap-southeast-1a \
    --topology private \
    --networking weave \
    --image [KOPS-DEBIAN-IMAGE] \
    --ssh-public-key [MY-SSH-KEY]

- Configure Cluster
1. Use dns access for master nodes
```
api:
 dns: {}
```

**5. What happened after the commands executed?**
A master **master-ap-southeast-1a.masters.solrcluster.k8s.local** is created
A node **nodes.solrcluster.k8s.local** is created

**6. What did you expect to happen?**

I hoped to access the master node without additional ELB.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-02-25T02:24:21Z"
  generation: 1
  name: solrcluster.k8s.local
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://XXXX-example-com-state-store/solrcluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-southeast-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.9
  masterInternalName: api.internal.solrcluster.k8s.local
  masterPublicName: api.solrcluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: 172.20.64.0/19
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  - cidr: 172.20.96.0/19
    name: ap-southeast-1c
    type: Private
    zone: ap-southeast-1c
  - cidr: 172.20.0.0/22
    name: utility-ap-southeast-1a
    type: Utility
    zone: ap-southeast-1a
  - cidr: 172.20.4.0/22
    name: utility-ap-southeast-1b
    type: Utility
    zone: ap-southeast-1b
  - cidr: 172.20.8.0/22
    name: utility-ap-southeast-1c
    type: Utility
    zone: ap-southeast-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-25T02:24:22Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: solrcluster.k8s.local
  name: master-ap-southeast-1a
spec:
  image: XXXXX
  kubelet:
    failSwapOn: false
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-southeast-1a
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-25T02:24:22Z"
  labels:
    kops.k8s.io/cluster: solrcluster.k8s.local
  name: nodes
spec:
  image: XXXXX
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
