### ISSUE TITLE
k8s 1.16.7 node fails to go to Ready state in mixed 1.15,1.16 master cluster

### ISSUE THREAD

**Issue by MMeent** [kubernetes/kops#8690]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.16.0 (git-4b0e62b82)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster; kops rolling-update cluster;

NOTE: autoscaler scaled other nodes in new configuration during master updates.

**5. What happened after the commands executed?**

Node failed to enter ready state (not within 30m at least): 
```
Mar  6 17:46:16 ip-10-128-34-90 kubelet[2293]: E0306 17:46:16.872107    2293 pod_workers.go:191] Error syncing pod 90ece95b-90f4-4427-ac45-91d30028a28c ("fluentd-internal-5m7ll_kube-logging(90ece95b-90f4-4427-ac45-91d30028a28c)"), skipping: network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR
```

**6. What did you expect to happen?**

Node should go to ready in 5 minutes.

**7. Please provide your cluster manifest.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-02-05T11:31:39Z"
  generation: 18
  name: <cluster-name>
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://<cluster-name>-cluster-state-store/<cluster-name>
  etcdClusters:
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
    provider: Manager
    version: 3.3.13
  - enableEtcdTLS: true
    enableTLSAuth: true
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
    provider: Manager
    version: 3.3.13
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogFormat: json
    auditLogMaxAge: 31
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-audit
    enableAdmissionPlugins:
    - AlwaysPullImages
    - SecurityContextDeny
    - PodSecurityPolicy
    - ServiceAccount
    - NodeRestriction
    - StorageObjectInUseProtection
    featureGates:
      CSIMigrationAWS: "true"
    tlsCipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_128_GCM_SHA256
  kubeControllerManager:
    horizontalPodAutoscalerUpscaleDelay: 30s
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    tlsCipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_128_GCM_SHA256
  kubernetesApiAccess:
  - 10.131.0.0/16
  - 10.132.0.0/16
  - 10.130.16.0/20
  kubernetesVersion: 1.16.7
  masterInternalName: api.internal.<cluster-name>
  masterPublicName: api.<cluster-name>
  networkCIDR: 10.128.0.0/16
  networkID: vpc-8004e6eb
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.131.0.0/16
  - 10.132.0.0/16
  subnets:
  - cidr: 10.128.32.0/22
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 10.128.36.0/22
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  - cidr: 10.128.40.0/22
    name: eu-central-1c
    type: Public
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:09:53Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: ci-nodes-az-a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label/<cluster-name>/role: ci
    k8s.io/cluster-autoscaler/node-template/taint/<cluster-name>/role: ci:NoSchedule
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.xlarge
  maxSize: 2
  minSize: 0
  nodeLabels:
    <cluster-name>/role: ci
    kops.k8s.io/instancegroup: ci-nodes-az-a
  role: Node
  subnets:
  - eu-central-1a
  taints:
  - <cluster-name>/role=ci:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:10:48Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: test-1.eu-central-1.cofano.io
  name: ci-nodes-az-b
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label/<cluster-name>/role: ci
    k8s.io/cluster-autoscaler/node-template/taint/<cluster-name>/role: ci:NoSchedule
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.xlarge
  maxSize: 2
  minSize: 0
  nodeLabels:
    <cluster-name>/role: ci
    kops.k8s.io/instancegroup: ci-nodes-az-b
  role: Node
  subnets:
  - eu-central-1b
  taints:
  - <cluster-name>/role=ci:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:11:27Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: test-1.eu-central-1.cofano.io
  name: ci-nodes-az-c
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label/<cluster-name>/role: ci
    k8s.io/cluster-autoscaler/node-template/taint/<cluster-name>/role: ci:NoSchedule
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.xlarge
  maxSize: 2
  minSize: 0
  nodeLabels:
    <cluster-name>/role: ci
    kops.k8s.io/instancegroup: ci-nodes-az-c
  role: Node
  subnets:
  - eu-central-1c
  taints:
  - <cluster-name>/role=ci:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-02-05T11:31:39Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-eu-central-1a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-02-05T11:31:40Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-eu-central-1b
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-02-05T11:31:40Z"
  generation: 5
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: master-eu-central-1c
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:00:30Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: nodes-az-a
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: truei
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: r5.large
  maxSize: 4
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-az-a
  role: Node
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:01:55Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: nodes-az-b
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: r5.large
  maxSize: 4
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-az-b
  role: Node
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-22T14:02:27Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: <cluster-name>
  name: nodes-az-c
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/<cluster-name>: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: r5.large
  maxSize: 4
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-az-c
  role: Node
  subnets:
  - eu-central-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

```
kubectl describe node <node-that-does-not-get-ready-state>

Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Fri, 06 Mar 2020 18:45:40 +0100   Fri, 06 Mar 2020 18:45:40 +0100   RouteCreated                 RouteController created a route
  MemoryPressure       False   Fri, 06 Mar 2020 19:02:03 +0100   Fri, 06 Mar 2020 18:45:32 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Fri, 06 Mar 2020 19:02:03 +0100   Fri, 06 Mar 2020 18:45:32 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Fri, 06 Mar 2020 19:02:03 +0100   Fri, 06 Mar 2020 18:45:32 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                False   Fri, 06 Mar 2020 19:02:03 +0100   Fri, 06 Mar 2020 18:45:32 +0100   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR
```
