### ISSUE TITLE
apis depreciated in kubernetes 0.17 still used in addons

### ISSUE THREAD

**Issue by coryschwartz** [kubernetes/kops#8710]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
Version 1.17.0-beta.1 (git-32af4ed9b)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Using `kops -f`, with a manifest lightly edited to add addons into the spec portion.

**5. What happened after the commands executed?**
The prometheus-operator (and I believe others as well) are unable to start.
The syslog of the master shows the following error message:
```
Mar 10 06:36:30 ip-172-20-63-47 docker[2652]: unable to recognize "/tmp/channel625389394/manifest.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
Mar 10 06:36:30 ip-172-20-63-47 docker[2652]: unable to recognize "/tmp/channel625389394/manifest.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
Mar 10 06:36:30 ip-172-20-63-47 docker[2652]: unable to recognize "/tmp/channel625389394/manifest.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
Mar 10 06:36:30 ip-172-20-63-47 docker[2652]: unable to recognize "/tmp/channel625389394/manifest.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"
Mar 10 06:36:30 ip-172-20-63-47 docker[2652]: unable to recognize "/tmp/channel625389394/manifest.yaml": no matches for kind "Deployment" in version "apps/v1beta2"

Mar 10 06:36:30 ip-172-20-63-47 docker[2652]: Error: error updating "prometheus-operator": error applying update from "https://raw.githubusercontent.com/kubernetes/kops/master/addons/prometheus-operator/v0.29.0.yaml": error running kubectl
```

This is because apps/v1beta2 is depreciated this version of kubernetes.

```
# kubectl api-versions
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
metrics.k8s.io/v1beta1
monitoring.coreos.com/v1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

```

**6. What did you expect to happen?**
Addons should install correctly.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-10T06:04:16Z"
  name: xxx
spec:
  addons:
  - manifest: metrics-server
  - manifest: prometheus-operator
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://yyy/xxx
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    allowedUnsafeSysctls:
    - net.core.somaxconn
    anonymousAuth: false
    maxPods: 200
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.3
  masterInternalName: api.internal.xxx.k8s.local
  masterPublicName: api.xxx.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-10T06:04:17Z"
  labels:
    kops.k8s.io/cluster: xxx.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2a
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-10T06:04:17Z"
  labels:
    kops.k8s.io/cluster: xxx.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.2xlarge
  maxSize: 8
  minSize: 8
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
