### ISSUE TITLE
Only first zone, subnet and utility subnet are used with --dry-run

### ISSUE THREAD

**Issue by domhdp** [kubernetes/kops#8728]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.16.0 (git-4b0e62b82)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Haven't get a cluster yet

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
export CLUSTER_ID=blah
export DNS_ZONE=myzone.com
export CLUSTER_NAME=cluster.$CLUSTER_ID.$DNS_ZONE
export VPC_ID=vpc-XXX
export VPC_CIDR=10.2.0.0/16
export MASTER_COUNT=1
export MASTER_ZONES=ca-central-1a
export NODE_COUNT=2
export NODE_ZONES=ca-central-1a,ca-central-1b
export SUBNET_IDS=subnet-AAA,subnet-BBB
export UTILITY_SUBNETS=subnet-CCC,subnet-DDD

kops create cluster --name=$CLUSTER_NAME \
        --admin-access=$VPC_CIDR \
        --api-loadbalancer-type=internal \
        --associate-public-ip=false \
        --authorization=RBAC \
        --bastion \
        --cloud=aws \
        --dns-zone=$DNS_ZONE \
        --encrypt-etcd-storage \
        --master-count=$MASTER_COUNT \
        --master-size=t2.medium \
        --master-zones=$MASTER_ZONES \
        --network-cidr=$VPC_CIDR \
        --networking=weave \
        --node-count=$NODE_COUNT \
        --node-size=m5.large \
        --zones=$MASTER_ZONES \
        --subnets=$SUBNET_IDS \
        --ssh-access=$VPC_CIDR \
        --vpc=$VPC_ID \
        --topology=private \
        --utility-subnets=$UTILITY_SUBNETS \
        --dry-run --output=yaml \
        1>temp-cluster-spec.yaml
```

**5. What happened after the commands executed?**

The output YAML contained only one zone, one private subnet and one utility subnet, instead of two.

**6. What did you expect to happen?**

The output YAML should contain both zones, and `subnets:` for all 4 subnets (2 private and 2 utility).

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

This is the `--dry-run` output

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: cluster.blah.myzone.com
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-cluster-state/cluster.blah.myzone.com
  dnsZone: myzone.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ca-central-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ca-central-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 10.2.0.0/16
  kubernetesVersion: 1.16.7
  masterPublicName: api.cluster.blah.myzone.com
  networkCIDR: 10.2.0.0/16
  networkID: vpc-XXX
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.2.0.0/16
  subnets:
  - cidr: 10.2.4.0/24
    id: subnet-AAA
    name: ca-central-1a
    type: Private
    zone: ca-central-1a
  - cidr: 10.2.1.0/24
    id: subnet-CCC
    name: utility-ca-central-1a
    type: Utility
    zone: ca-central-1a
  topology:
    bastion:
      bastionPublicName: bastion.cluster.blah.myzone.com
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.blah.myzone.com
  name: master-ca-central-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ca-central-1a
  role: Master
  subnets:
  - ca-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.blah.myzone.com
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ca-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.blah.myzone.com
  name: bastions
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-ca-central-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

There doesn't seem to be anything unusual in the logs.

**9. Anything else do we need to know?**

I think that's it.
