### ISSUE TITLE
KOPS on AWS, pods on different nodes cannot communicate to each other

### ISSUE THREAD

**Issue by janvdvegt** [kubernetes/kops#8811]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.16.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15.10 (but same problem on 1.16.7)

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I used Terraform output to spin up the Kops cluster. It contains 3 different availability zones, 3 masters and 3 normal nodes, plus a few autoscaling instance groups that are not used yet. We use a private topology, standard kubenet networking and a previously defined VPC with a NAT gateway.

**5. What happened after the commands executed?**

Cluster spins up and I first found out the issue when additional APIServices that are installed cannot be reached by the `kube-apiserver`. After spending days diving into what is happening, we find out that pods can only communicate to each other when they are on the same node. We talked to AWS support and they say that all the networking settings are good.

**6. What did you expect to happen?**

That pods can communicate to each other when they are on different nodes.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: XXX
spec:
  api:
    loadBalancer:
      additionalSecurityGroups:
      - sg-03f9906ea368d4b56
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://XXX
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.10
  masterPublicName: XXX
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0b4157267eecbbaba
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - id: subnet-08022a7f59b8c3187
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - id: subnet-0a2831a5daabb93a7
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - id: subnet-04879c7b53a2fc931
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  - egress: nat-0a52bfb03d91da216
    id: subnet-018d9361603d15b32
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - egress: nat-0f3b5e83bad39b112
    id: subnet-0663eb828a678abdc
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - egress: nat-00203d5a6424ee6e6
    id: subnet-06a26d0454bf39df8
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-27T15:15:18Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: base-nodes
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/XXX: ""
    k8s.io/cluster-autoscaler/enabled: ""
    kubernetes.io/cluster/XXX: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.medium
  maxSize: 10
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: t3medium
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-27T15:15:18Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: c5large
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/XXX: ""
    k8s.io/cluster-autoscaler/enabled: ""
    kubernetes.io/cluster/XXX: owned
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.large
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: c5large
    name: c5large
  role: Node
  rootVolumeSize: 25
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
  taints:
  - dedicated=c5large:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-27T15:15:17Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-27T15:15:17Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: master-eu-central-1b
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-27T15:15:18Z"
  labels:
    kops.k8s.io/cluster: XXX
  name: master-eu-central-1c
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c


```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
