### ISSUE TITLE
Support for Bind Mount option for InstanceGroup volume/volume mount

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/kops#8815]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
it will be great  to mount /var/lib/docker and /var/lib/kubelet to the AWS d types aka m5d.xalrge on the ephemeral volume(local storage).
For example:
```
m5d.xlarge | 4 | 16 | 16 GiB | 1 x 150 NVMe SSD | $0.226 per Hour
-- | -- | -- | -- | -- | --
m5d.2xlarge | 8 | 37 | 32 GiB | 1 x 300 NVMe SSD | $0.452 per Hour

------
c5d.xlarge | 4 | 20 | 8 GiB | 1 x 100 NVMe SSD | $0.192 per Hour
-- | -- | -- | -- | -- | --
c5d.2xlarge | 8 | 39 | 16 GiB | 1 x 200 NVMe SSD | $0.384 per Hour

```
All above have only one NVMe SSD, and it could share docker and kubelet directory.
So It should improve performance of kubelet as docker too. 

**2. Feel free to provide a design supporting your feature request.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: my-beloved-cluster
  name: compute
spec:
  cloudLabels:
    role: compute
  image: coreos.com/CoreOS-stable-1855.4.0-hvm
  machineType: m4.large
  ...
  volumeMounts:
  - device: /dev/xvdd
    filesystem: ext4
    path: /var/lib/docker 
    options:
        bind: true
  - device: /dev/xvdd
    filesystem: ext4
    path: /var/lib/docker
    options:
        bind: true
```

Thanks!
