### ISSUE TITLE
target groups from externalLoadBalancers are not removed from the ASG

### ISSUE THREAD

**Issue by recollir** [kubernetes/kops#8819]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.15.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.15.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
The cluster spec contains an instance groups with an external load balancers.
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: test.example.com
  name: test-eu-west-1a
spec:   
  externalLoadBalancers:
    - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:123456789012:targetgroup/foo/001234567890
```
The target group foo is correctly added to the ASG of the instance group after running kops. the cluster spec is then edited. The target group foo is replaced with the target group bar and kops is run again (kops replace and kops update)
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: test.example.com
  name: test-eu-west-1a
spec:   
  externalLoadBalancers:
    - targetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:123456789012:targetgroup/bar/999876543210
```
**5. What happened after the commands executed?**
Both target groups foo and bar are still attached to the ASG of the instance group.

**6. What did you expect to happen?**
That the first added target group (foo) is removed from the ASG and only the second target group (bar) is now attached to the ASG.
