### ISSUE TITLE
Kubelet failing in nodes

### ISSUE THREAD

**Issue by nicolasdonoso** [kubernetes/kops#8913]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.16.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.16.7

**3. What cloud provider are you using?**

Google Cloud

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster --name <cluster name> --zones us-west1-b
kops update cluster --name <cluster name> --yes
```

**5. What happened after the commands executed?**

Resources were created in GCP but the cluster is not accessible when running `kubectl` commands

**6. What did you expect to happen?**

Once resources are ready to be able to handle the cluster using `kubectl`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-04-14T19:50:42Z"
  name: <cluster name>
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://<STORAGE>/<cluster name>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west1-b
      name: b
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west1-b
      name: b
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.7
  masterPublicName: api.<cluster name>
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: data-science-213423
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-west1
    region: us-west1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-14T19:50:43Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: master-us-west1-b
spec:
  image: cos-cloud/cos-stable-77-12371-114-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west1-b
  role: Master
  subnets:
  - us-west1
  zones:
  - us-west1-b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-14T19:50:43Z"
  labels:
    kops.k8s.io/cluster: <cluster name>
  name: nodes
spec:
  image: cos-cloud/cos-stable-77-12371-114-0
  machineType: n1-standard-2
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west1
  zones:
  - us-west1-b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Running the following commands inside the master I get this:
```
kubectl get nodes
NAME                     STATUS   ROLES    AGE   VERSION
master-us-west1-b-kdfk   Ready    master   12m   v1.16.7

kubectl  get po -n kube-system
NAME                                             READY   STATUS    RESTARTS   AGE
dns-controller-744c458fc8-swch2                  1/1     Running   0          72s
etcd-manager-events-master-us-west1-b-grdd       1/1     Running   0          48s
etcd-manager-main-master-us-west1-b-grdd         1/1     Running   0          56s
kops-controller-2mn8x                            1/1     Running   0          26s
kube-apiserver-master-us-west1-b-grdd            0/1     Pending   0          10s
kube-controller-manager-master-us-west1-b-grdd   1/1     Running   0          39s
kube-dns-autoscaler-594dcb44b5-lpb2q             0/1     Pending   0          72s
kube-dns-b84c667f4-ppnwh                         0/3     Pending   0          72s
kube-proxy-master-us-west1-b-grdd                1/1     Running   0          57s
kube-scheduler-master-us-west1-b-grdd            1/1     Running   0          56s
```
Kube DNS pending pods events shows the folling:

```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  63s (x5 over 119s)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
```

The nodes never register and even when manually restarting kubelet they keep failing and cannot reach internal api. I've checked the DNS values and api.internal is pointing correctly to the master internal IP.
