### ISSUE TITLE
kops overwrites Kubernetes API URL in custom kube config

### ISSUE THREAD

**Issue by saidmasoud** [kubernetes/kops#8957]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.14.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.14.9

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Given a custom-written kube config file with the following (note the server URL is the _internal_ API server):
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://api.internal.cluster.url
  name: cluster.url
..........
```
Perform any update on the cluster and try to validate

```sh
kops edit cluster
kops update cluster --yes
kops validate cluster
```

**5. What happened after the commands executed?**
`kops validate cluster` fails because kops updates the kube config file to point to the _external_ URL, which is not accessible due to security group rules. I had to manually update the kube config file to validate cluster.

**6. What did you expect to happen?**
`kops validate cluster` should have used the existing URL endpoint to validate cluster

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```yaml
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-10-10T02:50:49Z
  generation: 7
  name: cluster.url
spec:
  additionalPolicies:
    node: |
      [
      {redacted}
      ]
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    datadog: "true"
    role: k8s
    team: common
  cloudProvider: aws
  configBase: s3://bucket/cluster.url
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1f
      name: f
    name: main
    provider: Manager
    version: 3.2.18
  - etcdMembers:
    - instanceGroup: master-us-east-1f
      name: f
    name: events
    provider: Manager
    version: 3.2.18
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    authenticationTokenWebhookConfigFile: /etc/kubernetes/heptio-authenticator-aws/kubeconfig.yaml
  kubernetesApiAccess:
  - 10.0.0.0/24
  - 172.16.0.0/24
  - 192.168.0.0/24
  kubernetesVersion: 1.14.9
  masterInternalName: api.internal.cluster.url
  masterPublicName: api.cluster.url
  networkCIDR: 172.20.0.0/23
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 10.0.0.0/24
  - 172.16.0.0/24
  - 192.168.0.0/24
  subnets:
  - cidr: 172.20.0.0/24
    name: us-east-1e
    type: Public
    zone: us-east-1e
  - cidr: 172.20.1.0/24
    name: us-east-1f
    type: Public
    zone: us-east-1f
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
It would be nice if `kops` had a global flag to override the server URL, or perhaps one to point to the internal API server.
