### ISSUE TITLE
kops 1.16.1 docker TLS handshake timeout, Error getting v2 registry: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure"

### ISSUE THREAD

**Issue by prudhvigodithi** [kubernetes/kops#8968]
**1. What `kops` version are you running? The command `kops version`, will display
 1.16.1 (same with 1.16.0)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
1.16.7

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
docker pull k8s.gcr.io/pause-amd64:3.0

**5. What happened after the commands executed?**
Apr 23 18:12:11 ip-10-35-6-41 dockerd[2125]: time="2020-04-23T18:12:11.172579196-04:00" level=warning msg="Error getting v2 registry: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure"
Apr 23 18:12:11 ip-10-35-6-41 dockerd[2125]: time="2020-04-23T18:12:11.173286660-04:00" level=error msg="Not continuing with pull after error: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure"
Apr 23 18:12:11 ip-10-35-6-41 dockerd[2125]: time="2020-04-23T18:12:11.173706068-04:00" level=error msg="Handler for POST /v1.39/images/create?fromImage=k8s.gcr.io%2Fpause-amd64&tag=3.0 returned error: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure"
Apr 23 18:12:11 ip-10-35-6-41 dockerd[2125]: time="2020-04-23T18:12:11.191787240-04:00" level=error msg="Handler for POST /v1.39/images/create returned error: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure"

**6. What did you expect to happen?**
Able to pull the pause container

Kops docker nodes using squid proxy, able to pull the image with same squid proxy using kops 1.12.2
for 1.16.0 kops using k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17 AMI

Cluster Yaml
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-04-23T22:07:27Z"
  generation: 1
  name: toolstestoffline6.k8s.local
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:TerminateInstanceInAutoScalingGroup"
          ],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    ClusterName: toolstestoffline6.k8s.local
    Department: tools
    NonStop: "True"
    Platform: infratools
  cloudProvider: aws
  configBase: s3://data-tools-us-east-1/kopstest/toolstestoffline6.k8s.local
  docker:
    authorizationPlugins:
    - toolsk8s.tools.docker/policyagent/docker-authz-v2:0.5
  egressProxy:
    excludes: dist.kope.io,.ec2.us-east-1.amazonaws.com,.s3.amazonaws.com,127.0.0.1,localhost,.k8s.local,100.65.0.1,173.21.0.0/16,101.64.0.0/10,169.254.169.254,10.35.7.0/21,.elb.amazonaws.com,.qa.example.com,.tpp.example.com,100.96.0.0/11,.ec2.internal,api.qacd.k8s.local,api.internal.,internal.,.elb.us-east-1.amazonaws.com,elasticloadbalancing.us-east-1.amazonaws.com,.test.io,s3.amazonaws.com,api.toolstestoffline6.k8s.local,toolstestoffline6.k8s.local
    httpProxy:
      host: test-proxy.us-east-1.aws
      port: 4438
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
    provider: Manager
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
    provider: Manager
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    clusterCIDR: 172.51.128.0/17
  kubeDNS:
    provider: CoreDNS
  kubeProxy:
    clusterCIDR: 172.51.128.0/17
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      ExpandPersistentVolumes: "true"
      PodPriority: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.7
  masterPublicName: api.toolstestoffline6.k8s.local
  networkCIDR: 10.35.16.0/24
  networkID: vpc-07758ba979708a684
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 172.41.1.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.35.5.0/25
    id: subnet-02dcvddb8c27967e9d
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.35.6.68/25
    id: subnet-02ccddf28c06908cb
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.35.6.7/25
    id: subnet-02dcddbfc27929e9d
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.35.6.129/25
    id: subnet-02ccssf28c07908cb
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```
