### ISSUE TITLE
AWS IAM Authenticator doesn't work

### ISSUE THREAD

**Issue by krangerich** [kubernetes/kops#8992]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.16.1 (git-d1b07f7fd6)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Added a ConfigMap aws-iam-authenticator

Added
```
  authentication:
    aws: {}
```
to cluster.yaml, updated the cluster, force rolled master

**5. What happened after the commands executed?**

aws-iam-authenticator log reads:

`time="2020-04-26T10:02:13Z" level=info msg="reconfigure your apiserver with `--authentication-token-webhook-config-file=/etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml` to enable (assuming default hostPath mounts)"`

kube-apiserver runs still with

 ` - --authentication-token-webhook-config-file=/etc/kubernetes/authn.config`

according to pod yaml

**6. What did you expect to happen?**

kube-apiserver should run with 

`- --authentication-token-webhook-config-file=/etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: <redacted>
spec:
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: <redacted>
  dnsZone: <redacted>
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 3
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 3
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    disableBasicAuth: true
    authenticationTokenWebhookConfigFile: /etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.8
  masterPublicName: <redacted>
  networkCIDR: 172.1.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.1.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.1.64.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: <redacted>
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 8
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: <redacted>
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.small
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 10
  subnets:
  - eu-central-1a
  - eu-central-1b
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by fred-vogt** [comment]
I'm seeing this with 1.17.0-beta.1, this appears to be a "known issue"
* https://github.com/kubernetes/kops/blob/master/docs/releases/1.17-NOTES.md#known-issues

## local exec
```
AWS_PROFILE=...  aws-iam-authenticator token -i <cluster>

works
```

## aws-iam-authenticator cm
```
# Using admin kubeconfig
kubectl  get cm aws-iam-authenticator -n kube-system -o yaml

contains the right entries
```

## api-server logs
```
E0504 18:52:25.873846       1 webhook.go:109] 
Failed to make webhook authenticator request: 
Post https://127.0.0.1:21362/authenticate?timeout=30s: 
dial tcp 127.0.0.1:21362: connect: connection refused

E0504 18:52:25.873871       1 authentication.go:104] 
Unable to authenticate the request due to an error: 
[invalid bearer token, 
Post https://127.0.0.1:21362/authenticate?timeout=30s
: dial tcp 127.0.0.1:21362: connect: connection refused]
```

## /etc/kubernetes/authn.config
```
apiVersion: ""
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:21362/authenticate
  name: aws-iam-authenticator
contexts:
- context:
    cluster: aws-iam-authenticator
    user: kube-apiserver
  name: webhook
current-context: webhook
kind: ""
users:
- name: kube-apiserver
  user: {}
```
