### ISSUE TITLE
Kops Template has issues with {{range $i, $az := .availability_zones.value}}

### ISSUE THREAD

**Issue by knagu** [kubernetes/kops#8996]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`1.16.1`

**2. What cloud provider are you using?**
AWS

**3. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops toolbox template --name ${CLUSTER_NAME} --values <( echo ${TF_OUTPUT}) --template template.yaml --format-yaml > cluster.yaml`

**4. What happened after the commands executed?**
cluster.yaml didnt create as expected. It created as below for the following section

input template.yml
```
etcdClusters:
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }}
  {{end}}
    name: main
  - etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }}
  {{end}}
    name: events
```
output:
```
etcdClusters:
  - etcdMembers:
    - instanceGroup: master-[us-west-2a us-west-2b us-west-2c]
      name: a
    name: main
```

**5. What did you expect to happen?**
 ```
etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2b
      name: b
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2c
      name: c
    name: main
```

**6. Anything else do we need to know?**
Expected to create three public and private instances in 3 azs in us-west-2. but stuck at this point. Could any one help me through this issue. 
Referred to this blog while creating: https://medium.com/bench-engineering/deploying-kubernetes-clusters-with-kops-and-terraform-832b89250e8e 
Thanks in advance!
