### ISSUE TITLE
API downtime during masters update

### ISSUE THREAD

**Issue by juris** [kubernetes/kops#9025]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
➜  ~ kops version
Version 1.16.1
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Updated instance group settings for master and initiated rolling update for masters IG.
```
kops rolling-update cluster cluster.k8s.local --instance-group master-us-east-1a --yes
kops rolling-update cluster cluster.k8s.local --instance-group master-us-east-1b --yes
kops rolling-update cluster cluster.k8s.local --instance-group master-us-east-1c --yes
```
**5. What happened after the commands executed?**

We have a cluster of ~160 nodes. During the masters IG rolling update vast majority of the nodes went to NotReady state because they failed to connect to K8S API. Ingresses failed to get pod lists for the same reason, so our clients had a lot of 5xx errors. Basically, cluster was broken.

Here's what happened in kubelet logs on one of the nodes:
```
Apr 29 12:44:12 ip-10-3-8-46 kubelet[1799]: E0429 12:44:12.062143    1799 kubelet_node_status.go:388] Error updating node status, will retry: error getting node "ip-10-3-8-46.ec2.internal": Get https://api.internal.cluster.k8s.local/api/v1/nodes/ip-10-3-8-46.ec2.internal?timeout=10s: dial tcp 10.3.0.133:443: connect: connection refused
Apr 29 12:44:12 ip-10-3-8-46 kubelet[1799]: E0429 12:44:12.062563    1799 kubelet_node_status.go:388] Error updating node status, will retry: error getting node "ip-10-3-8-46.ec2.internal": Get https://api.internal.cluster.k8s.local/api/v1/nodes/ip-10-3-8-46.ec2.internal?timeout=10s: dial tcp 10.3.0.133:443: connect: connection refused
Apr 29 12:44:12 ip-10-3-8-46 kubelet[1799]: E0429 12:44:12.062895    1799 kubelet_node_status.go:388] Error updating node status, will retry: error getting node "ip-10-3-8-46.ec2.internal": Get https://api.internal.cluster.k8s.local/api/v1/nodes/ip-10-3-8-46.ec2.internal?timeout=10s: dial tcp 10.3.0.133:443: connect: connection refused
Apr 29 12:44:12 ip-10-3-8-46 kubelet[1799]: E0429 12:44:12.062904    1799 kubelet_node_status.go:375] Unable to update node status: update node status exceeds retry count
Apr 29 12:44:13 ip-10-3-8-46 kubelet[1799]: E0429 12:44:13.062577    1799 reflector.go:123] object-"monitoring"/"filebeat-dynamic-token-7tm2n": Failed to list *v1.Secret: Get https://api.internal.cluster.k8s.local/api/v1/namespaces/monitoring/secrets?fieldSelector=metadata.name%3Dfilebeat-dynamic-token-7tm2n&limit=500&resourceVersion=0: dial tcp 10.3.0.133:443: connect: connection refused
Apr 29 12:44:13 ip-10-3-8-46 kubelet[1799]: E0429 12:44:13.063537    1799 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:459: Failed to list *v1.Node: Get https://api.internal.cluster.k8s.local/api/v1/nodes?fieldSelector=metadata.name%3Dip-10-3-8-46.ec2.internal&limit=500&resourceVersion=0: dial tcp 10.3.0.133:443: connect: connection refused
```

10.3.0.133 - IP address of the new master. For some reason, kubelet was trying to connect to a single master, no the other 2 healthy ones. We are using gossip and there were other masters in /etc/hosts

After all masters went up, issue was gone. But during the update we had completely unusable cluster, clients were suffering, there were weeping and gnashing of teeth.

**6. What did you expect to happen?**
Rolling update to succeed.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-01-22T11:15:26Z"
  generation: 8
  name: cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    env: prod
    project: cluster
  cloudProvider: aws
  configBase: s3://cluster-k8s-state/cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
    provider: Manager
    version: 3.3.10
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
    provider: Manager
    version: 3.3.10
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeControllerManager:
    horizontalPodAutoscalerUseRestClients: true
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 10.3.0.0/16
  kubernetesVersion: 1.16.8
  masterInternalName: api.internal.cluster.k8s.local
  masterPublicName: api.cluster.k8s.local
  networkCIDR: 10.3.0.0/16
  networking:
    calico:
      crossSubnet: true
      majorVersion: v3
      mtu: 8981
      typhaReplicas: 3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.3.0.0/24
    egress: nat-02b0270a9e10f0666
    name: masters-us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.3.1.0/24
    egress: nat-02b0270a9e10f0666
    name: masters-us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.3.2.0/24
    egress: nat-02b0270a9e10f0666
    name: masters-us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 10.3.3.0/24
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 10.3.4.0/24
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 10.3.5.0/24
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 10.3.8.0/21
    egress: nat-02b0270a9e10f0666
    name: nodes-us-east-1a
    type: Private
    zone: us-east-1a
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-01-22T11:15:26Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-us-east-1a
spec:
  image: ami-0e6efe78168ca57ec
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - masters-us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-01-22T11:15:27Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-us-east-1b
spec:
  image: ami-0e6efe78168ca57ec
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - masters-us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-01-22T11:15:27Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-us-east-1c
spec:
  image: ami-0e6efe78168ca57ec
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - masters-us-east-1c
```
