### ISSUE TITLE
user namespace remapping not working

### ISSUE THREAD

**Issue by xinau** [kubernetes/kops#9127]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.16.0 (git-4b0e62b82)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: EOF
```
1.17.5

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I wanted to create a cluster with user namespace remapping enabled as introduced by #5357
I set the configuration option in a cluster template to default and created a new cluster using `kops replace cluster -f ./cluster.yaml`
```yaml
...
  docker:
    userNamespaceRemap: default
...
```

**5. What happened after the commands executed?**
The api server is not reachable.
```
$ kubectl get nodes
Unable to connect to the server: EOF
```

**6. What did you expect to happen?**
To reach the api server.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-05-14T08:25:05Z"
  name: foo.bar
spec:
  api:
    loadBalancer:
      crossZoneLoadBalancing: true
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx-foo-bar
  docker:
    userNamespaceRemap: default
  etcdClusters:
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 10
    name: main
    version: 3.3.13
  - enableEtcdTLS: true
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
      volumeSize: 10
    name: events
    version: 3.3.13
  fileAssets:
  - content: "---\napiVersion: audit.k8s.io/v1beta1\nkind: Policy\nrules:\n  # The
      following requests were manually identified as high-volume and low-risk,\n  #
      so drop them.\n  - level: None\n    resources:\n      - group: \"\"\n        resources:\n
      \         - endpoints\n          - services\n          - services/status\n    users:\n
      \     - 'system:kube-proxy'\n    verbs:\n      - watch\n\n  - level: None\n
      \   resources:\n      - group: \"\"\n        resources:\n          - nodes\n
      \         - nodes/status\n    userGroups:\n      - 'system:nodes'\n    verbs:\n
      \     - get\n\n  - level: None\n    namespaces:\n      - kube-system\n    resources:\n
      \     - group: \"\"\n        resources:\n          - endpoints\n    users:\n
      \     - 'system:kube-controller-manager'\n      - 'system:kube-scheduler'\n
      \     - 'system:serviceaccount:kube-system:endpoint-controller'\n    verbs:\n
      \     - get\n      - update\n\n  - level: None\n    resources:\n      - group:
      \"\"\n        resources:\n          - namespaces\n          - namespaces/status\n
      \         - namespaces/finalize\n    users:\n      - 'system:apiserver'\n    verbs:\n
      \     - get\n\n  # Don't log HPA fetching metrics.\n  - level: None\n    resources:\n
      \     - group: metrics.k8s.io\n    users:\n      - 'system:kube-controller-manager'\n
      \   verbs:\n      - get\n      - list\n\n  # Don't log these read-only URLs.\n
      \ - level: None\n    nonResourceURLs:\n      - '/healthz*'\n      - /version\n
      \     - '/swagger*'\n\n  # Don't log events requests.\n  - level: None\n    resources:\n
      \     - group: \"\"\n        resources:\n          - events\n\n  # node and
      pod status calls from nodes are high-volume and can be large, don't log responses
      for expected updates from nodes\n  - level: Request\n    omitStages:\n      -
      RequestReceived\n    resources:\n      - group: \"\"\n        resources:\n          -
      nodes/status\n          - pods/status\n    users:\n      - kubelet\n      -
      'system:node-problem-detector'\n      - 'system:serviceaccount:kube-system:node-problem-detector'\n
      \   verbs:\n      - update\n      - patch\n\n  - level: Request\n    omitStages:\n
      \     - RequestReceived\n    resources:\n      - group: \"\"\n        resources:\n
      \         - nodes/status\n          - pods/status\n    userGroups:\n      -
      'system:nodes'\n    verbs:\n      - update\n      - patch\n\n  # deletecollection
      calls can be large, don't log responses for expected namespace deletions\n  -
      level: Request\n    omitStages:\n      - RequestReceived\n    users:\n      -
      'system:serviceaccount:kube-system:namespace-controller'\n    verbs:\n      -
      deletecollection\n\n  # Secrets, ConfigMaps, and TokenReviews can contain sensitive
      & binary data,\n  # so only log at the Metadata level.\n  - level: Metadata\n
      \   omitStages:\n      - RequestReceived\n    resources:\n      - group: \"\"\n
      \       resources:\n          - secrets\n          - configmaps\n      - group:
      authentication.k8s.io\n        resources:\n          - tokenreviews\n  # Get
      repsonses can be large; skip them.\n  - level: Request\n    omitStages:\n      -
      RequestReceived\n    resources:\n      - group: \"\"\n      - group: admissionregistration.k8s.io\n
      \     - group: apiextensions.k8s.io\n      - group: apiregistration.k8s.io\n
      \     - group: apps\n      - group: authentication.k8s.io\n      - group: authorization.k8s.io\n
      \     - group: autoscaling\n      - group: batch\n      - group: certificates.k8s.io\n
      \     - group: extensions\n      - group: metrics.k8s.io\n      - group: networking.k8s.io\n
      \     - group: policy\n      - group: rbac.authorization.k8s.io\n      - group:
      scheduling.k8s.io\n      - group: settings.k8s.io\n      - group: storage.k8s.io\n
      \   verbs:\n      - get\n      - list\n      - watch\n\n  # Default level for
      known APIs\n  - level: RequestResponse\n    omitStages:\n      - RequestReceived\n
      \   resources:\n      - group: \"\"\n      - group: admissionregistration.k8s.io\n
      \     - group: apiextensions.k8s.io\n      - group: apiregistration.k8s.io\n
      \     - group: apps\n      - group: authentication.k8s.io\n      - group: authorization.k8s.io\n
      \     - group: autoscaling\n      - group: batch\n      - group: certificates.k8s.io\n
      \     - group: extensions\n      - group: metrics.k8s.io\n      - group: networking.k8s.io\n
      \     - group: policy\n      - group: rbac.authorization.k8s.io\n      - group:
      scheduling.k8s.io\n      - group: settings.k8s.io\n      - group: storage.k8s.io\n
      \     \n  # Default level for all other requests.\n  - level: Metadata\n    omitStages:\n
      \     - RequestReceived"
    name: kubernetes-audit
    path: /srv/kubernetes/audit.yaml
    roles:
    - Master
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Service]
      Type=oneshot
      RemainAfterExit=no
      ExecStart=/bin/sh -c "sed -i -- 's/pool/#pool/g' /etc/ntp.conf ; echo 'server 169.254.169.123 prefer iburst' >> /etc/ntp.conf"
      ExecStartPost=/bin/systemctl restart ntp.service
    name: kops-change-ntp-server.service
    roles:
    - Node
    - Master
  - manifest: |-
      [Unit]
      Description=Tag etcd EBS Volumes
      Wants=kubelet.service protokube.service
      After=kubelet.service protokube.service
      [Service]
      Type=oneshot
      ExecStartPre=/bin/bash -c "apt update -q && apt install -y jq"
      ExecStart=/bin/bash \
        -c 'AWS_REGION=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//'); \
            /usr/local/bin/aws ec2 describe-volumes --region $AWS_REGION --filters "Name=tag:Name,Values=*etcd-main*" | /usr/bin/jq -r '"'"'.Volumes[] | .VolumeId'"'"' | \
            xargs -I{} /usr/local/bin/aws ec2 create-tags --region "$AWS_REGION" --resources "{}" --tags "Key=lm-dailysnapshot-enable,Value=true";'
      [Install]
      WantedBy=multi-user.target
    name: kops-hook-tag-etcd-volumes.service
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    auditLogMaxAge: 1
    auditLogMaxBackups: 14
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    disableBasicAuth: true
    enableAdmissionPlugins:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - PodSecurityPolicy
    - AlwaysPullImages
    - DenyEscalatingExec
    featureGates:
      DynamicAuditing: "true"
      TTLAfterFinished: "true"
    oidcCAFile: /etc/ssl/certs/ca-certificates.crt
    oidcClientID: client-id
    oidcGroupsClaim: groups
    oidcIssuerURL: https://127.0.0.1
    oidcUsernameClaim: preferred_username
    runtimeConfig:
      auditregistration.k8s.io/v1alpha1: "true"
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 127.0.0.1
  kubernetesVersion: 1.17.5
  networkCIDR: 172.31.0.0/16
  networkID: vpc-xxx
  networking:
    calico:
      prometheusMetricsEnabled: true
      prometheusMetricsPort: 9091
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 127.0.0.1
  subnets:
  - cidr: 172.31.133.0/24
    egress: nat-xxx
    id: subnet-xxx
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.31.134.0/24
    egress: nat-xxx
    id: subnet-xxx
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.31.135.0/24
    egress: nat-xxx
    id: subnet-xxx
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.31.140.0/24
    id: subnet-xxx
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.31.141.0/24
    id: subnet-xxx
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.31.142.0/24
    id: subnet-xxx
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T08:25:06Z"
  labels:
    kops.k8s.io/cluster: foo.bar
  name: bastions
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  rootVolumeSize: 10
  subnets:
  - utility-eu-central-1a
  - utility-eu-central-1b
  - utility-eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T08:25:07Z"
  labels:
    kops.k8s.io/cluster: foo.bar
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: masters
  role: Master
  rootVolumeSize: 40
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T08:25:07Z"
  labels:
    kops.k8s.io/cluster: foo.bar
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.medium
  maxSize: 4
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T08:25:08Z"
  labels:
    kops.k8s.io/cluster: foo.bar
  name: nodes_scale_group
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.small
  maxSize: 4
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nodes_scale_group
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Logs from the single node master.

docker.service
```
May 14 08:52:12 ip-172-31-133-171 dockerd[2209]: time="2020-05-14T08:52:12.306769070Z" level=warning msg="
Published ports are discarded when using host network mode"
```
kubelet.service
```
May 14 08:46:02 ip-172-31-133-171 kubelet[4883]: E0514 08:46:02.823750    4883 remote_runtime.go:105] RunP
odSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod
 "etcd-manager-events-ip-172-31-133-171.eu-central-1.compute.internal": Error response from daemon: cannot
 share the host's network namespace when user namespaces are enabled 
```
protokube.service
```
May 14 08:26:53 ip-172-31-133-171 systemd[1]: Started Kubernetes Protokube Service.
May 14 08:26:53 ip-172-31-133-171 docker[3371]: /usr/bin/docker: Error response from daemon: privileged mo
de is incompatible with user namespaces.  You must run the container in the host namespace when running pr
ivileged mode.
May 14 08:26:53 ip-172-31-133-171 docker[3371]: See '/usr/bin/docker run --help'.
May 14 08:26:53 ip-172-31-133-171 systemd[1]: protokube.service: Main process exited, code=exited,
 status=125/n/a
May 14 08:26:53 ip-172-31-133-171 systemd[1]: protokube.service: Unit entered failed state.
May 14 08:26:53 ip-172-31-133-171 systemd[1]: protokube.service: Failed with result 'exit-code'.
```
