### ISSUE TITLE
Unable to set insecurePort

### ISSUE THREAD

**Issue by lrodorigo** [kubernetes/kops#9209]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.16.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.16.9

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kubectl edit cluster`
and set

```
  kubeAPIServer:
    disableBasicAuth: true
    insecurePort: 0
```

**5. What happened after the commands executed?**
The provided YAML did not validate.
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
# ...
#       disableBasicAuth: true
# +     insecurePort: 0
#     kubelet:
#       anonymousAuth: false
# ...
# 
#
```

**6. What did you expect to happen?**
insecurePort options should be read.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-05-27T14:58:49Z"
  generation: 8
  name: <hidden>
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: <hidden>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  iam:
    legacy: true
  kubeAPIServer:
    disableBasicAuth: true
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    readOnlyPort: 0
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.9
  masterInternalName: <hidden>
  masterPublicName: <hidden>
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-27T15:10:10Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: <hidden>
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.small
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-27T15:09:58Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: <hidden>
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.medium
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - eu-central-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
