### ISSUE TITLE
Using kube2iam can prevent master node cycling

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/kops#921]
The default deployment spec for kube2iam is as a daemonset with a flag to modify iptables on the host:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::123456789012:role/"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true
```

Once run on an instance, this adds an iptables rule so that containers on that host cannot access 169.254.169.254 directly and must instead go through kube2iam to get desired roles. In general, this is perfect but the problem occurs when you need to cycle your master nodes in kops because they need to manage Route53 entries through `dns-controller`, which obviously does not have a kube2iam role associated with it.

The end-result is Route53 has previous DNS entries for the API address, though etcd is updated since that isn't through `dns-controller`. Even if you stop kube2iam temporarily,  the iptables rule is already written so this would need to happen before the new master nodes come back up.

Workarounds:
- Delete kube2iam before new master nodes come up
- Constrain kube2iam to run on nodes only (needs some work that kops could help with there)

**Comment by chrislovecnm** [comment]
I am confused on what this issue is actually about... Please add more context.

**Comment by jaygorrell** [comment]
@chrislovecnm I've added more information that hopefully clarifies the issue. @justinsb also has some other ideas about longer-term solutions for this as a whole -- bringing the kube2iam functionality into kops.

**Comment by justinsb** [comment]
@chrislovecnm I asked jaygorrell to open this.  We don't play well with kube2iam on the master because of dns-controller, but kube2iam works well and we should probably have an example manifest that e.g. excludes dns-controller

**Comment by ajohnstone** [comment]
Any update on this?

**Comment by totallyunknown** [comment]
I've specified tolerations for the DaemonSet in spec.template.spec to prevent, that kube2iam Scheduling on master nodes.

```
      tolerations:
        - key: "kubernetes.io/role"
          operator: "Equal"
          value: "master"
          effect: "NoSchedule"
```
