### ISSUE TITLE
Switching Flatcar to other distro with Calico enabled breaks Flatcar nodes immediately after updating cluster

### ISSUE THREAD

**Issue by cwwarren** [kubernetes/kops#9273]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
% ./kops-1.18-beta1 version
Version 1.18.0-beta.1 (git-ec8022b352)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.17.6

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

1. Create a basic cluster using Calico and the default kops image
2. Add a new instance group with one worker that uses flatcar
2a. Notice that the volume plugin directory changed to accommodate Flatcar's read only directories
3. Edit the flatcar worker instance group to use a different image, i.e. ubuntu then `kops replace` and `kops update --yes`
4a. Notice that the volume plugin directory changed again and calico restarts on all nodes

**5. What happened after the commands executed?**

Calico on the Flatcar node is restarted with the `kops update cluster --yes`, leaving the node in an unhealthy state since the volume plugin directory has changed and does not work on Flatcar and the instance group has not been cycled to switch Flatcar to the new distro yet.

**6. What did you expect to happen?**

Honestly I'm not sure. I would expect my node not to break when switching distros but I'm not sure what the path to resolve this is. Maybe keep the "flatcar safe" directory for all distros?

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: XXX.XXX
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: alpha
  cloudLabels:
    ClusterName: XXX.XXX
    XXX.XXX: XXX.XXX
  cloudProvider: aws
  configBase: s3://XXX.XXX/XXX.XXX
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.4.3
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    - encryptedVolume: true
      instanceGroup: master-us-west-2b
      name: b
    - encryptedVolume: true
      instanceGroup: master-us-west-2c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.4.3
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      ServiceTopology: "true"
      StartupProbe: "true"
  kubernetesApiAccess:
  - XXX.XXX.XXX.XXX/XX
  - XXX.XXX.XXX.XXX/XX
  kubernetesVersion: 1.17.6
  masterInternalName: api.internal.XXX.XXX
  masterPublicName: api.XXX.XXX
  networkCIDR: XXX.XXX.0.0/16
  networking:
    calico:
      majorVersion: v3
      typhaReplicas: 3
  nonMasqueradeCIDR: XXX.XXX.0.0/10
  sshAccess:
  - XXX.XXX.XXX.XXX/XX
  - XXX.XXX.XXX.XXX/XX
  subnets:
  - cidr: XXX.XXX.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  - cidr: XXX.XXX.64.0/19
    name: us-west-2b
    type: Public
    zone: us-west-2b
  - cidr: XXX.XXX.96.0/19
    name: us-west-2c
    type: Public
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I know this is convoluted behavior and I wouldn't blame you if you wanted to add a "user beware" warning sticker on it and be done.
