### ISSUE TITLE
Nodes created via AutoScale Group are in Unauthorized state with same configuration as authorized nodes.

### ISSUE THREAD

**Issue by lazzarello** [kubernetes/kops#9291]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.17.0-alpha.1 (git-3f34983e6)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T20:32:36Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster
kops update cluster foo
kops update cluster foo --out=./foo --target=terraform
terraform plan
terraform apply
```

**5. What happened after the commands executed?**

The cluster boots correctly and creates the expected instance groups. Then when I adjust the number of desired instances in any Autoscale Group to scale out and scale in, newly created instances cannot register to the apiserver so the worker node can't run scheduled pods. Kubelet logs report "...Unauthorized" when attempting to register to the apiserver URL.

**6. What did you expect to happen?**

Newly created instances should use the same launch configuration and user data as the ones created on the initial `kops create cluster` action. They do not appear to be doing this. At least that's the best I got to understand what's happening.

**7. Please provide your cluster manifest.

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-01-22T06:08:23Z"
  name: launch.ops
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://[redacted]/launch.ops
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    - instanceGroup: master-us-gov-west-1b
      name: b
    - instanceGroup: master-us-gov-west-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    - instanceGroup: master-us-gov-west-1b
      name: b
    - instanceGroup: master-us-gov-west-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.0
  masterPublicName: api.launch.ops
  networkCIDR: 00.000.0.0/16
  networkID: vpc-xxxxxxxx
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 00.000.0.0/19
    id: subnet-xxxxxxxx
    name: us-gov-west-1a
    type: Private
    zone: us-gov-west-1a
  - cidr: 00.000.00.0/19
    id: subnet-xxxxxxxx
    name: us-gov-west-1b
    type: Private
    zone: us-gov-west-1b
  - cidr: 00.000.000.0/19
    id: subnet-xxxxxxxx
    name: us-gov-west-1c
    type: Private
    zone: us-gov-west-1c
  - cidr: 00.000.000.0/22
    id: subnet-xxxxxxxx
    name: utility-us-gov-west-1a
    type: Utility
    zone: us-gov-west-1a
  - cidr: 00.000.000.0/22
    id: subnet-xxxxxxxx
    name: utility-us-gov-west-1b
    type: Utility
    zone: us-gov-west-1b
  - cidr:00.000.000.0/22
    id: subnet-xxxxxxxx
    name: utility-us-gov-west-1c
    type: Utility
    zone: us-gov-west-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:33Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: consumer
spec:
  image: 190570271432/CoreOS-stable-2303.3.0-hvm
  machineType: c5.2xlarge
  maxSize: 2
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: consumer
  role: Node
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b
  - us-gov-west-1c
  taints:
  - dedicated=consumer:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:34Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: launch.ops
  name: general
spec:
  image: 190570271432/CoreOS-stable-2303.3.0-hvm
  machineType: m5.xlarge
  maxSize: 3
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: general
  role: Node
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b
  - us-gov-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:36Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: influx-master
spec:
  image: 190570271432/CoreOS-stable-2303.3.0-hvm
  machineType: c5.4xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: influx-master
  role: Node
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b
  - us-gov-west-1c
  taints:
  - dedicated=influx-master:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:37Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: influx-pool
spec:
  image: 190570271432/CoreOS-stable-2303.3.0-hvm
  machineType: c5d.4xlarge
  maxSize: 6
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: influx-pool
  role: Node
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b
  - us-gov-west-1c
  taints:
  - dedicated=influx-pool:NoSchedule
  volumeMounts:
  - device: /dev/nvme1n1
    filesystem: ext4
    path: /var/lib/influxdb

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:38Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: ingress
spec:
  image: 190570271432/CoreOS-stable-2303.3.0-hvm
  machineType: t3.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: ingress
  role: Node
  subnets:
  - us-gov-west-1a
  - us-gov-west-1b
  - us-gov-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:39Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: master-us-gov-west-1a
spec:
  cloudLabels:
    targetGroup: api-launch-ops
  image: 190570271432/CoreOS-stable-1855.4.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-gov-west-1a
  role: Master
  subnets:
  - us-gov-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:40Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: master-us-gov-west-1b
spec:
  cloudLabels:
    targetGroup: api-launch-ops
  image: 190570271432/CoreOS-stable-1855.4.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-gov-west-1b
  role: Master
  subnets:
  - us-gov-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-06T05:37:40Z"
  labels:
    kops.k8s.io/cluster: launch.ops
  name: master-us-gov-west-1c
spec:
  cloudLabels:
    targetGroup: api-launch-ops
  image: 190570271432/CoreOS-stable-1855.4.0-hvm
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-gov-west-1c
  role: Master
  subnets:
  - us-gov-west-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

kubelet logs from a broken node, launched via same ASG + LaunchConfiguration as working nodes.

```
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.459576    4391 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Unauthorized
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.503818    4391 kubelet.go:2263] node "ip-10-193-141-139.us-gov-west-1.compute.internal" not found
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.603930    4391 kubelet.go:2263] node "ip-10-193-141-139.us-gov-west-1.compute.internal" not found
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: W0606 23:01:38.654866    4391 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d/
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.658304    4391 reflector.go:156] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Unauthorized
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.704057    4391 kubelet.go:2263] node "ip-10-193-141-139.us-gov-west-1.compute.internal" not found
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.766970    4391 eviction_manager.go:246] eviction manager: failed to get summary stats: failed to get node info: node "ip-10-193-141-139.us-gov-west-1.compute.internal" not found
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.769305    4391 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jun 06 23:01:38 ip-10-193-141-139.us-gov-west-1.compute.internal kubelet[4391]: E0606 23:01:38.804169    4391 kubelet.go:2263] node "ip-10-193-141-139.us-gov-west-1.compute.internal" not found
```
**9. Anything else do we need to know?**

I've destroyed and created the cluster numerous times and I get the same outcome.
