### ISSUE TITLE
optionally disable NTP daemon installation+config

### ISSUE THREAD

**Issue by jsleeio** [kubernetes/kops#9307]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

**TLDR**: we build and use our own AWS AMIs with all required packages already installed and would like a toggle that lets me skip some or all of the OS package checks/remediation. We prefer `chrony` over `ntp` for its security track record. The `ntp` package in Ubuntu 18.04 [has unpatched CVEs](https://people.canonical.com/~ubuntu-security/cve/pkg/ntp.html). Additionally we will upgrade to Ubuntu 20.04 and at that point we **definitely** don't want to [switch to `systemd-timesyncd`](https://github.com/kubernetes/kops/pull/9182)

**Previously**: operated clusters on custom AMIs built from Debian stretch and used `execContainer` hooks to replace `ntp` package with `chrony`. This worked fine, though it slowed `nodeup` a little. Looked like the below. I think it was derived from the `cachefilesd` hooks example in the cluster spec docs.

https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks 

```
  hooks:
  - before:
    - kubelet.service
    execContainer:
      command:
      - sh
      - -c
      - chroot /rootfs apt-get update && chroot /rootfs apt-get install -y chrony
        && chroot /rootfs cp /root/chrony.conf /etc/chrony/chrony.conf
      image: busybox
    name: replace-ntpd-with-chrony.service
    requires:
    - ntp.service
  - before:
    - kubelet.service
    manifest: |
      Type=oneshot
      ExecStart=/bin/systemctl restart chrony.service
    name: restart-chrony.service
    requires:
    - replace-ntpd-with-chrony.service
```

**Now**: operating clusters on custom AMIs built from Ubuntu 18.04. `apt-get` seems to require DBus to work at all, so the `execContainer` hack doesn't work anymore, and when I tried to install it with a `oneshot` Systemd unit, `apt-get` kept getting killed with a `SIGTERM` before it could complete. Probably I'm doing something wrong with the Systemd unit, but...

Really I'd prefer to not have to do any of this. My AMIs already have an NTP daemon installed and configured.

**2. Feel free to provide a design supporting your feature request.**

As mentioned above, I don't think the _default_ behaviour should change. The current defaults are good for users that don't feel like setting up their own AMI pipeline.

Maybe a list in the cluster (or instance group?) spec of `nodeup` tasks to skip? In our case we would skip _all_ the package-related tasks, as our AMI already has the required packages.

```
spec:
  nodeup:
    skipTasks:
      - ntp
      - packages
```

There is a precedent here: there's already a knob for skipping the Docker install.

https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#skip-install

One problem with this approach is that users that do build their own cloud images and skip tasks like this would need to pay close attention to any subsequent changes in the prerequisites. I can see this increasing the support burden for `kops`, and that's not good.
