### ISSUE TITLE
Probable networking issue - ec2net.hotplug failing with exit code 1

### ISSUE THREAD

**Issue by xoxbet** [kubernetes/kops#9315]
Kops: 17.0.0
Kubernetes: 1.17.6
Cloud provider: AWS

I have multiple instance groups and this issue seems to appear on both on demand and spot instances.

I did an upgrade from kops 16.2 to 17.0 on my development cluster and then the following errors started to appear in node syslog:
```
Jun 9, 2020 @ 13:35:05.000	Process '/etc/sysconfig/network-scripts/ec2net.hotplug' failed with exit code 1.
Jun 9, 2020 @ 13:35:05.000	Process '/etc/sysconfig/network-scripts/ec2net.hotplug' failed with exit code 1.
Jun 9, 2020 @ 13:35:05.000	Process '/etc/sysconfig/network-scripts/ec2net.hotplug' failed with exit code 1.
Jun 9, 2020 @ 13:35:04.000	Process '/etc/sysconfig/network-scripts/ec2net.hotplug' failed with exit code 1.
Jun 9, 2020 @ 13:35:04.000	Process '/etc/sysconfig/network-scripts/ec2net.hotplug' failed with exit code 1.
Jun 9, 2020 @ 13:35:04.000	Process '/etc/sysconfig/network-scripts/ec2net.hotplug' failed with exit code 1.
```
No additional info in logs.

Cluster manifest with sensitive and non-related info removed:
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-02-25T21:50:18Z"
  generation: 23
  name: <..>
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  <..>
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  <..>
  kubernetesVersion: 1.17.6
  networkCIDR: 10.0.0.0/16
  networkID: <..>
  networking:
    cilium:
      IPTablesRulesNoinstall: false
      autoDirectNodeRoutes: false
      bpfCTGlobalAnyMax: 0
      bpfCTGlobalTCPMax: 0
      clusterName: ""
      cniBinPath: ""
      enableNodePort: false
      enablePrometheusMetrics: true
      enableipv4: false
      enableipv6: false
      monitorAggregation: ""
      nodeInitBootstrapFile: ""
      preallocateBPFMaps: true
      reconfigureKubelet: false
      removeCbrBridge: false
      restartPods: false
      sidecarIstioProxyImage: ""
      toFqdnsEnablePoller: false
      version: v1.6.6
  nonMasqueradeCIDR: 100.64.0.0/10
  <..>
  topology:
    bastion:
      bastionPublicName: <..>
    dns:
      type: Public
    masters: private
    nodes: private

---
<Bastion IG not affected>
---
<Master IGs not affected>
---
<On demand IGs not affected>
---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-02-25T21:50:19Z"
  generation: 15
  labels:
    kops.k8s.io/cluster: <..>
  name: nodes
spec:
  cloudLabels:
    <..>
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxPrice: <..>
  maxSize: 10
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5.large
    - m5n.large
    - m5a.large
    - m5ad.large
    - m5dn.large
    - m5d.large
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    on-demand: "false"
  role: Node
  rootVolumeSize: 40
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
  suspendProcesses:
  - AZRebalance

  --- 

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-20T13:17:50Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: <..>
  name: prometheus-nodes
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: prometheus-nodes
  role: Node
  rootVolumeSize: 30
  subnets:
  - eu-west-1b
  suspendProcesses:
  - AZRebalance
  taints:
  - prometheus=:NoSchedule
```

I'm not sure if this is causing any major problems but I don't feel safe to upgrade my production cluster when seeing this. Do you have any ideas of what could cause this?
