### ISSUE TITLE
After upgrading to 1.17.0 cannot reach the api server intermittently

### ISSUE THREAD

**Issue by feniix** [kubernetes/kops#9327]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
kops version
Version 1.17.0 (git-a17511e6dd)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Upgraded from 1.16.2 to 1.17.0 following the upgrade process documented

**5. What happened after the commands executed?**
N/A

**6. What did you expect to happen?**
N/A

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2016-11-14T00:04:30Z"
  generation: 24
  name: k8s.CLUSTERNAME.net
spec:
  api:
    loadBalancer:
      idleTimeoutSeconds: 300
      sslCertificate: arn:aws:acm:us-east-1:AWSACCOUNT:certificate/94d57c3c-80dc-46fe-90e4-b3d07c6365bd
      type: Public
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://CLUSTERNAME-kubernetes/k8s.CLUSTERNAME.net
  docker:
    insecureRegistry: 100.64.0.0/10
    logDriver: ""
    storage: overlay2,overlay,aufs
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: us-east-1e
    name: main
    provider: Manager
  - etcdMembers:
    - instanceGroup: master-us-east-1e
      name: us-east-1e
    name: events
    provider: Manager
  fileAssets:
  - content: |
      apiVersion: audit.k8s.io/v1beta1 # This is required.
      kind: Policy
      omitStages:
        - "RequestReceived"
      rules:
        - level: RequestResponse
          resources:
          - group: ""
            resources: ["pods"]
        - level: Metadata
          resources:
          - group: ""
            resources: ["pods/log", "pods/status"]

        - level: None
          resources:
          - group: ""
            resources: ["configmaps"]
            resourceNames: ["controller-leader"]

        - level: None
          users: ["system:kube-proxy"]
          verbs: ["watch"]
          resources:
          - group: "" # core API group
            resources: ["endpoints", "services"]

        - level: None
          userGroups: ["system:authenticated"]
          nonResourceURLs:
          - "/api*" # Wildcard matching.
          - "/version"

        - level: Request
          resources:
          - group: "" # core API group
            resources: ["configmaps"]
          namespaces: ["kube-system"]

        - level: Metadata
          resources:
          - group: "" # core API group
            resources: ["secrets", "configmaps"]

        - level: Request
          resources:
          - group: "" # core API group
          - group: "extensions" # Version of group should NOT be included.

        - level: Metadata
          omitStages:
            - "RequestReceived"
    name: audit-policy
    path: /srv/kubernetes/audit.yaml
    roles:
    - Master
  iam:
    legacy: true
  kubeAPIServer:
    auditLogMaxAge: 10
    auditLogMaxBackups: 1
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit.yaml
    runtimeConfig:
      admissionregistration.k8s.io/v1beta1: "true"
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.6
  masterInternalName: api.internal.k8s.CLUSTERNAME.net
  masterPublicName: api.k8s.CLUSTERNAME.net
  networkCIDR: 10.1.0.0/16
  networkID: vpc-ae19a8cb
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.1.160.0/19
    name: us-east-1e
    type: Public
    zone: us-east-1e
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2016-11-14T00:04:31Z"
  generation: 13
  labels:
    kops.k8s.io/cluster: k8s.CLUSTERNAME.net
  name: master-us-east-1e
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1e

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2016-11-14T00:04:31Z"
  generation: 14
  labels:
    kops.k8s.io/cluster: k8s.CLUSTERNAME.net
  name: nodes
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.xlarge
  maxSize: 3
  minSize: 1
  role: Node
  subnets:
  - us-east-1e
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A

**9. Anything else do we need to know?**

I upgraded a cluster from 1.16x to 1.17 going from kops 1.16.2 to 1.17.0. 

This is a single master cluster that we use for testing some small stuff and the gitlab runners etc.
After the upgrade I started having issues with some pods talking to the api intermittently, like this:

`Failed to list *v1.Namespace: Get "https://100.64.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 100.64.0.1:443: connect: no route to host`

after a lot of digging I see that I while I have 2 nodes (1 master and 1 worker node)
I have multiple endpoints to the kubernetes default service

```
kubectl describe service kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                100.64.0.1
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:         10.1.170.97:443,10.1.186.140:443,10.1.188.72:443
Session Affinity:  None
Events:            <none>
```

I think I may have something stale somewhere but I do not know where to look
any ideas?
