### ISSUE TITLE
Kops create -f panic without defining topology

### ISSUE THREAD

**Issue by SNagappan** [kubernetes/kops#943]
`kops create -f cluster.yaml`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4d2998]

goroutine 1 [running]:
panic(0x23d3800, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
k8s.io/kops/pkg/apis/kops.(*Cluster).Validate(0xc8205a4b00, 0xc800000000, 0x0, 0x0)
	/vol/go/bin/src/k8s.io/kops/pkg/apis/kops/validation.go:296 +0x27c8
k8s.io/kops/pkg/client/simple/vfsclientset.(*ClusterVFS).Create(0xc8203cd400, 0xc8205a4b00, 0xc8203cd400, 0x0, 0x0)
	/vol/go/bin/src/k8s.io/kops/pkg/client/simple/vfsclientset/cluster.go:86 +0x4a
main.RunCreate(0xc8204b0f00, 0xc820450fc0, 0x7fac66cb7330, 0xc820026010, 0xc8204b1020, 0x0, 0x0)
	/vol/go/bin/src/k8s.io/kops/cmd/kops/create.go:107 +0xc27
main.NewCmdCreate.func1(0xc820450fc0, 0xc82044c480, 0x0, 0x4)
	/vol/go/bin/src/k8s.io/kops/cmd/kops/create.go:53 +0x99
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc820450fc0, 0xc82044c440, 0x4, 0x4, 0x0, 0x0)
	/vol/go/bin/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x896
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3c9b840, 0xc820450fc0, 0x0, 0x0)
	/vol/go/bin/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x55c
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x3c9b840, 0x0, 0x0)
	/vol/go/bin/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2d
main.Execute()
	/vol/go/bin/src/k8s.io/kops/cmd/kops/root.go:70 +0x1bb
main.main()
	/vol/go/bin/src/k8s.io/kops/cmd/kops/main.go:31 +0x14
```

Here is my cluster.yaml file. I redacted some information. It's the same information as what I see in the create -> edit -> update sequence which works without problems.

```
kind: Cluster
apiVersion: kops/v1alpha1
metadata:
  name: example.com
spec:
  adminAccess:
  - 0.0.0.0/0
  channel: stable
  cloudProvider: aws
  configBase: s3://example-bucket/example.com
  etcdClusters:
  - etcdMembers:
    - name: us-west-1c
      zone: us-west-1c
    name: main
    etcdMembers:
    - name: us-west-1c
      zone: us-west-1c
    name: events
  kubernetesVersion: 1.4.5
  masterPublicName: api.example.com
  networkCIDR: redacted
  networkID: redacted
  networking:
    kubenet: {}
  nonMasqueradeCIDR: redacted
  zones:
  - cidr: redacted
    name: us-west-1c
```
