### ISSUE TITLE
After upgrade to 1.16.10: Random dns failures and kernel flooded with IPVS: Creating netns size=2104 id=XXX  messages

### ISSUE THREAD

**Issue by pshanoop** [kubernetes/kops#9433]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`Version 1.16.0 (git-4b0e62b82)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops upgrade cluster`
`kops update cluster --yes`
`kops rolling-update --yes`

Update was from 1.16.8 to 1.16.10

**5. What happened after the commands executed?**
Cluster updated successfully.  But with kernel logs flooded with `IPVS: Creating netns size=2104 id=7210` and dns failures on pod

**6. What did you expect to happen?**
Dns works fine and kernel doesn't have any flooded messages.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-12-12T16:08:07Z"
  generation: 3
  name: k-production.company.iog
spec:
  additionalPolicies:
    master: |
      [
        {
          "Sid": "PassRole",
          "Effect": "Allow",
          "Action": "sts:AssumeRole",
          "Resource": "*"
        }
      ]
    node: |
      [
        {
          "Sid": "PassRole",
          "Effect": "Allow",
          "Action": "sts:AssumeRole",
          "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      crossZoneLoadBalancing: true
      sslCertificate: arn:aws:acm:eu-central-1:aws-account-number:certificate/id
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state/k-production.company.iog
  dnsZone: Z051843416IJIYW78BT23
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    legacy: false
  kubeAPIServer:
    authorizationMode: RBAC
    oidcClientID: kubernetes
    oidcGroupsClaim: groups
    oidcIssuerURL: https://auth.k-production.company.iog/dex
    oidcUsernameClaim: email
    runtimeConfig:
      rbac.authorization.k8s.io/v1alpha1: "true"
  kubeProxy:
    metricsBindAddress: 0.0.0.0
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.10
  masterInternalName: api.internal.k-production.company.iog
  masterPublicName: api.k-production.company.iog
  networkCIDR: 10.3.0.0/16
  networkID: vpc-00000000000
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.3.4.0/22
    id: subnet-00000000000
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.3.8.0/22
    id: subnet-0000000000
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 10.3.12.0/22
    id: subnet-0000000
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 10.3.16.0/22
    id: subnet-0000000
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 10.3.20.0/22
    id: subnet-0000000
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 10.3.24.0/22
    id: subnet-0000000
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-12T16:08:07Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: master-eu-central-1a
spec:
  additionalSecurityGroups:
  - sg-00000000
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-12T16:08:07Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: master-eu-central-1b
spec:
  additionalSecurityGroups:
  - sg-00000000
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-12-12T16:08:07Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: master-eu-central-1c
spec:
  additionalSecurityGroups:
  - sg-00000000
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1c
  role: Master
  subnets:
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:05:28Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: nodes-base
spec:
  additionalSecurityGroups:
  - sg-00000000
  cloudLabels:
    Owner: DevOps
    instanceGroup: nodes-base
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/k-production.company.iog: ""
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.xlarge
  maxSize: 15
  minSize: 5
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: nodes-base
    company.iog/node-importance: high
    company.iog/node-type: on-demand
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:05:28Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: nodes-infra-eu-central-1a
spec:
  additionalSecurityGroups:
  - sg-00000000
  cloudLabels:
    Owner: DevOps
    instanceGroup: nodes-infra
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/k-production.company.iog: ""
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.2xlarge
  maxSize: 15
  minSize: 0
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: nodes-infra
    company.iog/node-importance: high
    company.iog/node-type: infra
  role: Node
  subnets:
  - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:05:29Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: nodes-infra-eu-central-1b
spec:
  additionalSecurityGroups:
  - sg-00000000
  cloudLabels:
    Owner: DevOps
    instanceGroup: nodes-infra
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/k-production.company.iog: ""
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.2xlarge
  maxSize: 15
  minSize: 0
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: nodes-infra
    company.iog/node-importance: high
    company.iog/node-type: infra
  role: Node
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-29T15:05:29Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k-production.company.iog
  name: nodes-infra-eu-central-1c
spec:
  additionalSecurityGroups:
  - sg-00000000
  cloudLabels:
    Owner: DevOps
    instanceGroup: nodes-infra
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/k-production.company.iog: ""
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m4.2xlarge
  maxSize: 15
  minSize: 0
  nodeLabels:
    beta.kubernetes.io/fluentd-ds-ready: "true"
    kops.k8s.io/instancegroup: nodes-infra
    company.iog/node-importance: high
    company.iog/node-type: infra
  role: Node
  subnets:
  - eu-central-1c
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
It also has randomly this message too
```
[  +0.335340] IPv6: ADDRCONF(NETDEV_UP): cali69c0da2c4dc: link is not ready
[  +0.004815] IPv6: ADDRCONF(NETDEV_CHANGE): cali69c0da2c4dc: link becomes ready
```

I have similar kind of cluster setup in another environment it seems stable.
I also not sure if this right place to put this bug/issue. Sorry, If it's wrong place.
