### ISSUE TITLE
aws classic load balancer becomes inactive after a while

### ISSUE THREAD

**Issue by iojas** [kubernetes/kops#9438]
Hi all, 

I am standing up a kubernetes cluster using kops with following command. 
```

kops create cluster \                                                                           
    --name mycluster.com.k8s.local \
    --zones "ap-south-1a" \
    --master-size t3.micro  \
    --master-count 1 \
    --node-size t3.micro \
    --node-count 1 \
    --networking calico 
```

when the cluster stands up it's accessible with kubectl commands. but after about 6-8 hours my load balancer becomes unhealthy. 

Instance to which load balancer is pointing to, master on kubernetes cluster, is running. the health check is failing that is why load balancer thinks instance status is unhealthy. 

`kubectl get all `

returns 

`Unable to connect to the server: EOF`

`kops validate cluster`

returns

`unexpected error during validation: error listing nodes: Get "https://api-mycluster-com--hllh7h-1281346414.ap-south-1.elb.amazonaws.com/api/v1/nodes": EOF`

I have tried creating a cluster at least 5 times and end up with the same result.

here is the cluster config kops create generates. 

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: mycluster.com.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mycluster.com/mycluster.com.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.0
  masterPublicName: api.mycluster.com.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: mycluster.com.k8s.local
  name: master-ap-south-1a
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1a
  role: Master
  subnets:
  - ap-south-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: mycluster.com.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - ap-south-1a
```

what am I missing here? Any inputs will be helpful.
