### ISSUE TITLE
scripts configured in InstanceGroup additionalUserData should be run before nodeup.sh

### ISSUE THREAD

**Issue by weisjohn** [kubernetes/kops#9441]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

[cloud-init config/scripts specified via the InstanceGroup `additionalUserData` setting](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#additionaluserdata) are [rendered by `nodeup.go` _after_ the `nodeup.sh` template](https://github.com/kubernetes/kops/blob/f5ce011fa036034e8b40d0dc94bc5bfc2419bc56/pkg/model/resources/nodeup.go#L208-L221) in the AWS AutoScalingGroup LaunchConfiguration.

In my use-case, I have to add a root certificate to the instance's trust stores via an inlined script in the `additionalUserData`, [as shown in the kops docs on the cluster_spec](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#optional-step-add-root-certificates-to-instancegroups-root-ca-bundle).

My cluster runs inside a network with a TLS terminating proxy at the gateway. (This proxy is transparent and not addressible, so I have no `HTTPS_PROXY` escape hatch).  This means all of the [attempts to download the assets](https://github.com/kubernetes/kops/blob/f5ce011fa036034e8b40d0dc94bc5bfc2419bc56/pkg/model/resources/nodeup.go#L65-L69) will fail until after my script runs. 

NOTE: I've also tried [workarounds like using cloud-init's configuration to inline the PEM directly](https://cloudinit.readthedocs.io/en/latest/topics/examples.html?highlight=certificate#configure-an-instances-trusted-ca-certificates), however, that does not work as that [only supports cloud-init step only supports debian and ubuntu](https://github.com/canonical/cloud-init/blob/7c88f96245535aacfac9b0b04d9c0d82ac2067f4/cloudinit/config/cc_ca_certs.py#L23) and I am using Amazon Linux. (Discovering why this was silently failing was fairly difficult). Other work-arounds include bundling the PEM into an AMI or using the AWS API to modifying the userData in the AWS ASG Launch Config, but then I break my team's desired `kops` workflow.

**2. Feel free to provide a design supporting your feature request.**

1. [Modify the nodeup.go renderer to put additionalUserData _before_ nodeup ](https://github.com/kubernetes/kops/blob/f5ce011fa036034e8b40d0dc94bc5bfc2419bc56/pkg/model/resources/nodeup.go#L208-L221) _or_
2. Extend the InstanceGroup config to include an additional configuration like `preflightUserData` or `preNodeupUserData` and extend `nodeup.go` to render it before `nodeup.sh`.

I'm thinking #1 is actually a _bad idea_, but perhaps most users might expect this work this way(?). I'm planning on trying to hack up a PoC on #2, but I wanted to see if this PR would even be welcomed before submitting.

**Comment by rifelpet** [comment]
Rather than a new InstanceGroupSpec field we could add a new field within each additionalUserData item. Two ideas for how we could implement this:

1. A numerical field like “priority” or “order” where userdata items are sorted by the field and the nodeup code occurs at a well-known number. 

2. An enum-like string field with possible values that mean “before nodeup” and “after nodeup”. This would allow future values if there are other cases we’d want to handle.

I’m a fan of 1. except for nodeup having a “magic” number, though I suppose it could be mentioned in the new field’s docs. Anyone have other ideas?

**Comment by weisjohn** [comment]
More digging here, I built a version of `kops` locally to put my scripts before `nodeup.sh`. Here's the userData for my AWS AutoScalingGroup Instance Config (truncated for visibility)

```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Disposition: attachment; filename="provisioner-trust-root-ca.yaml"
Content-Transfer-Encoding: 7bit
Content-Type: text/cloud-config
Mime-Version: 1.0

#cloud-config
write_files:
- path: /etc/pki/ca-trust/source/anchors/provisioner-0.crt
  content: |
    -----BEGIN CERTIFICATE-----
    ...snip...
    -----END CERTIFICATE-----
--MIMEBOUNDARY
Content-Disposition: attachment; filename="provisioner-trust-root-ca.sh"
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

#!/bin/sh
trust="/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
log="/root/provisioner-update-ca-trust-time.txt"
before=$(mktemp)
grep "${trust}" -e "#" > "${before}"
sudo update-ca-trust
after=$(mktemp)
grep "${trust}" -e "#" > "${after}"
echo "added the following certs on: $(date)" | sudo tee "${log}"
diff "${before}" "${after}" | sudo tee -a "${log}"
--MIMEBOUNDARY
Content-Disposition: attachment; filename="nodeup.sh"
Content-Transfer-Encoding: 7bit
Content-Type: text/x-shellscript
Mime-Version: 1.0

#!/bin/bash
# Copyright 2016 The Kubernetes Authors All rights reserved.
#    ...snip...
--MIMEBOUNDARY--
```

You can see my `additionalUserData` is rendered before `nodeup.sh`, but after bringing up the cluster, looking at `/var/log/cloud-init.log`, it still showed nodeup running _before_ my script. (Relevant log lines):

```
Jun 25 00:22:56 cloud-init[3586]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-020d8607bbb9c41ae/sem/config_scripts_user'>)
Jun 25 00:22:56 cloud-init[3586]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/nodeup.sh'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 00:26:15 cloud-init[3586]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/provisioner-trust-root-ca.sh'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 00:26:17 cloud-init[3586]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
```

Noticing the timestamps between the logs, nodeup runs first and then after ~3 minutes, my script runs, implying they're sequential, and since `nodeup,sh` begins with the letter `n` and my script begins with the letter `p`, I am now assuming they're alphabetical...

And, coincidentally, the [example of using `additionalUserData` uses a script named `myscript.sh`](https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#additionaluserdata), which you'll notice begins with a `m`.... "m" > "n" > "p". 

Here's a verbose example....

My instance-group config:

```yaml
λ kops get ig nodes -o yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-25T00:20:07Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: infradev3.k8s.local
  name: nodes
spec:
  additionalUserData:
  - content: |-
      #!/bin/sh
      echo "mu $(date)" | sudo tee "/root/out.txt"
    name: mu.sh
    type: text/x-shellscript
  - content: |-
      #!/bin/sh
      echo "zeta $(date)" | sudo tee "/root/out.txt"
    name: zeta.sh
    type: text/x-shellscript
  - content: |-
      #!/bin/sh
      echo "alpha $(date)" | sudo tee "/root/out.txt"
    name: alpha.sh
    type: text/x-shellscript
  - content: |-
      #!/bin/sh
      echo "phi $(date)" | sudo tee "/root/out.txt"
    name: phi.sh
    type: text/x-shellscript
  image: ami-74c4f215
  machineType: t3.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-gov-west-1a
```

and here's the `/var/log/cloud-init.log` from the node, as expected:

```
Jun 25 03:18:06 cloud-init[2774]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/alpha.sh'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 03:18:06 cloud-init[2774]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/mu.sh'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 03:18:06 cloud-init[2774]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/nodeup.sh'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 03:19:16 cloud-init[2774]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/phi.sh'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 03:19:16 cloud-init[2774]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/zeta.sh'] with allowed return codes [0] (shell=True, capture=False)
```

At this point, I don't think my proposal is valid, because the sort order in the AWS ASG does not translate to run order, however it may be worth documenting that the alphabetical name will be interpreted by `cloud-init` that way. 
This doesn't seem to be documented anywhere in the cloud-init project from what I can tell.
