### ISSUE TITLE
aws-iam-authenticator v0.5.1 backend-mode(s)

### ISSUE THREAD

**Issue by fred-vogt** [kubernetes/kops#9468]
Would like to get this one in before the first office hours in July 2020.

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Support for `backend-mode`s that don't require restarting the containers running on masters when mappings are updated.

Currently kops deploys `aws-iam-authenticator` with a volume mounted ConfigMap - this is the `mounted-file` backend-mode.

@rifelpet - I think you were going to add a `clusterspec.authentication.aws.backendMode` setting already.

**2. Feel free to provide a design supporting your feature request.**
```yaml
  authentication:
    aws:
      backendMode: CRD,EKSConfigMap,MountedFile
```

BTW - Tested with latest release - Its safe to use as new default image
```yaml
  authentication:
    aws: 
      image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.5.1-stretch
```

## Docs
* https://kubernetes-kops.netlify.app/authentication/
  * https://github.com/kubernetes/kops/blob/master/docs/authentication.md

## Links
* https://github.com/kubernetes/kops/blob/master/docs/releases/1.17-NOTES.md#known-issues
  * [Update AWS IAM Authenticator to 0.5.0](https://github.com/kubernetes/kops/commit/32e6a6b53477131f084f0ef82b7ff3aa8853a354#diff-49ab9104184d27772708fb0ecd00e0aa)
* https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.1
