### ISSUE TITLE
[Question] How to enable Ephemeral Containers 

### ISSUE THREAD

**Issue by emirot** [kubernetes/kops#9469]
Hey there,

I would like to enable ephemeral container (https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container) in a dev cluster.
However, I don't understand how to activate that feature using kops.
Looking at:
- https://kops.sigs.k8s.io/cluster_spec/#feature-gates
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

It looks like only this need to be added:
```
    featureGates:
      EphemeralContainers: "true"
```
But I get `error: ephemeral containers are disabled for this cluster (error from server: "the server could not find the requested resource").`

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-07-01T19:13:30Z"
  generation: 1
  name: cluster.mydomain.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-mydomain-com-state-store/cluster.mydomain.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    featureGates:
      EphemeralContainers: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.5
  masterInternalName: api.internal.cluster.mydomain.com
  masterPublicName: api.cluster.mydomain.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**Comment by olemarkus** [comment]
When gated features affects resources, you typically also have to add the feature gate to `kubeAPIServer` as the docs says.

**Comment by emirot** [comment]
Thanks a lot @olemarkus, I missed that.

Updating to 
```
  kubeAPIServer:
    featureGates:
      EphemeralContainers: "true"
  kubelet:
    anonymousAuth: false
    featureGates:
      EphemeralContainers: "true"

```
And now it works !
