### ISSUE TITLE
Subnet is not actually deleted after it's removed from cluster spec

### ISSUE THREAD

**Issue by zagr0** [kubernetes/kops#9506]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.16.0 (git-4b0e62b82)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
- update cluster spec, remove one of subnets with `kops edit cluster`
- run `kops update cluster`

**5. What happened after the commands executed?**
nothing happens, kops does not recognize the changes, subnet is missing in spec, but kops does not remove it actually from AWS

**6. What did you expect to happen?**
kops should remove those subnets with related resources like nat gateway, routes

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
before change
```
  subnets:
  - cidr: 172.11.44.0/22
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.11.48.0/22
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.11.52.0/22
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.11.32.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.11.36.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.11.40.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```
after change
```
  subnets:
  - cidr: 172.11.44.0/22
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.11.32.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.11.36.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.11.40.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
