### ISSUE TITLE
Cluster upgrade from 1.15.12 to 1.16.0 failing

### ISSUE THREAD

**Issue by Priyanka098** [kubernetes/kops#9587]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.15.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 54.93.250.80:443: i/o timeout

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Run following commands on k8s cluster version 1.15.12
kops edit cluster --name=example.com(kubernetesVersion: 1.16.2)
kops upgrade cluster --name=example.com
kops upgrade cluster --name=example.com --yes
kops update cluster --name=example.com 
kops update cluster --name=example.com --yes
kops rolling-update cluster --name= example.com
kops rolling-update cluster --name= example.com --yes

**5. What happened after the commands executed?**
ERROR: 
unexpected error during validation: error listing nodes: Get https://example.com/api/v1/nodes: dial tcp 54.93.250.76:443: i/o timeout

**6. What did you expect to happen?**
Cluster updated to 1.16.0 version

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-12T09:29:14Z"
  generation: 1
  name: example.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my.cluster.bucket/example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1b
      name: b
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1b
      name: b
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.2
  masterInternalName: api.internal.example.com
  masterPublicName: api.example.com
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-12T09:29:14Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: example.com
  name: master-eu-central-1b
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1b
  role: Master
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-13T10:07:01Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: example.com
  name: mongo-x-c
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 4
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: mongo-x-c
  role: Node
  subnets:
  - eu-central-1b
  taints:
  - dedicated=mongo-x-c:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-13T10:46:18Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: example.com
  name: mongo-x-p
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: mongo-x-p
  role: Node
  subnets:
  - eu-central-1b
  taints:
  - dedicated=mongo-x-p:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-12T09:29:14Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: example.com
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: r4.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-13T10:07:00Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: example.com
  name: nodes-x-c
spec:
  image: 383156758163/k8s-1.11-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: r4.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-x-c
  role: Node
  subnets:
  - eu-central-1b
  taints:
  - dedicated=nodes-x-c:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-13T10:46:17Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: example.com
  name: nodes-x-p
spec:
  image: 383156758163/k8s-1.11-debian-jessie-amd64-hvm-ebs-2018-08-17
  machineType: r4.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-x-p
  role: Node
  subnets:
  - eu-central-1b
  taints:
  - dedicated=nodes-x-p:NoSchedule
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
command - kops validate cluster -v 10

I0717 11:29:38.727022    1361 loader.go:359] Config loaded from file:  /home/ubuntu/.kube/config
Using cluster from kubectl context: exampple.com

I0717 11:29:38.727342    1361 factory.go:68] state store s3://my.cluster.bucket
I0717 11:29:38.727468    1361 s3context.go:325] unable to read /sys/devices/virtual/dmi/id/product_uuid, assuming not running on EC2: open /sys/devices/virtual/dmi/id/product_uuid: permission denied
I0717 11:29:38.727569    1361 s3context.go:170] defaulting region to "us-east-1"
I0717 11:29:39.163563    1361 s3context.go:210] found bucket in region "eu-central-1"
I0717 11:29:39.163850    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/config"
I0717 11:29:39.235693    1361 s3fs.go:257] Listing objects in S3 bucket "my.cluster.bucket" with prefix "exampple.com/instancegroup/"
I0717 11:29:39.251058    1361 s3fs.go:285] Listed files in s3://my.cluster.bucket/exampple.com/instancegroup: [s3://my.cluster.bucket/exampple.com/instancegroup/master-eu-central-1b s3://my.cluster.bucket/exampple.com/instancegroup/mongo-x-c s3://my.cluster.bucket/exampple.com/instancegroup/mongo-x-p s3://my.cluster.bucket/exampple.com/instancegroup/nodes s3://my.cluster.bucket/exampple.com/instancegroup/nodes-x-c s3://my.cluster.bucket/exampple.com/instancegroup/nodes-x-p]
I0717 11:29:39.251216    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/instancegroup/master-eu-central-1b"
I0717 11:29:39.266701    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/instancegroup/mongo-x-c"
I0717 11:29:39.280403    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/instancegroup/mongo-x-p"
I0717 11:29:39.303726    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/instancegroup/nodes"
I0717 11:29:39.316797    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/instancegroup/nodes-x-c"
I0717 11:29:39.374778    1361 s3fs.go:220] Reading file "s3://my.cluster.bucket/exampple.com/instancegroup/nodes-x-p"
Validating cluster exampple.com

I0717 11:29:39.450428    1361 validate_cluster.go:113] instance group: kops.InstanceGroupSpec{Role:"Master", Image:"kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17", MinSize:(*int32)(0xc0006f80cc), MaxSize:(*int32)(0xc0006f80c0), MachineType:"m5.xlarge", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1b"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"master-eu-central-1b"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string(nil), MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil), InstanceProtection:(*bool)(nil)}

I0717 11:29:39.450564    1361 validate_cluster.go:113] instance group: kops.InstanceGroupSpec{Role:"Node", Image:"kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17", MinSize:(*int32)(0xc0006f8dfc), MaxSize:(*int32)(0xc0006f8df0), MachineType:"m5.large", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1b"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"mongo-x-c"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string{"dedicated=mongo-x-c:NoSchedule"}, MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil), InstanceProtection:(*bool)(nil)}

I0717 11:29:39.450655    1361 validate_cluster.go:113] instance group: kops.InstanceGroupSpec{Role:"Node", Image:"kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17", MinSize:(*int32)(0xc0006f98ec), MaxSize:(*int32)(0xc0006f98e0), MachineType:"m5.large", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1b"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"mongo-x-p"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string{"dedicated=mongo-x-p:NoSchedule"}, MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil), InstanceProtection:(*bool)(nil)}

I0717 11:29:39.450764    1361 validate_cluster.go:113] instance group: kops.InstanceGroupSpec{Role:"Node", Image:"kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17", MinSize:(*int32)(0xc00088626c), MaxSize:(*int32)(0xc000886260), MachineType:"r4.large", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1b"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"nodes"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string(nil), MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil), InstanceProtection:(*bool)(nil)}

I0717 11:29:39.450848    1361 validate_cluster.go:113] instance group: kops.InstanceGroupSpec{Role:"Node", Image:"383156758163/k8s-1.11-debian-jessie-amd64-hvm-ebs-2018-08-17", MinSize:(*int32)(0xc000886c3c), MaxSize:(*int32)(0xc000886c30), MachineType:"r4.large", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1b"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"nodes-x-c"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string{"dedicated=nodes-x-c:NoSchedule"}, MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil), InstanceProtection:(*bool)(nil)}

I0717 11:29:39.450950    1361 validate_cluster.go:113] instance group: kops.InstanceGroupSpec{Role:"Node", Image:"383156758163/k8s-1.11-debian-jessie-amd64-hvm-ebs-2018-08-17", MinSize:(*int32)(0xc0008875ec), MaxSize:(*int32)(0xc0008875e0), MachineType:"r4.large", RootVolumeSize:(*int32)(nil), RootVolumeType:(*string)(nil), RootVolumeIops:(*int32)(nil), RootVolumeOptimization:(*bool)(nil), Volumes:[]*kops.VolumeSpec(nil), VolumeMounts:[]*kops.VolumeMountSpec(nil), Subnets:[]string{"eu-central-1b"}, Zones:[]string(nil), Hooks:[]kops.HookSpec(nil), MaxPrice:(*string)(nil), AssociatePublicIP:(*bool)(nil), AdditionalSecurityGroups:[]string(nil), CloudLabels:map[string]string(nil), NodeLabels:map[string]string{"kops.k8s.io/instancegroup":"nodes-x-p"}, FileAssets:[]kops.FileAssetSpec(nil), Tenancy:"", Kubelet:(*kops.KubeletConfigSpec)(nil), Taints:[]string{"dedicated=nodes-x-p:NoSchedule"}, MixedInstancesPolicy:(*kops.MixedInstancesPolicySpec)(nil), AdditionalUserData:[]kops.UserData(nil), SuspendProcesses:[]string(nil), ExternalLoadBalancers:[]kops.LoadBalancer(nil), DetailedInstanceMonitoring:(*bool)(nil), IAM:(*kops.IAMProfileSpec)(nil), SecurityGroupOverride:(*string)(nil), InstanceProtection:(*bool)(nil)}

I0717 11:29:39.451677    1361 loader.go:359] Config loaded from file:  /home/ubuntu/.kube/config
I0717 11:29:39.455226    1361 loader.go:359] Config loaded from file:  /home/ubuntu/.kube/config
I0717 11:29:39.461942    1361 aws_cloud.go:1234] Querying EC2 for all valid zones in region "eu-central-1"
I0717 11:29:39.462130    1361 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones
I0717 11:29:39.511128    1361 round_trippers.go:419] curl -k -v -XGET  -H "User-Agent: kops/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Accept: application/json, */*" -H "Authorization: Basic YWRtaW46SFVkWnlJU3ZUN09aeFkzdmJPcllVMUJFOUVPNm5ra2E=" 'https://api.exampple.com/api/v1/nodes'
I0717 11:30:09.511622    1361 round_trippers.go:438] GET https://api.exampple.com/api/v1/nodes  in 30000 milliseconds
I0717 11:30:09.511650    1361 round_trippers.go:444] Response Headers:

unexpected error during validation: error listing nodes: Get https://api.exampple.com/api/v1/nodes: dial tcp 54.93.250.80:443: i/o timeout

**9. Anything else do we need to know?**
