### ISSUE TITLE
mixedInstancesPolicy refuses to accept EC2 instance type "r6g.large"

### ISSUE THREAD

**Issue by slashr** [kubernetes/kops#9607]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.17.1 (git-4dfd4779fe)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops edit ig nodes` 

**5. What happened after the commands executed?**
`nodes.instances[3].instanceType: Invalid value: "r6g.large": machine type specified is invalid`

**6. What did you expect to happen?**
Expected that the instance type r6g.large would be accepted

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-02-04T14:30:51Z"
  generation: 6
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    - instanceGroup: master-eu-central-1b
      name: b
    - instanceGroup: master-eu-central-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2beta1: "true"
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.6
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.32.144.0/20
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 172.32.160.0/20
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 172.32.176.0/20
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 172.32.192.0/22
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 172.32.208.0/22
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 172.32.224.0/22
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    bastion:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-02-04T14:30:52Z"
  generation: 14
  labels:
  name: nodes
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  kubelet:
    evictionHard: memory.available<500Mi,nodefs.available<10%
    systemReserved:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 1.5Gi
  machineType: r6g.large
  maxSize: 20
  minSize: 7
  mixedInstancesPolicy:
    instances:
    - r5.large
    - t3.large
    - t3a.large
    onDemandAboveBase: 0
    onDemandBase: 7
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    ProdClusterAutoscaling: Enabled
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Seems like a bug with KOPS because it accepts r6g.large in `spec.machineType` but not inside `spec.mixedInstancesPolicy.instances`
