### ISSUE TITLE
kops don't retry validation when rolling-update

### ISSUE THREAD

**Issue by h3poteto** [kubernetes/kops#9618]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.17.1 (git-4dfd4779fe)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.16.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I want to update my Kubernetes cluster.

1. `kops edit cluster $CLUSTER_NAME`
2. I rewrite Kubernetes version to 1.17.9
3. `kops update cluster --yes`
4. `kops rolling-update cluster $CLUSTER_NAME --yes`

**5. What happened after the commands executed?**

kops said

```
NAME                    STATUS          NEEDUPDATE      READY   MIN     MAX     NODES
master-ap-northeast-1a  NeedsUpdate     1               0       1       1       1
master-ap-northeast-1c  NeedsUpdate     1               0       1       1       1
master-ap-northeast-1d  NeedsUpdate     1               0       1       1       1
I0723 21:15:24.187611  162418 instancegroups.go:157] Draining the node: "ip-10-0-12-130.ap-northeast-1.compute.internal".
WARNING: ignoring DaemonSet-managed Pods: kube-system/aws-iam-authenticator-dnv5f, kube-system/aws-node-h2brx, kube-system/kops-controller-twszk, monitoring/prometheus-node-exporter-q8nbh
evicting pod "dns-controller-6b798bf6d5-jl6jt"
I0723 21:15:35.493947  162418 instancegroups.go:363] Waiting for 5s for pods to stabilize after draining.
I0723 21:15:40.494083  162418 instancegroups.go:176] deleting node "ip-10-0-12-130.ap-northeast-1.compute.internal" from kubernetes
I0723 21:15:40.519892  162418 instancegroups.go:302] Stopping instance "i-0d3fb67617841cb7b", node "ip-10-0-12-130.ap-northeast-1.compute.internal", in group "master-ap-northeast-1a.masters.my-cluster" (this may take a while).
I0723 21:15:40.809292  162418 instancegroups.go:189] waiting for 15s after terminating instance
I0723 21:15:55.809417  162418 instancegroups.go:196] Validating the cluster.
W0723 21:15:56.282015  162418 aws_cloud.go:673] ignoring instance as it is terminating: i-0d3fb67617841cb7b in autoscaling group: master-ap-northeast-1a.masters.my-cluster
I0723 21:15:56.355443  162418 instancegroups.go:268] Cluster did not pass validation, will try again in "30s" until duration "15m0s" expires: InstanceGroup "master-ap-northeast-1a" did not have enough nodes 0 vs 1.
```

but it did not retry validation.
I waited 30 seconds, but kops did not say any logs. After that I waited 15 minutes, but kops did not say any logs. At this time, master node has already created and joined Kubernetes cluster.

kops said nothing any more, so I kill this process with `Ctrl + c`.

**6. What did you expect to happen?**

Please retry validation and update next nodes after pass the validation.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 8
  name: my-cluster
spec:
  api:
    dns: {}
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://my-cluster
  dnsZone: Z21DTFU4BHSZ51
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ap-northeast-1a
      name: a
    - instanceGroup: master-ap-northeast-1c
      name: c
    - instanceGroup: master-ap-northeast-1d
      name: d
    memoryRequest: 100Mi
    name: events
  fileAssets:
  - content: ****
    isBase64: true
    name: service-account-signing-key-file
    path: /srv/kubernetes/assets/service-account-signing-key
  - content: ****
    isBase64: true
    name: service-account-key-file
    path: /srv/kubernetes/assets/service-account-key
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    apiAudiences:
    - ****.s3.amazonaws.com
    serviceAccountIssuer: https://****.s3.amazonaws.com
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    - /srv/kubernetes/assets/service-account-key
    serviceAccountSigningKeyFile: /srv/kubernetes/assets/service-account-signing-key
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.9
  masterInternalName: api.internal.my-cluster
  masterPublicName: api.my-cluster
  networkCIDR: 10.0.0.0/16
  networkID: vpc-fb354b9c
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 10.0.0.0/16
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.0.0/20
    id: subnet-fa7f7fb3
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 10.0.16.0/20
    id: subnet-70bbc92b
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 10.0.32.0/20
    id: subnet-f45541dc
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: my-cluster
  name: master-ap-northeast-1a
spec:
  iam:
    profile: arn:aws:iam::****:instance-profile/k8s-master-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1a
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: my-cluster
  name: master-ap-northeast-1c
spec:
  iam:
    profile: arn:aws:iam::****:instance-profile/k8s-master-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1c
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: my-cluster
  name: master-ap-northeast-1d
spec:
  iam:
    profile: arn:aws:iam:****:instance-profile/k8s-master-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.small
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-northeast-1d
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-0110c581f1db6223d
  subnets:
  - ap-northeast-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-28T15:37:11Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: my-cluster
  name: nodes
spec:
  cloudLabels:
    datadog: enabled
  iam:
    profile: arn:aws:iam::****:instance-profile/k8s-node-profile
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: t3.medium
  maxPrice: "0.05"
  maxSize: 5
  minSize: 2
  nodeLabels:
    datadog: enabled
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  securityGroupOverride: sg-02c91c8f054c85937
  subnets:
  - ap-northeast-1a
  - ap-northeast-1c
  - ap-northeast-1d
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
