### ISSUE TITLE
How to enable HPAScaleToZero

### ISSUE THREAD

**Issue by devsentient** [kubernetes/kops#9643]
I'm trying to enable the HPAScaleToZero on the Kops cluster.

Currently my cluster config looks like this:

```
  kubeAPIServer:
    featureGates:
      HPAScaleToZero: "true"

  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    featureGates:
      HPAScaleToZero: "true"
```
and yet when I try to set the min replicas to in an HPA resource it comes back as invalid.
Any thoughts on what could be missing?
