### ISSUE TITLE
Panic error when creating a cluster using a config file

### ISSUE THREAD

**Issue by CliMz** [kubernetes/kops#966]
Hi,

I tried to create a cluster using a config file and got the error below : 
```
bash-3.2$ kops create -f clusterConf02.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5642]

goroutine 1 [running]:
panic(0x17c7260, 0xc4200160a0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
k8s.io/kops/pkg/apis/kops.(*Cluster).Validate(0xc4200b78c0, 0x1a69900, 0x8, 0x1a66d76)
	/Users/julien/src/k8s.io/kops/pkg/apis/kops/validation.go:296 +0x642
k8s.io/kops/pkg/client/simple/vfsclientset.(*ClusterVFS).Create(0xc420012f00, 0xc4200b78c0, 0xc420012f00, 0x4c6, 0x0)
	/Users/julien/src/k8s.io/kops/pkg/client/simple/vfsclientset/cluster.go:88 +0x45
main.RunCreate(0xc4204b6160, 0xc42010e900, 0x2768760, 0xc42002e010, 0xc4204b6280, 0x1, 0xc420562090)
	/Users/julien/src/k8s.io/kops/cmd/kops/create.go:107 +0xacc
main.NewCmdCreate.func1(0xc42010e900, 0xc4204b6960, 0x0, 0x2)
	/Users/julien/src/k8s.io/kops/cmd/kops/create.go:53 +0x74
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc42010e900, 0xc4204b6800, 0x2, 0x2, 0xc42010e900, 0xc4204b6800)
	/Users/julien/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x283aee0, 0x16a4600, 0x0, 0x0)
	/Users/julien/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x283aee0, 0x28668b8, 0x0)
	/Users/julien/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
	/Users/julien/src/k8s.io/kops/cmd/kops/root.go:70 +0xbc
main.main()
	/Users/julien/src/k8s.io/kops/cmd/kops/main.go:31 +0x14
```

Here is my kops version
```
bash-3.2$ kops version
Version git-9e1b3dc
```

And cluster config file : 

```
bash-3.2$ cat clusterConf02.yaml
kind: Cluster
apiVersion: kops/v1alpha1
metadata:
  creationTimestamp: "2016-11-18T11:39:13Z"
  name: kopscluster02.xxxxxxxxxxxx
spec:
  adminAccess:
  - 0.0.0.0/0
  channel: stable
  cloudProvider: aws
  configBase: s3://kopscluster02xxxxxxxxxxx
  dnsZone: xxxxxxxxxxx
  etcdClusters:
  - etcdMembers:
    - name: eu-west-1a
      zone: eu-west-1a
    name: main
  - etcdMembers:
    - name: eu-west-1a
      zone: eu-west-1a
    name: events
  kubernetesVersion: v1.4.3
  masterPublicName: xxxxxxxxxx
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  zones:
  - cidr: 172.20.32.0/19
    name: eu-west-1a
```

Any ideas ?
