### ISSUE TITLE
found duplicate tasks with name "IAMRolePolicy/node-policyoverride"

### ISSUE THREAD

**Issue by yuha0** [kubernetes/kops#9693]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.18

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.6

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
1. create a cluster.
2. follow https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#use-existing-aws-instance-profiles to change instance profile on an existing IG.
3. Add a new IG with `kops create ig` without specifying an existing profile
4. Run `kops update cluster` will result in the error `found duplicate tasks with name "IAMRolePolicy/node-policyoverride"`

**5. What happened after the commands executed?**
kops exits with error `found duplicate tasks with name "IAMRolePolicy/node-policyoverride"`

**6. What did you expect to happen?**
kops makes the update successfully. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: use2kube.k8s.local
  name: igname
spec:
  associatePublicIp: false
  # iam:
  #   profile: arn:aws:iam::1234567890108:instance-profile/kops-custom-node-role
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200729
  machineType: t2.medium
  maxSize: 10
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: igname
  role: Node
  rootVolumeSize: 128
  subnets:
  - subnet-name
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

If I understand the guide for using existing profile (https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#use-existing-aws-instance-profiles) correctly, it is not possible to create a new IG with existing profile, instead, one must create IG without `.spec.iam.profile` in the first place, and edit the IG afterwards, which involves a `kops update` with `--lifecycle-overrides` argument. This is fine when we first create the cluster, but how can we add a new IG when some existing IGs are using custom profiles?
