### ISSUE TITLE
Missing support for c6g instances

### ISSUE THREAD

**Issue by RomanKisilenko** [kubernetes/kops#9707]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.17.0-alpha.1 (git-8df0d34)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Tried to deploy an instance group with c6g.xlarge instance type

**5. What happened after the commands executed?**
nodes-mt.instances[0].instanceType: Invalid value: "c6g.xlarge": machine type specified is invalid

**6. What did you expect to happen?**
Instance group created successfully

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-02T18:07:55Z"
  name: nodes-mt
  labels:
    kops.k8s.io/cluster: mycluster.tld
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: c6g.xlarge
  maxSize: 5
  minSize: 0
  mixedInstancesPolicy:
    instances:
      - c6g.xlarge
      - c5.xlarge
    onDemandBase: 0
    onDemandAboveBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-mt
  role: Node
  taints:
    - dedicated=mt:NoSchedule
  subnets:
  - us-east-2a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
