### ISSUE TITLE
Allow root volume encryption (on AWS)

### ISSUE THREAD

**Issue by MichaelJDrK** [kubernetes/kops#9728]
When you have to use encryption at rest, you currently have to create your own encrypted AMIs on AWS and use these as base image.

With AWS you can create EC2 instances directly from a public AMI with an encrypted root volume with you own KMS key. In Terraform, for example, you could do this:

```
resource "aws_instance" "foobar" {
  ...

  root_block_device {
    volume_size = 256
    encrypted = true
    kms_key_id = data.aws_kms_key.my-key.arn
  }
}
```

InstanceGroups should support this, too. Suggestion:

```
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: example.com
  name: nodes
spec:
  image: <random public image>
  role: Node
  ...
  rootVolumeEncryption: true
  rootVolumeEncryptionKey: <key ARN>
  ...
```
