### ISSUE TITLE
DynamicAuditing crashes kube-apiserver

### ISSUE THREAD

**Issue by antoinedeschenes** [kubernetes/kops#9747]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.18.0 (git-698bf974d8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.18.6

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
install kops 1.18.0
kops upgrade cluster
kops update cluster
kops rolling-update cluster

**5. What happened after the commands executed?**
kube-apiserver doesn't start

**6. What did you expect to happen?**
API starts responding after master provisions

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml

apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
spec:
  kubeAPIServer:
    auditDynamicConfiguration: true
    runtimeConfig:
      auditregistration.k8s.io/v1alpha1: "true"
  kubelet:
    featureGates:
      DynamicAuditing: "true"


```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
/var/log/containers/kube-apiserver... logfile contains the following error:
`Error: --audit-dynamic-configuration set, but DynamicAuditing feature gate is not enabled`

however kubelet is running with: `--feature-gates=DynamicAuditing=true`
