### ISSUE TITLE
KOPS (1.19 master) aws-iam-authenticator - clusterID value defaults to 'MasterPublicName' instead of 'clusterID' from the config map (mountedFile)

### ISSUE THREAD

**Issue by fred-vogt** [kubernetes/kops#9750]
@rifelpet - FYI

kubectl error:
```
error: You must be logged in to the server (Unauthorized)
```

aws-iam-authenticator server error:
```
could not verify token: sts getCallerIdentity failed: error from AWS (expected 200, got 403). 
Body:
{
  "Error": {
    "Code": "SignatureDoesNotMatch",
    "Message": "The request signature we calculated does not match the signature you provided. 
                Check your AWS Secret Access Key and signing method. 
                Consult the service documentation for details.",
    "Type": "Sender"
  },
  "RequestId": "uuid"
}
```

The only possible way to get this error message on the server is if different values for `x-k8s-aws-id` were used between token creation versus verification.

[upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template)
```yaml
{{- if or .Authentication.Aws.ClusterID (not (contains "MountedFile" .Authentication.Aws.BackendMode))}}
- --cluster-id={{ or .Authentication.Aws.ClusterID .MasterPublicName }}
{{- end }}
```

The [docs](https://kops.sigs.k8s.io/authentication/) use an example of:
```yaml
# cluster spec
spec:
  authentication:
    aws: {}

# CM
data:
  config.yaml: |
    clusterID: my-dev-cluster.example.com
```
However `clusterID: my-dev-cluster.example.com` would be ignored and `-i api.clusterID: my-dev-cluster.example.com` would be required in kube-config.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
- Unreleased master version:  `Version 1.19.0-alpha.2 (git-cdbb780)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
N/A.

**3. What cloud provider are you using?**
AWS.

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Spec:
```yaml
spec:
  authentication:
    aws: {}
```
aws-iam-authenticator CM:
```yaml
data:
  config.yaml: |
    clusterID: <cluster-fqdn>
```

**5. What happened after the commands executed?**
[aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) started with expilict `--cluster-id=<master-public-name>` which overrides the CM `cluster-id` as a mounted config file for [viper](https://github.com/spf13/viper) settings.

**6. What did you expect to happen?**
No `--cluster-id=` override on the [upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template](https://github.com/kubernetes/kops/blob/8edbfedffed3be4e10db1c6686cb4c3870fd83bc/upup/models/cloudup/resources/addons/authentication.aws/k8s-1.12.yaml.template#L135)

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A:  
```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
Can be worked around on master by explicitly setting `clusterID` in the cluster spec:
```yaml
spec:
  authentication:
    aws: 
      clusterID: <cluster-fqdn>
```
This prevents the value of `spec::masterPublicName` from overriding the value in the CM.

The value used for `clusterID` should be same value used in the "user" kubeconfig authenticator cli `-i` argument:
```yaml
users:
 -name: ...
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - token
        - -i
        - <cluster-fqdn>
      env:
        - name: AWS_PROFILE
          value: ...
```
