### ISSUE TITLE
[Feature Request]: Docker networking (ipTables, ipMasq) on Instance Group level. 

### ISSUE THREAD

**Issue by iusergii** [kubernetes/kops#9845]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Release 1.18 has changed default [iptables](https://kops.sigs.k8s.io/releases/1.18-notes/#breaking-changes) rules. According to [docs](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#networking) - to re-enable internet access for `docker run` containers  we need updated **cluster** level config :
```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: foo.dev
spec:
spec:
  docker:
    ipMasq: true
    ipTables: true 
```
I'd like to have an option to configure this rule on a specific **Instance Group** only.
