### ISSUE TITLE
[GCP] Problems updating instancetemplates when upgrading clusters

### ISSUE THREAD

**Issue by sokoow** [kubernetes/kops#9868]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Latest

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

default that is available as invoke "kops create"

**3. What cloud provider are you using?**

GCP

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster remote.k8s.local --zones us-east-1b --state gs://my-state/ --project my_project_id
kops update cluster remote.k8s.local  --state gs://my-state/ --yes
```

**5. What happened after the commands executed?**
I got repeated:

```
I0903 14:50:53.976940    2531 instancetemplate.go:224] We should be using NVME for GCE
W0903 14:50:53.977922    2531 executor.go:128] error running task "InstanceTemplate/nodes-remote-k8s-local" (8m44s remaining to succeed): Cannot apply changes to InstanceTemplate: *gcetasks.InstanceTemplate {"Name":null,"NamePrefix":null,"Lifecycle":null,"Network":null,"Tags":null,"Preemptible":null,"BootDiskImage":null,"BootDiskSizeGB":null,"BootDiskType":null,"CanIPForward":null,"Subnet":null,"AliasIPRanges":null,"Scopes":null,"ServiceAccounts":["default"],"Metadata":null,"MachineType":null,"ID":null}
I0903 14:50:53.977957    2531 executor.go:143] No progress made, sleeping before retrying 1 failed task(s)
```

note that this is mostly during modification of existing clusters. Clusters created from scratch seem ok. 

**6. What did you expect to happen?**

Get a working thing without errors and warnings (;))

**7. Please provide your cluster manifest.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  generation: 1
  name: remote.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudConfig:
    gceServiceAccount: default
  cloudProvider: gce
  configBase: gs://anthos-XXX/remote.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-central1-b
      name: b
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-central1-b
      name: b
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    apiAudiences:
    - api
    - istio-ca
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.8
  masterInternalName: api.internal.remote.k8s.local
  masterPublicName: api.remote.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: anthos-XXX
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-central1
    region: us-central1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.**
I'll eventually get to that...

**9. Anything else do we need to know?**
