### ISSUE TITLE
Using Terraform Destroy on the Infrastructure and then using Terraform Apply using the same state will break the API Server. 

### ISSUE THREAD

**Issue by ksummersill2** [kubernetes/kops#9946]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Used Chocalety and download KOps 1.18.0
Version 1.18.0 (git-698bf974d8)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}

**3. What cloud provider are you using?**
AWS - us-east-1

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops --v 3 create cluster --cloud $cloudType --image $ami --master-zones $masterZones --zones $zones --networking $network --node-count $nodeCount --master-size $masterNodeSize --node-size $nodeSize --topology $topology --name $name --state $state
kops update cluster --out=. --target=terraform  --name <clusterName> --state <State/s3 bucket>
terraform plan
terraform apply
terraform destroy
terraform apply

**5. What happened after the commands executed?**
The first time I execute the terraform script all works great. I never really understood how its implements the A records into the Hosted Zone. As I saw the IP address automatically gets populated for the API and the internal records. Recommend setting up a Route53 resource within terraform for this. 
The API Server after blowing the cluster away with terraform destroy and starting it back. 

**6. What did you expect to happen?**
I expected since the state is the same that it would allow me to destroy the cluster and started it back. However the API Server failed. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-09-15T19:07:00Z"
  name: prod.scaled-agile-devsecops.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://devsecops-bc-state/prod.scaled-agile-devsecops.com
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.8
  masterPublicName: api.prod.scaled-agile-devsecops.com
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Public
    zone: us-east-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-09-15T19:07:00Z"
  labels:
    kops.k8s.io/cluster: prod.scaled-agile-devsecops.com
  name: master-us-east-1a
spec:
  image: ami-06b06b52eb579522b
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-09-15T19:07:00Z"
  labels:
    kops.k8s.io/cluster: prod.scaled-agile-devsecops.com
  name: master-us-east-1b
spec:
  image: ami-06b06b52eb579522b
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-09-15T19:07:00Z"
  labels:
    kops.k8s.io/cluster: prod.scaled-agile-devsecops.com
  name: master-us-east-1c
spec:
  image: ami-06b06b52eb579522b
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-09-15T19:07:00Z"
  labels:
    kops.k8s.io/cluster: prod.scaled-agile-devsecops.com
  name: nodes
spec:
  image: ami-06b06b52eb579522b
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
Not sure what you want me to run for verbose as I am running this in terraform and terraform applies just find. 

**9. Anything else do we need to know?**
Logs for the failed API server
```
I0915 19:49:33.166291       1 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0915 19:49:33.168219       1 client.go:361] parsed scheme: "endpoint"
I0915 19:49:33.168257       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:4001  <nil> 0 <nil>}]
W0915 19:49:33.168565       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:4001  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
I0915 19:49:34.164282       1 client.go:361] parsed scheme: "endpoint"
I0915 19:49:34.164339       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:4001  <nil> 0 <nil>}]
W0915 19:49:34.164684       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:4001  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
W0915 19:49:34.169132       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:4001  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
```
