### ISSUE TITLE
Wrong ASG names passed to cluster-autoscaler

### ISSUE THREAD

**Issue by vixus0** [kubernetes/kops#9959]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.19.0-alpha.4 (git-1ecb9ab)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.0

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Setup cluster-autoscaler as described in the documentation: https://kops.sigs.k8s.io/cluster_spec/#cluster-autoscaler

**5. What happened after the commands executed?**
The following appears in the cluster-autoscaler logs:
```
I0917 09:29:08.662127       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
E0917 09:29:08.662181       1 node_instances_cache.go:164] Failed to get cloud provider node instance for node group nodes, error error while looking for instances of ASG: {nodes}
E0917 09:29:08.662194       1 node_instances_cache.go:164] Failed to get cloud provider node instance for node group spot, error error while looking for instances of ASG: {spot}
I0917 09:29:08.662200       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 38.791µs
I0917 09:29:09.206981       1 aws_manager.go:269] Refreshed ASG list, next refresh after 2020-09-17 09:30:09.206972764 +0000 UTC m=+448.946157116
E0917 09:29:09.207794       1 utils.go:119] Unable to build proper template node for nodes: unable to get first AvailabilityZone for ASG "nodes"
E0917 09:29:09.207812       1 static_autoscaler.go:271] Failed to get node infos for groups: unable to get first AvailabilityZone for ASG "nodes"
...
```

**6. What did you expect to happen?**
cluster-autoscaler is successfully able to find my ASGs and build a template.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
--- # cluster configuration
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: {{ .domain }}
spec:
  api:
    loadBalancer:
      type: Public
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  clusterAutoscaler:
    enabled: true
    skipNodesWithLocalStorage: true
    skipNodesWithSystemPods: true
  containerRuntime: docker
  etcdClusters:
    - name: main
      cpuRequest: 200m
      etcdMembers:
        - instanceGroup: master-eu-west-1a
          name: a
          encryptedVolume: true
        - instanceGroup: master-eu-west-1b
          name: b
          encryptedVolume: true
        - instanceGroup: master-eu-west-1c
          name: c
          encryptedVolume: true
      memoryRequest: 100Mi
      version: 3.2.24
    - name: events
      cpuRequest: 100m
      etcdMembers:
        - instanceGroup: master-eu-west-1a
          name: a
          encryptedVolume: true
        - instanceGroup: master-eu-west-1b
          name: b
          encryptedVolume: true
        - instanceGroup: master-eu-west-1c
          name: c
          encryptedVolume: true
      memoryRequest: 100Mi
      version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
    - 0.0.0.0/0
  kubernetesVersion: 1.19.0
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshKeyName: ""
  sshAccess:
    - 0.0.0.0/0
  subnets:
    - cidr: 172.20.32.0/19
      name: eu-west-1a
      type: Private
      zone: eu-west-1a
    - cidr: 172.20.64.0/19
      name: eu-west-1b
      type: Private
      zone: eu-west-1b
    - cidr: 172.20.96.0/19
      name: eu-west-1c
      type: Private
      zone: eu-west-1c
    - cidr: 172.20.0.0/22
      name: utility-eu-west-1a
      type: Utility
      zone: eu-west-1a
    - cidr: 172.20.4.0/22
      name: utility-eu-west-1b
      type: Utility
      zone: eu-west-1b
    - cidr: 172.20.8.0/22
      name: utility-eu-west-1c
      type: Utility
      zone: eu-west-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  hooks:
    - # iptables rules for kiam on calico
      name: kiam-iptables.service
      roles:
        - Node
      before:
        - docker.service
      manifest: |
        Type=oneshot
        ExecStart=/bin/sh -c '/sbin/iptables -t nat -A PREROUTING -d 169.254.169.254/32 \
                -i cali+ -p tcp -m tcp --dport 80 -j DNAT \
                --to-destination $(curl -s http://169.254.169.254/latest/meta-data/local-ipv4):8181'
        RemainAfterExit=yes
      requires:
        - network-online.target

--- # bastions instances
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: bastions
  labels:
    kops.k8s.io/cluster: {{ .domain }}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: t3a.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
    - eu-west-1a

--- # master eu-west-1a
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1a
  labels:
    kops.k8s.io/cluster: {{ .domain }}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1a
  role: Master
  subnets:
    - eu-west-1a

--- # master eu-west-1b
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1b
  labels:
    kops.k8s.io/cluster: {{ .domain }}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1b
  role: Master
  subnets:
    - eu-west-1b

--- # master eu-west-1c
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-eu-west-1c
  labels:
    kops.k8s.io/cluster: {{ .domain }}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m5a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-1c
  role: Master
  subnets:
    - eu-west-1c

--- # on-demand nodes
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
  labels:
    kops.k8s.io/cluster: {{ .domain }}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m5a.large
  maxSize: 3
  minSize: 3
  maxSurge: "100%"
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
    - eu-west-1a
    - eu-west-1b
    - eu-west-1c

--- # spot nodes
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: spot
  labels:
    kops.k8s.io/cluster: {{ .domain }}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716
  machineType: m5a.xlarge
  maxSize: 12
  minSize: 3
  maxSurge: "100%"
  nodeLabels:
    kops.k8s.io/instancegroup: spot
    node-role.kubernetes.io/spot: ""
  role: Node
  subnets:
    - eu-west-1a
    - eu-west-1b
    - eu-west-1c
  mixedInstancesPolicy:
    instances:
      - c4.xlarge
      - c5.xlarge
      - c5a.xlarge
      - m4.xlarge
      - m5.xlarge
      - m5a.xlarge
      - m5n.xlarge
      - t2.xlarge
      - t3.xlarge
      - t3a.xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
---

**9. Anything else do we need to know?**
I *think* the correct ASG names should be `<instancegroup name>.<cluster name>`. The [cluster-autoscaler deployment template](https://github.com/kubernetes/kops/blob/58092b5666727e55546ce85e668a7b8acbc88bff/upup/models/cloudup/resources/addons/cluster-autoscaler.addons.k8s.io/k8s-1.15.yaml.template#L160) only uses the InstanceGroup name.

The cluster-autoscaler documentation does suggest [using auto-discovery based on tags](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup) instead of explicitly passing ASG names. Since the ASGs are already tagged by kops, this should be doable.
