### ISSUE TITLE
Inaccurate instructions for enabling Cilium

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kops#9966]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.1

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster --name foo.k8s.local --node-count 1 --master-count 1 --zones us-west-2a --cloud aws
kops edit cluster --name foo.k8s.local # see details below
```
**5. What happened after the commands executed?**
`edit cluster` failed
**6. What did you expect to happen?**
`edit cluster` to succeed
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-09-17T20:04:28Z"
  generation: 2
  name: foo.k8s.local
spec:
  api:
    dns: {}
  authentication:
    aws:
      backendMode: CRD
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://tune-kops-state-us-west-2/foo.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 67.4.208.203/32
  kubernetesVersion: 1.19.0-rc.1
  masterInternalName: api.internal.foo.k8s.local
  masterPublicName: api.foo.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      hubble: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 67.4.208.203/32
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The [docs](https://kops.sigs.k8s.io/networking/cilium/#installing-cilium-on-a-new-cluster) mention that enabling cilium just requires:

```yaml
spec:
  networking:
    cilium: {}
```

but the following error is reported when using this cluster spec:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
# ...
#     networkCIDR: 172.20.0.0/16
#     networking:
# -     cilium:
# +     cilium: {}
# -       hubble: {}
#     nonMasqueradeCIDR: 100.64.0.0/10
#     sshAccess:
# ...
```

It seems like we should either make the hubble field optional by making it a pointer, or update the docs to include `hubble: {}`
